/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import RenewalGeometry.Spectralization.FiniteRealEvenSpectralizationExact
/-!
# Finite real differential data and the austere unit zero-mode

This file covers `def:finite-real-differential` and `prop:austere-zero-mode`
of `predictive_spectral_geometry`.

* `FiniteRealDifferentialDatum` is the compiler packet of
  `FiniteDifferentialOccurrenceCompiler` (Hilbert bimodule with commuting
  star-adjoint actions, antiunitary involution reversing the actions, and a
  linear `δ`) whose `δ` is a star-bimodule derivation: `δ(1) = 0`, Leibniz,
  and `C δ(a) = δ(a^*)`.  The clause `C(a ξ b) = b^* C(ξ) a^*` is
  `reverse_bimodule`, and the retained source-minimal carrier is
  `sourceMinimalCarrier` (the range of the universal factor map).
* `austere_unit_zero_mode` is `prop:austere-zero-mode` in the orthonormal
  coordinates of `FiniteRealEvenSpectralizationExact`: the Hodge–Dirac
  block matrix kills the coordinate vector of `(1, 0)`, hence has zero
  determinant and is never invertible.
-/

open Matrix
open scoped InnerProductSpace

namespace RenewalGeometry
namespace AustereUnitZeroMode

open FiniteDifferentialOccurrenceCompiler

noncomputable section

section Datum

variable {n : ℕ} {A K : Type*}
  [NormedRing A] [NormedAlgebra ℂ A]
  [StarRing A] [StarModule ℂ A]
  [NormedAddCommGroup K] [InnerProductSpace ℂ K]

/-- **`def:finite-real-differential`.**  A finite real differential datum on
a finite-dimensional star algebra `A`: a compiler packet (Hilbert
`A`-bimodule `K` with commuting star-adjoint left and right actions, an
antiunitary involution `C` reversing the actions, and a complex-linear
`δ : A → K`) whose `δ` satisfies `δ(1) = 0`, the Leibniz rule
`δ(ab) = a δ(b) + δ(a) b` and the star compatibility `C δ(a) = δ(a^*)`. -/
def FiniteRealDifferentialDatum (n : ℕ) (A K : Type*)
    [NormedRing A] [NormedAlgebra ℂ A] [StarRing A] [StarModule ℂ A]
    [NormedAddCommGroup K] [InnerProductSpace ℂ K] : Type _ :=
  {P : Packet n A K // P.IsStarBimoduleDerivation}

namespace FiniteRealDifferentialDatum

variable (D : FiniteRealDifferentialDatum n A K)

/-- The underlying compiler packet. -/
abbrev packet : Packet n A K := D.1

/-- The packet of a datum is a star-bimodule derivation. -/
theorem isStarBimoduleDerivation : D.packet.IsStarBimoduleDerivation := D.2

/-- `δ(1) = 0`. -/
theorem delta_one : D.packet.delta 1 = 0 := D.2.1

/-- The Leibniz rule `δ(ab) = a δ(b) + δ(a) b`. -/
theorem leibniz (a b : A) :
    D.packet.delta (a * b) =
      D.packet.left a (D.packet.delta b) + D.packet.right b (D.packet.delta a) :=
  D.2.2.1 a b

/-- Star compatibility `C δ(a) = δ(a^*)`. -/
theorem delta_star (a : A) :
    D.packet.delta (star a) = D.packet.reverse (D.packet.delta a) :=
  D.2.2.2 a

/-- The antiunitary involution reverses the bimodule actions:
`C(a ξ b) = b^* C(ξ) a^*`. -/
theorem reverse_bimodule (a b : A) (ξ : K) :
    D.packet.reverse (D.packet.left a (D.packet.right b ξ)) =
      D.packet.left (star b) (D.packet.right (star a) (D.packet.reverse ξ)) := by
  rw [D.packet.reverse_left, D.packet.reverse_right]
  have h := (D.packet.commute_actions (star b) (star a)).eq
  have h' := congrArg (fun f : Module.End ℂ K => f (D.packet.reverse ξ)) h
  simp only [Module.End.mul_apply] at h'
  exact h'.symm

/-- `C` is antiunitary. -/
theorem reverse_inner (ξ η : K) :
    ⟪D.packet.reverse ξ, D.packet.reverse η⟫_ℂ = ⟪η, ξ⟫_ℂ :=
  D.packet.reverse_inner ξ η

/-- `C` is an involution. -/
theorem reverse_involutive : Function.Involutive D.packet.reverse :=
  D.packet.reverse_involutive

/-- Only the bimodule generated by `δ(A)` is retained: the source-minimal
carrier is the range of the universal factor map `T_δ`. -/
abbrev sourceMinimalCarrier : Submodule ℂ K := LinearMap.range D.packet.universalFactor

/-- The source-minimal quotient of universal one-forms is the retained carrier. -/
def sourceMinimalEquiv :
    (UniversalOneForm A ⧸ LinearMap.ker D.packet.universalFactor) ≃ₗ[ℂ]
      D.sourceMinimalCarrier :=
  D.packet.sourceMinimalEquivRange

/-- The induced derivation `∂ a = [d_u a]` factors back to `δ`. -/
theorem universalFactor_differential (a : A) :
    D.packet.universalFactor (universalDifferential a) = D.packet.delta a := by
  have h := D.packet.universalFactor_comp_differential D.2
  exact LinearMap.congr_fun h a

/-- The induced derivation kills the unit: `∂ 1 = 0`. -/
theorem universalFactor_differential_one :
    D.packet.universalFactor (universalDifferential (1 : A)) = 0 := by
  rw [universalFactor_differential, delta_one]

end FiniteRealDifferentialDatum

end Datum

section Coordinates

open FiniteRealEvenSpectralizationExact

variable {A I J : Type*} [Ring A] [Algebra ℂ A] [StarRing A]
  [StarModule ℂ A] [Fintype I] [Fintype J]
  [DecidableEq I] [DecidableEq J]

variable (P : FiniteRealEvenSpectralizationExact.Packet (A := A) (I := I) (J := J))

/-- The coordinate vector of `(1, 0) ∈ H₀ ⊕ H₁(δ)`. -/
def unitZeroForm : P.HIndex → ℂ := Sum.elim P.unitVector 0

theorem unitZeroForm_ne_zero (hu : P.unitVector ≠ 0) : unitZeroForm P ≠ 0 := by
  intro h
  apply hu
  funext i
  have := congrFun h (Sum.inl i)
  simpa [unitZeroForm] using this

/-- `eq:austere-zero-mode`: `D(1, 0) = 0` once the derivation kills the
unit (`∂ 1 = 0`, i.e. `differential *ᵥ unitVector = 0`). -/
theorem dirac_unitZeroForm (h1 : P.differential *ᵥ P.unitVector = 0) :
    P.dirac *ᵥ unitZeroForm P = 0 := by
  unfold unitZeroForm Packet.dirac
  rw [Matrix.fromBlocks_mulVec]
  simp [h1]

theorem dirac_det_eq_zero (h1 : P.differential *ᵥ P.unitVector = 0)
    (hu : P.unitVector ≠ 0) : P.dirac.det = 0 := by
  rw [← Matrix.exists_mulVec_eq_zero_iff]
  exact ⟨unitZeroForm P, unitZeroForm_ne_zero P hu, dirac_unitZeroForm P h1⟩

theorem not_isUnit_dirac (h1 : P.differential *ᵥ P.unitVector = 0)
    (hu : P.unitVector ≠ 0) : ¬ IsUnit P.dirac := by
  rw [Matrix.isUnit_iff_isUnit_det, dirac_det_eq_zero P h1 hu]
  exact not_isUnit_zero

/-- **`prop:austere-zero-mode`.**  For a coordinate packet whose derivation
kills the unit (`∂ 1 = 0`, the unit clause of
`def:finite-real-differential`) with nonzero unit vector, the Hodge–Dirac
matrix of `thm:finite-spectralization` satisfies `D(1, 0) = 0`; consequently
it has a nonzero kernel vector, zero determinant, and is never invertible. -/
theorem austere_unit_zero_mode (h1 : P.differential *ᵥ P.unitVector = 0)
    (hu : P.unitVector ≠ 0) :
    P.dirac *ᵥ unitZeroForm P = 0 ∧ unitZeroForm P ≠ 0 ∧
      P.dirac.det = 0 ∧ ¬ IsUnit P.dirac :=
  ⟨dirac_unitZeroForm P h1, unitZeroForm_ne_zero P hu, dirac_det_eq_zero P h1 hu,
    not_isUnit_dirac P h1 hu⟩

end Coordinates

end

end AustereUnitZeroMode
end RenewalGeometry
