/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The pointer-sector Born rule (wavefunction, Phase 2)

`thm:pointer-born`: under the predictively-sufficient pointer-record
assumptions, the unique normalized additive probability measure on
the (finite, atomic) Boolean algebra generated by the pointer
records is `p_i = Tr(E_i ρ)`.

* `additive_measure_unique` — a finitely additive set function on
  the Boolean algebra generated by finitely many atoms is uniquely
  determined by its atom values: `μ(S) = Σ_{i∈S} μ({i})`;
* `born_weights_additive`, `born_weights_normalized` — the Born
  weights `w_i = Tr(E_i ρ)` are exactly such an assignment: they
  aggregate by trace linearity (`Σ_{i∈S} Tr(E_iρ) = Tr((Σ E_i)ρ)`)
  and normalize to `Tr ρ` when `Σ E_i = 1`;
* `pointer_born` — the combination: every normalized additive
  measure with the record atom weights is
  `μ(S) = Tr((Σ_{i∈S} E_i)ρ)`.

The Lüders conditional state for projective records is the
already-formalized sector machinery
(`NCG.central_expectation_decomposes`, `NCG.lueders_kraus_sum`).
-/

namespace NCG

open Matrix

/-- Uniqueness of the additive extension: a finitely additive set
function on the powerset Boolean algebra is determined by its
atoms. -/
theorem additive_measure_unique {ι : Type*} [DecidableEq ι]
    (mu : Finset ι → ℝ)
    (hadd : ∀ s t, Disjoint s t → mu (s ∪ t) = mu s + mu t) :
    ∀ s : Finset ι, mu s = ∑ i ∈ s, mu {i} := by
  intro s
  induction s using Finset.induction_on with
  | empty =>
    have h := hadd ∅ ∅ (Finset.disjoint_empty_left ∅)
    simp only [Finset.empty_union] at h
    have h0 : mu ∅ = 0 := by linarith
    rw [h0, Finset.sum_empty]
  | insert i s hi ih =>
    have hdisj : Disjoint ({i} : Finset ι) s := by
      rw [Finset.disjoint_singleton_left]
      exact hi
    have h1 : insert i s = {i} ∪ s := by
      rw [Finset.singleton_union]
    rw [Finset.sum_insert hi, ← ih, h1, hadd _ _ hdisj]

/-- Born weights aggregate by trace linearity:
`Σ_{i∈S} Tr(E_iρ) = Tr((Σ_{i∈S} E_i)ρ)`. -/
theorem born_weights_additive {ι n : Type*} [Fintype n]
    (E : ι → Matrix n n ℂ) (rho : Matrix n n ℂ) (s : Finset ι) :
    ∑ i ∈ s, ((E i) * rho).trace = ((∑ i ∈ s, E i) * rho).trace := by
  rw [Finset.sum_mul, Matrix.trace_sum]

/-- Born weights are normalized: with `Σ E_i = 1` (a resolved record
family) the total weight is `Tr ρ` (`= 1` on states). -/
theorem born_weights_normalized {ι n : Type*} [Fintype ι] [Fintype n]
    [DecidableEq n] (E : ι → Matrix n n ℂ) (rho : Matrix n n ℂ)
    (hres : ∑ i, E i = 1) :
    ∑ i, ((E i) * rho).trace = rho.trace := by
  rw [born_weights_additive, hres, one_mul]

/-- `thm:pointer-born`: the unique normalized additive probability
measure on the Boolean algebra generated by the pointer records with
the record weights `μ({i}) = Tr(E_iρ)` is the Born assignment
`μ(S) = Tr((Σ_{i∈S} E_i)ρ)`; for projective records the associated
conditional state is the Lüders state (see
`NCG.central_expectation_decomposes`). -/
theorem pointer_born {ι n : Type*} [DecidableEq ι] [Fintype n]
    (E : ι → Matrix n n ℂ) (rho : Matrix n n ℂ)
    (mu : Finset ι → ℝ)
    (hadd : ∀ s t, Disjoint s t → mu (s ∪ t) = mu s + mu t)
    (hatom : ∀ i, (mu {i} : ℂ) = ((E i) * rho).trace) :
    ∀ s : Finset ι, (mu s : ℂ) = ((∑ i ∈ s, E i) * rho).trace := by
  intro s
  rw [additive_measure_unique mu hadd s]
  rw [← born_weights_additive]
  push_cast
  exact Finset.sum_congr rfl fun i _ => hatom i

end NCG
