/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Predictive.DerivedPredictiveCarrierUniversalExact
import RenewalGeometry.Commutant.IntrinsicRegularTrace
import RenewalGeometry.Operational.MinimalNaturality

/-!
# The finite Renewal Grand Tensor and its canonical reconstruction

Paper `predictive_spectral_geometry`, labels `def:ncg-grand-tensor` and
`prop:ncg-grand-tensor-reconstruction`.

## Objects (`def:ncg-grand-tensor`)

* `historyAlgebra gen` — the represented history algebra
  `A^hist ⊆ B(M)` (`eq:ncg-history-algebra`): the star subalgebra of
  `Matrix M M ℂ` generated by a family `gen : Γ → Matrix M M ℂ` of represented
  operators on a finite support-minimal carrier `M` (in the paper: the
  represented predictive-state projections, the mixed forward maps and their
  Hilbert–Schmidt reverses).
* `wordOp gen w` — the represented operator `[w]` of a finite history word.
* `wordGram gen v w = τ̂_reg([v]^* [w])` — the word-Gram kernel
  `eq:ncg-word-gram`, with `τ̂_reg` the normalized regular trace
  `eq:ncg-grand-regular-trace` of `A^hist` (`RenewalGeometry.normalizedRegularTrace`);
  `wordGramLevel gen r` is its depth-`r` layer `K_{X,r}`.
* `GrandTensor` — the bundle `(A^hist, {K_{X,r}}, Z^min)` of
  `eq:ncg-grand-tensor`, with `Z^min` the future-minimal carrier
  `PredictiveSystem.MinimalCarrier` of the operational process.

## Reconstruction (`prop:ncg-grand-tensor-reconstruction`)

* Clause (i) is `DerivedPredictiveCarrierUniversalExact` (cited in
  `grand_tensor_reconstruction`).
* Clause (ii): support-minimal Gram factorizations of the same positive process
  data are unitarily equivalent (`gram_unitary`, cited) and the unitary
  intertwines the represented shift operators (`intertwine_of_surjective`);
  unitarily conjugate generator families generate history algebras related by
  a represented `*`-isomorphism `x ↦ U x U^*` (`conjEquiv`).
* Clause (iii): the normalized regular trace and the whole word-Gram hierarchy
  are invariant under that isomorphism (`wordGram_conj`).
* Clause (iv): the bundled statement `grand_tensor_reconstruction`.

What is *not* formalized is the tomographic passage from finite multitime
intervention tables to the positive process matrices; the generator family on
the support-minimal carrier is taken as data.
-/

open Matrix

namespace RenewalGeometry
namespace FiniteGrandTensor

open DerivedPredictiveCarrierUniversal

variable {M : Type*} [Fintype M] [DecidableEq M] {Γ : Type*}

/-- The represented history algebra `A^hist` (`eq:ncg-history-algebra`): the
star subalgebra of `B(M)` generated by the represented operators. -/
def historyAlgebra (gen : Γ → Matrix M M ℂ) : StarSubalgebra ℂ (Matrix M M ℂ) :=
  StarAlgebra.adjoin ℂ (Set.range gen)

theorem gen_mem_historyAlgebra (gen : Γ → Matrix M M ℂ) (γ : Γ) :
    gen γ ∈ historyAlgebra gen :=
  StarAlgebra.subset_adjoin ℂ _ ⟨γ, rfl⟩

/-- The represented operator `[w]` of a finite history word. -/
def wordOp (gen : Γ → Matrix M M ℂ) : List Γ → Matrix M M ℂ
  | [] => 1
  | γ :: w => gen γ * wordOp gen w

@[simp] theorem wordOp_nil (gen : Γ → Matrix M M ℂ) : wordOp gen [] = 1 := rfl

@[simp] theorem wordOp_cons (gen : Γ → Matrix M M ℂ) (γ : Γ) (w : List Γ) :
    wordOp gen (γ :: w) = gen γ * wordOp gen w := rfl

/-- Represented words compose: concatenation of histories is multiplication. -/
theorem wordOp_append (gen : Γ → Matrix M M ℂ) (v w : List Γ) :
    wordOp gen (v ++ w) = wordOp gen v * wordOp gen w := by
  induction v with
  | nil => simp
  | cons γ v ih => simp [ih, Matrix.mul_assoc]

theorem wordOp_mem (gen : Γ → Matrix M M ℂ) (w : List Γ) :
    wordOp gen w ∈ historyAlgebra gen := by
  induction w with
  | nil => exact one_mem _
  | cons γ w ih => exact mul_mem (gen_mem_historyAlgebra gen γ) ih

/-- The history algebra is finite dimensional. -/
instance instFiniteDimensional (gen : Γ → Matrix M M ℂ) :
    FiniteDimensional ℂ (historyAlgebra gen) :=
  FiniteDimensional.of_injective (historyAlgebra gen).subtype.toAlgHom.toLinearMap
    Subtype.val_injective

/-- The element `[v]^* [w]` of the history algebra. -/
def wordPair (gen : Γ → Matrix M M ℂ) (v w : List Γ) : historyAlgebra gen :=
  ⟨star (wordOp gen v) * wordOp gen w,
    mul_mem (star_mem (wordOp_mem gen v)) (wordOp_mem gen w)⟩

/-- The word-Gram kernel `K_X(v, w) = τ̂_reg([v]^* [w])` (`eq:ncg-word-gram`). -/
noncomputable def wordGram (gen : Γ → Matrix M M ℂ) (v w : List Γ) : ℂ :=
  normalizedRegularTrace (historyAlgebra gen) (wordPair gen v w)

/-- Words of length at most `r`. -/
def Words (Γ : Type*) (r : ℕ) : Type _ := {w : List Γ // w.length ≤ r}

/-- The depth-`r` word-Gram layer `K_{X,r}` (`eq:ncg-word-gram`). -/
noncomputable def wordGramLevel (gen : Γ → Matrix M M ℂ) (r : ℕ) (v w : Words Γ r) : ℂ :=
  wordGram gen v.1 w.1

/-- **Definition `def:ncg-grand-tensor`.**  The finite Renewal Grand Tensor
`(A^hist, {K_{X,r}}_r, Z^min)` of an operational process: the complete
finite-future predictive law (whose quotient `MinimalCarrier` is `Z^min`)
together with the represented generator family on a finite support-minimal
carrier, from which `A^hist = historyAlgebra gen` and the Gram hierarchy
`K_{X,r} = wordGramLevel gen r` are derived. -/
structure GrandTensor (History Letter M Γ : Type*) where
  /-- The complete finite-future predictive law of the process. -/
  system : PredictiveSystem History Letter
  /-- The represented generators on the support-minimal carrier. -/
  gen : Γ → Matrix M M ℂ

namespace GrandTensor

variable {History Letter : Type*} (T : GrandTensor History Letter M Γ)

/-- `Z^min`: the future-minimal carrier. -/
abbrev minimalCarrier := T.system.MinimalCarrier

/-- `A^hist`: the represented history algebra. -/
def historyAlgebra : StarSubalgebra ℂ (Matrix M M ℂ) := FiniteGrandTensor.historyAlgebra T.gen

/-- `τ̂_{X,reg}`: the normalized regular trace of `A^hist`. -/
noncomputable def regularTrace : FiniteGrandTensor.historyAlgebra T.gen →ₗ[ℂ] ℂ :=
  normalizedRegularTrace (FiniteGrandTensor.historyAlgebra T.gen)

/-- `K_{X,r}`: the depth-`r` word-Gram layer. -/
noncomputable def wordGram (r : ℕ) : Words Γ r → Words Γ r → ℂ := wordGramLevel T.gen r

end GrandTensor

/-! ## Unitary conjugation of generator families -/

/-- The generator family conjugated by `U`: `γ ↦ U (gen γ) U^*`. -/
def conj (gen : Γ → Matrix M M ℂ) (U : Matrix M M ℂ) : Γ → Matrix M M ℂ :=
  fun γ => U * gen γ * star U

theorem star_mul_mul_cancel {U : Matrix M M ℂ} (hU : star U * U = 1) (X : Matrix M M ℂ) :
    star U * (U * X) = X := by
  rw [← Matrix.mul_assoc, hU, Matrix.one_mul]

theorem mul_star_mul_cancel {U : Matrix M M ℂ} (hU : star U * U = 1) (X : Matrix M M ℂ) :
    U * (star U * X) = X := by
  rw [← Matrix.mul_assoc, mul_eq_one_comm.mp hU, Matrix.one_mul]

/-- Represented words of the conjugated family are the conjugated words. -/
theorem wordOp_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ} (hU : star U * U = 1)
    (w : List Γ) : wordOp (conj gen U) w = U * wordOp gen w * star U := by
  induction w with
  | nil => simp [mul_eq_one_comm.mp hU]
  | cons γ w ih =>
      rw [wordOp_cons, wordOp_cons, ih]
      simp only [conj, Matrix.mul_assoc]
      rw [star_mul_mul_cancel hU]

/-- The conjugation star-automorphism of `B(M)` by a unitary `U`. -/
noncomputable def conjHom {U : Matrix M M ℂ} (hU : star U * U = 1) :
    Matrix M M ℂ →⋆ₐ[ℂ] Matrix M M ℂ :=
  (Unitary.conjStarAlgAut ℂ (Matrix M M ℂ)
    ⟨U, Unitary.mem_iff.mpr ⟨hU, mul_eq_one_comm.mp hU⟩⟩).toStarAlgHom

theorem conjHom_apply {U : Matrix M M ℂ} (hU : star U * U = 1) (x : Matrix M M ℂ) :
    conjHom hU x = U * x * star U := rfl

/-- The history algebra of the conjugated family is the image of the history
algebra under conjugation. -/
theorem historyAlgebra_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) :
    historyAlgebra (conj gen U) = (historyAlgebra gen).map (conjHom hU) := by
  unfold historyAlgebra
  rw [StarAlgHom.map_adjoin]
  congr 1
  ext x
  constructor
  · rintro ⟨γ, rfl⟩
    exact ⟨gen γ, ⟨γ, rfl⟩, rfl⟩
  · rintro ⟨y, ⟨γ, rfl⟩, rfl⟩
    exact ⟨γ, rfl⟩

theorem mem_historyAlgebra_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) {x : Matrix M M ℂ} (hx : x ∈ historyAlgebra gen) :
    U * x * star U ∈ historyAlgebra (conj gen U) := by
  rw [historyAlgebra_conj gen hU]
  exact StarSubalgebra.mem_map.mpr ⟨x, hx, rfl⟩

theorem mem_historyAlgebra_of_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) {y : Matrix M M ℂ} (hy : y ∈ historyAlgebra (conj gen U)) :
    star U * y * U ∈ historyAlgebra gen := by
  rw [historyAlgebra_conj gen hU] at hy
  obtain ⟨x, hx, rfl⟩ := StarSubalgebra.mem_map.mp hy
  rw [conjHom_apply]
  have : star U * (U * x * star U) * U = x := by
    simp only [Matrix.mul_assoc]
    rw [star_mul_mul_cancel hU, hU, Matrix.mul_one]
  rw [this]
  exact hx

/-- **Represented `*`-isomorphism** (clause (ii) of
`prop:ncg-grand-tensor-reconstruction`): unitarily conjugate generator families
generate history algebras identified by `x ↦ U x U^*`. -/
noncomputable def conjEquiv (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) :
    historyAlgebra gen ≃⋆ₐ[ℂ] historyAlgebra (conj gen U) where
  toFun x := ⟨U * x * star U, mem_historyAlgebra_conj gen hU x.2⟩
  invFun y := ⟨star U * y * U, mem_historyAlgebra_of_conj gen hU y.2⟩
  left_inv x := by
    apply Subtype.ext
    change star U * (U * x * star U) * U = x
    simp only [Matrix.mul_assoc]
    rw [star_mul_mul_cancel hU, hU, Matrix.mul_one]
  right_inv y := by
    apply Subtype.ext
    change U * (star U * y * U) * star U = y
    simp only [Matrix.mul_assoc]
    rw [mul_star_mul_cancel hU, mul_eq_one_comm.mp hU, Matrix.mul_one]
  map_mul' x y := by
    apply Subtype.ext
    change U * (x * y) * star U = (U * x * star U) * (U * y * star U)
    simp only [Matrix.mul_assoc]
    rw [star_mul_mul_cancel hU]
  map_add' x y := by
    apply Subtype.ext
    change U * (x + y) * star U = U * x * star U + U * y * star U
    rw [Matrix.mul_add, Matrix.add_mul]
  map_smul' c x := by
    apply Subtype.ext
    change U * (c • (x : Matrix M M ℂ)) * star U = c • (U * x * star U)
    rw [Matrix.mul_smul, Matrix.smul_mul]
  map_star' x := by
    apply Subtype.ext
    change U * star (x : Matrix M M ℂ) * star U = star (U * x * star U)
    rw [star_mul, star_mul, star_star, Matrix.mul_assoc]

theorem coe_conjEquiv_apply (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) (x : historyAlgebra gen) :
    (conjEquiv gen hU x : Matrix M M ℂ) = U * x * star U := rfl

/-- The normalized regular trace is intrinsic: it is transported by the
represented `*`-isomorphism (clause (iii)). -/
theorem normalizedRegularTrace_conjEquiv (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) (x : historyAlgebra gen) :
    normalizedRegularTrace (historyAlgebra (conj gen U)) (conjEquiv gen hU x) =
      normalizedRegularTrace (historyAlgebra gen) x :=
  normalizedRegularTrace_algEquiv (conjEquiv gen hU).toAlgEquiv x

/-- The represented `*`-isomorphism carries `[v]^*[w]` to `[v]'^*[w]'`. -/
theorem conjEquiv_wordPair (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) (v w : List Γ) :
    conjEquiv gen hU (wordPair gen v w) = wordPair (conj gen U) v w := by
  apply Subtype.ext
  rw [coe_conjEquiv_apply]
  change U * (star (wordOp gen v) * wordOp gen w) * star U =
    star (wordOp (conj gen U) v) * wordOp (conj gen U) w
  rw [wordOp_conj gen hU, wordOp_conj gen hU, star_mul, star_mul, star_star]
  simp only [Matrix.mul_assoc]
  rw [star_mul_mul_cancel hU]

/-- **Invariance of the word-Gram hierarchy** (clause (iii) of
`prop:ncg-grand-tensor-reconstruction`). -/
theorem wordGram_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) (v w : List Γ) :
    wordGram (conj gen U) v w = wordGram gen v w := by
  unfold wordGram
  rw [← conjEquiv_wordPair gen hU, normalizedRegularTrace_conjEquiv]

theorem wordGramLevel_conj (gen : Γ → Matrix M M ℂ) {U : Matrix M M ℂ}
    (hU : star U * U = 1) (r : ℕ) :
    wordGramLevel (conj gen U) r = wordGramLevel gen r := by
  funext v w
  exact wordGram_conj gen hU v.1 w.1

/-! ## Support-minimal realizations of the same process data -/

/-- A unitary intertwiner of two support-minimal realization stacks also
intertwines their represented shift operators: if `Ω N = N'`, `T N = N S` and
`T' N' = N' S` with the columns of `N` spanning the carrier (support
minimality), then `Ω T = T' Ω`, i.e. `T' = Ω T Ω^*`.  Together with
`RenewalGeometry.gram_unitary` (equal Grams over a spanning stack give a
unitary `Ω` with `Ω N = N'`) this is the unitary equivalence of support-minimal
realizations of the same positive process data used in clause (ii). -/
theorem intertwine_of_surjective {q : Type*} [Fintype q]
    (N N' : Matrix M q ℂ) (T T' Ω : Matrix M M ℂ) (S : Matrix q q ℂ)
    (hsurj : Function.Surjective N.mulVec) (hΩ : Ω * N = N')
    (hT : T * N = N * S) (hT' : T' * N' = N' * S) :
    Ω * T = T' * Ω := by
  have hXN : (Ω * T - T' * Ω) * N = 0 := by
    rw [Matrix.sub_mul, Matrix.mul_assoc, hT, ← Matrix.mul_assoc, hΩ, Matrix.mul_assoc, hΩ,
      hT', sub_self]
  have hzero : Ω * T - T' * Ω = 0 := by
    ext i j
    obtain ⟨v, hv⟩ := hsurj (Pi.single j 1)
    have h := congrFun (congrArg (fun A : Matrix M q ℂ => A *ᵥ v) hXN) i
    simp only [Matrix.zero_mulVec, Pi.zero_apply, ← Matrix.mulVec_mulVec, hv,
      Matrix.mulVec_single_one, Matrix.col_apply] at h
    simpa using h
  exact sub_eq_zero.mp hzero

/-- **Unitary equivalence of support-minimal realizations** (clause (ii) of
`prop:ncg-grand-tensor-reconstruction`).  Two support-minimal realization
stacks `N, N'` (columns: realization vectors of the process words) with the
same positive process Gram `Nᴴ N = N'ᴴ N'`, carrying represented operators
`T a`, `T' a` that implement the same word shifts `S a`, are related by a
unitary `Ω` with `Ω N = N'` and `T' = Ω T Ω^*`; hence they present the same
Grand Tensor (`grand_tensor_reconstruction`). -/
theorem exists_unitary_intertwiner {q Λ : Type*} [Fintype q]
    (N N' : Matrix M q ℂ) (T T' : Λ → Matrix M M ℂ) (S : Λ → Matrix q q ℂ)
    (hgram : Nᴴ * N = N'ᴴ * N') (hsurj : Function.Surjective N.mulVec)
    (hT : ∀ a, T a * N = N * S a) (hT' : ∀ a, T' a * N' = N' * S a) :
    ∃ Ω : Matrix M M ℂ, star Ω * Ω = 1 ∧ Ω * N = N' ∧ T' = conj T Ω := by
  obtain ⟨Ω, hΩ, hΩN⟩ := RenewalGeometry.gram_unitary N' N hgram hsurj
  have hstar : star Ω * Ω = 1 := by
    rw [Matrix.star_eq_conjTranspose]
    exact hΩ
  refine ⟨Ω, hstar, hΩN, ?_⟩
  funext a
  have hint : Ω * T a = T' a * Ω :=
    intertwine_of_surjective N N' (T a) (T' a) Ω (S a) hsurj hΩN (hT a) (hT' a)
  unfold conj
  rw [hint, Matrix.mul_assoc, mul_eq_one_comm.mp hstar, Matrix.mul_one]

/-- The Grand Tensor presented on a unitarily conjugate support-minimal
carrier realization. -/
def GrandTensor.conj {History Letter : Type*} (T : GrandTensor History Letter M Γ)
    (U : Matrix M M ℂ) : GrandTensor History Letter M Γ :=
  ⟨T.system, FiniteGrandTensor.conj T.gen U⟩

/-- **Proposition `prop:ncg-grand-tensor-reconstruction`.**  For a Grand
Tensor `T` and a unitary `U` (the freedom between two support-minimal
realizations of the same positive process data, cf. `gram_unitary` and
`intertwine_of_surjective`):

(i) the future-minimal carrier `Z^min` receives a unique surjection from every
reachable deterministic realization, intertwining branch laws and occurring
updates (`DerivedPredictiveCarrierUniversalExact`);

(ii) the represented history algebras of `T` and of its conjugate presentation
are related by the represented `*`-isomorphism `x ↦ U x U^*`;

(iii) the normalized regular trace is transported by that isomorphism and the
whole word-Gram hierarchy `K_{X,r}` is invariant;

(iv) consequently the Grand Tensor components `(A^hist, {K_{X,r}}, Z^min)` are
fixed up to their natural isomorphisms. -/
theorem grand_tensor_reconstruction {History Letter : Type*}
    (T : GrandTensor History Letter M Γ) {U : Matrix M M ℂ} (hU : star U * U = 1) :
    (∀ {State : Type*} (R : T.system.Realization State),
      Function.Surjective (PredictiveSystem.Realization.toMinimal T.system R) ∧
      (∀ f : State → T.system.MinimalCarrier,
        (∀ h, f (R.stateOf h) = Quotient.mk T.system.futureSetoid h) →
          f = PredictiveSystem.Realization.toMinimal T.system R) ∧
      (∀ s a, T.system.minimalBranch a
          (PredictiveSystem.Realization.toMinimal T.system R s) = R.rate s a) ∧
      (∀ s a, R.rate s a ≠ 0 →
        PredictiveSystem.Realization.toMinimal T.system R (R.update s a) =
          T.system.minimalUpdate a (PredictiveSystem.Realization.toMinimal T.system R s))) ∧
    (∃ e : T.historyAlgebra ≃⋆ₐ[ℂ] (T.conj U).historyAlgebra,
      (∀ x, (e x : Matrix M M ℂ) = U * x * star U) ∧
      ∀ x, (T.conj U).regularTrace (e x) = T.regularTrace x) ∧
    (∀ r, (T.conj U).wordGram r = T.wordGram r) ∧
    (T.conj U).minimalCarrier = T.minimalCarrier := by
  refine ⟨fun R => ⟨PredictiveSystem.Realization.toMinimal_surjective T.system R,
      PredictiveSystem.Realization.toMinimal_unique T.system R,
      PredictiveSystem.Realization.toMinimal_branch T.system R,
      fun s a ha => PredictiveSystem.Realization.toMinimal_update_of_occurs T.system R s a ha⟩,
    ⟨conjEquiv T.gen hU, fun x => rfl, fun x => normalizedRegularTrace_conjEquiv T.gen hU x⟩,
    fun r => wordGramLevel_conj T.gen hU r, rfl⟩

end FiniteGrandTensor
end RenewalGeometry
