/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Predictive.CombProcessHistoryRealization
import RenewalGeometry.Predictive.ContextualFutureNullIdeal
import RenewalGeometry.Predictive.FiniteGrandTensorExact
import RenewalGeometry.Predictive.FlatWordPanelReconstruction

/-!
# The finite Renewal Grand Tensor of a finite operational process

Paper `predictive_spectral_geometry`, labels `def:ncg-grand-tensor` and
`prop:ncg-grand-tensor-reconstruction`.

## The future-separated quotient as a concrete matrix algebra

* `exists_centralSupport`: a star-stable two-sided ideal `J` of a star subalgebra
  `A ⊆ M_n(ℂ)` is `e A` for a central projection `e ∈ J` (Hilbert–Schmidt
  orthogonal decomposition `A = J ⊕ J^⊥`).
* `exists_quotient_compression`: hence there is an isometry `V` onto the range
  of `1 - e` commuting with `A`, and compression `a ↦ Vᴴ a V` is a star
  homomorphism with kernel **exactly** `J` (`compressionHom`, `compressionHom_eq_zero_iff`):
  it realizes `A / J` concretely.

## The operational process and its Grand Tensor

* `FiniteOperationalProcess`: the finite operational input — the complete
  multitime intervention tables (multilinear functionals of the slot Choi
  matrices, at every depth `k`), the deterministic causal comb conditions on
  the reconstructed tensors (positivity, normalization, prefix compatibility),
  and the typed event grammar (branch interventions with their slots and
  Kraus vectors).
* `FiniteOperationalProcess.predictiveSystem`: the conditional event law
  `p(w | h) = p(hw)/p(h)` of the branch histories, read off the tables; the
  chain rule is proved from the comb realization (zero-probability prefixes
  propagate, `eventProb_eq_zero_of_prefix`).
* `SequentialComb.SequentialIsometricComb.histGen`: for a sequential
  realization, the branch generators pushed through the future-separated
  quotient `A^proc / N^fut` of its represented process algebra by the
  contextual future-null ideal of the causal readouts;
  `histAlgebraEquivQuotient`: `A^hist ≃ A^proc / N^fut`, letters ↦ classes.
* `GrandTensor.ofProcess`: the Grand Tensor `(A^hist, {K_r}, Z^min)` of the
  process: `system` is the process's predictive law and `gen` the quotient
  branch generators of its canonical support-minimal realization.
* `histAlgebra_realization_independent`, `grand_tensor_reconstruction_of_statistics`:
  equal complete intervention statistics (probabilities of all physical probe
  tuples) give equal predictive systems (hence `Z^min`, branch laws, updates),
  star-isomorphic represented process algebras, star-isomorphic future-separated
  history algebras compatible with every history word, equal regular traces and
  word-Gram hierarchies and equal least flat depths, for **any** choice of
  support-minimal realizations.
-/

noncomputable section

set_option linter.deprecated false
set_option linter.unusedSectionVars false
set_option linter.unusedSimpArgs false

open Matrix
open scoped ComplexOrder Kronecker

namespace RenewalGeometry
namespace OperationalGrandTensor

/-! ## Central support of a star-stable two-sided ideal -/

section CentralSupport

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The complex subspace of matrices underlying an ideal of a star subalgebra. -/
def idealSubspace (A : StarSubalgebra ℂ (Matrix n n ℂ)) (J : Ideal A) :
    Submodule ℂ (Matrix n n ℂ) where
  carrier := {x | ∃ q ∈ J, (q : Matrix n n ℂ) = x}
  add_mem' := by
    rintro _ _ ⟨q, hq, rfl⟩ ⟨r, hr, rfl⟩
    exact ⟨q + r, J.add_mem hq hr, rfl⟩
  zero_mem' := ⟨0, J.zero_mem, rfl⟩
  smul_mem' := by
    rintro c _ ⟨q, hq, rfl⟩
    refine ⟨c • q, ?_, rfl⟩
    rw [Algebra.smul_def]
    exact J.mul_mem_left _ hq

/-- Vectorization into the Euclidean space of matrix entries. -/
def vecLin : Matrix n n ℂ →ₗ[ℂ] EuclideanSpace ℂ (n × n) where
  toFun X := WithLp.toLp 2 (fun p : n × n => X p.1 p.2)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

theorem inner_vecLin (X Y : Matrix n n ℂ) :
    inner ℂ (vecLin X) (vecLin Y) = (Xᴴ * Y).trace := by
  change (fun p : n × n => Y p.1 p.2) ⬝ᵥ star (fun p : n × n => X p.1 p.2) = _
  simp only [dotProduct, Pi.star_apply, Matrix.trace, Matrix.diag, Matrix.mul_apply,
    conjTranspose_apply, Fintype.sum_prod_type]
  rw [Finset.sum_comm]
  exact Finset.sum_congr rfl fun _ _ => Finset.sum_congr rfl fun _ _ => mul_comm _ _

/-- **Central support.**  A star-stable two-sided ideal `J` of a finite
dimensional star algebra of matrices is generated by a central projection
`e ∈ J`: `q ∈ J ↔ e q = q`. -/
theorem exists_centralSupport (A : StarSubalgebra ℂ (Matrix n n ℂ)) (J : Ideal A)
    [J.IsTwoSided] (hstar : ∀ q ∈ J, star q ∈ J) :
    ∃ e : A, e ∈ J ∧ e * e = e ∧ star e = e ∧ (∀ a : A, e * a = a * e) ∧
      ∀ q : A, q ∈ J ↔ e * q = q := by
  classical
  set K : Submodule ℂ (EuclideanSpace ℂ (n × n)) := (idealSubspace A J).map vecLin
  obtain ⟨w, hwK, hperp⟩ := Submodule.HasOrthogonalProjection.exists_orthogonal (K := K)
    (vecLin (1 : Matrix n n ℂ))
  obtain ⟨x, ⟨e, he, rfl⟩, rfl⟩ := hwK
  -- the complement `f = 1 - e` is orthogonal to `J`
  have horth : ∀ q ∈ J, ((q : Matrix n n ℂ)ᴴ * ((1 : A) - e : A)).trace = 0 := by
    intro q hq
    have h := (Submodule.mem_orthogonal K _).1 hperp (vecLin (q : Matrix n n ℂ))
      ⟨q, ⟨q, hq, rfl⟩, rfl⟩
    rw [← map_sub, inner_vecLin] at h
    simpa using h
  set Jp : Set A := {y | ∀ q ∈ J, ((q : Matrix n n ℂ)ᴴ * (y : Matrix n n ℂ)).trace = 0}
  have hP1 : ∀ y ∈ Jp, ∀ a : A, a * y ∈ Jp := by
    intro y hy a q hq
    have := hy (star a * q) (J.mul_mem_left _ hq)
    simpa [Matrix.mul_assoc, conjTranspose_mul, star_eq_conjTranspose] using this
  have hP2 : ∀ y ∈ Jp, ∀ a : A, y * a ∈ Jp := by
    intro y hy a q hq
    have := hy (q * star a) (Ideal.mul_mem_right _ J hq)
    have e1 : ((q : Matrix n n ℂ)ᴴ * ((y : Matrix n n ℂ) * a)).trace =
        ((((q * star a : A) : Matrix n n ℂ))ᴴ * y).trace := by
      simp only [MulMemClass.coe_mul, StarMemClass.coe_star, star_eq_conjTranspose,
        conjTranspose_mul, conjTranspose_conjTranspose]
      rw [← Matrix.mul_assoc, trace_mul_comm]
      simp only [Matrix.mul_assoc]
    change ((q : Matrix n n ℂ)ᴴ * ((y : Matrix n n ℂ) * a)).trace = 0
    rw [e1]
    exact this
  have hP3 : ∀ q : A, q ∈ J → q ∈ Jp → q = 0 := by
    intro q hq hqp
    have := hqp q hq
    rw [trace_conjTranspose_mul_self_eq_zero_iff] at this
    exact Subtype.ext this
  have hf : (1 - e : A) ∈ Jp := horth
  have hright : ∀ q ∈ J, q * e = q := by
    intro q hq
    have h0 : q * (1 - e) = 0 :=
      hP3 _ (Ideal.mul_mem_right _ J hq) (hP1 _ hf q)
    rw [mul_sub, mul_one, sub_eq_zero] at h0
    exact h0.symm
  have hleft : ∀ q ∈ J, e * q = q := by
    intro q hq
    have h0 : (1 - e) * q = 0 := hP3 _ (J.mul_mem_left _ hq) (hP2 _ hf q)
    rw [sub_mul, one_mul, sub_eq_zero] at h0
    exact h0.symm
  have hee : e * e = e := hright e he
  have hstare : star e = e := by
    have h2 : e * star e = star e := hleft _ (hstar e he)
    have h4 : e * star e = e := by
      have := congrArg star h2
      rwa [star_mul, star_star] at this
    exact h2.symm.trans h4
  have hcent : ∀ a : A, e * a = a * e := by
    intro a
    have h1 : a * e = e * (a * e) := (hleft _ (J.mul_mem_left a he)).symm
    have h2 : e * a = (e * a) * e := (hright _ (Ideal.mul_mem_right a J he)).symm
    rw [h1, h2, mul_assoc]
  refine ⟨e, he, hee, hstare, hcent, fun q => ⟨hleft q, fun h => ?_⟩⟩
  rw [← h]
  exact Ideal.mul_mem_right q J he

/-- An isometry onto the range of a projection. -/
theorem exists_isometry_of_projection (f : Matrix n n ℂ) (hf : f * f = f) (hfs : fᴴ = f) :
    ∃ V : Matrix n (Fin f.rank) ℂ, Vᴴ * V = 1 ∧ V * Vᴴ = f := by
  have hpsd : f.PosSemidef := by
    have : fᴴ * f = f := by rw [hfs, hf]
    rw [← this]
    exact posSemidef_conjTranspose_mul_self f
  obtain ⟨F, hF⟩ := SequentialComb.exists_rank_factor f hpsd
  have hmin : SequentialComb.IsPrefixSupportMinimal F := by
    rw [SequentialComb.isPrefixSupportMinimal_iff_rank, ← rank_self_mul_conjTranspose, hF,
      Fintype.card_fin]
  obtain ⟨L, hL⟩ := (SequentialComb.isPrefixSupportMinimal_iff_exists_leftInverse F).1 hmin
  refine ⟨F, ?_, hF⟩
  have hLs : Fᴴ * Lᴴ = 1 := by rw [← conjTranspose_mul, hL, conjTranspose_one]
  calc Fᴴ * F = (L * F) * (Fᴴ * F) * (Fᴴ * Lᴴ) := by rw [hL, hLs]; simp
    _ = L * ((F * Fᴴ) * (F * Fᴴ)) * Lᴴ := by simp only [Matrix.mul_assoc]
    _ = L * (F * Fᴴ) * Lᴴ := by rw [hF, hf]
    _ = (L * F) * (Fᴴ * Lᴴ) := by simp only [Matrix.mul_assoc]
    _ = 1 := by rw [hL, hLs, Matrix.one_mul]

/-- **Concrete quotient.**  For a star-stable two-sided ideal `J` of a star
subalgebra `A ⊆ M_n(ℂ)` there is an isometry `V` whose range projection commutes
with `A`, such that `q ∈ J ↔ Vᴴ q V = 0`. -/
theorem exists_quotient_compression (A : StarSubalgebra ℂ (Matrix n n ℂ)) (J : Ideal A)
    [J.IsTwoSided] (hstar : ∀ q ∈ J, star q ∈ J) :
    ∃ (r : ℕ) (V : Matrix n (Fin r) ℂ), Vᴴ * V = 1 ∧
      (∀ a ∈ A, a * (V * Vᴴ) = (V * Vᴴ) * a) ∧
      ∀ q : A, q ∈ J ↔ Vᴴ * (q : Matrix n n ℂ) * V = 0 := by
  obtain ⟨e, he, hee, hstare, hcent, hJ⟩ := exists_centralSupport A J hstar
  set f : Matrix n n ℂ := 1 - (e : Matrix n n ℂ)
  have hff : f * f = f := by
    have : (e : Matrix n n ℂ) * e = e := congrArg Subtype.val hee
    simp only [f, sub_mul, mul_sub, Matrix.one_mul, Matrix.mul_one, this, sub_self, sub_zero]
  have hfs : fᴴ = f := by
    have : (e : Matrix n n ℂ)ᴴ = e := congrArg Subtype.val hstare
    simp only [f, conjTranspose_sub, conjTranspose_one, this]
  obtain ⟨V, hV1, hV2⟩ := exists_isometry_of_projection f hff hfs
  have hcomm : ∀ a ∈ A, a * f = f * a := by
    intro a ha
    have := congrArg Subtype.val (hcent ⟨a, ha⟩)
    simp only [MulMemClass.coe_mul] at this
    simp only [f, sub_mul, mul_sub, Matrix.one_mul, Matrix.mul_one, this]
  refine ⟨f.rank, V, hV1, fun a ha => by rw [hV2]; exact hcomm a ha, fun q => ?_⟩
  have hVf : Vᴴ * f = Vᴴ := by
    calc Vᴴ * f = Vᴴ * (V * Vᴴ) := by rw [hV2]
      _ = Vᴴ := by rw [← Matrix.mul_assoc, hV1, Matrix.one_mul]
  rw [hJ q]
  constructor
  · intro h
    have hfq : f * (q : Matrix n n ℂ) = 0 := by
      have : (e : Matrix n n ℂ) * q = q := congrArg Subtype.val h
      simp only [f, sub_mul, Matrix.one_mul, this, sub_self]
    calc Vᴴ * (q : Matrix n n ℂ) * V = Vᴴ * f * (q : Matrix n n ℂ) * V := by rw [hVf]
      _ = Vᴴ * (f * (q : Matrix n n ℂ)) * V := by simp only [Matrix.mul_assoc]
      _ = 0 := by rw [hfq]; simp
  · intro h
    have hfq : f * (q : Matrix n n ℂ) = 0 := by
      have h1 : V * (Vᴴ * (q : Matrix n n ℂ) * V) * Vᴴ = 0 := by rw [h]; simp
      have h2 : V * (Vᴴ * (q : Matrix n n ℂ) * V) * Vᴴ = f * (q : Matrix n n ℂ) * f := by
        calc V * (Vᴴ * (q : Matrix n n ℂ) * V) * Vᴴ = (V * Vᴴ) * (q : Matrix n n ℂ) * (V * Vᴴ) := by
              simp only [Matrix.mul_assoc]
          _ = f * (q : Matrix n n ℂ) * f := by rw [hV2]
      rw [h2, Matrix.mul_assoc, hcomm (q : Matrix n n ℂ) q.2, ← Matrix.mul_assoc, hff] at h1
      exact h1
    apply Subtype.ext
    have : f * (q : Matrix n n ℂ) = q - (e : Matrix n n ℂ) * q := by
      simp only [f, sub_mul, Matrix.one_mul]
    rw [this, sub_eq_zero] at hfq
    simpa using hfq.symm

/-- Compression by an isometry whose range projection commutes with a star
subalgebra is a unital star homomorphism on it. -/
def compressionHom (A : StarSubalgebra ℂ (Matrix n n ℂ)) {r : Type*} [Fintype r] [DecidableEq r]
    (V : Matrix n r ℂ) (hV : Vᴴ * V = 1) (hcomm : ∀ a ∈ A, a * (V * Vᴴ) = (V * Vᴴ) * a) :
    A →⋆ₐ[ℂ] Matrix r r ℂ where
  toFun a := Vᴴ * (a : Matrix n n ℂ) * V
  map_one' := by simp [hV]
  map_mul' a b := by
    change Vᴴ * ((a : Matrix n n ℂ) * (b : Matrix n n ℂ)) * V =
      Vᴴ * (a : Matrix n n ℂ) * V * (Vᴴ * (b : Matrix n n ℂ) * V)
    have hVf : Vᴴ * (V * Vᴴ) = Vᴴ := by rw [← Matrix.mul_assoc, hV, Matrix.one_mul]
    calc Vᴴ * ((a : Matrix n n ℂ) * (b : Matrix n n ℂ)) * V =
          Vᴴ * (V * Vᴴ) * (a : Matrix n n ℂ) * (b : Matrix n n ℂ) * V := by
          rw [hVf]; simp only [Matrix.mul_assoc]
      _ = Vᴴ * ((a : Matrix n n ℂ) * (V * Vᴴ)) * (b : Matrix n n ℂ) * V := by
          rw [hcomm (a : Matrix n n ℂ) a.2]; simp only [Matrix.mul_assoc]
      _ = _ := by simp only [Matrix.mul_assoc]
  map_zero' := by simp
  map_add' a b := by simp [Matrix.mul_add, Matrix.add_mul]
  commutes' c := by
    simp [Algebra.algebraMap_eq_smul_one, hV]
  map_star' a := by
    change Vᴴ * (a : Matrix n n ℂ)ᴴ * V = (Vᴴ * (a : Matrix n n ℂ) * V)ᴴ
    simp [conjTranspose_mul, Matrix.mul_assoc]

theorem compressionHom_apply (A : StarSubalgebra ℂ (Matrix n n ℂ)) {r : Type*} [Fintype r]
    [DecidableEq r] (V : Matrix n r ℂ) (hV : Vᴴ * V = 1)
    (hcomm : ∀ a ∈ A, a * (V * Vᴴ) = (V * Vᴴ) * a) (a : A) :
    compressionHom A V hV hcomm a = Vᴴ * (a : Matrix n n ℂ) * V := rfl

end CentralSupport

/-! ## Star isomorphism of images with equal kernels -/

section KernelIso

variable {F B B' : Type*} [Ring F] [StarRing F] [Algebra ℂ F] [StarModule ℂ F]
  [Ring B] [StarRing B] [Algebra ℂ B] [StarModule ℂ B] [Ring B'] [StarRing B'] [Algebra ℂ B']
  [StarModule ℂ B']

/-- Two star homomorphisms with the same kernel have star-isomorphic images,
compatibly with the source.  The images are given as star subalgebras `S`, `S'`
characterized by their membership. -/
theorem exists_starAlgEquiv_of_ker_eq (Φ : F →⋆ₐ[ℂ] B) (Φ' : F →⋆ₐ[ℂ] B')
    (S : StarSubalgebra ℂ B) (S' : StarSubalgebra ℂ B')
    (hS : ∀ x, x ∈ S ↔ ∃ f, Φ f = x) (hS' : ∀ x, x ∈ S' ↔ ∃ f, Φ' f = x)
    (h : ∀ f, Φ f = 0 ↔ Φ' f = 0) :
    ∃ ψ : S ≃⋆ₐ[ℂ] S', ∀ f (hf : Φ f ∈ S), (ψ ⟨Φ f, hf⟩ : B') = Φ' f := by
  classical
  have heq : ∀ f g, Φ f = Φ g → Φ' f = Φ' g := by
    intro f g hfg
    have : Φ (f - g) = 0 := by rw [map_sub, hfg, sub_self]
    have := (h _).1 this
    rwa [map_sub, sub_eq_zero] at this
  have heq' : ∀ f g, Φ' f = Φ' g → Φ f = Φ g := by
    intro f g hfg
    have : Φ' (f - g) = 0 := by rw [map_sub, hfg, sub_self]
    have := (h _).2 this
    rwa [map_sub, sub_eq_zero] at this
  let pre : S → F := fun x => Classical.choose ((hS x).1 x.2)
  have hpre : ∀ x : S, Φ (pre x) = x := fun x => Classical.choose_spec ((hS x).1 x.2)
  have hval : ∀ (x : S) (f : F), Φ f = x → Φ' (pre x) = Φ' f :=
    fun x f hf => heq _ _ ((hpre x).trans hf.symm)
  have hmem : ∀ f, Φ' f ∈ S' := fun f => (hS' _).2 ⟨f, rfl⟩
  let ψ₀ : S →⋆ₐ[ℂ] S' :=
    { toFun := fun x => ⟨Φ' (pre x), hmem _⟩
      map_one' := by
        apply Subtype.ext
        change Φ' (pre 1) = 1
        rw [hval 1 1 (map_one Φ), map_one]
      map_mul' := fun x y => by
        apply Subtype.ext
        change Φ' (pre (x * y)) = Φ' (pre x) * Φ' (pre y)
        rw [hval (x * y) (pre x * pre y) (by rw [map_mul, hpre, hpre]; rfl), map_mul]
      map_zero' := by
        apply Subtype.ext
        change Φ' (pre 0) = 0
        rw [hval 0 0 (map_zero Φ), map_zero]
      map_add' := fun x y => by
        apply Subtype.ext
        change Φ' (pre (x + y)) = Φ' (pre x) + Φ' (pre y)
        rw [hval (x + y) (pre x + pre y) (by rw [map_add, hpre, hpre]; rfl), map_add]
      commutes' := fun c => by
        apply Subtype.ext
        change Φ' (pre (algebraMap ℂ S c)) = algebraMap ℂ B' c
        rw [hval _ (algebraMap ℂ F c) (by rw [AlgHomClass.commutes]; rfl),
          AlgHomClass.commutes]
      map_star' := fun x => by
        apply Subtype.ext
        change Φ' (pre (star x)) = star (Φ' (pre x))
        rw [hval (star x) (star (pre x)) (by rw [map_star, hpre]; rfl), map_star] }
  have hψ₀ : ∀ f (hf : Φ f ∈ S), ψ₀ ⟨Φ f, hf⟩ = ⟨Φ' f, hmem f⟩ := fun f hf =>
    Subtype.ext (hval _ f rfl)
  have hbij : Function.Bijective ψ₀ := by
    constructor
    · intro x y hxy
      have h1 : Φ' (pre x) = Φ' (pre y) := congrArg Subtype.val hxy
      apply Subtype.ext
      rw [← hpre x, ← hpre y]
      exact heq' _ _ h1
    · rintro ⟨y, hy⟩
      obtain ⟨f, rfl⟩ := (hS' y).1 hy
      exact ⟨⟨Φ f, (hS _).2 ⟨f, rfl⟩⟩, hψ₀ f _⟩
  exact ⟨StarAlgEquiv.ofBijective ψ₀ hbij, fun f hf => congrArg Subtype.val (hψ₀ f hf)⟩

end KernelIso

/-! ## The future-separated history algebra of a sequential realization -/

theorem starAlgHom_rangeRestrict_surjective {A B : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    [Ring B] [StarRing B] [Algebra ℂ B] [StarModule ℂ B] (φ : A →⋆ₐ[ℂ] B) :
    Function.Surjective φ.rangeRestrict := by
  rintro ⟨_, a, rfl⟩
  exact ⟨a, rfl⟩

/-- Path letters form a finite alphabet. -/
instance pathLetterFintype {Obj Arr : Type*} [Fintype Obj] [Fintype Arr] :
    Fintype (ProcessHistory.PathLetter Obj Arr) :=
  Fintype.ofEquiv (Arr ⊕ (Arr ⊕ Obj))
    { toFun := fun x => match x with
        | .inl a => .arrow a
        | .inr (.inl a) => .reverse a
        | .inr (.inr ξ) => .unit ξ
      invFun := fun x => match x with
        | .arrow a => .inl a
        | .reverse a => .inr (.inl a)
        | .unit ξ => .inr (.inr ξ)
      left_inv := by rintro (a | a | ξ) <;> rfl
      right_inv := by rintro (a | a | ξ) <;> rfl }

/-- Bounded-length words over a finite alphabet form a finite type. -/
noncomputable instance wordsFintype {Γ : Type*} [Finite Γ] (r : ℕ) :
    Fintype (FiniteGrandTensor.Words Γ r) :=
  haveI : Finite (FiniteGrandTensor.Words Γ r) := (List.finite_length_le Γ r).to_subtype
  Fintype.ofFinite _

section HistoryOfComb

open SequentialComb ProcessHistory FiniteGrandTensor

variable {O I : Type} [Fintype O] [Fintype I] [DecidableEq O] [DecidableEq I] {N : ℕ}
  {Arr : Type} {K : Type} [Fintype K]
  (C : SequentialIsometricComb O I N) (slot : Arr → Fin N) (kv : Arr → K → O × I → ℂ)

/-- The Hilbert–Schmidt memory index of a realization. -/
abbrev HSI : Type := HSIdx fun ξ : Fin (N + 1) => C.Mem ξ

/-- The represented process algebra `A^proc = C*(ρ(a))` of the realization. -/
abbrev procAlg : StarSubalgebra ℂ (Matrix (HSI C) (HSI C) ℂ) :=
  (C.typedBranches slot kv).rep.range

/-- The causal readouts on `A^proc`: prepare the initial memory state, apply the
represented history, discard the memory at cut `η`. -/
def readoutHom (η : Fin (N + 1)) : procAlg C slot kv →+ ℂ where
  toFun x := causalReadout (D := fun ξ : Fin (N + 1) => C.Mem ξ) 0 η (x : Matrix (HSI C) (HSI C) ℂ)
  map_zero' := by simp [causalReadout]
  map_add' x y := by simp [causalReadout, add_mulVec, dotProduct_add]

/-- The contextual future-null ideal `N^fut` of the causal readouts
(`eq:ncg-contextual-null`, both `q` and `q^*` tested in every two-sided context). -/
abbrev futureNull : Ideal (procAlg C slot kv) :=
  contextualFutureNullIdeal (readoutHom C slot kv)

theorem futureNull_star_mem : ∀ q ∈ futureNull C slot kv, star q ∈ futureNull C slot kv :=
  fun _ hq => contextualFutureNullIdeal_star_mem _ hq

theorem exists_hist_compression :
    ∃ (r : ℕ) (V : Matrix (HSI C) (Fin r) ℂ), Vᴴ * V = 1 ∧
      (∀ a ∈ procAlg C slot kv, a * (V * Vᴴ) = (V * Vᴴ) * a) ∧
      ∀ q : procAlg C slot kv, q ∈ futureNull C slot kv ↔ Vᴴ * (q : Matrix (HSI C) (HSI C) ℂ) * V = 0 :=
  exists_quotient_compression _ _ (futureNull_star_mem C slot kv)

/-- The dimension of the concrete future-separated quotient. -/
def histRank : ℕ := Classical.choose (exists_hist_compression C slot kv)

/-- The isometry realizing `A^proc / N^fut` by compression. -/
def histIso : Matrix (HSI C) (Fin (histRank C slot kv)) ℂ :=
  Classical.choose (Classical.choose_spec (exists_hist_compression C slot kv))

theorem histIso_spec :
    (histIso C slot kv)ᴴ * histIso C slot kv = 1 ∧
      (∀ a ∈ procAlg C slot kv,
        a * (histIso C slot kv * (histIso C slot kv)ᴴ) =
          (histIso C slot kv * (histIso C slot kv)ᴴ) * a) ∧
      ∀ q : procAlg C slot kv, q ∈ futureNull C slot kv ↔
        (histIso C slot kv)ᴴ * (q : Matrix (HSI C) (HSI C) ℂ) * histIso C slot kv = 0 :=
  Classical.choose_spec (Classical.choose_spec (exists_hist_compression C slot kv))

/-- The quotient star homomorphism `A^proc → A^proc / N^fut`, concretely. -/
def histQuotient : procAlg C slot kv →⋆ₐ[ℂ] Matrix (Fin (histRank C slot kv))
    (Fin (histRank C slot kv)) ℂ :=
  compressionHom _ (histIso C slot kv) (histIso_spec C slot kv).1 (histIso_spec C slot kv).2.1

theorem histQuotient_eq_zero_iff (q : procAlg C slot kv) :
    histQuotient C slot kv q = 0 ↔ q ∈ futureNull C slot kv :=
  ((histIso_spec C slot kv).2.2 q).symm

/-- The word map `𝔉_X → A^proc → A^proc / N^fut`. -/
def histMap : FreePathAlg (Fin (N + 1)) Arr →⋆ₐ[ℂ]
    Matrix (Fin (histRank C slot kv)) (Fin (histRank C slot kv)) ℂ :=
  (histQuotient C slot kv).comp (C.typedBranches slot kv).rep.rangeRestrict

/-- **The branch generators pushed through the future-separated quotient**. -/
def histGen (γ : PathLetter (Fin (N + 1)) Arr) :
    Matrix (Fin (histRank C slot kv)) (Fin (histRank C slot kv)) ℂ :=
  histMap C slot kv (FreeStarAlg.ι γ)

theorem histGen_apply (γ : PathLetter (Fin (N + 1)) Arr) :
    histGen C slot kv γ = (histIso C slot kv)ᴴ * (C.typedBranches slot kv).rep (FreeStarAlg.ι γ) *
      histIso C slot kv := rfl

theorem histGen_star (γ : PathLetter (Fin (N + 1)) Arr) :
    histGen C slot kv (star γ) = star (histGen C slot kv γ) := by
  rw [histGen, ← FreeStarAlg.star_ι, map_star]
  rfl

theorem histMap_eq_lift :
    histMap C slot kv = FreeStarAlg.lift (histGen C slot kv) (histGen_star C slot kv) :=
  FreeStarAlg.starAlgHom_ext fun x => by rw [FreeStarAlg.lift_ι]; rfl

theorem mem_historyAlgebra_histGen_iff (x : Matrix (Fin (histRank C slot kv))
    (Fin (histRank C slot kv)) ℂ) :
    x ∈ historyAlgebra (histGen C slot kv) ↔ ∃ f, histMap C slot kv f = x := by
  rw [histMap_eq_lift]
  unfold historyAlgebra
  rw [← FreeStarAlg.range_lift (histGen C slot kv) (histGen_star C slot kv)]
  rfl

theorem histMap_eq_zero_iff (f : FreePathAlg (Fin (N + 1)) Arr) :
    histMap C slot kv f = 0 ↔
      (C.typedBranches slot kv).rep.rangeRestrict f ∈ futureNull C slot kv :=
  histQuotient_eq_zero_iff C slot kv _

/-- **`A^hist = A^proc / N^fut`** (`eq:ncg-history-algebra`): the quotient of the
represented process algebra by the contextual future-null ideal is algebra
isomorphic to the history algebra generated by the quotient branch generators,
each class `[q]` going to its concrete representative. -/
theorem histAlgebraEquivQuotient :
    ∃ e : (procAlg C slot kv ⧸ futureNull C slot kv) ≃ₐ[ℂ]
        (historyAlgebra (histGen C slot kv)).toSubalgebra,
      ∀ q : procAlg C slot kv,
        (e (Ideal.Quotient.mk _ q) : Matrix (Fin (histRank C slot kv))
          (Fin (histRank C slot kv)) ℂ) = histQuotient C slot kv q := by
  have hmem : ∀ q : procAlg C slot kv,
      histQuotient C slot kv q ∈ (historyAlgebra (histGen C slot kv)).toSubalgebra := by
    intro q
    obtain ⟨f, hf⟩ := starAlgHom_rangeRestrict_surjective (C.typedBranches slot kv).rep q
    change _ ∈ historyAlgebra (histGen C slot kv)
    rw [mem_historyAlgebra_histGen_iff]
    exact ⟨f, by rw [histMap, StarAlgHom.comp_apply, hf]⟩
  let κ : procAlg C slot kv →ₐ[ℂ] (historyAlgebra (histGen C slot kv)).toSubalgebra :=
    (histQuotient C slot kv).toAlgHom.codRestrict _ hmem
  have hsurj : Function.Surjective κ := by
    rintro ⟨x, hx⟩
    obtain ⟨f, rfl⟩ := (mem_historyAlgebra_histGen_iff C slot kv x).1 hx
    exact ⟨(C.typedBranches slot kv).rep.rangeRestrict f, Subtype.ext rfl⟩
  have hker : RingHom.ker κ = futureNull C slot kv := by
    ext q
    rw [RingHom.mem_ker, ← histQuotient_eq_zero_iff]
    constructor
    · intro h; exact congrArg Subtype.val h
    · intro h; exact Subtype.ext h
  refine ⟨(Ideal.quotientEquivAlgOfEq ℂ hker.symm).trans
    (Ideal.quotientKerAlgEquivOfSurjective hsurj), fun q => rfl⟩

/-- The future-null ideal does not contain the unit: the initial causal readout
of the unit is `1`. -/
theorem one_not_mem_futureNull : (1 : procAlg C slot kv) ∉ futureNull C slot kv := by
  intro h
  have h1 := h.1 0 1 1
  simp only [mul_one] at h1
  change causalReadout (D := fun ξ : Fin (N + 1) => C.Mem ξ) 0 0 (1 : Matrix (HSI C) (HSI C) ℂ) = 0
    at h1
  unfold causalReadout at h1
  rw [one_mulVec, dotProduct_star_self_eq_zero] at h1
  have h2 := congrArg (fun v => (blockIncl (fun ξ : Fin (N + 1) => C.Mem ξ) 0)ᴴ *ᵥ v) h1
  simp only [blockVec, mulVec_mulVec, blockIncl_isometry, one_mulVec, mulVec_zero] at h2
  have : Unique (C.Mem ((0 : Fin (N + 1)) : ℕ)) := C.memZero
  have h3 := congrFun h2 (default, default)
  simp [hsVec] at h3

theorem histRank_pos : 0 < histRank C slot kv := by
  rcases Nat.eq_zero_or_pos (histRank C slot kv) with h | h
  · exfalso
    apply one_not_mem_futureNull C slot kv
    rw [← histQuotient_eq_zero_iff]
    ext i
    exact absurd i.2 (by omega)
  · exact h

instance histCarrier_nonempty : Nonempty (Fin (histRank C slot kv)) :=
  ⟨⟨0, histRank_pos C slot kv⟩⟩

/-- Free path words: the free-algebra element of a letter word. -/
def freeWord : List (PathLetter (Fin (N + 1)) Arr) → FreePathAlg (Fin (N + 1)) Arr
  | [] => 1
  | γ :: w => FreeStarAlg.ι γ * freeWord w

theorem histMap_freeWord (w : List (PathLetter (Fin (N + 1)) Arr)) :
    histMap C slot kv (freeWord w) = wordOp (histGen C slot kv) w := by
  induction w with
  | nil => simp [freeWord]
  | cons γ w ih => rw [freeWord, map_mul, ih, wordOp_cons]; rfl

end HistoryOfComb

/-! ## Realization independence of the future-separated history algebra -/

section Independence

open SequentialComb ProcessHistory FiniteGrandTensor

variable {O I : Type} [Fintype O] [Fintype I] [DecidableEq O] [DecidableEq I] {N : ℕ}
  {Arr : Type} [Fintype Arr] {K : Type} [Fintype K] (slot : Arr → Fin N)
  (kv : Arr → K → O × I → ℂ)

/-- Two prefix-support-minimal realizations of the same terminal tensor have the
same future-null kernel on the free path algebra. -/
theorem histMap_eq_zero_iff_of_realizations [Nonempty I]
    (C C' : SequentialIsometricComb O I N)
    (hmin : ∀ k, k ≤ N → IsPrefixSupportMinimal (C.cumulative k))
    (hmin' : ∀ k, k ≤ N → IsPrefixSupportMinimal (C'.cumulative k))
    (hT : C.realizedChoi N = C'.realizedChoi N) (f : FreePathAlg (Fin (N + 1)) Arr) :
    histMap C slot kv f = 0 ↔ histMap C' slot kv f = 0 := by
  obtain ⟨U, hU, hrep, hread, -⟩ := typedBranches_realization_independent slot kv C C' hmin hmin' hT
  set ρ := (C.typedBranches slot kv).rep
  set ρ' := (C'.typedBranches slot kv).rep
  have hR : ∀ η (g : FreePathAlg (Fin (N + 1)) Arr),
      readoutHom C' slot kv η (ρ'.rangeRestrict g) = readoutHom C slot kv η (ρ.rangeRestrict g) := by
    intro η g
    change causalReadout _ _ (ρ' g) = causalReadout _ _ (ρ g)
    rw [hrep g, hread]
  have key : ∀ (R : Fin (N + 1) → (C.typedBranches slot kv).rep.range →+ ℂ)
      (R' : Fin (N + 1) → (C'.typedBranches slot kv).rep.range →+ ℂ),
      (∀ η g, R' η (ρ'.rangeRestrict g) = R η (ρ.rangeRestrict g)) →
      (ρ.rangeRestrict f ∈ contextualFutureNullIdeal R ↔
        ρ'.rangeRestrict f ∈ contextualFutureNullIdeal R') := by
    intro R R' hRR
    rw [show (ρ.rangeRestrict f ∈ contextualFutureNullIdeal R) ↔
        (ρ.rangeRestrict f ∈ contextualFutureNull R) from Iff.rfl,
      show (ρ'.rangeRestrict f ∈ contextualFutureNullIdeal R') ↔
        (ρ'.rangeRestrict f ∈ contextualFutureNull R') from Iff.rfl]
    simp only [contextualFutureNull, Set.mem_setOf_eq]
    have hall : ∀ (q : FreePathAlg (Fin (N + 1)) Arr),
        (∀ η (u v : (C.typedBranches slot kv).rep.range), R η (u * ρ.rangeRestrict q * v) = 0) ↔
          ∀ η (u v : (C'.typedBranches slot kv).rep.range),
            R' η (u * ρ'.rangeRestrict q * v) = 0 := by
      intro q
      constructor
      · intro h η u v
        obtain ⟨g, rfl⟩ := starAlgHom_rangeRestrict_surjective ρ' u
        obtain ⟨g', rfl⟩ := starAlgHom_rangeRestrict_surjective ρ' v
        rw [show ρ'.rangeRestrict g * ρ'.rangeRestrict q * ρ'.rangeRestrict g' =
          ρ'.rangeRestrict (g * q * g') by rw [map_mul, map_mul], hRR,
          show ρ.rangeRestrict (g * q * g') =
            ρ.rangeRestrict g * ρ.rangeRestrict q * ρ.rangeRestrict g' by rw [map_mul, map_mul]]
        exact h η _ _
      · intro h η u v
        obtain ⟨g, rfl⟩ := starAlgHom_rangeRestrict_surjective ρ u
        obtain ⟨g', rfl⟩ := starAlgHom_rangeRestrict_surjective ρ v
        rw [show ρ.rangeRestrict g * ρ.rangeRestrict q * ρ.rangeRestrict g' =
          ρ.rangeRestrict (g * q * g') by rw [map_mul, map_mul], ← hRR,
          show ρ'.rangeRestrict (g * q * g') =
            ρ'.rangeRestrict g * ρ'.rangeRestrict q * ρ'.rangeRestrict g' by rw [map_mul, map_mul]]
        exact h η _ _
    have hs : star (ρ.rangeRestrict f) = ρ.rangeRestrict (star f) := (map_star _ _).symm
    have hs' : star (ρ'.rangeRestrict f) = ρ'.rangeRestrict (star f) := (map_star _ _).symm
    constructor
    · rintro ⟨h1, h2⟩
      refine ⟨(hall f).1 h1, ?_⟩
      rw [hs']
      rw [hs] at h2
      exact (hall (star f)).1 h2
    · rintro ⟨h1, h2⟩
      refine ⟨(hall f).2 h1, ?_⟩
      rw [hs]
      rw [hs'] at h2
      exact (hall (star f)).2 h2
  rw [histMap_eq_zero_iff, histMap_eq_zero_iff]
  exact key _ _ hR

/-- **Realization independence of the Grand Tensor components**
(`prop:ncg-grand-tensor-reconstruction`, clauses (ii)–(iv)).  For two
prefix-support-minimal realizations of the same terminal tensor, the
future-separated history algebras are star isomorphic by an isomorphism carrying
every represented history word to its namesake; the normalized regular traces
correspond, every word-Gram layer coincides, and the flat-depth criterion holds
at exactly the same depths. -/
theorem histAlgebra_realization_independent [Nonempty I]
    (C C' : SequentialIsometricComb O I N)
    (hmin : ∀ k, k ≤ N → IsPrefixSupportMinimal (C.cumulative k))
    (hmin' : ∀ k, k ≤ N → IsPrefixSupportMinimal (C'.cumulative k))
    (hT : C.realizedChoi N = C'.realizedChoi N) :
    ∃ ψ : historyAlgebra (histGen C slot kv) ≃⋆ₐ[ℂ] historyAlgebra (histGen C' slot kv),
      (∀ w, ψ (wordElt (histGen C slot kv) w) = wordElt (histGen C' slot kv) w) ∧
      (∀ x, normalizedRegularTrace (historyAlgebra (histGen C' slot kv)) (ψ x) =
        normalizedRegularTrace (historyAlgebra (histGen C slot kv)) x) ∧
      (∀ r, wordGramLevel (histGen C' slot kv) r = wordGramLevel (histGen C slot kv) r) ∧
      (∀ r, gramPanel (histGen C' slot kv) r = gramPanel (histGen C slot kv) r) ∧
      ∀ r, ((gramPanel (histGen C slot kv) r).rank =
          (gramPanel (histGen C slot kv) (r + 1)).rank ↔
        (gramPanel (histGen C' slot kv) r).rank = (gramPanel (histGen C' slot kv) (r + 1)).rank) := by
  obtain ⟨ψ, hψ⟩ := exists_starAlgEquiv_of_ker_eq (histMap C slot kv) (histMap C' slot kv)
    (historyAlgebra (histGen C slot kv)) (historyAlgebra (histGen C' slot kv))
    (mem_historyAlgebra_histGen_iff C slot kv) (mem_historyAlgebra_histGen_iff C' slot kv)
    (histMap_eq_zero_iff_of_realizations slot kv C C' hmin hmin' hT)
  have hword : ∀ w, ψ (wordElt (histGen C slot kv) w) = wordElt (histGen C' slot kv) w := by
    intro w
    apply Subtype.ext
    have hmem : histMap C slot kv (freeWord w) ∈ historyAlgebra (histGen C slot kv) :=
      (mem_historyAlgebra_histGen_iff C slot kv _).2 ⟨_, rfl⟩
    have := hψ (freeWord w) hmem
    have hx : (⟨histMap C slot kv (freeWord w), hmem⟩ : historyAlgebra (histGen C slot kv)) =
        wordElt (histGen C slot kv) w := Subtype.ext (histMap_freeWord C slot kv w)
    rw [← hx, this, histMap_freeWord]
    rfl
  have htrace : ∀ x, normalizedRegularTrace (historyAlgebra (histGen C' slot kv)) (ψ x) =
      normalizedRegularTrace (historyAlgebra (histGen C slot kv)) x :=
    fun x => normalizedRegularTrace_algEquiv ψ.toAlgEquiv x
  have hgram : ∀ r, wordGramLevel (histGen C' slot kv) r = wordGramLevel (histGen C slot kv) r := by
    intro r
    funext v w
    change FiniteGrandTensor.wordGram (histGen C' slot kv) v.1 w.1 =
      FiniteGrandTensor.wordGram (histGen C slot kv) v.1 w.1
    unfold FiniteGrandTensor.wordGram
    rw [wordPair_eq, wordPair_eq, ← hword, ← hword, ← map_star, ← map_mul, htrace]
  have hpanel : ∀ r, gramPanel (histGen C' slot kv) r = gramPanel (histGen C slot kv) r := by
    intro r
    unfold gramPanel
    rw [hgram r]
  refine ⟨ψ, hword, htrace, hgram, hpanel, fun r => ?_⟩
  rw [hpanel r, hpanel (r + 1)]

end Independence

/-! ## Finite operational processes -/

section Process

open SequentialComb ProcessHistory FiniteGrandTensor DerivedPredictiveCarrierUniversal

/-- **A finite operational process** over a typed event grammar: slot spaces
`O = H^out`, `I = H^in`, horizon `N`, primitive branch interventions `a` at slot
`slot a` with Kraus vectors `kraus a ν` on `H^out ⊗ H^in` (the grammar is a
parameter), and the operational data proper: the complete finite multitime
intervention tables at every depth `k` (multilinear functionals of the slot Choi
matrices, i.e. affine under randomization and additive under coarse graining),
whose reconstructed Choi tensors are positive, normalized and prefix/causally
compatible (`eq:ncg-comb-causality`). -/
structure FiniteOperationalProcess (O I : Type) [Fintype O] [Fintype I] [DecidableEq O]
    [DecidableEq I] (N : ℕ) {Arr K : Type} [Fintype K] (slot : Arr → Fin N)
    (kraus : Arr → K → O × I → ℂ) where
  /-- The complete `k`-slot intervention tables. -/
  table : ∀ k, MultilinearMap ℂ (fun _ : Fin k => Matrix (O × I) (O × I) ℂ) ℂ
  /-- Positivity, normalization and prefix/causal compatibility of the
  reconstructed tensors. -/
  deterministic : IsDeterministicCombThrough (fun k => combRepTensor (table k)) N

namespace FiniteOperationalProcess

variable {O I : Type} [Fintype O] [Fintype I] [DecidableEq O] [DecidableEq I] {N : ℕ}
  {Arr K : Type} [Fintype K] {slot : Arr → Fin N} {kraus : Arr → K → O × I → ℂ}
  (X : FiniteOperationalProcess O I N slot kraus)

/-- The reconstructed Choi tensors `R^(k)` of the tables. -/
def tensor : CombPrefixFamily O I := fun k => combRepTensor (X.table k)

/-- The canonical support-minimal sequential realization of the process. -/
def canonicalRealization : SequentialIsometricComb O I N :=
  canonicalComb X.tensor N X.deterministic

theorem canonicalRealization_realizedChoi (k : ℕ) (hk : k ≤ N) :
    X.canonicalRealization.realizedChoi k = X.tensor k :=
  canonicalComb_realizedChoi X.deterministic k hk

theorem canonicalRealization_minimal (k : ℕ) (hk : k ≤ N) :
    IsPrefixSupportMinimal (X.canonicalRealization.cumulative k) :=
  canonicalComb_minimal X.deterministic k hk

/-- A branch history is admissible when its `j`-th event acts at slot `j`. -/
def Admissible (h : List Arr) : Prop := ∀ j : Fin h.length, ((slot (h.get j) : Fin N) : ℕ) = j

/-- The Choi tuple of a history. -/
def wordChoi (h : List Arr) : Fin h.length → Matrix (O × I) (O × I) ℂ :=
  fun j => interventionChoi (kraus (h.get j))

open Classical in
/-- **The event probability** of a branch history, read off the intervention
table of its depth. -/
def eventProb (h : List Arr) : ℝ :=
  if Admissible (slot := slot) h then (X.table h.length (wordChoi (kraus := kraus) h)).re else 0

/-- **The conditional event law** `p(w | h) = p(hw) / p(h)` (unit law on
unreachable histories). -/
def condProb (h w : List Arr) : ℝ :=
  if X.eventProb h = 0 then (if w = [] then 1 else 0) else X.eventProb (h ++ w) / X.eventProb h

theorem admissible_length_le {h : List Arr} (hadm : Admissible (slot := slot) h) :
    h.length ≤ N := by
  rcases Nat.eq_zero_or_pos h.length with h0 | hpos
  · omega
  · have h1 := hadm ⟨h.length - 1, by omega⟩
    have h2 := (slot (h.get ⟨h.length - 1, by omega⟩)).2
    simp only at h1
    omega

theorem admissible_append_left {L w : List Arr} (hadm : Admissible (slot := slot) (L ++ w)) :
    Admissible (slot := slot) L := by
  intro j
  have h1 := hadm ⟨j, by simp; omega⟩
  simp only [List.get_eq_getElem] at h1 ⊢
  rwa [List.getElem_append_left] at h1

/-- The event probability is the squared norm of the sequential amplitudes of
the canonical realization. -/
theorem eventProb_eq_amp {h : List Arr} (hadm : Admissible (slot := slot) h) :
    X.eventProb h = (∑ ν : Fin h.length → K,
      star (X.canonicalRealization.combAmp h.length (fun j => kraus (h.get j) (ν j))) ⬝ᵥ
        X.canonicalRealization.combAmp h.length (fun j => kraus (h.get j) (ν j))).re := by
  classical
  unfold eventProb
  rw [if_pos hadm]
  congr 1
  have hk := admissible_length_le hadm
  have htab : X.table h.length = combPairing (X.canonicalRealization.realizedChoi h.length) := by
    rw [X.canonicalRealization_realizedChoi h.length hk, tensor, combPairing_combRepTensor]
  rw [htab, combPairing_apply]
  exact X.canonicalRealization.trace_realizedChoi_mul_combProd_choi h.length
    (fun j => kraus (h.get j))

/-- **Zero-probability prefixes propagate** to every continuation. -/
theorem eventProb_eq_zero_of_prefix (L w : List Arr) (hL : X.eventProb L = 0) :
    X.eventProb (L ++ w) = 0 := by
  classical
  by_cases hadm : Admissible (slot := slot) (L ++ w)
  · have hadmL := admissible_append_left hadm
    rw [X.eventProb_eq_amp hadmL] at hL
    have hnn : ∀ ν : Fin L.length → K,
        0 ≤ star (X.canonicalRealization.combAmp L.length (fun j => kraus (L.get j) (ν j))) ⬝ᵥ
          X.canonicalRealization.combAmp L.length (fun j => kraus (L.get j) (ν j)) :=
      fun ν => dotProduct_star_self_nonneg _
    have hsum_nonneg := Finset.sum_nonneg (fun ν (_ : ν ∈ Finset.univ) => hnn ν)
    have hzero : (∑ ν : Fin L.length → K,
        star (X.canonicalRealization.combAmp L.length (fun j => kraus (L.get j) (ν j))) ⬝ᵥ
          X.canonicalRealization.combAmp L.length (fun j => kraus (L.get j) (ν j))) = 0 := by
      apply Complex.ext
      · simpa using hL
      · simpa using (Complex.nonneg_iff.1 hsum_nonneg).2.symm
    have hamp : ∀ ν : Fin L.length → K,
        X.canonicalRealization.combAmp L.length (fun j => kraus (L.get j) (ν j)) = 0 := by
      intro ν
      have := (Finset.sum_eq_zero_iff_of_nonneg (fun ν _ => hnn ν)).1 hzero ν (Finset.mem_univ _)
      exact dotProduct_star_self_eq_zero.1 this
    rw [X.eventProb_eq_amp hadm]
    have hlen : L.length ≤ (L ++ w).length := by simp
    have hamp' : ∀ ν : Fin (L ++ w).length → K,
        X.canonicalRealization.combAmp (L ++ w).length
          (fun j => kraus ((L ++ w).get j) (ν j)) = 0 := by
      intro ν
      apply X.canonicalRealization.combAmp_eq_zero_of_prefix _ _ L.length hlen
      have hpre : (fun j : Fin L.length => kraus ((L ++ w).get (Fin.castLE hlen j))
          (ν (Fin.castLE hlen j))) =
          fun j => kraus (L.get j) (ν (Fin.castLE hlen j)) := by
        funext j
        have hget : (L ++ w).get (Fin.castLE hlen j) = L.get j := by
          simp only [List.get_eq_getElem, Fin.coe_castLE]
          exact List.getElem_append_left j.2
        rw [hget]
      rw [hpre]
      exact hamp (fun j => ν (Fin.castLE hlen j))
    have hsum : (∑ ν : Fin (L ++ w).length → K,
        star (X.canonicalRealization.combAmp (L ++ w).length
          (fun j => kraus ((L ++ w).get j) (ν j))) ⬝ᵥ
        X.canonicalRealization.combAmp (L ++ w).length
          (fun j => kraus ((L ++ w).get j) (ν j))) = 0 :=
      Finset.sum_eq_zero fun ν _ => by rw [hamp' ν, dotProduct_zero]
    rw [hsum, Complex.zero_re]
  · unfold eventProb
    rw [if_neg hadm]

/-- **The predictive law of the process** (`eq:ncg-chain-law`): histories are
branch words, the update appends the event, and the complete future law is the
conditional event law of the tables. -/
def predictiveSystem : PredictiveSystem (List Arr) Arr where
  probability := X.condProb
  step h a := h ++ [a]
  branch h a := X.condProb h [a]
  probability_nil h := by
    unfold condProb
    by_cases h0 : X.eventProb h = 0
    · rw [if_pos h0, if_pos rfl]
    · rw [if_neg h0, List.append_nil, div_self h0]
  probability_cons h a w := by
    unfold condProb
    by_cases h0 : X.eventProb h = 0
    · simp [h0]
    · rw [if_neg h0, if_neg h0]
      by_cases h1 : X.eventProb (h ++ [a]) = 0
      · rw [h1, zero_div, zero_mul]
        have := X.eventProb_eq_zero_of_prefix (h ++ [a]) w h1
        rw [List.append_assoc, List.singleton_append] at this
        rw [this, zero_div]
      · rw [if_neg h1, List.append_assoc, List.singleton_append]
        field_simp

theorem predictiveSystem_probability (h w : List Arr) :
    X.predictiveSystem.probability h w = X.condProb h w := rfl

end FiniteOperationalProcess

end Process

/-! ## The Grand Tensor of an operational process -/

section GrandTensorOfProcess

open SequentialComb ProcessHistory FiniteGrandTensor DerivedPredictiveCarrierUniversal

variable {O I : Type} [Fintype O] [Fintype I] [DecidableEq O] [DecidableEq I] {N : ℕ}
  {Arr K : Type} [Fintype K] {slot : Arr → Fin N} {kraus : Arr → K → O × I → ℂ}

/-- **Definition `def:ncg-grand-tensor`** (`eq:ncg-grand-tensor`).  The finite
Renewal Grand Tensor associated with the operational process `X`: its predictive
law (whose quotient is `Z^min_X`) and the branch generators of `X` pushed
through the future-separated quotient `A^proc / N^fut` of the represented process
algebra of its canonical support-minimal realization; `A^hist`, `τ̂_reg` and the
word-Gram hierarchy `{K_{X,r}}` are the derived fields
`historyAlgebra`, `regularTrace`, `wordGram`. -/
def GrandTensor.ofProcess (X : FiniteOperationalProcess O I N slot kraus) :
    FiniteGrandTensor.GrandTensor (List Arr) Arr
      (Fin (histRank X.canonicalRealization slot kraus)) (PathLetter (Fin (N + 1)) Arr) :=
  ⟨X.predictiveSystem, histGen X.canonicalRealization slot kraus⟩

/-- **The Grand Tensor of a process is built from the process.**  Its predictive
system is the process's conditional event law; its history algebra is the
future-separated quotient `A^proc / N^fut` of the represented process algebra by
the contextual future-null ideal of the causal readouts, every class going to its
concrete representative and every branch letter to its generator; and the
quotient is nonzero. -/
theorem GrandTensor.ofProcess_spec (X : FiniteOperationalProcess O I N slot kraus) :
    (GrandTensor.ofProcess X).system = X.predictiveSystem ∧
    (∀ γ, (GrandTensor.ofProcess X).gen γ =
      (histIso X.canonicalRealization slot kraus)ᴴ *
        (X.canonicalRealization.typedBranches slot kraus).rep (FreeStarAlg.ι γ) *
          histIso X.canonicalRealization slot kraus) ∧
    (∃ e : (procAlg X.canonicalRealization slot kraus ⧸
          futureNull X.canonicalRealization slot kraus) ≃ₐ[ℂ]
        (GrandTensor.ofProcess X).historyAlgebra.toSubalgebra,
      ∀ q, (e (Ideal.Quotient.mk _ q) : Matrix (Fin (histRank X.canonicalRealization slot kraus))
          (Fin (histRank X.canonicalRealization slot kraus)) ℂ) =
        histQuotient X.canonicalRealization slot kraus q) ∧
    (∀ q, histQuotient X.canonicalRealization slot kraus q = 0 ↔
      q ∈ futureNull X.canonicalRealization slot kraus) ∧
    0 < histRank X.canonicalRealization slot kraus :=
  ⟨rfl, fun γ => rfl, histAlgebraEquivQuotient _ slot kraus,
    histQuotient_eq_zero_iff _ slot kraus, histRank_pos _ slot kraus⟩

/-- **Proposition `prop:ncg-grand-tensor-reconstruction`.**  Let `X`, `X'` be finite
operational processes over the same event grammar whose complete intervention
statistics coincide (equal probabilities for every tuple of trace-normalized
positive Choi probes, at every depth `k ≤ N`), and let `C`, `C'` be **any**
prefix-support-minimal sequential realizations of `X` and `X'`.  Then:

(i) the predictive laws coincide, hence so do `Z^min`, its branch probabilities
and its partial updates (and `Z^min` has the universal property of
`DerivedPredictiveCarrierUniversalExact`);

(ii) the represented process algebras are star isomorphic by a represented
isomorphism implemented by a Hilbert–Schmidt unitary, and the universal
future-separated history algebras are star isomorphic by an isomorphism carrying
every represented history word to its namesake;

(iii) the normalized regular traces correspond and every word-Gram layer
coincides;

(iv) the flat-depth criterion holds at exactly the same depths (so the least flat
depths agree), and at the least flat depth the panel reconstructs the history
algebra, multiplication and involution
(`flat_word_reconstruction`). -/
theorem grand_tensor_reconstruction_of_statistics [Nonempty I] [Fintype Arr]
    (X X' : FiniteOperationalProcess O I N slot kraus)
    (hstat : ∀ k, k ≤ N → ∀ M : Fin k → Matrix (O × I) (O × I) ℂ,
      (∀ j, (M j).PosSemidef ∧ ((M j).trace).re ≤ 1) → X.table k M = X'.table k M)
    (C C' : SequentialIsometricComb O I N)
    (hC : C.realizedChoi N = X.tensor N) (hC' : C'.realizedChoi N = X'.tensor N)
    (hmin : ∀ k, k ≤ N → IsPrefixSupportMinimal (C.cumulative k))
    (hmin' : ∀ k, k ≤ N → IsPrefixSupportMinimal (C'.cumulative k)) :
    X.predictiveSystem = X'.predictiveSystem ∧
    (∃ e : (C.typedBranches slot kraus).rep.range ≃⋆ₐ[ℂ] (C'.typedBranches slot kraus).rep.range,
      ∀ f, (e ⟨(C.typedBranches slot kraus).rep f, f, rfl⟩ :
        Matrix (HSI C') (HSI C') ℂ) = (C'.typedBranches slot kraus).rep f) ∧
    (∃ ψ : historyAlgebra (histGen C slot kraus) ≃⋆ₐ[ℂ] historyAlgebra (histGen C' slot kraus),
      (∀ w, ψ (wordElt (histGen C slot kraus) w) = wordElt (histGen C' slot kraus) w) ∧
      ∀ x, normalizedRegularTrace (historyAlgebra (histGen C' slot kraus)) (ψ x) =
        normalizedRegularTrace (historyAlgebra (histGen C slot kraus)) x) ∧
    (∀ r, wordGramLevel (histGen C' slot kraus) r = wordGramLevel (histGen C slot kraus) r) ∧
    (∀ r, ((gramPanel (histGen C slot kraus) r).rank =
        (gramPanel (histGen C slot kraus) (r + 1)).rank ↔
      (gramPanel (histGen C' slot kraus) r).rank =
        (gramPanel (histGen C' slot kraus) (r + 1)).rank)) ∧
    ∃ r : ℕ, ((gramPanel (histGen C slot kraus) r).rank =
        (gramPanel (histGen C slot kraus) (r + 1)).rank ∧
      ∀ r' < r, (gramPanel (histGen C slot kraus) r').rank ≠
        (gramPanel (histGen C slot kraus) (r' + 1)).rank) ∧
      historyWordSpan (histGen C slot kraus) r =
        Subalgebra.toSubmodule (historyAlgebra (histGen C slot kraus)).toSubalgebra := by
  classical
  have htab : ∀ k, k ≤ N → X.table k = X'.table k := fun k hk =>
    multilinear_eq_of_physical _ _ (hstat k hk)
  have hT : C.realizedChoi N = C'.realizedChoi N := by
    rw [hC, hC', FiniteOperationalProcess.tensor, FiniteOperationalProcess.tensor, htab N le_rfl]
  -- (i) equal predictive laws
  have hprob : ∀ h, X.eventProb h = X'.eventProb h := by
    intro h
    unfold FiniteOperationalProcess.eventProb
    split_ifs with hadm
    · rw [htab h.length (FiniteOperationalProcess.admissible_length_le hadm)]
    · rfl
  have hsys : X.predictiveSystem = X'.predictiveSystem := by
    have hcond : X.condProb = X'.condProb := by
      funext h w
      simp only [FiniteOperationalProcess.condProb, hprob]
    unfold FiniteOperationalProcess.predictiveSystem
    simp only [hcond]
  -- (ii) process representation
  obtain ⟨-, -, -, -, -, e, he⟩ :=
    typedBranches_realization_independent slot kraus C C' hmin hmin' hT
  -- (ii)-(iv) history algebra
  obtain ⟨ψ, hψw, hψτ, hgram, -, hflat⟩ :=
    histAlgebra_realization_independent slot kraus C C' hmin hmin' hT
  obtain ⟨-, r, hr, hex, -⟩ := flat_word_reconstruction_rank (histGen C slot kraus)
    (fun γ => ⟨star γ, (histGen_star C slot kraus γ).symm⟩)
  exact ⟨hsys, ⟨e, he⟩, ⟨ψ, hψw, hψτ⟩, hgram, hflat, r, hr, hex⟩

/-- The Grand Tensors of two processes with equal complete intervention statistics
are canonically isomorphic: equal predictive systems, star-isomorphic history
algebras compatible with every history word, equal regular traces and equal
word-Gram hierarchies. -/
theorem GrandTensor.ofProcess_eq_of_statistics [Nonempty I] [Fintype Arr]
    (X X' : FiniteOperationalProcess O I N slot kraus)
    (hstat : ∀ k, k ≤ N → ∀ M : Fin k → Matrix (O × I) (O × I) ℂ,
      (∀ j, (M j).PosSemidef ∧ ((M j).trace).re ≤ 1) → X.table k M = X'.table k M) :
    (GrandTensor.ofProcess X).system = (GrandTensor.ofProcess X').system ∧
    (∃ ψ : (GrandTensor.ofProcess X).historyAlgebra ≃⋆ₐ[ℂ] (GrandTensor.ofProcess X').historyAlgebra,
      (∀ w, ψ (wordElt (GrandTensor.ofProcess X).gen w) = wordElt (GrandTensor.ofProcess X').gen w) ∧
      ∀ x, (GrandTensor.ofProcess X').regularTrace (ψ x) = (GrandTensor.ofProcess X).regularTrace x) ∧
    ∀ r, (GrandTensor.ofProcess X').wordGram r = (GrandTensor.ofProcess X).wordGram r := by
  obtain ⟨hsys, -, ⟨ψ, hψw, hψτ⟩, hgram, -⟩ := grand_tensor_reconstruction_of_statistics X X'
    hstat X.canonicalRealization X'.canonicalRealization
    (X.canonicalRealization_realizedChoi N le_rfl) (X'.canonicalRealization_realizedChoi N le_rfl)
    (fun k hk => X.canonicalRealization_minimal k hk)
    (fun k hk => X'.canonicalRealization_minimal k hk)
  exact ⟨hsys, ⟨ψ, hψw, hψτ⟩, hgram⟩

end GrandTensorOfProcess

/-! ## Non-vacuity -/

section NonVacuity

open SequentialComb

/-- The qubit identity process (identity links on a qubit, trivial memory) as a
finite operational process: its tables are the intervention functionals of the
realized Choi tensors. -/
def qubitIdentityProcess (N : ℕ) {Arr K : Type} [Fintype K] (slot : Arr → Fin N)
    (kraus : Arr → K → Fin 2 × Fin 2 → ℂ) :
    FiniteOperationalProcess (Fin 2) (Fin 2) N slot kraus where
  table k := combPairing ((qubitIdentityComb N).realizedChoi k)
  deterministic := by
    have h : (fun k => combRepTensor (combPairing ((qubitIdentityComb N).realizedChoi k))) =
        (qubitIdentityComb N).realizedChoi :=
      funext fun k => combPairing_combRepTensor_of_eq _
    rw [h]
    exact (qubitIdentityComb N).realizedChoi_isDeterministic

/-- Non-vacuity of `def:ncg-grand-tensor`: the Grand Tensor of the qubit identity
process with one maximally-correlated intervention per slot exists and its history
algebra is a nonzero quotient. -/
example (N : ℕ) :
    0 < histRank (qubitIdentityProcess N (fun a : Fin N => a)
      (fun _ (_ : Unit) p => if p.1 = p.2 then (1 : ℂ) else 0)).canonicalRealization
      (fun a : Fin N => a) (fun _ (_ : Unit) p => if p.1 = p.2 then (1 : ℂ) else 0) :=
  (GrandTensor.ofProcess_spec _).2.2.2.2

/-- Non-vacuity of `prop:ncg-grand-tensor-reconstruction`: its hypotheses are met
by a process compared with itself through its canonical realization. -/
example (N : ℕ) :
    let X := qubitIdentityProcess N (fun a : Fin N => a)
      (fun _ (_ : Unit) p => if p.1 = p.2 then (1 : ℂ) else 0)
    X.predictiveSystem = X.predictiveSystem := by
  intro X
  exact (grand_tensor_reconstruction_of_statistics X X (fun _ _ _ _ => rfl)
    X.canonicalRealization X.canonicalRealization (X.canonicalRealization_realizedChoi N le_rfl)
    (X.canonicalRealization_realizedChoi N le_rfl) (fun k hk => X.canonicalRealization_minimal k hk)
    (fun k hk => X.canonicalRealization_minimal k hk)).1

end NonVacuity

end OperationalGrandTensor
end RenewalGeometry
