/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Predictive.WordGramPositivityExact

/-!
# Finite flat word reconstruction: the panel through depth `r_X + 1` reconstructs
  the history algebra (`thm:supp-word-flatness`, last clause; emergent-spacetime
  manuscript)

Let `gen : Γ → Matrix M M ℂ` and `gen' : Γ → Matrix M' M' ℂ` be two represented
generator families over the same letter alphabet `Γ`, both closed under the same
letter involution `inv` (`star (gen γ) = gen (inv γ)`, `star (gen' γ) = gen' (inv γ)`),
with history algebras `A = historyAlgebra gen`, `A' = historyAlgebra gen'` and word-Gram
panels `𝕂_{X,d} = gramPanel gen d`, `𝕂'_{X,d} = gramPanel gen' d`
(`eq:supp-word-gram`, regular trace `τ̂_reg`).

* `wordCombination gen d : (Words Γ d →₀ ℂ) →ₗ[ℂ] A`, `c ↦ ∑_v c_v [v]`, is the word
  coordinate map; its kernel is the represented word-relation space, detected by the
  panel: `c ∈ ker ↔ ∑_{v,w} conj(c_v) c_w 𝕂_{X,d}(v,w) = 0`
  (`mem_ker_wordCombination_iff`, faithfulness of `τ̂_reg`), so equal panels give equal
  kernels (`ker_wordCombination_eq_of_panel_eq`).
* At a flat depth `r` (`rank 𝕂_{X,r} = rank 𝕂_{X,r+1}`) the coordinate maps of depth
  `r` and `r+1` are onto `A` (`wordCombination_surjective_of_flat`, exhaustion clause
  of `FlatWordReconstructionExact`), and flatness transfers to `gen'` through the
  depth-`r` sub-panel (`gramPanel_eq_of_succ`).
* `panelEquiv` is the induced linear isomorphism `A ≃ₗ A'` with `[v] ↦ [v]'` for
  `|v| ≤ r+1`.  It is multiplicative because the depth-`(r+1)` panel encodes the
  generator multiplication matrices: `[γ]·(∑_v c_v [v]) = ∑_v c_v [γ v]` with
  `|v| ≤ r`, `|γ v| ≤ r+1` (`genElt_mul_wordCombination`), and it preserves the
  involution because reversed words reconstruct it:
  `[v]^* = [reverse (map inv v)]` (`star_wordCombination`).
* **`exists_starAlgEquiv_of_panel_eq`**: hence there is a star-algebra isomorphism
  `ψ : A ≃⋆ₐ[ℂ] A'` with `ψ [w] = [w]'` for **every** history word `w` — the panel
  through depth `r_X+1` reconstructs the unit, the multiplication, the involution and
  every represented (mixed) history; `mem_core_iff_of_panel_eq`: `ψ` matches the
  predictive core algebras `StarAlgebra.adjoin ℂ (gen '' Δ)` generated by any sub-alphabet
  `Δ ⊆ Γ` (in particular the minimum predictive state algebra).
* **`flat_word_reconstruction`**: `thm:supp-word-flatness` in full: positivity of every
  panel, the least flat depth `r_X` with `eq:supp-flat-stop`, exhaustion and constancy
  of the word spans from `r_X` on, and the reconstruction statement above at `r_X`.

Disclosed rendering: "the panel through depth `r_X+1` reconstructs the object" is
formalised as reconstruction up to star-isomorphism compatible with the word labels:
any other represented family over the same alphabet and letter involution with the
same depth-`(r_X+1)` panel has a canonically isomorphic history algebra, core algebras
and represented histories.  Scoped hypotheses: nonempty finite carriers, finite alphabet
(`Fintype (Words Γ d)`), and the letter involution `inv` is part of the data (the
paper's generator families are closed under the Hilbert–Schmidt adjoint letter by letter).
-/

open Matrix Module ComplexConjugate

namespace RenewalGeometry

open FiniteGrandTensor (historyAlgebra wordOp wordOp_mem wordOp_append Words wordGramLevel
  historyWordSpan gen_mem_historyAlgebra historyWordSpan_eq_historyAlgebra_of_flat
  exists_least_flat_depth)

noncomputable section

section Setup

variable {M : Type*} [Fintype M] [DecidableEq M] {Γ : Type*}

/-- The represented generator `[γ]` as an element of `A^hist`. -/
def genElt (gen : Γ → Matrix M M ℂ) (γ : Γ) : historyAlgebra gen :=
  ⟨gen γ, gen_mem_historyAlgebra gen γ⟩

theorem wordElt_nil (gen : Γ → Matrix M M ℂ) : wordElt gen [] = 1 := Subtype.ext rfl

theorem wordElt_cons (gen : Γ → Matrix M M ℂ) (γ : Γ) (w : List Γ) :
    wordElt gen (γ :: w) = genElt gen γ * wordElt gen w := Subtype.ext rfl

theorem wordElt_singleton (gen : Γ → Matrix M M ℂ) (γ : Γ) :
    wordElt gen [γ] = genElt gen γ := by
  rw [wordElt_cons, wordElt_nil, mul_one]

/-- The word coordinate map `T_d : (Words Γ d →₀ ℂ) → A^hist`, `c ↦ ∑_v c_v [v]`. -/
def wordCombination (gen : Γ → Matrix M M ℂ) (d : ℕ) :
    (Words Γ d →₀ ℂ) →ₗ[ℂ] historyAlgebra gen :=
  Finsupp.linearCombination ℂ (fun v : Words Γ d => wordElt gen v.1)

theorem wordCombination_single (gen : Γ → Matrix M M ℂ) (d : ℕ) (v : Words Γ d) :
    wordCombination gen d (Finsupp.single v 1) = wordElt gen v.1 := by
  simp [wordCombination, Finsupp.linearCombination_single]

theorem wordCombination_apply (gen : Γ → Matrix M M ℂ) (d : ℕ) [Fintype (Words Γ d)]
    (c : Words Γ d →₀ ℂ) :
    wordCombination gen d c = ∑ v, c v • wordElt gen v.1 := by
  rw [wordCombination, Finsupp.linearCombination_apply, Finsupp.sum_fintype]
  intro v; simp

/-- The inclusion `Words Γ d → Words Γ (d+1)`. -/
def inclWord (d : ℕ) (v : Words Γ d) : Words Γ (d + 1) := ⟨v.1, v.2.trans (Nat.le_succ d)⟩

/-- Prepending a letter, `Words Γ d → Words Γ (d+1)`. -/
def consWord (γ : Γ) (d : ℕ) (v : Words Γ d) : Words Γ (d + 1) :=
  ⟨γ :: v.1, by simp only [List.length_cons]; exact Nat.succ_le_succ v.2⟩

/-- The reversed-involuted word `v ↦ reverse (map inv v)`, `Words Γ d → Words Γ d`. -/
def adjWord (inv : Γ → Γ) (d : ℕ) (v : Words Γ d) : Words Γ d :=
  ⟨(v.1.map inv).reverse, by simp only [List.length_reverse, List.length_map]; exact v.2⟩

theorem wordCombination_mapDomain_incl (gen : Γ → Matrix M M ℂ) (d : ℕ)
    (c : Words Γ d →₀ ℂ) :
    wordCombination gen (d + 1) (Finsupp.mapDomain (inclWord d) c) = wordCombination gen d c := by
  rw [wordCombination, wordCombination, Finsupp.linearCombination_mapDomain]
  rfl

/-- The depth-`(d+1)` coordinates encode left multiplication by a generator:
`[γ] · ∑_v c_v [v] = ∑_v c_v [γ v]`. -/
theorem genElt_mul_wordCombination (gen : Γ → Matrix M M ℂ) (d : ℕ) (γ : Γ)
    (c : Words Γ d →₀ ℂ) :
    genElt gen γ * wordCombination gen d c =
      wordCombination gen (d + 1) (Finsupp.mapDomain (consWord γ d) c) := by
  rw [wordCombination, wordCombination, Finsupp.linearCombination_mapDomain,
    Finsupp.linearCombination_apply, Finsupp.linearCombination_apply, Finsupp.mul_sum]
  refine Finset.sum_congr rfl fun v _ => ?_
  beta_reduce
  rw [Function.comp_apply, mul_smul_comm]
  rfl

/-- Reversed words reconstruct the involution: `[w]^* = [reverse (map inv w)]`. -/
theorem star_wordOp (gen : Γ → Matrix M M ℂ) (inv : Γ → Γ)
    (hstar : ∀ γ, star (gen γ) = gen (inv γ)) (w : List Γ) :
    star (wordOp gen w) = wordOp gen ((w.map inv).reverse) := by
  induction w with
  | nil => simp
  | cons γ w ih =>
    rw [FiniteGrandTensor.wordOp_cons, star_mul, ih, List.map_cons, List.reverse_cons,
      wordOp_append, FiniteGrandTensor.wordOp_cons, FiniteGrandTensor.wordOp_nil, mul_one, hstar]

theorem star_wordElt (gen : Γ → Matrix M M ℂ) (inv : Γ → Γ)
    (hstar : ∀ γ, star (gen γ) = gen (inv γ)) (w : List Γ) :
    star (wordElt gen w) = wordElt gen ((w.map inv).reverse) :=
  Subtype.ext (star_wordOp gen inv hstar w)

/-- The adjoint coordinates `c ↦ conj c ∘ adjWord⁻¹`. -/
def adjCoeff (inv : Γ → Γ) (d : ℕ) (c : Words Γ d →₀ ℂ) : Words Γ d →₀ ℂ :=
  Finsupp.mapDomain (adjWord inv d) (Finsupp.mapRange (starRingEnd ℂ) (map_zero _) c)

/-- `(∑_v c_v [v])^* = ∑_v conj(c_v) [reverse (map inv v)]`. -/
theorem star_wordCombination (gen : Γ → Matrix M M ℂ) (inv : Γ → Γ)
    (hstar : ∀ γ, star (gen γ) = gen (inv γ)) (d : ℕ) (c : Words Γ d →₀ ℂ) :
    star (wordCombination gen d c) = wordCombination gen d (adjCoeff inv d c) := by
  rw [adjCoeff, wordCombination, Finsupp.linearCombination_mapDomain,
    Finsupp.linearCombination_apply, Finsupp.linearCombination_apply,
    Finsupp.sum_mapRange_index]
  · rw [Finsupp.sum, Finsupp.sum, star_sum]
    refine Finset.sum_congr rfl fun v _ => ?_
    rw [star_smul, Complex.star_def, star_wordElt gen inv hstar]
    rfl
  · intro v; simp

end Setup

/-! ### Kernel and range of the word coordinate map -/

section KernelRange

variable {M : Type*} [Fintype M] [DecidableEq M] {Γ : Type*}

/-- The kernel of the word coordinate map is the Gram kernel of the panel:
`c ∈ ker T_d ↔ ∑_{v,w} conj(c_v) c_w 𝕂_{X,d}(v,w) = 0` (faithfulness of `τ̂_reg`). -/
theorem mem_ker_wordCombination_iff [Nonempty M] (gen : Γ → Matrix M M ℂ) (d : ℕ)
    [Fintype (Words Γ d)] (c : Words Γ d →₀ ℂ) :
    c ∈ LinearMap.ker (wordCombination gen d) ↔
      ∑ v, ∑ w, star (c v) * c w * gramPanel gen d v w = 0 := by
  rw [LinearMap.mem_ker, wordCombination_apply]
  have hq := wordGram_quadForm (normalizedRegularTrace (historyAlgebra gen))
    (fun v : Words Γ d => wordElt gen v.1) (fun v => c v)
  have hpanel : ∀ v w, gramPanel gen d v w =
      RenewalGeometry.wordGram (normalizedRegularTrace (historyAlgebra gen))
        (fun u : Words Γ d => wordElt gen u.1) v w := fun v w => rfl
  simp_rw [hpanel]
  rw [hq]
  exact (normalizedRegularTrace_star_mul_self_eq_zero_iff _ _).symm

/-- The sub-panel of depth `d` inside the panel of depth `d+1`. -/
theorem gramPanel_eq_submatrix (gen : Γ → Matrix M M ℂ) (d : ℕ) :
    gramPanel gen d = (gramPanel gen (d + 1)).submatrix (inclWord d) (inclWord d) := rfl

/-- The range of the word coordinate map, pushed to matrices, is the word span. -/
theorem map_range_wordCombination (gen : Γ → Matrix M M ℂ) (d : ℕ) :
    (LinearMap.range (wordCombination gen d)).map
        (Subalgebra.val (historyAlgebra gen).toSubalgebra).toLinearMap
      = historyWordSpan gen d := by
  rw [wordCombination, Finsupp.range_linearCombination, Submodule.map_span,
    historyWordSpan_eq_span]
  congr 1
  ext x
  simp only [Set.mem_image, Set.mem_range, exists_exists_eq_and]
  rfl

/-- At a flat depth `r`, the word coordinate maps of every depth `d ≥ r` are onto `A^hist`. -/
theorem wordCombination_surjective_of_flat (gen : Γ → Matrix M M ℂ)
    (hstar : ∀ γ, ∃ γ', star (gen γ) = gen γ') (r : ℕ)
    (hflat : finrank ℂ (historyWordSpan gen (r + 1)) ≤ finrank ℂ (historyWordSpan gen r))
    (d : ℕ) (hd : r ≤ d) : Function.Surjective (wordCombination gen d) := by
  obtain ⟨hex, hconst⟩ := historyWordSpan_eq_historyAlgebra_of_flat gen hstar r hflat
  rw [← LinearMap.range_eq_top]
  set ι : historyAlgebra gen →ₗ[ℂ] Matrix M M ℂ :=
    (Subalgebra.val (historyAlgebra gen).toSubalgebra).toLinearMap with hι
  have hιinj : Function.Injective ι := Subtype.val_injective
  apply Submodule.map_injective_of_injective hιinj
  rw [map_range_wordCombination, hconst d hd, hex, Submodule.map_top, LinearMap.range_eq_map]
  ext x
  simp only [Subalgebra.mem_toSubmodule, Submodule.mem_map, Submodule.mem_top, true_and]
  constructor
  · intro hx; exact ⟨⟨x, hx⟩, rfl⟩
  · rintro ⟨y, rfl⟩; exact y.2

end KernelRange

/-! ### The reconstruction isomorphism -/

section Reconstruction

variable {M M' : Type*} [Fintype M] [DecidableEq M] [Fintype M'] [DecidableEq M'] {Γ : Type*}

/-- Equal panels give equal word-relation spaces. -/
theorem ker_wordCombination_eq_of_panel_eq [Nonempty M] [Nonempty M'] (gen : Γ → Matrix M M ℂ)
    (gen' : Γ → Matrix M' M' ℂ) (d : ℕ) [Fintype (Words Γ d)]
    (hpanel : gramPanel gen d = gramPanel gen' d) :
    LinearMap.ker (wordCombination gen d) = LinearMap.ker (wordCombination gen' d) := by
  ext c
  rw [mem_ker_wordCombination_iff, mem_ker_wordCombination_iff, hpanel]

/-- The linear isomorphism `A^hist ≃ A'^hist` induced by two onto word coordinate maps
with the same kernel. -/
def panelEquiv (gen : Γ → Matrix M M ℂ) (gen' : Γ → Matrix M' M' ℂ) (d : ℕ)
    (hs : Function.Surjective (wordCombination gen d))
    (hs' : Function.Surjective (wordCombination gen' d))
    (hker : LinearMap.ker (wordCombination gen d) = LinearMap.ker (wordCombination gen' d)) :
    historyAlgebra gen ≃ₗ[ℂ] historyAlgebra gen' :=
  (LinearMap.quotKerEquivOfSurjective _ hs).symm.trans
    ((Submodule.quotEquivOfEq _ _ hker).trans (LinearMap.quotKerEquivOfSurjective _ hs'))

theorem panelEquiv_wordCombination (gen : Γ → Matrix M M ℂ) (gen' : Γ → Matrix M' M' ℂ) (d : ℕ)
    (hs : Function.Surjective (wordCombination gen d))
    (hs' : Function.Surjective (wordCombination gen' d))
    (hker : LinearMap.ker (wordCombination gen d) = LinearMap.ker (wordCombination gen' d))
    (c : Words Γ d →₀ ℂ) :
    panelEquiv gen gen' d hs hs' hker (wordCombination gen d c) = wordCombination gen' d c := by
  unfold panelEquiv
  have h1 : (LinearMap.quotKerEquivOfSurjective _ hs).symm (wordCombination gen d c)
      = Submodule.Quotient.mk c := by
    rw [LinearEquiv.symm_apply_eq, LinearMap.quotKerEquivOfSurjective_apply_mk]
  rw [LinearEquiv.trans_apply, LinearEquiv.trans_apply, h1, Submodule.quotEquivOfEq_mk,
    LinearMap.quotKerEquivOfSurjective_apply_mk]

theorem panelEquiv_wordElt (gen : Γ → Matrix M M ℂ) (gen' : Γ → Matrix M' M' ℂ) (d : ℕ)
    (hs : Function.Surjective (wordCombination gen d))
    (hs' : Function.Surjective (wordCombination gen' d))
    (hker : LinearMap.ker (wordCombination gen d) = LinearMap.ker (wordCombination gen' d))
    (v : Words Γ d) :
    panelEquiv gen gen' d hs hs' hker (wordElt gen v.1) = wordElt gen' v.1 := by
  rw [← wordCombination_single, panelEquiv_wordCombination, wordCombination_single]

/-- Membership in `A^hist` from membership in the generated (star-closed) subalgebra. -/
theorem mem_historyAlgebra_of_mem_adjoin (gen : Γ → Matrix M M ℂ) {x : Matrix M M ℂ}
    (hx : x ∈ Algebra.adjoin ℂ (Set.range gen ∪ star (Set.range gen))) :
    x ∈ historyAlgebra gen := by
  change x ∈ (historyAlgebra gen).toSubalgebra
  rw [historyAlgebra, StarAlgebra.adjoin_toSubalgebra]
  exact hx

theorem mem_adjoin_of_mem_historyAlgebra (gen : Γ → Matrix M M ℂ) {x : Matrix M M ℂ}
    (hx : x ∈ historyAlgebra gen) :
    x ∈ Algebra.adjoin ℂ (Set.range gen ∪ star (Set.range gen)) := by
  have h : x ∈ (historyAlgebra gen).toSubalgebra := hx
  rwa [historyAlgebra, StarAlgebra.adjoin_toSubalgebra] at h

/-- **The panel through depth `r+1` reconstructs the algebra.**  If `r` is a flat depth
for `gen` and the depth-`(r+1)` panels of `gen` and `gen'` agree, there is a
star-algebra isomorphism `ψ : A^hist ≃⋆ₐ[ℂ] A'^hist` with `ψ [w] = [w]'` for every history
word `w` (in particular the units, the generator multiplication, the involution and every
represented mixed history are reconstructed). -/
theorem exists_starAlgEquiv_of_panel_eq [Nonempty M] [Nonempty M'] [∀ d, Fintype (Words Γ d)]
    (gen : Γ → Matrix M M ℂ) (gen' : Γ → Matrix M' M' ℂ) (inv : Γ → Γ)
    (hstar : ∀ γ, star (gen γ) = gen (inv γ)) (hstar' : ∀ γ, star (gen' γ) = gen' (inv γ))
    (r : ℕ) (hflat : (gramPanel gen r).rank = (gramPanel gen (r + 1)).rank)
    (hpanel : gramPanel gen (r + 1) = gramPanel gen' (r + 1)) :
    ∃ ψ : historyAlgebra gen ≃⋆ₐ[ℂ] historyAlgebra gen',
      ∀ w : List Γ, ψ (wordElt gen w) = wordElt gen' w := by
  have hstar₁ : ∀ γ, ∃ γ', star (gen γ) = gen γ' := fun γ => ⟨inv γ, hstar γ⟩
  have hstar₁' : ∀ γ, ∃ γ', star (gen' γ) = gen' γ' := fun γ => ⟨inv γ, hstar' γ⟩
  -- flatness of `gen` in dimension form, and its transfer to `gen'`
  have hflatd : finrank ℂ (historyWordSpan gen (r + 1)) ≤ finrank ℂ (historyWordSpan gen r) := by
    rw [← rank_gramPanel, ← rank_gramPanel]; exact hflat.symm.le
  have hpanel_r : gramPanel gen r = gramPanel gen' r := by
    rw [gramPanel_eq_submatrix gen r, gramPanel_eq_submatrix gen' r, hpanel]
  have hflatd' : finrank ℂ (historyWordSpan gen' (r + 1)) ≤ finrank ℂ (historyWordSpan gen' r) := by
    rw [← rank_gramPanel, ← rank_gramPanel, ← hpanel, ← hpanel_r]; exact hflat.symm.le
  have hs : Function.Surjective (wordCombination gen (r + 1)) :=
    wordCombination_surjective_of_flat gen hstar₁ r hflatd (r + 1) (Nat.le_succ r)
  have hsr : Function.Surjective (wordCombination gen r) :=
    wordCombination_surjective_of_flat gen hstar₁ r hflatd r le_rfl
  have hs' : Function.Surjective (wordCombination gen' (r + 1)) :=
    wordCombination_surjective_of_flat gen' hstar₁' r hflatd' (r + 1) (Nat.le_succ r)
  have hker := ker_wordCombination_eq_of_panel_eq gen gen' (r + 1) hpanel
  set e := panelEquiv gen gen' (r + 1) hs hs' hker with he
  have he_comb : ∀ c, e (wordCombination gen (r + 1) c) = wordCombination gen' (r + 1) c :=
    panelEquiv_wordCombination gen gen' (r + 1) hs hs' hker
  have he_comb_r : ∀ c, e (wordCombination gen r c) = wordCombination gen' r c := by
    intro c
    rw [← wordCombination_mapDomain_incl, he_comb, wordCombination_mapDomain_incl]
  have he_word : ∀ w : List Γ, w.length ≤ r + 1 → e (wordElt gen w) = wordElt gen' w :=
    fun w hw => panelEquiv_wordElt gen gen' (r + 1) hs hs' hker ⟨w, hw⟩
  -- unit
  have he_one : e 1 = 1 := by
    rw [← wordElt_nil, he_word [] (Nat.zero_le _), wordElt_nil]
  -- generators
  have he_gen : ∀ γ, e (genElt gen γ) = genElt gen' γ := by
    intro γ
    rw [← wordElt_singleton, he_word [γ] (by simp), wordElt_singleton]
  have he_gen_mul : ∀ γ (y : historyAlgebra gen), e (genElt gen γ * y) = genElt gen' γ * e y := by
    intro γ y
    obtain ⟨c, rfl⟩ := hsr y
    rw [genElt_mul_wordCombination, he_comb, he_comb_r, genElt_mul_wordCombination]
  -- multiplicativity on the generated algebra
  have he_mul_adj : ∀ x ∈ Algebra.adjoin ℂ (Set.range gen ∪ star (Set.range gen)),
      ∀ (hx : x ∈ historyAlgebra gen) (y : historyAlgebra gen),
        e (⟨x, hx⟩ * y) = e ⟨x, hx⟩ * e y := by
    intro x hx
    induction hx using Algebra.adjoin_induction with
    | mem x hx =>
      intro hx' y
      have hgen : ∃ γ, gen γ = x := by
        rcases hx with ⟨γ, rfl⟩ | hx
        · exact ⟨γ, rfl⟩
        · obtain ⟨γ, hγ⟩ := Set.mem_star.mp hx
          exact ⟨inv γ, by rw [← hstar, hγ, star_star]⟩
      obtain ⟨γ, rfl⟩ := hgen
      have : (⟨gen γ, hx'⟩ : historyAlgebra gen) = genElt gen γ := rfl
      rw [this, he_gen_mul, he_gen]
    | algebraMap c =>
      intro hx' y
      have : (⟨algebraMap ℂ (Matrix M M ℂ) c, hx'⟩ : historyAlgebra gen) = c • 1 :=
        Subtype.ext (Algebra.algebraMap_eq_smul_one c)
      rw [this, smul_mul_assoc, one_mul, map_smul, map_smul, he_one, smul_mul_assoc, one_mul]
    | add x z hx hz ihx ihz =>
      intro hxz y
      have hx' := mem_historyAlgebra_of_mem_adjoin gen hx
      have hz' := mem_historyAlgebra_of_mem_adjoin gen hz
      have : (⟨x + z, hxz⟩ : historyAlgebra gen) = ⟨x, hx'⟩ + ⟨z, hz'⟩ := rfl
      rw [this, add_mul, map_add, map_add, ihx hx' y, ihz hz' y, add_mul]
    | mul x z hx hz ihx ihz =>
      intro hxz y
      have hx' := mem_historyAlgebra_of_mem_adjoin gen hx
      have hz' := mem_historyAlgebra_of_mem_adjoin gen hz
      have : (⟨x * z, hxz⟩ : historyAlgebra gen) = ⟨x, hx'⟩ * ⟨z, hz'⟩ := rfl
      rw [this, mul_assoc, ihx hx' _, ihz hz' y, ihx hx' ⟨z, hz'⟩, mul_assoc]
  have he_mul : ∀ x y : historyAlgebra gen, e (x * y) = e x * e y := by
    intro x y
    exact he_mul_adj x (mem_adjoin_of_mem_historyAlgebra gen x.2) x.2 y
  -- involution
  have he_star : ∀ x : historyAlgebra gen, e (star x) = star (e x) := by
    intro x
    obtain ⟨c, rfl⟩ := hs x
    rw [star_wordCombination gen inv hstar, he_comb, he_comb, star_wordCombination gen' inv hstar']
  -- assemble
  let ψ : historyAlgebra gen ≃⋆ₐ[ℂ] historyAlgebra gen' :=
    StarAlgEquiv.ofAlgEquiv (AlgEquiv.ofLinearEquiv e he_one he_mul) he_star
  have hψ : ∀ x, ψ x = e x := fun x => rfl
  refine ⟨ψ, fun w => ?_⟩
  induction w with
  | nil => rw [wordElt_nil, wordElt_nil, map_one]
  | cons γ w ih => rw [wordElt_cons, map_mul, ih, hψ, he_gen, wordElt_cons]

/-- The predictive core algebra generated by the sub-alphabet `Δ ⊆ Γ`. -/
def coreAlgebra (gen : Γ → Matrix M M ℂ) (Δ : Set Γ) : StarSubalgebra ℂ (Matrix M M ℂ) :=
  StarAlgebra.adjoin ℂ (gen '' Δ)

theorem coreAlgebra_le (gen : Γ → Matrix M M ℂ) (Δ : Set Γ) :
    coreAlgebra gen Δ ≤ historyAlgebra gen :=
  StarAlgebra.adjoin_mono (Set.image_subset_range gen Δ)

/-- The core algebra inside `A^hist` is the star-subalgebra generated by `[γ]`, `γ ∈ Δ`. -/
theorem mem_coreAlgebra_iff (gen : Γ → Matrix M M ℂ) (Δ : Set Γ) (x : historyAlgebra gen) :
    (x : Matrix M M ℂ) ∈ coreAlgebra gen Δ ↔ x ∈ StarAlgebra.adjoin ℂ (genElt gen '' Δ) := by
  have hmap : (StarAlgebra.adjoin ℂ (genElt gen '' Δ)).map (historyAlgebra gen).subtype
      = coreAlgebra gen Δ := by
    rw [StarAlgHom.map_adjoin, coreAlgebra, Set.image_image]
    rfl
  constructor
  · intro hx
    rw [← hmap, StarSubalgebra.mem_map] at hx
    obtain ⟨y, hy, hyx⟩ := hx
    have : y = x := Subtype.ext hyx
    rwa [← this]
  · intro hx
    rw [← hmap, StarSubalgebra.mem_map]
    exact ⟨x, hx, rfl⟩

/-- A star-isomorphism `ψ` with `ψ [γ] = [γ]'` matches the predictive core algebras of every
sub-alphabet `Δ`: `x ∈ core_Δ(A) ↔ ψ x ∈ core_Δ(A')`. -/
theorem mem_core_iff_of_wordElt_eq (gen : Γ → Matrix M M ℂ) (gen' : Γ → Matrix M' M' ℂ)
    (ψ : historyAlgebra gen ≃⋆ₐ[ℂ] historyAlgebra gen')
    (hψ : ∀ w : List Γ, ψ (wordElt gen w) = wordElt gen' w) (Δ : Set Γ)
    (x : historyAlgebra gen) :
    (x : Matrix M M ℂ) ∈ coreAlgebra gen Δ ↔ (ψ x : Matrix M' M' ℂ) ∈ coreAlgebra gen' Δ := by
  rw [mem_coreAlgebra_iff, mem_coreAlgebra_iff]
  have hgen : ∀ γ, ψ (genElt gen γ) = genElt gen' γ := by
    intro γ
    rw [← wordElt_singleton, hψ, wordElt_singleton]
  have hmap : (StarAlgebra.adjoin ℂ (genElt gen '' Δ)).map (ψ : historyAlgebra gen →⋆ₐ[ℂ] _)
      = StarAlgebra.adjoin ℂ (genElt gen' '' Δ) := by
    rw [StarAlgHom.map_adjoin, Set.image_image]
    congr 2
    funext γ
    exact hgen γ
  rw [← hmap, StarSubalgebra.mem_map]
  constructor
  · intro hx; exact ⟨x, hx, rfl⟩
  · rintro ⟨y, hy, hyx⟩
    have : y = x := ψ.injective hyx
    rwa [← this]

end Reconstruction

/-! ### `thm:supp-word-flatness` in full -/

section Full

variable {M : Type*} [Fintype M] [DecidableEq M] {Γ : Type*}

/-- **`thm:supp-word-flatness` (Finite flat word reconstruction).**  For a represented
generator family `gen` on a nonempty finite carrier, closed under the letter involution
`inv`: every panel `𝕂_{X,r}` is positive; there is a least depth `r_X` with
`rank 𝕂_{X,r_X} = rank 𝕂_{X,r_X+1}` (`eq:supp-flat-stop`); at this depth the represented
word span is the whole history algebra and the spans are constant from `r_X` on; and the
panel through depth `r_X+1` reconstructs the object: any represented family `gen'` over
the same alphabet and involution (on any nonempty finite carrier) with the same
depth-`(r_X+1)` panel has a star-isomorphic history algebra, `ψ : A ≃⋆ₐ[ℂ] A'` with
`ψ [w] = [w]'` for every history word `w` (units, multiplication, involution and every
represented mixed history), matching the predictive core algebras of every sub-alphabet. -/
theorem flat_word_reconstruction [Nonempty M] (gen : Γ → Matrix M M ℂ)
    [∀ r, Fintype (Words Γ r)] (inv : Γ → Γ) (hstar : ∀ γ, star (gen γ) = gen (inv γ)) :
    (∀ (r : ℕ) (c : Words Γ r → ℂ),
        0 ≤ (∑ v, ∑ w, star (c v) * c w * wordGramLevel gen r v w).re) ∧
    ∃ r : ℕ,
      ((gramPanel gen r).rank = (gramPanel gen (r + 1)).rank ∧
        ∀ r' < r, (gramPanel gen r').rank ≠ (gramPanel gen (r' + 1)).rank) ∧
      historyWordSpan gen r = Subalgebra.toSubmodule (historyAlgebra gen).toSubalgebra ∧
      (∀ s, r ≤ s → historyWordSpan gen s = historyWordSpan gen r) ∧
      ∀ (M' : Type*) [Fintype M'] [DecidableEq M'] [Nonempty M'] (gen' : Γ → Matrix M' M' ℂ),
        (∀ γ, star (gen' γ) = gen' (inv γ)) →
        gramPanel gen (r + 1) = gramPanel gen' (r + 1) →
        ∃ ψ : historyAlgebra gen ≃⋆ₐ[ℂ] historyAlgebra gen',
          (∀ w : List Γ, ψ (wordElt gen w) = wordElt gen' w) ∧
          ∀ (Δ : Set Γ) (x : historyAlgebra gen),
            (x : Matrix M M ℂ) ∈ coreAlgebra gen Δ ↔
              (ψ x : Matrix M' M' ℂ) ∈ coreAlgebra gen' Δ := by
  obtain ⟨hpos, r, hr, hex, hconst⟩ :=
    flat_word_reconstruction_rank gen (fun γ => ⟨inv γ, hstar γ⟩)
  refine ⟨hpos, r, hr, hex, hconst, ?_⟩
  intro M' _ _ _ gen' hstar' hpanel
  obtain ⟨ψ, hψ⟩ := exists_starAlgEquiv_of_panel_eq gen gen' inv hstar hstar' r hr.1 hpanel
  exact ⟨ψ, hψ, fun Δ x => mem_core_iff_of_wordElt_eq gen gen' ψ hψ Δ x⟩

end Full

end

end RenewalGeometry
