/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Predictive.GrandTensorMonoidalExact

/-!
# Iterated independent composition and its coherence
(`prop:supp-grand-monoidal`, emergent-spacetime manuscript)

Completion of `GrandTensorMonoidalExact`:

* **Span-closed context families.**  `SpanContextClosed C` (inserting represented elements on
  either side of a context stays in the linear span of the family) relaxes `ContextClosed`;
  the null set of `C` equals that of `span C` (`contextualNull_span`), and
  `SpanHistoryAlgebra C = 𝒜^raw / 𝒥^ctx(C)`.  The product contextual test family
  `productContexts C₁ C₂` of two span-closed families is span-closed
  (`productContexts_spanContextClosed`), so independent composites **iterate**.
* `compositeSpanEquiv` — `𝒜₁₂^hist ≃ 𝒜₁^hist ⊗ 𝒜₂^hist` for the product contextual family
  itself, `[r₁ ⊗ r₂] ↦ [r₁] ⊗ [r₂]`; `compositeSpanMoment` — the word-moment product law.
* **Coherence of the history-algebra identification.**  `spanHistoryComm`, `spanHistoryAssoc`
  are the history-algebra isomorphisms induced by interchange and reassociation of the raw
  factors; `compositeSpanEquiv_comm`, `compositeSpanEquiv_assoc` are the naturality squares
  with `Algebra.TensorProduct.comm` / `Algebra.TensorProduct.assoc`.
* **Coherence of the predictive identification.**  `indepProduct_comm_probability`,
  `indepProduct_assoc_probability` (the composite laws are interchange/reassociation
  invariant), `IdentityOperation.prod`, `minimalSwap`, `minimalAssoc` and the squares
  `indepProductMinimalEquiv_comm`, `indepProductMinimalEquiv_assoc` with `Equiv.prodComm` /
  `Equiv.prodAssoc`.
* **Typed product.**  `TypedPredictiveSystem` (cut-typed histories; histories of different cut
  type are never identified), `typedIndepProduct` (cut types `O₁ × O₂`),
  `typedIndepProductMinimalEquiv : Z₁₂^min ≃ Z₁^min × Z₂^min` preserving cut types, its
  fibrewise form `typedIndepProductFibreEquiv : Z₁₂,(x₁,x₂)^min ≃ Z₁,x₁^min × Z₂,x₂^min`, and
  its interchange/reassociation squares.
* **Unitary covariance, concrete form.**  `adjoinConjStarAlgEquiv`: a unitary `U : H ≃ H'`
  induces a `*`-isomorphism `a ↦ U a U^*` from the `*`-algebra generated by the represented
  operators `S` onto the one generated by `U S U^*`; `recordContexts` (record matrix
  coefficients `⟪u, x a y v⟫` of left/right history contexts) is context-closed and is carried
  to the record contexts of `U(rec)`; `unitary_history_covariance`: the induced isomorphism of
  history algebras is compatible with the involution and preserves all word moments.
* **Generated composite algebra.**  `generatedCompositeEquiv`: for represented matrix algebras
  `R₁ ⊆ M_n`, `R₂ ⊆ M_m`, the algebra generated by the independently accessible generators
  `a ⊗ I`, `I ⊗ b` is `R₁ ⊗ R₂` (`a ⊗ b ↦ a ⊗ₖ b`; injectivity over a field), which justifies
  taking `R₁ ⊗ R₂` as the composite raw algebra.
* `grand_monoidal_composite` — the packaged composition statement.
-/

open scoped TensorProduct

namespace RenewalGeometry

namespace GrandTensorMonoidal

open Module

/-! ## Span-closed context families -/

section SpanClosed

variable {K : Type*} [Field K]

/-- A context family is span-closed when inserting represented elements on either side of an
admitted context gives a linear combination of admitted contexts. -/
def SpanContextClosed {R : Type*} [Ring R] [Algebra K R] (C : Set (Dual K R)) : Prop :=
  ∀ φ ∈ C, ∀ x y : R,
    φ ∘ₗ (LinearMap.mulLeft K x ∘ₗ LinearMap.mulRight K y) ∈ Submodule.span K C

variable {R : Type*} [Ring R] [Algebra K R]

theorem ContextClosed.spanContextClosed {C : Set (Dual K R)} (hC : ContextClosed C) :
    SpanContextClosed C :=
  fun φ hφ x y => Submodule.subset_span (hC φ hφ x y)

/-- The linear span of a span-closed family is closed under insertion. -/
theorem contextClosed_span {C : Set (Dual K R)} (hC : SpanContextClosed C) :
    ContextClosed (Submodule.span K C : Set (Dual K R)) := by
  intro ψ hψ x y
  have hle : Submodule.span K C ≤ (Submodule.span K C).comap
      (LinearMap.lcomp K K (LinearMap.mulLeft K x ∘ₗ LinearMap.mulRight K y)) := by
    rw [Submodule.span_le]
    intro φ hφ
    exact hC φ hφ x y
  exact hle hψ

/-- A family and its linear span have the same null elements. -/
theorem contextualNull_span (C : Set (Dual K R)) :
    contextualNull (Submodule.span K C : Set (Dual K R)) = contextualNull C := by
  ext a
  constructor
  · intro h φ hφ
    exact h φ (Submodule.subset_span hφ)
  · intro h ψ hψ
    have hle : Submodule.span K C ≤ LinearMap.ker (Module.Dual.eval K R a) := by
      rw [Submodule.span_le]
      intro φ hφ
      exact h φ hφ
    exact hle hψ

/-- Families squeezed between `C` and `span C` have the null elements of `C`. -/
theorem contextualNull_eq_of_subset_span {C C' : Set (Dual K R)} (h₁ : C ⊆ C')
    (h₂ : C' ⊆ Submodule.span K C) : contextualNull C' = contextualNull C := by
  apply le_antisymm
  · intro a ha φ hφ
    exact ha φ (h₁ hφ)
  · intro a ha ψ hψ
    rw [← contextualNull_span] at ha
    exact ha ψ (h₂ hψ)

/-- `eq:supp-history-algebra` for a span-closed family: `𝒜^hist = 𝒜^raw / 𝒥^ctx`, the
quotient by the elements null in every admitted context. -/
abbrev SpanHistoryAlgebra (C : Set (Dual K R)) (hC : SpanContextClosed C) : Type _ :=
  HistoryAlgebra (Submodule.span K C : Set (Dual K R)) (contextClosed_span hC)

theorem mem_spanContextualIdeal (C : Set (Dual K R)) (hC : SpanContextClosed C) (a : R) :
    a ∈ contextualIdeal (Submodule.span K C : Set (Dual K R)) (contextClosed_span hC) ↔
      ∀ φ ∈ C, φ a = 0 := by
  change a ∈ contextualNull _ ↔ _
  rw [contextualNull_span]
  rfl

/-- The history word moment `τ̂_reg([v]^* [w])` in the history algebra of a span-closed
family. -/
noncomputable def spanHistoryMoment [Star R] (C : Set (Dual K R)) (hC : SpanContextClosed C)
    (v w : R) : K :=
  regTrace (K := K) (SpanHistoryAlgebra C hC) (Ideal.Quotient.mk _ (star v * w))

/-- An algebra isomorphism of raw algebras matching the null sets induces an isomorphism of
history algebras, `[r] ↦ [Ψ r]`. -/
noncomputable def spanHistoryCongr {R' : Type*} [Ring R'] [Algebra K R']
    (C : Set (Dual K R)) (hC : SpanContextClosed C) (C' : Set (Dual K R'))
    (hC' : SpanContextClosed C') (Ψ : R ≃ₐ[K] R')
    (hnull : ∀ x, x ∈ contextualNull C ↔ Ψ x ∈ contextualNull C') :
    SpanHistoryAlgebra C hC ≃ₐ[K] SpanHistoryAlgebra C' hC' :=
  Ideal.quotientEquivAlg _ _ Ψ (by
    have hmem : ∀ x, x ∈ contextualIdeal (Submodule.span K C : Set (Dual K R))
        (contextClosed_span hC) ↔ Ψ x ∈ contextualIdeal (Submodule.span K C' : Set (Dual K R'))
        (contextClosed_span hC') := by
      intro x
      change x ∈ contextualNull _ ↔ Ψ x ∈ contextualNull _
      rw [contextualNull_span, contextualNull_span]
      exact hnull x
    apply le_antisymm
    · intro y hy
      have hy' : Ψ.symm y ∈ contextualIdeal (Submodule.span K C : Set (Dual K R))
          (contextClosed_span hC) := (hmem _).mpr (by simpa using hy)
      have := Ideal.mem_map_of_mem (Ψ : R →+* R') hy'
      simpa using this
    · rw [Ideal.map_le_iff_le_comap]
      intro x hx
      exact (hmem x).mp hx)

theorem spanHistoryCongr_mk {R' : Type*} [Ring R'] [Algebra K R']
    (C : Set (Dual K R)) (hC : SpanContextClosed C) (C' : Set (Dual K R'))
    (hC' : SpanContextClosed C') (Ψ : R ≃ₐ[K] R')
    (hnull : ∀ x, x ∈ contextualNull C ↔ Ψ x ∈ contextualNull C') (r : R) :
    spanHistoryCongr C hC C' hC' Ψ hnull (Ideal.Quotient.mk _ r) = Ideal.Quotient.mk _ (Ψ r) :=
  rfl

end SpanClosed

/-! ## Product contexts are span-closed: composites iterate -/

section Product

variable {K : Type*} [Field K]
variable {R₁ R₂ R₃ : Type*} [Ring R₁] [Algebra K R₁] [Ring R₂] [Algebra K R₂]
  [Ring R₃] [Algebra K R₃]

/-- Products of spanned contexts are spanned by product contexts. -/
theorem dualDistrib_mem_span_productContexts {C₁ : Set (Dual K R₁)} {C₂ : Set (Dual K R₂)}
    {φ₁ : Dual K R₁} {φ₂ : Dual K R₂} (h₁ : φ₁ ∈ Submodule.span K C₁)
    (h₂ : φ₂ ∈ Submodule.span K C₂) :
    TensorProduct.dualDistrib K R₁ R₂ (φ₁ ⊗ₜ φ₂) ∈ Submodule.span K (productContexts C₁ C₂) := by
  induction h₁ using Submodule.span_induction with
  | mem a ha =>
    induction h₂ using Submodule.span_induction with
    | mem b hb => exact Submodule.subset_span ⟨a, ha, b, hb, rfl⟩
    | zero => simp
    | add b c _ _ hb hc => rw [TensorProduct.tmul_add, map_add]; exact add_mem hb hc
    | smul k b _ hb => rw [TensorProduct.tmul_smul, map_smul]; exact Submodule.smul_mem _ k hb
  | zero => simp
  | add a c _ _ ha hc => rw [TensorProduct.add_tmul, map_add]; exact add_mem ha hc
  | smul k a _ ha => rw [← TensorProduct.smul_tmul', map_smul]; exact Submodule.smul_mem _ k ha

theorem productContexts_subset_span {C₁ : Set (Dual K R₁)} {C₂ : Set (Dual K R₂)} :
    productContexts (Submodule.span K C₁ : Set (Dual K R₁)) (Submodule.span K C₂ : Set _)
      ⊆ (Submodule.span K (productContexts C₁ C₂) : Set (Dual K (R₁ ⊗[K] R₂))) := by
  rintro _ ⟨φ₁, h₁, φ₂, h₂, rfl⟩
  exact dualDistrib_mem_span_productContexts h₁ h₂

theorem productContexts_mono {C₁ C₁' : Set (Dual K R₁)} {C₂ C₂' : Set (Dual K R₂)}
    (h₁ : C₁ ⊆ C₁') (h₂ : C₂ ⊆ C₂') : productContexts C₁ C₂ ⊆ productContexts C₁' C₂' := by
  rintro _ ⟨φ₁, hφ₁, φ₂, hφ₂, rfl⟩
  exact ⟨φ₁, h₁ hφ₁, φ₂, h₂ hφ₂, rfl⟩

/-- Product contexts with spanned factors have the null set of the product contexts. -/
theorem contextualNull_productContexts_span (C₁ : Set (Dual K R₁)) (C₂ : Set (Dual K R₂)) :
    contextualNull (productContexts (Submodule.span K C₁ : Set (Dual K R₁))
      (Submodule.span K C₂ : Set _)) = contextualNull (productContexts C₁ C₂) :=
  contextualNull_eq_of_subset_span
    (productContexts_mono Submodule.subset_span Submodule.subset_span)
    productContexts_subset_span

/-- Insertion of elementary tensors into a product context is the product of the insertions. -/
theorem dualDistrib_comp_mulLeft_mulRight_tmul (φ₁ : Dual K R₁) (φ₂ : Dual K R₂)
    (a c : R₁) (b d : R₂) :
    TensorProduct.dualDistrib K R₁ R₂ (φ₁ ⊗ₜ φ₂) ∘ₗ
        (LinearMap.mulLeft K (a ⊗ₜ[K] b) ∘ₗ LinearMap.mulRight K (c ⊗ₜ[K] d))
      = TensorProduct.dualDistrib K R₁ R₂
          ((φ₁ ∘ₗ (LinearMap.mulLeft K a ∘ₗ LinearMap.mulRight K c)) ⊗ₜ
            (φ₂ ∘ₗ (LinearMap.mulLeft K b ∘ₗ LinearMap.mulRight K d))) := by
  apply TensorProduct.ext'
  intro r₁ r₂
  simp [TensorProduct.dualDistrib_apply, Algebra.TensorProduct.tmul_mul_tmul]

/-- **The product contextual test family is span-closed**, so the composite of two independent
processes is again a process with a span-closed contextual family and composites iterate. -/
theorem productContexts_spanContextClosed {C₁ : Set (Dual K R₁)} {C₂ : Set (Dual K R₂)}
    (hC₁ : SpanContextClosed C₁) (hC₂ : SpanContextClosed C₂) :
    SpanContextClosed (productContexts C₁ C₂) := by
  rintro _ ⟨φ₁, h₁, φ₂, h₂, rfl⟩ x y
  set ψ := TensorProduct.dualDistrib K R₁ R₂ (φ₁ ⊗ₜ φ₂)
  induction x using TensorProduct.induction_on with
  | zero =>
    have : ψ ∘ₗ (LinearMap.mulLeft K (0 : R₁ ⊗[K] R₂) ∘ₗ LinearMap.mulRight K y) = 0 := by
      ext r; simp
    rw [this]; exact zero_mem _
  | add x x' hx hx' =>
    have : ψ ∘ₗ (LinearMap.mulLeft K (x + x') ∘ₗ LinearMap.mulRight K y)
        = ψ ∘ₗ (LinearMap.mulLeft K x ∘ₗ LinearMap.mulRight K y)
          + ψ ∘ₗ (LinearMap.mulLeft K x' ∘ₗ LinearMap.mulRight K y) := by
      ext r; simp [add_mul]
    rw [this]; exact add_mem hx hx'
  | tmul a b =>
    induction y using TensorProduct.induction_on with
    | zero =>
      have : ψ ∘ₗ (LinearMap.mulLeft K (a ⊗ₜ[K] b) ∘ₗ
          LinearMap.mulRight K (0 : R₁ ⊗[K] R₂)) = 0 := by
        ext r; simp
      rw [this]; exact zero_mem _
    | add y y' hy hy' =>
      have : ψ ∘ₗ (LinearMap.mulLeft K (a ⊗ₜ[K] b) ∘ₗ LinearMap.mulRight K (y + y'))
          = ψ ∘ₗ (LinearMap.mulLeft K (a ⊗ₜ[K] b) ∘ₗ LinearMap.mulRight K y)
            + ψ ∘ₗ (LinearMap.mulLeft K (a ⊗ₜ[K] b) ∘ₗ LinearMap.mulRight K y') := by
        ext r; simp [mul_add]
      rw [this]; exact add_mem hy hy'
    | tmul c d =>
      rw [dualDistrib_comp_mulLeft_mulRight_tmul]
      exact dualDistrib_mem_span_productContexts (hC₁ φ₁ h₁ a c) (hC₂ φ₂ h₂ b d)

variable [FiniteDimensional K R₁] [FiniteDimensional K R₂] [FiniteDimensional K R₃]

/-- The contextual ideal of the product family is the kernel of
`R₁ ⊗ R₂ → 𝒜₁^hist ⊗ 𝒜₂^hist`. -/
theorem spanContextualIdeal_productContexts_eq {C₁ : Set (Dual K R₁)} {C₂ : Set (Dual K R₂)}
    (hC₁ : SpanContextClosed C₁) (hC₂ : SpanContextClosed C₂) :
    contextualIdeal (Submodule.span K (productContexts C₁ C₂) : Set (Dual K (R₁ ⊗[K] R₂)))
        (contextClosed_span (productContexts_spanContextClosed hC₁ hC₂))
      = compositeNullIdeal (Submodule.span K C₁ : Set (Dual K R₁)) (contextClosed_span hC₁)
          (Submodule.span K C₂ : Set (Dual K R₂)) (contextClosed_span hC₂) := by
  ext x
  rw [mem_compositeNullIdeal, contextualNull_productContexts_span]
  change x ∈ contextualNull _ ↔ _
  rw [contextualNull_span]

/-- **`eq:supp-grand-product`, history-algebra factor, iterable form.**  For span-closed
contextual families, the history algebra of the composite with the product contextual test
family is `𝒜₁^hist ⊗ 𝒜₂^hist`, via `[r₁ ⊗ r₂] ↦ [r₁] ⊗ [r₂]`. -/
noncomputable def compositeSpanEquiv (C₁ : Set (Dual K R₁)) (hC₁ : SpanContextClosed C₁)
    (C₂ : Set (Dual K R₂)) (hC₂ : SpanContextClosed C₂) :
    SpanHistoryAlgebra (productContexts C₁ C₂) (productContexts_spanContextClosed hC₁ hC₂)
      ≃ₐ[K] SpanHistoryAlgebra C₁ hC₁ ⊗[K] SpanHistoryAlgebra C₂ hC₂ :=
  (Ideal.quotientEquivAlgOfEq K (spanContextualIdeal_productContexts_eq hC₁ hC₂)).trans
    (compositeHistoryAlgebraEquiv _ (contextClosed_span hC₁) _ (contextClosed_span hC₂))

theorem compositeSpanEquiv_mk_tmul (C₁ : Set (Dual K R₁)) (hC₁ : SpanContextClosed C₁)
    (C₂ : Set (Dual K R₂)) (hC₂ : SpanContextClosed C₂) (r₁ : R₁) (r₂ : R₂) :
    compositeSpanEquiv C₁ hC₁ C₂ hC₂ (Ideal.Quotient.mk _ (r₁ ⊗ₜ r₂))
      = Ideal.Quotient.mk _ r₁ ⊗ₜ Ideal.Quotient.mk _ r₂ := rfl

/-- **`eq:supp-grand-gram-product` for the product contextual family.**  Word moments of
independent word pairs factor. -/
theorem compositeSpanMoment [StarRing K] [StarAddMonoid R₁] [StarModule K R₁]
    [StarAddMonoid R₂] [StarModule K R₂]
    (C₁ : Set (Dual K R₁)) (hC₁ : SpanContextClosed C₁)
    (C₂ : Set (Dual K R₂)) (hC₂ : SpanContextClosed C₂) (v₁ w₁ : R₁) (v₂ w₂ : R₂) :
    spanHistoryMoment (productContexts C₁ C₂) (productContexts_spanContextClosed hC₁ hC₂)
        (v₁ ⊗ₜ[K] v₂) (w₁ ⊗ₜ[K] w₂)
      = spanHistoryMoment C₁ hC₁ v₁ w₁ * spanHistoryMoment C₂ hC₂ v₂ w₂ := by
  unfold spanHistoryMoment
  rw [← regTrace_algEquiv (compositeSpanEquiv C₁ hC₁ C₂ hC₂), TensorProduct.star_tmul,
    Algebra.TensorProduct.tmul_mul_tmul, compositeSpanEquiv_mk_tmul]
  exact regTrace_tmul _ _

/-! ### Interchange -/

theorem dualDistrib_comp_comm (φ₁ : Dual K R₁) (φ₂ : Dual K R₂) :
    TensorProduct.dualDistrib K R₂ R₁ (φ₂ ⊗ₜ φ₁) ∘ₗ
        (Algebra.TensorProduct.comm K R₁ R₂).toLinearMap
      = TensorProduct.dualDistrib K R₁ R₂ (φ₁ ⊗ₜ φ₂) := by
  apply TensorProduct.ext'
  intro a b
  simp [TensorProduct.dualDistrib_apply, mul_comm]

theorem contextualNull_productContexts_comm (C₁ : Set (Dual K R₁)) (C₂ : Set (Dual K R₂))
    (x : R₁ ⊗[K] R₂) :
    x ∈ contextualNull (productContexts C₁ C₂) ↔
      Algebra.TensorProduct.comm K R₁ R₂ x ∈ contextualNull (productContexts C₂ C₁) := by
  constructor
  · rintro hx _ ⟨φ₂, h₂, φ₁, h₁, rfl⟩
    have := hx _ ⟨φ₁, h₁, φ₂, h₂, rfl⟩
    rw [← dualDistrib_comp_comm] at this
    exact this
  · rintro hx _ ⟨φ₁, h₁, φ₂, h₂, rfl⟩
    rw [← dualDistrib_comp_comm]
    exact hx _ ⟨φ₂, h₂, φ₁, h₁, rfl⟩

/-- The interchange of the raw factors induces an isomorphism of composite history algebras,
`[r₁ ⊗ r₂] ↦ [r₂ ⊗ r₁]`. -/
noncomputable def spanHistoryComm {C₁ : Set (Dual K R₁)} (hC₁ : SpanContextClosed C₁)
    {C₂ : Set (Dual K R₂)} (hC₂ : SpanContextClosed C₂) :
    SpanHistoryAlgebra (productContexts C₁ C₂) (productContexts_spanContextClosed hC₁ hC₂)
      ≃ₐ[K] SpanHistoryAlgebra (productContexts C₂ C₁)
        (productContexts_spanContextClosed hC₂ hC₁) :=
  spanHistoryCongr _ _ _ _ (Algebra.TensorProduct.comm K R₁ R₂)
    (contextualNull_productContexts_comm C₁ C₂)

/-- **Interchange square.**  The identification `𝒜₁₂^hist ≃ 𝒜₁^hist ⊗ 𝒜₂^hist` commutes with
interchange of the independent factors. -/
theorem compositeSpanEquiv_comm {C₁ : Set (Dual K R₁)} (hC₁ : SpanContextClosed C₁)
    {C₂ : Set (Dual K R₂)} (hC₂ : SpanContextClosed C₂)
    (z : SpanHistoryAlgebra (productContexts C₁ C₂)
      (productContexts_spanContextClosed hC₁ hC₂)) :
    compositeSpanEquiv C₂ hC₂ C₁ hC₁ (spanHistoryComm hC₁ hC₂ z)
      = Algebra.TensorProduct.comm K _ _ (compositeSpanEquiv C₁ hC₁ C₂ hC₂ z) := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective z
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul a b => rfl
  | add x y hx hy => simp only [map_add, hx, hy]

/-! ### Reassociation -/

theorem dualDistrib_comp_assoc (φ₁ : Dual K R₁) (φ₂ : Dual K R₂) (φ₃ : Dual K R₃) :
    TensorProduct.dualDistrib K R₁ (R₂ ⊗[K] R₃)
        (φ₁ ⊗ₜ TensorProduct.dualDistrib K R₂ R₃ (φ₂ ⊗ₜ φ₃)) ∘ₗ
        (Algebra.TensorProduct.assoc K K K R₁ R₂ R₃).toLinearMap
      = TensorProduct.dualDistrib K (R₁ ⊗[K] R₂) R₃
          (TensorProduct.dualDistrib K R₁ R₂ (φ₁ ⊗ₜ φ₂) ⊗ₜ φ₃) := by
  apply TensorProduct.ext_threefold
  intro a b c
  simp [TensorProduct.dualDistrib_apply, mul_assoc]

theorem contextualNull_productContexts_assoc (C₁ : Set (Dual K R₁)) (C₂ : Set (Dual K R₂))
    (C₃ : Set (Dual K R₃)) (x : (R₁ ⊗[K] R₂) ⊗[K] R₃) :
    x ∈ contextualNull (productContexts (productContexts C₁ C₂) C₃) ↔
      Algebra.TensorProduct.assoc K K K R₁ R₂ R₃ x ∈
        contextualNull (productContexts C₁ (productContexts C₂ C₃)) := by
  constructor
  · rintro hx _ ⟨φ₁, h₁, _, ⟨φ₂, h₂, φ₃, h₃, rfl⟩, rfl⟩
    have := hx _ ⟨_, ⟨φ₁, h₁, φ₂, h₂, rfl⟩, φ₃, h₃, rfl⟩
    rw [← dualDistrib_comp_assoc] at this
    exact this
  · rintro hx _ ⟨_, ⟨φ₁, h₁, φ₂, h₂, rfl⟩, φ₃, h₃, rfl⟩
    rw [← dualDistrib_comp_assoc]
    exact hx _ ⟨φ₁, h₁, _, ⟨φ₂, h₂, φ₃, h₃, rfl⟩, rfl⟩

/-- Reassociation of the raw factors induces an isomorphism of the iterated composite history
algebras, `[(r₁ ⊗ r₂) ⊗ r₃] ↦ [r₁ ⊗ (r₂ ⊗ r₃)]`. -/
noncomputable def spanHistoryAssoc {C₁ : Set (Dual K R₁)} (hC₁ : SpanContextClosed C₁)
    {C₂ : Set (Dual K R₂)} (hC₂ : SpanContextClosed C₂)
    {C₃ : Set (Dual K R₃)} (hC₃ : SpanContextClosed C₃) :
    SpanHistoryAlgebra (productContexts (productContexts C₁ C₂) C₃)
        (productContexts_spanContextClosed (productContexts_spanContextClosed hC₁ hC₂) hC₃)
      ≃ₐ[K] SpanHistoryAlgebra (productContexts C₁ (productContexts C₂ C₃))
        (productContexts_spanContextClosed hC₁ (productContexts_spanContextClosed hC₂ hC₃)) :=
  spanHistoryCongr _ _ _ _ (Algebra.TensorProduct.assoc K K K R₁ R₂ R₃)
    (contextualNull_productContexts_assoc C₁ C₂ C₃)

/-- **Reassociation square.**  The two iterated identifications
`𝒜₍₁₂₎₃^hist ≃ (𝒜₁ ⊗ 𝒜₂) ⊗ 𝒜₃` and `𝒜₁₍₂₃₎^hist ≃ 𝒜₁ ⊗ (𝒜₂ ⊗ 𝒜₃)` commute with the
reassociation maps. -/
theorem compositeSpanEquiv_assoc {C₁ : Set (Dual K R₁)} (hC₁ : SpanContextClosed C₁)
    {C₂ : Set (Dual K R₂)} (hC₂ : SpanContextClosed C₂)
    {C₃ : Set (Dual K R₃)} (hC₃ : SpanContextClosed C₃)
    (z : SpanHistoryAlgebra (productContexts (productContexts C₁ C₂) C₃)
      (productContexts_spanContextClosed (productContexts_spanContextClosed hC₁ hC₂) hC₃)) :
    Algebra.TensorProduct.congr (AlgEquiv.refl : SpanHistoryAlgebra C₁ hC₁ ≃ₐ[K] _)
        (compositeSpanEquiv C₂ hC₂ C₃ hC₃)
        (compositeSpanEquiv C₁ hC₁ _ (productContexts_spanContextClosed hC₂ hC₃)
          (spanHistoryAssoc hC₁ hC₂ hC₃ z))
      = Algebra.TensorProduct.assoc K K K _ _ _
          (Algebra.TensorProduct.congr (compositeSpanEquiv C₁ hC₁ C₂ hC₂)
            (AlgEquiv.refl : SpanHistoryAlgebra C₃ hC₃ ≃ₐ[K] _)
            (compositeSpanEquiv _ (productContexts_spanContextClosed hC₁ hC₂) C₃ hC₃ z)) := by
  obtain ⟨x, rfl⟩ := Ideal.Quotient.mk_surjective z
  induction x using TensorProduct.induction_on with
  | zero => simp
  | tmul y c =>
    induction y using TensorProduct.induction_on with
    | zero => simp
    | tmul a b => rfl
    | add y y' hy hy' =>
      simp only [TensorProduct.add_tmul, map_add, hy, hy']
  | add x y hx hy => simp only [map_add, hx, hy]

end Product

/-! ## Coherence of the predictive identification `Z₁₂^min ≃ Z₁^min × Z₂^min` -/

section Predictive

open DerivedPredictiveCarrierUniversal

variable {H₁ L₁ H₂ L₂ H₃ L₃ : Type*}

/-- Identity operations on both factors give the identity operation `(id₁, id₂)` of the
independent composite, so composites of processes with identity operations again have one. -/
def IdentityOperation.prod {P₁ : PredictiveSystem H₁ L₁} {P₂ : PredictiveSystem H₂ L₂}
    (I₁ : IdentityOperation P₁) (I₂ : IdentityOperation P₂) :
    IdentityOperation (indepProduct P₁ P₂) where
  id := (I₁.id, I₂.id)
  branch_id h := by simp [indepProduct, I₁.branch_id, I₂.branch_id]
  step_id h := by simp [indepProduct, I₁.step_id, I₂.step_id]

/-- Interchange invariance of the composite law: swapping the two independent factors (in
histories and letters) leaves every joint future probability unchanged. -/
theorem indepProduct_comm_probability (P₁ : PredictiveSystem H₁ L₁)
    (P₂ : PredictiveSystem H₂ L₂) (h : H₁ × H₂) (w : List (L₁ × L₂)) :
    (indepProduct P₂ P₁).probability h.swap (w.map Prod.swap)
      = (indepProduct P₁ P₂).probability h w := by
  simp only [indepProduct, List.map_map]
  rw [mul_comm]
  rfl

/-- Reassociation invariance of the composite law. -/
theorem indepProduct_assoc_probability (P₁ : PredictiveSystem H₁ L₁)
    (P₂ : PredictiveSystem H₂ L₂) (P₃ : PredictiveSystem H₃ L₃) (h : (H₁ × H₂) × H₃)
    (w : List ((L₁ × L₂) × L₃)) :
    (indepProduct P₁ (indepProduct P₂ P₃)).probability (Equiv.prodAssoc _ _ _ h)
        (w.map (Equiv.prodAssoc _ _ _))
      = (indepProduct (indepProduct P₁ P₂) P₃).probability h w := by
  simp only [indepProduct, List.map_map]
  rw [mul_assoc]
  rfl

/-- Interchange of the factors induces `Z₁₂^min ≃ Z₂₁^min`, `[(h₁,h₂)] ↦ [(h₂,h₁)]`. -/
def minimalSwap (P₁ : PredictiveSystem H₁ L₁) (P₂ : PredictiveSystem H₂ L₂)
    (I₁ : IdentityOperation P₁) (I₂ : IdentityOperation P₂) :
    (indepProduct P₁ P₂).MinimalCarrier ≃ (indepProduct P₂ P₁).MinimalCarrier :=
  Quotient.congr (Equiv.prodComm H₁ H₂) (fun h h' => by
    change (indepProduct P₁ P₂).FutureEquivalent h h' ↔
      (indepProduct P₂ P₁).FutureEquivalent (h.2, h.1) (h'.2, h'.1)
    rw [indepProduct_futureEquivalent_iff P₁ P₂ I₁ I₂,
      indepProduct_futureEquivalent_iff P₂ P₁ I₂ I₁]
    exact And.comm)

/-- **Interchange square** for `Z₁₂^min ≃ Z₁^min × Z₂^min`. -/
theorem indepProductMinimalEquiv_comm (P₁ : PredictiveSystem H₁ L₁)
    (P₂ : PredictiveSystem H₂ L₂) (I₁ : IdentityOperation P₁) (I₂ : IdentityOperation P₂)
    (z : (indepProduct P₁ P₂).MinimalCarrier) :
    indepProductMinimalEquiv P₂ P₁ I₂ I₁ (minimalSwap P₁ P₂ I₁ I₂ z)
      = Equiv.prodComm _ _ (indepProductMinimalEquiv P₁ P₂ I₁ I₂ z) := by
  induction z using Quotient.inductionOn with
  | h h => rfl

/-- Reassociation of the factors induces `Z₍₁₂₎₃^min ≃ Z₁₍₂₃₎^min`. -/
def minimalAssoc (P₁ : PredictiveSystem H₁ L₁) (P₂ : PredictiveSystem H₂ L₂)
    (P₃ : PredictiveSystem H₃ L₃) (I₁ : IdentityOperation P₁) (I₂ : IdentityOperation P₂)
    (I₃ : IdentityOperation P₃) :
    (indepProduct (indepProduct P₁ P₂) P₃).MinimalCarrier
      ≃ (indepProduct P₁ (indepProduct P₂ P₃)).MinimalCarrier :=
  Quotient.congr (Equiv.prodAssoc H₁ H₂ H₃) (fun h h' => by
    change (indepProduct (indepProduct P₁ P₂) P₃).FutureEquivalent h h' ↔
      (indepProduct P₁ (indepProduct P₂ P₃)).FutureEquivalent (h.1.1, (h.1.2, h.2))
        (h'.1.1, (h'.1.2, h'.2))
    rw [indepProduct_futureEquivalent_iff _ P₃ (I₁.prod I₂) I₃,
      indepProduct_futureEquivalent_iff P₁ P₂ I₁ I₂,
      indepProduct_futureEquivalent_iff P₁ _ I₁ (I₂.prod I₃),
      indepProduct_futureEquivalent_iff P₂ P₃ I₂ I₃]
    exact and_assoc)

/-- **Reassociation square** for `Z₁₂^min ≃ Z₁^min × Z₂^min`. -/
theorem indepProductMinimalEquiv_assoc (P₁ : PredictiveSystem H₁ L₁)
    (P₂ : PredictiveSystem H₂ L₂) (P₃ : PredictiveSystem H₃ L₃) (I₁ : IdentityOperation P₁)
    (I₂ : IdentityOperation P₂) (I₃ : IdentityOperation P₃)
    (z : (indepProduct (indepProduct P₁ P₂) P₃).MinimalCarrier) :
    Equiv.prodCongr (Equiv.refl _) (indepProductMinimalEquiv P₂ P₃ I₂ I₃)
        (indepProductMinimalEquiv P₁ _ I₁ (I₂.prod I₃) (minimalAssoc P₁ P₂ P₃ I₁ I₂ I₃ z))
      = Equiv.prodAssoc _ _ _
          (Equiv.prodCongr (indepProductMinimalEquiv P₁ P₂ I₁ I₂) (Equiv.refl _)
            (indepProductMinimalEquiv _ P₃ (I₁.prod I₂) I₃ z)) := by
  induction z using Quotient.inductionOn with
  | h h => rfl

end Predictive

/-! ## Typed predictive systems and their independent product -/

section Typed

open DerivedPredictiveCarrierUniversal

/-- A cut-typed predictive system: a predictive law together with the cut type of every
history.  (Inadmissible letters at a cut are encoded by branch probability zero, so the
complete future bank of `def:supp-future-signature` is the set of all finite words.) -/
structure TypedPredictiveSystem (O History Letter : Type*) where
  /-- the predictive law -/
  system : PredictiveSystem History Letter
  /-- the cut type of a history -/
  cut : History → O

namespace TypedPredictiveSystem

variable {O H L : Type*} (T : TypedPredictiveSystem O H L)

/-- Typed future equivalence (`eq:supp-future-equivalence`): same cut type and equal complete
future signatures; histories of different cut type are never identified. -/
def TypedFutureEquivalent (h h' : H) : Prop :=
  T.cut h = T.cut h' ∧ T.system.FutureEquivalent h h'

/-- The typed future-equivalence setoid. -/
def typedSetoid : Setoid H where
  r := T.TypedFutureEquivalent
  iseqv := ⟨fun _ => ⟨rfl, fun _ => rfl⟩, fun h => ⟨h.1.symm, fun w => (h.2 w).symm⟩,
    fun h h' => ⟨h.1.trans h'.1, fun w => (h.2 w).trans (h'.2 w)⟩⟩

/-- `Z_X^min = ⊔_x H_{X,x}/∼_X` (`eq:supp-predictive-state`). -/
abbrev TypedMinimalCarrier : Type _ := Quotient T.typedSetoid

/-- The cut type of a minimum predictive state. -/
def minimalCut : T.TypedMinimalCarrier → O :=
  Quotient.lift T.cut (fun _ _ h => h.1)

/-- The fibre `Z_{X,x}^min` over a cut type `x`. -/
abbrev Fibre (x : O) : Type _ := {z : T.TypedMinimalCarrier // T.minimalCut z = x}

/-- The one-step branch law `κ_a([h]) = p(a | h)` on typed minimum states. -/
def typedMinimalBranch (a : L) : T.TypedMinimalCarrier → ℝ :=
  Quotient.lift (fun h => T.system.branch h a)
    (fun _ _ hh => T.system.branch_eq_of_futureEquivalent hh.2 a)

end TypedPredictiveSystem

open TypedPredictiveSystem

variable {O₁ H₁ L₁ O₂ H₂ L₂ O₃ H₃ L₃ : Type*}

/-- The independent composite of two typed processes: cut types `O₁ × O₂`, product
histories, joint letters, factorized future law. -/
def typedIndepProduct (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) :
    TypedPredictiveSystem (O₁ × O₂) (H₁ × H₂) (L₁ × L₂) where
  system := indepProduct T₁.system T₂.system
  cut h := (T₁.cut h.1, T₂.cut h.2)

/-- Typed joint future equivalence is the conjunction of the typed marginal ones. -/
theorem typedIndepProduct_futureEquivalent_iff (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (h h' : H₁ × H₂) :
    (typedIndepProduct T₁ T₂).TypedFutureEquivalent h h' ↔
      T₁.TypedFutureEquivalent h.1 h'.1 ∧ T₂.TypedFutureEquivalent h.2 h'.2 := by
  unfold TypedFutureEquivalent
  change ((T₁.cut h.1, T₂.cut h.2) = (T₁.cut h'.1, T₂.cut h'.2) ∧
    (indepProduct T₁.system T₂.system).FutureEquivalent h h') ↔ _
  rw [indepProduct_futureEquivalent_iff _ _ I₁ I₂, Prod.mk.injEq]
  tauto

/-- **`eq:supp-grand-product`, typed predictive factor.**  `Z₁₂^min ≃ Z₁^min × Z₂^min`,
`[(h₁,h₂)] ↦ ([h₁],[h₂])`. -/
def typedIndepProductMinimalEquiv (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) :
    (typedIndepProduct T₁ T₂).TypedMinimalCarrier
      ≃ T₁.TypedMinimalCarrier × T₂.TypedMinimalCarrier :=
  (Quotient.congr (Equiv.refl _) (fun h h' =>
      typedIndepProduct_futureEquivalent_iff T₁ T₂ I₁ I₂ h h')).trans
    (Setoid.prodQuotientEquiv T₁.typedSetoid T₂.typedSetoid).symm

theorem typedIndepProductMinimalEquiv_mk (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (h : H₁ × H₂) :
    typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ (Quotient.mk _ h)
      = (Quotient.mk _ h.1, Quotient.mk _ h.2) := rfl

/-- The identification preserves cut types: the joint cut type is the pair of marginal cut
types. -/
theorem typedIndepProductMinimalEquiv_cut (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (z : (typedIndepProduct T₁ T₂).TypedMinimalCarrier) :
    (T₁.minimalCut (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ z).1,
        T₂.minimalCut (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ z).2)
      = (typedIndepProduct T₁ T₂).minimalCut z := by
  induction z using Quotient.inductionOn with
  | h h => rfl

/-- The joint branch law is the product of the marginal branch laws. -/
theorem typedIndepProductMinimalEquiv_branch (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (z : (typedIndepProduct T₁ T₂).TypedMinimalCarrier)
    (a : L₁ × L₂) :
    (typedIndepProduct T₁ T₂).typedMinimalBranch a z
      = T₁.typedMinimalBranch a.1 (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ z).1
        * T₂.typedMinimalBranch a.2 (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ z).2 := by
  induction z using Quotient.inductionOn with
  | h h => rfl

/-- **Fibrewise form.**  `Z₁₂,(x₁,x₂)^min ≃ Z₁,x₁^min × Z₂,x₂^min` for every pair of cut
types. -/
def typedIndepProductFibreEquiv (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (x₁ : O₁) (x₂ : O₂) :
    (typedIndepProduct T₁ T₂).Fibre (x₁, x₂) ≃ T₁.Fibre x₁ × T₂.Fibre x₂ :=
  ((typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂).subtypeEquiv
      (p := fun z => (typedIndepProduct T₁ T₂).minimalCut z = (x₁, x₂))
      (q := fun p : T₁.TypedMinimalCarrier × T₂.TypedMinimalCarrier =>
        T₁.minimalCut p.1 = x₁ ∧ T₂.minimalCut p.2 = x₂) (fun z => by
        rw [← typedIndepProductMinimalEquiv_cut T₁ T₂ I₁ I₂ z, Prod.mk.injEq])).trans
    (Equiv.subtypeProdEquivProd (p := fun z : T₁.TypedMinimalCarrier => T₁.minimalCut z = x₁)
      (q := fun z : T₂.TypedMinimalCarrier => T₂.minimalCut z = x₂))

/-- Interchange of typed factors, `[(h₁,h₂)] ↦ [(h₂,h₁)]`. -/
def typedMinimalSwap (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) :
    (typedIndepProduct T₁ T₂).TypedMinimalCarrier
      ≃ (typedIndepProduct T₂ T₁).TypedMinimalCarrier :=
  Quotient.congr (Equiv.prodComm H₁ H₂) (fun h h' => by
    change (typedIndepProduct T₁ T₂).TypedFutureEquivalent h h' ↔
      (typedIndepProduct T₂ T₁).TypedFutureEquivalent (h.2, h.1) (h'.2, h'.1)
    rw [typedIndepProduct_futureEquivalent_iff T₁ T₂ I₁ I₂,
      typedIndepProduct_futureEquivalent_iff T₂ T₁ I₂ I₁]
    exact And.comm)

/-- **Typed interchange square.** -/
theorem typedIndepProductMinimalEquiv_comm (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system) (z : (typedIndepProduct T₁ T₂).TypedMinimalCarrier) :
    typedIndepProductMinimalEquiv T₂ T₁ I₂ I₁ (typedMinimalSwap T₁ T₂ I₁ I₂ z)
      = Equiv.prodComm _ _ (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂ z) := by
  induction z using Quotient.inductionOn with
  | h h => rfl

/-- Reassociation of typed factors, `[((h₁,h₂),h₃)] ↦ [(h₁,(h₂,h₃))]`. -/
def typedMinimalAssoc (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (T₃ : TypedPredictiveSystem O₃ H₃ L₃)
    (I₁ : IdentityOperation T₁.system) (I₂ : IdentityOperation T₂.system)
    (I₃ : IdentityOperation T₃.system) :
    (typedIndepProduct (typedIndepProduct T₁ T₂) T₃).TypedMinimalCarrier
      ≃ (typedIndepProduct T₁ (typedIndepProduct T₂ T₃)).TypedMinimalCarrier :=
  Quotient.congr (Equiv.prodAssoc H₁ H₂ H₃) (fun h h' => by
    change (typedIndepProduct (typedIndepProduct T₁ T₂) T₃).TypedFutureEquivalent h h' ↔
      (typedIndepProduct T₁ (typedIndepProduct T₂ T₃)).TypedFutureEquivalent
        (h.1.1, (h.1.2, h.2)) (h'.1.1, (h'.1.2, h'.2))
    rw [typedIndepProduct_futureEquivalent_iff (typedIndepProduct T₁ T₂) T₃ (I₁.prod I₂) I₃,
      typedIndepProduct_futureEquivalent_iff T₁ T₂ I₁ I₂,
      typedIndepProduct_futureEquivalent_iff T₁ (typedIndepProduct T₂ T₃) I₁ (I₂.prod I₃),
      typedIndepProduct_futureEquivalent_iff T₂ T₃ I₂ I₃]
    exact and_assoc)

/-- **Typed reassociation square.** -/
theorem typedIndepProductMinimalEquiv_assoc (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (T₃ : TypedPredictiveSystem O₃ H₃ L₃)
    (I₁ : IdentityOperation T₁.system) (I₂ : IdentityOperation T₂.system)
    (I₃ : IdentityOperation T₃.system)
    (z : (typedIndepProduct (typedIndepProduct T₁ T₂) T₃).TypedMinimalCarrier) :
    Equiv.prodCongr (Equiv.refl _) (typedIndepProductMinimalEquiv T₂ T₃ I₂ I₃)
        (typedIndepProductMinimalEquiv T₁ (typedIndepProduct T₂ T₃) I₁ (I₂.prod I₃)
          (typedMinimalAssoc T₁ T₂ T₃ I₁ I₂ I₃ z))
      = Equiv.prodAssoc _ _ _
          (Equiv.prodCongr (typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂) (Equiv.refl _)
            (typedIndepProductMinimalEquiv (typedIndepProduct T₁ T₂) T₃ (I₁.prod I₂) I₃ z)) := by
  induction z using Quotient.inductionOn with
  | h h => rfl

end Typed

/-- Non-vacuity: the full dual is a (span-)closed context family. -/
example {K R : Type*} [Field K] [Ring R] [Algebra K R] :
    SpanContextClosed (Set.univ : Set (Dual K R)) :=
  fun _ _ _ _ => Submodule.subset_span trivial

/-! ## The composite raw algebra is the tensor product (Kronecker realization) -/

section KroneckerRealization

open scoped Kronecker

variable {K : Type*} [Field K] {n m : Type*} [Fintype n] [DecidableEq n] [Fintype m]
  [DecidableEq m]

/-- The Kronecker realization `R₁ ⊗ R₂ → M_{n×m}(K)`, `a ⊗ b ↦ a ⊗ₖ b`, of the composite raw
algebra of two represented matrix algebras. -/
noncomputable def kroneckerRealization (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) : R₁ ⊗[K] R₂ →ₐ[K] Matrix (n × m) (n × m) K :=
  (Matrix.kroneckerAlgEquiv n m K : Matrix n n K ⊗[K] Matrix m m K →ₐ[K] _).comp
    (Algebra.TensorProduct.map R₁.val R₂.val)

theorem kroneckerRealization_tmul (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) (a : R₁) (b : R₂) :
    kroneckerRealization R₁ R₂ (a ⊗ₜ b) = (a : Matrix n n K) ⊗ₖ (b : Matrix m m K) := by
  simp [kroneckerRealization]

/-- Over a field the Kronecker realization of `R₁ ⊗ R₂` is injective. -/
theorem kroneckerRealization_injective (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) : Function.Injective (kroneckerRealization R₁ R₂) := by
  have h := TensorProduct.map_injective_of_flat_flat R₁.val.toLinearMap R₂.val.toLinearMap
    Subtype.val_injective Subtype.val_injective
  intro x y hxy
  apply h
  exact (Matrix.kroneckerAlgEquiv n m K).injective hxy

/-- The independently accessible generators `a ⊗ I` (`a ∈ R₁`) and `I ⊗ b` (`b ∈ R₂`). -/
def independentGenerators (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) : Set (Matrix (n × m) (n × m) K) :=
  {x | ∃ a ∈ R₁, x = a ⊗ₖ (1 : Matrix m m K)} ∪ {x | ∃ b ∈ R₂, x = (1 : Matrix n n K) ⊗ₖ b}

/-- The image of the Kronecker realization is the algebra generated by the independently
accessible generators. -/
theorem range_kroneckerRealization (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) :
    (kroneckerRealization R₁ R₂).range = Algebra.adjoin K (independentGenerators R₁ R₂) := by
  apply le_antisymm
  · rintro _ ⟨t, rfl⟩
    induction t using TensorProduct.induction_on with
    | zero => simp
    | tmul a b =>
      change kroneckerRealization R₁ R₂ (a ⊗ₜ b) ∈ _
      rw [kroneckerRealization_tmul]
      have h : (a : Matrix n n K) ⊗ₖ (b : Matrix m m K)
          = ((a : Matrix n n K) ⊗ₖ (1 : Matrix m m K)) * ((1 : Matrix n n K) ⊗ₖ (b : Matrix m m K)) := by
        rw [← Matrix.mul_kronecker_mul, Matrix.mul_one, Matrix.one_mul]
      rw [h]
      exact Subalgebra.mul_mem _ (Algebra.subset_adjoin (Or.inl ⟨a, a.2, rfl⟩))
        (Algebra.subset_adjoin (Or.inr ⟨b, b.2, rfl⟩))
    | add x y hx hy => rw [map_add]; exact Subalgebra.add_mem _ hx hy
  · rw [Algebra.adjoin_le_iff]
    rintro _ (⟨a, ha, rfl⟩ | ⟨b, hb, rfl⟩)
    · refine ⟨⟨a, ha⟩ ⊗ₜ 1, ?_⟩
      change kroneckerRealization R₁ R₂ _ = _
      rw [kroneckerRealization_tmul]; rfl
    · refine ⟨1 ⊗ₜ ⟨b, hb⟩, ?_⟩
      change kroneckerRealization R₁ R₂ _ = _
      rw [kroneckerRealization_tmul]; rfl

/-- **Independently accessible generators generate the tensor product**: the algebra generated
by `a ⊗ I` and `I ⊗ b` is isomorphic to `R₁ ⊗ R₂`, by `a ⊗ b ↦ a ⊗ₖ b`. -/
noncomputable def generatedCompositeEquiv (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) :
    R₁ ⊗[K] R₂ ≃ₐ[K] Algebra.adjoin K (independentGenerators R₁ R₂) :=
  (AlgEquiv.ofInjective _ (kroneckerRealization_injective R₁ R₂)).trans
    (Subalgebra.equivOfEq _ _ (range_kroneckerRealization R₁ R₂))

theorem generatedCompositeEquiv_tmul (R₁ : Subalgebra K (Matrix n n K))
    (R₂ : Subalgebra K (Matrix m m K)) (a : R₁) (b : R₂) :
    (generatedCompositeEquiv R₁ R₂ (a ⊗ₜ b) : Matrix (n × m) (n × m) K)
      = (a : Matrix n n K) ⊗ₖ (b : Matrix m m K) := by
  rw [← kroneckerRealization_tmul]
  rfl

end KroneckerRealization

/-! ## Packaged independent composition -/

section Packaged

open DerivedPredictiveCarrierUniversal

/-- **`prop:supp-grand-monoidal`, independent composition (packaged).**  For two independent
typed processes with identity operations and product reachability, and span-closed contextual
families on finite-dimensional raw represented algebras: the product contextual family is
again span-closed (composites iterate); `Z₁₂^min ≃ Z₁^min × Z₂^min` via
`[(h₁,h₂)] ↦ ([h₁],[h₂])`; `𝒜₁₂^hist ≃ 𝒜₁^hist ⊗ 𝒜₂^hist` via `[r₁ ⊗ r₂] ↦ [r₁] ⊗ [r₂]`; and
word moments of independent word pairs factor (`eq:supp-grand-gram-product`).  Interchange
and reassociation: `typedIndepProductMinimalEquiv_comm/assoc`,
`compositeSpanEquiv_comm/assoc`. -/
theorem grand_monoidal_composite {K : Type*} [Field K] [StarRing K]
    {O₁ H₁ L₁ O₂ H₂ L₂ : Type*} (T₁ : TypedPredictiveSystem O₁ H₁ L₁)
    (T₂ : TypedPredictiveSystem O₂ H₂ L₂) (I₁ : IdentityOperation T₁.system)
    (I₂ : IdentityOperation T₂.system)
    {R₁ R₂ : Type*} [Ring R₁] [Algebra K R₁] [Ring R₂] [Algebra K R₂]
    [FiniteDimensional K R₁] [FiniteDimensional K R₂] [StarAddMonoid R₁] [StarModule K R₁]
    [StarAddMonoid R₂] [StarModule K R₂]
    (C₁ : Set (Dual K R₁)) (hC₁ : SpanContextClosed C₁)
    (C₂ : Set (Dual K R₂)) (hC₂ : SpanContextClosed C₂) :
    SpanContextClosed (productContexts C₁ C₂) ∧
    (∃ e : (typedIndepProduct T₁ T₂).TypedMinimalCarrier
        ≃ T₁.TypedMinimalCarrier × T₂.TypedMinimalCarrier,
      ∀ h, e (Quotient.mk _ h) = (Quotient.mk _ h.1, Quotient.mk _ h.2)) ∧
    (∃ f : SpanHistoryAlgebra (productContexts C₁ C₂) (productContexts_spanContextClosed hC₁ hC₂)
        ≃ₐ[K] SpanHistoryAlgebra C₁ hC₁ ⊗[K] SpanHistoryAlgebra C₂ hC₂,
      ∀ r₁ r₂, f (Ideal.Quotient.mk _ (r₁ ⊗ₜ r₂))
        = Ideal.Quotient.mk _ r₁ ⊗ₜ Ideal.Quotient.mk _ r₂) ∧
    (∀ (v₁ w₁ : R₁) (v₂ w₂ : R₂),
      spanHistoryMoment (productContexts C₁ C₂) (productContexts_spanContextClosed hC₁ hC₂)
          (v₁ ⊗ₜ[K] v₂) (w₁ ⊗ₜ[K] w₂)
        = spanHistoryMoment C₁ hC₁ v₁ w₁ * spanHistoryMoment C₂ hC₂ v₂ w₂) :=
  ⟨productContexts_spanContextClosed hC₁ hC₂,
    ⟨typedIndepProductMinimalEquiv T₁ T₂ I₁ I₂, typedIndepProductMinimalEquiv_mk T₁ T₂ I₁ I₂⟩,
    ⟨compositeSpanEquiv C₁ hC₁ C₂ hC₂, compositeSpanEquiv_mk_tmul C₁ hC₁ C₂ hC₂⟩,
    compositeSpanMoment C₁ hC₁ C₂ hC₂⟩

end Packaged

/-! ## Unitary covariance for represented operator algebras -/

section UnitaryCovariance

variable {H H' : Type*} [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]
  [NormedAddCommGroup H'] [InnerProductSpace ℂ H'] [CompleteSpace H']

/-- The raw represented algebra: the `*`-algebra generated by the represented operators. -/
abbrev RawOperatorAlgebra (S : Set (H →L[ℂ] H)) : Type _ := StarAlgebra.adjoin ℂ S

theorem conj_mem_adjoin_image (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) (a : H →L[ℂ] H)
    (ha : a ∈ StarAlgebra.adjoin ℂ S) :
    e.conjStarAlgEquiv a ∈ StarAlgebra.adjoin ℂ (e.conjStarAlgEquiv '' S) := by
  have hle : StarAlgebra.adjoin ℂ S ≤ StarSubalgebra.comap
      (StarAlgHomClass.toStarAlgHom e.conjStarAlgEquiv)
      (StarAlgebra.adjoin ℂ (e.conjStarAlgEquiv '' S)) := by
    rw [StarAlgebra.adjoin_le_iff]
    intro s hs
    exact StarAlgebra.subset_adjoin ℂ _ ⟨s, hs, rfl⟩
  exact hle ha

theorem conj_symm_mem_adjoin (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) (b : H' →L[ℂ] H')
    (hb : b ∈ StarAlgebra.adjoin ℂ (e.conjStarAlgEquiv '' S)) :
    e.conjStarAlgEquiv.symm b ∈ StarAlgebra.adjoin ℂ S := by
  have hle : StarAlgebra.adjoin ℂ (e.conjStarAlgEquiv '' S) ≤ StarSubalgebra.comap
      (StarAlgHomClass.toStarAlgHom e.conjStarAlgEquiv.symm) (StarAlgebra.adjoin ℂ S) := by
    rw [StarAlgebra.adjoin_le_iff]
    rintro _ ⟨s, hs, rfl⟩
    change e.conjStarAlgEquiv.symm (e.conjStarAlgEquiv s) ∈ StarAlgebra.adjoin ℂ S
    rw [StarAlgEquiv.symm_apply_apply]
    exact StarAlgebra.subset_adjoin ℂ _ hs
  exact hle hb

/-- **A unitary equivalence carrying represented generators to represented generators induces
a `*`-isomorphism of the raw represented algebras**, `a ↦ U a U^*`. -/
noncomputable def adjoinConjStarAlgEquiv (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) :
    RawOperatorAlgebra S ≃⋆ₐ[ℂ] RawOperatorAlgebra (e.conjStarAlgEquiv '' S) where
  toFun a := ⟨e.conjStarAlgEquiv a, conj_mem_adjoin_image e S a a.2⟩
  invFun b := ⟨e.conjStarAlgEquiv.symm b, conj_symm_mem_adjoin e S b b.2⟩
  left_inv a := Subtype.ext (e.conjStarAlgEquiv.symm_apply_apply a)
  right_inv b := Subtype.ext (e.conjStarAlgEquiv.apply_symm_apply b)
  map_mul' a b := Subtype.ext (map_mul e.conjStarAlgEquiv (a : H →L[ℂ] H) b)
  map_add' a b := Subtype.ext (map_add e.conjStarAlgEquiv (a : H →L[ℂ] H) b)
  map_star' a := Subtype.ext (map_star e.conjStarAlgEquiv (a : H →L[ℂ] H))
  map_smul' c a := Subtype.ext (map_smul e.conjStarAlgEquiv c (a : H →L[ℂ] H))

theorem adjoinConjStarAlgEquiv_apply (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H))
    (a : RawOperatorAlgebra S) (y : H') :
    (adjoinConjStarAlgEquiv e S a : H' →L[ℂ] H') y = e ((a : H →L[ℂ] H) (e.symm y)) := rfl

/-- The record matrix coefficient `a ↦ ⟪u, (x a y) v⟫` of the history context `(x, y)` between
record vectors `u, v`. -/
noncomputable def recordCoefficient {S : Set (H →L[ℂ] H)} (u v : H)
    (x y : RawOperatorAlgebra S) : Dual ℂ (RawOperatorAlgebra S) where
  toFun a := inner ℂ u (((x * a * y : RawOperatorAlgebra S) : H →L[ℂ] H) v)
  map_add' a b := by
    rw [mul_add, add_mul]
    exact inner_add_right _ _ _
  map_smul' c a := by
    rw [mul_smul_comm, smul_mul_assoc]
    exact inner_smul_right _ _ _

theorem recordCoefficient_apply {S : Set (H →L[ℂ] H)} (u v : H) (x y a : RawOperatorAlgebra S) :
    recordCoefficient u v x y a = inner ℂ u (((x * a * y : RawOperatorAlgebra S) : H →L[ℂ] H) v) :=
  rfl

/-- The admitted contexts of a record set: all record matrix coefficients of all left and right
history contexts. -/
def recordContexts (S : Set (H →L[ℂ] H)) (rec : Set H) : Set (Dual ℂ (RawOperatorAlgebra S)) :=
  {ψ | ∃ u ∈ rec, ∃ v ∈ rec, ∃ x y : RawOperatorAlgebra S, ψ = recordCoefficient u v x y}

theorem recordContexts_contextClosed (S : Set (H →L[ℂ] H)) (rec : Set H) :
    ContextClosed (recordContexts S rec) := by
  rintro _ ⟨u, hu, v, hv, x, y, rfl⟩ x' y'
  refine ⟨u, hu, v, hv, x * x', y' * y, ?_⟩
  ext a
  simp only [LinearMap.coe_comp, Function.comp_apply, LinearMap.mulLeft_apply,
    LinearMap.mulRight_apply, recordCoefficient_apply, mul_assoc]

theorem recordCoefficient_comp_conj (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) (u v : H)
    (x y : RawOperatorAlgebra S) :
    recordCoefficient (e u) (e v) (adjoinConjStarAlgEquiv e S x) (adjoinConjStarAlgEquiv e S y)
        ∘ₗ (AlgEquivClass.toAlgEquiv (adjoinConjStarAlgEquiv e S) :
          RawOperatorAlgebra S ≃ₐ[ℂ] RawOperatorAlgebra (e.conjStarAlgEquiv '' S)).toLinearMap
      = recordCoefficient u v x y := by
  ext a
  rw [LinearMap.comp_apply, AlgEquiv.toLinearMap_apply]
  change inner ℂ (e u) ((((adjoinConjStarAlgEquiv e S x) * (adjoinConjStarAlgEquiv e S a) *
    (adjoinConjStarAlgEquiv e S y) : RawOperatorAlgebra (e.conjStarAlgEquiv '' S)) :
      H' →L[ℂ] H') (e v)) = _
  rw [← map_mul, ← map_mul, adjoinConjStarAlgEquiv_apply, LinearIsometryEquiv.symm_apply_apply,
    LinearIsometryEquiv.inner_map_map]
  rfl

/-- A record-preserving unitary carries the admitted contexts to the admitted contexts. -/
theorem recordContexts_conj_iff (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) (rec : Set H)
    (ψ : Dual ℂ (RawOperatorAlgebra (e.conjStarAlgEquiv '' S))) :
    ψ ∈ recordContexts (e.conjStarAlgEquiv '' S) (e '' rec) ↔
      ψ ∘ₗ (AlgEquivClass.toAlgEquiv (adjoinConjStarAlgEquiv e S) :
          RawOperatorAlgebra S ≃ₐ[ℂ] RawOperatorAlgebra (e.conjStarAlgEquiv '' S)).toLinearMap
        ∈ recordContexts S rec := by
  set Ψ := adjoinConjStarAlgEquiv e S
  constructor
  · rintro ⟨_, ⟨u, hu, rfl⟩, _, ⟨v, hv, rfl⟩, x', y', rfl⟩
    refine ⟨u, hu, v, hv, Ψ.symm x', Ψ.symm y', ?_⟩
    rw [← recordCoefficient_comp_conj e S u v, StarAlgEquiv.apply_symm_apply,
      StarAlgEquiv.apply_symm_apply]
  · rintro ⟨u, hu, v, hv, x, y, hψ⟩
    refine ⟨e u, ⟨u, hu, rfl⟩, e v, ⟨v, hv, rfl⟩, Ψ x, Ψ y, ?_⟩
    rw [← recordCoefficient_comp_conj e S u v x y] at hψ
    ext b
    have := LinearMap.congr_fun hψ (Ψ.symm b)
    simp only [LinearMap.coe_comp, Function.comp_apply, AlgEquiv.toLinearMap_apply] at this
    convert this using 2 <;> exact (Ψ.apply_symm_apply b).symm

/-- **`prop:supp-grand-monoidal`, unitary covariance (concrete form).**  A unitary
`U : H ≃ H'` carrying the represented generators `S` to `U S U^*` and the record vectors to
the record vectors induces a `*`-isomorphism of history algebras `[a] ↦ [U a U^*]`,
compatible with the involution, preserving every word moment `τ̂_reg([v]^*[w])`. -/
theorem unitary_history_covariance (e : H ≃ₗᵢ[ℂ] H') (S : Set (H →L[ℂ] H)) (rec : Set H) :
    ∃ φ : HistoryAlgebra (recordContexts S rec) (recordContexts_contextClosed S rec)
        ≃ₐ[ℂ] HistoryAlgebra (recordContexts (e.conjStarAlgEquiv '' S) (e '' rec))
          (recordContexts_contextClosed _ _),
      (∀ r, φ (Ideal.Quotient.mk _ r) = Ideal.Quotient.mk _ (adjoinConjStarAlgEquiv e S r)) ∧
      (∀ r, φ (Ideal.Quotient.mk _ (star r))
        = Ideal.Quotient.mk _ (star (adjoinConjStarAlgEquiv e S r))) ∧
      (∀ v w, historyMoment (recordContexts (e.conjStarAlgEquiv '' S) (e '' rec))
          (recordContexts_contextClosed _ _)
          (adjoinConjStarAlgEquiv e S v) (adjoinConjStarAlgEquiv e S w)
        = historyMoment (recordContexts S rec) (recordContexts_contextClosed S rec) v w) :=
  historyAlgebra_starAlgEquiv _ _ _ _ (adjoinConjStarAlgEquiv e S)
    (recordContexts_conj_iff e S rec)

end UnitaryCovariance

end GrandTensorMonoidal

end RenewalGeometry
