/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Algebra.MatrixKrausExistence
import RenewalGeometry.Predictive.FiniteProcessCombTomography
/-!
# The represented process algebra of typed branches

Paper `predictive_spectral_geometry`, label `thm:ncg-process-history-representation`.

## The free star algebra on an involutive alphabet

`FreeStarAlg X` (for an alphabet with an involution `x ↦ x⋆`, `[InvolutiveStar X]`) is the
complex algebra of finite linear combinations of words in `X`, with the conjugate-linear
anti-involution reversing words, applying `⋆` letterwise and conjugating coefficients
(`FreeStarAlg.instStarRing`, `FreeStarAlg.instStarModule`).  `FreeStarAlg.lift g` is the unique
star algebra homomorphism extending a letter assignment `g` with `g (x⋆) = star (g x)`
(`FreeStarAlg.lift_ι`, `FreeStarAlg.starAlgHom_ext`); its range is the star algebra generated by
the letters' images (`FreeStarAlg.range_lift`).

## Typed branches

A finite quiver of boundary objects `ξ` (memory spaces `ℂ^{D ξ}`) and primitive branches
`a : src a → tgt a` with reduced superoperators `op a` (`ProcessHistory.TypedBranches`).  The
Hilbert–Schmidt memory space is `𝒳 = ⊕_ξ B(ℂ^{D ξ})`, with orthonormal basis indexed by
`HSIdx D = Σ ξ, D ξ × D ξ`; `hsMat` is the Hilbert–Schmidt matrix of a superoperator.

* `ProcessHistory.PathLetter`: primitive branches `a`, formal reverses `a♯` and object units
  `e_ξ`, with `a⋆ = a♯`, `e_ξ⋆ = e_ξ`; `FreePathAlg = FreeStarAlg (PathLetter …)` is the free
  path star algebra.  The path relations (object units orthogonal projections summing to one,
  `P_η ρ(a) P_ξ = ρ(a)`, non-composable products zero) hold in the representation, so the
  quotient by `Ker ρ_X` is the same as for the path algebra.
* `TypedBranches.rep`: the representation `ρ_X` (`a ↦ P_η T_a P_ξ = branchOp a`,
  `a♯ ↦ branchOp aᴴ` (Hilbert–Schmidt adjoint), `e_ξ ↦ P_ξ = objProj ξ`).
* `process_history_representation`: `ρ_X` is a star homomorphism respecting the path
  relations, `Ker ρ_X` is a two-sided star ideal, `𝔉_X / Ker ρ_X ≃ₐ C*(ρ_X(a), P_ξ)` (the
  isomorphism intertwines the formal involution with the Hilbert–Schmidt adjoint), a
  finite-dimensional closed star subalgebra of `B(𝒳)`.
* Independence: `TypedBranches.rep_eq_of_op_eq` (ρ depends only on the reduced superoperators,
  hence not on Kraus coordinates or on the tomographic frame);
  `process_history_unitary_invariance` (memory unitaries `U_ξ` relating two support-minimal
  realizations conjugate the whole word representation by the Hilbert–Schmidt unitary
  `⊕_ξ U_ξ ⊗ Ū_ξ`, giving a represented star isomorphism); `process_history_kraus_invariance`
  and `krausMap_conj_eq` (Kraus/isometry coordinates conjugated by memory unitaries give
  Hilbert–Schmidt conjugate reduced branch maps); `hsMat_conj`, `hsApply_kron`.
-/

namespace RenewalGeometry

open Matrix
open scoped Kronecker

set_option linter.unusedSectionVars false

/-! ### The free star algebra on an involutive alphabet -/

/-- The free complex star algebra on an alphabet `X` with an involution: complex linear
combinations of words. -/
def FreeStarAlg (X : Type*) : Type _ := MonoidAlgebra ℂ (FreeMonoid X)

namespace FreeStarAlg

variable {X : Type*}

noncomputable instance instRing : Ring (FreeStarAlg X) :=
  inferInstanceAs (Ring (MonoidAlgebra ℂ (FreeMonoid X)))

noncomputable instance instAlgebra : Algebra ℂ (FreeStarAlg X) :=
  inferInstanceAs (Algebra ℂ (MonoidAlgebra ℂ (FreeMonoid X)))

variable [InvolutiveStar X]

/-- Word involution: reverse the word and apply `⋆` to every letter. -/
def wordStar (w : FreeMonoid X) : FreeMonoid X := star (FreeMonoid.map (star : X → X) w)

theorem toList_wordStar (w : FreeMonoid X) :
    FreeMonoid.toList (wordStar w) = (FreeMonoid.toList w).reverse.map star := by
  simp [wordStar, List.map_reverse]
  rfl

theorem wordStar_wordStar (w : FreeMonoid X) : wordStar (wordStar w) = w := by
  apply FreeMonoid.toList.injective
  have h : (star ∘ star : X → X) = id := funext star_star
  rw [toList_wordStar, toList_wordStar, List.map_reverse, List.map_map, h, List.map_id,
    List.reverse_reverse]

theorem wordStar_mul (v w : FreeMonoid X) : wordStar (v * w) = wordStar w * wordStar v := by
  simp [wordStar, star_mul]

theorem wordStar_of (x : X) : wordStar (FreeMonoid.of x) = FreeMonoid.of (star x) := by
  simp [wordStar]

/-- The word involution as an equivalence. -/
def wordStarEquiv : FreeMonoid X ≃ FreeMonoid X where
  toFun := wordStar
  invFun := wordStar
  left_inv := wordStar_wordStar
  right_inv := wordStar_wordStar

/-- The conjugate-linear anti-involution on complex combinations of words. -/
noncomputable def mstar (f : MonoidAlgebra ℂ (FreeMonoid X)) : MonoidAlgebra ℂ (FreeMonoid X) :=
  MonoidAlgebra.ofCoeff (Finsupp.equivMapDomain wordStarEquiv
    (Finsupp.mapRange star (star_zero ℂ) (MonoidAlgebra.coeff f)))

theorem coeff_mstar (f : MonoidAlgebra ℂ (FreeMonoid X)) (w : FreeMonoid X) :
    (mstar f).coeff w = star (f.coeff (wordStar w)) := by
  simp [mstar, Finsupp.equivMapDomain_apply, wordStarEquiv]

theorem mstar_ext {f g : MonoidAlgebra ℂ (FreeMonoid X)} (h : ∀ w, f.coeff w = g.coeff w) :
    f = g :=
  MonoidAlgebra.coeffEquiv.injective (Finsupp.ext h)

theorem mstar_single (w : FreeMonoid X) (r : ℂ) :
    mstar (MonoidAlgebra.single w r) = MonoidAlgebra.single (wordStar w) (star r) := by
  classical
  refine mstar_ext fun v => ?_
  rw [coeff_mstar, MonoidAlgebra.coeff_single, MonoidAlgebra.coeff_single, Finsupp.single_apply,
    Finsupp.single_apply]
  by_cases h : w = wordStar v
  · subst h
    simp [wordStar_wordStar]
  · rw [if_neg h, if_neg, star_zero]
    rintro rfl
    exact h (wordStar_wordStar w).symm

theorem mstar_add (f g : MonoidAlgebra ℂ (FreeMonoid X)) :
    mstar (f + g) = mstar f + mstar g := by
  refine mstar_ext fun v => ?_
  rw [MonoidAlgebra.coeff_add, Finsupp.add_apply, coeff_mstar, coeff_mstar, coeff_mstar,
    MonoidAlgebra.coeff_add, Finsupp.add_apply, star_add]

theorem mstar_zero : mstar (0 : MonoidAlgebra ℂ (FreeMonoid X)) = 0 := by
  refine mstar_ext fun v => ?_
  rw [coeff_mstar]
  simp

theorem mstar_mstar (f : MonoidAlgebra ℂ (FreeMonoid X)) : mstar (mstar f) = f := by
  refine mstar_ext fun v => ?_
  rw [coeff_mstar, coeff_mstar, star_star, wordStar_wordStar]

theorem mstar_mul (f g : MonoidAlgebra ℂ (FreeMonoid X)) :
    mstar (f * g) = mstar g * mstar f := by
  induction f using MonoidAlgebra.induction_linear with
  | zero => rw [zero_mul, mstar_zero, mul_zero]
  | add f₁ f₂ h₁ h₂ => rw [add_mul, mstar_add, h₁, h₂, mstar_add, mul_add]
  | single v r =>
    induction g using MonoidAlgebra.induction_linear with
    | zero => rw [mul_zero, mstar_zero, zero_mul]
    | add g₁ g₂ h₁ h₂ => rw [mul_add, mstar_add, h₁, h₂, mstar_add, add_mul]
    | single w s =>
      rw [MonoidAlgebra.single_mul_single, mstar_single, mstar_single, mstar_single,
        MonoidAlgebra.single_mul_single, wordStar_mul, star_mul', mul_comm (star s)]

theorem mstar_smul (c : ℂ) (f : MonoidAlgebra ℂ (FreeMonoid X)) :
    mstar (c • f) = star c • mstar f := by
  refine mstar_ext fun v => ?_
  rw [coeff_mstar, MonoidAlgebra.coeff_smul, MonoidAlgebra.coeff_smul, Finsupp.smul_apply,
    Finsupp.smul_apply, coeff_mstar, smul_eq_mul, smul_eq_mul, star_mul', mul_comm]

noncomputable instance instStarRing : StarRing (FreeStarAlg X) where
  star := mstar
  star_involutive := mstar_mstar
  star_mul := mstar_mul
  star_add := mstar_add

instance instStarModule : StarModule ℂ (FreeStarAlg X) where
  star_smul c f := mstar_smul c f

/-- A monomial `r · w` of the free star algebra. -/
noncomputable def single (w : FreeMonoid X) (r : ℂ) : FreeStarAlg X := MonoidAlgebra.single w r

theorem star_single (w : FreeMonoid X) (r : ℂ) :
    star (single w r) = single (wordStar w) (star r) := mstar_single w r

theorem single_mul_single (v w : FreeMonoid X) (r s : ℂ) :
    single v r * single w s = single (v * w) (r * s) := MonoidAlgebra.single_mul_single v w r s

theorem single_eq_smul (w : FreeMonoid X) (r : ℂ) : single w r = r • single w 1 := by
  have h := MonoidAlgebra.smul_single (R := ℂ) r w (1 : ℂ)
  rw [smul_eq_mul, mul_one] at h
  exact h.symm

theorem single_one_one : single (1 : FreeMonoid X) 1 = 1 := rfl

/-- Linear induction principle for the free star algebra. -/
@[elab_as_elim]
theorem induction_linear {motive : FreeStarAlg X → Prop} (f : FreeStarAlg X) (zero : motive 0)
    (add : ∀ f g, motive f → motive g → motive (f + g))
    (single : ∀ w r, motive (single w r)) : motive f :=
  MonoidAlgebra.induction_linear (motive := motive) f zero add single

/-- The generator of a letter. -/
noncomputable def ι (x : X) : FreeStarAlg X := single (FreeMonoid.of x) 1

theorem star_ι (x : X) : star (ι x) = ι (star x) := by
  rw [ι, star_single, wordStar_of, star_one]
  rfl

variable {B : Type*} [Ring B] [StarRing B] [Algebra ℂ B] [StarModule ℂ B]

/-- The word value `g(x₁) ⋯ g(x_k)` of a letter assignment, and its involution law. -/
theorem lift_wordStar (g : X → B) (hg : ∀ x, g (star x) = star (g x)) (w : FreeMonoid X) :
    FreeMonoid.lift g (wordStar w) = star (FreeMonoid.lift g w) := by
  induction w using FreeMonoid.inductionOn' with
  | one => simp [wordStar]
  | of_mul x w ih =>
    rw [wordStar_mul, map_mul, map_mul, ih, wordStar_of, FreeMonoid.lift_eval_of,
      FreeMonoid.lift_eval_of, hg, star_mul]

/-- **Universal property**: a letter assignment compatible with the involutions extends to a
star algebra homomorphism. -/
noncomputable def lift (g : X → B) (hg : ∀ x, g (star x) = star (g x)) :
    FreeStarAlg X →⋆ₐ[ℂ] B :=
  { (MonoidAlgebra.lift ℂ B (FreeMonoid X) (FreeMonoid.lift g) :
      MonoidAlgebra ℂ (FreeMonoid X) →ₐ[ℂ] B) with
    map_star' := fun f => by
      change MonoidAlgebra.lift ℂ B (FreeMonoid X) (FreeMonoid.lift g) (mstar f) =
        star (MonoidAlgebra.lift ℂ B (FreeMonoid X) (FreeMonoid.lift g) f)
      induction f using MonoidAlgebra.induction_linear with
      | zero => simp [mstar_zero]
      | add f₁ f₂ h₁ h₂ => rw [mstar_add, map_add, map_add, h₁, h₂, star_add]
      | single w r =>
        rw [mstar_single, MonoidAlgebra.lift_single, MonoidAlgebra.lift_single,
          lift_wordStar g hg, star_smul] }

theorem lift_apply_single (g : X → B) (hg : ∀ x, g (star x) = star (g x)) (w : FreeMonoid X)
    (r : ℂ) : lift g hg (single w r) = r • FreeMonoid.lift g w :=
  MonoidAlgebra.lift_single _ _ _

theorem lift_ι (g : X → B) (hg : ∀ x, g (star x) = star (g x)) (x : X) :
    lift g hg (ι x) = g x := by
  rw [ι, lift_apply_single, one_smul, FreeMonoid.lift_eval_of]

/-- Star algebra homomorphisms out of the free star algebra are determined by the letters. -/
theorem starAlgHom_ext {φ ψ : FreeStarAlg X →⋆ₐ[ℂ] B} (h : ∀ x, φ (ι x) = ψ (ι x)) :
    φ = ψ := by
  have hw : ∀ w : FreeMonoid X, φ (single w 1) = ψ (single w 1) := by
    intro w
    induction w using FreeMonoid.inductionOn' with
    | one => rw [single_one_one, map_one, map_one]
    | of_mul x w ih =>
      have hs : single (FreeMonoid.of x * w) (1 : ℂ) = ι x * single w 1 := by
        rw [ι, single_mul_single, one_mul]
      rw [hs, map_mul, map_mul, h, ih]
  apply StarAlgHom.ext
  intro f
  induction f using induction_linear with
  | zero => rw [map_zero, map_zero]
  | add f₁ f₂ h₁ h₂ => rw [map_add, map_add, h₁, h₂]
  | single w r => rw [single_eq_smul, map_smul, map_smul, hw]

/-- The range of the lift is the star algebra generated by the letter images. -/
theorem range_lift (g : X → B) (hg : ∀ x, g (star x) = star (g x)) :
    (lift g hg).range = StarAlgebra.adjoin ℂ (Set.range g) := by
  apply le_antisymm
  · rintro _ ⟨f, rfl⟩
    change lift g hg f ∈ _
    induction f using induction_linear with
    | zero => rw [map_zero]; exact zero_mem _
    | add f₁ f₂ h₁ h₂ => rw [map_add]; exact add_mem h₁ h₂
    | single w r =>
      rw [lift_apply_single]
      refine Subalgebra.smul_mem _ ?_ r
      induction w using FreeMonoid.inductionOn' with
      | one => rw [map_one]; exact one_mem _
      | of_mul x w ih =>
        rw [map_mul, FreeMonoid.lift_eval_of]
        exact mul_mem (StarAlgebra.subset_adjoin ℂ _ ⟨x, rfl⟩) ih
  · refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨x, rfl⟩
    exact ⟨ι x, lift_ι g hg x⟩

end FreeStarAlg

/-! ### Rectangular Hilbert–Schmidt matrices -/

namespace ProcessHistory

section HSRect

variable {p q r : Type*} [Fintype p] [DecidableEq p] [Fintype q] [DecidableEq q] [Fintype r]
  [DecidableEq r]

/-- Vectorisation of a square matrix. -/
def hsVec (X : Matrix p p ℂ) : p × p → ℂ := fun s => X s.1 s.2

/-- Inverse of the vectorisation. -/
def hsUnvec (v : q × q → ℂ) : Matrix q q ℂ := Matrix.of fun i j => v (i, j)

/-- The Hilbert–Schmidt matrix of a superoperator `B(ℂ^p) → B(ℂ^q)` in the bases of matrix
units (an orthonormal basis for the Hilbert–Schmidt inner product). -/
def hsMat (Φ : Matrix p p ℂ →ₗ[ℂ] Matrix q q ℂ) : Matrix (q × q) (p × p) ℂ :=
  Matrix.of fun s t => Φ (Matrix.single t.1 t.2 1) s.1 s.2

/-- The superoperator of a Hilbert–Schmidt matrix. -/
def hsApply (M : Matrix (q × q) (p × p) ℂ) (X : Matrix p p ℂ) : Matrix q q ℂ :=
  hsUnvec (M *ᵥ hsVec X)

theorem hsVec_single (k l : p) : hsVec (Matrix.single k l (1 : ℂ)) = Pi.single (k, l) 1 := by
  funext s
  obtain ⟨a, b⟩ := s
  simp only [hsVec, single_apply, Pi.single_apply, Prod.mk.injEq]
  by_cases h : k = a ∧ l = b
  · obtain ⟨rfl, rfl⟩ := h; simp
  · rw [if_neg h, if_neg]
    rintro ⟨rfl, rfl⟩; exact h ⟨rfl, rfl⟩

theorem hsApply_single (M : Matrix (q × q) (p × p) ℂ) (i j : q) (k l : p) :
    hsApply M (Matrix.single k l 1) i j = M (i, j) (k, l) := by
  simp [hsApply, hsUnvec, hsVec_single]

theorem hsMat_ext {M N : Matrix (q × q) (p × p) ℂ} (h : ∀ X, hsApply M X = hsApply N X) :
    M = N := by
  ext ⟨i, j⟩ ⟨k, l⟩
  rw [← hsApply_single M i j k l, ← hsApply_single N i j k l, h]

theorem hsApply_hsMat (Φ : Matrix p p ℂ →ₗ[ℂ] Matrix q q ℂ) (X : Matrix p p ℂ) :
    hsApply (hsMat Φ) X = Φ X := by
  ext i j
  conv_rhs => rw [Matrix.matrix_eq_sum_single X]
  have hs : ∀ k l, Matrix.single k l (X k l) = X k l • Matrix.single k l (1 : ℂ) := fun k l => by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  simp only [hs, map_sum, map_smul, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul]
  simp only [hsApply, hsUnvec, hsVec, hsMat, mulVec, dotProduct, Matrix.of_apply,
    Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun k _ => Finset.sum_congr rfl fun l _ => ?_
  ring

theorem hsApply_mul (M : Matrix (r × r) (q × q) ℂ) (N : Matrix (q × q) (p × p) ℂ)
    (X : Matrix p p ℂ) : hsApply (M * N) X = hsApply M (hsApply N X) := by
  ext i j
  simp only [hsApply, hsUnvec, Matrix.of_apply]
  rw [← mulVec_mulVec]
  rfl

/-- **Hilbert–Schmidt conjugation is a Kronecker matrix**: `vec(W X Wᴴ) = (W ⊗ W̄) vec X`. -/
theorem hsApply_kron (W : Matrix q p ℂ) (X : Matrix p p ℂ) :
    hsApply (W ⊗ₖ W.map star) X = W * X * Wᴴ := by
  ext i j
  simp only [hsApply, hsUnvec, hsVec, Matrix.of_apply, mulVec, dotProduct, kronecker_apply,
    Matrix.map_apply, Matrix.mul_apply, conjTranspose_apply, Fintype.sum_prod_type,
    Finset.sum_mul]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun l _ => Finset.sum_congr rfl fun k _ => ?_
  ring

theorem conjTranspose_kron_map (W : Matrix q p ℂ) :
    (W ⊗ₖ W.map star)ᴴ = Wᴴ ⊗ₖ (Wᴴ).map star := by
  rw [conjTranspose_kronecker]
  congr 1

theorem map_star_conjTranspose_mul {W : Matrix q p ℂ} (h : Wᴴ * W = 1) :
    (Wᴴ).map star * W.map star = 1 := by
  ext i j
  have hij := congrArg star (congrFun (congrFun h i) j)
  simp only [Matrix.mul_apply, conjTranspose_apply, star_sum, star_mul', star_star] at hij
  simp only [Matrix.mul_apply, Matrix.map_apply, conjTranspose_apply, star_star]
  rw [hij, one_apply]
  split_ifs <;> simp

/-- `W ⊗ W̄` is an isometry when `W` is. -/
theorem kron_map_isometry {W : Matrix q p ℂ} (h : Wᴴ * W = 1) :
    (W ⊗ₖ W.map star)ᴴ * (W ⊗ₖ W.map star) = 1 := by
  rw [conjTranspose_kron_map, ← mul_kronecker_mul, h, map_star_conjTranspose_mul h,
    one_kronecker_one]

/-- **Memory unitaries act on reduced branch maps by Hilbert–Schmidt conjugation**: if
`T'(Y) = U_q T(U_pᴴ Y U_p) U_qᴴ`, the Hilbert–Schmidt matrices are related by the Kronecker
unitaries `U ⊗ Ū`. -/
theorem hsMat_conj {p' q' : Type*} [Fintype p'] [DecidableEq p'] [Fintype q'] [DecidableEq q']
    (Φ : Matrix p p ℂ →ₗ[ℂ] Matrix q q ℂ) (Φ' : Matrix p' p' ℂ →ₗ[ℂ] Matrix q' q' ℂ)
    (Up : Matrix p' p ℂ) (Uq : Matrix q' q ℂ)
    (h : ∀ Y, Φ' Y = Uq * Φ (Upᴴ * Y * Up) * Uqᴴ) :
    hsMat Φ' = (Uq ⊗ₖ Uq.map star) * hsMat Φ * (Up ⊗ₖ Up.map star)ᴴ := by
  refine hsMat_ext fun X => ?_
  rw [hsApply_hsMat, h, hsApply_mul, hsApply_mul, conjTranspose_kron_map, hsApply_kron,
    hsApply_hsMat, hsApply_kron, conjTranspose_conjTranspose]

/-- Kraus coordinates conjugated by memory unitaries give the Hilbert–Schmidt conjugated
reduced map: `∑ (U' K U^ᴴ) Y (U' K Uᴴ)ᴴ = U' (∑ K (Uᴴ Y U) Kᴴ) U'ᴴ`. -/
theorem krausMap_conj_eq {κ : Type*} [Fintype κ] {p' q' : Type*} [Fintype p'] [Fintype q']
    (K : κ → Matrix q p ℂ) (U : Matrix p' p ℂ) (U' : Matrix q' q ℂ) (Y : Matrix p' p' ℂ) :
    MatrixKraus.krausMap (fun ν => U' * K ν * Uᴴ) Y =
      U' * MatrixKraus.krausMap K (Uᴴ * Y * U) * U'ᴴ := by
  simp only [MatrixKraus.krausMap_apply, Matrix.mul_sum, Matrix.sum_mul, conjTranspose_mul,
    conjTranspose_conjTranspose, Matrix.mul_assoc]

end HSRect

/-! ### Typed branches and the representation `ρ_X` -/

/-- The letters of the free path star algebra: primitive branches, their formal reverses and
the object units (trivial paths). -/
inductive PathLetter (Obj Arr : Type*)
  | arrow (a : Arr)
  | reverse (a : Arr)
  | unit (ξ : Obj)

namespace PathLetter

variable {Obj Arr : Type*}

/-- The formal involution `a ↦ a♯`, `a♯ ↦ a`, `e_ξ ↦ e_ξ`. -/
def inv : PathLetter Obj Arr → PathLetter Obj Arr
  | arrow a => reverse a
  | reverse a => arrow a
  | unit ξ => unit ξ

instance : InvolutiveStar (PathLetter Obj Arr) where
  star := inv
  star_involutive := by rintro (a | a | ξ) <;> rfl

end PathLetter

/-- The free path star algebra `𝔉_X` on the primitive branches, their formal reverses and the
object units. -/
abbrev FreePathAlg (Obj Arr : Type*) := FreeStarAlg (PathLetter Obj Arr)

section Blocks

variable {Obj : Type*} [Fintype Obj] [DecidableEq Obj] (D : Obj → Type*)
  [∀ ξ, Fintype (D ξ)] [∀ ξ, DecidableEq (D ξ)]

/-- The orthonormal-basis index of the Hilbert–Schmidt memory space `𝒳 = ⊕_ξ B(ℂ^{D ξ})`. -/
abbrev HSIdx := Σ ξ, D ξ × D ξ

/-- The isometric inclusion of the block `B(ℂ^{D ξ})` into `𝒳`. -/
def blockIncl (ξ : Obj) : Matrix (HSIdx D) (D ξ × D ξ) ℂ :=
  Matrix.of fun P s => if P = ⟨ξ, s⟩ then 1 else 0

/-- The orthogonal projection `P_ξ` of `𝒳` onto the block `B(ℂ^{D ξ})`. -/
def objProj (ξ : Obj) : Matrix (HSIdx D) (HSIdx D) ℂ := blockIncl D ξ * (blockIncl D ξ)ᴴ

theorem blockIncl_isometry (ξ : Obj) : (blockIncl D ξ)ᴴ * blockIncl D ξ = 1 := by
  ext s t
  simp only [Matrix.mul_apply, conjTranspose_apply, blockIncl, Matrix.of_apply, one_apply]
  simp only [apply_ite star, star_one, star_zero, ite_mul, one_mul, zero_mul,
    Finset.sum_ite_eq', Finset.mem_univ, if_true]
  by_cases h : s = t
  · subst h; simp
  · rw [if_neg, if_neg h]
    intro h'
    exact h (by simpa using h')

theorem blockIncl_orth {ξ η : Obj} (h : ξ ≠ η) : (blockIncl D ξ)ᴴ * blockIncl D η = 0 := by
  ext s t
  simp only [Matrix.mul_apply, conjTranspose_apply, blockIncl, Matrix.of_apply, Matrix.zero_apply]
  simp only [apply_ite star, star_one, star_zero, ite_mul, one_mul, zero_mul,
    Finset.sum_ite_eq', Finset.mem_univ, if_true]
  rw [if_neg]
  intro h'
  exact h (congrArg Sigma.fst h')

theorem sum_objProj : ∑ ξ, objProj D ξ = 1 := by
  ext P Q
  simp only [objProj, Matrix.sum_apply, Matrix.mul_apply, conjTranspose_apply, blockIncl,
    Matrix.of_apply, apply_ite star, star_one, star_zero, mul_ite, mul_one, mul_zero]
  rw [← Fintype.sum_sigma (fun R : HSIdx D => if Q = R then (if P = R then (1 : ℂ) else 0)
    else 0)]
  simp only [Finset.sum_ite_eq, Finset.mem_univ, if_true, one_apply]

theorem objProj_conjTranspose (ξ : Obj) : (objProj D ξ)ᴴ = objProj D ξ := by
  simp [objProj, conjTranspose_mul]

theorem objProj_mul_self (ξ : Obj) : objProj D ξ * objProj D ξ = objProj D ξ := by
  simp only [objProj, Matrix.mul_assoc]
  rw [← Matrix.mul_assoc (blockIncl D ξ)ᴴ, blockIncl_isometry, Matrix.one_mul]

theorem objProj_mul_of_ne {ξ η : Obj} (h : ξ ≠ η) : objProj D ξ * objProj D η = 0 := by
  simp only [objProj, Matrix.mul_assoc]
  rw [← Matrix.mul_assoc (blockIncl D ξ)ᴴ, blockIncl_orth D h, Matrix.zero_mul,
    Matrix.mul_zero]

end Blocks

/-- **Typed branch data**: a finite quiver of boundary objects `ξ` (memory spaces `ℂ^{D ξ}`)
and primitive branches `a : src a → tgt a` with their reduced superoperators
`op a : B(ℂ^{D(src a)}) → B(ℂ^{D(tgt a)})`. -/
structure TypedBranches (Obj Arr : Type*) (src tgt : Arr → Obj) (D : Obj → Type*) where
  /-- The reduced Schrödinger superoperator of each primitive branch. -/
  op : ∀ a, Matrix (D (src a)) (D (src a)) ℂ →ₗ[ℂ] Matrix (D (tgt a)) (D (tgt a)) ℂ

namespace TypedBranches

variable {Obj Arr : Type*} [Fintype Obj] [DecidableEq Obj] {src tgt : Arr → Obj}
  {D : Obj → Type*} [∀ ξ, Fintype (D ξ)] [∀ ξ, DecidableEq (D ξ)]
  (B : TypedBranches Obj Arr src tgt D)

/-- `ρ_X(a) = P_η T_a P_ξ` as an operator on `𝒳`. -/
def branchOp (a : Arr) : Matrix (HSIdx D) (HSIdx D) ℂ :=
  blockIncl D (tgt a) * hsMat (B.op a) * (blockIncl D (src a))ᴴ

/-- Generator images: `a ↦ ρ(a)`, `a♯ ↦ ρ(a)ᴴ` (the Hilbert–Schmidt adjoint), `e_ξ ↦ P_ξ`. -/
def gen : PathLetter Obj Arr → Matrix (HSIdx D) (HSIdx D) ℂ
  | .arrow a => B.branchOp a
  | .reverse a => (B.branchOp a)ᴴ
  | .unit ξ => objProj D ξ

theorem gen_star (x : PathLetter Obj Arr) : B.gen (star x) = star (B.gen x) := by
  rcases x with a | a | ξ
  · rfl
  · change B.branchOp a = ((B.branchOp a)ᴴ)ᴴ
    rw [conjTranspose_conjTranspose]
  · change objProj D ξ = (objProj D ξ)ᴴ
    rw [objProj_conjTranspose]

/-- **The representation `ρ_X : 𝔉_X → B(𝒳)`** of the free path star algebra. -/
noncomputable def rep : FreePathAlg Obj Arr →⋆ₐ[ℂ] Matrix (HSIdx D) (HSIdx D) ℂ :=
  FreeStarAlg.lift B.gen B.gen_star

theorem rep_arrow (a : Arr) : B.rep (FreeStarAlg.ι (.arrow a)) = B.branchOp a :=
  FreeStarAlg.lift_ι _ _ _

theorem rep_reverse (a : Arr) : B.rep (FreeStarAlg.ι (.reverse a)) = (B.branchOp a)ᴴ :=
  FreeStarAlg.lift_ι _ _ _

theorem rep_unit (ξ : Obj) : B.rep (FreeStarAlg.ι (.unit ξ)) = objProj D ξ :=
  FreeStarAlg.lift_ι _ _ _

/-- Typed composition: `P_η ρ(a) P_ξ = ρ(a)` for `a : ξ → η`. -/
theorem objProj_mul_branchOp_mul_objProj (a : Arr) :
    objProj D (tgt a) * B.branchOp a * objProj D (src a) = B.branchOp a := by
  simp only [objProj, branchOp, Matrix.mul_assoc]
  rw [← Matrix.mul_assoc (blockIncl D (tgt a))ᴴ (blockIncl D (tgt a)), blockIncl_isometry,
    Matrix.one_mul, ← Matrix.mul_assoc (blockIncl D (src a))ᴴ (blockIncl D (src a)),
    blockIncl_isometry, Matrix.one_mul]

/-- Non-composable products vanish: if `src b ≠ tgt a` then `ρ(b) ρ(a) = 0`. -/
theorem branchOp_mul_branchOp_of_ne {a b : Arr} (h : src b ≠ tgt a) :
    B.branchOp b * B.branchOp a = 0 := by
  simp only [branchOp, Matrix.mul_assoc]
  rw [← Matrix.mul_assoc (blockIncl D (src b))ᴴ, blockIncl_orth D h, Matrix.zero_mul,
    Matrix.mul_zero, Matrix.mul_zero]

/-- The represented process algebra is the star algebra generated by the primitive branches
and the object units. -/
theorem range_rep :
    B.rep.range = StarAlgebra.adjoin ℂ (Set.range B.branchOp ∪ Set.range (objProj D)) := by
  rw [rep, FreeStarAlg.range_lift]
  apply le_antisymm
  · refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨x, rfl⟩
    rcases x with a | a | ξ
    · exact StarAlgebra.subset_adjoin ℂ _ (Or.inl ⟨a, rfl⟩)
    · exact star_mem (StarAlgebra.subset_adjoin ℂ _ (Or.inl ⟨a, rfl⟩))
    · exact StarAlgebra.subset_adjoin ℂ _ (Or.inr ⟨ξ, rfl⟩)
  · refine StarAlgebra.adjoin_le ?_
    rintro _ (⟨a, rfl⟩ | ⟨ξ, rfl⟩)
    · exact StarAlgebra.subset_adjoin ℂ _ ⟨.arrow a, rfl⟩
    · exact StarAlgebra.subset_adjoin ℂ _ ⟨.unit ξ, rfl⟩

/-- `ρ_X` depends on the branch data only through the reduced superoperators: in particular
not on Kraus coordinates or on the tomographic frame used to reconstruct them. -/
theorem rep_eq_of_op_eq {B' : TypedBranches Obj Arr src tgt D} (h : ∀ a, B.op a = B'.op a) :
    B.rep = B'.rep := by
  have : B = B' := by
    cases B; cases B'
    congr
    funext a
    exact h a
  rw [this]

end TypedBranches

/-! ### The theorem -/

section Main

variable {Obj Arr : Type*} [Fintype Obj] [DecidableEq Obj] {src tgt : Arr → Obj}
  {D : Obj → Type*} [∀ ξ, Fintype (D ξ)] [∀ ξ, DecidableEq (D ξ)]

/-- Conjugation by a rectangular unitary as a star algebra homomorphism. -/
def conjHom {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]
    (W : Matrix n m ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1) :
    Matrix m m ℂ →⋆ₐ[ℂ] Matrix n n ℂ where
  toFun x := W * x * Wᴴ
  map_one' := by simp [hW2]
  map_mul' x y := by
    change W * (x * y) * Wᴴ = W * x * Wᴴ * (W * y * Wᴴ)
    calc W * (x * y) * Wᴴ = W * x * (Wᴴ * W) * y * Wᴴ := by
          rw [hW1, Matrix.mul_one]; simp only [Matrix.mul_assoc]
      _ = W * x * Wᴴ * (W * y * Wᴴ) := by simp only [Matrix.mul_assoc]
  map_zero' := by simp
  map_add' x y := by simp [Matrix.mul_add, Matrix.add_mul]
  commutes' r := by simp [Algebra.algebraMap_eq_smul_one, hW2]
  map_star' x := by
    change W * xᴴ * Wᴴ = (W * x * Wᴴ)ᴴ
    simp [conjTranspose_mul, Matrix.mul_assoc]

theorem conjHom_apply {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]
    (W : Matrix n m ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1) (x : Matrix m m ℂ) :
    conjHom W hW1 hW2 x = W * x * Wᴴ := rfl

/-- **Theorem `thm:ncg-process-history-representation`, representation part.**
`ρ_X` sends the primitive branches to `P_η T_a P_ξ`, the formal reverses to the
Hilbert–Schmidt adjoints and the object units to the block projections; it respects the path
relations (object units are orthogonal projections summing to one, `P_η ρ(a) P_ξ = ρ(a)`,
non-composable products vanish); its kernel is a two-sided star ideal; the represented
process algebra `𝔉_X / Ker ρ_X ≅ C*(ρ_X(a))` (algebra isomorphism intertwining the formal
involution with the Hilbert–Schmidt adjoint) is a finite-dimensional, closed star subalgebra of
`B(𝒳)`. -/
theorem process_history_representation (B : TypedBranches Obj Arr src tgt D) :
    (∀ a, B.rep (FreeStarAlg.ι (.arrow a)) = B.branchOp a) ∧
    (∀ a, B.rep (FreeStarAlg.ι (.reverse a)) = (B.branchOp a)ᴴ) ∧
    (∀ ξ, B.rep (FreeStarAlg.ι (.unit ξ)) = objProj D ξ) ∧
    (∀ a (v w : HSIdx D → ℂ),
      star ((B.branchOp a)ᴴ *ᵥ v) ⬝ᵥ w = star v ⬝ᵥ (B.branchOp a *ᵥ w)) ∧
    (∀ ξ, (objProj D ξ)ᴴ = objProj D ξ ∧ objProj D ξ * objProj D ξ = objProj D ξ) ∧
    (∀ ξ η, ξ ≠ η → objProj D ξ * objProj D η = 0) ∧ ∑ ξ, objProj D ξ = 1 ∧
    (∀ a, objProj D (tgt a) * B.branchOp a * objProj D (src a) = B.branchOp a) ∧
    (∀ a b, src b ≠ tgt a → B.branchOp b * B.branchOp a = 0) ∧
    (∀ f ∈ RingHom.ker B.rep, star f ∈ RingHom.ker B.rep) ∧
    B.rep.range = StarAlgebra.adjoin ℂ (Set.range B.branchOp ∪ Set.range (objProj D)) ∧
    FiniteDimensional ℂ B.rep.range ∧
    IsClosed (B.rep.range : Set (Matrix (HSIdx D) (HSIdx D) ℂ)) ∧
    ∃ e : (FreePathAlg Obj Arr ⧸ RingHom.ker B.rep.toAlgHom) ≃ₐ[ℂ] B.rep.toAlgHom.range,
      (∀ f, (e (Ideal.Quotient.mk _ f) : Matrix (HSIdx D) (HSIdx D) ℂ) = B.rep f) ∧
      ∀ f, (e (Ideal.Quotient.mk _ (star f)) : Matrix (HSIdx D) (HSIdx D) ℂ) =
        star (e (Ideal.Quotient.mk _ f) : Matrix (HSIdx D) (HSIdx D) ℂ) := by
  have he : ∀ f, ((Ideal.quotientKerEquivRange B.rep.toAlgHom) (Ideal.Quotient.mk _ f) :
      Matrix (HSIdx D) (HSIdx D) ℂ) = B.rep f := fun f => rfl
  refine ⟨B.rep_arrow, B.rep_reverse, B.rep_unit, fun a v w => ?_,
    fun ξ => ⟨objProj_conjTranspose D ξ, objProj_mul_self D ξ⟩,
    fun ξ η h => objProj_mul_of_ne D h, sum_objProj D, B.objProj_mul_branchOp_mul_objProj,
    fun a b h => B.branchOp_mul_branchOp_of_ne h, fun f hf => ?_, B.range_rep, ?_, ?_,
    Ideal.quotientKerEquivRange B.rep.toAlgHom, he, fun f => ?_⟩
  · rw [star_mulVec, conjTranspose_conjTranspose, dotProduct_mulVec]
  · rw [RingHom.mem_ker] at hf ⊢
    change B.rep (star f) = 0
    rw [map_star]
    change star (B.rep f) = 0
    rw [show B.rep f = 0 from hf, star_zero]
  · exact FiniteDimensional.of_injective (B.rep.range.subtype.toAlgHom.toLinearMap)
      Subtype.val_injective
  · exact Submodule.closed_of_finiteDimensional
      (Subalgebra.toSubmodule B.rep.range.toSubalgebra)
  · rw [he, he, map_star]

/-- **Realization independence** (`thm:ncg-process-history-representation`, second sentence).
Let a second support-minimal realization have memory spaces `ℂ^{D' ξ}` related to the first by
memory unitaries `U_ξ`, so that its reduced branch maps are the Hilbert–Schmidt conjugates
`T'_a(Y) = U_η T_a(U_ξᴴ Y U_ξ) U_ηᴴ` (`thm:ncg-minimal-comb-dilation`, consequence clause; see
`process_history_kraus_invariance` for the derivation from conjugated Kraus/isometry
coordinates).  Then the Hilbert–Schmidt unitary `𝒰 = ⊕_ξ U_ξ ⊗ Ū_ξ` conjugates the whole word
representation, the kernels agree, and the represented process algebras are star-isomorphic by
a represented isomorphism carrying `ρ_X(f)` to `ρ'_X(f)` for every `f ∈ 𝔉_X`. -/
theorem process_history_unitary_invariance {D' : Obj → Type*} [∀ ξ, Fintype (D' ξ)]
    [∀ ξ, DecidableEq (D' ξ)] (B : TypedBranches Obj Arr src tgt D)
    (B' : TypedBranches Obj Arr src tgt D') (U : ∀ ξ, Matrix (D' ξ) (D ξ) ℂ)
    (hU1 : ∀ ξ, (U ξ)ᴴ * U ξ = 1) (hU2 : ∀ ξ, U ξ * (U ξ)ᴴ = 1)
    (hT : ∀ a Y, B'.op a Y = U (tgt a) * B.op a ((U (src a))ᴴ * Y * U (src a)) * (U (tgt a))ᴴ) :
    ∃ 𝒰 : Matrix (HSIdx D') (HSIdx D) ℂ, 𝒰ᴴ * 𝒰 = 1 ∧ 𝒰 * 𝒰ᴴ = 1 ∧
      (∀ f, B'.rep f = 𝒰 * B.rep f * 𝒰ᴴ) ∧ RingHom.ker B'.rep = RingHom.ker B.rep ∧
      ∃ e : B.rep.range ≃⋆ₐ[ℂ] B'.rep.range,
        ∀ f, (e ⟨B.rep f, f, rfl⟩ : Matrix (HSIdx D') (HSIdx D') ℂ) = B'.rep f := by
  classical
  set V : ∀ ξ, Matrix (D' ξ × D' ξ) (D ξ × D ξ) ℂ := fun ξ => U ξ ⊗ₖ (U ξ).map star with hVdef
  have hV1 : ∀ ξ, (V ξ)ᴴ * V ξ = 1 := fun ξ => kron_map_isometry (hU1 ξ)
  have hV2 : ∀ ξ, V ξ * (V ξ)ᴴ = 1 := by
    intro ξ
    have h := kron_map_isometry (W := (U ξ)ᴴ) (by rw [conjTranspose_conjTranspose, hU2])
    rw [← conjTranspose_kron_map] at h
    simpa [hVdef] using h
  set 𝒰 : Matrix (HSIdx D') (HSIdx D) ℂ :=
    ∑ ξ, blockIncl D' ξ * V ξ * (blockIncl D ξ)ᴴ with h𝒰def
  have h𝒰ι : ∀ ξ, 𝒰 * blockIncl D ξ = blockIncl D' ξ * V ξ := by
    intro ξ
    rw [h𝒰def, Matrix.sum_mul, Finset.sum_eq_single ξ]
    · rw [Matrix.mul_assoc, blockIncl_isometry, Matrix.mul_one]
    · intro η _ hη
      rw [Matrix.mul_assoc, blockIncl_orth D hη, Matrix.mul_zero]
    · simp
  have h𝒰ι' : ∀ ξ, (blockIncl D' ξ)ᴴ * 𝒰 = V ξ * (blockIncl D ξ)ᴴ := by
    intro ξ
    rw [h𝒰def, Matrix.mul_sum, Finset.sum_eq_single ξ]
    · rw [← Matrix.mul_assoc, ← Matrix.mul_assoc, blockIncl_isometry, Matrix.one_mul]
    · intro η _ hη
      rw [← Matrix.mul_assoc, ← Matrix.mul_assoc, blockIncl_orth D' (Ne.symm hη),
        Matrix.zero_mul, Matrix.zero_mul]
    · simp
  have h𝒰star : 𝒰ᴴ = ∑ ξ, blockIncl D ξ * (V ξ)ᴴ * (blockIncl D' ξ)ᴴ := by
    rw [h𝒰def, conjTranspose_sum]
    refine Finset.sum_congr rfl fun ξ _ => ?_
    rw [conjTranspose_mul, conjTranspose_mul, conjTranspose_conjTranspose, Matrix.mul_assoc]
  have hu1 : 𝒰ᴴ * 𝒰 = 1 := by
    rw [h𝒰star, Matrix.sum_mul, ← sum_objProj D]
    refine Finset.sum_congr rfl fun ξ _ => ?_
    rw [Matrix.mul_assoc, h𝒰ι',
      show blockIncl D ξ * (V ξ)ᴴ * (V ξ * (blockIncl D ξ)ᴴ) =
        blockIncl D ξ * ((V ξ)ᴴ * V ξ) * (blockIncl D ξ)ᴴ by simp only [Matrix.mul_assoc],
      hV1, Matrix.mul_one, objProj]
  have hu2 : 𝒰 * 𝒰ᴴ = 1 := by
    rw [h𝒰star, Matrix.mul_sum, ← sum_objProj D']
    refine Finset.sum_congr rfl fun ξ _ => ?_
    rw [← Matrix.mul_assoc, ← Matrix.mul_assoc, h𝒰ι, Matrix.mul_assoc (blockIncl D' ξ),
      hV2, Matrix.mul_one, objProj]
  have hιstar : ∀ ξ, (blockIncl D ξ)ᴴ * 𝒰ᴴ = (V ξ)ᴴ * (blockIncl D' ξ)ᴴ := by
    intro ξ
    have := congrArg conjTranspose (h𝒰ι ξ)
    rwa [conjTranspose_mul, conjTranspose_mul] at this
  -- the conjugation star homomorphism
  let c := conjHom 𝒰 hu1 hu2
  have hgen : ∀ x, B'.gen x = 𝒰 * B.gen x * 𝒰ᴴ := by
    have hbr : ∀ a, B'.branchOp a = 𝒰 * B.branchOp a * 𝒰ᴴ := by
      intro a
      simp only [TypedBranches.branchOp]
      rw [hsMat_conj (B.op a) (B'.op a) (U (src a)) (U (tgt a)) (hT a)]
      calc blockIncl D' (tgt a) * (V (tgt a) * hsMat (B.op a) * (V (src a))ᴴ) *
            (blockIncl D' (src a))ᴴ
          = (blockIncl D' (tgt a) * V (tgt a)) * hsMat (B.op a) *
              ((V (src a))ᴴ * (blockIncl D' (src a))ᴴ) := by simp only [Matrix.mul_assoc]
        _ = (𝒰 * blockIncl D (tgt a)) * hsMat (B.op a) * ((blockIncl D (src a))ᴴ * 𝒰ᴴ) := by
          rw [h𝒰ι, hιstar]
        _ = _ := by simp only [Matrix.mul_assoc]
    rintro (a | a | ξ)
    · exact hbr a
    · change (B'.branchOp a)ᴴ = 𝒰 * (B.branchOp a)ᴴ * 𝒰ᴴ
      rw [hbr, conjTranspose_mul, conjTranspose_mul, conjTranspose_conjTranspose,
        Matrix.mul_assoc]
    · change objProj D' ξ = 𝒰 * objProj D ξ * 𝒰ᴴ
      rw [objProj, objProj, ← Matrix.mul_assoc, h𝒰ι, Matrix.mul_assoc, hιstar,
        ← Matrix.mul_assoc, Matrix.mul_assoc (blockIncl D' ξ) (V ξ), hV2, Matrix.mul_one]
  have hrep : B'.rep = c.comp B.rep := by
    refine FreeStarAlg.starAlgHom_ext fun x => ?_
    rw [StarAlgHom.comp_apply]
    change FreeStarAlg.lift B'.gen B'.gen_star (FreeStarAlg.ι x) =
      c (FreeStarAlg.lift B.gen B.gen_star (FreeStarAlg.ι x))
    rw [FreeStarAlg.lift_ι, FreeStarAlg.lift_ι, conjHom_apply, hgen]
  have hrepf : ∀ f, B'.rep f = 𝒰 * B.rep f * 𝒰ᴴ := fun f => by
    rw [hrep]
    rfl
  have hcinj : Function.Injective c := by
    intro x y hxy
    have h1 : 𝒰ᴴ * (𝒰 * x * 𝒰ᴴ) * 𝒰 = 𝒰ᴴ * (𝒰 * y * 𝒰ᴴ) * 𝒰 := by
      change 𝒰ᴴ * c x * 𝒰 = 𝒰ᴴ * c y * 𝒰
      rw [hxy]
    have hid : ∀ z : Matrix (HSIdx D) (HSIdx D) ℂ, 𝒰ᴴ * (𝒰 * z * 𝒰ᴴ) * 𝒰 = z := fun z => by
      simp only [← Matrix.mul_assoc, hu1, Matrix.one_mul]
      rw [Matrix.mul_assoc, hu1, Matrix.mul_one]
    rwa [hid, hid] at h1
  have hker : RingHom.ker B'.rep = RingHom.ker B.rep := by
    ext f
    rw [RingHom.mem_ker, RingHom.mem_ker]
    change B'.rep f = 0 ↔ B.rep f = 0
    rw [hrep, StarAlgHom.comp_apply]
    constructor
    · intro h
      exact hcinj (by rw [h, map_zero])
    · intro h
      rw [h, map_zero]
  have hmem : ∀ x : B.rep.range, c x ∈ B'.rep.range := by
    rintro ⟨_, f, rfl⟩
    exact ⟨f, by rw [hrep]; rfl⟩
  let φ : B.rep.range →⋆ₐ[ℂ] B'.rep.range := (c.comp B.rep.range.subtype).codRestrict _ hmem
  have hφ : Function.Bijective φ := by
    refine ⟨fun x y hxy => Subtype.val_injective (hcinj (congrArg Subtype.val hxy)), ?_⟩
    rintro ⟨_, f, rfl⟩
    refine ⟨⟨B.rep f, f, rfl⟩, Subtype.val_injective ?_⟩
    change c (B.rep f) = B'.rep f
    rw [hrep]
    rfl
  refine ⟨𝒰, hu1, hu2, hrepf, hker, StarAlgEquiv.ofBijective φ hφ, fun f => ?_⟩
  change c (B.rep f) = B'.rep f
  rw [hrep]
  rfl

/-- **Kraus/purification coordinates and memory unitaries.**  If the reduced branch maps of two
realizations have Kraus operators related by the memory unitaries,
`K'_{a,ν} = U_η K_{a,ν} U_ξᴴ` (as produced by the sequential covariance
`V'_k = (I ⊗ U_k) V_k (I ⊗ U_{k-1}^*)` of `thm:ncg-minimal-comb-dilation` after contracting the
fixed external interventions), then the reduced maps are Hilbert–Schmidt conjugate and the
represented process algebras are star-isomorphic by a represented isomorphism. -/
theorem process_history_kraus_invariance {D' : Obj → Type*} [∀ ξ, Fintype (D' ξ)]
    [∀ ξ, DecidableEq (D' ξ)] {κ : Arr → Type*} [∀ a, Fintype (κ a)]
    (K : ∀ a, κ a → Matrix (D (tgt a)) (D (src a)) ℂ) (B : TypedBranches Obj Arr src tgt D)
    (B' : TypedBranches Obj Arr src tgt D') (U : ∀ ξ, Matrix (D' ξ) (D ξ) ℂ)
    (hU1 : ∀ ξ, (U ξ)ᴴ * U ξ = 1) (hU2 : ∀ ξ, U ξ * (U ξ)ᴴ = 1)
    (hB : ∀ a, B.op a = MatrixKraus.krausMap (K a))
    (hB' : ∀ a, B'.op a = MatrixKraus.krausMap fun ν => U (tgt a) * K a ν * (U (src a))ᴴ) :
    ∃ 𝒰 : Matrix (HSIdx D') (HSIdx D) ℂ, 𝒰ᴴ * 𝒰 = 1 ∧ 𝒰 * 𝒰ᴴ = 1 ∧
      (∀ f, B'.rep f = 𝒰 * B.rep f * 𝒰ᴴ) ∧ RingHom.ker B'.rep = RingHom.ker B.rep ∧
      ∃ e : B.rep.range ≃⋆ₐ[ℂ] B'.rep.range,
        ∀ f, (e ⟨B.rep f, f, rfl⟩ : Matrix (HSIdx D') (HSIdx D') ℂ) = B'.rep f :=
  process_history_unitary_invariance B B' U hU1 hU2 fun a Y => by
    rw [hB', krausMap_conj_eq, hB]

end Main

/-- Non-vacuity witness for `process_history_unitary_invariance`: the identity memory
unitaries relate any branch data to itself. -/
example {Obj Arr : Type} [Fintype Obj] [DecidableEq Obj] {src tgt : Arr → Obj}
    {D : Obj → Type} [∀ ξ, Fintype (D ξ)] [∀ ξ, DecidableEq (D ξ)]
    (B : TypedBranches Obj Arr src tgt D) :
    ∃ 𝒰 : Matrix (HSIdx D) (HSIdx D) ℂ, 𝒰ᴴ * 𝒰 = 1 ∧ 𝒰 * 𝒰ᴴ = 1 ∧
      (∀ f, B.rep f = 𝒰 * B.rep f * 𝒰ᴴ) ∧ RingHom.ker B.rep = RingHom.ker B.rep ∧
      ∃ e : B.rep.range ≃⋆ₐ[ℂ] B.rep.range,
        ∀ f, (e ⟨B.rep f, f, rfl⟩ : Matrix (HSIdx D) (HSIdx D) ℂ) = B.rep f :=
  process_history_unitary_invariance B B (fun _ => 1) (fun _ => by simp) (fun _ => by simp)
    fun a Y => by simp

end ProcessHistory

end RenewalGeometry
