-- Root module of the NCG library: generic noncommutative geometry.
import NCG.Algebra.CPMap
import NCG.Algebra.CanonicalReductions
import NCG.Algebra.CircleSelection
import NCG.Algebra.CliffordConcrete
import NCG.Algebra.CliffordGenerates
import NCG.Algebra.ExternalFactor
import NCG.Algebra.FactorBlocks
import NCG.Algebra.InternalComplement
import NCG.Algebra.JordanWigner
import NCG.Algebra.LuedersInstrument
import NCG.Algebra.MarkedFactor
import NCG.Algebra.PauliJordan
import NCG.Algebra.PhaseVelocity
import NCG.Algebra.ProjectiveDefect
import NCG.Algebra.RadicalCentre
import NCG.Algebra.RealizedReversible
import NCG.Algebra.RebitCounterexample
import NCG.Algebra.RevisionCocycle
import NCG.Algebra.RevisionDerived
import NCG.Algebra.RevisionTwirl
import NCG.Algebra.SkolemNoether
import NCG.Algebra.SpinFactor
import NCG.Algebra.Symplectic
import NCG.Algebra.UnitalStationary
import NCG.Basic
import NCG.Graph.BettiNumber
import NCG.Graph.Cohomology
import NCG.Graph.CohomologyZ4
import NCG.Graph.Condensation
import NCG.Graph.Decimation
import NCG.Graph.Displacement
import NCG.Graph.Multigraph
import NCG.Graph.RecordOrientation
import NCG.Graph.SignCocycle
import NCG.Graph.SignedCover
import NCG.Krein.AmplitudeLift
import NCG.Krein.CoverModel
import NCG.Krein.EnrichmentClassification
import NCG.Krein.EnrichmentNaturality
import NCG.Krein.FlatSector
import NCG.Krein.FundamentalSymmetry
import NCG.Krein.InternalHolonomy
import NCG.Krein.IrreducibleNoGo
import NCG.Krein.ModularDirac
import NCG.Krein.SheetRealization
import NCG.Krein.SignedData
import NCG.Krein.SignedDirac
import NCG.Krein.TemporalRow
import NCG.Krein.TimelikeGenerator
import NCG.Operator.Diagonal
import NCG.Operator.DiagonalRigidity
import NCG.Operator.FibreDichotomy
import NCG.PerronFrobenius.PerronExistence
import NCG.PerronFrobenius.PerronPressure
import NCG.SpectralTriple.Basic
