/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import RenewalGeometry.Algebra.GhostSuperalgebra
import RenewalGeometry.Gravity.FiniteActionWardBRSTStressEinsteinExact
/-!
# The ghost-field BRST identity of the finite action (`thm:finite-action-identities`)

The BRST clause of `thm:finite-action-identities` (spacetime–gauge duality paper): the
standard ghost extension

`s c = −c²`, `s U_e = c_{t(e)} U_e − U_e c_{s(e)}`, `s H_v = c_v H_v`, `s Ψ_v = c_v Ψ_v`,
`s c̄ = B`, `s B = 0`

is nilpotent and satisfies `s² = 0`, `s 𝒮 = 0` (`eq:brst`).

## Setting

The fields and ghosts live in a superalgebra `(A, ε)` (`ParityStructure`) — the algebra of
field polynomials tensored with the Grassmann algebra of the ghosts — on which the BRST
operator `s` is an odd superderivation (`SuperDerivation`, right-acting graded Leibniz rule
`s (ab) = a (s b) + (s a) ε(b)`, the convention under which the displayed rules are consistent).
The lattice has vertices `V`, edges `E` with source/target `src, tgt : E → V`, a colour index
`n`; the link variables `U_e`, Higgs fields `H_v`, matter amplitudes `Ψ_v` and their independent
dual amplitudes `Ψ̄_v` are matrices over `A` with even entries; the ghosts `c_v`, antighosts
`c̄_v` are odd, the auxiliary fields `B_v` even (`FiniteGhostBRST`).  The dual amplitude
transforms contragrediently, `s Ψ̄_v = −Ψ̄_v c_v`.

## Results

* `FiniteGhostBRST.square_zero_fields`: `s² = 0` on every field and ghost matrix.
* `FiniteGhostBRST.brst_nilpotent`: **`s² = 0`** on the whole field–ghost algebra (the unital
  subalgebra generated by all field, ghost, antighost and auxiliary entries).
* `FiniteGhostBRST.brst_action_closed`: **`s 𝒮 = 0`** for every element `𝒮` of the field
  algebra that is infinitesimally gauge invariant.  Here the ghost is expanded in a basis
  `T_a` of the gauge Lie algebra, `c_v = ∑_a c_v^a T_a` with odd Grassmann scalars `c_v^a`
  commuting with the field entries, and the infinitesimal gauge variations `δ_{v,a}` are the
  derivations of the field algebra with `δ_{v,a} U_e = [v = t(e)] T_a U_e − [v = s(e)] U_e T_a`,
  `δ_{v,a} H_w = [v = w] T_a H_w`, `δ_{v,a} Ψ_w = [v = w] T_a Ψ_w`,
  `δ_{v,a} Ψ̄_w = −[v = w] Ψ̄_w T_a`; the BRST operator restricted to the field algebra is
  `s = ∑_{v,a} c_v^a δ_{v,a}` (`brst_eq_ghost_sum_on_fields`), so gauge invariance
  `δ_{v,a} 𝒮 = 0` (the infinitesimal form of the exact gauge invariance of the action, i.e. the
  Ward identity `gauge_ward_divergence`) gives `s 𝒮 = 0`.
* `finite_action_brst`: the two BRST clauses of `eq:brst` together.

Disclosed: the ambient superalgebra and the odd superderivation `s` are taken as the
structure in which the displayed rules are imposed (the free supercommutative extension is
not constructed); matter amplitudes are treated as even (commuting) variables, as in the
finite action `eq:finite-SM-action` with its independent dual amplitude; `s 𝒮 = 0` is derived
from the infinitesimal gauge invariance of `𝒮`, the differentiated form of the exact gauge
invariance established for the four-term action
(`explicitRegulatedStandardModelAction_gaugeInvariant`).  The library's finite group-cochain
differential (`finiteBRST0/1/2`) is a different object and is not the ghost operator `s`.
-/

open Matrix

namespace RenewalGeometry

/-- The entries of a matrix over `A`, as a set. -/
def matrixEntries {A : Type*} {m n : Type*} (M : Matrix m n A) : Set A :=
  Set.range fun ij : m × n => M ij.1 ij.2

theorem mem_matrixEntries {A : Type*} {m n : Type*} (M : Matrix m n A) (i : m) (j : n) :
    M i j ∈ matrixEntries M := ⟨(i, j), rfl⟩

theorem matrixEntries_subset_of_map_eq_zero {A : Type*} [Ring A] [Algebra ℂ A]
    {P : ParityStructure A} (s : SuperDerivation P) {m n : Type*} {M : Matrix m n A}
    (h : s.matrix (s.matrix M) = 0) : ∀ x ∈ matrixEntries M, s (s x) = 0 := by
  rintro x ⟨⟨i, j⟩, rfl⟩
  have := congrFun (congrFun h i) j
  simpa [SuperDerivation.matrix_apply] using this

theorem isEven_of_mem_matrixEntries {A : Type*} [Ring A] [Algebra ℂ A]
    (P : ParityStructure A) {m n : Type*} {M : Matrix m n A} (h : P.matrix M = M) :
    ∀ x ∈ matrixEntries M, P.IsEven x := by
  rintro x ⟨⟨i, j⟩, rfl⟩
  have := congrFun (congrFun h i) j
  simpa [ParityStructure.matrix, ParityStructure.IsEven] using this

/-- **The ghost extension of `thm:finite-action-identities`**: parities of the fields and
ghosts and the displayed BRST rules, imposed in a superalgebra `(A, ε)` with odd
superderivation `s`. -/
structure FiniteGhostBRST {A : Type*} [Ring A] [Algebra ℂ A] {P : ParityStructure A}
    (s : SuperDerivation P) {V E n p q : Type*} [Fintype n] (src tgt : E → V)
    (c : V → Matrix n n A) (U : E → Matrix n n A) (H : V → Matrix n p A)
    (Ψ : V → Matrix n q A) (Ψb : V → Matrix q n A) (cb B : V → Matrix n n A) : Prop where
  /-- ghosts are odd -/
  ghost_odd : ∀ v, P.matrix (c v) = -(c v)
  /-- link variables are even -/
  link_even : ∀ e, P.matrix (U e) = U e
  /-- Higgs fields are even -/
  higgs_even : ∀ v, P.matrix (H v) = H v
  /-- matter amplitudes are even -/
  matter_even : ∀ v, P.matrix (Ψ v) = Ψ v
  /-- dual amplitudes are even -/
  dual_even : ∀ v, P.matrix (Ψb v) = Ψb v
  /-- `s c = −c²` -/
  s_ghost : ∀ v, s.matrix (c v) = -(c v * c v)
  /-- `s U_e = c_{t(e)} U_e − U_e c_{s(e)}` -/
  s_link : ∀ e, s.matrix (U e) = c (tgt e) * U e - U e * c (src e)
  /-- `s H_v = c_v H_v` -/
  s_higgs : ∀ v, s.matrix (H v) = c v * H v
  /-- `s Ψ_v = c_v Ψ_v` -/
  s_matter : ∀ v, s.matrix (Ψ v) = c v * Ψ v
  /-- `s Ψ̄_v = −Ψ̄_v c_v` (contragredient dual amplitude) -/
  s_dual : ∀ v, s.matrix (Ψb v) = -(Ψb v * c v)
  /-- `s c̄ = B` -/
  s_antighost : ∀ v, s.matrix (cb v) = B v
  /-- `s B = 0` -/
  s_aux : ∀ v, s.matrix (B v) = 0

namespace FiniteGhostBRST

variable {A : Type*} [Ring A] [Algebra ℂ A] {P : ParityStructure A} {s : SuperDerivation P}
  {V E n p q : Type*} [Fintype n] [DecidableEq n] {src tgt : E → V}
  {c : V → Matrix n n A} {U : E → Matrix n n A} {H : V → Matrix n p A}
  {Ψ : V → Matrix n q A} {Ψb : V → Matrix q n A} {cb B : V → Matrix n n A}

/-- The field generators: all entries of `U_e, H_v, Ψ_v, Ψ̄_v`. -/
def fieldGenerators (U : E → Matrix n n A) (H : V → Matrix n p A) (Ψ : V → Matrix n q A)
    (Ψb : V → Matrix q n A) : Set A :=
  (⋃ e, matrixEntries (U e)) ∪ (⋃ v, matrixEntries (H v)) ∪ (⋃ v, matrixEntries (Ψ v))
    ∪ (⋃ v, matrixEntries (Ψb v))

/-- The field–ghost generators: the field entries together with all entries of the ghosts,
antighosts and auxiliary fields. -/
def fieldGhostGenerators (c : V → Matrix n n A) (U : E → Matrix n n A) (H : V → Matrix n p A)
    (Ψ : V → Matrix n q A) (Ψb : V → Matrix q n A) (cb B : V → Matrix n n A) : Set A :=
  fieldGenerators U H Ψ Ψb ∪ (⋃ v, matrixEntries (c v)) ∪ (⋃ v, matrixEntries (cb v))
    ∪ (⋃ v, matrixEntries (B v))

/-- `s² = 0` on every field and ghost matrix. -/
theorem square_zero_fields (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B) :
    (∀ v, s.matrix (s.matrix (c v)) = 0) ∧ (∀ e, s.matrix (s.matrix (U e)) = 0)
      ∧ (∀ v, s.matrix (s.matrix (H v)) = 0) ∧ (∀ v, s.matrix (s.matrix (Ψ v)) = 0)
      ∧ (∀ v, s.matrix (s.matrix (Ψb v)) = 0) ∧ (∀ v, s.matrix (s.matrix (cb v)) = 0)
      ∧ (∀ v, s.matrix (s.matrix (B v)) = 0) :=
  ⟨fun v => s.ghost_square_zero (R.ghost_odd v) (R.s_ghost v),
    fun e => s.link_square_zero (R.ghost_odd (tgt e)) (R.ghost_odd (src e)) (R.link_even e)
      (R.s_ghost (tgt e)) (R.s_ghost (src e)) (R.s_link e),
    fun v => s.matter_square_zero (R.higgs_even v) (R.s_ghost v) (R.s_higgs v),
    fun v => s.matter_square_zero (R.matter_even v) (R.s_ghost v) (R.s_matter v),
    fun v => s.dual_matter_square_zero (R.ghost_odd v) (R.s_ghost v) (R.s_dual v),
    fun v => (s.antighost_square_zero (R.s_antighost v) (R.s_aux v)).1,
    fun v => (s.antighost_square_zero (R.s_antighost v) (R.s_aux v)).2⟩

/-- **`s² = 0` (`eq:brst`, nilpotency)** on the whole field–ghost algebra. -/
theorem brst_nilpotent (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B) :
    ∀ x ∈ Algebra.adjoin ℂ (fieldGhostGenerators c U H Ψ Ψb cb B), s (s x) = 0 := by
  obtain ⟨hc, hU, hH, hΨ, hΨb, hcb, hB⟩ := R.square_zero_fields
  refine s.square_eq_zero_on_adjoin fun x hx => ?_
  simp only [fieldGhostGenerators, fieldGenerators, Set.mem_union, Set.mem_iUnion] at hx
  rcases hx with (((((⟨e, he⟩ | ⟨v, hv⟩) | ⟨v, hv⟩) | ⟨v, hv⟩) | ⟨v, hv⟩) | ⟨v, hv⟩) | ⟨v, hv⟩
  · exact matrixEntries_subset_of_map_eq_zero s (hU e) x he
  · exact matrixEntries_subset_of_map_eq_zero s (hH v) x hv
  · exact matrixEntries_subset_of_map_eq_zero s (hΨ v) x hv
  · exact matrixEntries_subset_of_map_eq_zero s (hΨb v) x hv
  · exact matrixEntries_subset_of_map_eq_zero s (hc v) x hv
  · exact matrixEntries_subset_of_map_eq_zero s (hcb v) x hv
  · exact matrixEntries_subset_of_map_eq_zero s (hB v) x hv

/-- The field generators are even. -/
theorem fieldGenerators_even (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B) :
    ∀ x ∈ fieldGenerators U H Ψ Ψb, P.IsEven x := by
  intro x hx
  simp only [fieldGenerators, Set.mem_union, Set.mem_iUnion] at hx
  rcases hx with ((⟨e, he⟩ | ⟨v, hv⟩) | ⟨v, hv⟩) | ⟨v, hv⟩
  · exact isEven_of_mem_matrixEntries P (R.link_even e) x he
  · exact isEven_of_mem_matrixEntries P (R.higgs_even v) x hv
  · exact isEven_of_mem_matrixEntries P (R.matter_even v) x hv
  · exact isEven_of_mem_matrixEntries P (R.dual_even v) x hv

/-! ### The ghost expansion `c_v = ∑_a c_v^a T_a` and the gauge derivations -/

section Expansion

variable [Fintype V] [DecidableEq V] {d : ℕ}

/-- A complex Lie-algebra generator `T_a` read inside the superalgebra. -/
def liftGen (T : Fin d → Matrix n n ℂ) (a : Fin d) : Matrix n n A :=
  (T a).map (algebraMap ℂ A)

/-- Entry of a left ghost product: `((∑_a c^a T_a) M)_{ij} = ∑_a c^a (T_a M)_{ij}`. -/
theorem entry_ghost_mul_left {m : Type*} (cs : Fin d → A) (Tm : Fin d → Matrix n n A)
    (M : Matrix n m A) (i : n) (j : m) :
    ((∑ a, cs a • Tm a) * M) i j = ∑ a, cs a * (Tm a * M) i j := by
  simp [Matrix.sum_mul, Matrix.smul_mul, Matrix.sum_apply, Matrix.smul_apply]

/-- Entry of a right ghost product, when the entries of `M` commute with the ghost scalars:
`(M (∑_a c^a T_a))_{ij} = ∑_a c^a (M T_a)_{ij}`. -/
theorem entry_ghost_mul_right {m : Type*} (cs : Fin d → A) (Tm : Fin d → Matrix n n A)
    (M : Matrix m n A) (i : m) (j : n) (hcomm : ∀ k a, M i k * cs a = cs a * M i k) :
    (M * ∑ a, cs a • Tm a) i j = ∑ a, cs a * (M * Tm a) i j := by
  simp only [Matrix.mul_apply, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul, Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun a _ => Finset.sum_congr rfl fun k _ => ?_
  rw [← mul_assoc, hcomm, mul_assoc]

/-- A double sum over a vertex indicator collapses to the indicated vertex. -/
theorem sum_sum_ite_eq (v₀ : V) (f : V → Fin d → A) :
    ∑ v, ∑ a, (if v = v₀ then f v a else 0) = ∑ a, f v₀ a := by
  rw [Finset.sum_comm]
  simp [Finset.sum_ite_eq']

/-- **The BRST operator on the field algebra is the ghost-weighted sum of the gauge
derivations.**  With `c_v = ∑_a c_v^a T_a` (odd scalars `c_v^a` commuting with the field
entries) and `δ_{v,a}` the infinitesimal gauge variations, `s x = ∑_{v,a} c_v^a δ_{v,a} x` for
every field generator `x`. -/
theorem brst_eq_ghost_sum_on_fields (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B)
    (T : Fin d → Matrix n n ℂ) (cs : V → Fin d → A)
    (hc : ∀ v, c v = ∑ a, cs v a • liftGen (A := A) T a)
    (δ : V × Fin d → A →ₗ[ℂ] A)
    (hδU : ∀ v a e i j, δ (v, a) (U e i j) =
      (if v = tgt e then (liftGen (A := A) T a * U e) i j else 0)
        - (if v = src e then (U e * liftGen (A := A) T a) i j else 0))
    (hδH : ∀ v a w i j, δ (v, a) (H w i j) = if v = w then (liftGen (A := A) T a * H w) i j else 0)
    (hδΨ : ∀ v a w i j, δ (v, a) (Ψ w i j) = if v = w then (liftGen (A := A) T a * Ψ w) i j else 0)
    (hδΨb : ∀ v a w i j, δ (v, a) (Ψb w i j) = if v = w then -(Ψb w * liftGen (A := A) T a) i j else 0)
    (hcomm : ∀ x ∈ fieldGenerators U H Ψ Ψb, ∀ v a, x * cs v a = cs v a * x) :
    ∀ x ∈ fieldGenerators U H Ψ Ψb, s x = ∑ p : V × Fin d, cs p.1 p.2 * δ p x := by
  intro x hx
  have hx' := hx
  simp only [fieldGenerators, Set.mem_union, Set.mem_iUnion] at hx
  rcases hx with ((⟨e, ⟨⟨i, j⟩, rfl⟩⟩ | ⟨w, ⟨⟨i, j⟩, rfl⟩⟩) | ⟨w, ⟨⟨i, j⟩, rfl⟩⟩)
    | ⟨w, ⟨⟨i, j⟩, rfl⟩⟩
  · -- link variables
    have h1 : s (U e i j) = (c (tgt e) * U e) i j - (U e * c (src e)) i j := by
      rw [← Matrix.sub_apply, ← SuperDerivation.matrix_apply, R.s_link e]
    have hcommU : ∀ k a, U e i k * cs (src e) a = cs (src e) a * U e i k := fun k a =>
      hcomm _ (by
        simp only [fieldGenerators, Set.mem_union, Set.mem_iUnion]
        exact Or.inl (Or.inl (Or.inl ⟨e, mem_matrixEntries _ i k⟩))) _ _
    rw [h1, hc (tgt e), hc (src e), entry_ghost_mul_left, entry_ghost_mul_right _ _ _ _ _ hcommU,
      Fintype.sum_prod_type]
    simp only [hδU, mul_sub, mul_ite, mul_zero, Finset.sum_sub_distrib, sum_sum_ite_eq]
  · -- Higgs fields
    have h1 : s (H w i j) = (c w * H w) i j := by
      rw [← SuperDerivation.matrix_apply, R.s_higgs w]
    rw [h1, hc w, entry_ghost_mul_left, Fintype.sum_prod_type]
    simp only [hδH, mul_ite, mul_zero, sum_sum_ite_eq]
  · -- matter amplitudes
    have h1 : s (Ψ w i j) = (c w * Ψ w) i j := by
      rw [← SuperDerivation.matrix_apply, R.s_matter w]
    rw [h1, hc w, entry_ghost_mul_left, Fintype.sum_prod_type]
    simp only [hδΨ, mul_ite, mul_zero, sum_sum_ite_eq]
  · -- dual amplitudes
    have h1 : s (Ψb w i j) = -(Ψb w * c w) i j := by
      rw [← Matrix.neg_apply, ← SuperDerivation.matrix_apply, R.s_dual w]
    have hcommΨb : ∀ k a, Ψb w i k * cs w a = cs w a * Ψb w i k := fun k a =>
      hcomm _ (by
        simp only [fieldGenerators, Set.mem_union, Set.mem_iUnion]
        exact Or.inr ⟨w, mem_matrixEntries _ i k⟩) _ _
    rw [h1, hc w, entry_ghost_mul_right _ _ _ _ _ hcommΨb, Fintype.sum_prod_type,
      ← Finset.sum_neg_distrib]
    simp only [hδΨb, mul_ite, mul_zero, mul_neg, sum_sum_ite_eq]

/-- **`s 𝒮 = 0` (`eq:brst`, closure of the action).**  Every element `𝒮` of the field algebra
that is infinitesimally gauge invariant (`δ_{v,a} 𝒮 = 0` for all vertices `v` and Lie-algebra
directions `a`) is BRST closed. -/
theorem brst_action_closed (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B)
    (T : Fin d → Matrix n n ℂ) (cs : V → Fin d → A)
    (hc : ∀ v, c v = ∑ a, cs v a • liftGen (A := A) T a)
    (δ : V × Fin d → A →ₗ[ℂ] A)
    (hδ : ∀ p x y, δ p (x * y) = x * δ p y + δ p x * y)
    (hδU : ∀ v a e i j, δ (v, a) (U e i j) =
      (if v = tgt e then (liftGen (A := A) T a * U e) i j else 0)
        - (if v = src e then (U e * liftGen (A := A) T a) i j else 0))
    (hδH : ∀ v a w i j, δ (v, a) (H w i j) = if v = w then (liftGen (A := A) T a * H w) i j else 0)
    (hδΨ : ∀ v a w i j, δ (v, a) (Ψ w i j) = if v = w then (liftGen (A := A) T a * Ψ w) i j else 0)
    (hδΨb : ∀ v a w i j, δ (v, a) (Ψb w i j) = if v = w then -(Ψb w * liftGen (A := A) T a) i j else 0)
    (hcomm : ∀ x ∈ fieldGenerators U H Ψ Ψb, ∀ v a, x * cs v a = cs v a * x)
    {S : A} (hS : S ∈ Algebra.adjoin ℂ (fieldGenerators U H Ψ Ψb))
    (hinv : ∀ p, δ p S = 0) : s S = 0 :=
  s.apply_eq_zero_of_derivations_eq_zero (R.fieldGenerators_even)
    (fun p : V × Fin d => cs p.1 p.2) δ hδ (fun x hx p => hcomm x hx p.1 p.2)
    (R.brst_eq_ghost_sum_on_fields T cs hc δ hδU hδH hδΨ hδΨb hcomm) hS hinv

end Expansion

end FiniteGhostBRST

/-- **BRST clause of `thm:finite-action-identities` (`eq:brst`).**  For the standard ghost
extension `s c = −c²`, `s U = c_t U − U c_s`, `s H = c H`, `s Ψ = c Ψ`, `s c̄ = B`, `s B = 0`
imposed in a superalgebra with odd superderivation `s`: `s² = 0` on the field–ghost algebra,
and `s 𝒮 = 0` for every infinitesimally gauge-invariant element `𝒮` of the field algebra
(the ghost expanded as `c_v = ∑_a c_v^a T_a`, the gauge derivations `δ_{v,a}` as in
`FiniteGhostBRST.brst_action_closed`). -/
theorem finite_action_brst {A : Type*} [Ring A] [Algebra ℂ A] {P : ParityStructure A}
    (s : SuperDerivation P) {V E n p q : Type*} [Fintype V] [DecidableEq V] [Fintype n]
    [DecidableEq n] (src tgt : E → V)
    (c : V → Matrix n n A) (U : E → Matrix n n A) (H : V → Matrix n p A)
    (Ψ : V → Matrix n q A) (Ψb : V → Matrix q n A) (cb B : V → Matrix n n A)
    (R : FiniteGhostBRST s src tgt c U H Ψ Ψb cb B) {d : ℕ}
    (T : Fin d → Matrix n n ℂ) (cs : V → Fin d → A)
    (hc : ∀ v, c v = ∑ a, cs v a • FiniteGhostBRST.liftGen (A := A) T a)
    (δ : V × Fin d → A →ₗ[ℂ] A)
    (hδ : ∀ p x y, δ p (x * y) = x * δ p y + δ p x * y)
    (hδU : ∀ v a e i j, δ (v, a) (U e i j) =
      (if v = tgt e then (FiniteGhostBRST.liftGen (A := A) T a * U e) i j else 0)
        - (if v = src e then (U e * FiniteGhostBRST.liftGen (A := A) T a) i j else 0))
    (hδH : ∀ v a w i j, δ (v, a) (H w i j) =
      if v = w then (FiniteGhostBRST.liftGen (A := A) T a * H w) i j else 0)
    (hδΨ : ∀ v a w i j, δ (v, a) (Ψ w i j) =
      if v = w then (FiniteGhostBRST.liftGen (A := A) T a * Ψ w) i j else 0)
    (hδΨb : ∀ v a w i j, δ (v, a) (Ψb w i j) =
      if v = w then -(Ψb w * FiniteGhostBRST.liftGen (A := A) T a) i j else 0)
    (hcomm : ∀ x ∈ FiniteGhostBRST.fieldGenerators U H Ψ Ψb, ∀ v a,
      x * cs v a = cs v a * x) :
    (∀ x ∈ Algebra.adjoin ℂ (FiniteGhostBRST.fieldGhostGenerators c U H Ψ Ψb cb B),
        s (s x) = 0)
    ∧ ∀ S ∈ Algebra.adjoin ℂ (FiniteGhostBRST.fieldGenerators U H Ψ Ψb),
        (∀ p, δ p S = 0) → s S = 0 :=
  ⟨R.brst_nilpotent, fun S hS hinv =>
    R.brst_action_closed T cs hc δ hδ hδU hδH hδΨ hδΨb hcomm hS hinv⟩

end RenewalGeometry
