/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Operational.RankOneForcing
import RenewalGeometry.Operational.CompressionDefectDilation
import RenewalGeometry.Predictive.ContextualFutureNullIdeal
import RenewalGeometry.Predictive.FiniteGrandTensorExact
import RenewalGeometry.Commutant.ReciprocalWedderburnKronecker
import RenewalGeometry.Spectralization.MarkedCommutantCoordinates
/-!
# Finite operational realization and recognition with multiplicities

Paper `predictive_spectral_geometry`, labels `thm:ncg-operational-realization`,
`prop:ncg-operational-recognition` and `cor:ncg-operational-calibrated-triples`.

## Hilbert–Schmidt matrices of superoperators

A superoperator `Φ : M_Ω(ℂ) → M_Ω(ℂ)` is encoded by its matrix in the Hilbert–Schmidt
orthonormal basis of matrix units, `superMatrix Φ : Matrix (Ω × Ω) (Ω × Ω) ℂ`; `superApply M`
is the superoperator of a matrix `M`.  Composition is matrix multiplication
(`superApply_mul`), and the Hilbert–Schmidt adjoint is the conjugate transpose
(`hsInner_superApply`, `superMatrix_eq_conjTranspose_of_hsAdjoint`).

## Finite operational schemes

`Scheme Ω ι Br` is a finite physical memory `ℂ^Ω` with boundary preparations `prep : ι → M_Ω`,
terminal readouts (effects) `eff : ι → M_Ω` and a finite family `Br` of two-outcome
instruments `(succ β, fail β)`.  `Scheme.IsValid`: densities, effects, completely positive
branches (finite Kraus form, `IsKrausCP`) and normalized instruments
(`Tr(succ β X + fail β X) = Tr X`).

* `Scheme.processAlgebra`: the internal history algebra, the star subalgebra of
  `B(HS(ℂ^Ω))` generated by the Hilbert–Schmidt matrices of all branches (star = HS adjoint).
* `Scheme.readout i j x = Tr(E_i x(ρ_j))`: the boundary readout contexts;
  `Scheme.futureNull`: the contextual future-null ideal of these readouts
  (`contextualFutureNullIdeal`, both `q` and `q^*` tested in every two-sided context).
* `Scheme.sourceSpan = span{ρ_j}`: the diagonal Hilbert–Schmidt source subspace.
* `Scheme.RealizesRep S π`: **the future-separated source representation of `S` is unitarily
  equivalent to `π`**: there are a surjective star homomorphism `θ : A^proc → A` whose kernel is
  exactly the contextual future-null ideal (so `A^proc / N^fut ≅ A`) and a Hilbert–Schmidt
  unitary `T : ℂ^n ≅ span{ρ_j}` with `x(T v) = T(π(θ x) v)` for every internal history `x`.

## Main results

* `realizesRep_of_frame`: the general compression mechanism (preparations forming a
  Hilbert–Schmidt orthonormal frame, perfectly discriminated, every branch and its
  Hilbert–Schmidt adjoint acting on the frame by given matrices `A_γ`, and the algebra
  generated by the `A_γ` unitarily equivalent to `π(A)`).
* `exists_wedderburn_blockForm`: the Wedderburn block form `Wᴴ π(A) W = ⊕_λ M_{n_λ} ⊗ I_{m_λ}`
  of a faithful representation (from `reciprocal_wedderburn`).
* `realizationScheme`: the explicit realization (rank-one Kraus matrix-unit branches
  `realizationScheme_succ_eq_kraus`, dephasing failure branches `realizationScheme_fail_eq`).
* `operational_realization` (`thm:ncg-operational-realization`).
* `frame_data_of_card_eq`, `card_le_of_perfectDiscrimination`, `Scheme.SamePanel`,
  `operational_recognition` (`prop:ncg-operational-recognition`).
* `operational_calibrated_triples` (`cor:ncg-operational-calibrated-triples`).
-/

namespace RenewalGeometry
namespace OperationalRealization

open Matrix MatrixKraus
open scoped ComplexOrder Kronecker

set_option linter.unusedSectionVars false

/-! ### Hilbert–Schmidt matrices of superoperators -/

section HS

variable {Ω : Type*} [Fintype Ω] [DecidableEq Ω]

/-- Vectorisation `X ↦ (X_{ij})_{(i,j)}` of a memory operator. -/
def vecHS (X : Matrix Ω Ω ℂ) : Ω × Ω → ℂ := fun p => X p.1 p.2

/-- Inverse of the vectorisation. -/
def unvecHS (v : Ω × Ω → ℂ) : Matrix Ω Ω ℂ := Matrix.of fun i j => v (i, j)

@[simp] theorem vecHS_unvecHS (v : Ω × Ω → ℂ) : vecHS (unvecHS v) = v := rfl

@[simp] theorem unvecHS_vecHS (X : Matrix Ω Ω ℂ) : unvecHS (vecHS X) = X := rfl

theorem vecHS_add (X Y : Matrix Ω Ω ℂ) : vecHS (X + Y) = vecHS X + vecHS Y := rfl

theorem vecHS_smul (c : ℂ) (X : Matrix Ω Ω ℂ) : vecHS (c • X) = c • vecHS X := rfl

/-- The Hilbert–Schmidt matrix of a superoperator in the basis of matrix units. -/
def superMatrix (Φ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) : Matrix (Ω × Ω) (Ω × Ω) ℂ :=
  Matrix.of fun p q => Φ (Matrix.single q.1 q.2 1) p.1 p.2

/-- The superoperator of a Hilbert–Schmidt matrix. -/
def superApply (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X : Matrix Ω Ω ℂ) : Matrix Ω Ω ℂ :=
  unvecHS (M *ᵥ vecHS X)

theorem vecHS_superApply (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X : Matrix Ω Ω ℂ) :
    vecHS (superApply M X) = M *ᵥ vecHS X := rfl

/-- `superApply M` as a linear map. -/
def superLin (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ where
  toFun := superApply M
  map_add' X Y := by
    ext i j
    simp [superApply, unvecHS, vecHS_add, mulVec_add]
  map_smul' c X := by
    ext i j
    simp [superApply, unvecHS, vecHS_smul, mulVec_smul]

theorem superLin_apply (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X : Matrix Ω Ω ℂ) :
    superLin M X = superApply M X := rfl

theorem vecHS_single (k l : Ω) : vecHS (Matrix.single k l (1 : ℂ)) = Pi.single (k, l) 1 := by
  funext p
  obtain ⟨a, b⟩ := p
  simp only [vecHS, single_apply, Pi.single_apply, Prod.mk.injEq]
  by_cases h : k = a ∧ l = b
  · obtain ⟨rfl, rfl⟩ := h; simp
  · rw [if_neg h, if_neg]
    rintro ⟨rfl, rfl⟩; exact h ⟨rfl, rfl⟩

theorem superApply_single (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) (i j k l : Ω) :
    superApply M (Matrix.single k l 1) i j = M (i, j) (k, l) := by
  simp [superApply, unvecHS, vecHS_single]

theorem superMatrix_superLin (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) : superMatrix (superLin M) = M := by
  ext p q
  simp [superMatrix, superLin_apply, superApply_single]

theorem superApply_superMatrix (Φ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) (X : Matrix Ω Ω ℂ) :
    superApply (superMatrix Φ) X = Φ X := by
  ext i j
  conv_rhs => rw [Matrix.matrix_eq_sum_single X]
  have hs : ∀ k l, Matrix.single k l (X k l) = X k l • Matrix.single k l (1 : ℂ) := fun k l => by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  simp only [hs, map_sum, map_smul, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul]
  simp only [superApply, unvecHS, vecHS, superMatrix, mulVec, dotProduct, Matrix.of_apply,
    Fintype.sum_prod_type]
  refine Finset.sum_congr rfl fun k _ => Finset.sum_congr rfl fun l _ => ?_
  ring

theorem superLin_superMatrix (Φ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) :
    superLin (superMatrix Φ) = Φ :=
  LinearMap.ext fun X => superApply_superMatrix Φ X

theorem superApply_mul (M N : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X : Matrix Ω Ω ℂ) :
    superApply (M * N) X = superApply M (superApply N X) := by
  simp [superApply, mulVec_mulVec]

theorem superApply_one (X : Matrix Ω Ω ℂ) : superApply (1 : Matrix (Ω × Ω) (Ω × Ω) ℂ) X = X := by
  simp [superApply]

/-- Composition of superoperators is multiplication of Hilbert–Schmidt matrices. -/
theorem superMatrix_comp (Φ Ψ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) :
    superMatrix (Φ ∘ₗ Ψ) = superMatrix Φ * superMatrix Ψ := by
  conv_lhs => rw [← superLin_superMatrix Φ, ← superLin_superMatrix Ψ]
  rw [← superMatrix_superLin (superMatrix Φ * superMatrix Ψ)]
  congr 1
  exact LinearMap.ext fun X => (superApply_mul _ _ X).symm

/-- The Hilbert–Schmidt inner product in vectorised form. -/
theorem hsInner_eq_dotProduct (X Y : Matrix Ω Ω ℂ) :
    hsInner X Y = star (vecHS X) ⬝ᵥ vecHS Y := by
  simp only [hsInner, trace, diag, Matrix.mul_apply, conjTranspose_apply, dotProduct, vecHS,
    Pi.star_apply, Fintype.sum_prod_type]
  rw [Finset.sum_comm]

theorem hsInner_conj_symm (X Y : Matrix Ω Ω ℂ) : hsInner X Y = star (hsInner Y X) := by
  rw [hsInner_eq_dotProduct, hsInner_eq_dotProduct, star_dotProduct]

/-- The Hilbert–Schmidt adjoint of `superApply M` is `superApply Mᴴ`. -/
theorem hsInner_superApply (M : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X Y : Matrix Ω Ω ℂ) :
    hsInner Y (superApply M X) = hsInner (superApply Mᴴ Y) X := by
  rw [hsInner_eq_dotProduct, hsInner_eq_dotProduct, vecHS_superApply, vecHS_superApply,
    dotProduct_mulVec, star_mulVec, conjTranspose_conjTranspose]

theorem superMatrix_eq_of_superApply_eq {M N : Matrix (Ω × Ω) (Ω × Ω) ℂ}
    (h : ∀ X, superApply M X = superApply N X) : M = N := by
  ext ⟨i, j⟩ ⟨k, l⟩
  rw [← superApply_single M i j k l, ← superApply_single N i j k l, h]

/-- **Hilbert–Schmidt adjoints are conjugate transposes**: if `Ψ` is a Hilbert–Schmidt
adjoint of `Φ`, then `superMatrix Ψ = (superMatrix Φ)ᴴ`. -/
theorem superMatrix_eq_conjTranspose_of_hsAdjoint
    {Φ Ψ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ} (h : ∀ X Y, hsInner Y (Φ X) = hsInner (Ψ Y) X) :
    superMatrix Ψ = (superMatrix Φ)ᴴ := by
  refine superMatrix_eq_of_superApply_eq fun Y => ?_
  refine hsInner_left_eq_iff.1 fun X => ?_
  rw [superApply_superMatrix, ← h, ← superApply_superMatrix Φ, hsInner_superApply]

/-- The Hilbert–Schmidt frame matrix of a family of memory operators (columns `vec ρ_j`). -/
def frame {ι : Type*} (ρ : ι → Matrix Ω Ω ℂ) : Matrix (Ω × Ω) ι ℂ :=
  Matrix.of fun p j => ρ j p.1 p.2

theorem frame_conjTranspose_mul_frame {ι : Type*} [Fintype ι] (ρ : ι → Matrix Ω Ω ℂ) (i j : ι) :
    ((frame ρ)ᴴ * frame ρ) i j = hsInner (ρ i) (ρ j) := by
  rw [hsInner_eq_dotProduct]
  simp [frame, Matrix.mul_apply, dotProduct, vecHS, conjTranspose_apply]

/-- Action of a superoperator on a frame, in matrix form. -/
theorem mul_frame_eq {ι : Type*} [Fintype ι] (M : Matrix (Ω × Ω) (Ω × Ω) ℂ)
    (ρ : ι → Matrix Ω Ω ℂ) (B : Matrix ι ι ℂ)
    (h : ∀ j, superApply M (ρ j) = ∑ i, B i j • ρ i) : M * frame ρ = frame ρ * B := by
  ext p j
  have h1 := congrArg (fun X => X p.1 p.2) (h j)
  simp only [superApply, unvecHS, Matrix.of_apply, Matrix.sum_apply, Matrix.smul_apply,
    smul_eq_mul] at h1
  simp only [Matrix.mul_apply, frame, Matrix.of_apply]
  rw [show (∑ q, M p q * ρ j q.1 q.2) = (M *ᵥ vecHS (ρ j)) p from rfl, h1]
  exact Finset.sum_congr rfl fun i _ => mul_comm _ _

/-- Applying a Hilbert–Schmidt matrix to a frame vector. -/
theorem superApply_frame_col {ι : Type*} [Fintype ι] (M : Matrix (Ω × Ω) (Ω × Ω) ℂ)
    (ρ : ι → Matrix Ω Ω ℂ) (B : Matrix ι ι ℂ) (hMB : M * frame ρ = frame ρ * B) (j : ι) :
    superApply M (ρ j) = ∑ i, B i j • ρ i := by
  ext a b
  have h1 := congrFun (congrFun hMB (a, b)) j
  simp only [Matrix.mul_apply, frame, Matrix.of_apply] at h1
  simp only [superApply, unvecHS, Matrix.of_apply, Matrix.sum_apply, Matrix.smul_apply,
    smul_eq_mul]
  rw [show (M *ᵥ vecHS (ρ j)) (a, b) = ∑ q, M (a, b) q * ρ j q.1 q.2 from rfl, h1]
  exact Finset.sum_congr rfl fun i _ => mul_comm _ _

theorem superApply_add_left (M N : Matrix (Ω × Ω) (Ω × Ω) ℂ) (X : Matrix Ω Ω ℂ) :
    superApply (M + N) X = superApply M X + superApply N X := by
  ext i j
  simp [superApply, unvecHS, add_mulVec]

theorem superApply_zero_left (X : Matrix Ω Ω ℂ) :
    superApply (0 : Matrix (Ω × Ω) (Ω × Ω) ℂ) X = 0 := by
  ext i j
  simp [superApply, unvecHS]

/-- A linear combination of frame elements in vectorised form. -/
theorem sum_smul_eq_unvecHS {ι : Type*} [Fintype ι] (ρ : ι → Matrix Ω Ω ℂ) (c : ι → ℂ) :
    ∑ j, c j • ρ j = unvecHS (frame ρ *ᵥ c) := by
  ext a b
  simp only [unvecHS, Matrix.of_apply, Matrix.sum_apply, Matrix.smul_apply, smul_eq_mul, frame,
    mulVec, dotProduct]
  exact Finset.sum_congr rfl fun j _ => mul_comm _ _

end HS

/-- `⟪M c, M d⟫ = ⟪c, Mᴴ M d⟫`. -/
theorem star_mulVec_dotProduct_mulVec {p q : Type*} [Fintype p] [Fintype q] (M : Matrix p q ℂ)
    (c d : q → ℂ) : star (M *ᵥ c) ⬝ᵥ (M *ᵥ d) = star c ⬝ᵥ ((Mᴴ * M) *ᵥ d) := by
  rw [star_mulVec, ← dotProduct_mulVec, mulVec_mulVec]

/-! ### Compression to a reducing frame -/

section Compression

open CompressionDefect

variable {m k Γ : Type*} [Fintype m] [DecidableEq m] [Fintype k] [DecidableEq k]

/-- If `G V = V B` and `Gᴴ V = V Bᴴ` for an isometry `V`, the range projection of `V`
commutes with `G` (the range of `V` reduces `G`). -/
theorem commute_rangeProj_of_intertwine {V : Matrix m k ℂ} {G : Matrix m m ℂ}
    {B : Matrix k k ℂ} (h1 : G * V = V * B) (h2 : Gᴴ * V = V * Bᴴ) :
    Commute (rangeProj V) G := by
  have h3 : Vᴴ * G = B * Vᴴ := by
    have := congrArg conjTranspose h2
    simpa [conjTranspose_mul] using this
  show rangeProj V * G = G * rangeProj V
  rw [rangeProj, Matrix.mul_assoc, h3, ← Matrix.mul_assoc, ← h1, Matrix.mul_assoc]

/-- The range projection of the frame commutes with the whole generated star algebra. -/
theorem commute_rangeProj_of_mem_adjoin {V : Matrix m k ℂ} (gen : Γ → Matrix m m ℂ)
    (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) :
    ∀ x ∈ StarAlgebra.adjoin ℂ (Set.range gen), Commute (rangeProj V) x := by
  have hle : StarAlgebra.adjoin ℂ (Set.range gen) ≤
      StarSubalgebra.centralizer ℂ {rangeProj V} := by
    refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨γ, rfl⟩
    rw [SetLike.mem_coe, StarSubalgebra.mem_centralizer_iff]
    intro g hg
    rw [Set.mem_singleton_iff] at hg
    subst hg
    have hc := commute_rangeProj_of_intertwine (h1 γ) (h2 γ)
    have hs : star (rangeProj V) = rangeProj V := rangeProj_conjTranspose V
    rw [hs]
    exact ⟨hc, hc⟩
  intro x hx
  exact (((StarSubalgebra.mem_centralizer_iff ℂ).1 (hle hx)) (rangeProj V) rfl).1

/-- Elements of the generated algebra map the frame range into itself:
`x V = V (Vᴴ x V)`. -/
theorem mul_isometry_eq_of_mem_adjoin {V : Matrix m k ℂ} (hV : Vᴴ * V = 1)
    (gen : Γ → Matrix m m ℂ) (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) {x : Matrix m m ℂ}
    (hx : x ∈ StarAlgebra.adjoin ℂ (Set.range gen)) : x * V = V * compress V x := by
  have hc : rangeProj V * x = x * rangeProj V := commute_rangeProj_of_mem_adjoin gen B h1 h2 x hx
  have hPV : rangeProj V * V = V := by rw [rangeProj, Matrix.mul_assoc, hV, Matrix.mul_one]
  calc x * V = x * rangeProj V * V := by rw [Matrix.mul_assoc, hPV]
    _ = rangeProj V * x * V := by rw [hc]
    _ = V * compress V x := by simp only [rangeProj, compress, Matrix.mul_assoc]

theorem compress_mul_of_mem_adjoin {V : Matrix m k ℂ} (hV : Vᴴ * V = 1)
    (gen : Γ → Matrix m m ℂ) (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) {x y : Matrix m m ℂ}
    (hx : x ∈ StarAlgebra.adjoin ℂ (Set.range gen))
    (hy : y ∈ StarAlgebra.adjoin ℂ (Set.range gen)) :
    compress V (x * y) = compress V x * compress V y := by
  have hy' := mul_isometry_eq_of_mem_adjoin hV gen B h1 h2 hy
  have hx' := mul_isometry_eq_of_mem_adjoin hV gen B h1 h2 hx
  calc compress V (x * y) = Vᴴ * (x * (y * V)) := by simp only [compress, Matrix.mul_assoc]
    _ = Vᴴ * (x * V) * compress V y := by rw [hy']; simp only [Matrix.mul_assoc]
    _ = compress V x * compress V y := by
      rw [hx', ← Matrix.mul_assoc, hV, Matrix.one_mul]

/-- **Compression to a reducing frame is a star homomorphism** on the generated algebra. -/
noncomputable def compressHom {V : Matrix m k ℂ} (hV : Vᴴ * V = 1)
    (gen : Γ → Matrix m m ℂ) (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) :
    StarAlgebra.adjoin ℂ (Set.range gen) →⋆ₐ[ℂ] Matrix k k ℂ where
  toFun x := compress V x
  map_one' := compress_one hV
  map_mul' x y := compress_mul_of_mem_adjoin hV gen B h1 h2 x.2 y.2
  map_zero' := by simp [compress]
  map_add' x y := compress_add V x y
  commutes' r := by
    simp [compress, Algebra.algebraMap_eq_smul_one, hV]
  map_star' x := by
    change compress V (x : Matrix m m ℂ)ᴴ = (compress V x)ᴴ
    exact compress_conjTranspose V x

theorem compressHom_apply {V : Matrix m k ℂ} (hV : Vᴴ * V = 1)
    (gen : Γ → Matrix m m ℂ) (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) (x : StarAlgebra.adjoin ℂ (Set.range gen)) :
    compressHom hV gen B h1 h2 x = compress V x := rfl

/-- The compressed generated algebra is the star algebra generated by the compressed
generators. -/
theorem range_compressHom {V : Matrix m k ℂ} (hV : Vᴴ * V = 1)
    (gen : Γ → Matrix m m ℂ) (B : Γ → Matrix k k ℂ) (h1 : ∀ γ, gen γ * V = V * B γ)
    (h2 : ∀ γ, (gen γ)ᴴ * V = V * (B γ)ᴴ) :
    (compressHom hV gen B h1 h2).range = StarAlgebra.adjoin ℂ (Set.range B) := by
  have hgen : ∀ γ, compress V (gen γ) = B γ := fun γ => by
    rw [compress, Matrix.mul_assoc, h1, ← Matrix.mul_assoc, hV, Matrix.one_mul]
  apply le_antisymm
  · rintro _ ⟨x, rfl⟩
    obtain ⟨x, hx⟩ := x
    change compress V x ∈ _
    induction hx using StarAlgebra.adjoin_induction with
    | mem x hx =>
      obtain ⟨γ, rfl⟩ := hx
      rw [hgen]
      exact StarAlgebra.subset_adjoin ℂ _ ⟨γ, rfl⟩
    | algebraMap r =>
      rw [show compress V (algebraMap ℂ (Matrix m m ℂ) r) = algebraMap ℂ (Matrix k k ℂ) r by
        simp [compress, Algebra.algebraMap_eq_smul_one, hV]]
      exact StarSubalgebra.algebraMap_mem _ r
    | add x y _ _ hx hy =>
      rw [compress_add]
      exact add_mem hx hy
    | mul x y hx' hy' hx hy =>
      rw [compress_mul_of_mem_adjoin hV gen B h1 h2 hx' hy']
      exact mul_mem hx hy
    | star x _ hx =>
      rw [show star x = xᴴ from rfl, compress_conjTranspose]
      exact star_mem hx
  · refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨γ, rfl⟩
    exact ⟨⟨gen γ, StarAlgebra.subset_adjoin ℂ _ ⟨γ, rfl⟩⟩, hgen γ⟩

end Compression

/-- Conjugation `x ↦ W x Wᴴ` by a (rectangular) unitary as a star algebra homomorphism. -/
def unitaryConjHom {n ι : Type*} [Fintype n] [DecidableEq n] [Fintype ι] [DecidableEq ι]
    (W : Matrix n ι ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1) :
    Matrix ι ι ℂ →⋆ₐ[ℂ] Matrix n n ℂ where
  toFun x := W * x * Wᴴ
  map_one' := by simp [hW2]
  map_mul' x y := by
    change W * (x * y) * Wᴴ = W * x * Wᴴ * (W * y * Wᴴ)
    calc W * (x * y) * Wᴴ = W * x * (Wᴴ * W) * y * Wᴴ := by
          rw [hW1, Matrix.mul_one]; simp only [Matrix.mul_assoc]
      _ = W * x * Wᴴ * (W * y * Wᴴ) := by simp only [Matrix.mul_assoc]
  map_zero' := by simp
  map_add' x y := by simp [Matrix.mul_add, Matrix.add_mul]
  commutes' r := by simp [Algebra.algebraMap_eq_smul_one, hW2]
  map_star' x := by
    change W * xᴴ * Wᴴ = (W * x * Wᴴ)ᴴ
    simp [conjTranspose_mul, Matrix.mul_assoc]

theorem unitaryConjHom_apply {n ι : Type*} [Fintype n] [DecidableEq n] [Fintype ι]
    [DecidableEq ι] (W : Matrix n ι ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1)
    (x : Matrix ι ι ℂ) : unitaryConjHom W hW1 hW2 x = W * x * Wᴴ := rfl

/-! ### Finite operational schemes -/

section KrausCP

variable {Ω : Type*} [Fintype Ω] [DecidableEq Ω]

/-- Complete positivity in finite Kraus form, `Φ(X) = ∑_a W_a X W_aᴴ`.  For `Ω = Fin d` this is
the library's `IsMatrixCompletelyPositive` (`isKrausCP_iff_isMatrixCompletelyPositive`). -/
def IsKrausCP (Φ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) : Prop :=
  ∃ (κ : Type) (_ : Fintype κ) (W : κ → Matrix Ω Ω ℂ), Φ = krausMap W

theorem isKrausCP_iff_isMatrixCompletelyPositive {d : ℕ}
    (Φ : Matrix (Fin d) (Fin d) ℂ →ₗ[ℂ] Matrix (Fin d) (Fin d) ℂ) :
    IsKrausCP Φ ↔ IsMatrixCompletelyPositive Φ := by
  constructor
  · rintro ⟨κ, _, W, rfl⟩
    exact krausMap_completelyPositive W
  · intro h
    obtain ⟨W, hW⟩ := (completelyPositive_iff_exists_kraus Φ).1 h
    exact ⟨_, inferInstance, W, hW⟩

end KrausCP

/-- A finite operational scheme: physical memory `ℂ^Ω`, boundary preparations `prep j`,
terminal readouts (effects) `eff i`, and a finite family `Br` of two-outcome instruments with
success branch `succ β` and failure branch `fail β`. -/
structure Scheme (Ω ι Br : Type*) where
  /-- Boundary preparations. -/
  prep : ι → Matrix Ω Ω ℂ
  /-- Terminal readouts (effects). -/
  eff : ι → Matrix Ω Ω ℂ
  /-- Success branches. -/
  succ : Br → Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ
  /-- Complementary failure branches. -/
  fail : Br → Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ

namespace Scheme

variable {Ω ι Br : Type*} [Fintype Ω] [DecidableEq Ω] (S : Scheme Ω ι Br)

/-- Physical validity: density preparations, effect readouts, completely positive branches,
and normalized instruments `Tr(succ β X + fail β X) = Tr X`. -/
structure IsValid : Prop where
  prep_isDensity : ∀ j, RankOneForcing.IsDensity (S.prep j)
  eff_isEffect : ∀ i, RankOneForcing.IsEffect (S.eff i)
  succ_cp : ∀ β, IsKrausCP (S.succ β)
  fail_cp : ∀ β, IsKrausCP (S.fail β)
  normalized : ∀ β X, (S.succ β X + S.fail β X).trace = X.trace

/-- All branches: `inl β` success, `inr β` failure. -/
def branch : Br ⊕ Br → (Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ) := Sum.elim S.succ S.fail

/-- The internal history (process) algebra: the star subalgebra of operators on the
Hilbert–Schmidt memory space generated by all branch superoperators (the star is the
Hilbert–Schmidt adjoint, `superMatrix_eq_conjTranspose_of_hsAdjoint`). -/
def processAlgebra : StarSubalgebra ℂ (Matrix (Ω × Ω) (Ω × Ω) ℂ) :=
  FiniteGrandTensor.historyAlgebra fun γ => superMatrix (S.branch γ)

/-- The boundary readout context `x ↦ Tr(E_i x(ρ_j))`. -/
def readout (i j : ι) : S.processAlgebra →+ ℂ where
  toFun x := (S.eff i * superApply (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) (S.prep j)).trace
  map_zero' := by simp [superApply_zero_left]
  map_add' x y := by
    simp [superApply_add_left, Matrix.mul_add, trace_add]

/-- The contextual future-null ideal of the boundary readouts. -/
def futureNull : Ideal S.processAlgebra :=
  contextualFutureNullIdeal fun p : ι × ι => S.readout p.1 p.2

/-- The diagonal Hilbert–Schmidt source subspace `span{ρ_j}`. -/
def sourceSpan : Submodule ℂ (Matrix Ω Ω ℂ) := Submodule.span ℂ (Set.range S.prep)

/-- **The future-separated source representation of `S` is unitarily equivalent to `π`**:
a surjective star homomorphism `θ` from the internal history algebra onto `A` whose kernel is
exactly the contextual future-null ideal (so the future-separated quotient is `≅ A`), and a
Hilbert–Schmidt unitary `T : ℂ^n → span{ρ_j}` intertwining the action of every internal
history on the source span with `π ∘ θ`. -/
def RealizesRep {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A] {n : Type*} [Fintype n]
    [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ) : Prop :=
  ∃ (θ : S.processAlgebra →⋆ₐ[ℂ] A) (T : (n → ℂ) →ₗ[ℂ] Matrix Ω Ω ℂ),
    Function.Surjective θ ∧ (∀ x, θ x = 0 ↔ x ∈ S.futureNull) ∧
    (∀ v w, hsInner (T v) (T w) = star v ⬝ᵥ w) ∧ LinearMap.range T = S.sourceSpan ∧
    ∀ (x : S.processAlgebra) (v : n → ℂ),
      superApply (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) (T v) = T (π (θ x) *ᵥ v)

/-- The source span reduces every internal history (a consequence of `RealizesRep`). -/
theorem RealizesRep.reducing {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A] {n : Type*}
    [Fintype n] [DecidableEq n] {π : A →⋆ₐ[ℂ] Matrix n n ℂ} (h : S.RealizesRep π)
    (x : S.processAlgebra) {X : Matrix Ω Ω ℂ} (hX : X ∈ S.sourceSpan) :
    superApply (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) X ∈ S.sourceSpan := by
  obtain ⟨θ, T, -, -, -, hT, hint⟩ := h
  rw [← hT] at hX ⊢
  obtain ⟨v, rfl⟩ := hX
  rw [hint]
  exact LinearMap.mem_range_self _ _

/-- The readout of a history acting on a reducing frame is its compressed matrix
coefficient. -/
theorem readout_eq_of_frame [Fintype ι] [DecidableEq ι]
    (hdisc : ∀ i j, (S.eff i * S.prep j).trace = if i = j then 1 else 0)
    (x : S.processAlgebra) (B : Matrix ι ι ℂ)
    (hxB : (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) * frame S.prep = frame S.prep * B) (i j : ι) :
    S.readout i j x = B i j := by
  change (S.eff i * superApply (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) (S.prep j)).trace = B i j
  rw [superApply_frame_col _ _ _ hxB, Matrix.mul_sum, trace_sum]
  simp_rw [Matrix.mul_smul, trace_smul, hdisc, smul_eq_mul, mul_ite, mul_one, mul_zero]
  simp

/-- **General realization criterion.**  Let the preparations of a scheme form a
Hilbert–Schmidt orthonormal frame that is perfectly discriminated by the readouts, let every
branch `γ` and a Hilbert–Schmidt adjoint of it act on the frame by the matrices `A_γ`,
`A_γᴴ`, and let the star algebra generated by the `A_γ` be unitarily equivalent (via `W`) to
the image of a faithful representation `π`.  Then the future-separated source representation
of the scheme is unitarily equivalent to `π`. -/
theorem realizesRep_of_frame {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ)
    (hπ : Function.Injective π) [Fintype ι] [DecidableEq ι]
    (hON : ∀ i j, hsInner (S.prep i) (S.prep j) = if i = j then 1 else 0)
    (hdisc : ∀ i j, (S.eff i * S.prep j).trace = if i = j then 1 else 0)
    (Am : Br ⊕ Br → Matrix ι ι ℂ)
    (hfwd : ∀ γ j, S.branch γ (S.prep j) = ∑ i, Am γ i j • S.prep i)
    (hadj : ∀ γ, ∃ Ψ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ,
      (∀ X Y, hsInner Y (S.branch γ X) = hsInner (Ψ Y) X) ∧
      ∀ j, Ψ (S.prep j) = ∑ i, star (Am γ j i) • S.prep i)
    (W : Matrix n ι ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1)
    (hrange : (fun x => W * x * Wᴴ) ''
      (StarAlgebra.adjoin ℂ (Set.range Am) : Set (Matrix ι ι ℂ)) = Set.range π) :
    S.RealizesRep π := by
  classical
  set V := frame S.prep with hVdef
  have hV : Vᴴ * V = 1 := by
    ext i j
    rw [frame_conjTranspose_mul_frame, hON, one_apply]
  set gen : Br ⊕ Br → Matrix (Ω × Ω) (Ω × Ω) ℂ := fun γ => superMatrix (S.branch γ) with hgen
  have h1 : ∀ γ, gen γ * V = V * Am γ := fun γ =>
    mul_frame_eq _ _ _ fun j => by rw [hgen, superApply_superMatrix, hfwd]
  have h2 : ∀ γ, (gen γ)ᴴ * V = V * (Am γ)ᴴ := by
    intro γ
    obtain ⟨Ψ, hΨ, hΨρ⟩ := hadj γ
    rw [hgen, ← superMatrix_eq_conjTranspose_of_hsAdjoint hΨ]
    refine mul_frame_eq _ _ _ fun j => ?_
    rw [superApply_superMatrix, hΨρ]
    simp [conjTranspose_apply]
  -- the compression star homomorphism
  let κ : S.processAlgebra →⋆ₐ[ℂ] Matrix ι ι ℂ := compressHom hV gen Am h1 h2
  have hκ : ∀ x : S.processAlgebra, κ x = CompressionDefect.compress V x := fun x => rfl
  have hxV : ∀ x : S.processAlgebra, (x : Matrix (Ω × Ω) (Ω × Ω) ℂ) * V = V * κ x := fun x =>
    mul_isometry_eq_of_mem_adjoin hV gen Am h1 h2 x.2
  have hκrange : κ.range = StarAlgebra.adjoin ℂ (Set.range Am) :=
    range_compressHom hV gen Am h1 h2
  -- the represented homomorphism
  let res : S.processAlgebra →⋆ₐ[ℂ] Matrix n n ℂ := (unitaryConjHom W hW1 hW2).comp κ
  have hres : ∀ x, res x = W * κ x * Wᴴ := fun x => rfl
  have hres_mem : ∀ x, res x ∈ π.range := by
    intro x
    have hmem : κ x ∈ StarAlgebra.adjoin ℂ (Set.range Am) := hκrange ▸ ⟨x, rfl⟩
    have : res x ∈ (fun x => W * x * Wᴴ) ''
        (StarAlgebra.adjoin ℂ (Set.range Am) : Set (Matrix ι ι ℂ)) := ⟨κ x, hmem, rfl⟩
    rw [hrange] at this
    obtain ⟨a, ha⟩ := this
    exact ⟨a, ha⟩
  have hres_surj : ∀ a, ∃ x, res x = π a := by
    intro a
    have : π a ∈ (fun x => W * x * Wᴴ) ''
        (StarAlgebra.adjoin ℂ (Set.range Am) : Set (Matrix ι ι ℂ)) := by
      rw [hrange]; exact ⟨a, rfl⟩
    obtain ⟨y, hy, hya⟩ := this
    rw [SetLike.mem_coe, ← hκrange] at hy
    obtain ⟨x, rfl⟩ := hy
    exact ⟨x, hya⟩
  have hbij : Function.Bijective π.rangeRestrict := by
    refine ⟨fun a b h => hπ (congrArg Subtype.val h), ?_⟩
    rintro ⟨_, a, rfl⟩
    exact ⟨a, rfl⟩
  let e : A ≃⋆ₐ[ℂ] π.range := StarAlgEquiv.ofBijective π.rangeRestrict hbij
  let θ : S.processAlgebra →⋆ₐ[ℂ] A :=
    (e.symm : π.range →⋆ₐ[ℂ] A).comp (res.codRestrict π.range hres_mem)
  have hθ : ∀ x, π (θ x) = res x := by
    intro x
    have h := congrArg Subtype.val (e.apply_symm_apply ⟨res x, hres_mem x⟩)
    exact h
  have hκ0 : ∀ x, θ x = 0 ↔ κ x = 0 := by
    intro x
    constructor
    · intro h0
      have h3 : res x = 0 := by rw [← hθ, h0, map_zero]
      rw [hres] at h3
      calc κ x = Wᴴ * (W * κ x * Wᴴ) * W := by
            simp only [← Matrix.mul_assoc, hW1, Matrix.one_mul]
            rw [Matrix.mul_assoc, hW1, Matrix.mul_one]
        _ = 0 := by rw [h3, Matrix.mul_zero, Matrix.zero_mul]
    · intro h0
      apply hπ
      rw [hθ, hres, h0, map_zero]
      simp
  -- readouts are compressed matrix coefficients
  have hread : ∀ (x : S.processAlgebra) (i j : ι), S.readout i j x = κ x i j :=
    fun x i j => S.readout_eq_of_frame hdisc x (κ x) (hxV x) i j
  -- the source unitary
  let T : (n → ℂ) →ₗ[ℂ] Matrix Ω Ω ℂ :=
    (Fintype.linearCombination ℂ S.prep) ∘ₗ (Wᴴ).mulVecLin
  have hT : ∀ v, T v = unvecHS (V *ᵥ (Wᴴ *ᵥ v)) := by
    intro v
    change Fintype.linearCombination ℂ S.prep (Wᴴ *ᵥ v) = _
    rw [Fintype.linearCombination_apply, sum_smul_eq_unvecHS]
  refine ⟨θ, T, ?_, ?_, ?_, ?_, ?_⟩
  · -- surjectivity
    intro a
    obtain ⟨x, hx⟩ := hres_surj a
    exact ⟨x, hπ (by rw [hθ, hx])⟩
  · -- the kernel is the contextual future-null ideal
    intro x
    rw [hκ0]
    change κ x = 0 ↔ contextualFutureNull _ x
    constructor
    · intro h0
      refine ⟨fun p u v => ?_, fun p u v => ?_⟩
      · change S.readout p.1 p.2 (u * x * v) = 0
        rw [hread, map_mul, map_mul, h0, Matrix.mul_zero, Matrix.zero_mul, Matrix.zero_apply]
      · change S.readout p.1 p.2 (u * star x * v) = 0
        rw [hread, map_mul, map_mul, map_star, h0, star_zero, Matrix.mul_zero, Matrix.zero_mul,
          Matrix.zero_apply]
    · intro hx
      ext i j
      have h3 := hx.1 (i, j) 1 1
      change S.readout i j (1 * x * 1) = 0 at h3
      rw [one_mul, mul_one, hread] at h3
      rw [h3, Matrix.zero_apply]
  · -- Hilbert–Schmidt isometry
    intro v w
    rw [hT, hT, hsInner_eq_dotProduct, vecHS_unvecHS, vecHS_unvecHS,
      star_mulVec_dotProduct_mulVec, hV, Matrix.one_mulVec, star_mulVec_dotProduct_mulVec,
      conjTranspose_conjTranspose, hW2, Matrix.one_mulVec]
  · -- onto the source span
    change LinearMap.range ((Fintype.linearCombination ℂ S.prep) ∘ₗ (Wᴴ).mulVecLin) = _
    rw [LinearMap.range_comp_of_range_eq_top, Fintype.range_linearCombination]
    · rfl
    · rw [LinearMap.range_eq_top]
      intro c
      refine ⟨W *ᵥ c, ?_⟩
      rw [Matrix.mulVecLin_apply, mulVec_mulVec, hW1, one_mulVec]
  · -- intertwining
    intro x v
    rw [hT, hT, superApply, vecHS_unvecHS, mulVec_mulVec, hxV, hθ, hres, ← mulVec_mulVec,
      ← mulVec_mulVec]
    congr 2
    rw [mulVec_mulVec, mulVec_mulVec, mulVec_mulVec, ← Matrix.mul_assoc]
    rw [hW1, Matrix.one_mul]

end Scheme

/-! ### Classical (diagonal-to-diagonal) superoperators -/

section Diag

variable {Ω : Type*} [Fintype Ω] [DecidableEq Ω]

/-- The classical superoperator `X ↦ diag(A · diag X)` with transition matrix `A`: it reads
the diagonal of `X` in the memory basis and prepares the image diagonally. -/
def diagSuperop (A : Matrix Ω Ω ℂ) : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ where
  toFun X := diagonal (A *ᵥ fun t => X t t)
  map_add' X Y := by
    ext a b
    by_cases h : a = b
    · subst h
      simp [mulVec, dotProduct, mul_add, Finset.sum_add_distrib]
    · simp [diagonal_apply_ne _ h]
  map_smul' c X := by
    ext a b
    by_cases h : a = b
    · subst h
      simp [mulVec, dotProduct, Finset.mul_sum, mul_left_comm]
    · simp [diagonal_apply_ne _ h]

theorem diagSuperop_apply (A X : Matrix Ω Ω ℂ) :
    diagSuperop A X = diagonal (A *ᵥ fun t => X t t) := rfl

/-- On the diagonal matrix units the classical superoperator acts by its transition matrix:
`𝒟_A(p_j) = ∑_i A_ij p_i`. -/
theorem diagSuperop_single (A : Matrix Ω Ω ℂ) (j : Ω) :
    diagSuperop A (Matrix.single j j 1) = ∑ i, A i j • Matrix.single i i (1 : ℂ) := by
  ext a b
  rw [diagSuperop_apply, Matrix.sum_apply]
  simp only [Matrix.smul_apply, single_apply, smul_eq_mul, mul_ite, mul_one, mul_zero]
  by_cases hab : a = b
  · subst hab
    rw [diagonal_apply_eq]
    simp [mulVec, dotProduct, single_apply]
  · rw [diagonal_apply_ne _ hab]
    symm
    refine Finset.sum_eq_zero fun i _ => ?_
    rw [if_neg]
    rintro ⟨rfl, rfl⟩
    exact hab rfl

theorem hsInner_diagonal_right (Y : Matrix Ω Ω ℂ) (u : Ω → ℂ) :
    hsInner Y (diagonal u) = ∑ i, star (Y i i) * u i := by
  simp [hsInner, trace, Matrix.mul_diagonal, conjTranspose_apply]

theorem hsInner_diagonal_left (u : Ω → ℂ) (X : Matrix Ω Ω ℂ) :
    hsInner (diagonal u) X = ∑ i, star (u i) * X i i := by
  simp [hsInner, trace, diagonal_conjTranspose, Matrix.diagonal_mul]

/-- The Hilbert–Schmidt adjoint of `𝒟_A` is `𝒟_{Aᴴ}`. -/
theorem hsInner_diagSuperop (A X Y : Matrix Ω Ω ℂ) :
    hsInner Y (diagSuperop A X) = hsInner (diagSuperop Aᴴ Y) X := by
  rw [diagSuperop_apply, diagSuperop_apply, hsInner_diagonal_right, hsInner_diagonal_left]
  simp only [mulVec, dotProduct, star_sum, star_mul', conjTranspose_apply, star_star,
    Finset.mul_sum, Finset.sum_mul]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  ring

/-- The trace of `𝒟_A(X)`: `Tr 𝒟_A(X) = ∑_t (∑_s A_st) X_tt`. -/
theorem trace_diagSuperop (A X : Matrix Ω Ω ℂ) :
    (diagSuperop A X).trace = ∑ t, (∑ s, A s t) * X t t := by
  rw [diagSuperop_apply, trace_diagonal]
  simp only [mulVec, dotProduct, Finset.sum_mul]
  exact Finset.sum_comm

/-- **Kraus form of a classical superoperator** with nonnegative transition weights:
`𝒟_A = ∑_{(s,t)} K_{st} (·) K_{st}ᴴ`, `K_{st} = √(w_st) |e_s⟩⟨e_t|`. -/
theorem diagSuperop_eq_krausMap (A : Matrix Ω Ω ℂ) (w : Ω → Ω → ℝ) (hw : ∀ s t, 0 ≤ w s t)
    (hA : ∀ s t, A s t = w s t) :
    diagSuperop A = krausMap (fun p : Ω × Ω =>
      Matrix.single p.1 p.2 ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ)) := by
  refine LinearMap.ext fun X => ?_
  rw [krausMap_apply, diagSuperop_apply]
  have hterm : ∀ p : Ω × Ω,
      Matrix.single p.1 p.2 ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ) * X *
        (Matrix.single p.1 p.2 ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ))ᴴ =
      Matrix.single p.1 p.1 ((w p.1 p.2 : ℂ) * X p.2 p.2) := by
    intro p
    rw [conjTranspose_single, single_mul_mul_single]
    congr 1
    have hc : ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ) * star ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ) =
        (w p.1 p.2 : ℂ) := by
      rw [Complex.star_def, Complex.conj_ofReal, ← Complex.ofReal_mul,
        Real.mul_self_sqrt (hw _ _)]
    calc ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ) * X p.2 p.2 * star ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ)
        = (((Real.sqrt (w p.1 p.2) : ℝ) : ℂ) * star ((Real.sqrt (w p.1 p.2) : ℝ) : ℂ)) *
          X p.2 p.2 := by ring
      _ = _ := by rw [hc]
  simp_rw [hterm]
  ext a b
  rw [Matrix.sum_apply, Fintype.sum_prod_type]
  simp only [single_apply]
  by_cases hab : a = b
  · subst hab
    rw [diagonal_apply_eq]
    simp [mulVec, dotProduct, hA]
  · rw [diagonal_apply_ne _ hab]
    symm
    refine Finset.sum_eq_zero fun s _ => Finset.sum_eq_zero fun t _ => ?_
    rw [if_neg]
    rintro ⟨rfl, rfl⟩
    exact hab rfl

end Diag

/-! ### Block matrix units `E^{(λ)}_{ab} ⊗ I_{m_λ}` -/

section Block

variable {β : Type} [Fintype β] [DecidableEq β] (I J : β → Type) [∀ b, Fintype (I b)]
  [∀ b, DecidableEq (I b)] [∀ b, Fintype (J b)] [∀ b, DecidableEq (J b)]

/-- The block-Kronecker embedding `(X_λ) ↦ ⊕_λ X_λ ⊗ I_{m_λ}` as a linear map. -/
def blockLin : (∀ b, Matrix (I b) (I b) ℂ) →ₗ[ℂ] Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ where
  toFun X := blockDiagonal' fun b => X b ⊗ₖ (1 : Matrix (J b) (J b) ℂ)
  map_add' X Y := by
    rw [← blockDiagonal'_add]
    congr 1
    funext b
    rw [Pi.add_apply, Pi.add_apply, add_kronecker]
  map_smul' c X := by
    rw [RingHom.id_apply, ← blockDiagonal'_smul]
    congr 1
    funext b
    rw [Pi.smul_apply, Pi.smul_apply, smul_kronecker]

/-- The block-Kronecker embedding `(X_λ) ↦ ⊕_λ X_λ ⊗ I_{m_λ}` as a star algebra
homomorphism; its range is the Wedderburn action algebra `actionBlockSet I J`. -/
def blockHom : (∀ b, Matrix (I b) (I b) ℂ) →⋆ₐ[ℂ] Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ :=
  { AlgHom.ofLinearMap (blockLin I J)
      (by
        change blockDiagonal' (fun b => (1 : Matrix (I b) (I b) ℂ) ⊗ₖ
          (1 : Matrix (J b) (J b) ℂ)) = 1
        simp_rw [one_kronecker_one]
        exact blockDiagonal'_one)
      (fun X Y => by
        change blockDiagonal' (fun b => (X b * Y b) ⊗ₖ (1 : Matrix (J b) (J b) ℂ)) =
          blockDiagonal' (fun b => X b ⊗ₖ (1 : Matrix (J b) (J b) ℂ)) *
            blockDiagonal' (fun b => Y b ⊗ₖ (1 : Matrix (J b) (J b) ℂ))
        rw [← blockDiagonal'_mul]
        congr 1
        funext b
        rw [← mul_kronecker_mul, Matrix.mul_one]) with
    map_star' := fun X => by
      change blockDiagonal' (fun b => (star X) b ⊗ₖ (1 : Matrix (J b) (J b) ℂ)) =
        (blockDiagonal' (fun b => X b ⊗ₖ (1 : Matrix (J b) (J b) ℂ)))ᴴ
      rw [blockDiagonal'_conjTranspose]
      congr 1
      funext b
      rw [conjTranspose_kronecker, conjTranspose_one]
      rfl }

theorem blockHom_apply (X : ∀ b, Matrix (I b) (I b) ℂ) :
    blockHom I J X = blockDiagonal' fun b => X b ⊗ₖ (1 : Matrix (J b) (J b) ℂ) := rfl

theorem range_blockHom : Set.range (blockHom I J) = actionBlockSet I J := by
  ext x
  constructor
  · rintro ⟨X, rfl⟩
    exact ⟨X, rfl⟩
  · rintro ⟨X, rfl⟩
    exact ⟨X, rfl⟩

/-- The block matrix unit `E^{(λ)}_{ab} ⊗ I_{m_λ}`. -/
def blockUnit (b : β) (i j : I b) : Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ :=
  blockHom I J (Pi.single b (Matrix.single i j 1))

variable {I J}

theorem sigma_mk_eq_mk_iff {b : β} {i i' : I b} {r r' : J b} :
    (⟨b, (i, r)⟩ : Σ b, I b × J b) = ⟨b, (i', r')⟩ ↔ i = i' ∧ r = r' := by
  simp

theorem blockUnit_apply_mk (b : β) (i j : I b) (r : J b) :
    blockUnit I J b i j ⟨b, (i, r)⟩ ⟨b, (j, r)⟩ = 1 := by
  simp [blockUnit, blockHom_apply, blockDiagonal'_apply_eq, kronecker_apply, single_apply]

theorem blockUnit_apply_of_not (b : β) (i j : I b) (s t : Σ b, I b × J b)
    (h : ¬ ∃ r : J b, s = ⟨b, (i, r)⟩ ∧ t = ⟨b, (j, r)⟩) : blockUnit I J b i j s t = 0 := by
  obtain ⟨b1, i1, r1⟩ := s
  obtain ⟨b2, j2, r2⟩ := t
  rw [blockUnit, blockHom_apply]
  by_cases h12 : b1 = b2
  · subst h12
    rw [blockDiagonal'_apply_eq, kronecker_apply]
    by_cases hb : b1 = b
    · subst hb
      simp only [Pi.single_eq_same, single_apply, one_apply]
      by_cases hh : i = i1 ∧ j = j2 ∧ r1 = r2
      · obtain ⟨rfl, rfl, rfl⟩ := hh
        exact absurd ⟨r1, rfl, rfl⟩ h
      · rw [ite_mul, one_mul, zero_mul]
        split_ifs with h1 h2
        · exact absurd ⟨h1.1, h1.2, h2⟩ hh
        · rfl
        · rfl
    · rw [Pi.single_eq_of_ne hb]
      simp
  · exact blockDiagonal'_apply_ne _ _ _ h12

theorem exists_of_blockUnit_ne_zero {b : β} {i j : I b} {s t : Σ b, I b × J b}
    (h : blockUnit I J b i j s t ≠ 0) : ∃ r : J b, s = ⟨b, (i, r)⟩ ∧ t = ⟨b, (j, r)⟩ := by
  by_contra hc
  exact h (blockUnit_apply_of_not b i j s t hc)

theorem blockUnit_apply_eq_zero_or_one (b : β) (i j : I b) (s t : Σ b, I b × J b) :
    blockUnit I J b i j s t = 0 ∨ blockUnit I J b i j s t = 1 := by
  by_cases h : ∃ r : J b, s = ⟨b, (i, r)⟩ ∧ t = ⟨b, (j, r)⟩
  · obtain ⟨r, rfl, rfl⟩ := h
    exact Or.inr (blockUnit_apply_mk b i j r)
  · exact Or.inl (blockUnit_apply_of_not b i j s t h)

/-- Column sums of a block matrix unit do not depend on the row label `a`. -/
theorem sum_blockUnit_col (b : β) (i i' j : I b) (t : Σ b, I b × J b) :
    ∑ s, blockUnit I J b i j s t = ∑ s, blockUnit I J b i' j s t := by
  by_cases h : ∃ r : J b, t = ⟨b, (j, r)⟩
  · obtain ⟨r, rfl⟩ := h
    have hcol : ∀ k : I b, ∑ s, blockUnit I J b k j s ⟨b, (j, r)⟩ = 1 := by
      intro k
      rw [Finset.sum_eq_single ⟨b, (k, r)⟩]
      · exact blockUnit_apply_mk b k j r
      · intro s _ hs
        refine blockUnit_apply_of_not b k j s _ ?_
        rintro ⟨r', rfl, h2⟩
        rw [sigma_mk_eq_mk_iff] at h2
        exact hs (by rw [h2.2])
      · simp
    rw [hcol, hcol]
  · have hz : ∀ k : I b, ∑ s, blockUnit I J b k j s t = 0 := fun k =>
      Finset.sum_eq_zero fun s _ => blockUnit_apply_of_not b k j s t
        fun ⟨r, _, h2⟩ => h ⟨r, h2⟩
    rw [hz, hz]

/-- Every block-Kronecker element is a combination of block matrix units. -/
theorem blockHom_eq_sum (X : ∀ b, Matrix (I b) (I b) ℂ) :
    blockHom I J X = ∑ b, ∑ i, ∑ j, X b i j • blockUnit I J b i j := by
  have hX : X = ∑ b, ∑ i, ∑ j, X b i j • (Pi.single b (Matrix.single i j (1 : ℂ)) :
      ∀ b, Matrix (I b) (I b) ℂ) := by
    funext b'
    ext i' j'
    rw [Finset.sum_apply, Matrix.sum_apply, Finset.sum_eq_single b']
    · simp only [Finset.sum_apply, Matrix.sum_apply, Pi.smul_apply, Matrix.smul_apply,
        Pi.single_eq_same, single_apply, smul_eq_mul, mul_ite, mul_one, mul_zero]
      rw [Finset.sum_eq_single i', Finset.sum_eq_single j']
      · simp
      · intro j _ hj; simp [hj]
      · simp
      · intro i _ hi
        refine Finset.sum_eq_zero fun j _ => ?_
        simp [hi]
      · simp
    · intro b _ hb
      simp only [Finset.sum_apply, Matrix.sum_apply, Pi.smul_apply, Matrix.smul_apply,
        Pi.single_eq_of_ne' hb, Pi.single_eq_of_ne (Ne.symm hb)]
      simp
    · simp
  conv_lhs => rw [hX]
  simp only [map_sum, map_smul]
  rfl

end Block

/-! ### The realization -/

section Realization

variable {β : Type} [Fintype β] [DecidableEq β] (I J : β → Type) [∀ b, Fintype (I b)]
  [∀ b, DecidableEq (I b)] [∀ b, Fintype (J b)] [∀ b, DecidableEq (J b)]

/-- The transition matrices of the realization: success branch `(λ, a, b) ↦ E^{(λ)}_{ab} ⊗ I`,
failure branch `(λ, a, b) ↦ 1 − E^{(λ)}_{bb} ⊗ I`. -/
def realizationMatrix :
    (Σ b, I b × I b) ⊕ (Σ b, I b × I b) → Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ :=
  Sum.elim (fun β => blockUnit I J β.1 β.2.1 β.2.2) (fun β => 1 - blockUnit I J β.1 β.2.2 β.2.2)

/-- **The realization of `thm:ncg-operational-realization`.**  Memory `H = ℂ^{⊕_λ n_λ × m_λ}`
with basis `e_{λ,a,r}`; boundary preparations and terminal readouts
`p_{λ,a,r} = |e_{λ,a,r}⟩⟨e_{λ,a,r}|`; for each `(λ, a, b)` the two-outcome instrument with
success branch `Φ^λ_{ab}(X) = ∑_r L X Lᴴ`, `L = |e_{λ,a,r}⟩⟨e_{λ,b,r}|`
(`realizationScheme_succ_eq_kraus`), and failure branch `Ψ^λ_b = 𝖯 − Φ^λ_{bb}` (`𝖯` the
dephasing channel). -/
noncomputable def realizationScheme :
    Scheme (Σ b, I b × J b) (Σ b, I b × J b) (Σ b, I b × I b) where
  prep s := Matrix.single s s 1
  eff s := Matrix.single s s 1
  succ β := diagSuperop (realizationMatrix I J (Sum.inl β))
  fail β := diagSuperop (realizationMatrix I J (Sum.inr β))

theorem realizationScheme_branch (γ : (Σ b, I b × I b) ⊕ (Σ b, I b × I b)) :
    (realizationScheme I J).branch γ = diagSuperop (realizationMatrix I J γ) := by
  cases γ <;> rfl

/-- The failure branch is `𝖯 − Φ^λ_{bb}` with `𝖯` the dephasing channel `𝒟_1`. -/
theorem realizationScheme_fail_eq (β : Σ b, I b × I b) :
    (realizationScheme I J).fail β =
      diagSuperop 1 - (realizationScheme I J).succ ⟨β.1, (β.2.2, β.2.2)⟩ := by
  refine LinearMap.ext fun X => ?_
  simp only [realizationScheme, realizationMatrix, Sum.elim_inl, Sum.elim_inr,
    LinearMap.sub_apply, diagSuperop_apply, sub_mulVec, diagonal_sub]
  rfl

/-- The success branch is the paper's rank-one Kraus map
`Φ^λ_{ab}(X) = ∑_r L_r X L_rᴴ`, `L_r = |e_{λ,a,r}⟩⟨e_{λ,b,r}|`. -/
theorem realizationScheme_succ_eq_kraus (b : β) (i j : I b) :
    (realizationScheme I J).succ ⟨b, (i, j)⟩ =
      krausMap (fun r : J b => Matrix.single (⟨b, (i, r)⟩ : Σ b, I b × J b) ⟨b, (j, r)⟩ 1) := by
  refine LinearMap.ext fun X => ?_
  rw [krausMap_apply]
  simp only [conjTranspose_single, star_one, single_mul_mul_single, one_mul, mul_one]
  change diagonal (blockUnit I J b i j *ᵥ fun t => X t t) = _
  ext s t
  rw [Matrix.sum_apply]
  simp only [single_apply]
  by_cases hst : s = t
  · subst hst
    rw [diagonal_apply_eq]
    by_cases h : ∃ r : J b, s = ⟨b, (i, r)⟩
    · obtain ⟨r, rfl⟩ := h
      rw [Finset.sum_eq_single r]
      · simp only [and_self, if_true, mulVec, dotProduct]
        rw [Finset.sum_eq_single ⟨b, (j, r)⟩]
        · rw [blockUnit_apply_mk, one_mul]
        · intro t _ ht
          rw [blockUnit_apply_of_not, zero_mul]
          rintro ⟨r', h1, rfl⟩
          rw [sigma_mk_eq_mk_iff] at h1
          exact ht (by rw [h1.2])
        · simp
      · intro r' _ hr'
        rw [if_neg]
        rintro ⟨h1, -⟩
        rw [sigma_mk_eq_mk_iff] at h1
        exact hr' h1.2
      · simp
    · rw [Finset.sum_eq_zero fun r _ => if_neg fun h1 => h ⟨r, h1.1.symm⟩]
      simp only [mulVec, dotProduct]
      refine Finset.sum_eq_zero fun t _ => ?_
      rw [blockUnit_apply_of_not, zero_mul]
      rintro ⟨r, h1, -⟩
      exact h ⟨r, h1⟩
  · rw [diagonal_apply_ne _ hst]
    refine (Finset.sum_eq_zero fun r _ => ?_).symm
    rw [if_neg]
    rintro ⟨h1, h2⟩
    exact hst (h1.symm.trans h2)

variable {I J}

theorem realizationMatrix_apply_eq_zero_or_one (γ) (s t : Σ b, I b × J b) :
    realizationMatrix I J γ s t = 0 ∨ realizationMatrix I J γ s t = 1 := by
  rcases γ with ⟨b, i, j⟩ | ⟨b, i, j⟩
  · exact blockUnit_apply_eq_zero_or_one b i j s t
  · change (1 - blockUnit I J b j j) s t = 0 ∨ (1 - blockUnit I J b j j) s t = 1
    rw [Matrix.sub_apply]
    by_cases hst : s = t
    · subst hst
      rw [one_apply_eq]
      rcases blockUnit_apply_eq_zero_or_one b j j s s with h | h <;> rw [h] <;> norm_num
    · rw [one_apply_ne hst, blockUnit_apply_of_not, sub_zero]
      · exact Or.inl rfl
      · rintro ⟨r, rfl, rfl⟩
        exact hst rfl

/-- The realization transition matrices are partial permutations: at most one nonzero entry
in each column and in each row. -/
theorem realizationMatrix_partialPerm (γ) :
    (∀ i i' j, realizationMatrix I J γ i j ≠ 0 → realizationMatrix I J γ i' j ≠ 0 → i = i') ∧
    (∀ i j j', realizationMatrix I J γ i j ≠ 0 → realizationMatrix I J γ i j' ≠ 0 → j = j') := by
  rcases γ with ⟨b, i, j⟩ | ⟨b, i, j⟩
  · change (∀ s s' t, blockUnit I J b i j s t ≠ 0 → blockUnit I J b i j s' t ≠ 0 → s = s') ∧
      (∀ s t t', blockUnit I J b i j s t ≠ 0 → blockUnit I J b i j s t' ≠ 0 → t = t')
    constructor
    · intro s s' t h1 h2
      obtain ⟨r, rfl, rfl⟩ := exists_of_blockUnit_ne_zero h1
      obtain ⟨r', rfl, h3⟩ := exists_of_blockUnit_ne_zero h2
      rw [sigma_mk_eq_mk_iff] at h3
      rw [h3.2]
    · intro s t t' h1 h2
      obtain ⟨r, rfl, rfl⟩ := exists_of_blockUnit_ne_zero h1
      obtain ⟨r', h3, rfl⟩ := exists_of_blockUnit_ne_zero h2
      rw [sigma_mk_eq_mk_iff] at h3
      rw [h3.2]
  · have hdiag : ∀ s t, (1 - blockUnit I J b j j) s t ≠ 0 → s = t := by
      intro s t h
      by_contra hst
      apply h
      rw [Matrix.sub_apply, one_apply_ne hst, blockUnit_apply_of_not, sub_zero]
      rintro ⟨r, rfl, rfl⟩
      exact hst rfl
    change (∀ s s' t, (1 - blockUnit I J b j j) s t ≠ 0 → (1 - blockUnit I J b j j) s' t ≠ 0 →
      s = s') ∧ (∀ s t t', (1 - blockUnit I J b j j) s t ≠ 0 →
        (1 - blockUnit I J b j j) s t' ≠ 0 → t = t')
    exact ⟨fun s s' t h1 h2 => (hdiag s t h1).trans (hdiag s' t h2).symm,
      fun s t t' h1 h2 => (hdiag s t h1).symm.trans (hdiag s t' h2)⟩

theorem realizationMatrix_col_sum (β : Σ b, I b × I b) (t : Σ b, I b × J b) :
    ∑ s, (realizationMatrix I J (Sum.inl β) + realizationMatrix I J (Sum.inr β)) s t = 1 := by
  obtain ⟨b, i, j⟩ := β
  change ∑ s, (blockUnit I J b i j + (1 - blockUnit I J b j j)) s t = 1
  simp only [Matrix.add_apply, Matrix.sub_apply, Finset.sum_add_distrib, Finset.sum_sub_distrib,
    sum_blockUnit_col b i j j t]
  simp [one_apply]

/-- The algebra generated by the realization transition matrices is the block algebra
`⊕_λ M_{n_λ}(ℂ) ⊗ I_{m_λ}`. -/
theorem adjoin_realizationMatrix :
    StarAlgebra.adjoin ℂ (Set.range (realizationMatrix I J)) = (blockHom I J).range := by
  apply le_antisymm
  · refine StarAlgebra.adjoin_le ?_
    rintro _ ⟨γ, rfl⟩
    rcases γ with ⟨b, i, j⟩ | ⟨b, i, j⟩
    · exact ⟨Pi.single b (Matrix.single i j 1), rfl⟩
    · refine ⟨1 - Pi.single b (Matrix.single j j 1), ?_⟩
      rw [map_sub, map_one]
      rfl
  · rintro _ ⟨X, rfl⟩
    change blockHom I J X ∈ _
    rw [blockHom_eq_sum]
    refine Subalgebra.sum_mem _ fun b _ => Subalgebra.sum_mem _ fun i _ =>
      Subalgebra.sum_mem _ fun j _ => Subalgebra.smul_mem _ ?_ _
    exact StarAlgebra.subset_adjoin ℂ _ ⟨Sum.inl ⟨b, (i, j)⟩, rfl⟩

theorem hsInner_single_single {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (i j : Ω) :
    hsInner (Matrix.single i i (1 : ℂ)) (Matrix.single j j 1) = if i = j then 1 else 0 := by
  rw [hsInner, conjTranspose_single, star_one]
  by_cases h : i = j
  · subst h; simp
  · rw [single_mul_single_of_ne (h := h), trace_zero, if_neg h]

theorem trace_single_mul_single {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (i j : Ω) :
    (Matrix.single i i (1 : ℂ) * Matrix.single j j 1).trace = if i = j then 1 else 0 := by
  have := hsInner_single_single i j
  rwa [hsInner, conjTranspose_single, star_one] at this

theorem single_posSemidef {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (s : Ω) :
    (Matrix.single s s (1 : ℂ)).PosSemidef := by
  rw [← diagonal_single]
  refine PosSemidef.diagonal fun t => ?_
  by_cases h : t = s
  · subst h; simp
  · simp [Pi.single_apply, h]

theorem one_sub_single_posSemidef {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (s : Ω) :
    (1 - Matrix.single s s (1 : ℂ)).PosSemidef := by
  rw [← diagonal_single, ← diagonal_one, diagonal_sub]
  refine PosSemidef.diagonal fun t => ?_
  by_cases h : t = s
  · subst h; simp
  · simp [Pi.single_apply, h]

/-- The realization scheme is a valid finite operational scheme. -/
theorem realizationScheme_isValid : (realizationScheme I J).IsValid := by
  have hw : ∀ γ, ∃ w : _ → _ → ℝ, (∀ s t, 0 ≤ w s t) ∧
      ∀ s t, realizationMatrix I J γ s t = w s t := by
    intro γ
    refine ⟨fun s t => (realizationMatrix I J γ s t).re, fun s t => ?_, fun s t => ?_⟩
    · show 0 ≤ (realizationMatrix I J γ s t).re
      rcases realizationMatrix_apply_eq_zero_or_one γ s t with h | h <;> simp [h]
    · show realizationMatrix I J γ s t = ((realizationMatrix I J γ s t).re : ℂ)
      rcases realizationMatrix_apply_eq_zero_or_one γ s t with h | h <;> simp [h]
  have hcp : ∀ γ, IsKrausCP (diagSuperop (realizationMatrix I J γ)) := by
    intro γ
    obtain ⟨w, hw0, hwA⟩ := hw γ
    exact ⟨_, inferInstance, _, diagSuperop_eq_krausMap _ w hw0 hwA⟩
  refine ⟨fun s => ⟨single_posSemidef s, trace_single_eq_same _ _⟩,
    fun s => ⟨single_posSemidef s, one_sub_single_posSemidef s⟩,
    fun β => hcp (Sum.inl β), fun β => hcp (Sum.inr β), fun β X => ?_⟩
  change (diagSuperop (realizationMatrix I J (Sum.inl β)) X +
    diagSuperop (realizationMatrix I J (Sum.inr β)) X).trace = X.trace
  rw [trace_add, trace_diagSuperop, trace_diagSuperop, ← Finset.sum_add_distrib, trace]
  refine Finset.sum_congr rfl fun t _ => ?_
  rw [← add_mul, ← Finset.sum_add_distrib]
  have := realizationMatrix_col_sum β t
  simp only [Matrix.add_apply] at this
  rw [this, one_mul]
  rfl

/-- The represented range condition of the realization: if `W` carries `π(A)` onto the block
algebra, then `W (⊕ M_{n_λ} ⊗ I) Wᴴ = π(A)`, the block algebra being generated by the
realization transition matrices. -/
theorem realization_image_eq_range {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ)
    (W : Matrix n (Σ b, I b × J b) ℂ) (hW2 : W * Wᴴ = 1)
    (hWed : (fun x => Wᴴ * x * W) '' Set.range π = actionBlockSet I J) :
    (fun x => W * x * Wᴴ) '' (StarAlgebra.adjoin ℂ (Set.range (realizationMatrix I J)) :
      Set (Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ)) = Set.range π := by
  have hcoe : (((blockHom I J).range : StarSubalgebra ℂ _) : Set _) =
      Set.range (blockHom I J) := by
    ext x
    exact Iff.rfl
  have hid : ∀ y : Matrix n n ℂ, W * (Wᴴ * y * W) * Wᴴ = y := by
    intro y
    simp only [← Matrix.mul_assoc, hW2, Matrix.one_mul]
    rw [Matrix.mul_assoc, hW2, Matrix.mul_one]
  rw [adjoin_realizationMatrix, hcoe, range_blockHom, ← hWed, Set.image_image]
  simp only [hid, Set.image_id']

/-- The realization preparations and branches act on the diagonal frame by the transition
matrices, and the Hilbert–Schmidt adjoints by their conjugate transposes. -/
theorem realizationScheme_branch_prep (γ) (j : Σ b, I b × J b) :
    (realizationScheme I J).branch γ ((realizationScheme I J).prep j) =
      ∑ i, realizationMatrix I J γ i j • (realizationScheme I J).prep i := by
  rw [realizationScheme_branch]
  exact diagSuperop_single _ j

theorem realizationScheme_adjoint (γ) :
    ∃ Ψ : Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ →ₗ[ℂ]
        Matrix (Σ b, I b × J b) (Σ b, I b × J b) ℂ,
      (∀ X Y, hsInner Y ((realizationScheme I J).branch γ X) = hsInner (Ψ Y) X) ∧
      ∀ j, Ψ ((realizationScheme I J).prep j) =
        ∑ i, star (realizationMatrix I J γ j i) • (realizationScheme I J).prep i := by
  refine ⟨diagSuperop (realizationMatrix I J γ)ᴴ, fun X Y => ?_, fun j => ?_⟩
  · rw [realizationScheme_branch, hsInner_diagSuperop]
  · change diagSuperop _ (Matrix.single j j 1) =
      ∑ i, star (realizationMatrix I J γ j i) • Matrix.single i i 1
    rw [diagSuperop_single]
    simp only [conjTranspose_apply]

/-- **Realization from a Wedderburn form.**  If a unitary `W` carries `π(A)` onto the block
algebra `⊕_λ M_{n_λ}(ℂ) ⊗ I_{m_λ}`, the realization scheme realizes `π`. -/
theorem realizationScheme_realizesRep {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ)
    (hπ : Function.Injective π) (W : Matrix n (Σ b, I b × J b) ℂ) (hW1 : Wᴴ * W = 1)
    (hW2 : W * Wᴴ = 1)
    (hWed : (fun x => Wᴴ * x * W) '' Set.range π = actionBlockSet I J) :
    (realizationScheme I J).RealizesRep π :=
  (realizationScheme I J).realizesRep_of_frame π hπ
    (fun i j => hsInner_single_single i j) (fun i j => trace_single_mul_single i j)
    (realizationMatrix I J) realizationScheme_branch_prep realizationScheme_adjoint W hW1 hW2
    (realization_image_eq_range π W hW2 hWed)

end Realization

/-- Unitarily equivalent finite index sets have the same cardinality. -/
theorem card_eq_of_unitary {n ι : Type*} [Fintype n] [Fintype ι] [DecidableEq n] [DecidableEq ι]
    (W : Matrix n ι ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1) :
    Fintype.card ι = Fintype.card n := by
  let e : (ι → ℂ) ≃ₗ[ℂ] (n → ℂ) :=
    LinearEquiv.ofLinear W.mulVecLin Wᴴ.mulVecLin
      (LinearMap.ext fun v => by simp [mulVec_mulVec, hW2])
      (LinearMap.ext fun v => by simp [mulVec_mulVec, hW1])
  have := e.finrank_eq
  rwa [Module.finrank_fintype_fun_eq_card, Module.finrank_fintype_fun_eq_card] at this

/-- The reindexed representation `a ↦ reindex e (π a)`. -/
def reindexRep {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A] {n m : Type*} [Fintype n]
    [DecidableEq n] [Fintype m] [DecidableEq m] (π : A →⋆ₐ[ℂ] Matrix n n ℂ) (e : n ≃ m) :
    A →⋆ₐ[ℂ] Matrix m m ℂ :=
  { (Matrix.reindexAlgEquiv ℂ ℂ e).toAlgHom.comp π.toAlgHom with
    map_star' := fun a => by
      change reindex e e (π (star a)) = (reindex e e (π a))ᴴ
      rw [map_star, conjTranspose_reindex]
      rfl }

/-- **Wedderburn block form of a faithful representation** (any universe for the carrier
index): a unitary `W : ℂ^{⊕_λ n_λ × m_λ} → ℂ^n` with `Wᴴ π(A) W = ⊕_λ M_{n_λ}(ℂ) ⊗ I_{m_λ}`
(from `reciprocal_wedderburn` after reindexing by `n ≃ Fin |n|`). -/
theorem exists_wedderburn_blockForm {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ) :
    ∃ (ι : Type) (_ : Fintype ι) (_ : DecidableEq ι) (I J : ι → Type)
      (_ : ∀ b, Fintype (I b)) (_ : ∀ b, DecidableEq (I b))
      (_ : ∀ b, Fintype (J b)) (_ : ∀ b, DecidableEq (J b))
      (W : Matrix n (Σ b, I b × J b) ℂ), Wᴴ * W = 1 ∧ W * Wᴴ = 1 ∧
        (fun x => Wᴴ * x * W) '' Set.range π = actionBlockSet I J := by
  classical
  let e := Fintype.equivFin n
  let π' := reindexRep π e
  obtain ⟨ι, hι, hιd, I, J, hIf, hId, hJf, hJd, W0, h1, h2, -, -, hWed, -⟩ :=
    reciprocal_wedderburn π'.range.toSubalgebra fun a ha => star_mem (s := π'.range) ha
  refine ⟨ι, hι, hιd, I, J, hIf, hId, hJf, hJd, W0.submatrix e id, ?_, ?_, ?_⟩
  · rw [conjTranspose_submatrix, ← submatrix_mul _ _ _ _ _ e.bijective, h1, submatrix_id_id]
  · rw [conjTranspose_submatrix, ← submatrix_mul _ _ _ _ _ Function.bijective_id, h2,
      submatrix_one_equiv]
  · have hconj : ∀ y : Matrix n n ℂ, (W0.submatrix e id)ᴴ * y * W0.submatrix e id =
        W0ᴴ * reindex e e y * W0 := by
      intro y
      have hy : y = (reindex e e y).submatrix e e := by
        ext i j
        simp
      conv_lhs => rw [hy]
      rw [conjTranspose_submatrix, ← submatrix_mul _ _ _ _ _ e.bijective,
        ← submatrix_mul _ _ _ _ _ e.bijective, submatrix_id_id]
    have hcoe : ((π'.range : StarSubalgebra ℂ _) : Set (Matrix (Fin (Fintype.card n))
        (Fin (Fintype.card n)) ℂ)) = Set.range π' := by
      ext x
      exact Iff.rfl
    have hWed' : (fun x => W0ᴴ * x * W0) '' Set.range π' = actionBlockSet I J := by
      rw [← hcoe]
      exact hWed
    rw [← hWed', ← Set.range_comp, ← Set.range_comp]
    congr 1
    funext a
    exact hconj (π a)

/-- **Theorem `thm:ncg-operational-realization` (finite operational realization with
multiplicities).**  For every faithful unital star representation `π : A → M_n(ℂ)` (so `A` is a
finite-dimensional C*-algebra) there are a finite physical memory `ℂ^Ω` with `|Ω| = n`, a finite
family of normalized completely positive two-outcome instruments, boundary preparations and
terminal readouts (a valid `Scheme`) whose future-separated source representation is
unitarily equivalent to `(A, ℂ^n, π)` (`Scheme.RealizesRep`); in particular all representation
multiplicities are preserved. -/
theorem operational_realization {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ)
    (hπ : Function.Injective π) :
    ∃ (Ω : Type) (_ : Fintype Ω) (_ : DecidableEq Ω) (Br : Type) (_ : Fintype Br)
      (S : Scheme Ω Ω Br), S.IsValid ∧ Fintype.card Ω = Fintype.card n ∧ S.RealizesRep π := by
  classical
  obtain ⟨ι, hι, hιd, I, J, hIf, hId, hJf, hJd, W, hW1, hW2, hWed⟩ :=
    exists_wedderburn_blockForm π
  exact ⟨_, inferInstance, inferInstance, _, inferInstance, realizationScheme I J,
    realizationScheme_isValid, card_eq_of_unitary W hW1 hW2,
    realizationScheme_realizesRep π hπ W hW1 hW2 hWed⟩

/-! ### Recognition from the one-step panel -/

section Recognition

/-- The Hilbert–Schmidt overlap of two rank-one projectors: `⟪|a⟩⟨a|, |b⟩⟨b|⟫ = |⟨a, b⟩|²`. -/
theorem hsInner_vecMulVec_self {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (a b : Ω → ℂ) :
    hsInner (vecMulVec a (star a)) (vecMulVec b (star b)) =
      (star a ⬝ᵥ b) * star (star a ⬝ᵥ b) := by
  rw [hsInner_eq_dotProduct]
  simp only [dotProduct, vecHS, vecMulVec_apply, Pi.star_apply, Fintype.sum_prod_type,
    star_mul', star_star, star_sum, Finset.sum_mul, Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun p _ => Finset.sum_congr rfl fun q _ => by ring

/-- `Tr(|a⟩⟨a| M) = ⟨a, M a⟩`. -/
theorem trace_vecMulVec_mul {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (a : Ω → ℂ)
    (M : Matrix Ω Ω ℂ) : (vecMulVec a (star a) * M).trace = star a ⬝ᵥ (M *ᵥ a) := by
  simp only [trace, diag, Matrix.mul_apply, vecMulVec_apply, dotProduct, mulVec, Pi.star_apply,
    Finset.mul_sum]
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun p _ => Finset.sum_congr rfl fun q _ => by ring

/-- The Hilbert–Schmidt inner product is linear in its second argument on finite sums. -/
theorem hsInner_sum_smul {Ω ι : Type*} [Fintype Ω] [Fintype ι] (X : Matrix Ω Ω ℂ)
    (c : ι → ℂ) (Y : ι → Matrix Ω Ω ℂ) :
    hsInner X (∑ i, c i • Y i) = ∑ i, c i * hsInner X (Y i) := by
  simp [hsInner, Matrix.mul_sum, trace_sum, Matrix.mul_smul, trace_smul]

variable {Ω ι Br : Type*} [Fintype Ω] [DecidableEq Ω] [Fintype ι] [DecidableEq ι]

/-- At minimal memory dimension the readouts coincide with the preparations:
perfect discrimination of `|Ω|` states on `ℂ^Ω` forces `E_i = ρ_i`. -/
theorem eff_eq_prep_of_card_eq (S : Scheme Ω ι Br) (hS : S.IsValid)
    (hdisc : ∀ i j, (S.eff i * S.prep j).trace = if i = j then 1 else 0)
    (hcard : Fintype.card ι = Fintype.card Ω) (i : ι) : S.eff i = S.prep i := by
  classical
  obtain ⟨e, hρ, he⟩ := RankOneForcing.exists_orthonormal_of_card_eq hS.prep_isDensity
    hS.eff_isEffect hdisc hcard
  have hsum : ∑ j, S.prep j = 1 := by
    have h := RankOneForcing.eq_sum_of_offDiag_eq_zero he hcard (M := 1) (fun j k hjk => by
      rw [one_mulVec, he, if_neg hjk])
    rw [h]
    refine Finset.sum_congr rfl fun j _ => ?_
    rw [one_mulVec, he, if_pos rfl, one_smul, hρ]
  have hoff : ∀ j, j ≠ i → S.eff i * S.prep j = 0 := fun j hj =>
    (RankOneForcing.trace_mul_eq_zero_iff (hS.eff_isEffect i).1 (hS.prep_isDensity j).1).1
      (by rw [hdisc, if_neg (Ne.symm hj)])
  have hdiag : S.eff i * S.prep i = S.prep i := by
    have h0 : (1 - S.eff i) * S.prep i = 0 := by
      refine (RankOneForcing.trace_mul_eq_zero_iff (hS.eff_isEffect i).2
        (hS.prep_isDensity i).1).1 ?_
      rw [Matrix.sub_mul, Matrix.one_mul, trace_sub, hdisc, if_pos rfl,
        (hS.prep_isDensity i).2, sub_self]
    rw [Matrix.sub_mul, Matrix.one_mul, sub_eq_zero] at h0
    exact h0.symm
  calc S.eff i = S.eff i * ∑ j, S.prep j := by rw [hsum, Matrix.mul_one]
    _ = ∑ j, S.eff i * S.prep j := by rw [Matrix.mul_sum]
    _ = S.eff i * S.prep i := by
      rw [Finset.sum_eq_single i (fun j _ hj => hoff j hj) (by simp)]
    _ = S.prep i := hdiag

theorem Scheme.branch_isKrausCP (S : Scheme Ω ι Br) (hS : S.IsValid) (γ : Br ⊕ Br) :
    IsKrausCP (S.branch γ) := by
  rcases γ with β | β
  · exact hS.succ_cp β
  · exact hS.fail_cp β

/-- **Recognition at minimal memory dimension** (`prop:ncg-operational-recognition`, frame
step).  Let a valid scheme on `ℂ^Ω` have `|Ω| = |ι|` perfectly discriminated preparations,
and let its one-step transition probabilities `Tr(E_i Φ_γ(ρ_j))` form real partial-permutation
matrices `A_γ`.  Then the preparations form a Hilbert–Schmidt orthonormal frame, every branch
acts on it by `A_γ` and its Hilbert–Schmidt adjoint by `A_γᴴ` (`lem:ncg-rank-one-forcing`). -/
theorem frame_data_of_card_eq (S : Scheme Ω ι Br) (hS : S.IsValid)
    (hdisc : ∀ i j, (S.eff i * S.prep j).trace = if i = j then 1 else 0)
    (hcard : Fintype.card ι = Fintype.card Ω) (Am : Br ⊕ Br → Matrix ι ι ℂ)
    (hreal : ∀ γ i j, Am γ i j = ((Am γ i j).re : ℂ))
    (hperm : ∀ γ, (∀ i i' j, Am γ i j ≠ 0 → Am γ i' j ≠ 0 → i = i') ∧
      (∀ i j j', Am γ i j ≠ 0 → Am γ i j' ≠ 0 → j = j'))
    (htrans : ∀ γ i j, (S.eff i * S.branch γ (S.prep j)).trace = Am γ i j) :
    (∀ i j, hsInner (S.prep i) (S.prep j) = if i = j then 1 else 0) ∧
    (∀ γ j, S.branch γ (S.prep j) = ∑ i, Am γ i j • S.prep i) ∧
    (∀ γ, ∃ Ψ : Matrix Ω Ω ℂ →ₗ[ℂ] Matrix Ω Ω ℂ,
      (∀ X Y, hsInner Y (S.branch γ X) = hsInner (Ψ Y) X) ∧
      ∀ j, Ψ (S.prep j) = ∑ i, star (Am γ j i) • S.prep i) := by
  classical
  obtain ⟨e, hρ, he⟩ := RankOneForcing.exists_orthonormal_of_card_eq hS.prep_isDensity
    hS.eff_isEffect hdisc hcard
  have hON : ∀ i j, hsInner (S.prep i) (S.prep j) = if i = j then 1 else 0 := by
    intro i j
    rw [hρ, hρ, hsInner_vecMulVec_self, he]
    split_ifs <;> simp
  have hEρ := eff_eq_prep_of_card_eq S hS hdisc hcard
  -- forward action
  have hfwd : ∀ γ j, S.branch γ (S.prep j) = ∑ i, Am γ i j • S.prep i := by
    intro γ j
    obtain ⟨κ, _, W, hW⟩ := S.branch_isKrausCP hS γ
    set M := S.branch γ (S.prep j) with hMdef
    have hMpsd : M.PosSemidef := by
      rw [hMdef, hW]
      exact krausMap_posSemidef W (hS.prep_isDensity j).1
    have hcoef : ∀ i, star (e i) ⬝ᵥ (M *ᵥ e i) = Am γ i j := by
      intro i
      rw [← trace_vecMulVec_mul, ← hρ, ← hEρ, hMdef, htrans]
    have hkill : ∀ i, Am γ i j = 0 → M *ᵥ e i = 0 := fun i h0 =>
      (hMpsd.dotProduct_mulVec_zero_iff (e i)).1 (by rw [hcoef, h0])
    have hoff : ∀ a b, a ≠ b → star (e a) ⬝ᵥ (M *ᵥ e b) = 0 := by
      intro a b hab
      by_cases hb : Am γ b j = 0
      · rw [hkill b hb, dotProduct_zero]
      · have ha : Am γ a j = 0 := by
          by_contra ha
          exact hab ((hperm γ).1 a b j ha hb)
        have hherm : Mᴴ = M := hMpsd.isHermitian.eq
        have hv : star (e a) ᵥ* M = 0 := by
          have h := star_mulVec M (e a)
          rw [hherm, hkill a ha, star_zero] at h
          exact h.symm
        rw [dotProduct_mulVec, hv, zero_dotProduct]
    rw [RankOneForcing.eq_sum_of_offDiag_eq_zero he hcard hoff]
    refine Finset.sum_congr rfl fun i _ => ?_
    rw [hcoef, hρ]
  refine ⟨hON, hfwd, fun γ => ?_⟩
  -- adjoint action
  obtain ⟨κ, _, W, hW⟩ := S.branch_isKrausCP hS γ
  refine ⟨krausMap fun a => (W a)ᴴ, fun X Y => by rw [hW, hsInner_krausMap], fun j => ?_⟩
  -- the panel data for `lem:ncg-rank-one-forcing`
  let Jdom : Set ι := {j | ∃ i, Am γ i j ≠ 0}
  let σ : ι → ι := fun j => if h : ∃ i, Am γ i j ≠ 0 then h.choose else j
  have hσspec : ∀ j, (h : ∃ i, Am γ i j ≠ 0) → Am γ (σ j) j ≠ 0 := by
    intro j h
    simp only [σ, dif_pos h]
    exact h.choose_spec
  have hcol : ∀ j, (h : ∃ i, Am γ i j ≠ 0) → ∀ i, i ≠ σ j → Am γ i j = 0 := by
    intro j h i hi
    by_contra h0
    exact hi ((hperm γ).1 i (σ j) j h0 (hσspec j h))
  have hσinj : Set.InjOn σ Jdom := by
    intro j hj j' hj' hjj
    exact (hperm γ).2 (σ j) j j' (hσspec j hj) (hjj ▸ hσspec j' hj')
  have hpanel : ∀ j ∈ Jdom, krausMap W (vecMulVec (e j) (star (e j))) =
      ((Am γ (σ j) j).re : ℂ) • vecMulVec (e (σ j)) (star (e (σ j))) := by
    intro j hj
    rw [← hρ, ← hW, hfwd, Finset.sum_eq_single (σ j)]
    · rw [← hreal, hρ]
    · intro i _ hi
      rw [hcol j hj i hi, zero_smul]
    · simp
  have hnull : ∀ j ∉ Jdom, (krausMap W (vecMulVec (e j) (star (e j)))).trace = 0 := by
    intro j hj
    have hz : ∀ i, Am γ i j = 0 := fun i => by
      by_contra h0
      exact hj ⟨i, h0⟩
    rw [← hρ, ← hW, hfwd]
    simp [hz]
  obtain ⟨-, hadjinv⟩ := RankOneForcing.panel_invariant_kraus he hcard W Jdom σ hσinj
    (fun j => (Am γ (σ j) j).re) hpanel hnull
  have hspan : Submodule.span ℂ (Set.range fun j => vecMulVec (e j) (star (e j))) =
      Submodule.span ℂ (Set.range S.prep) := by
    rw [show (fun j => vecMulVec (e j) (star (e j))) = S.prep from funext fun j => (hρ j).symm]
  have hmem := hadjinv (S.prep j) (by
    rw [hspan]
    exact Submodule.subset_span ⟨j, rfl⟩)
  rw [hspan] at hmem
  obtain ⟨c, hc⟩ := (Submodule.mem_span_range_iff_exists_fun ℂ).1 hmem
  rw [← hc]
  refine Finset.sum_congr rfl fun k _ => ?_
  congr 1
  -- coefficient extraction
  have h1 : hsInner (S.prep k) (∑ i, c i • S.prep i) = c k := by
    rw [hsInner_sum_smul]
    simp [hON]
  have h2 : hsInner (S.prep k) (krausMap (fun a => (W a)ᴴ) (S.prep j)) = star (Am γ j k) := by
    rw [hsInner_conj_symm, ← hsInner_krausMap, ← hW, hfwd, hsInner_sum_smul]
    simp [hON]
  rw [← h1, hc, h2]

/-- The retained one-step panel of two schemes agree: the boundary discrimination table
`Tr(E_i ρ_j)` and all one-step success and failure transition probabilities
`Tr(E_i Φ_γ(ρ_j))` (including the zero probabilities outside each branch domain). -/
def Scheme.SamePanel {Ω' : Type*} [Fintype Ω'] [DecidableEq Ω'] (S' : Scheme Ω' ι Br)
    (S : Scheme Ω ι Br) : Prop :=
  (∀ i j, (S'.eff i * S'.prep j).trace = (S.eff i * S.prep j).trace) ∧
  ∀ γ i j, (S'.eff i * S'.branch γ (S'.prep j)).trace =
    (S.eff i * S.branch γ (S.prep j)).trace

/-- **Memory lower bound** (`eq:perfect-discrimination-rank`): a valid scheme with perfectly
discriminated preparations indexed by `ι` needs memory dimension at least `|ι|`. -/
theorem card_le_of_perfectDiscrimination (S : Scheme Ω ι Br) (hS : S.IsValid)
    (hdisc : ∀ i j, (S.eff i * S.prep j).trace = if i = j then 1 else 0) :
    Fintype.card ι ≤ Fintype.card Ω := by
  have h1 := RankOneForcing.sum_rank_le_card hS.prep_isDensity hS.eff_isEffect hdisc
  have h2 : ∑ _j : ι, 1 ≤ ∑ j, (S.prep j).rank :=
    Finset.sum_le_sum fun j _ => RankOneForcing.rank_pos_of_isDensity (hS.prep_isDensity j)
  simp only [Finset.sum_const, Finset.card_univ, smul_eq_mul, mul_one] at h2
  omega

end Recognition

theorem trace_single_mul_sum_smul_single {Ω : Type*} [Fintype Ω] [DecidableEq Ω] (i : Ω)
    (c : Ω → ℂ) :
    (Matrix.single i i (1 : ℂ) * ∑ k, c k • Matrix.single k k 1).trace = c i := by
  rw [Matrix.mul_sum, trace_sum]
  simp_rw [Matrix.mul_smul, trace_smul, trace_single_mul_single, smul_eq_mul, mul_ite, mul_one,
    mul_zero]
  simp

/-- **Proposition `prop:ncg-operational-recognition` (finite recognition from the one-step
panel).**  For every faithful unital star representation `π : A → M_n(ℂ)` the realization
scheme `S` of `thm:ncg-operational-realization` (memory dimension `n`) has the following
property: every valid scheme `S'` (any finite memory `ℂ^{Ω'}`) reproducing the retained panel
of `S` — the perfect boundary discrimination table and all one-step success and complementary
failure transition probabilities, including the zero probabilities outside the branch
domains — has memory dimension at least `n`, and if its memory dimension is minimal
(`= n`), its future-separated source representation is unitarily equivalent to `(A, ℂ^n, π)`. -/
theorem operational_recognition {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {n : Type*} [Fintype n] [DecidableEq n] (π : A →⋆ₐ[ℂ] Matrix n n ℂ)
    (hπ : Function.Injective π) :
    ∃ (Ω : Type) (_ : Fintype Ω) (_ : DecidableEq Ω) (Br : Type) (_ : Fintype Br)
      (S : Scheme Ω Ω Br), S.IsValid ∧ Fintype.card Ω = Fintype.card n ∧ S.RealizesRep π ∧
      ∀ (Ω' : Type*) [Fintype Ω'] [DecidableEq Ω'] (S' : Scheme Ω' Ω Br),
        S'.IsValid → S'.SamePanel S →
          Fintype.card n ≤ Fintype.card Ω' ∧
          (Fintype.card Ω' = Fintype.card n → S'.RealizesRep π) := by
  classical
  obtain ⟨ι, hι, hιd, I, J, hIf, hId, hJf, hJd, W, hW1, hW2, hWed'⟩ :=
    exists_wedderburn_blockForm π
  have hcardΩ := card_eq_of_unitary W hW1 hW2
  refine ⟨_, inferInstance, inferInstance, _, inferInstance, realizationScheme I J,
    realizationScheme_isValid, hcardΩ, realizationScheme_realizesRep π hπ W hW1 hW2 hWed', ?_⟩
  intro Ω' _ _ S' hS' hpanel
  have hdisc' : ∀ i j, (S'.eff i * S'.prep j).trace = if i = j then 1 else 0 := fun i j => by
    rw [hpanel.1]
    exact trace_single_mul_single i j
  have htrans : ∀ γ i j, (S'.eff i * S'.branch γ (S'.prep j)).trace =
      realizationMatrix I J γ i j := by
    intro γ i j
    rw [hpanel.2, realizationScheme_branch_prep]
    exact trace_single_mul_sum_smul_single i _
  refine ⟨hcardΩ ▸ card_le_of_perfectDiscrimination S' hS' hdisc', fun hcard => ?_⟩
  obtain ⟨hON, hfwd, hadj⟩ := frame_data_of_card_eq S' hS' hdisc' (hcardΩ.trans hcard.symm)
    (realizationMatrix I J)
    (fun γ i j => by
      rcases realizationMatrix_apply_eq_zero_or_one γ i j with h | h <;> simp [h])
    realizationMatrix_partialPerm htrans
  exact S'.realizesRep_of_frame π hπ hON hdisc' (realizationMatrix I J) hfwd hadj W hW1 hW2
    (realization_image_eq_range π W hW2 hWed')

/-! ### Calibrated marked triples (`cor:ncg-operational-calibrated-triples`) -/

section Calibrated

open MarkedCommutantCoordinates MarkedCommutantCoordinates.MarkedFiniteSpectralTriple

/-- **Corollary `cor:ncg-operational-calibrated-triples`.**  For every finite marked spectral
triple `𝖲 = (𝒜, ℂ^K, π, D, J, γ; 𝔪)`:

1. its represented algebra component `π(𝒜) ⊆ M_K(ℂ)` (faithfully and unitally represented by
   inclusion) admits the operational realization of `thm:ncg-operational-realization`: a
   valid finite scheme with memory dimension `|K|` whose future-separated source
   representation is unitarily equivalent to the inclusion `π(𝒜) ↪ M_K(ℂ)`;
2. after independently supplying the commutator derivation and declared marks (the
   compatible implementers `X`, `IsCompatibleImplementer`) and the sharp real-linear
   commutant coordinates of `thm:commutant-fibre` — `q_S` Hilbert–Schmidt-orthonormal
   commutant coordinates exist, any injective real-linear coordinate map on `c_S` works, and
   fewer than `q_S` coordinates never suffice — the full compatible Dirac operator `D` is
   reconstructed.

The disclaimer sentence of the corollary (no claim that operational probabilities alone
determine `D`) carries no mathematical content. -/
theorem operational_calibrated_triples {A : Type*} [Ring A] [StarRing A] [Algebra ℂ A]
    {K : Type*} [Fintype K] [DecidableEq K] {ι : Type*}
    (S : MarkedFiniteSpectralTriple A K ι) :
    (∃ (Ω : Type) (_ : Fintype Ω) (_ : DecidableEq Ω) (Br : Type) (_ : Fintype Br)
      (Sc : Scheme Ω Ω Br), Sc.IsValid ∧ Fintype.card Ω = Fintype.card K ∧
        Sc.RealizesRep S.rep.range.subtype) ∧
    (∃ C : Fin S.commutantDim → Matrix K K ℂ, (∀ j, C j ∈ S.commutantSpace) ∧
      ∀ i j, MarkedCommutantCoordinates.hsInner (C i) (C j) = if i = j then 1 else 0) ∧
    (∀ C : Fin S.commutantDim → Matrix K K ℂ, (∀ j, C j ∈ S.commutantSpace) →
      (∀ i j, MarkedCommutantCoordinates.hsInner (C i) (C j) = if i = j then 1 else 0) →
      ∀ X, S.IsCompatibleImplementer X →
        (∀ j, MarkedCommutantCoordinates.hsInner (C j) X =
          MarkedCommutantCoordinates.hsInner (C j) S.dirac) → X = S.dirac) ∧
    (∀ (m : ℕ) (α : S.CommutantCoordinateMap m), Function.Injective α →
      ∀ X, S.IsCompatibleImplementer X →
        α (S.commutantProjectionMem X) = α (S.commutantProjectionMem S.dirac) →
        X = S.dirac) ∧
    (∀ (m : ℕ) (α : S.CommutantCoordinateMap m), m < S.commutantDim →
      ∃ X, S.IsCompatibleImplementer X ∧ X ≠ S.dirac ∧
        α (S.commutantProjectionMem X) = α (S.commutantProjectionMem S.dirac)) := by
  obtain ⟨-, -, -, -, h5, h6, h7, h8, -, -⟩ := S.commutant_fibre
  exact ⟨operational_realization S.rep.range.subtype Subtype.val_injective, h6,
    fun C hC hon => (h5 C hC hon).2, h7, h8⟩

/-- Non-vacuity witness: the trivial one-dimensional marked triple satisfies the corollary. -/
example : ∃ (Ω : Type) (_ : Fintype Ω) (_ : DecidableEq Ω) (Br : Type) (_ : Fintype Br)
    (Sc : Scheme Ω Ω Br), Sc.IsValid ∧ Fintype.card Ω = 1 ∧
      Sc.RealizesRep trivialMarkedFiniteSpectralTriple.rep.range.subtype :=
  (operational_calibrated_triples trivialMarkedFiniteSpectralTriple).1

end Calibrated

end OperationalRealization
end RenewalGeometry
