/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The environment coefficient algebra and the canonical pointer instrument

Definition `def:environment-coefficient-algebra`, Proposition
`prop:interaction-algebra-minimal` and the instrument identity of
Theorem `thm:canonical-pointer-instrument` from
`manuscripts/renewal_emergence/renewal_emergence.tex`, in the finite-dimensional matrix model
`𝔅(P ⊗ E) = Matrix (P × E) (P × E) ℂ`.

* `slice a b H` — the operator-Schmidt coefficient
  `h_{ab} = (ω_{ba} ⊗ id)(H)`;
* `coeffAlgebra H` — the environment coefficient algebra
  `𝒞_E(ℋ)`, the star-subalgebra generated by all slices;
* `sum_ptensor_slice` — the block decomposition
  `H = ∑_{ab} e_{ab} ⊗ h_{ab}`;
* `mem_tensorSpan_iff_slice` — `H ∈ 𝔅(P) ⊗ 𝒞` iff every slice lies
  in `𝒞`;
* `coeffAlgebra_minimal` — **minimality**: `𝒞_E(ℋ)` is the smallest
  subalgebra `𝒞` with every `H_ν ∈ 𝔅(P) ⊗ 𝒞`; in particular it is
  independent of probe bases, Schmidt decompositions, and generating
  lists;
* `commute_onePE_iff_slice` / `mem_stable_iff_commute` — the boxed
  **nondemolition characterization**:
  `X ∈ ℱ_E = 𝒞_E(ℋ)' ⟺ [1_P ⊗ X, H_ν] = 0` for all `ν`;
* `ptrace_compress` / `pointer_instrument_sum` /
  `pointer_offdiag_vanish` — the **canonical pointer instrument**:
  for any family of idempotents summing to one,
  `∑_α Tr_E[(1⊗z_α) M (1⊗z_α)] = Tr_E M`, and cross-compressions
  have vanishing partial trace; applied to `M = VρV*` this is
  `∑_α ℐ_α = Φ` of `thm:canonical-pointer-instrument`.
-/

namespace NCG.Upstream

open Kronecker Matrix

variable {P E : Type*} [Fintype P] [Fintype E]
variable [DecidableEq P] [DecidableEq E]

/-- The operator-Schmidt slice `h_{ab} = (ω_{ba} ⊗ id_E)(H)`. -/
def slice (a b : P) (H : Matrix (P × E) (P × E) ℂ) :
    Matrix E E ℂ :=
  Matrix.of fun c d => H (a, c) (b, d)

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
@[simp] theorem slice_apply (a b : P) (H : Matrix (P × E) (P × E) ℂ)
    (c d : E) : slice a b H c d = H (a, c) (b, d) := rfl

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
theorem slice_add (a b : P) (H K : Matrix (P × E) (P × E) ℂ) :
    slice a b (H + K) = slice a b H + slice a b K := by
  ext c d
  simp [slice]

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
theorem slice_smul (a b : P) (t : ℂ) (H : Matrix (P × E) (P × E) ℂ) :
    slice a b (t • H) = t • slice a b H := by
  ext c d
  simp [slice]

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
theorem slice_zero (a b : P) :
    slice a b (0 : Matrix (P × E) (P × E) ℂ) = 0 := by
  ext c d
  simp [slice]

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
/-- Slices of a Kronecker product. -/
theorem slice_kronecker (a b : P) (M : Matrix P P ℂ)
    (X : Matrix E E ℂ) : slice a b (M ⊗ₖ X) = M a b • X := by
  ext c d
  simp [slice, Matrix.kroneckerMap_apply]

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
/-- Slices of a Hermitian interaction are conjugate-symmetric:
`(h_{ab})ᴴ = h_{ba}`. -/
theorem slice_conjTranspose (a b : P)
    (H : Matrix (P × E) (P × E) ℂ) :
    (slice a b H)ᴴ = slice b a Hᴴ := by
  ext c d
  simp [slice, Matrix.conjTranspose_apply]

omit [DecidableEq E] [Fintype E] in
/-- **Block decomposition** `H = ∑_{ab} e_{ab} ⊗ h_{ab}`: every
interaction is the sum of matrix units tensored with its slices. -/
theorem sum_ptensor_slice (H : Matrix (P × E) (P × E) ℂ) :
    ∑ a : P, ∑ b : P,
      (Matrix.single a b (1 : ℂ)) ⊗ₖ slice a b H = H := by
  ext ⟨p, c⟩ ⟨q, d⟩
  rw [Matrix.sum_apply, Finset.sum_eq_single p]
  · rw [Matrix.sum_apply, Finset.sum_eq_single q]
    · simp [Matrix.kroneckerMap_apply, Matrix.single]
    · intro b _ hb
      simp only [Matrix.kroneckerMap_apply, Matrix.single_apply,
        slice_apply]
      rw [if_neg (by
        rintro ⟨-, rfl⟩
        exact hb rfl), zero_mul]
    · intro hq
      exact absurd (Finset.mem_univ q) hq
  · intro a _ ha
    rw [Matrix.sum_apply]
    refine Finset.sum_eq_zero fun b _ => ?_
    simp only [Matrix.kroneckerMap_apply, Matrix.single_apply,
      slice_apply]
    rw [if_neg (by
      rintro ⟨rfl, -⟩
      exact ha rfl), zero_mul]
  · intro hp
    exact absurd (Finset.mem_univ p) hp

/-- The subspace `𝔅(P) ⊗ 𝒞` of interactions with coefficients in a
given set of environment operators. -/
def tensorSpan (C : Set (Matrix E E ℂ)) :
    Submodule ℂ (Matrix (P × E) (P × E) ℂ) :=
  Submodule.span ℂ
    {Y | ∃ M : Matrix P P ℂ, ∃ X ∈ C, Y = M ⊗ₖ X}

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
/-- **Membership in `𝔅(P) ⊗ 𝒞` is a slice condition**: for a
subalgebra-like set (a submodule of coefficients), `H ∈ 𝔅(P) ⊗ 𝒞`
iff every slice of `H` lies in `𝒞`. -/
theorem mem_tensorSpan_iff_slice [Finite P] [Finite E]
    (C : Submodule ℂ (Matrix E E ℂ))
    (H : Matrix (P × E) (P × E) ℂ) :
    H ∈ tensorSpan (P := P) (C : Set (Matrix E E ℂ))
      ↔ ∀ a b : P, slice a b H ∈ C := by
  classical
  cases nonempty_fintype P
  cases nonempty_fintype E
  constructor
  · intro hH
    induction hH using Submodule.span_induction with
    | mem Y hY =>
      obtain ⟨M, X, hX, rfl⟩ := hY
      intro a b
      rw [slice_kronecker]
      exact C.smul_mem _ hX
    | zero =>
      intro a b
      rw [slice_zero]
      exact C.zero_mem
    | add Y Z _ _ hY hZ =>
      intro a b
      rw [slice_add]
      exact C.add_mem (hY a b) (hZ a b)
    | smul t Y _ hY =>
      intro a b
      rw [slice_smul]
      exact C.smul_mem t (hY a b)
  · intro hs
    rw [← sum_ptensor_slice H]
    refine Submodule.sum_mem _ fun a _ => ?_
    refine Submodule.sum_mem _ fun b _ => ?_
    exact Submodule.subset_span
      ⟨Matrix.single a b 1, slice a b H, hs a b, rfl⟩

section CoeffAlgebra

variable {ι : Type*} (H : ι → Matrix (P × E) (P × E) ℂ)

/-- **Definition `def:environment-coefficient-algebra`**: the
environment coefficient algebra `𝒞_E(ℋ)` — the star-subalgebra of
`𝔅(E)` generated by all slices of the interaction family. -/
def coeffAlgebra : StarSubalgebra ℂ (Matrix E E ℂ) :=
  StarAlgebra.adjoin ℂ
    {X | ∃ (ν : ι) (a b : P), X = slice a b (H ν)}

omit [DecidableEq P] [Fintype P] in
theorem slice_mem_coeffAlgebra (ν : ι) (a b : P) :
    slice a b (H ν) ∈ coeffAlgebra H :=
  StarAlgebra.subset_adjoin ℂ _ ⟨ν, a, b, rfl⟩

omit [DecidableEq P] [Fintype P] in
/-- **Proposition `prop:interaction-algebra-minimal` (minimality)**:
`𝒞_E(ℋ)` is the smallest star-subalgebra `𝒞` such that every
interaction lies in `𝔅(P) ⊗ 𝒞`.  In particular it is independent of
the probe basis, the operator-Schmidt decomposition, and the
generating list. -/
theorem coeffAlgebra_minimal [Finite P] (C : StarSubalgebra ℂ (Matrix E E ℂ)) :
    (∀ ν, H ν ∈ tensorSpan (P := P) (C : Set (Matrix E E ℂ)))
      ↔ coeffAlgebra H ≤ C := by
  classical
  cases nonempty_fintype P
  constructor
  · intro hall
    rw [coeffAlgebra, StarAlgebra.adjoin_le_iff]
    rintro X ⟨ν, a, b, rfl⟩
    have h1 := (mem_tensorSpan_iff_slice
      (C := Subalgebra.toSubmodule C.toSubalgebra) (H ν)).mp
      (hall ν)
    exact h1 a b
  · intro hle ν
    refine (mem_tensorSpan_iff_slice
      (C := Subalgebra.toSubmodule C.toSubalgebra) (H ν)).mpr ?_
    intro a b
    exact hle (slice_mem_coeffAlgebra H ν a b)

end CoeffAlgebra

/-! ## The nondemolition characterization of the stable algebra -/

/-- The ampliation `1_P ⊗ X`. -/
def onePE (X : Matrix E E ℂ) : Matrix (P × E) (P × E) ℂ :=
  (1 : Matrix P P ℂ) ⊗ₖ X

omit [DecidableEq E] in
/-- Left multiplication by an ampliation acts on slices from the
left. -/
theorem slice_onePE_mul (X : Matrix E E ℂ)
    (H : Matrix (P × E) (P × E) ℂ) (a b : P) :
    slice a b (onePE (P := P) X * H) = X * slice a b H := by
  ext c d
  rw [slice_apply, Matrix.mul_apply, Matrix.mul_apply]
  have h1 : ∑ j : P × E, onePE (P := P) X (a, c) j * H j (b, d)
      = ∑ a' : P, ∑ c' : E,
          onePE (P := P) X (a, c) (a', c') * H (a', c') (b, d) :=
    Fintype.sum_prod_type
      (f := fun j => onePE (P := P) X (a, c) j * H j (b, d))
  rw [h1, Finset.sum_eq_single a]
  · refine Finset.sum_congr rfl fun c' _ => ?_
    congr 1
    simp [onePE, Matrix.kroneckerMap_apply]
  · intro a' _ ha'
    refine Finset.sum_eq_zero fun c' _ => ?_
    have h2 : onePE (P := P) X (a, c) (a', c') = 0 := by
      simp [onePE, Matrix.kroneckerMap_apply,
        Matrix.one_apply_ne (Ne.symm ha')]
    rw [h2, zero_mul]
  · intro ha
    exact absurd (Finset.mem_univ a) ha

omit [DecidableEq E] in
/-- Right multiplication by an ampliation acts on slices from the
right. -/
theorem slice_mul_onePE (X : Matrix E E ℂ)
    (H : Matrix (P × E) (P × E) ℂ) (a b : P) :
    slice a b (H * onePE (P := P) X) = slice a b H * X := by
  ext c d
  rw [slice_apply, Matrix.mul_apply, Matrix.mul_apply]
  have h1 : ∑ j : P × E, H (a, c) j * onePE (P := P) X j (b, d)
      = ∑ b' : P, ∑ d' : E,
          H (a, c) (b', d') * onePE (P := P) X (b', d') (b, d) :=
    Fintype.sum_prod_type
      (f := fun j => H (a, c) j * onePE (P := P) X j (b, d))
  rw [h1, Finset.sum_eq_single b]
  · refine Finset.sum_congr rfl fun d' _ => ?_
    congr 1
    simp [onePE, Matrix.kroneckerMap_apply]
  · intro b' _ hb'
    refine Finset.sum_eq_zero fun d' _ => ?_
    have h2 : onePE (P := P) X (b', d') (b, d) = 0 := by
      simp [onePE, Matrix.kroneckerMap_apply,
        Matrix.one_apply_ne hb']
    rw [h2, mul_zero]
  · intro hb
    exact absurd (Finset.mem_univ b) hb

omit [DecidableEq E] in
/-- **The boxed nondemolition criterion, slice form**:
`[1_P ⊗ X, H] = 0` iff `X` commutes with every slice of `H`. -/
theorem commute_onePE_iff_slice (X : Matrix E E ℂ)
    (H : Matrix (P × E) (P × E) ℂ) :
    onePE (P := P) X * H = H * onePE (P := P) X
      ↔ ∀ a b : P, X * slice a b H = slice a b H * X := by
  constructor
  · intro h a b
    have h1 := congrArg (slice a b) h
    rwa [slice_onePE_mul, slice_mul_onePE] at h1
  · intro h
    ext ⟨p, c⟩ ⟨q, d⟩
    change slice p q (onePE (P := P) X * H) c d
      = slice p q (H * onePE (P := P) X) c d
    rw [slice_onePE_mul, slice_mul_onePE, h p q]

section Stable

variable {ι : Type*} (H : ι → Matrix (P × E) (P × E) ℂ)

/-- The nondemolition stable algebra `ℱ_E = 𝒞_E(ℋ)'`. -/
def stableAlgebra : Subalgebra ℂ (Matrix E E ℂ) :=
  Subalgebra.centralizer ℂ
    ((coeffAlgebra H : Set (Matrix E E ℂ)))

/-- The stable classical pointer algebra `𝒵_E = Z(ℱ_E)`. -/
def pointerCentre : Subalgebra ℂ (Matrix E E ℂ) :=
  stableAlgebra H ⊓ Subalgebra.centralizer ℂ
    ((stableAlgebra H : Set (Matrix E E ℂ)))

omit [DecidableEq E] [DecidableEq P] [Fintype E] [Fintype P] in
/-- The generating slices are closed under star for a Hermitian
interaction family. -/
theorem star_slice_set (hH : ∀ ν, (H ν)ᴴ = H ν) :
    {X : Matrix E E ℂ | ∃ (ν : ι) (a b : P), X = slice a b (H ν)}
      ∪ star {X : Matrix E E ℂ |
          ∃ (ν : ι) (a b : P), X = slice a b (H ν)}
      = {X : Matrix E E ℂ |
          ∃ (ν : ι) (a b : P), X = slice a b (H ν)} := by
  refine Set.union_eq_self_of_subset_right ?_
  rintro Y hY
  rw [Set.mem_star] at hY
  obtain ⟨ν, a, b, hab⟩ := hY
  refine ⟨ν, b, a, ?_⟩
  have h1 : Y = star (star Y) := (star_star Y).symm
  rw [h1, hab]
  change (slice a b (H ν))ᴴ = slice b a (H ν)
  rw [slice_conjTranspose, hH ν]

/-- **Proposition `prop:interaction-algebra-minimal`, boxed
characterization**: `X` lies in the nondemolition stable algebra
`ℱ_E` exactly when `[1_P ⊗ X, H_ν] = 0` for every interaction. -/
theorem mem_stableAlgebra_iff (hH : ∀ ν, (H ν)ᴴ = H ν)
    (X : Matrix E E ℂ) :
    X ∈ stableAlgebra H
      ↔ ∀ ν, onePE (P := P) X * H ν = H ν * onePE (P := P) X := by
  rw [stableAlgebra, Subalgebra.mem_centralizer_iff]
  constructor
  · intro h ν
    rw [commute_onePE_iff_slice]
    intro a b
    exact (h _ (slice_mem_coeffAlgebra H ν a b)).symm
  · intro h Y hY
    -- reduce the star-adjoin to the plain adjoin over the
    -- star-closed generator set
    have hY' : Y ∈ Algebra.adjoin ℂ
        {X : Matrix E E ℂ |
          ∃ (ν : ι) (a b : P), X = slice a b (H ν)} := by
      have h1 : Y ∈ (coeffAlgebra H).toSubalgebra := hY
      rw [coeffAlgebra, StarAlgebra.adjoin_toSubalgebra,
        star_slice_set H hH] at h1
      exact h1
    clear hY
    have hkey : X * Y = Y * X := by
      induction hY' using Algebra.adjoin_induction with
      | mem y hy =>
        obtain ⟨ν, a, b, rfl⟩ := hy
        exact (commute_onePE_iff_slice X (H ν)).mp (h ν) a b
      | algebraMap c =>
        rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm,
          smul_mul_assoc, mul_one, one_mul]
      | add y z _ _ ihy ihz =>
        rw [mul_add, add_mul, ihy, ihz]
      | mul y z _ _ ihy ihz =>
        rw [← mul_assoc, ihy, mul_assoc, ihz, ← mul_assoc]
    exact hkey.symm

end Stable

/-! ## The canonical pointer instrument -/

/-- The partial trace over the environment. -/
def ptrace (M : Matrix (P × E) (P × E) ℂ) : Matrix P P ℂ :=
  Matrix.of fun p q => ∑ c, M (p, c) (q, c)

omit [DecidableEq E] [DecidableEq P] [Fintype P] in
theorem ptrace_eq_trace_slice (M : Matrix (P × E) (P × E) ℂ)
    (p q : P) : ptrace M p q = (slice p q M).trace := by
  simp [ptrace, slice, Matrix.trace, Matrix.diag]

omit [DecidableEq E] in
/-- Partial trace of a two-sided ampliated compression. -/
theorem ptrace_compress (A B : Matrix E E ℂ)
    (M : Matrix (P × E) (P × E) ℂ) (p q : P) :
    ptrace (onePE (P := P) A * M * onePE (P := P) B) p q
      = ((slice p q M) * (B * A)).trace := by
  rw [ptrace_eq_trace_slice]
  have h1 : slice p q (onePE (P := P) A * M * onePE (P := P) B)
      = A * (slice p q M * B) := by
    rw [mul_assoc, slice_onePE_mul, slice_mul_onePE]
  rw [h1, Matrix.trace_mul_comm, mul_assoc]

/-- **Theorem `thm:canonical-pointer-instrument`, instrument
identity**: for any family of idempotent environment projections
summing to one, the compressed partial traces resolve the full
partial trace: `∑_α Tr_E[(1 ⊗ z_α) M (1 ⊗ z_α)] = Tr_E M`.  Applied
to `M = VρV*` this is `∑_α ℐ_α(ρ) = Φ_*(ρ)`. -/
theorem pointer_instrument_sum {κ : Type*} [Fintype κ]
    (z : κ → Matrix E E ℂ) (hidem : ∀ α, z α * z α = z α)
    (hsum : ∑ α, z α = 1) (M : Matrix (P × E) (P × E) ℂ) :
    ∑ α, ptrace (onePE (P := P) (z α) * M * onePE (P := P) (z α))
      = ptrace M := by
  ext p q
  rw [Matrix.sum_apply]
  have h1 : ∀ α, ptrace
      (onePE (P := P) (z α) * M * onePE (P := P) (z α)) p q
      = ((slice p q M) * z α).trace := by
    intro α
    rw [ptrace_compress, hidem α]
  rw [Finset.sum_congr rfl fun α _ => h1 α]
  have h2 : ∑ α, ((slice p q M) * z α).trace
      = (∑ α, (slice p q M) * z α).trace :=
    (Matrix.trace_sum _ _).symm
  rw [h2, ← Finset.mul_sum, hsum, mul_one, ptrace_eq_trace_slice]

omit [DecidableEq E] in
/-- **Off-diagonal blocks are invisible to the partial trace**:
cross-compressions along orthogonal projections vanish. -/
theorem pointer_offdiag_vanish (z z' : Matrix E E ℂ)
    (horth : z' * z = 0) (M : Matrix (P × E) (P × E) ℂ) :
    ptrace (onePE (P := P) z * M * onePE (P := P) z') = 0 := by
  ext p q
  rw [ptrace_compress, horth, mul_zero, Matrix.trace_zero]
  rfl

end NCG.Upstream
