/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The canonical future-distinct record algebra

Covers `def:record-future-equivalence`, `thm:canonical-record-algebra`
and `prop:record-transport-descent` from `manuscripts/renewal_emergence/renewal_emergence.tex`.

Raw outcome records are identified when all conditional future
predictions agree (`RecordEquiv`).  The canonical record algebra —
the functions of the raw records through which all conditional
predictions factor — is **exactly** the pullback of the function
algebra on the quotient `Ω = O/≡` (`recordAlgebra_eq_pullback`), it
is a subalgebra (`recordAlgebra_*` closure lemmas), and every
prediction-compatible function factors **uniquely** through the
quotient (`recordAlgebra_factor_unique`) — the reduced minimality and
uniqueness clause.

Reversible record transport compatible with prediction pullback
descends to a bijection of the record classes, functorially in
composition and inversion (`recordTransport_descend`,
`recordTransport_descend_comp`), and pulls the canonical algebras
back isomorphically (`recordAlgebra_comap_bij`).
-/

namespace NCG

variable {O : Type*} {F : Type*} (pcond : F → O → ℝ)

/-- **Definition `def:record-future-equivalence`**: records with the
same conditional prediction for every admissible future
experiment. -/
def RecordEquiv (o o' : O) : Prop := ∀ Fe : F, pcond Fe o = pcond Fe o'

theorem recordEquiv_equivalence : Equivalence (RecordEquiv pcond) :=
  ⟨fun _ _ => rfl, fun h Fe => (h Fe).symm,
    fun h1 h2 Fe => (h1 Fe).trans (h2 Fe)⟩

/-- The record setoid. -/
def recordSetoid : Setoid O :=
  ⟨RecordEquiv pcond, recordEquiv_equivalence pcond⟩

/-- The reduced record classes `Ω = O/≡`. -/
def RecordClasses := Quotient (recordSetoid pcond)

/-- The canonical record algebra: real record functions constant on
prediction classes. -/
def recordAlgebra : Set (O → ℝ) :=
  {f | ∀ o o', RecordEquiv pcond o o' → f o = f o'}

theorem recordAlgebra_const (c : ℝ) :
    (fun _ => c) ∈ recordAlgebra pcond := fun _ _ _ => rfl

theorem recordAlgebra_add {f g : O → ℝ}
    (hf : f ∈ recordAlgebra pcond) (hg : g ∈ recordAlgebra pcond) :
    (f + g) ∈ recordAlgebra pcond := by
  intro o o' h
  simp only [Pi.add_apply, hf o o' h, hg o o' h]

theorem recordAlgebra_mul {f g : O → ℝ}
    (hf : f ∈ recordAlgebra pcond) (hg : g ∈ recordAlgebra pcond) :
    (f * g) ∈ recordAlgebra pcond := by
  intro o o' h
  simp only [Pi.mul_apply, hf o o' h, hg o o' h]

/-- **Theorem `thm:canonical-record-algebra` (identification)**: the
canonical record algebra is exactly the pullback of the function
algebra on the reduced classes. -/
theorem recordAlgebra_eq_pullback :
    recordAlgebra pcond
      = Set.range (fun g : RecordClasses pcond → ℝ =>
          fun o => g (Quotient.mk (recordSetoid pcond) o)) := by
  ext f
  constructor
  · intro hf
    exact ⟨Quotient.lift f hf, rfl⟩
  · rintro ⟨g, rfl⟩ o o' h
    have h1 : Quotient.mk (recordSetoid pcond) o
        = Quotient.mk (recordSetoid pcond) o' := Quotient.sound h
    simp only [h1]

/-- **Theorem `thm:canonical-record-algebra` (unique reduced
factorization)**: every prediction-compatible record function factors
uniquely through the reduced classes. -/
theorem recordAlgebra_factor_unique {f : O → ℝ}
    (hf : f ∈ recordAlgebra pcond) :
    ∃! g : RecordClasses pcond → ℝ,
      (fun o => g (Quotient.mk (recordSetoid pcond) o)) = f := by
  refine ⟨Quotient.lift f hf, rfl, ?_⟩
  intro g hg
  funext x
  induction x using Quotient.ind with | _ o =>
  exact congrFun hg o

/-! ## The generated algebra is the class-constant algebra
(`thm:canonical-record-algebra`, boxed identity, first equality) -/

/-- The canonical record algebra as a subalgebra of `O → ℝ`. -/
def recordSubalgebra : Subalgebra ℝ (O → ℝ) where
  carrier := recordAlgebra pcond
  add_mem' := recordAlgebra_add pcond
  mul_mem' := recordAlgebra_mul pcond
  algebraMap_mem' := fun c => recordAlgebra_const pcond c

theorem mem_recordSubalgebra {f : O → ℝ} :
    f ∈ recordSubalgebra pcond ↔ f ∈ recordAlgebra pcond := Iff.rfl

/-- **Theorem `thm:canonical-record-algebra` (boxed identity, content
half)**: for a finite resolved record set, the real unital algebra
generated by the conditional prediction functions `{p_F}` is exactly
the algebra of class-constant functions.  One inclusion is that each
generator is constant on `≡`-classes; the reverse is the manuscript's
separation argument — affinely rescaled separating predictions give
`g_D` with value `1` on `C` and `0` on `D`, the products
`e_C = ∏ g_D` are the class indicators, and the indicators span. -/
theorem adjoin_predictions_eq_recordAlgebra [Fintype O] :
    Algebra.adjoin ℝ (Set.range pcond) = recordSubalgebra pcond := by
  classical
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨Fe, rfl⟩ o o' h
    exact h Fe
  · intro f hf
    -- pairwise separators, affinely rescaled
    have hsep : ∀ o o' : O, ¬ RecordEquiv pcond o o' →
        ∃ g : O → ℝ, g ∈ Algebra.adjoin ℝ (Set.range pcond) ∧
          (∀ o₂, RecordEquiv pcond o o₂ → g o₂ = 1) ∧
          (∀ o₂, RecordEquiv pcond o' o₂ → g o₂ = 0) := by
      intro o o' hne
      obtain ⟨Fe, hFe⟩ := not_forall.mp hne
      have hp : pcond Fe ∈ Algebra.adjoin ℝ (Set.range pcond) :=
        Algebra.subset_adjoin ⟨Fe, rfl⟩
      have hc1 : (fun _ : O => pcond Fe o')
          ∈ Algebra.adjoin ℝ (Set.range pcond) :=
        Subalgebra.algebraMap_mem _ (pcond Fe o')
      have hc2 : (fun _ : O => (pcond Fe o - pcond Fe o')⁻¹)
          ∈ Algebra.adjoin ℝ (Set.range pcond) :=
        Subalgebra.algebraMap_mem _ ((pcond Fe o - pcond Fe o')⁻¹)
      refine ⟨fun o₂ =>
        (pcond Fe o₂ - pcond Fe o') * (pcond Fe o - pcond Fe o')⁻¹,
        ?_, ?_, ?_⟩
      · exact Subalgebra.mul_mem _ (Subalgebra.sub_mem _ hp hc1) hc2
      · intro o₂ ho₂
        have h1 : pcond Fe o₂ = pcond Fe o := (ho₂ Fe).symm
        dsimp only
        rw [h1]
        exact mul_inv_cancel₀ (sub_ne_zero.mpr hFe)
      · intro o₂ ho₂
        have h1 : pcond Fe o₂ = pcond Fe o' := (ho₂ Fe).symm
        dsimp only
        rw [h1, sub_self, zero_mul]
    choose g hgmem hgone hgzero using hsep
    -- class indicators as products of separators
    set S : O → Finset O :=
      fun o => Finset.univ.filter (fun o' => ¬ RecordEquiv pcond o o')
      with hS
    have hSmem : ∀ {o o' : O}, o' ∈ S o → ¬ RecordEquiv pcond o o' :=
      fun h => (Finset.mem_filter.mp h).2
    set e : O → (O → ℝ) :=
      fun o => ∏ x ∈ (S o).attach, g o x.1 (hSmem x.2) with he
    have he_mem : ∀ o, e o ∈ Algebra.adjoin ℝ (Set.range pcond) :=
      fun o => Subalgebra.prod_mem _
        (fun x _ => hgmem o x.1 (hSmem x.2))
    have he_one : ∀ o o₂, RecordEquiv pcond o o₂ → e o o₂ = 1 := by
      intro o o₂ h
      simp only [he, Finset.prod_apply]
      exact Finset.prod_eq_one fun x _ => hgone o x.1 (hSmem x.2) o₂ h
    have he_zero : ∀ o o₂, ¬ RecordEquiv pcond o o₂ → e o o₂ = 0 := by
      intro o o₂ h
      simp only [he, Finset.prod_apply]
      have hmem : o₂ ∈ S o :=
        Finset.mem_filter.mpr ⟨Finset.mem_univ _, h⟩
      refine Finset.prod_eq_zero
        (Finset.mem_attach (S o) ⟨o₂, hmem⟩) ?_
      exact hgzero o o₂ (hSmem hmem) o₂
        ((recordEquiv_equivalence pcond).refl o₂)
    -- class sizes
    set n : O → ℕ :=
      fun o => (Finset.univ.filter
        (fun o' => RecordEquiv pcond o o')).card with hn
    have hn_pos : ∀ o, 0 < n o := by
      intro o
      simp only [hn]
      exact Finset.card_pos.mpr
        ⟨o, Finset.mem_filter.mpr ⟨Finset.mem_univ _,
          (recordEquiv_equivalence pcond).refl o⟩⟩
    have hn_congr : ∀ o o₂, RecordEquiv pcond o o₂ → n o = n o₂ := by
      intro o o₂ h
      simp only [hn]
      congr 1
      apply Finset.filter_congr
      intro o' _
      constructor
      · intro h1
        exact (recordEquiv_equivalence pcond).trans
          ((recordEquiv_equivalence pcond).symm h) h1
      · intro h1
        exact (recordEquiv_equivalence pcond).trans h h1
    -- the weighted indicator expansion of a class-constant function
    have hf_eq : f = ∑ o, (f o / n o) • e o := by
      funext o₂
      rw [Finset.sum_apply]
      have hsplit :
          ∑ o, ((f o / n o) • e o) o₂
            = ∑ o ∈ Finset.univ.filter
                (fun o => RecordEquiv pcond o o₂),
                ((f o / n o) • e o) o₂
              + ∑ o ∈ Finset.univ.filter
                  (fun o => ¬ RecordEquiv pcond o o₂),
                  ((f o / n o) • e o) o₂ :=
        (Finset.sum_filter_add_sum_filter_not _ _ _).symm
      rw [hsplit]
      have hzero : ∑ o ∈ Finset.univ.filter
          (fun o => ¬ RecordEquiv pcond o o₂),
          ((f o / n o) • e o) o₂ = 0 := by
        refine Finset.sum_eq_zero fun o ho => ?_
        have h := (Finset.mem_filter.mp ho).2
        simp [he_zero o o₂ h]
      have hval : ∑ o ∈ Finset.univ.filter
          (fun o => RecordEquiv pcond o o₂),
          ((f o / n o) • e o) o₂
            = ∑ _o ∈ Finset.univ.filter
                (fun o => RecordEquiv pcond o o₂),
                f o₂ / n o₂ := by
        refine Finset.sum_congr rfl fun o ho => ?_
        have h := (Finset.mem_filter.mp ho).2
        have h1 : f o = f o₂ := hf o o₂ h
        have h2 : n o = n o₂ := hn_congr o o₂ h
        simp [he_one o o₂ h, h1, h2]
      rw [hzero, hval, add_zero, Finset.sum_const]
      have hcard : (Finset.univ.filter
          (fun o => RecordEquiv pcond o o₂)).card = n o₂ := by
        simp only [hn]
        congr 1
        apply Finset.filter_congr
        intro o' _
        exact ⟨fun h => (recordEquiv_equivalence pcond).symm h,
          fun h => (recordEquiv_equivalence pcond).symm h⟩
      rw [hcard, nsmul_eq_mul]
      have hne : ((n o₂ : ℕ) : ℝ) ≠ 0 :=
        Nat.cast_ne_zero.mpr (hn_pos o₂).ne'
      field_simp
    rw [hf_eq]
    exact Subalgebra.sum_mem _
      (fun o _ => Subalgebra.smul_mem _ (he_mem o) _)

/-! ## Descent of reversible record transport
(`prop:record-transport-descent`) -/

section Descent

variable {O O' O'' F F' F'' : Type*}
variable {pcond : F → O → ℝ} {pcond' : F' → O' → ℝ}
variable {pcond'' : F'' → O'' → ℝ}

/-- Transport compatibility: the reversible process pulls future
experiments back so that predictions after transported records match
predictions of pulled-back experiments. -/
def TransportCompat (τ : O → O') (upull : F' → F)
    (pcond : F → O → ℝ) (pcond' : F' → O' → ℝ) : Prop :=
  ∀ (Fe' : F') (o : O), pcond' Fe' (τ o) = pcond (upull Fe') o

theorem recordEquiv_map {τ : O → O'} {upull : F' → F}
    (hcompat : TransportCompat τ upull pcond pcond')
    {o o' : O} (h : RecordEquiv pcond o o') :
    RecordEquiv pcond' (τ o) (τ o') := by
  intro Fe'
  rw [hcompat Fe' o, hcompat Fe' o']
  exact h (upull Fe')

/-- **Proposition `prop:record-transport-descent` (descent)**: a
compatible record transport descends to the reduced classes. -/
def recordTransport_descend (τ : O → O') (upull : F' → F)
    (hcompat : TransportCompat τ upull pcond pcond') :
    RecordClasses pcond → RecordClasses pcond' :=
  Quotient.map' τ fun _ _ h => recordEquiv_map hcompat h

@[simp]
theorem recordTransport_descend_mk (τ : O → O') (upull : F' → F)
    (hcompat : TransportCompat τ upull pcond pcond') (o : O) :
    recordTransport_descend τ upull hcompat
        (Quotient.mk (recordSetoid pcond) o)
      = Quotient.mk (recordSetoid pcond') (τ o) := rfl

/-- **Descent is functorial in composition.** -/
theorem recordTransport_descend_comp
    (τ : O → O') (σ : O' → O'') (upull : F' → F) (vpull : F'' → F')
    (hτ : TransportCompat τ upull pcond pcond')
    (hσ : TransportCompat σ vpull pcond' pcond'')
    (x : RecordClasses pcond) :
    recordTransport_descend σ vpull hσ
        (recordTransport_descend τ upull hτ x)
      = recordTransport_descend (σ ∘ τ) (upull ∘ vpull)
          (fun Fe'' o => by
            rw [Function.comp_apply, Function.comp_apply,
              hσ Fe'' (τ o), hτ (vpull Fe'') o]) x := by
  induction x using Quotient.ind with | _ o =>
  rfl

/-- **Bijectivity of the descent** for a reversible transport with
compatible inverse. -/
theorem recordTransport_descend_bijective
    (τ : O → O') (τinv : O' → O) (upull : F' → F) (upush : F → F')
    (hτ : TransportCompat τ upull pcond pcond')
    (hτinv : TransportCompat τinv upush pcond' pcond)
    (hleft : ∀ o, τinv (τ o) = o) (hright : ∀ o', τ (τinv o') = o') :
    Function.Bijective
      (recordTransport_descend τ upull hτ
        (pcond := pcond) (pcond' := pcond')) := by
  constructor
  · intro x y hxy
    induction x using Quotient.ind with | _ o =>
    induction y using Quotient.ind with | _ o' =>
    have h1 := congrArg
      (recordTransport_descend τinv upush hτinv) hxy
    simp only [recordTransport_descend_mk] at h1
    rw [show τinv (τ o) = o from hleft o,
      show τinv (τ o') = o' from hleft o'] at h1
    exact h1
  · intro y
    induction y using Quotient.ind with | _ o' =>
    exact ⟨Quotient.mk (recordSetoid pcond) (τinv o'), by
      simp only [recordTransport_descend_mk]
      rw [hright o']⟩

/-- **Algebra pullback**: composing with the transport maps the
canonical record algebra of the target into that of the source; for a
reversible transport this is a bijection (unital, order- and
ring-compatible since it is composition). -/
theorem recordAlgebra_comap (τ : O → O') (upull : F' → F)
    (hcompat : TransportCompat τ upull pcond pcond')
    {f : O' → ℝ} (hf : f ∈ recordAlgebra pcond') :
    (f ∘ τ) ∈ recordAlgebra pcond := by
  intro o o' h
  exact hf (τ o) (τ o') (recordEquiv_map hcompat h)

theorem recordAlgebra_comap_bij
    (τ : O → O') (τinv : O' → O) (upull : F' → F) (upush : F → F')
    (hτ : TransportCompat τ upull pcond pcond')
    (hτinv : TransportCompat τinv upush pcond' pcond)
    (hleft : ∀ o, τinv (τ o) = o) (hright : ∀ o', τ (τinv o') = o') :
    ∀ g ∈ recordAlgebra pcond, ∃! f ∈ recordAlgebra pcond',
      f ∘ τ = g := by
  intro g hg
  refine ⟨g ∘ τinv, ⟨?_, ?_⟩, ?_⟩
  · exact recordAlgebra_comap (pcond := pcond') (pcond' := pcond)
      τinv upush hτinv hg
  · funext o
    simp only [Function.comp_apply, hleft o]
  · rintro f ⟨-, hfτ⟩
    funext o'
    have h1 := congrFun hfτ (τinv o')
    simp only [Function.comp_apply, hright o'] at h1
    simp only [Function.comp_apply]
    exact h1

end Descent

end NCG
