/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Upstream.Retract

/-!
# The finite renewal monoid in the recurrent one-interface case

Covers `cor:finite-renewal-monoid` of `manuscripts/renewal_emergence/renewal_emergence.tex`: with
one
recurrent interface `B` and a finite predictive quotient, the
renewal maps `Φ_σ^{(s)} = E_s ∘ U_σ` generate a finite
transformation monoid on the minimal predictive memory
`im E_s ≅ Q₊`, and for a word `w = σ_n ⋯ σ_1` the composite is
`Φ_w^{(s)} = E_s ∘ U_w`.
-/

namespace NCG.Upstream

open CategoryTheory

universe u v w t

variable {P : Type u} [Category.{v} P] {W : Type w} {T : P → Type t}
variable {O : OperationalSystem P W T} {G : GeneratedPresentation O}

/-- The minimal predictive memory of a selector at interface `B`:
the selected predictive image `im E_s`. -/
def Selector.Carrier (s : Selector G) (B : P) : Type _ :=
  {h : Hist G O.root B //
    h ∈ Set.range (fun h : Hist G O.root B => s.compress h)}

/-- **Corollary `cor:finite-renewal-monoid` (transformations)**: the
renewal map of a one-interface continuation, as a transformation of
the minimal predictive memory. -/
def Selector.renewalEnd (s : Selector G) {B : P} (c : Hist G B B)
    (x : s.Carrier B) : s.Carrier B :=
  ⟨s.renewal c x.1, s.renewal_mem_range c x.1⟩

/-- The identity continuation acts as the identity transformation. -/
theorem Selector.renewalEnd_nil (s : Selector G) (B : P) :
    s.renewalEnd (Hist.nil B) = id := by
  funext x
  exact Subtype.ext (s.renewal_nil x.2)

/-- **Corollary `cor:finite-renewal-monoid` (action law)**: the
renewal transformations compose exactly — `Φ_{d∘c} = Φ_d ∘ Φ_c`. -/
theorem Selector.renewalEnd_comp (s : Selector G) {B : P}
    (c d : Hist G B B) :
    s.renewalEnd (c.comp d) = s.renewalEnd d ∘ s.renewalEnd c := by
  funext x
  exact Subtype.ext (s.renewal_comp c d x.1).symm

/-- One-letter history of a single elementary generator. -/
def singleEdge {B : P} (σ : G.Edge B B) : Hist G B B :=
  Hist.cons (Hist.nil B) σ

/-- The history of a word `w = σ_n ⋯ σ_1` of elementary generators
(read right to left, matching `Φ_w = Φ_{σ_n} ∘ ⋯ ∘ Φ_{σ_1}`). -/
def wordHist {B : P} : List (G.Edge B B) → Hist G B B
  | [] => Hist.nil B
  | σ :: l => (singleEdge σ).comp (wordHist l)

/-- **Corollary `cor:finite-renewal-monoid` (word law)**: for a word
`w = σ_n ⋯ σ_1`, `Φ_w^{(s)} = Φ_{σ_n}^{(s)} ∘ ⋯ ∘ Φ_{σ_1}^{(s)}`
— the transformation of the composite history is the composite of
the one-letter renewal transformations. -/
theorem Selector.renewalEnd_wordHist (s : Selector G) {B : P} :
    ∀ l : List (G.Edge B B),
      s.renewalEnd (wordHist l)
        = l.foldr
            (fun σ f => f ∘ s.renewalEnd (singleEdge σ)) id
  | [] => s.renewalEnd_nil B
  | σ :: l => by
    change s.renewalEnd ((singleEdge σ).comp (wordHist l)) = _
    rw [s.renewalEnd_comp, s.renewalEnd_wordHist l]
    rfl

/-- **Corollary `cor:finite-renewal-monoid` (finite memory)**: with a
finite predictive quotient the minimal predictive memory is finite
(via the bijection `q|_{im E_s} : im E_s ≃ Q₊`). -/
theorem Selector.finite_carrier (s : Selector G) (B : P)
    [Finite (Qpred G B)] : Finite (s.Carrier B) :=
  @Finite.of_injective _ (Qpred G B) _
    (fun x => Quot.mk _ x.1)
    (fun x y hxy => Subtype.ext ((s.bijOn_mk B).injOn x.2 y.2 hxy))

/-- **Corollary `cor:finite-renewal-monoid` (finite monoid)**: the
full transformation monoid of the minimal predictive memory is
finite; in particular the submonoid generated by the elementary
renewal maps `{Φ_σ^{(s)}}` is finite. -/
theorem Selector.finite_renewalEnd (s : Selector G) (B : P)
    [Finite (Qpred G B)] :
    Finite (s.Carrier B → s.Carrier B) := by
  haveI := s.finite_carrier B
  infer_instance

end NCG.Upstream
