/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
/-!
# Ghost superalgebras and odd (BRST) superderivations

Minimal Grassmann-graded infrastructure for the ghost-field BRST operator `s` of
`thm:finite-action-identities` (spacetime–gauge duality paper): the rules
`s c = −c²`, `s U = c_t U − U c_s`, `s H = c H`, `s Ψ = c Ψ`, `s c̄ = B`, `s B = 0` and the
identities `s² = 0`, `s 𝒮 = 0`.

## The structures

* `ParityStructure A`: a `ℤ/2`-grading of a `ℂ`-algebra `A`, presented by its **parity
  involution** `ε : A ≃ₐ[ℂ] A`, `ε ∘ ε = id`.  Even elements satisfy `ε a = a`, odd elements
  `ε a = −a` (over `ℂ` this is equivalent to a direct-sum grading `A = A₀ ⊕ A₁` with
  `A_i A_j ⊆ A_{i+j}`; the exterior algebra with its grade involution
  `ExteriorAlgebra.involute` is the basic example, `exteriorParity`).
* `SuperDerivation P`: an **odd superderivation** `s` of `(A, ε)`: a `ℂ`-linear map with
  `s ∘ ε = −ε ∘ s` (it exchanges parities) and the graded Leibniz rule in its right-acting
  form `s (a b) = a (s b) + (s a) ε(b)`, i.e. `s (a b) = a (s b) + (−1)^{|b|} (s a) b` for
  homogeneous `b`.  This is exactly the convention under which the manuscript's ghost rules
  `s c = −c²`, `s H = c H` are consistent (`s² H = c (cH) + (−c²) H = 0`).

## The results

* `SuperDerivation.square_leibniz`: `s²` is an ordinary (even) derivation,
  `s² (a b) = a s² b + (s² a) b` — the graded Jacobi mechanism behind nilpotency.
* `SuperDerivation.square_eq_zero_on_adjoin`: `s²` vanishes on the unital subalgebra
  generated by any set on which it vanishes.
* `SuperDerivation.mapMatrix_mul`: the entrywise extension of `s` to matrices over `A`
  obeys the same right-acting graded Leibniz rule `s (M N) = M (s N) + (s M) ε(N)`.
* `SuperDerivation.ghost_square_zero`: `s c = −c²` for an odd matrix `c` forces
  `s (s c) = 0`.
* `SuperDerivation.link_square_zero`: `s U = c_t U − U c_s` for an even matrix `U` and odd
  ghosts `c_t, c_s` with `s c = −c²` forces `s (s U) = 0`; `matter_square_zero` /
  `dual_matter_square_zero` are the analogues for `s H = c H`, `s H̄ = −H̄ c`;
  `antighost_square_zero` for `s c̄ = B`, `s B = 0`.
* `SuperDerivation.eq_sum_mul_on_adjoin`: on the (commutative, even) subalgebra generated by
  field entries, an odd superderivation whose values on the generators expand as
  `s x = ∑_a c_a δ_a x` with odd ghost scalars `c_a` commuting with the generators and
  ordinary derivations `δ_a` has the same expansion on the whole generated subalgebra;
  hence `s 𝒮 = 0` for every element `𝒮` killed by all `δ_a`
  (`SuperDerivation.apply_eq_zero_of_derivations_eq_zero`).  This is the transfer
  "infinitesimal gauge invariance ⇒ BRST closure".

The library's finite group-cochain differential (`RenewalGeometry.finiteBRST0/1/2`) is a
different object (an inhomogeneous cochain coboundary on a finite gauge group); the
superderivation `s` of this file is the ghost-field BRST operator of the manuscript.
-/

namespace RenewalGeometry

/-! ### Parity structures -/

/-- A `ℤ/2`-grading of a `ℂ`-algebra presented by its parity involution `ε`. -/
structure ParityStructure (A : Type*) [Ring A] [Algebra ℂ A] where
  /-- the parity automorphism `ε` (identity on even, `−1` on odd elements) -/
  ε : A ≃ₐ[ℂ] A
  /-- `ε ∘ ε = id` -/
  ε_involutive : ∀ a, ε (ε a) = a

namespace ParityStructure

variable {A : Type*} [Ring A] [Algebra ℂ A] (P : ParityStructure A)

/-- Even elements: `ε a = a`. -/
def IsEven (a : A) : Prop := P.ε a = a

/-- Odd elements: `ε a = −a`. -/
def IsOdd (a : A) : Prop := P.ε a = -a

theorem isEven_one : P.IsEven 1 := map_one P.ε

theorem isEven_algebraMap (r : ℂ) : P.IsEven (algebraMap ℂ A r) := P.ε.commutes r

theorem IsEven.mul {a b : A} (ha : P.IsEven a) (hb : P.IsEven b) : P.IsEven (a * b) := by
  unfold IsEven at *
  rw [map_mul, ha, hb]

theorem IsEven.add {a b : A} (ha : P.IsEven a) (hb : P.IsEven b) : P.IsEven (a + b) := by
  unfold IsEven at *
  rw [map_add, ha, hb]

theorem IsOdd.mul_odd {a b : A} (ha : P.IsOdd a) (hb : P.IsOdd b) : P.IsEven (a * b) := by
  unfold IsOdd at *
  unfold IsEven
  rw [map_mul, ha, hb, neg_mul_neg]

/-- The parity involution of the exterior (Grassmann) algebra: the grade involution
`ExteriorAlgebra.involute`, `ι v ↦ −ι v`. -/
noncomputable def exteriorParity (M : Type*) [AddCommGroup M] [Module ℂ M] :
    ParityStructure (ExteriorAlgebra ℂ M) where
  ε := CliffordAlgebra.involuteEquiv
  ε_involutive := CliffordAlgebra.involute_involute

/-- The Grassmann generators `ι v` are odd for the exterior parity. -/
theorem exteriorParity_isOdd_ι (M : Type*) [AddCommGroup M] [Module ℂ M] (v : M) :
    (exteriorParity M).IsOdd (ExteriorAlgebra.ι ℂ v) := by
  show CliffordAlgebra.involuteEquiv (ExteriorAlgebra.ι ℂ v) = -ExteriorAlgebra.ι ℂ v
  exact CliffordAlgebra.involute_ι v

/-- Entrywise parity on matrices over `A`. -/
def matrix {m n : Type*} (M : Matrix m n A) : Matrix m n A := M.map P.ε

theorem matrix_mul {m n o : Type*} [Fintype n] (M : Matrix m n A) (N : Matrix n o A) :
    P.matrix (M * N) = P.matrix M * P.matrix N := by
  ext i j
  simp [matrix, Matrix.mul_apply, map_sum, map_mul]

theorem matrix_add {m n : Type*} (M N : Matrix m n A) :
    P.matrix (M + N) = P.matrix M + P.matrix N :=
  Matrix.map_add _ (map_add P.ε) M N

theorem matrix_sub {m n : Type*} (M N : Matrix m n A) :
    P.matrix (M - N) = P.matrix M - P.matrix N :=
  Matrix.map_sub _ (map_sub P.ε) M N

theorem matrix_neg {m n : Type*} (M : Matrix m n A) : P.matrix (-M) = -P.matrix M :=
  Matrix.map_neg _ (map_neg P.ε) M

end ParityStructure

/-! ### Odd superderivations -/

/-- An **odd superderivation** of `(A, ε)`: `ℂ`-linear, parity-exchanging (`s ∘ ε = −ε ∘ s`),
with the right-acting graded Leibniz rule `s (a b) = a (s b) + (s a) ε(b)`. -/
structure SuperDerivation {A : Type*} [Ring A] [Algebra ℂ A] (P : ParityStructure A) where
  /-- the underlying linear map -/
  toLinearMap : A →ₗ[ℂ] A
  /-- `s` exchanges parities: `s (ε a) = −ε (s a)` -/
  map_parity : ∀ a, toLinearMap (P.ε a) = -P.ε (toLinearMap a)
  /-- the graded Leibniz rule `s (a b) = a (s b) + (s a) ε(b)` -/
  leibniz : ∀ a b, toLinearMap (a * b) = a * toLinearMap b + toLinearMap a * P.ε b

namespace SuperDerivation

variable {A : Type*} [Ring A] [Algebra ℂ A] {P : ParityStructure A} (s : SuperDerivation P)

instance : CoeFun (SuperDerivation P) (fun _ => A → A) := ⟨fun s => s.toLinearMap⟩

theorem map_add (a b : A) : s (a + b) = s a + s b := s.toLinearMap.map_add a b

theorem map_smul (r : ℂ) (a : A) : s (r • a) = r • s a := s.toLinearMap.map_smul r a

theorem map_neg (a : A) : s (-a) = -s a := s.toLinearMap.map_neg a

theorem map_sub (a b : A) : s (a - b) = s a - s b := s.toLinearMap.map_sub a b

theorem map_zero : s 0 = 0 := s.toLinearMap.map_zero

theorem map_sum {ι : Type*} (t : Finset ι) (f : ι → A) : s (∑ i ∈ t, f i) = ∑ i ∈ t, s (f i) :=
  _root_.map_sum s.toLinearMap f t

/-- `s 1 = 0`. -/
theorem map_one : s 1 = 0 := by
  have h := s.leibniz 1 1
  rw [one_mul, one_mul, _root_.map_one P.ε, mul_one] at h
  have h2 : (2 : ℂ) • s 1 = s 1 := by
    rw [two_smul]
    exact h.symm
  have h3 : ((2 : ℂ) - 1) • s 1 = 0 := by rw [sub_smul, h2, one_smul, sub_self]
  have h4 : ((2 : ℂ) - 1) ≠ 0 := by norm_num
  exact (smul_eq_zero.mp h3).resolve_left h4

theorem map_algebraMap (r : ℂ) : s (algebraMap ℂ A r) = 0 := by
  rw [Algebra.algebraMap_eq_smul_one, map_smul, map_one, smul_zero]

/-- The graded Leibniz rule for an even right factor: `s (a b) = a (s b) + (s a) b`. -/
theorem leibniz_even (a : A) {b : A} (hb : P.IsEven b) : s (a * b) = a * s b + s a * b := by
  rw [s.leibniz, hb]

/-- The graded Leibniz rule for an odd right factor: `s (a b) = a (s b) − (s a) b`. -/
theorem leibniz_odd (a : A) {b : A} (hb : P.IsOdd b) : s (a * b) = a * s b - s a * b := by
  rw [s.leibniz, hb, mul_neg, sub_eq_add_neg]

/-- **`s²` is an even derivation**: `s² (a b) = a s² b + (s² a) b`.  This is the graded
Jacobi mechanism: the cross terms `(s a) ε(s b)` and `(s a) s(ε b) = −(s a) ε(s b)` cancel. -/
theorem square_leibniz (a b : A) : s (s (a * b)) = a * s (s b) + s (s a) * b := by
  rw [s.leibniz a b, s.map_add, s.leibniz a (s b), s.leibniz (s a) (P.ε b), s.map_parity,
    P.ε_involutive, mul_neg]
  abel

/-- `s²` vanishes on the unital subalgebra generated by a set on which it vanishes. -/
theorem square_eq_zero_on_adjoin {gens : Set A} (h : ∀ x ∈ gens, s (s x) = 0) :
    ∀ x ∈ Algebra.adjoin ℂ gens, s (s x) = 0 := by
  intro x hx
  induction hx using Algebra.adjoin_induction with
  | mem x hx => exact h x hx
  | algebraMap r => rw [s.map_algebraMap, s.map_zero]
  | add x y _ _ hx hy => rw [s.map_add, s.map_add, hx, hy, add_zero]
  | mul x y _ _ hx hy => rw [s.square_leibniz, hx, hy, mul_zero, zero_mul, add_zero]

/-! ### Matrices over a superalgebra -/

/-- Entrywise action of `s` on matrices over `A`. -/
def matrix {m n : Type*} (M : Matrix m n A) : Matrix m n A := M.map s

theorem matrix_apply {m n : Type*} (M : Matrix m n A) (i : m) (j : n) :
    s.matrix M i j = s (M i j) := rfl

theorem matrix_add {m n : Type*} (M N : Matrix m n A) :
    s.matrix (M + N) = s.matrix M + s.matrix N :=
  Matrix.map_add _ s.map_add M N

theorem matrix_sub {m n : Type*} (M N : Matrix m n A) :
    s.matrix (M - N) = s.matrix M - s.matrix N :=
  Matrix.map_sub _ s.map_sub M N

theorem matrix_neg {m n : Type*} (M : Matrix m n A) : s.matrix (-M) = -s.matrix M :=
  Matrix.map_neg _ s.map_neg M

theorem matrix_zero {m n : Type*} : s.matrix (0 : Matrix m n A) = 0 :=
  Matrix.map_zero _ s.map_zero

/-- The right-acting graded Leibniz rule for matrices: `s (M N) = M (s N) + (s M) ε(N)`. -/
theorem matrix_mul {m n o : Type*} [Fintype n] (M : Matrix m n A) (N : Matrix n o A) :
    s.matrix (M * N) = M * s.matrix N + s.matrix M * P.matrix N := by
  ext i j
  simp only [matrix, ParityStructure.matrix, Matrix.map_apply, Matrix.mul_apply,
    Matrix.add_apply, s.map_sum, s.leibniz, Finset.sum_add_distrib]

/-! ### The ghost rules force nilpotency -/

section GhostRules

variable {n p : Type*} [Fintype n] [DecidableEq n]

/-- **`s c = −c²` is nilpotent**: for an odd ghost matrix `c`, `s (s c) = 0`. -/
theorem ghost_square_zero {c : Matrix n n A} (hodd : P.matrix c = -c)
    (hsc : s.matrix c = -(c * c)) : s.matrix (s.matrix c) = 0 := by
  rw [hsc, s.matrix_neg, s.matrix_mul, hsc, hodd]
  noncomm_ring

/-- **`s U = c_t U − U c_s` is nilpotent**: for an even link `U` and odd ghosts `c_t, c_s`
with `s c = −c²`, `s (s U) = 0`. -/
theorem link_square_zero {ct cs U : Matrix n n A}
    (_hct : P.matrix ct = -ct) (hcs : P.matrix cs = -cs) (hU : P.matrix U = U)
    (hsct : s.matrix ct = -(ct * ct)) (hscs : s.matrix cs = -(cs * cs))
    (hsU : s.matrix U = ct * U - U * cs) : s.matrix (s.matrix U) = 0 := by
  rw [hsU, s.matrix_sub, s.matrix_mul, s.matrix_mul, hsU, hsct, hscs, hU, hcs]
  noncomm_ring

/-- **`s H = c H` is nilpotent**: for an even matter field `H` (a column block) and an odd
ghost `c` with `s c = −c²`, `s (s H) = 0`. -/
theorem matter_square_zero {c : Matrix n n A} {H : Matrix n p A}
    (hH : P.matrix H = H) (hsc : s.matrix c = -(c * c)) (hsH : s.matrix H = c * H) :
    s.matrix (s.matrix H) = 0 := by
  rw [hsH, s.matrix_mul, hsH, hsc, hH, ← Matrix.mul_assoc, Matrix.neg_mul, add_neg_cancel]

/-- **`s H̄ = −H̄ c` is nilpotent** for an even dual amplitude `H̄` (a row block) and an odd
ghost `c` with `s c = −c²`. -/
theorem dual_matter_square_zero {c : Matrix n n A} {Hb : Matrix p n A}
    (hc : P.matrix c = -c) (hsc : s.matrix c = -(c * c)) (hsHb : s.matrix Hb = -(Hb * c)) :
    s.matrix (s.matrix Hb) = 0 := by
  rw [hsHb, s.matrix_neg, s.matrix_mul, hsHb, hsc, hc, Matrix.mul_neg, Matrix.neg_mul,
    Matrix.mul_neg, neg_neg, Matrix.mul_assoc, neg_add_cancel, neg_zero]

/-- **`s c̄ = B`, `s B = 0` is nilpotent.** -/
theorem antighost_square_zero {cb B : Matrix n n A} (hscb : s.matrix cb = B)
    (hsB : s.matrix B = 0) : s.matrix (s.matrix cb) = 0 ∧ s.matrix (s.matrix B) = 0 := by
  refine ⟨by rw [hscb, hsB], by rw [hsB, s.matrix_zero]⟩

end GhostRules

/-! ### Transfer: infinitesimal gauge invariance gives BRST closure -/

section Transfer

variable {ι : Type*} [Fintype ι]

/-- On the unital subalgebra generated by even generators, an odd superderivation that
expands on the generators as `s x = ∑_a c_a δ_a x` — with ghost scalars `c_a` commuting
with the generators and ordinary derivations `δ_a` — has the same expansion everywhere;
moreover the generated subalgebra is even and commutes with the `c_a`. -/
theorem eq_sum_mul_on_adjoin {gens : Set A} (heven : ∀ x ∈ gens, P.IsEven x)
    (c : ι → A) (δ : ι → A →ₗ[ℂ] A)
    (hδ : ∀ a x y, δ a (x * y) = x * δ a y + δ a x * y)
    (hcomm : ∀ x ∈ gens, ∀ a, x * c a = c a * x)
    (hgen : ∀ x ∈ gens, s x = ∑ a, c a * δ a x) :
    ∀ x ∈ Algebra.adjoin ℂ gens,
      P.IsEven x ∧ (∀ a, x * c a = c a * x) ∧ s x = ∑ a, c a * δ a x := by
  have hδ1 : ∀ a, δ a 1 = 0 := by
    intro a
    have h := hδ a 1 1
    rw [one_mul, one_mul, mul_one] at h
    have h2 : ((2 : ℂ) - 1) • δ a 1 = 0 := by
      rw [sub_smul, two_smul, one_smul, ← h, sub_self]
    exact (smul_eq_zero.mp h2).resolve_left (by norm_num)
  intro x hx
  induction hx using Algebra.adjoin_induction with
  | mem x hx => exact ⟨heven x hx, hcomm x hx, hgen x hx⟩
  | algebraMap r =>
    refine ⟨P.isEven_algebraMap r, fun a => Algebra.commutes r (c a), ?_⟩
    rw [s.map_algebraMap]
    symm
    refine Finset.sum_eq_zero fun a _ => ?_
    rw [Algebra.algebraMap_eq_smul_one, (δ a).map_smul, hδ1, smul_zero, mul_zero]
  | add x y _ _ hx hy =>
    obtain ⟨hxe, hxc, hxs⟩ := hx
    obtain ⟨hye, hyc, hys⟩ := hy
    refine ⟨ParityStructure.IsEven.add P hxe hye, fun a => by rw [add_mul, mul_add, hxc, hyc], ?_⟩
    rw [s.map_add, hxs, hys, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [(δ a).map_add, mul_add]
  | mul x y _ _ hx hy =>
    obtain ⟨hxe, hxc, hxs⟩ := hx
    obtain ⟨hye, hyc, hys⟩ := hy
    refine ⟨ParityStructure.IsEven.mul P hxe hye, fun a => by rw [mul_assoc, hyc, ← mul_assoc, hxc, mul_assoc], ?_⟩
    rw [s.leibniz_even x hye, hxs, hys, Finset.mul_sum, Finset.sum_mul, ← Finset.sum_add_distrib]
    refine Finset.sum_congr rfl fun a _ => ?_
    rw [hδ a x y, mul_add, ← mul_assoc, hxc, mul_assoc, mul_assoc]

/-- **BRST closure from infinitesimal gauge invariance.**  If the odd superderivation `s`
expands on the field generators as `s x = ∑_a c_a δ_a x` (ghost scalars times the
infinitesimal gauge derivations), then every element `𝒮` of the field algebra with
`δ_a 𝒮 = 0` for all `a` satisfies `s 𝒮 = 0`. -/
theorem apply_eq_zero_of_derivations_eq_zero {gens : Set A} (heven : ∀ x ∈ gens, P.IsEven x)
    (c : ι → A) (δ : ι → A →ₗ[ℂ] A)
    (hδ : ∀ a x y, δ a (x * y) = x * δ a y + δ a x * y)
    (hcomm : ∀ x ∈ gens, ∀ a, x * c a = c a * x)
    (hgen : ∀ x ∈ gens, s x = ∑ a, c a * δ a x)
    {S : A} (hS : S ∈ Algebra.adjoin ℂ gens) (hinv : ∀ a, δ a S = 0) : s S = 0 := by
  rw [(s.eq_sum_mul_on_adjoin heven c δ hδ hcomm hgen S hS).2.2]
  exact Finset.sum_eq_zero fun a _ => by rw [hinv a, mul_zero]

end Transfer

end SuperDerivation

end RenewalGeometry
