/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Action.InitialConstraintRetractionExact
import RenewalGeometry.Action.ValidatedInitialRetractionExact

/-!
# A posteriori exact physical shadows
  (`thm:aposteriori-physical-shadow`, `cor:shadow-harmonic-defect`)

Einstein–Standard-Model action-closure manuscript, subsection "A posteriori exact physical
shadows": `ass:physical-Cauchy-tube`, `thm:aposteriori-physical-shadow`
(`eq:aposteriori-shadow-budget`, `eq:aposteriori-physical-shadow`) and
`cor:shadow-harmonic-defect` (`eq:shadow-harmonic-budget`).

## Setting

The theorem is a composition of four ingredients; this file formalizes the composition on an
abstract slab model and proves every step that is not one of the inputs.

* `SlabModel Z X O` — the analytic data on the slab `Q = [0,T] × 𝕋³`: a type `Z` of actual field
  tuples (records and exact solutions), the initial actual-jet state `𝒰(z)(0) ∈ 𝒳_k` (`init`,
  `𝒳_k` a real normed space carrying the `H^k` norm), the comparison observable
  `(𝒰(z), Riem(g), T^SM(z))` in a pseudometric space `O` whose distance is the left side of
  `eq:aposteriori-physical-shadow` (sum of the `C_tH^k_x`, `L²_tH^{k-1}_x`, `L²_tH^k_x` distances),
  the residual norms `‖𝓡_B‖_{L²_tH^k_x}`, `‖𝓡_D‖_{L²_tH^{k+1}_x}` (`resB`, `resD`), the
  harmonic-defect norm `‖C(g)‖_{L²_tH^{k+1}_x} + ‖∂_tC(g)‖_{L²_tH^k_x}` (`harm`), the predicate
  "smooth actual field tuple on the slab and foliated chart in exact temporal internal gauge"
  (`Admissible`, the hypothesis on `ẑ` in `prop:coupled-bootstrap`) and "exact physical
  Einstein–Standard-Model solution in harmonic coordinates and temporal gauge" (`IsExact`, which
  has vanishing physical residuals and harmonic defect).
* `CauchyTube` — **`ass:physical-Cauchy-tube`** encoded as a hypothesis structure with exactly the
  listed properties: a regular compatible family `𝒞_k^reg ⊂ 𝒞_k` with a fixed higher-order bound,
  an open `H^k` neighbourhood `𝒪_k`, a solution map generating from every datum of
  `𝒞_k^reg ∩ 𝒪_k` an exact solution on the common slab with that datum, unique in the declared
  gauge class, staying in one chart with a uniform `C_tH^{k+1}_x` state bound, and uniform
  constants `(d_*, C_*)` of `prop:coupled-bootstrap` on this family.
* `CoupledBootstrapConclusion` — the **stated conclusion of `prop:coupled-bootstrap`**
  (`eq:bootstrap-state`, `eq:bootstrap-curvature`) for the references of the tube family with
  the tube's uniform constants: `d ≤ d_*` implies (state + curvature + stress difference)
  `≤ C_* d`, with `d` the mismatch of `prop:coupled-bootstrap` (`SlabModel.mismatch`).
  `prop:coupled-bootstrap` is OPEN in the ledger; it is carried as a hypothesis here.

## Main results

* `shadow_of_datum` — the core step of the proof: exact solution generated by the tube from a
  datum in `𝒞_k^reg ∩ 𝒪_k`, uniqueness, and the shadow bound `≤ C 𝔡` once the budget
  `𝔡 = (initial mismatch) + C_R√T (forcing + harmonic defect)` is below the stability radius.
* `shadow_of_retraction` — composition with the output of the initial retraction.
* **`aposteriori_physical_shadow`** — `thm:aposteriori-physical-shadow` (normalized record with
  exact base point, harmonic normalization `C(ĝ_h) = 0`, `𝔡_h = 2B_*γ_*⁻¹β_h + C_R√T η_{h,k}`),
  composed with the proved `prop:initial-constraint-retraction`
  (`initialConstraintRetraction_derivAtZero`).
* `aposteriori_shadow_limit` — the final assertion: convergent corrected data in the tube give
  convergent shadows (continuous dependence from the bootstrap applied to exact solutions), and
  records with `𝔡_h → 0` have the same continuum limit.
* **`shadow_harmonic_defect`** — `cor:shadow-harmonic-defect` with the enlarged budget
  `𝔡_h^C = ζ^comp + 2B_*γ_*⁻¹β_h + C_R√T(η_{h,k} + γ̂_{h,k})` (approximately harmonic record,
  nonzero complementary correction `ζ^comp` of `rem:initial-correction-bookkeeping`), and
  `shadow_harmonic_defect_validated` with the validated budget `β^eff` of
  `cor:validated-initial-retraction` (`validatedInitialRetraction`).

Renderings disclosed: the PDE objects (Sobolev spaces on the slab `[0,T] × 𝕋³`, `Σ = 𝕋³`, the
actual-jet state, curvature and stress) enter only through the abstract slab model; the record
`zh` is the normalized record `ẑ_h` (a certified normalization multiplies the residual norms by a
cutoff-independent factor, absorbed in `η`); the paper's generic constant `C_R` in the budget is the
parameter `c > 0`, and the conclusion holds with the explicit constant
`C_* max(1, (c√T)⁻¹)`.
-/

open Metric Filter Topology

namespace RenewalGeometry.AposterioriShadow

noncomputable section

/-! ### The slab model, the Cauchy tube and the bootstrap conclusion -/

/-- **The analytic slab model** (`subsec:aposteriori-shadow`, `prop:coupled-bootstrap`): actual
field tuples `Z` on the slab, their initial actual-jet state in `𝒳_k` (`H^k` norm), the comparison
observable `(𝒰, Riem, T^SM)` in the pseudometric space `O`, the residual and harmonic-defect norms,
admissible approximate records and exact solutions. -/
structure SlabModel (Z X O : Type*) [NormedAddCommGroup X] [PseudoMetricSpace O] where
  /-- The initial actual-jet state `𝒰(z)(0) ∈ 𝒳_k`. -/
  init : Z → X
  /-- The comparison observable `(𝒰(z), Riem(g), T^SM(z))`; its distance is the left side of
  `eq:aposteriori-physical-shadow`. -/
  obs : Z → O
  /-- `‖𝓡_B(z)‖_{L²_tH^k_x}` (Einstein, Yang–Mills and Higgs rows). -/
  resB : Z → ℝ
  /-- `‖𝓡_D(z)‖_{L²_tH^{k+1}_x}` (Dirac and dual-Dirac rows). -/
  resD : Z → ℝ
  /-- `‖C(g)‖_{L²_tH^{k+1}_x} + ‖∂_tC(g)‖_{L²_tH^k_x}`, `C^μ = g^{αβ}Γ^μ_{αβ}`. -/
  harm : Z → ℝ
  /-- Smooth actual field tuple on the slab and foliated chart, exact temporal internal gauge. -/
  Admissible : Z → Prop
  /-- Exact physical Einstein–Standard-Model solution in the declared gauge class. -/
  IsExact : Z → Prop
  resB_nonneg : ∀ z, 0 ≤ resB z
  resD_nonneg : ∀ z, 0 ≤ resD z
  harm_nonneg : ∀ z, 0 ≤ harm z
  /-- An exact solution has vanishing physical rows. -/
  exact_resB : ∀ z, IsExact z → resB z = 0
  /-- An exact solution has vanishing Dirac rows. -/
  exact_resD : ∀ z, IsExact z → resD z = 0
  /-- An exact solution is in harmonic coordinates. -/
  exact_harm : ∀ z, IsExact z → harm z = 0

variable {Z X O : Type*} [NormedAddCommGroup X] [PseudoMetricSpace O]

/-- The mismatch `d` of `prop:coupled-bootstrap`:
`‖𝒰̂(0) - 𝒰_*(0)‖_{H^k} + ‖𝓡_B(ẑ)‖_{L²H^k} + ‖𝓡_D(ẑ)‖_{L²H^{k+1}} + (harmonic defect of ĝ)`;
the reference has vanishing residuals. -/
def SlabModel.mismatch (M : SlabModel Z X O) (zh zs : Z) : ℝ :=
  ‖M.init zh - M.init zs‖ + M.resB zh + M.resD zh + M.harm zh

/-- **The conclusion of `prop:coupled-bootstrap`** for the references in `Ref` with constants
`(d_*, C_*)`: for every reference `z_* ∈ Ref` and every admissible approximate record `ẑ`,
`d ≤ d_*` implies `‖𝒰̂ - 𝒰_*‖_{C_tH^k} + ‖Riem(ĝ) - Riem(g_*)‖_{L²H^{k-1}} +
‖T^SM(ẑ) - T^SM(z_*)‖_{L²H^k} ≤ C_* d` (`eq:bootstrap-state`, `eq:bootstrap-curvature`).
`prop:coupled-bootstrap` is open in the ledger; this predicate is used only as a hypothesis. -/
def CoupledBootstrapConclusion (M : SlabModel Z X O) (Ref : Set Z) (dstar Cstar : ℝ) : Prop :=
  ∀ zs ∈ Ref, ∀ zh, M.Admissible zh → M.mismatch zh zs ≤ dstar →
    dist (M.obs zh) (M.obs zs) ≤ Cstar * M.mismatch zh zs

/-- **`ass:physical-Cauchy-tube`** (verified physical Cauchy tube), for the constraint map
`𝔠_k : 𝒳_k → 𝒴_k^con` (`Ck`): a declared regular compatible family `𝒞_k^reg ⊂ 𝒞_k = {𝔠_k = 0}`
carrying a fixed higher-order (`H^{k+1}`) bound, an open neighbourhood `𝒪_k` in the initial `H^k`
topology, and a solution map such that every datum of `𝒞_k^reg ∩ 𝒪_k` generates a unique exact
solution on the common slab with that initial datum; these solutions remain in one compact
nondegenerate chart with a common spacelike foliation (`InChart`) with a uniform `C_tH^{k+1}_x`
bound for their actual-jet states, and the constants of `prop:coupled-bootstrap` are uniform on the
family (`dstar`, `Cstar`). -/
structure CauchyTube (M : SlabModel Z X O) {Y : Type*} [Zero Y] (Ck : X → Y) where
  /-- The regular compatible family `𝒞_k^reg`. -/
  Creg : Set X
  /-- `𝒞_k^reg ⊂ 𝒞_k`. -/
  Creg_constraint : ∀ d ∈ Creg, Ck d = 0
  /-- The higher-order (`H^{k+1}`) norm of a datum. -/
  hiNorm : X → ℝ
  /-- The fixed higher-order bound. -/
  hiBound : ℝ
  Creg_hi : ∀ d ∈ Creg, hiNorm d ≤ hiBound
  /-- The open neighbourhood `𝒪_k`. -/
  nbhd : Set X
  nbhd_open : IsOpen nbhd
  /-- The Cauchy solution map. -/
  evolve : X → Z
  evolve_exact : ∀ d ∈ Creg ∩ nbhd, M.IsExact (evolve d)
  evolve_init : ∀ d ∈ Creg ∩ nbhd, M.init (evolve d) = d
  /-- Uniqueness in the declared gauge class. -/
  evolve_unique : ∀ d ∈ Creg ∩ nbhd, ∀ z, M.IsExact z → M.init z = d → z = evolve d
  /-- Membership in the common compact nondegenerate foliated chart. -/
  InChart : Z → Prop
  evolve_chart : ∀ d ∈ Creg ∩ nbhd, InChart (evolve d)
  /-- The `C_tH^{k+1}_x` norm of the actual-jet state. -/
  stateHi : Z → ℝ
  stateBound : ℝ
  evolve_stateHi : ∀ d ∈ Creg ∩ nbhd, stateHi (evolve d) ≤ stateBound
  /-- The uniform smallness constant `d_*` of `prop:coupled-bootstrap` on the family. -/
  dstar : ℝ
  /-- The uniform stability constant `C_*` of `prop:coupled-bootstrap` on the family. -/
  Cstar : ℝ
  dstar_pos : 0 < dstar
  Cstar_nonneg : 0 ≤ Cstar

namespace CauchyTube

variable {M : SlabModel Z X O} {Y : Type*} [Zero Y] {Ck : X → Y}

/-- The family of exact solutions generated by the tube. -/
def family (T : CauchyTube M Ck) : Set Z := T.evolve '' (T.Creg ∩ T.nbhd)

/-- The uniform stability radius for budgets `ι + c√τ(·)`: `d_* min(1, c√τ)`. -/
def stabilityRadius (T : CauchyTube M Ck) (c τ : ℝ) : ℝ := T.dstar * min 1 (c * Real.sqrt τ)

/-- The shadow constant `C_* max(1, (c√τ)⁻¹)`. -/
def shadowConst (T : CauchyTube M Ck) (c τ : ℝ) : ℝ := T.Cstar * max 1 (c * Real.sqrt τ)⁻¹

theorem evolve_mem_family (T : CauchyTube M Ck) {d : X} (hd : d ∈ T.Creg ∩ T.nbhd) :
    T.evolve d ∈ T.family :=
  ⟨d, hd, rfl⟩

theorem evolve_constraint (T : CauchyTube M Ck) {d : X} (hd : d ∈ T.Creg ∩ T.nbhd) :
    Ck (M.init (T.evolve d)) = 0 := by
  rw [T.evolve_init d hd]; exact T.Creg_constraint d hd.1

theorem stabilityRadius_pos (T : CauchyTube M Ck) {c τ : ℝ} (hc : 0 < c) (hτ : 0 < τ) :
    0 < T.stabilityRadius c τ :=
  mul_pos T.dstar_pos (lt_min one_pos (mul_pos hc (Real.sqrt_pos.mpr hτ)))

theorem shadowConst_nonneg (T : CauchyTube M Ck) (c τ : ℝ) : 0 ≤ T.shadowConst c τ :=
  mul_nonneg T.Cstar_nonneg (le_trans zero_le_one (le_max_left _ _))

end CauchyTube

/-! ### Budget arithmetic -/

/-- `max(1, a⁻¹) min(1, a) = 1` for `a > 0`. -/
theorem max_one_inv_mul_min_one {a : ℝ} (ha : 0 < a) : max 1 a⁻¹ * min 1 a = 1 := by
  rcases le_or_gt a 1 with h | h
  · rw [max_eq_right (one_le_inv₀ ha |>.mpr h), min_eq_right h, inv_mul_cancel₀ ha.ne']
  · rw [max_eq_left (inv_le_one_of_one_le₀ h.le), min_eq_left h.le, one_mul]

/-- **Cauchy–Schwarz bookkeeping of the budget**: an initial mismatch `ι ≥ 0` plus forcing `f ≥ 0`
is at most `max(1, a⁻¹)(ι + a f)` for `a > 0` (this is how the factor `C_R√T` of
`eq:aposteriori-shadow-budget` is absorbed in the shadow constant). -/
theorem add_le_max_one_inv_mul {ι f a : ℝ} (hι : 0 ≤ ι) (hf : 0 ≤ f) (ha : 0 < a) :
    ι + f ≤ max 1 a⁻¹ * (ι + a * f) := by
  have h1 : ι ≤ max 1 a⁻¹ * ι := le_mul_of_one_le_left hι (le_max_left _ _)
  have h2 : f ≤ max 1 a⁻¹ * (a * f) := by
    calc f = a⁻¹ * (a * f) := by field_simp
      _ ≤ max 1 a⁻¹ * (a * f) :=
        mul_le_mul_of_nonneg_right (le_max_right _ _) (mul_nonneg ha.le hf)
  rw [mul_add]; linarith

/-! ### The shadow from a corrected datum -/

variable (M : SlabModel Z X O) {Y : Type*} [Zero Y] {Ck : X → Y}

/-- **Core step of `thm:aposteriori-physical-shadow`.**  Let `d ∈ 𝒞_k^reg ∩ 𝒪_k` be a datum with
initial mismatch `‖𝒰(ẑ)(0) - d‖ ≤ ι` from an admissible record `ẑ` with forcing
`‖𝓡_B‖_{L²H^k} + ‖𝓡_D‖_{L²H^{k+1}} ≤ η`.  If the budget `𝔡 = ι + c√τ(η + γ̂)`
(`γ̂` the harmonic-defect norm of `ẑ`) is at most the stability radius `d_* min(1, c√τ)`, then
the tube's solution `z_* = evolve d` is exact with datum `d`, it is the unique exact solution with
that datum, and (by the conclusion of `prop:coupled-bootstrap` with reference `z_*`)
`dist(obs ẑ, obs z_*) ≤ C_* max(1, (c√τ)⁻¹) 𝔡`. -/
theorem shadow_of_datum (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {zh : Z} (hadm : M.Admissible zh) {d : X} (hd : d ∈ T.Creg ∩ T.nbhd)
    {ι η c τ : ℝ} (hc : 0 < c) (hτ : 0 < τ)
    (hinit : ‖M.init zh - d‖ ≤ ι) (hforce : M.resB zh + M.resD zh ≤ η)
    (hsmall : ι + c * Real.sqrt τ * (η + M.harm zh) ≤ T.stabilityRadius c τ) :
    M.IsExact (T.evolve d) ∧ M.init (T.evolve d) = d ∧
      (∀ z, M.IsExact z → M.init z = d → z = T.evolve d) ∧
      dist (M.obs zh) (M.obs (T.evolve d)) ≤
        T.shadowConst c τ * (ι + c * Real.sqrt τ * (η + M.harm zh)) := by
  set a := c * Real.sqrt τ with ha_def
  have ha : 0 < a := mul_pos hc (Real.sqrt_pos.mpr hτ)
  have hι : 0 ≤ ι := (norm_nonneg _).trans hinit
  have hη : 0 ≤ η := le_trans (add_nonneg (M.resB_nonneg zh) (M.resD_nonneg zh)) hforce
  have hf : 0 ≤ η + M.harm zh := add_nonneg hη (M.harm_nonneg zh)
  -- the mismatch of `prop:coupled-bootstrap` against `z_* = evolve d`
  have hmis : M.mismatch zh (T.evolve d) ≤ ι + (η + M.harm zh) := by
    unfold SlabModel.mismatch
    rw [T.evolve_init d hd]
    linarith
  have hmisK : M.mismatch zh (T.evolve d) ≤ max 1 a⁻¹ * (ι + a * (η + M.harm zh)) :=
    hmis.trans (add_le_max_one_inv_mul hι hf ha)
  have hK0 : 0 ≤ max 1 a⁻¹ := le_trans zero_le_one (le_max_left _ _)
  have hsmall' : M.mismatch zh (T.evolve d) ≤ T.dstar := by
    calc M.mismatch zh (T.evolve d) ≤ max 1 a⁻¹ * (ι + a * (η + M.harm zh)) := hmisK
      _ ≤ max 1 a⁻¹ * (T.dstar * min 1 a) := mul_le_mul_of_nonneg_left hsmall hK0
      _ = T.dstar * (max 1 a⁻¹ * min 1 a) := by ring
      _ = T.dstar := by rw [max_one_inv_mul_min_one ha, mul_one]
  refine ⟨T.evolve_exact d hd, T.evolve_init d hd, T.evolve_unique d hd, ?_⟩
  calc dist (M.obs zh) (M.obs (T.evolve d))
      ≤ T.Cstar * M.mismatch zh (T.evolve d) :=
        hboot _ (T.evolve_mem_family hd) zh hadm hsmall'
    _ ≤ T.Cstar * (max 1 a⁻¹ * (ι + a * (η + M.harm zh))) :=
        mul_le_mul_of_nonneg_left hmisK T.Cstar_nonneg
    _ = T.shadowConst c τ * (ι + c * Real.sqrt τ * (η + M.harm zh)) := by
        simp only [CauchyTube.shadowConst, ha_def]; ring

/-! ### Composition with the initial retraction -/

section Retraction

variable [NormedSpace ℝ X] {Y : Type*} [AddCommGroup Y] [Module ℝ Y] {Ck : X → Y}

/-- The budget `𝔡_h = 2B_*γ_*⁻¹β_h + C_R√T η_{h,k}` of `eq:aposteriori-shadow-budget`. -/
def shadowBudget (B γ β c τ η : ℝ) : ℝ := 2 * B * γ⁻¹ * β + c * Real.sqrt τ * η

/-- The enlarged budget of `eq:shadow-harmonic-budget`, with a complementary initial correction
`ζ` (`rem:initial-correction-bookkeeping`):
`𝔡_h^C = ζ + 2B_*γ_*⁻¹β_h + C_R√T(η_{h,k} + γ̂_{h,k})`. -/
def harmonicBudget (ζ B γ β c τ η γh : ℝ) : ℝ :=
  ζ + 2 * B * γ⁻¹ * β + c * Real.sqrt τ * (η + γh)

/-- **The shadow from the output of an initial retraction.**  If the retained map `Φ_h` of an exact
reduction has a unique zero in the ball of radius `ρ`, every such zero gives an exactly compatible
datum at distance `≤ δ` from the base point `x0`, the base point is `ζ`-close to the record's
initial
state, and the corrected data lie in the tube, then the corrected datum generates the unique exact
solution and the shadow bound holds with budget `ζ + δ + c√τ(η + γ̂)`. -/
theorem shadow_of_retraction (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {zh : Z} (hadm : M.Admissible zh) {x0 : X} {m : ℕ} {r B : ℝ}
    (R : ExactInitialConstraintReduction Ck x0 m r B) {ρ δ ζ η c τ : ℝ}
    (hret : (∃! l, l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) ρ ∧ R.retained l = 0) ∧
      ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) ρ, R.retained l = 0 →
        Ck (R.corr l) = 0 ∧ ‖R.corr l - x0‖ ≤ δ)
    (hbase : ‖M.init zh - x0‖ ≤ ζ)
    (htube : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) ρ, R.retained l = 0 →
      R.corr l ∈ T.Creg ∩ T.nbhd)
    (hc : 0 < c) (hτ : 0 < τ) (hforce : M.resB zh + M.resD zh ≤ η)
    (hsmall : ζ + δ + c * Real.sqrt τ * (η + M.harm zh) ≤ T.stabilityRadius c τ) :
    ∃ l, (l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) ρ ∧ R.retained l = 0) ∧
      (∀ l', l' ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) ρ ∧ R.retained l' = 0 → l' = l) ∧
      Ck (R.corr l) = 0 ∧ ‖R.corr l - x0‖ ≤ δ ∧
      M.IsExact (T.evolve (R.corr l)) ∧ M.init (T.evolve (R.corr l)) = R.corr l ∧
      (∀ z, M.IsExact z → M.init z = R.corr l → z = T.evolve (R.corr l)) ∧
      dist (M.obs zh) (M.obs (T.evolve (R.corr l))) ≤
        T.shadowConst c τ * (ζ + δ + c * Real.sqrt τ * (η + M.harm zh)) := by
  obtain ⟨l, ⟨hl, h0⟩, huniq⟩ := hret.1
  obtain ⟨hC, hdisp⟩ := hret.2 l hl h0
  have hinit : ‖M.init zh - R.corr l‖ ≤ ζ + δ := by
    calc ‖M.init zh - R.corr l‖ = ‖(M.init zh - x0) + (x0 - R.corr l)‖ := by congr 1; abel
      _ ≤ ‖M.init zh - x0‖ + ‖x0 - R.corr l‖ := norm_add_le _ _
      _ ≤ ζ + δ := add_le_add hbase (by rw [norm_sub_rev]; exact hdisp)
  obtain ⟨hex, hin, hun, hdist⟩ :=
    shadow_of_datum M T hboot hadm (htube l hl h0) hc hτ hinit hforce hsmall
  exact ⟨l, ⟨hl, h0⟩, fun l' hl' => huniq l' hl', hC, hdisp, hex, hin, hun, hdist⟩

/-- **`thm:aposteriori-physical-shadow`** (conditional on the conclusion of the open
`prop:coupled-bootstrap`, carried as `hboot`).  Assume `ass:physical-Cauchy-tube` (`T`), a complete
normalized record `ẑ_h` (`zh`, admissible, in the harmonic/temporal chart: `C(ĝ_h) = 0`) with
forcing `‖𝓡_B‖_{L²H^k} + ‖𝓡_D‖_{L²H^{k+1}} ≤ η_{h,k}` (the output of
`prop:shadow-residual-upgrade`), the exact initial reduction of `def:exact-initial-reduction` at
`𝒰(ẑ_h)(0)` with the retraction hypotheses of `prop:initial-constraint-retraction`
(`σ_min(DΦ_h(0)) ≥ γ_*`, `‖DΦ_h(λ) - DΦ_h(0)‖ ≤ γ_*/2`, `c_h = |Φ_h(0)| ≤ β_h`,
`2γ_*⁻¹β_h ≤ r_*`), the corrected data in `𝒞_k^reg ∩ 𝒪_k`, and
`𝔡_h = 2B_*γ_*⁻¹β_h + C_R√T η_{h,k}` below the uniform stability radius.  Then there is a unique
zero `λ_h`, the corrected datum `d_h = ι_h(λ_h)` is exactly compatible with
`‖d_h - 𝒰(ẑ_h)(0)‖ ≤ 2B_*γ_*⁻¹β_h`, the tube generates the exact solution `z_{*,h}` with datum
`d_h`,
unique in the declared gauge class, and `eq:aposteriori-physical-shadow` holds:
(state + curvature + stress distance) `≤ C 𝔡_h` with `C = C_* max(1, (C_R√T)⁻¹)`. -/
theorem aposteriori_physical_shadow (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {zh : Z} (hadm : M.Admissible zh) (hharm : M.harm zh = 0) {m : ℕ} {r B : ℝ}
    (R : ExactInitialConstraintReduction Ck (M.init zh) m r B) {γ β η c τ : ℝ} (hγ : 0 < γ)
    (hA : ∀ v, γ * ‖v‖ ≤ ‖fderivWithin ℝ R.retained (closedBall 0 r) 0 v‖)
    (hmargin : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) r,
      ‖fderivWithin ℝ R.retained (closedBall 0 r) l -
        fderivWithin ℝ R.retained (closedBall 0 r) 0‖ ≤ γ / 2)
    (hres : ‖R.retained 0‖ ≤ β) (hrad : 2 * γ⁻¹ * β ≤ r) (hB : 0 ≤ B)
    (htube : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β), R.retained l = 0 →
      R.corr l ∈ T.Creg ∩ T.nbhd)
    (hc : 0 < c) (hτ : 0 < τ) (hforce : M.resB zh + M.resD zh ≤ η)
    (hsmall : shadowBudget B γ β c τ η ≤ T.stabilityRadius c τ) :
    ∃ l, (l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β) ∧ R.retained l = 0) ∧
      (∀ l', l' ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β) ∧
        R.retained l' = 0 → l' = l) ∧
      Ck (R.corr l) = 0 ∧ ‖R.corr l - M.init zh‖ ≤ 2 * B * γ⁻¹ * β ∧
      M.IsExact (T.evolve (R.corr l)) ∧ M.init (T.evolve (R.corr l)) = R.corr l ∧
      (∀ z, M.IsExact z → M.init z = R.corr l → z = T.evolve (R.corr l)) ∧
      dist (M.obs zh) (M.obs (T.evolve (R.corr l))) ≤
        T.shadowConst c τ * shadowBudget B γ β c τ η := by
  have hret := initialConstraintRetraction_derivAtZero R hγ hA hmargin hres hrad hB
  have e : (0 : ℝ) + 2 * B * γ⁻¹ * β + c * Real.sqrt τ * (η + M.harm zh) =
      shadowBudget B γ β c τ η := by rw [hharm, shadowBudget]; ring
  have hbase : ‖M.init zh - M.init zh‖ ≤ 0 := by simp
  have := shadow_of_retraction M T hboot hadm R hret hbase htube hc hτ hforce
    (by rw [e]; exact hsmall)
  rwa [e] at this

/-- **`cor:shadow-harmonic-defect`** (conditional on the conclusion of the open
`prop:coupled-bootstrap`).  The normalized record need only be approximately harmonic, with
harmonic-defect norm `γ̂_{h,k} = ‖C(ĝ_h)‖_{L²H^{k+1}} + ‖∂_tC(ĝ_h)‖_{L²H^k}` (`M.harm zh`); a
nonzero
complementary initial correction (`rem:initial-correction-bookkeeping`: the base point `x0` of the
reduction is `ζ`-close to `𝒰(ẑ_h)(0)`) and an arbitrary frozen matrix `A` with
`σ_min(A) ≥ γ_*`, `‖DΦ_h - A‖ ≤ γ_*/2` are allowed.  If the enlarged budget
`𝔡_h^C = ζ + 2B_*γ_*⁻¹β_h + C_R√T(η_{h,k} + γ̂_{h,k})` lies within the same stability radius, the
exact solution from the corrected datum satisfies `eq:aposteriori-physical-shadow` with `𝔡_h^C`. -/
theorem shadow_harmonic_defect (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {zh : Z} (hadm : M.Admissible zh) {x0 : X} {m : ℕ} {r B : ℝ}
    (R : ExactInitialConstraintReduction Ck x0 m r B)
    (A : EuclideanSpace ℝ (Fin m) →L[ℝ] EuclideanSpace ℝ (Fin m)) {γ β ζ η c τ : ℝ} (hγ : 0 < γ)
    (hA : ∀ v, γ * ‖v‖ ≤ ‖A v‖)
    (hmargin : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) r,
      ‖fderivWithin ℝ R.retained (closedBall 0 r) l - A‖ ≤ γ / 2)
    (hres : ‖R.retained 0‖ ≤ β) (hrad : 2 * γ⁻¹ * β ≤ r) (hB : 0 ≤ B)
    (hbase : ‖M.init zh - x0‖ ≤ ζ)
    (htube : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β), R.retained l = 0 →
      R.corr l ∈ T.Creg ∩ T.nbhd)
    (hc : 0 < c) (hτ : 0 < τ) (hforce : M.resB zh + M.resD zh ≤ η)
    (hsmall : harmonicBudget ζ B γ β c τ η (M.harm zh) ≤ T.stabilityRadius c τ) :
    ∃ l, (l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β) ∧ R.retained l = 0) ∧
      (∀ l', l' ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * β) ∧
        R.retained l' = 0 → l' = l) ∧
      Ck (R.corr l) = 0 ∧ ‖R.corr l - x0‖ ≤ 2 * B * γ⁻¹ * β ∧
      M.IsExact (T.evolve (R.corr l)) ∧ M.init (T.evolve (R.corr l)) = R.corr l ∧
      (∀ z, M.IsExact z → M.init z = R.corr l → z = T.evolve (R.corr l)) ∧
      dist (M.obs zh) (M.obs (T.evolve (R.corr l))) ≤
        T.shadowConst c τ * harmonicBudget ζ B γ β c τ η (M.harm zh) :=
  shadow_of_retraction M T hboot hadm R (initialConstraintRetraction R A hγ hA hmargin hres hrad hB)
    hbase htube hc hτ hforce hsmall

/-- **`cor:shadow-harmonic-defect`, validated form**: with an evaluated reduced map `Φ̃_h` and the
margins of `cor:validated-initial-retraction`, the enlarged budget is taken with
`β^eff = |Φ̃_h(0)| + ζ₀` (an exact zero of `Φ̃_h` does not remove `ζ₀`). -/
theorem shadow_harmonic_defect_validated (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {zh : Z} (hadm : M.Admissible zh) {x0 : X} {m : ℕ} {r B : ℝ}
    (R : ExactInitialConstraintReduction Ck x0 m r B)
    (Φt : EuclideanSpace ℝ (Fin m) → EuclideanSpace ℝ (Fin m))
    (hΦt : ContDiffOn ℝ 1 Φt (closedBall 0 r)) {γ ζ₀ ζ η c τ : ℝ} (hγ : 0 < γ)
    (hA : ∀ v, γ * ‖v‖ ≤ ‖fderivWithin ℝ Φt (closedBall 0 r) 0 v‖)
    (hmarginEval : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) r,
      ‖fderivWithin ℝ Φt (closedBall 0 r) l - fderivWithin ℝ Φt (closedBall 0 r) 0‖ ≤ γ / 4)
    (hmarginExact : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) r,
      ‖fderivWithin ℝ R.retained (closedBall 0 r) l - fderivWithin ℝ Φt (closedBall 0 r) l‖ ≤
        γ / 4)
    (hζ₀ : ‖R.retained 0 - Φt 0‖ ≤ ζ₀)
    (hrad : 2 * γ⁻¹ * (‖Φt 0‖ + ζ₀) ≤ r) (hB : 0 ≤ B)
    (hbase : ‖M.init zh - x0‖ ≤ ζ)
    (htube : ∀ l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * (‖Φt 0‖ + ζ₀)),
      R.retained l = 0 → R.corr l ∈ T.Creg ∩ T.nbhd)
    (hc : 0 < c) (hτ : 0 < τ) (hforce : M.resB zh + M.resD zh ≤ η)
    (hsmall : harmonicBudget ζ B γ (‖Φt 0‖ + ζ₀) c τ η (M.harm zh) ≤ T.stabilityRadius c τ) :
    ∃ l, (l ∈ closedBall (0 : EuclideanSpace ℝ (Fin m)) (2 * γ⁻¹ * (‖Φt 0‖ + ζ₀)) ∧
        R.retained l = 0) ∧
      Ck (R.corr l) = 0 ∧ ‖R.corr l - x0‖ ≤ 2 * B * γ⁻¹ * (‖Φt 0‖ + ζ₀) ∧
      M.IsExact (T.evolve (R.corr l)) ∧
      (∀ z, M.IsExact z → M.init z = R.corr l → z = T.evolve (R.corr l)) ∧
      dist (M.obs zh) (M.obs (T.evolve (R.corr l))) ≤
        T.shadowConst c τ * harmonicBudget ζ B γ (‖Φt 0‖ + ζ₀) c τ η (M.harm zh) := by
  obtain ⟨l, hl, -, hC, hd, hex, -, hun, hdist⟩ :=
    shadow_of_retraction M T hboot hadm R
      (validatedInitialRetraction R Φt hΦt hγ hA hmarginEval hmarginExact hζ₀ hrad hB)
      hbase htube hc hτ hforce hsmall
  exact ⟨l, hl, hC, hd, hex, hun, hdist⟩

end Retraction

/-! ### The continuum-limit assertion -/

section Limit

variable {Y : Type*} [Zero Y] {Ck : X → Y}

/-- **Final assertion of `thm:aposteriori-physical-shadow`** (conditional on the conclusion of the
open `prop:coupled-bootstrap`).  If corrected data `d_h ∈ 𝒞_k^reg ∩ 𝒪_k` converge in `H^k` to
`d_∞ ∈ 𝒞_k^reg ∩ 𝒪_k` (a Cauchy class in which the physical solution is unique) and the exact
shadows are admissible smooth records, then the shadows converge to the unique exact solution
`z_∞` with datum `d_∞` (continuous dependence: the bootstrap with reference `z_∞` applied to the
exact
solution `z_{*,h}`, whose mismatch is `‖d_h - d_∞‖`); and if the certified records satisfy
`dist(obs ẑ_h, obs z_{*,h}) ≤ C 𝔡_h` with `𝔡_h → 0`, they have the same continuum limit. -/
theorem aposteriori_shadow_limit (T : CauchyTube M Ck)
    (hboot : CoupledBootstrapConclusion M T.family T.dstar T.Cstar)
    {ι : Type*} {l : Filter ι} (d : ι → X) {dinf : X} (hd : ∀ i, d i ∈ T.Creg ∩ T.nbhd)
    (hdinf : dinf ∈ T.Creg ∩ T.nbhd) (hadm : ∀ i, M.Admissible (T.evolve (d i)))
    (hconv : Tendsto d l (𝓝 dinf)) :
    (∀ z, M.IsExact z → M.init z = dinf → z = T.evolve dinf) ∧
      Tendsto (fun i => dist (M.obs (T.evolve (d i))) (M.obs (T.evolve dinf))) l (𝓝 0) ∧
      ∀ (zh : ι → Z) (𝔡 : ι → ℝ) (C : ℝ), Tendsto 𝔡 l (𝓝 0) →
        (∀ᶠ i in l, dist (M.obs (zh i)) (M.obs (T.evolve (d i))) ≤ C * 𝔡 i) →
        Tendsto (fun i => dist (M.obs (zh i)) (M.obs (T.evolve dinf))) l (𝓝 0) := by
  have hmis : ∀ i, M.mismatch (T.evolve (d i)) (T.evolve dinf) = ‖d i - dinf‖ := by
    intro i
    have hex := T.evolve_exact (d i) (hd i)
    simp [SlabModel.mismatch, T.evolve_init (d i) (hd i), T.evolve_init dinf hdinf,
      M.exact_resB _ hex, M.exact_resD _ hex, M.exact_harm _ hex]
  have hn : Tendsto (fun i => ‖d i - dinf‖) l (𝓝 0) := by
    simpa using (hconv.sub_const dinf).norm
  have hev : ∀ᶠ i in l, ‖d i - dinf‖ < T.dstar := hn.eventually (gt_mem_nhds T.dstar_pos)
  have hshadow : Tendsto (fun i => dist (M.obs (T.evolve (d i))) (M.obs (T.evolve dinf))) l
      (𝓝 0) := by
    have hup : Tendsto (fun i => T.Cstar * ‖d i - dinf‖) l (𝓝 0) := by
      simpa using hn.const_mul T.Cstar
    refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds hup
      (Eventually.of_forall fun i => dist_nonneg) ?_
    filter_upwards [hev] with i hi
    have := hboot _ (T.evolve_mem_family hdinf) _ (hadm i) (by rw [hmis]; exact hi.le)
    rwa [hmis] at this
  refine ⟨T.evolve_unique dinf hdinf, hshadow, fun zh 𝔡 C h𝔡 hrec => ?_⟩
  have hup : Tendsto (fun i => C * 𝔡 i + dist (M.obs (T.evolve (d i))) (M.obs (T.evolve dinf)))
      l (𝓝 0) := by simpa using (h𝔡.const_mul C).add hshadow
  refine tendsto_of_tendsto_of_tendsto_of_le_of_le' tendsto_const_nhds hup
    (Eventually.of_forall fun i => dist_nonneg) ?_
  filter_upwards [hrec] with i hi
  exact (dist_triangle _ _ _).trans (by linarith)

end Limit

/-! ### Non-vacuity -/

/-- A trivial slab model on `ℝ` (records are their initial data, no residuals). -/
def trivialModel : SlabModel ℝ ℝ ℝ where
  init := id
  obs := id
  resB := fun _ => 0
  resD := fun _ => 0
  harm := fun _ => 0
  Admissible := fun _ => True
  IsExact := fun _ => True
  resB_nonneg := fun _ => le_rfl
  resD_nonneg := fun _ => le_rfl
  harm_nonneg := fun _ => le_rfl
  exact_resB := fun _ _ => rfl
  exact_resD := fun _ _ => rfl
  exact_harm := fun _ _ => rfl

/-- The whole line as a Cauchy tube for the zero constraint map. -/
def trivialTube : CauchyTube trivialModel (fun _ : ℝ => (0 : ℝ)) where
  Creg := Set.univ
  Creg_constraint := fun _ _ => rfl
  hiNorm := fun _ => 0
  hiBound := 0
  Creg_hi := fun _ _ => le_rfl
  nbhd := Set.univ
  nbhd_open := isOpen_univ
  evolve := id
  evolve_exact := fun _ _ => trivial
  evolve_init := fun _ _ => rfl
  evolve_unique := fun _ _ _ _ h => h
  InChart := fun _ => True
  evolve_chart := fun _ _ => trivial
  stateHi := fun _ => 0
  stateBound := 0
  evolve_stateHi := fun _ _ => le_rfl
  dstar := 1
  Cstar := 1
  dstar_pos := one_pos
  Cstar_nonneg := zero_le_one

/-- The bootstrap conclusion holds in the trivial model (`C_* = 1`). -/
theorem trivial_bootstrap :
    CoupledBootstrapConclusion trivialModel trivialTube.family trivialTube.dstar
      trivialTube.Cstar := by
  intro zs _ zh _ _
  simp [trivialModel, trivialTube, SlabModel.mismatch, Real.dist_eq]

/-- The zero-dimensional exact reduction at a datum `x0` (no retained constraints). -/
def trivialReduction (x0 : ℝ) :
    ExactInitialConstraintReduction (fun _ : ℝ => (0 : ℝ)) x0 0 1 0 where
  corr := fun _ => x0
  corr_contDiffOn := contDiffOn_const
  embed := 0
  embed_injective := Function.injective_of_subsingleton _
  retained := fun _ => 0
  retained_contDiffOn := contDiffOn_const
  basepoint := rfl
  factorization := fun _ _ => by simp
  lipschitz := fun _ _ _ _ => by simp

/-- **Non-vacuity** of the hypothesis packet of `aposteriori_physical_shadow` (tube, bootstrap
conclusion, exact reduction with its margins, tube membership, forcing and smallness). -/
example (x0 : ℝ) : ∃ l : EuclideanSpace ℝ (Fin 0),
    dist (trivialModel.obs x0) (trivialModel.obs (trivialTube.evolve
      ((trivialReduction x0).corr l))) ≤
      trivialTube.shadowConst 1 1 * shadowBudget 0 1 0 1 1 0 := by
  obtain ⟨l, -, -, -, -, -, -, -, hd⟩ := aposteriori_physical_shadow trivialModel trivialTube
    trivial_bootstrap (zh := x0) trivial rfl (trivialReduction x0) (γ := 1) (β := 0) (η := 0)
    (c := 1) (τ := 1) one_pos (fun v => by simp [Subsingleton.elim v 0])
    (fun l _ => by
      rw [Subsingleton.elim (fderivWithin ℝ (trivialReduction x0).retained (closedBall 0 1) l -
        fderivWithin ℝ (trivialReduction x0).retained (closedBall 0 1) 0) 0]
      simp)
    (by simp [trivialReduction]) (by norm_num) le_rfl (fun _ _ _ => ⟨trivial, trivial⟩)
    one_pos one_pos (by simp [trivialModel]) (by
      simp [shadowBudget, CauchyTube.stabilityRadius, trivialTube])
  exact ⟨l, hd⟩

end

end RenewalGeometry.AposterioriShadow
