/-
Copyright (c) 2026 Aurelien Pelissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurelien Pelissier
-/
import Mathlib
import Mathlib.Topology.MetricSpace.Lipschitz

/-!
# Approximation singular values

The `(k+1)`st approximation singular value of a finite Euclidean operator is
its operator-norm distance to the operators of rank at most `k`.  This
characterization makes the sharp Weyl perturbation estimate an immediate
consequence of the one-Lipschitz property of distance to a set.
-/

namespace NCG

/-! ## Coordinate-free approximation numbers -/

section ApproximationNumbers

variable {𝕜 E F : Type*} [NontriviallyNormedField 𝕜]
  [NormedAddCommGroup E] [NormedSpace 𝕜 E]
  [NormedAddCommGroup F] [NormedSpace 𝕜 F]
  [FiniteDimensional 𝕜 F]

/-- Rank of a continuous linear operator, measured by the dimension of its
range.  This is finite whenever the target is finite-dimensional. -/
noncomputable def continuousOperatorRank (A : E →L[𝕜] F) : ℕ :=
  Module.finrank 𝕜 A.range

/-- Continuous operators whose range has dimension at most `k`. -/
def continuousOperatorsOfRankAtMost (k : ℕ) : Set (E →L[𝕜] F) :=
  {A | continuousOperatorRank A ≤ k}

theorem continuousOperatorsOfRankAtMost_nonempty (k : ℕ) :
    (continuousOperatorsOfRankAtMost k : Set (E →L[𝕜] F)).Nonempty := by
  refine ⟨0, ?_⟩
  change continuousOperatorRank (0 : E →L[𝕜] F) ≤ k
  rw [show continuousOperatorRank (0 : E →L[𝕜] F) = 0 by
    simp [continuousOperatorRank, LinearMap.range_eq_bot]]
  exact Nat.zero_le k

/-- The `(k+1)`st approximation number: operator-norm distance to rank at
most `k`.  On finite-dimensional Hilbert spaces this is the
Eckart--Young characterization of the `(k+1)`st singular value. -/
noncomputable def approximationNumber (A : E →L[𝕜] F) (k : ℕ) : ℝ :=
  Metric.infDist A (continuousOperatorsOfRankAtMost k)

theorem approximationNumber_nonneg (A : E →L[𝕜] F) (k : ℕ) :
    0 ≤ approximationNumber A k :=
  Metric.infDist_nonneg

theorem approximationNumber_eq_zero_of_rank_le
    (A : E →L[𝕜] F) (k : ℕ) (hA : continuousOperatorRank A ≤ k) :
    approximationNumber A k = 0 := by
  exact Metric.infDist_zero_of_mem
    (show A ∈ continuousOperatorsOfRankAtMost k from hA)

theorem approximationNumber_antitone (A : E →L[𝕜] F) :
    Antitone (approximationNumber A) := by
  intro i j hij
  exact Metric.infDist_le_infDist_of_subset
    (fun B hB => le_trans hB hij)
    (continuousOperatorsOfRankAtMost_nonempty i)

/-- Sharp one-Lipschitz/Weyl perturbation estimate for approximation
numbers. -/
theorem approximationNumber_weyl (A B : E →L[𝕜] F) (k : ℕ) :
    |approximationNumber A k - approximationNumber B k| ≤ ‖A - B‖ := by
  have h := (Metric.lipschitz_infDist_pt
    (s := continuousOperatorsOfRankAtMost k)).dist_le_mul A B
  simpa [approximationNumber, Real.dist_eq, dist_eq_norm] using h

/-- Exact best-rank-one formula for the second approximation singular
value. -/
theorem secondApproximationNumber_eq_distance_to_rankOne
    (A : E →L[𝕜] F) :
    approximationNumber A 1 =
      Metric.infDist A (continuousOperatorsOfRankAtMost 1) :=
  rfl

end ApproximationNumbers

/-! ## Topology-independent linear approximation numbers

The following equivalent presentation spells out operator-norm error through
its defining uniform bound.  It is useful for finite-dimensional subtypes
whose induced topology is propositionally, but not definitionally, the
topology generated by their norm. -/

section LinearApproximationNumbers

variable {𝕜 E F : Type*} [Field 𝕜]
  [AddCommGroup E] [Module 𝕜 E] [Norm E]
  [AddCommGroup F] [Module 𝕜 F] [Norm F]
  [FiniteDimensional 𝕜 F]

/-- Operator-norm distance between two linear maps, written directly as the
infimum of all uniform Lipschitz bounds for their difference. -/
noncomputable def linearOperatorNormDistance
    (A B : E →ₗ[𝕜] F) : ℝ :=
  sInf {c : ℝ | 0 ≤ c ∧ ∀ x, ‖(A - B) x‖ ≤ c * ‖x‖}

/-- Linear maps whose range has dimension at most `k`. -/
def linearOperatorsOfRankAtMost (k : ℕ) : Set (E →ₗ[𝕜] F) :=
  {A | Module.finrank 𝕜 A.range ≤ k}

/-- Exact operator-norm distance from a linear map to maps of rank at most
`k`, without packaging the maps as continuous linear maps. -/
noncomputable def linearDistanceToRankAtMost
    (A : E →ₗ[𝕜] F) (k : ℕ) : ℝ :=
  sInf {d : ℝ | ∃ B ∈ linearOperatorsOfRankAtMost k,
    d = linearOperatorNormDistance A B}

/-- The `(k+1)`st linear approximation singular value. -/
noncomputable def linearApproximationNumber
    (A : E →ₗ[𝕜] F) (k : ℕ) : ℝ :=
  linearDistanceToRankAtMost A k

/-- Exact best-rank-one formula for the second linear approximation singular
value. -/
theorem secondLinearApproximationNumber_eq_distance_to_rankOne
    (A : E →ₗ[𝕜] F) :
    linearApproximationNumber A 1 = linearDistanceToRankAtMost A 1 :=
  rfl

end LinearApproximationNumbers

variable {m n : Type*} [Fintype m] [Fintype n]

/-- Continuous operators between finite complex Euclidean spaces. -/
abbrev EuclideanOperator (m n : Type*) [Fintype m] [Fintype n] :=
  EuclideanSpace ℂ n →L[ℂ] EuclideanSpace ℂ m

/-- Operator rank, as the complex dimension of the range. -/
noncomputable def euclideanOperatorRank (A : EuclideanOperator m n) : ℕ :=
  Module.finrank ℂ A.range

/-- Operators with rank at most `k`. -/
def operatorsOfRankAtMost (k : ℕ) : Set (EuclideanOperator m n) :=
  {A | euclideanOperatorRank A ≤ k}

theorem operatorsOfRankAtMost_nonempty (k : ℕ) :
    (operatorsOfRankAtMost k : Set (EuclideanOperator m n)).Nonempty := by
  refine ⟨0, ?_⟩
  change euclideanOperatorRank (0 : EuclideanOperator m n) ≤ k
  rw [show euclideanOperatorRank (0 : EuclideanOperator m n) = 0 by
    simp [euclideanOperatorRank]]
  exact Nat.zero_le k

/-- The `(k+1)`st singular value in its best rank-`k` approximation
characterization. -/
noncomputable def approximationSingularValue
    (A : EuclideanOperator m n) (k : ℕ) : ℝ :=
  Metric.infDist A (operatorsOfRankAtMost k)

theorem approximationSingularValue_nonneg
    (A : EuclideanOperator m n) (k : ℕ) :
    0 ≤ approximationSingularValue A k :=
  Metric.infDist_nonneg

theorem approximationSingularValue_eq_zero_of_rank_le
    (A : EuclideanOperator m n) (k : ℕ)
    (hA : euclideanOperatorRank A ≤ k) :
    approximationSingularValue A k = 0 := by
  exact Metric.infDist_zero_of_mem
    (show A ∈ operatorsOfRankAtMost k from hA)

theorem approximationSingularValue_antitone
    (A : EuclideanOperator m n) : Antitone (approximationSingularValue A) := by
  intro i j hij
  exact Metric.infDist_le_infDist_of_subset
    (fun B hB => le_trans hB hij)
    (operatorsOfRankAtMost_nonempty i)

/-- Sharp Weyl stability for approximation singular values. -/
theorem approximationSingularValue_weyl
    (A B : EuclideanOperator m n) (k : ℕ) :
    |approximationSingularValue A k - approximationSingularValue B k| ≤
      ‖A - B‖ := by
  have h := (Metric.lipschitz_infDist_pt
    (s := operatorsOfRankAtMost k)).dist_le_mul A B
  simpa [approximationSingularValue, Real.dist_eq, dist_eq_norm] using h

theorem approximationSingularValue_lower_perturbation
    (A B : EuclideanOperator m n) (k : ℕ) :
    approximationSingularValue B k - ‖A - B‖ ≤
      approximationSingularValue A k := by
  have h := abs_le.mp (approximationSingularValue_weyl A B k)
  linarith [h.1]

theorem approximationSingularValue_upper_perturbation
    (A B : EuclideanOperator m n) (k : ℕ) :
    approximationSingularValue A k ≤
      approximationSingularValue B k + ‖A - B‖ := by
  have h := abs_le.mp (approximationSingularValue_weyl A B k)
  linarith [h.2]

end NCG
