/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Flagship.PredictiveRN
import NCG.Flagship.MinimalNaturality
import NCG.Flagship.StoreFrequencyCount
import NCG.Flagship.AnalyticPolar
import NCG.Flagship.OddRead
import NCG.Flagship.AnchorClifford

/-!
# Predictive Store–control finite closure and the reduced cell
  (`thm:predictive-clock-discharge`,
   `cor:reduced-hypothesis-spacetime`, flagship manuscript)

* `predictive_clock_discharge`: the integrated finite closure —
  one theorem consuming the entry data of the constituent proved
  records and returning, in a single conjunction, (i) the
  canonical predictive Radon–Nikodym envelope with domination and
  the automatic naturality of the minimal Store realization,
  (ii) exact finite Store-jet reconstruction (positive-definite
  moment pencil and exact Hankel rank count), (iii) the physical
  polar quarter-root generated by finite Store/control words,
  (iv) the sharp transverse exchange-covariant Read on the loaded
  future-distinct odd line, (v) the negative-square temporal
  generator, and (vi) the marked `M₄(ℂ) ≅ Cl₁,₃(ℂ)` external
  factor with the complete six-direction Read;
* `record_group_closure`: the three signed external direction
  records generate the full accumulated record group `ℤ³`;
* `lorentzian_principal_symbol`: the boxed identity
  `𝒟(ξ)² = (-ξ₀² + |ξ⃗|²)I₄` for
  `𝒟(ξ) = ξ₀γ⁰ + ξ₁γ¹ + ξ₂γ² + ξ₃γ³`, from the certified
  Clifford relations of the anchor record;
* `reduced_hypothesis_spacetime`: the corollary's finite
  conjunction — record group and Lorentzian principal symbol.

Rendering disclosed: each displayed hypothesis of the closure is
the entry assumption of the correspondingly cited proved record
(`thm:predictive-RN-master`,
`thm:minimal-realization-naturality-master`,
`thm:store-frequency-pencil-master`,
`cor:store-frequency-count-master`,
`cor:real-score-polar-master`, `thm:consequential-odd-read-master`,
`thm:anchor-external-clifford-master`), which the manuscript
derives from `ass:predictive-clock-entry`; the completely
predictive external replacement/twirl reset (item (vii)) is the
uniform average of the generated finite Pauli action (prose on
top of `clifford_algebra_top`); for the corollary, the unique
positive renewal-pressure root and the strong-resolvent flat
convergence to the massless `(3+1)` Dirac Hamiltonian are the
manuscript's retained common-core inputs, and the curved
Levi–Civita alternative is decided by
`thm:physical-connection-master`, not here.
-/

open Matrix Kronecker NormedSpace
open scoped ComplexOrder

namespace NCG

/-- `thm:predictive-clock-discharge`: the integrated finite
closure — the entry data of the constituent proved records return
the seven-item conclusion in one conjunction. -/
theorem predictive_clock_discharge
    -- (i) predictive envelope: refined Stinespring data of the cell
    {Kd Ed Hd : Type*} [Fintype Kd] [Fintype Ed] [Fintype Hd]
    [DecidableEq Kd] [DecidableEq Ed] [Nonempty Kd]
    (V' V : Matrix (Kd × Ed) Hd ℂ)
    {F : Matrix Ed Ed ℂ} {X : Matrix Kd Kd ℂ}
    (hF : F.PosSemidef)
    (hF1 : ((1 : Matrix Ed Ed ℂ) - F).PosSemidef)
    (hX : X.PosSemidef)
    -- (i) naturality entry: covariance and minimality of the stack
    (Ug : Matrix Hd Hd ℂ) (Zg : Matrix Kd Kd ℂ)
    (hcov : ∀ Y : Matrix Kd Kd ℂ,
      Ugᴴ * (Vᴴ * (Y ⊗ₖ (1 : Matrix Ed Ed ℂ)) * V) * Ug
        = Vᴴ * ((Zgᴴ * Y * Zg) ⊗ₖ (1 : Matrix Ed Ed ℂ)) * V)
    (hmin : Function.Surjective
      (stineStack ((Zg ⊗ₖ (1 : Matrix Ed Ed ℂ)) * V)).mulVec)
    -- (ii) loaded Store spectrum: positive weights, distinct rates
    {s : ℕ} (w lam : Fin s → ℝ) (hw : ∀ j, 0 < w j)
    (hinj : Function.Injective lam) (r : ℕ)
    -- (iii) polar entry: finite Store/control word pair
    {𝔸 : Type*} [NormedRing 𝔸] [NormedAlgebra ℝ 𝔸]
    [CompleteSpace 𝔸]
    (R R' G G' : 𝔸) (h1 : R * R' = 1) (h2 : R' * R = 1)
    (hgen : R * G * R' = G')
    -- (iv) loaded future-distinct exchange-odd line
    {Xm : Type*} [AddCommGroup Xm] [Module ℝ Xm]
    (adm : (Xm →ₗ[ℝ] ℝ) → Prop) (u : Xm →ₗ[ℝ] ℝ)
    (sw : Xm →ₗ[ℝ] Xm)
    (hss : sw ∘ₗ sw = LinearMap.id) (hus : u ∘ₗ sw = u)
    (d : Xm) (hsd : sw d = -d) (hud : u d = 0)
    (hcompl : ∀ f, adm f → adm (u - f))
    (hpull : ∀ f, adm f → adm (f ∘ₗ sw))
    (hmix : ∀ f g, adm f → adm g → adm ((2⁻¹ : ℝ) • (f + g)))
    (e : Xm →ₗ[ℝ] ℝ) (he : adm e) (hed : e d ≠ 0) :
    -- (i) canonical predictive RN envelope, dominated by the cell
    ((thetaV V' F X).PosSemidef
      ∧ (thetaV V' 1 X - thetaV V' F X).PosSemidef)
    -- (i) automatic naturality of the minimal Store realization
    ∧ (∃ W : Matrix Ed Ed ℂ, Wᴴ * W = 1
        ∧ (Zg ⊗ₖ W) * V = V * Ug
        ∧ ∀ W' : Matrix Ed Ed ℂ,
            (Zg ⊗ₖ W') * V = V * Ug → W' = W)
    -- (ii) exact finite Store-jet reconstruction
    ∧ ((storeH0 w lam).PosDef
        ∧ (hankelShell w lam r).rank = min (r + 1) s)
    -- (iii) the physical polar quarter-root by finite words
    ∧ R * exp G * R' = exp G'
    -- (iv) sharp transverse exchange-covariant Read
    ∧ (adm ((2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw)))
        ∧ adm (u - (2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw)))
        ∧ ((2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw))) ∘ₗ sw
            = u - (2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw))
        ∧ ((2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw))) d = e d
        ∧ (u - (2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw))) d = -(e d)
        ∧ ((2⁻¹ : ℝ) • (e + (u - e ∘ₗ sw))) d ≠ 0)
    -- (v) negative-square temporal generator
    ∧ gamma0 * gamma0 = -1
    -- (vi) marked M₄(ℂ) ≅ Cl₁,₃(ℂ) factor and six-direction Read
    ∧ (Algebra.adjoin ℂ ({gamma0, gamma1, gamma2, gamma3} :
          Set (Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ)) = ⊤
        ∧ ∀ i : Fin 3,
            gammaEffect i 1 + gammaEffect i (-1) = 1) :=
  ⟨⟨thetaV_posSemidef V' hF hX, thetaV_dominated V' hF1 hX⟩,
    minimal_realization_naturality V Ug Zg hcov hmin,
    ⟨storeH0_posDef w lam hw hinj,
      store_hankel_rank w lam hw hinj r⟩,
    real_score_polar R R' G G' h1 h2 hgen,
    consequential_odd_read adm u sw hss hus d hsd hud
      hcompl hpull hmix e he hed,
    gamma0_sq,
    clifford_algebra_top, gammaEffect_complete⟩

/-- The three signed external direction records generate the full
accumulated record group `ℤ³`. -/
theorem record_group_closure :
    AddSubgroup.closure
      (Set.range fun i : Fin 3 => Pi.single i (1 : ℤ)) = ⊤ := by
  rw [eq_top_iff]
  intro v _
  have hv : v = ∑ i : Fin 3, v i • Pi.single i (1 : ℤ) := by
    ext j
    simp [Pi.single_apply]
  rw [hv]
  exact AddSubgroup.sum_mem _ fun i _ =>
    AddSubgroup.zsmul_mem _
      (AddSubgroup.subset_closure (Set.mem_range_self i)) (v i)

/-- `cor:reduced-hypothesis-spacetime`, boxed identity: the
Lorentzian principal symbol `𝒟(ξ)² = (-ξ₀² + |ξ⃗|²)I₄`, from the
certified Clifford relations. -/
theorem lorentzian_principal_symbol (ξ0 ξ1 ξ2 ξ3 : ℂ) :
    (ξ0 • gamma0 + ξ1 • gamma1 + ξ2 • gamma2 + ξ3 • gamma3)
      * (ξ0 • gamma0 + ξ1 • gamma1 + ξ2 • gamma2 + ξ3 • gamma3)
    = (-ξ0 ^ 2 + ξ1 ^ 2 + ξ2 ^ 2 + ξ3 ^ 2)
        • (1 : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ) := by
  have h10 : gamma1 * gamma0 = -(gamma0 * gamma1) :=
    eq_neg_of_add_eq_zero_right gamma_anti_01
  have h20 : gamma2 * gamma0 = -(gamma0 * gamma2) :=
    eq_neg_of_add_eq_zero_right gamma_anti_02
  have h30 : gamma3 * gamma0 = -(gamma0 * gamma3) :=
    eq_neg_of_add_eq_zero_right gamma_anti_03
  have h21 : gamma2 * gamma1 = -(gamma1 * gamma2) :=
    eq_neg_of_add_eq_zero_right gamma_anti_12
  have h31 : gamma3 * gamma1 = -(gamma1 * gamma3) :=
    eq_neg_of_add_eq_zero_right gamma_anti_13
  have h32 : gamma3 * gamma2 = -(gamma2 * gamma3) :=
    eq_neg_of_add_eq_zero_right gamma_anti_23
  simp only [add_mul, mul_add, smul_mul_smul_comm,
    gamma0_sq, gamma1_sq, gamma2_sq, gamma3_sq,
    h10, h20, h30, h21, h31, h32, smul_neg]
  module

/-- `cor:reduced-hypothesis-spacetime`: the reduced-hypothesis
local Lorentzian cell — accumulated `ℤ³` record group and the
Lorentzian principal symbol. -/
theorem reduced_hypothesis_spacetime :
    (AddSubgroup.closure
        (Set.range fun i : Fin 3 => Pi.single i (1 : ℤ)) = ⊤)
    ∧ ∀ ξ0 ξ1 ξ2 ξ3 : ℂ,
        (ξ0 • gamma0 + ξ1 • gamma1 + ξ2 • gamma2 + ξ3 • gamma3)
          * (ξ0 • gamma0 + ξ1 • gamma1 + ξ2 • gamma2 + ξ3 • gamma3)
        = (-ξ0 ^ 2 + ξ1 ^ 2 + ξ2 ^ 2 + ξ3 ^ 2)
            • (1 : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ) :=
  ⟨record_group_closure, lorentzian_principal_symbol⟩

end NCG
