/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Analysis.CubeReflection
import RenewalGeometry.Analysis.SobolevBoxExtension
import RenewalGeometry.Analysis.TorusBoxRestriction

/-!
# Sobolev spaces of the cube `Q₀ = (0,1/2)⁴` through reflection to `𝕋⁴`
  (stage A2 of the cube rendering of Uhlenbeck's small-energy gauge theorem)

Generic infrastructure (no renewal notions) for `prop:critical-uhlenbeck` of the
Einstein–Standard-Model action-closure manuscript.

The cube `Q₀ = box 0 (1/2,…,1/2) ⊂ ℝ⁴` is a fundamental domain of the reflection group of
`𝕋⁴ = ℝ⁴/ℤ⁴` generated by `x_j ↦ -x_j` (mirrors `x_j ∈ {0, 1/2}`).  The folding map is the
coordinatewise **triangle wave** `tri t = dist(t, ℤ) ∈ [0,1/2]` (`tri`, `fold`), with slope
`sgnTri t = ±1`.  A function `u` on `Q₀` has the **parity extensions**

  `extR S u (y) = (∏_{i ∈ S} sgnTri(y_i)) · u(fold y)`  on `ℝ⁴` (`1`-periodic),
  `parExt S u (t) = extR S u (rep t)`                    on `𝕋⁴`

(odd in the directions of `S`, even in the others).  Main results:

* `lintegral_box_double`, `aestronglyMeasurable_box_double`, `memLp_box_double`: the reflection
  doubling of integrals over boxes for reflection-symmetric functions;
* `lintegral_parExt` (**norm transfer**): `∫_{𝕋⁴} ‖parExt S u‖ₑ^p = 16 ∫_{Q₀} ‖u‖ₑ^p`, and
  `memLp_parExt`, `eLpNorm_parExt` (`‖parExt S u‖_{L^p(𝕋⁴)} = 16^{1/p} ‖u‖_{L^p(Q₀)}`);
* `memW12_extR_box` (**even reflection in `W^{1,2}`**): for `u ∈ W^{1,2}(Q₀)` with weak gradient
  `g`, the even extension `extR ∅ u` is in `W^{1,2}((0,2)⁴)` with weak gradient `extR {i} (g i)`
  (eight one-face reflections of `SobolevBoxExtension.hasWeakPartial_reflExt` and the
  identification of each reflection with the folded function);
* `isTPartial_of_periodic` (**periodic Fourier rule from local weak derivatives**): a
  `1`-periodic function with a weak partial derivative on `(0,2)⁴` has, on `𝕋⁴`, the torus
  partial derivative given by the periodic weak derivative (telescoping partition of unity
  `ψ(t) = η(t) - η(t-1)`);
* `isTPartial_parExt` (**`W^{1,2}(Q₀)` = even `H¹(𝕋⁴)`**, cube-to-torus direction):
  `u ∈ W^{1,2}(Q₀) ⇒ parExt ∅ u ∈ H¹(𝕋⁴)` with `∂_i (parExt ∅ u) = parExt {i} (g i)`;
  `hasParity_parExt`: `parExt S u` has the parity pattern `S`.
-/

open MeasureTheory Filter Topology Set UnitAddTorus
open scoped ENNReal NNReal Real ComplexConjugate ContDiff

noncomputable section

namespace RenewalGeometry.CubeNeumann

open SobolevOpen TorusSobolev UhlenbeckTorus

set_option linter.unusedSectionVars false

attribute [local instance 2000] instMeasureSpaceUnitAddCircle

local instance : IsProbabilityMeasure (volume : Measure UnitAddCircle) :=
  inferInstanceAs (IsProbabilityMeasure AddCircle.haarAddCircle)

local notation "𝕋⁴" => UnitAddTorus (Fin 4)

/-! ### The triangle wave -/

/-- The triangle wave `tri t = min(fract t, 1 - fract t) = dist(t, ℤ) ∈ [0, 1/2]`. -/
def tri (t : ℝ) : ℝ := min (Int.fract t) (1 - Int.fract t)

/-- The slope of the triangle wave: `1` where `fract t < 1/2`, `-1` otherwise. -/
def sgnTri (t : ℝ) : ℝ := if Int.fract t < 1 / 2 then 1 else -1

theorem tri_of_mem {t : ℝ} (h0 : 0 ≤ t) (h1 : t ≤ 1 / 2) : tri t = t := by
  have hf : Int.fract t = t := Int.fract_eq_self.2 ⟨h0, by linarith⟩
  simp only [tri, hf]
  exact min_eq_left (by linarith)

theorem tri_add_one (t : ℝ) : tri (t + 1) = tri t := by simp [tri, Int.fract_add_one]

theorem tri_neg (t : ℝ) : tri (-t) = tri t := by
  by_cases h : Int.fract t = 0
  · have h' : Int.fract (-t) = 0 := by
      rw [Int.fract_eq_iff] at h ⊢
      obtain ⟨-, -, z, hz⟩ := h
      exact ⟨le_rfl, by norm_num, -z, by push_cast; linarith⟩
    simp [tri, h, h']
  · simp only [tri, Int.fract_neg h]
    rw [min_comm]; ring_nf

theorem tri_sub_of_int (t : ℝ) (k : ℤ) : tri (k - t) = tri t := by
  rw [show (k : ℝ) - t = -t + k by ring]
  simp only [tri, Int.fract_add_intCast]
  exact tri_neg t

theorem tri_one_sub (t : ℝ) : tri (1 - t) = tri t := by
  have := tri_sub_of_int t 1; simpa using this

theorem tri_two_sub (t : ℝ) : tri (2 - t) = tri t := by
  have := tri_sub_of_int t 2; simpa using this

theorem tri_nonneg (t : ℝ) : 0 ≤ tri t :=
  le_min (Int.fract_nonneg t) (by linarith [Int.fract_lt_one t])

theorem tri_le_half (t : ℝ) : tri t ≤ 1 / 2 := by
  unfold tri
  rcases le_total (Int.fract t) (1 / 2) with h | h
  · exact (min_le_left _ _).trans h
  · exact (min_le_right _ _).trans (by linarith)

theorem measurable_tri : Measurable tri := by
  unfold tri; fun_prop

theorem sgnTri_add_one (t : ℝ) : sgnTri (t + 1) = sgnTri t := by simp [sgnTri, Int.fract_add_one]

theorem sgnTri_of_mem {t : ℝ} (h0 : 0 ≤ t) (h1 : t < 1 / 2) : sgnTri t = 1 := by
  have hf : Int.fract t = t := Int.fract_eq_self.2 ⟨h0, by linarith⟩
  rw [sgnTri, hf, if_pos h1]

/-- The exceptional set of the slope: `fract t ∈ {0, 1/2}`. -/
def triKink : Set ℝ := {t | Int.fract t = 0 ∨ Int.fract t = 1 / 2}

theorem sgnTri_sub_of_int {t : ℝ} (ht : t ∉ triKink) (k : ℤ) : sgnTri (k - t) = -sgnTri t := by
  simp only [triKink, mem_setOf_eq, not_or] at ht
  rw [show (k : ℝ) - t = -t + k by ring]
  simp only [sgnTri, Int.fract_add_intCast, Int.fract_neg ht.1]
  have h1 := Int.fract_nonneg t
  have h2 := Int.fract_lt_one t
  rcases lt_or_gt_of_ne ht.2 with h | h
  · rw [if_neg (by linarith), if_pos h]
  · rw [if_pos (by linarith), if_neg (by linarith)]; norm_num

theorem triKink_countable : triKink.Countable := by
  have : triKink ⊆ range (fun k : ℤ => (k : ℝ) / 2) := by
    intro t ht
    rcases ht with h | h
    · refine ⟨2 * ⌊t⌋, ?_⟩
      have := Int.floor_add_fract t
      push_cast; rw [h] at this; linarith
    · refine ⟨2 * ⌊t⌋ + 1, ?_⟩
      have := Int.floor_add_fract t
      push_cast; rw [h] at this; linarith
  exact (countable_range _).mono this

theorem volume_triKink : volume triKink = 0 := triKink_countable.measure_zero _

theorem measurable_sgnTri : Measurable sgnTri := by
  unfold sgnTri
  exact Measurable.ite (measurableSet_lt measurable_fract measurable_const)
    measurable_const measurable_const

theorem norm_sgnTri (t : ℝ) : ‖((sgnTri t : ℝ) : ℂ)‖ = 1 := by
  unfold sgnTri; split_ifs <;> simp

/-! ### Null hyperplanes of `ℝ⁴` -/

theorem ae_eval_notMem {s : Set ℝ} (hs : volume s = 0) (j : Fin 4) :
    ∀ᵐ x ∂(volume : Measure (Fin 4 → ℝ)), x j ∉ s := by
  have h : volume (Function.eval j ⁻¹' s : Set (Fin 4 → ℝ)) = 0 := by
    rw [MeasureTheory.volume_pi]
    exact Measure.pi_eval_preimage_null (fun _ => volume) hs
  rw [ae_iff]
  simp only [not_not]
  exact h

theorem ae_ne_hyperplane (j : Fin 4) (c : ℝ) :
    ∀ᵐ x ∂(volume : Measure (Fin 4 → ℝ)), x j ≠ c := by
  have := ae_eval_notMem (s := {c}) (by simp) j
  simpa using this

theorem ae_notMem_triKink (j : Fin 4) :
    ∀ᵐ x ∂(volume : Measure (Fin 4 → ℝ)), x j ∉ triKink := ae_eval_notMem volume_triKink j

/-! ### Reflection doubling over boxes -/

theorem refl_preimage_box {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j) :
    refl j (b j) ⁻¹' box a b =
      {x | b j < x j} ∩ box a (Function.update b j (2 * b j - a j)) := by
  have h := refl_preimage_inter (Ω' := box a (Function.update b j (2 * b j - a j))) (j := j)
    (c := b j) (fun x hx => refl_mem_box_upper j hx)
  rwa [box_upper_inter j hab] at h

theorem box_upper_ae_eq {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j) :
    (box a (Function.update b j (2 * b j - a j)) : Set (Fin 4 → ℝ)) =ᵐ[volume]
      (box a b ∪ refl j (b j) ⁻¹' box a b : Set (Fin 4 → ℝ)) := by
  rw [refl_preimage_box j hab]
  filter_upwards [ae_ne_hyperplane j (b j)] with x hx
  have hB := box_upper_inter j hab
  apply propext
  constructor
  · intro h
    rcases lt_or_gt_of_ne hx with hl | hl
    · left; rw [← hB]; exact ⟨h, hl⟩
    · right; exact ⟨hl, h⟩
  · rintro (h | ⟨-, h⟩)
    · rw [← hB] at h; exact h.1
    · exact h

theorem disjoint_box_refl {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j) :
    Disjoint (box a b) (refl j (b j) ⁻¹' box a b) := by
  rw [refl_preimage_box j hab, Set.disjoint_left]
  intro x hx hx'
  have := (mem_box.mp hx j).2
  exact absurd hx'.1 (not_lt.mpr this.le)

theorem measurableSet_refl_preimage_box (a b : Fin 4 → ℝ) (j : Fin 4) (c : ℝ) :
    MeasurableSet (refl j c ⁻¹' box a b) :=
  (isOpen_box a b).measurableSet.preimage (continuous_refl j c).measurable

/-- **Reflection doubling of integrals over boxes**: if `F ∘ R = F` a.e. for the reflection `R`
across the upper face `x_j = b_j` of `box a b`, then the integral of `F` over the doubled box is
twice the integral over `box a b`. -/
theorem lintegral_box_double {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j)
    {F : (Fin 4 → ℝ) → ℝ≥0∞} (hF : ∀ᵐ x ∂volume, F (refl j (b j) x) = F x) :
    ∫⁻ x in box a (Function.update b j (2 * b j - a j)), F x = 2 * ∫⁻ x in box a b, F x := by
  rw [setLIntegral_congr (box_upper_ae_eq j hab),
    lintegral_union (measurableSet_refl_preimage_box a b j _) (disjoint_box_refl j hab)]
  have h1 : ∫⁻ x in refl j (b j) ⁻¹' box a b, F x = ∫⁻ x in refl j (b j) ⁻¹' box a b,
      F (refl j (b j) x) :=
    setLIntegral_congr_fun_ae (measurableSet_refl_preimage_box a b j _)
      (hF.mono fun x hx _ => hx.symm)
  rw [h1, (measurePreserving_refl j (b j)).setLIntegral_comp_preimage_emb
    (reflEquiv j (b j)).measurableEmbedding F (box a b), two_mul]

theorem aestronglyMeasurable_box_double {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j)
    {f : (Fin 4 → ℝ) → ℂ} (hf : AEStronglyMeasurable f (volume.restrict (box a b))) {s : ℂ}
    (hsym : ∀ᵐ x ∂volume, f x = s * f (refl j (b j) x)) :
    AEStronglyMeasurable f (volume.restrict (box a (Function.update b j (2 * b j - a j)))) := by
  rw [Measure.restrict_congr_set (box_upper_ae_eq j hab), aestronglyMeasurable_union_iff]
  refine ⟨hf, ?_⟩
  have h1 : AEStronglyMeasurable (fun x => s * f (refl j (b j) x))
      (volume.restrict (refl j (b j) ⁻¹' box a b)) :=
    (hf.comp_measurePreserving (measurePreserving_refl_restrict j (b j) (box a b))).const_mul s
  exact h1.congr (ae_restrict_of_ae (hsym.mono fun x hx => hx.symm))

/-- **Reflection doubling in `L^p`** (`0 < p < ∞`): a function with `f = s · f ∘ R` a.e.,
`|s| = 1`, in `L^p(box a b)` is in `L^p` of the doubled box, with `∫ ‖f‖^p` doubled. -/
theorem memLp_box_double {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j)
    {f : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0) (hpt : p ≠ ⊤)
    (hf : MemLp f p (volume.restrict (box a b))) {s : ℂ} (hs : ‖s‖ = 1)
    (hsym : ∀ᵐ x ∂volume, f x = s * f (refl j (b j) x)) :
    MemLp f p (volume.restrict (box a (Function.update b j (2 * b j - a j)))) ∧
      ∫⁻ x in box a (Function.update b j (2 * b j - a j)), ‖f x‖ₑ ^ p.toReal =
        2 * ∫⁻ x in box a b, ‖f x‖ₑ ^ p.toReal := by
  have hsym' : ∀ᵐ x ∂volume, f (refl j (b j) x) = s * f x := by
    have h := (measurePreserving_refl j (b j)).quasiMeasurePreserving.ae hsym
    filter_upwards [h] with x hx
    rwa [refl_refl] at hx
  have hI : ∫⁻ x in box a (Function.update b j (2 * b j - a j)), ‖f x‖ₑ ^ p.toReal =
      2 * ∫⁻ x in box a b, ‖f x‖ₑ ^ p.toReal := by
    refine lintegral_box_double j hab ?_
    filter_upwards [hsym'] with x hx
    rw [hx, enorm_mul, show ‖s‖ₑ = 1 by rw [← ofReal_norm_eq_enorm, hs, ENNReal.ofReal_one],
      one_mul]
  refine ⟨⟨aestronglyMeasurable_box_double j hab hf.1 hsym, ?_⟩, hI⟩
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hpt, hI]
  have h2 := hf.2
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hpt] at h2
  have hpos : 0 < p.toReal := ENNReal.toReal_pos hp0 hpt
  have h3 : ∫⁻ x in box a b, ‖f x‖ₑ ^ p.toReal ≠ ⊤ := by
    intro h; rw [h, ENNReal.top_rpow_of_pos (by positivity)] at h2; exact lt_irrefl _ h2
  exact ENNReal.rpow_lt_top_of_nonneg (by positivity) (ENNReal.mul_ne_top (by norm_num) h3)

/-! ### Folding and parity extensions -/

/-- The corner `(1/2, …, 1/2)`. -/
def halfB : Fin 4 → ℝ := fun _ => 1 / 2

/-- The corner `(1, …, 1)`. -/
def oneB : Fin 4 → ℝ := fun _ => 1

/-- The corner `(2, …, 2)`. -/
def twoB : Fin 4 → ℝ := fun _ => 2

/-- **The cube** `Q₀ = (0, 1/2)⁴`, fundamental domain of the reflection group of `𝕋⁴`. -/
abbrev Q0 : Set (Fin 4 → ℝ) := box 0 halfB

/-- The folding map `ℝ⁴ → [0,1/2]⁴`, `y ↦ (tri y_i)_i`. -/
def fold (y : Fin 4 → ℝ) : Fin 4 → ℝ := fun i => tri (y i)

/-- The `1`-periodic **parity extension** of a function `u` on `Q₀` to `ℝ⁴`, odd in the
directions of `S`: `extR S u y = (∏_{i ∈ S} sgnTri y_i) · u(fold y)`. -/
def extR (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ) (y : Fin 4 → ℝ) : ℂ :=
  (∏ i ∈ S, ((sgnTri (y i) : ℝ) : ℂ)) * u (fold y)

/-- The parity extension of a function on `Q₀` to the torus `𝕋⁴` (via the representative
`rep t ∈ (0,1]⁴`). -/
def parExt (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ) (t : 𝕋⁴) : ℂ := extR S u (torusRep t)

theorem mem_Q0 {y : Fin 4 → ℝ} : y ∈ Q0 ↔ ∀ i, 0 < y i ∧ y i < 1 / 2 := by
  simp [Q0, mem_box, halfB]

theorem fold_of_mem_Q0 {y : Fin 4 → ℝ} (hy : y ∈ Q0) : fold y = y :=
  funext fun i => tri_of_mem (mem_Q0.1 hy i).1.le (mem_Q0.1 hy i).2.le

theorem extR_of_mem_Q0 (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ) {y : Fin 4 → ℝ}
    (hy : y ∈ Q0) : extR S u y = u y := by
  have hs : ∀ i, sgnTri (y i) = 1 := fun i => sgnTri_of_mem (mem_Q0.1 hy i).1.le (mem_Q0.1 hy i).2
  simp [extR, hs, fold_of_mem_Q0 hy]

theorem fold_refl {c : ℝ} {k : ℤ} (hc : 2 * c = k) (j : Fin 4) (x : Fin 4 → ℝ) :
    fold (refl j c x) = fold x := by
  funext i
  by_cases hi : i = j
  · subst hi; simp only [fold, refl_apply_self, hc]; exact tri_sub_of_int _ k
  · simp only [fold, refl_apply_ne hi]

theorem fold_add_int (x : Fin 4 → ℝ) (z : Fin 4 → ℤ) :
    fold (x + fun i => (z i : ℝ)) = fold x :=
  funext fun i => by simp [fold, tri, Int.fract_add_intCast]

theorem sgnTri_add_int (t : ℝ) (k : ℤ) : sgnTri (t + k) = sgnTri t := by
  simp [sgnTri, Int.fract_add_intCast]

theorem prod_sgnTri_refl {c : ℝ} {k : ℤ} (hc : 2 * c = k) (S : Finset (Fin 4)) (j : Fin 4)
    {x : Fin 4 → ℝ} (hx : x j ∉ triKink) :
    ∏ i ∈ S, ((sgnTri (refl j c x i) : ℝ) : ℂ) = pSign S j * ∏ i ∈ S, ((sgnTri (x i) : ℝ) : ℂ) := by
  by_cases hj : j ∈ S
  · rw [← Finset.mul_prod_erase S _ hj, ← Finset.mul_prod_erase S _ hj,
      Finset.prod_congr rfl (fun i hi => by rw [refl_apply_ne (Finset.ne_of_mem_erase hi)])]
    simp only [refl_apply_self, hc, sgnTri_sub_of_int hx, pSign, hj, if_true]
    push_cast; ring
  · have h : ∀ i ∈ S, ((sgnTri (refl j c x i) : ℝ) : ℂ) = ((sgnTri (x i) : ℝ) : ℂ) :=
      fun i hi => by rw [refl_apply_ne (show i ≠ j by rintro rfl; exact hj hi)]
    rw [Finset.prod_congr rfl h]
    simp [pSign, hj]

theorem extR_refl {c : ℝ} {k : ℤ} (hc : 2 * c = k) (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ)
    (j : Fin 4) {x : Fin 4 → ℝ} (hx : x j ∉ triKink) :
    extR S u (refl j c x) = pSign S j * extR S u x := by
  simp only [extR, prod_sgnTri_refl hc S j hx, fold_refl hc]; ring

theorem extR_refl_ae {c : ℝ} {k : ℤ} (hc : 2 * c = k) (S : Finset (Fin 4))
    (u : (Fin 4 → ℝ) → ℂ) (j : Fin 4) :
    ∀ᵐ x ∂volume, extR S u (refl j c x) = pSign S j * extR S u x := by
  filter_upwards [ae_notMem_triKink j] with x hx
  exact extR_refl hc S u j hx

theorem extR_refl_ae' {c : ℝ} {k : ℤ} (hc : 2 * c = k) (S : Finset (Fin 4))
    (u : (Fin 4 → ℝ) → ℂ) (j : Fin 4) :
    ∀ᵐ x ∂volume, extR S u x = pSign S j * extR S u (refl j c x) := by
  filter_upwards [extR_refl_ae hc S u j] with x hx
  rw [hx, ← mul_assoc, pSign_mul_self, one_mul]

theorem extR_add_int (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ) (x : Fin 4 → ℝ)
    (z : Fin 4 → ℤ) : extR S u (x + fun i => (z i : ℝ)) = extR S u x := by
  simp only [extR, fold_add_int, Pi.add_apply, sgnTri_add_int]

theorem reflSign_eq_pSign (j i : Fin 4) : ((reflSign j i : ℝ) : ℂ) = pSign {i} j := by
  rw [pSign_singleton]; unfold reflSign dSign; split_ifs <;> simp

/-! ### Iterated doubling of boxes -/

theorem prod_two_mul_update (b : Fin 4 → ℝ) (j : Fin 4) :
    ∏ i, (2 * Function.update b j (2 * b j) i) = 2 * ∏ i, (2 * b i) := by
  rw [Fin.prod_univ_four, Fin.prod_univ_four]
  fin_cases j <;> simp [Function.update] <;> ring

/-- Four doublings, one per coordinate, take the constant corner `β` to `2β`. -/
theorem four_steps {P : (Fin 4 → ℝ) → Prop} {β : ℝ}
    (hstep : ∀ (b : Fin 4 → ℝ) (j : Fin 4), b j = β → P b → P (Function.update b j (2 * b j)))
    (h0 : P fun _ => β) : P fun _ => 2 * β := by
  have h1 := hstep _ 0 rfl h0
  have h2 := hstep _ 1 (by simp [Function.update]) h1
  have h3 := hstep _ 2 (by simp [Function.update]) h2
  have h4 := hstep _ 3 (by simp [Function.update]) h3
  convert h4 using 1
  funext i; fin_cases i <;> simp [Function.update]

theorem box_update_zero (b : Fin 4 → ℝ) (j : Fin 4) :
    box (0 : Fin 4 → ℝ) (Function.update b j (2 * b j)) =
      box 0 (Function.update b j (2 * b j - (0 : Fin 4 → ℝ) j)) := by simp

/-- The `L^p` doubling for parity extensions. -/
theorem memLp_extR_double {S : Finset (Fin 4)} {u : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0)
    (hpt : p ≠ ⊤) {b : Fin 4 → ℝ} (j : Fin 4) (hb : 0 ≤ b j) {k : ℤ} (hk : 2 * b j = k)
    (h : MemLp (extR S u) p (volume.restrict (box 0 b))) :
    MemLp (extR S u) p (volume.restrict (box 0 (Function.update b j (2 * b j)))) ∧
      ∫⁻ x in box 0 (Function.update b j (2 * b j)), ‖extR S u x‖ₑ ^ p.toReal =
        2 * ∫⁻ x in box 0 b, ‖extR S u x‖ₑ ^ p.toReal := by
  rw [box_update_zero]
  exact memLp_box_double j hb hp0 hpt h (norm_pSign S j) (extR_refl_ae' hk S u j)

/-- **`L^p` norm of the parity extension over `(0, 1)⁴` and `(0, 2)⁴`**: the parity extension
of `u ∈ L^p(Q₀)` is in `L^p`, with `∫ ‖·‖^p` multiplied by the volume ratio `16`, resp. `256`. -/
theorem memLp_extR_box {S : Finset (Fin 4)} {u : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0)
    (hpt : p ≠ ⊤) (hu : MemLp u p (volume.restrict Q0)) :
    (MemLp (extR S u) p (volume.restrict (box 0 oneB)) ∧
      ∫⁻ x in box 0 oneB, ‖extR S u x‖ₑ ^ p.toReal = 16 * ∫⁻ x in Q0, ‖u x‖ₑ ^ p.toReal) ∧
    (MemLp (extR S u) p (volume.restrict (box 0 twoB)) ∧
      ∫⁻ x in box 0 twoB, ‖extR S u x‖ₑ ^ p.toReal = 256 * ∫⁻ x in Q0, ‖u x‖ₑ ^ p.toReal) := by
  set I := ∫⁻ x in Q0, ‖u x‖ₑ ^ p.toReal
  have heq : extR S u =ᵐ[volume.restrict Q0] u :=
    (ae_restrict_mem (isOpen_box _ _).measurableSet).mono fun y hy => extR_of_mem_Q0 S u hy
  set P : (Fin 4 → ℝ) → Prop := fun b => (∀ i, 0 ≤ b i) ∧
    MemLp (extR S u) p (volume.restrict (box 0 b)) ∧
    ∫⁻ x in box 0 b, ‖extR S u x‖ₑ ^ p.toReal = ENNReal.ofReal (∏ i, (2 * b i)) * I
  have hstep : ∀ β : ℝ, (∃ k : ℤ, 2 * β = k) → ∀ (b : Fin 4 → ℝ) (j : Fin 4), b j = β → P b →
      P (Function.update b j (2 * b j)) := by
    rintro β ⟨k, hk⟩ b j hbj ⟨hb0, hm, hI⟩
    obtain ⟨hm', hI'⟩ := memLp_extR_double hp0 hpt j (hb0 j) (by rw [hbj, hk]) hm
    refine ⟨fun i => ?_, hm', ?_⟩
    · by_cases hi : i = j
      · subst hi; simp only [Function.update_self]; linarith [hb0 i]
      · rw [Function.update_of_ne hi]; exact hb0 i
    · rw [hI', hI, prod_two_mul_update, ENNReal.ofReal_mul (by norm_num), ← mul_assoc]
      norm_num
  have hP0 : P halfB := by
    refine ⟨fun i => by simp [halfB], hu.ae_eq heq.symm, ?_⟩
    have : ∏ i : Fin 4, (2 * halfB i) = 1 := by simp [halfB]
    rw [this, ENNReal.ofReal_one, one_mul]
    exact setLIntegral_congr_fun_ae (isOpen_box _ _).measurableSet
      (Eventually.of_forall fun y hy => by rw [extR_of_mem_Q0 S u hy])
  have hP1 : P oneB := by
    have := four_steps (P := P) (β := 1 / 2) (hstep (1 / 2) ⟨1, by norm_num⟩) hP0
    have e : oneB = fun _ => 2 * (1 / 2 : ℝ) := by funext i; norm_num [oneB]
    rw [e]; exact this
  have hP2 : P twoB := by
    have e1 : oneB = fun _ => (1 : ℝ) := rfl
    have := four_steps (P := P) (β := 1) (hstep 1 ⟨2, by norm_num⟩) (e1 ▸ hP1)
    have e : twoB = fun _ => 2 * (1 : ℝ) := by funext i; norm_num [twoB]
    rw [e]; exact this
  refine ⟨⟨hP1.2.1, ?_⟩, ⟨hP2.2.1, ?_⟩⟩
  · rw [hP1.2.2]; norm_num [oneB, Fin.prod_univ_four]
  · rw [hP2.2.2]; norm_num [twoB, Fin.prod_univ_four]

/-! ### Norm transfer to the torus -/

theorem unitCube_ae_eq_box : (unitCube : Set (Fin 4 → ℝ)) =ᵐ[volume] (box 0 oneB : Set _) := by
  have h : ∀ᵐ x ∂(volume : Measure (Fin 4 → ℝ)), ∀ i, x i ≠ 1 :=
    ae_all_iff.2 fun i => ae_ne_hyperplane i 1
  filter_upwards [h] with x hx
  change (x ∈ unitCube) = (x ∈ box 0 oneB)
  rw [mem_box]
  simp only [unitCube, mem_setOf_eq, mem_Ioc, oneB, Pi.zero_apply]
  exact propext (forall_congr' fun i => ⟨fun h => ⟨h.1, lt_of_le_of_ne h.2 (hx i)⟩,
    fun h => ⟨h.1, h.2.le⟩⟩)

/-- **Norm transfer** (integrals): `∫_{𝕋⁴} ‖parExt S u‖ₑ^p = 16 ∫_{Q₀} ‖u‖ₑ^p`. -/
theorem lintegral_parExt {S : Finset (Fin 4)} {u : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0)
    (hpt : p ≠ ⊤) (hu : MemLp u p (volume.restrict Q0)) :
    ∫⁻ t, ‖parExt S u t‖ₑ ^ p.toReal = 16 * ∫⁻ x in Q0, ‖u x‖ₑ ^ p.toReal := by
  rw [lintegral_torus_eq_unitCube]
  have e : ∫⁻ y in unitCube, ‖parExt S u (fun i => (y i : UnitAddCircle))‖ₑ ^ p.toReal =
      ∫⁻ y in unitCube, ‖extR S u y‖ₑ ^ p.toReal :=
    setLIntegral_congr_fun measurableSet_unitCube fun y hy => by
      simp only [parExt, torusRep_mk hy]
  rw [e, setLIntegral_congr unitCube_ae_eq_box]
  exact ((memLp_extR_box (S := S) hp0 hpt hu).1).2

/-- **Norm transfer** (`L^p`): `parExt S u ∈ L^p(𝕋⁴)` for `u ∈ L^p(Q₀)`. -/
theorem memLp_parExt {S : Finset (Fin 4)} {u : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0)
    (hpt : p ≠ ⊤) (hu : MemLp u p (volume.restrict Q0)) : MemLp (parExt S u) p volume := by
  have h1 := ((memLp_extR_box (S := S) hp0 hpt hu).1).1
  rw [← Measure.restrict_congr_set unitCube_ae_eq_box] at h1
  exact h1.comp_measurePreserving measurePreserving_torusRep

/-- **Norm transfer**: `‖parExt S u‖_{L^p(𝕋⁴)} = 16^{1/p} ‖u‖_{L^p(Q₀)}`. -/
theorem eLpNorm_parExt {S : Finset (Fin 4)} {u : (Fin 4 → ℝ) → ℂ} {p : ℝ≥0∞} (hp0 : p ≠ 0)
    (hpt : p ≠ ⊤) (hu : MemLp u p (volume.restrict Q0)) :
    eLpNorm (parExt S u) p volume = 16 ^ (1 / p.toReal) * eLpNorm u p (volume.restrict Q0) := by
  rw [eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hpt,
    eLpNorm_eq_lintegral_rpow_enorm_toReal hp0 hpt, lintegral_parExt hp0 hpt hu,
    ENNReal.mul_rpow_of_nonneg _ _ (by positivity)]

/-! ### `W^{1,2}` doubling -/

theorem hasWeakPartial_congr_ae {Ω : Set (Fin 4 → ℝ)} {i : Fin 4} {u g u' g' : (Fin 4 → ℝ) → ℂ}
    (h : HasWeakPartial Ω i u g) (hu : u =ᵐ[volume] u') (hg : g =ᵐ[volume] g') :
    HasWeakPartial Ω i u' g' := by
  intro φ hφ
  have e1 : ∫ x, ((pd φ i x : ℝ) : ℂ) * u x = ∫ x, ((pd φ i x : ℝ) : ℂ) * u' x :=
    integral_congr_ae (hu.mono fun x hx => by simp only [hx])
  have e2 : ∫ x, ((φ x : ℝ) : ℂ) * g x = ∫ x, ((φ x : ℝ) : ℂ) * g' x :=
    integral_congr_ae (hg.mono fun x hx => by simp only [hx])
  rw [← e1, ← e2]
  exact h φ hφ

theorem hasWeakPartial_congr_on {Ω : Set (Fin 4 → ℝ)} {i : Fin 4} {u g u' g' : (Fin 4 → ℝ) → ℂ}
    (h : HasWeakPartial Ω i u g) (hu : ∀ x ∈ Ω, u x = u' x) (hg : ∀ x ∈ Ω, g x = g' x) :
    HasWeakPartial Ω i u' g' := by
  intro φ hφ
  have e1 : (fun x => ((pd φ i x : ℝ) : ℂ) * u x) = fun x => ((pd φ i x : ℝ) : ℂ) * u' x := by
    funext x
    by_cases hx : x ∈ Ω
    · rw [hu x hx]
    · have : pd φ i x = 0 :=
        image_eq_zero_of_notMem_tsupport fun h' => hx (hφ.subset (tsupport_pd_subset φ i h'))
      simp [this]
  have e2 : (fun x => ((φ x : ℝ) : ℂ) * g x) = fun x => ((φ x : ℝ) : ℂ) * g' x := by
    funext x
    by_cases hx : x ∈ Ω
    · rw [hg x hx]
    · have : φ x = 0 := image_eq_zero_of_notMem_tsupport fun h' => hx (hφ.subset h')
      simp [this]
  rw [← e1, ← e2]
  exact h φ hφ

/-- **One-face `W^{1,2}` doubling for symmetric functions**: if `U ∈ W^{1,2}(box 0 b)` is even
and its weak gradient has the reflected parity under the reflection across `x_j = b_j`, then
`U ∈ W^{1,2}` of the doubled box (with the same weak gradient). -/
theorem memW12_box_double {b : Fin 4 → ℝ} (j : Fin 4) (hb : 0 ≤ b j) {U : (Fin 4 → ℝ) → ℂ}
    {G : Fin 4 → (Fin 4 → ℝ) → ℂ} (hW : MemW12 (box 0 b) U G)
    (hsU : ∀ᵐ x ∂volume, U (refl j (b j) x) = U x)
    (hsG : ∀ i, ∀ᵐ x ∂volume, G i (refl j (b j) x) = ((reflSign j i : ℝ) : ℂ) * G i x) :
    MemW12 (box 0 (Function.update b j (2 * b j))) U G := by
  have hab : (0 : Fin 4 → ℝ) j ≤ b j := hb
  rw [box_update_zero]
  have hinter := box_upper_inter j hab
  rw [← hinter] at hW
  obtain ⟨h1, -⟩ := memW12_reflExt (isOpen_box _ _) (fun x hx => refl_mem_box_upper j hx) hW
    (by rw [hinter]; exact volume_box_ne_top _ _)
  have hne := ae_ne_hyperplane j (b j)
  have eU : reflExt j (b j) U =ᵐ[volume] U := by
    filter_upwards [hne, hsU] with x hx hs
    rcases lt_or_gt_of_ne hx with hl | hl
    · simp [reflExt, hl, not_lt.mpr hl.le]
    · simp [reflExt, hl, not_lt.mpr hl.le, hs]
  have eG : ∀ i, reflExtGrad j (b j) i (G i) =ᵐ[volume] G i := by
    intro i
    filter_upwards [hne, hsG i] with x hx hs
    rcases lt_or_gt_of_ne hx with hl | hl
    · simp [reflExtGrad, hl, not_lt.mpr hl.le]
    · simp only [reflExtGrad, Pi.add_apply, indicator, mem_setOf_eq, hl, not_lt.mpr hl.le,
        if_false, if_true, zero_add, hs]
      rw [← mul_assoc, ← Complex.ofReal_mul, reflSign_sq, Complex.ofReal_one, one_mul]
  exact ⟨h1.memLp.ae_eq (ae_restrict_of_ae eU),
    fun i => (h1.memLp_grad i).ae_eq (ae_restrict_of_ae (eG i)),
    fun i => hasWeakPartial_congr_ae (h1.weak i) eU (eG i)⟩

/-- **Even reflection of `W^{1,2}(Q₀)`**: for `u ∈ W^{1,2}(Q₀)` with weak gradient `g`, the even
extension `extR ∅ u` lies in `W^{1,2}((0,2)⁴)` with weak gradient `(extR {i} (g i))_i`. -/
theorem memW12_extR_box {u : (Fin 4 → ℝ) → ℂ} {g : Fin 4 → (Fin 4 → ℝ) → ℂ}
    (hW : MemW12 Q0 u g) :
    MemW12 (box 0 twoB) (extR ∅ u) (fun i => extR {i} (g i)) := by
  set P : (Fin 4 → ℝ) → Prop := fun b => (∀ i, 0 ≤ b i) ∧
    MemW12 (box 0 b) (extR ∅ u) (fun i => extR {i} (g i))
  have hstep : ∀ β : ℝ, (∃ k : ℤ, 2 * β = k) → ∀ (b : Fin 4 → ℝ) (j : Fin 4), b j = β → P b →
      P (Function.update b j (2 * b j)) := by
    rintro β ⟨k, hk⟩ b j hbj ⟨hb0, hm⟩
    have hk' : 2 * b j = k := by rw [hbj, hk]
    refine ⟨fun i => ?_, memW12_box_double j (hb0 j) hm ?_ fun i => ?_⟩
    · by_cases hi : i = j
      · subst hi; simp only [Function.update_self]; linarith [hb0 i]
      · rw [Function.update_of_ne hi]; exact hb0 i
    · filter_upwards [extR_refl_ae hk' ∅ u j] with x hx
      rw [hx, pSign_empty, one_mul]
    · filter_upwards [extR_refl_ae hk' {i} (g i) j] with x hx
      rw [hx, reflSign_eq_pSign]
  have hP0 : P halfB := by
    refine ⟨fun i => by simp [halfB], ⟨?_, fun i => ?_, fun i => ?_⟩⟩
    · exact hW.memLp.ae_eq ((ae_restrict_mem (isOpen_box _ _).measurableSet).mono
        fun y hy => (extR_of_mem_Q0 ∅ u hy).symm)
    · exact (hW.memLp_grad i).ae_eq ((ae_restrict_mem (isOpen_box _ _).measurableSet).mono
        fun y hy => (extR_of_mem_Q0 {i} (g i) hy).symm)
    · exact hasWeakPartial_congr_on (hW.weak i) (fun y hy => (extR_of_mem_Q0 ∅ u hy).symm)
        (fun y hy => (extR_of_mem_Q0 {i} (g i) hy).symm)
  have hP1 : P oneB := by
    have := four_steps (P := P) (β := 1 / 2) (hstep (1 / 2) ⟨1, by norm_num⟩) hP0
    have e : oneB = fun _ => 2 * (1 / 2 : ℝ) := by funext i; norm_num [oneB]
    rw [e]; exact this
  have hP2 : P twoB := by
    have e1 : oneB = fun _ => (1 : ℝ) := rfl
    have := four_steps (P := P) (β := 1) (hstep 1 ⟨2, by norm_num⟩) (e1 ▸ hP1)
    have e : twoB = fun _ => 2 * (1 : ℝ) := by funext i; norm_num [twoB]
    rw [e]; exact this
  exact hP2.2

/-! ### The periodic Fourier rule from local weak derivatives -/

/-- A smooth step: `0` for `t ≤ 1/4`, `1` for `t ≥ 3/4`. -/
def stepEta (t : ℝ) : ℝ := Real.smoothTransition (2 * t - 1 / 2)

/-- The telescoping bump `ψ(t) = η(t) - η(t - 1)`, supported in `[1/4, 7/4]`, with
`ψ(t) + ψ(t + 1) = 1` on `[-1/4, 5/4]`. -/
def bumpPsi (t : ℝ) : ℝ := stepEta t - stepEta (t - 1)

/-- The product bump `Ψ(x) = ∏_k ψ(x_k)`, supported in `[1/4, 7/4]⁴ ⊂ (0,2)⁴`. -/
def bumpPsi4 (x : Fin 4 → ℝ) : ℝ := ∏ k, bumpPsi (x k)

theorem contDiff_stepEta : ContDiff ℝ ∞ stepEta :=
  Real.smoothTransition.contDiff.comp (by fun_prop)

theorem stepEta_of_le {t : ℝ} (ht : t ≤ 1 / 4) : stepEta t = 0 :=
  Real.smoothTransition.zero_of_nonpos (by linarith)

theorem stepEta_of_ge {t : ℝ} (ht : 3 / 4 ≤ t) : stepEta t = 1 :=
  Real.smoothTransition.one_of_one_le (by linarith)

theorem contDiff_bumpPsi : ContDiff ℝ ∞ bumpPsi :=
  contDiff_stepEta.sub (contDiff_stepEta.comp (by fun_prop))

theorem bumpPsi_of_le {t : ℝ} (ht : t ≤ 1 / 4) : bumpPsi t = 0 := by
  simp [bumpPsi, stepEta_of_le ht, stepEta_of_le (show t - 1 ≤ 1 / 4 by linarith)]

theorem bumpPsi_of_ge {t : ℝ} (ht : 7 / 4 ≤ t) : bumpPsi t = 0 := by
  simp [bumpPsi, stepEta_of_ge (show 3 / 4 ≤ t by linarith),
    stepEta_of_ge (show 3 / 4 ≤ t - 1 by linarith)]

theorem bumpPsi_add_shift {t : ℝ} (h1 : -1 / 4 ≤ t) (h2 : t ≤ 5 / 4) :
    bumpPsi t + bumpPsi (t + 1) = 1 := by
  simp only [bumpPsi, add_sub_cancel_right]
  rw [stepEta_of_ge (show 3 / 4 ≤ t + 1 by linarith), stepEta_of_le (show t - 1 ≤ 1 / 4 by linarith)]
  ring

theorem contDiff_bumpPsi4 : ContDiff ℝ ∞ bumpPsi4 := by
  unfold bumpPsi4
  exact contDiff_prod fun k _ => contDiff_bumpPsi.comp (contDiff_apply ℝ ℝ k)

theorem bumpPsi4_eq_zero {x : Fin 4 → ℝ} (hx : x ∉ Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4) :
    bumpPsi4 x = 0 := by
  simp only [mem_Icc, not_and_or, Pi.le_def, not_forall, not_le] at hx
  unfold bumpPsi4
  rcases hx with ⟨k, hk⟩ | ⟨k, hk⟩
  · exact Finset.prod_eq_zero (Finset.mem_univ k) (bumpPsi_of_le hk.le)
  · exact Finset.prod_eq_zero (Finset.mem_univ k) (bumpPsi_of_ge hk.le)

theorem tsupport_bumpPsi4 :
    tsupport bumpPsi4 ⊆ Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4 :=
  closure_minimal (fun x hx => by_contra fun h => hx (bumpPsi4_eq_zero h)) isClosed_Icc

theorem hasCompactSupport_bumpPsi4 : HasCompactSupport bumpPsi4 :=
  HasCompactSupport.of_support_subset_isCompact isCompact_Icc
    ((subset_tsupport _).trans tsupport_bumpPsi4)

theorem Icc_quarter_subset_box : (Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4) ⊆ box 0 twoB :=
  fun x hx => mem_box.2 fun i => ⟨by simp; linarith [hx.1 i], by simp [twoB]; linarith [hx.2 i]⟩

/-- The integer shift by `κ ∈ {0,1}⁴`. -/
def shift2 (κ : Fin 4 → Fin 2) : Fin 4 → ℝ := fun i => ((κ i : ℕ) : ℝ)

theorem shift2_int (κ : Fin 4 → Fin 2) :
    shift2 κ = fun i => (((κ i : ℕ) : ℤ) : ℝ) := by funext i; simp [shift2]

/-- `Σ_{κ ∈ {0,1}⁴} Ψ(x + κ) = 1` on `[-1/4, 5/4]⁴`. -/
theorem sum_bumpPsi4_shift {x : Fin 4 → ℝ} (hx : ∀ i, -1 / 4 ≤ x i ∧ x i ≤ 5 / 4) :
    ∑ κ : Fin 4 → Fin 2, bumpPsi4 (x + shift2 κ) = 1 := by
  have h : ∏ k, ∑ b : Fin 2, bumpPsi (x k + ((b : ℕ) : ℝ)) = 1 := by
    refine Finset.prod_eq_one fun k _ => ?_
    rw [Fin.sum_univ_two]
    simpa using bumpPsi_add_shift (hx k).1 (hx k).2
  rw [Finset.prod_sum] at h
  rw [← h]
  rfl

/-- The unit cube `(0,1]⁴` lies in `[-1/4, 5/4]⁴`. -/
theorem mem_quarter_of_unitCube {y : Fin 4 → ℝ} (hy : y ∈ unitCube) :
    ∀ i, -1 / 4 ≤ y i ∧ y i ≤ 5 / 4 := fun i => by
  have := hy i; simp only [mem_Ioc] at this; constructor <;> linarith [this.1, this.2]

/-- The cells `κ + (0,1]⁴`. -/
def cell (κ : Fin 4 → Fin 2) : Set (Fin 4 → ℝ) := (fun x => x - shift2 κ) ⁻¹' unitCube

theorem measurableSet_cell (κ : Fin 4 → Fin 2) : MeasurableSet (cell κ) :=
  measurableSet_unitCube.preimage (by fun_prop)

theorem cell_disjoint : Pairwise (Function.onFun Disjoint cell) := by
  intro κ κ' hne
  rw [Function.onFun, Set.disjoint_left]
  intro x hx hx'
  apply hne
  funext i
  have h1 := hx i; have h2 := hx' i
  simp only [Pi.sub_apply, shift2, mem_Ioc] at h1 h2
  have hk : ((κ i : ℕ) : ℝ) = ((κ' i : ℕ) : ℝ) := by
    have a1 : ((κ i : ℕ) : ℝ) < ((κ' i : ℕ) : ℝ) + 1 := by linarith [h1.1, h2.2]
    have a2 : ((κ' i : ℕ) : ℝ) < ((κ i : ℕ) : ℝ) + 1 := by linarith [h2.1, h1.2]
    have b1 : (κ i : ℕ) < (κ' i : ℕ) + 1 := by exact_mod_cast a1
    have b2 : (κ' i : ℕ) < (κ i : ℕ) + 1 := by exact_mod_cast a2
    exact_mod_cast (show (κ i : ℕ) = (κ' i : ℕ) by omega)
  exact Fin.ext (by exact_mod_cast hk)

theorem iUnion_cell : (⋃ κ, cell κ) = {x : Fin 4 → ℝ | ∀ i, x i ∈ Ioc 0 2} := by
  ext x
  simp only [mem_iUnion, cell, mem_preimage, unitCube, mem_setOf_eq, Pi.sub_apply, shift2,
    mem_Ioc]
  constructor
  · rintro ⟨κ, hκ⟩ i
    have := hκ i
    have hb : ((κ i : ℕ) : ℝ) ≤ 1 := by exact_mod_cast Nat.le_of_lt_succ (κ i).isLt
    constructor <;> linarith [this.1, this.2, (Nat.cast_nonneg (κ i : ℕ) : (0 : ℝ) ≤ _)]
  · intro h
    refine ⟨fun i => if x i ≤ 1 then 0 else 1, fun i => ?_⟩
    have := h i
    by_cases hi : x i ≤ 1
    · have e : (((if x i ≤ 1 then (0 : Fin 2) else 1 : Fin 2) : ℕ) : ℝ) = 0 := by simp [hi]
      rw [e, sub_zero]; exact ⟨this.1, hi⟩
    · have e : (((if x i ≤ 1 then (0 : Fin 2) else 1 : Fin 2) : ℕ) : ℝ) = 1 := by simp [hi]
      rw [e]; constructor <;> linarith [this.2, not_le.mp hi]

/-- **Periodisation identity**: for `F` periodic under integer translations and `w` vanishing
outside `(0,2]⁴` with `w F` integrable, `∫_{ℝ⁴} w F = ∫_{(0,1]⁴} (Σ_κ w(y + κ)) F(y) dy`. -/
theorem integral_periodic_split {w F : (Fin 4 → ℝ) → ℂ}
    (hF : ∀ x (z : Fin 4 → ℤ), F (x + fun k => (z k : ℝ)) = F x)
    (hw : ∀ x, x ∉ {x : Fin 4 → ℝ | ∀ i, x i ∈ Ioc 0 2} → w x = 0)
    (hint : Integrable (fun x => w x * F x)) :
    ∫ x, w x * F x = ∫ y in unitCube, (∑ κ : Fin 4 → Fin 2, w (y + shift2 κ)) * F y := by
  rw [← setIntegral_eq_integral_of_forall_compl_eq_zero (s := {x : Fin 4 → ℝ | ∀ i, x i ∈ Ioc 0 2})
    (fun x hx => by rw [hw x hx, zero_mul]), ← iUnion_cell,
    integral_iUnion_fintype measurableSet_cell cell_disjoint (fun κ => hint.integrableOn)]
  have hcell : ∀ κ, ∫ x in cell κ, w x * F x =
      ∫ y in unitCube, w (y + shift2 κ) * F y := by
    intro κ
    have hmp := measurePreserving_add_right (volume : Measure (Fin 4 → ℝ)) (shift2 κ)
    have hemb : MeasurableEmbedding (fun y : Fin 4 → ℝ => y + shift2 κ) :=
      (Homeomorph.addRight (shift2 κ)).measurableEmbedding
    have h := hmp.setIntegral_preimage_emb hemb (fun x => w x * F x) (cell κ)
    have hpre : (fun y : Fin 4 → ℝ => y + shift2 κ) ⁻¹' cell κ = unitCube := by
      ext y; simp [cell]
    rw [hpre] at h
    rw [← h]
    refine setIntegral_congr_fun measurableSet_unitCube fun y _ => ?_
    rw [shift2_int, hF]
  simp only [hcell]
  rw [← integral_finset_sum _ fun κ _ => ?_]
  · congr 1; funext y; rw [Finset.sum_mul]
  · have h1 : IntegrableOn (fun x => w x * F x) (cell κ) := hint.integrableOn
    have hmp := measurePreserving_add_right (volume : Measure (Fin 4 → ℝ)) (shift2 κ)
    have hemb : MeasurableEmbedding (fun y : Fin 4 → ℝ => y + shift2 κ) :=
      (Homeomorph.addRight (shift2 κ)).measurableEmbedding
    have hpre : (fun y : Fin 4 → ℝ => y + shift2 κ) ⁻¹' cell κ = unitCube := by
      ext y; simp [cell]
    have h2 := (hmp.integrableOn_comp_preimage hemb).2 h1
    rw [hpre] at h2
    refine h2.congr_fun (fun y _ => ?_) measurableSet_unitCube
    simp only [Function.comp_apply]
    rw [shift2_int, hF]

theorem coe_add_int_circle (t : ℝ) (k : ℤ) : (((t + k : ℝ)) : UnitAddCircle) = (t : UnitAddCircle) := by
  rw [QuotientAddGroup.eq_iff_sub_mem]
  rw [AddSubgroup.mem_zmultiples_iff]
  exact ⟨k, by simp⟩

theorem charE_add_int (n : Fin 4 → ℤ) (y : Fin 4 → ℝ) (z : Fin 4 → ℤ) :
    charE n (y + fun k => (z k : ℝ)) = charE n y := by
  rw [← mFourier_neg_mk, ← mFourier_neg_mk]
  congr 1
  funext i
  simp only [Pi.add_apply]
  exact coe_add_int_circle _ _

theorem charE_eq_charS (n : Fin 4 → ℤ) : charE n = charS n 0 1 := by
  funext x; simp [charS]

theorem pd_charE (n : Fin 4 → ℤ) (i : Fin 4) (x : Fin 4 → ℝ) :
    pd (charE n) i x = charE n x * (-(2 * π * Complex.I) * (n i : ℂ)) := by
  rw [charE_eq_charS, pd_charS]; simp

theorem contDiff_charE (n : Fin 4 → ℤ) : ContDiff ℝ ∞ (charE n) := by
  rw [charE_eq_charS]; exact contDiff_charS n 0 1

/-- The complexified bump. -/
def bumpC (x : Fin 4 → ℝ) : ℂ := ((bumpPsi4 x : ℝ) : ℂ)

theorem contDiff_bumpC : ContDiff ℝ ∞ bumpC :=
  Complex.ofRealCLM.contDiff.comp contDiff_bumpPsi4

theorem bumpC_eq_zero {x : Fin 4 → ℝ} (hx : x ∉ Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4) :
    bumpC x = 0 := by simp [bumpC, bumpPsi4_eq_zero hx]

/-- The `ι`-th partials of the shifted bumps sum to zero on the unit cube. -/
theorem sum_pd_bumpC_shift {y : Fin 4 → ℝ} (hy : y ∈ unitCube) (i : Fin 4) :
    ∑ κ : Fin 4 → Fin 2, pd bumpC i (y + shift2 κ) = 0 := by
  set S : (Fin 4 → ℝ) → ℂ := fun x => ∑ κ : Fin 4 → Fin 2, bumpC (x + shift2 κ)
  have hdiff : ∀ κ : Fin 4 → Fin 2, Differentiable ℝ fun x => bumpC (x + shift2 κ) := fun κ =>
    (contDiff_bumpC.differentiable (by simp)).comp (differentiable_id.add_const _)
  have hS : fderiv ℝ S y = ∑ κ : Fin 4 → Fin 2, fderiv ℝ bumpC (y + shift2 κ) := by
    rw [fderiv_fun_sum fun κ _ => (hdiff κ y)]
    refine Finset.sum_congr rfl fun κ _ => ?_
    exact fderiv_comp_add_right (f := bumpC) (shift2 κ)
  have hev : S =ᶠ[𝓝 y] fun _ => 1 := by
    have ho : IsOpen {x : Fin 4 → ℝ | ∀ i, -1 / 4 < x i ∧ x i < 5 / 4} := by
      simp only [setOf_forall]
      exact isOpen_iInter_of_finite fun i => (isOpen_lt continuous_const (continuous_apply i)).inter
        (isOpen_lt (continuous_apply i) continuous_const)
    have hmem : y ∈ {x : Fin 4 → ℝ | ∀ i, -1 / 4 < x i ∧ x i < 5 / 4} := fun i => by
      have := hy i; simp only [mem_Ioc] at this; constructor <;> linarith [this.1, this.2]
    filter_upwards [ho.mem_nhds hmem] with x hx
    have h := sum_bumpPsi4_shift (x := x) fun i => ⟨(hx i).1.le, (hx i).2.le⟩
    simp only [S, bumpC]
    rw [← Complex.ofReal_sum, h, Complex.ofReal_one]
  have h0 : fderiv ℝ S y = 0 := by rw [hev.fderiv_eq]; simp
  have := congrArg (fun L => L (Pi.single i 1)) (hS.symm.trans h0)
  simpa [pd, ContinuousLinearMap.sum_apply] using this

/-- **Periodic Fourier rule from local weak derivatives.**  Let `U, G : ℝ⁴ → ℂ` be periodic
under integer translations, locally integrable on `(0,2)⁴`, with `G` the weak `i`-th partial of
`U` on `(0,2)⁴`.  Then on `𝕋⁴`, `G ∘ rep` is the torus partial `∂_i (U ∘ rep)`
(`ĝ(n) = 2πi n_i Û(n)`). -/
theorem isTPartial_of_periodic {U G : (Fin 4 → ℝ) → ℂ} {i : Fin 4}
    (hW : HasWeakPartial (box 0 twoB) i U G) (hU : LocallyIntegrableOn U (box 0 twoB))
    (hG : LocallyIntegrableOn G (box 0 twoB))
    (hpU : ∀ x (z : Fin 4 → ℤ), U (x + fun k => (z k : ℝ)) = U x)
    (hpG : ∀ x (z : Fin 4 → ℤ), G (x + fun k => (z k : ℝ)) = G x) :
    IsTPartial i (fun t => U (torusRep t)) (fun t => G (torusRep t)) := by
  intro n
  set Φ : (Fin 4 → ℝ) → ℂ := fun x => bumpC x * charE n x
  have hΦs : ContDiff ℝ ∞ Φ := contDiff_bumpC.mul (contDiff_charE n)
  have hsuppB : tsupport bumpC ⊆ Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4 :=
    closure_minimal (fun x hx => by_contra fun h => hx (bumpC_eq_zero h)) isClosed_Icc
  have hcB : HasCompactSupport bumpC :=
    HasCompactSupport.of_support_subset_isCompact isCompact_Icc ((subset_tsupport _).trans hsuppB)
  have hΦc : HasCompactSupport Φ := hcB.mul_right
  have hΦsupp : tsupport Φ ⊆ Icc (fun _ => (1 / 4 : ℝ)) fun _ => 7 / 4 :=
    (tsupport_mul_subset_left).trans hsuppB
  have hΦbox : tsupport Φ ⊆ box 0 twoB := hΦsupp.trans Icc_quarter_subset_box
  have key := hW.complex_test hU hG hΦs hΦc hΦbox
  -- the periodisation of both sides
  have hbox02 : ∀ x, x ∉ {x : Fin 4 → ℝ | ∀ i, x i ∈ Ioc 0 2} → x ∉ tsupport Φ := by
    intro x hx hx'
    apply hx
    intro k
    have := mem_box.1 (hΦbox hx') k
    simp only [Pi.zero_apply, twoB] at this
    exact ⟨this.1, this.2.le⟩
  have hΦ1 : ContDiff ℝ 1 Φ := hΦs.of_le (by simp)
  have hL := integral_periodic_split hpU (w := pd Φ i)
    (fun x hx => image_eq_zero_of_notMem_tsupport fun h =>
      hbox02 x hx (tsupport_pd_subset Φ i h))
    (integrable_mul_of_locallyIntegrableOn hU (continuous_pd hΦ1 i) (hasCompactSupport_pd hΦc i)
      ((tsupport_pd_subset Φ i).trans hΦbox))
  have hR := integral_periodic_split hpG (w := Φ)
    (fun x hx => image_eq_zero_of_notMem_tsupport (hbox02 x hx))
    (integrable_mul_of_locallyIntegrableOn hG hΦs.continuous hΦc hΦbox)
  -- the shifted sums
  have hsumΦ : ∀ y ∈ unitCube, ∑ κ : Fin 4 → Fin 2, Φ (y + shift2 κ) = charE n y := by
    intro y hy
    simp only [Φ, shift2_int, charE_add_int, ← Finset.sum_mul]
    have h := sum_bumpPsi4_shift (mem_quarter_of_unitCube hy)
    simp only [shift2_int] at h
    simp only [bumpC]
    rw [← Complex.ofReal_sum, h, Complex.ofReal_one, one_mul]
  have hpdΦ : ∀ x, pd Φ i x = pd bumpC i x * charE n x +
      bumpC x * (charE n x * (-(2 * π * Complex.I) * (n i : ℂ))) := by
    intro x
    have hb : DifferentiableAt ℝ bumpC x := (contDiff_bumpC.differentiable (by simp)) x
    have hc : DifferentiableAt ℝ (charE n) x := ((contDiff_charE n).differentiable (by simp)) x
    unfold pd
    rw [show Φ = fun x => bumpC x * charE n x from rfl, fderiv_fun_mul hb hc]
    have := pd_charE n i x
    unfold pd at this
    simp only [ContinuousLinearMap.add_apply, ContinuousLinearMap.smul_apply, smul_eq_mul, this]
    ring
  have hsumpd : ∀ y ∈ unitCube, ∑ κ : Fin 4 → Fin 2, pd Φ i (y + shift2 κ) =
      charE n y * (-(2 * π * Complex.I) * (n i : ℂ)) := by
    intro y hy
    simp only [hpdΦ]
    have hc : ∀ κ : Fin 4 → Fin 2, charE n (y + shift2 κ) = charE n y := fun κ => by
      rw [shift2_int, charE_add_int]
    simp only [hc, Finset.sum_add_distrib, ← Finset.sum_mul, sum_pd_bumpC_shift hy i, zero_mul,
      zero_add]
    have h := sum_bumpPsi4_shift (mem_quarter_of_unitCube hy)
    simp only [bumpC]
    rw [← Complex.ofReal_sum, h, Complex.ofReal_one, one_mul]
  rw [setIntegral_congr_fun measurableSet_unitCube (fun y hy => by rw [hsumpd y hy])] at hL
  rw [setIntegral_congr_fun measurableSet_unitCube (fun y hy => by rw [hsumΦ y hy])] at hR
  rw [hL, hR] at key
  -- Fourier coefficients on the torus
  have hcoef : ∀ H : (Fin 4 → ℝ) → ℂ, mFourierCoeff (fun t => H (torusRep t)) n =
      ∫ y in unitCube, charE n y * H y := by
    intro H
    unfold mFourierCoeff
    rw [integral_torus_eq_unitCube]
    refine setIntegral_congr_fun measurableSet_unitCube fun y hy => ?_
    simp only [smul_eq_mul, torusRep_mk hy, mFourier_neg_mk]
  rw [hcoef, hcoef, sym]
  have e1 : ∫ y in unitCube, charE n y * (-(2 * π * Complex.I) * (n i : ℂ)) * U y =
      (-(2 * π * Complex.I) * (n i : ℂ)) * ∫ y in unitCube, charE n y * U y := by
    rw [← integral_const_mul]; congr 1; funext y; ring
  rw [e1] at key
  linear_combination key

/-- **`W^{1,2}(Q₀)` ⊂ even `H¹(𝕋⁴)`** (cube-to-torus direction of the Neumann identification):
for `u ∈ W^{1,2}(Q₀)` with weak gradient `g`, the even extension `parExt ∅ u` is in `L²(𝕋⁴)` with
torus partials `∂_i (parExt ∅ u) = parExt {i} (g i)` (also in `L²`). -/
theorem isTPartial_parExt {u : (Fin 4 → ℝ) → ℂ} {g : Fin 4 → (Fin 4 → ℝ) → ℂ}
    (hW : MemW12 Q0 u g) :
    MemLp (parExt ∅ u) 2 volume ∧ (∀ i, MemLp (parExt {i} (g i)) 2 volume) ∧
      ∀ i, IsTPartial i (parExt ∅ u) (parExt {i} (g i)) := by
  have hB := memW12_extR_box hW
  refine ⟨memLp_parExt (by norm_num) (by norm_num) hW.memLp,
    fun i => memLp_parExt (by norm_num) (by norm_num) (hW.memLp_grad i), fun i => ?_⟩
  exact isTPartial_of_periodic (hB.weak i) (locallyIntegrableOn_of_memLp hB.memLp)
    (locallyIntegrableOn_of_memLp (hB.memLp_grad i)) (fun x z => extR_add_int _ _ x z)
    (fun x z => extR_add_int _ _ x z)

/-! ### Parity of the torus extension -/

theorem torusRep_mem (t : 𝕋⁴) (i : Fin 4) : torusRep t i ∈ Ioc (0 : ℝ) 1 := by
  have := (AddCircle.equivIoc 1 0 (t i)).2
  simpa [torusRep] using this

theorem torusRep_reflect {t : 𝕋⁴} {j : Fin 4} (hj : torusRep t j ≠ 1) :
    torusRep (reflect j t) = refl j (1 / 2) (torusRep t) := by
  funext i
  by_cases hi : i = j
  · subst hi
    rw [refl_apply_self]
    have hm := torusRep_mem t i
    have hlt : torusRep t i < 1 := lt_of_le_of_ne hm.2 hj
    have ht : t i = ((torusRep t i : ℝ) : UnitAddCircle) := by
      have := congrFun (mk_torusRep t) i; exact this.symm
    have h1 : reflect i t i = (((1 - torusRep t i : ℝ)) : UnitAddCircle) := by
      rw [reflect_apply_self, ht, ← AddCircle.coe_neg]
      have := coe_add_int_circle (-torusRep t i) 1
      rw [← this]; congr 1; push_cast; ring
    simp only [torusRep]
    rw [h1, AddCircle.equivIoc_coe_eq (by constructor <;> linarith [hm.1])]
    change (1 - torusRep t i) = 2 * (1 / 2) - torusRep t i
    ring
  · simp only [torusRep, reflect_apply_ne hi, refl_apply_ne hi]

theorem ae_torusRep_good (j : Fin 4) :
    ∀ᵐ t ∂(volume : Measure 𝕋⁴), torusRep t j ∉ triKink ∧ torusRep t j ≠ 1 := by
  have h1 : ∀ᵐ y ∂(volume.restrict (unitCube : Set (Fin 4 → ℝ))), y j ∉ triKink ∧ y j ≠ 1 :=
    ae_restrict_of_ae ((ae_notMem_triKink j).and (ae_ne_hyperplane j 1))
  exact measurePreserving_torusRep.quasiMeasurePreserving.ae h1

/-- **The torus extension has the parity pattern `S`.** -/
theorem hasParity_parExt (S : Finset (Fin 4)) (u : (Fin 4 → ℝ) → ℂ) :
    HasParity S (parExt S u) := by
  intro j
  filter_upwards [ae_torusRep_good j] with t ht
  simp only [parExt]
  rw [torusRep_reflect ht.2]
  exact extR_refl (k := 1) (by norm_num) S u j ht.1

/-! ### Torus to cube: restriction -/

theorem Q0_subset_cubeAt : Q0 ⊆ TorusChart.cubeAt (0 : Fin 4 → ℝ) 1 := fun x hx i => by
  have := mem_Q0.1 hx i; simp only [Pi.zero_apply, zero_add, mem_Ioc]
  exact ⟨this.1, by linarith [this.2]⟩

theorem hasWeakPartial_congr_ae_restrict {Ω : Set (Fin 4 → ℝ)} (hΩ : MeasurableSet Ω) {i : Fin 4}
    {u g u' g' : (Fin 4 → ℝ) → ℂ} (h : HasWeakPartial Ω i u g) (hu : u =ᵐ[volume.restrict Ω] u')
    (hg : g =ᵐ[volume.restrict Ω] g') : HasWeakPartial Ω i u' g' := by
  intro φ hφ
  have hu' := (ae_restrict_iff' hΩ).1 hu
  have hg' := (ae_restrict_iff' hΩ).1 hg
  have e1 : ∫ x, ((pd φ i x : ℝ) : ℂ) * u x = ∫ x, ((pd φ i x : ℝ) : ℂ) * u' x := by
    refine integral_congr_ae (hu'.mono fun x hx => ?_)
    by_cases hxΩ : x ∈ Ω
    · simp only [hx hxΩ]
    · have : pd φ i x = 0 :=
        image_eq_zero_of_notMem_tsupport fun h' => hxΩ (hφ.subset (tsupport_pd_subset φ i h'))
      simp [this]
  have e2 : ∫ x, ((φ x : ℝ) : ℂ) * g x = ∫ x, ((φ x : ℝ) : ℂ) * g' x := by
    refine integral_congr_ae (hg'.mono fun x hx => ?_)
    by_cases hxΩ : x ∈ Ω
    · simp only [hx hxΩ]
    · have : φ x = 0 := image_eq_zero_of_notMem_tsupport fun h' => hxΩ (hφ.subset h')
      simp [this]
  rw [← e1, ← e2]
  exact h φ hφ

/-- The chart `y ↦ y mod 1` from `ℝ⁴` to `𝕋⁴`. -/
abbrev chart0 : (Fin 4 → ℝ) → 𝕋⁴ := TorusChart.chart 0 1

/-- **Torus `H¹` restricts to `W^{1,2}(Q₀)`**: if `F ∈ L²(𝕋⁴)` has `L²` torus partials `G i`,
then `F ∘ chart ∈ W^{1,2}(Q₀)` with weak gradient `G i ∘ chart`. -/
theorem memW12_restrict {F : 𝕋⁴ → ℂ} {G : Fin 4 → 𝕋⁴ → ℂ} (hF : MemLp F 2 volume)
    (hG : ∀ i, MemLp (G i) 2 volume) (hd : ∀ i, IsTPartial i F (G i)) :
    MemW12 Q0 (fun x => F (chart0 x)) (fun i x => G i (chart0 x)) := by
  set U := hF.toLp F
  have hcU : mFourierCoeff ⇑U = mFourierCoeff F := mFourierCoeff_toLp hF
  have hH : MemH 1 ⇑U := by
    unfold MemH CoeffMemH
    rw [hcU]
    have h0 := (hasSum_sq_mFourierCoeff_of_memLp hF).summable
    have hi : ∀ i, Summable fun n => ‖mFourierCoeff (G i) n‖ ^ 2 :=
      fun i => (hasSum_sq_mFourierCoeff_of_memLp (hG i)).summable
    have hsum := h0.add (summable_sum fun i (_ : i ∈ Finset.univ) => hi i)
    refine hsum.congr fun n => ?_
    simp only [sobWeight, Real.rpow_one, hd _ n, norm_mul, mul_pow, norm_sym_sq]
    rw [add_mul, one_mul, Finset.mul_sum, Finset.sum_mul]
    congr 1
    refine Finset.sum_congr rfl fun i _ => ?_
    ring
  have hwd : ∀ i, ⇑(weakDeriv i U) =ᵐ[volume] G i := fun i =>
    ae_eq_of_mFourierCoeff_eq (Lp.memLp _) (hG i) fun n => by
      rw [mFourierCoeff_weakDeriv hH, hcU, hd i n, sym]
  have hW := TorusChart.memW12_chart (isOpen_box _ _).measurableSet (volume_box_ne_top _ _)
    (c := 0) (L := 1) one_pos Q0_subset_cubeAt hH
  have e1 : (fun x => U (chart0 x)) =ᵐ[volume.restrict Q0] fun x => F (chart0 x) :=
    TorusChart.ae_chart_of_ae one_pos Q0_subset_cubeAt hF.coeFn_toLp
  have e2 : ∀ i, (fun x => ((1 : ℝ)⁻¹ : ℂ) * weakDeriv i U (TorusChart.chart 0 1 x))
      =ᵐ[volume.restrict Q0] fun x => G i (chart0 x) := fun i => by
    have := TorusChart.ae_chart_of_ae one_pos Q0_subset_cubeAt (hwd i)
    filter_upwards [this] with x hx
    simp only [inv_one, Complex.ofReal_one, one_mul] at hx ⊢
    exact hx
  exact ⟨hW.memLp.ae_eq e1, fun i => (hW.memLp_grad i).ae_eq (e2 i),
    fun i => hasWeakPartial_congr_ae_restrict (isOpen_box _ _).measurableSet (hW.weak i) e1 (e2 i)⟩

/-! ### Integral transfer -/

/-- **Reflection doubling of Bochner integrals over boxes.** -/
theorem integral_box_double {a b : Fin 4 → ℝ} (j : Fin 4) (hab : a j ≤ b j)
    {f : (Fin 4 → ℝ) → ℂ} (hf : IntegrableOn f (box a b))
    (hsym : ∀ᵐ x ∂volume, f (refl j (b j) x) = f x) :
    ∫ x in box a (Function.update b j (2 * b j - a j)), f x = 2 * ∫ x in box a b, f x := by
  have hmp := measurePreserving_refl_restrict j (b j) (box a b)
  have hR : IntegrableOn (fun x => f (refl j (b j) x)) (refl j (b j) ⁻¹' box a b) :=
    memLp_one_iff_integrable.1 ((memLp_one_iff_integrable.2
      (show Integrable f (volume.restrict (box a b)) from hf)).comp_measurePreserving hmp)
  have hR' : IntegrableOn f (refl j (b j) ⁻¹' box a b) :=
    hR.congr_fun_ae (ae_restrict_of_ae hsym)
  rw [setIntegral_congr_set (box_upper_ae_eq j hab),
    setIntegral_union (disjoint_box_refl j hab) (measurableSet_refl_preimage_box a b j _) hf hR']
  have h1 : ∫ x in refl j (b j) ⁻¹' box a b, f x =
      ∫ x in refl j (b j) ⁻¹' box a b, f (refl j (b j) x) :=
    setIntegral_congr_ae (measurableSet_refl_preimage_box a b j _)
      (hsym.mono fun x hx _ => hx.symm)
  rw [h1, (measurePreserving_refl j (b j)).setIntegral_preimage_emb
    (reflEquiv j (b j)).measurableEmbedding f (box a b), two_mul]

/-- **Integral transfer**: `∫_{𝕋⁴} parExt ∅ H = 16 ∫_{Q₀} H` for `H ∈ L¹(Q₀)`. -/
theorem integral_parExt {H : (Fin 4 → ℝ) → ℂ} (hH : Integrable H (volume.restrict Q0)) :
    ∫ t, parExt ∅ H t = 16 * ∫ x in Q0, H x := by
  have hH1 : MemLp H 1 (volume.restrict Q0) := memLp_one_iff_integrable.2 hH
  set I := ∫ x in Q0, H x
  set P : (Fin 4 → ℝ) → Prop := fun b => (∀ i, 0 ≤ b i) ∧
    MemLp (extR ∅ H) 1 (volume.restrict (box 0 b)) ∧
    ∫ x in box 0 b, extR ∅ H x = ((∏ i, (2 * b i) : ℝ) : ℂ) * I
  have hstep : ∀ (b : Fin 4 → ℝ) (j : Fin 4), b j = 1 / 2 → P b →
      P (Function.update b j (2 * b j)) := by
    rintro b j hbj ⟨hb0, hm, hI⟩
    have hk : 2 * b j = ((1 : ℤ) : ℝ) := by rw [hbj]; norm_num
    obtain ⟨hm', -⟩ := memLp_extR_double (by norm_num) (by norm_num) j (hb0 j) hk hm
    refine ⟨fun i => ?_, hm', ?_⟩
    · by_cases hi : i = j
      · subst hi; simp only [Function.update_self]; linarith [hb0 i]
      · rw [Function.update_of_ne hi]; exact hb0 i
    · rw [box_update_zero, integral_box_double j (hb0 j) (memLp_one_iff_integrable.1 hm)
        (by filter_upwards [extR_refl_ae hk ∅ H j] with x hx; rw [hx, pSign_empty, one_mul]),
        hI, prod_two_mul_update]
      push_cast; ring
  have hP0 : P halfB := by
    have heq : extR ∅ H =ᵐ[volume.restrict Q0] H :=
      (ae_restrict_mem (isOpen_box _ _).measurableSet).mono fun y hy => extR_of_mem_Q0 ∅ H hy
    refine ⟨fun i => by simp [halfB], hH1.ae_eq heq.symm, ?_⟩
    have : ∏ i : Fin 4, (2 * halfB i) = 1 := by simp [halfB]
    rw [this, Complex.ofReal_one, one_mul]
    exact integral_congr_ae heq
  have hP1 : P oneB := by
    have := four_steps (P := P) (β := 1 / 2) hstep hP0
    have e : oneB = fun _ => 2 * (1 / 2 : ℝ) := by funext i; norm_num [oneB]
    rw [e]; exact this
  rw [integral_torus_eq_unitCube]
  have e : ∫ y in unitCube, parExt ∅ H (fun i => (y i : UnitAddCircle)) =
      ∫ y in unitCube, extR ∅ H y :=
    setIntegral_congr_fun measurableSet_unitCube fun y hy => by simp only [parExt, torusRep_mk hy]
  rw [e, setIntegral_congr_set unitCube_ae_eq_box, hP1.2.2]
  norm_num [oneB, Fin.prod_univ_four]

/-! ### Parity functions are parity extensions of their restriction -/

/-- The partial reflection `x_i ↦ -x_i` for `i ∈ A`. -/
def reflSet (A : Finset (Fin 4)) (t : 𝕋⁴) : 𝕋⁴ := fun i => if i ∈ A then -t i else t i

theorem measurePreserving_reflSet (A : Finset (Fin 4)) :
    MeasurePreserving (reflSet A) (volume : Measure 𝕋⁴) volume := by
  have h : reflSet A = fun x i => (if i ∈ A then (fun z : UnitAddCircle => -z) else id) (x i) := by
    funext x i
    by_cases hi : i ∈ A <;> simp [reflSet, hi]
  rw [h]
  refine measurePreserving_pi (fun _ => volume) (fun _ => volume) fun i => ?_
  by_cases hi : i ∈ A
  · simp only [hi, if_true]; exact measurePreserving_neg_circle
  · simp only [hi, if_false]; exact MeasurePreserving.id _

theorem reflSet_empty (t : 𝕋⁴) : reflSet ∅ t = t := by
  funext i; simp [reflSet]

theorem reflSet_insert {A : Finset (Fin 4)} {j : Fin 4} (hj : j ∉ A) (t : 𝕋⁴) :
    reflSet (insert j A) t = reflect j (reflSet A t) := by
  funext i
  by_cases hi : i = j
  · subst hi; simp [reflSet, reflect_apply_self, hj]
  · simp [reflSet, reflect_apply_ne hi, hi]

theorem HasParity.comp_reflSet {S : Finset (Fin 4)} {F : 𝕋⁴ → ℂ} (hF : HasParity S F)
    (A : Finset (Fin 4)) :
    ∀ᵐ t ∂volume, F (reflSet A t) = (∏ i ∈ A, pSign S i) * F t := by
  induction A using Finset.induction_on with
  | empty => exact Eventually.of_forall fun t => by rw [reflSet_empty]; simp
  | insert j A hj ih =>
    have h1 := (measurePreserving_reflSet A).quasiMeasurePreserving.ae (hF j)
    filter_upwards [h1, ih] with t h1 h2
    rw [reflSet_insert hj, h1, h2, Finset.prod_insert hj]; ring

theorem prod_ite_comm (S A : Finset (Fin 4)) :
    ∏ i ∈ S, (if i ∈ A then (-1 : ℂ) else 1) = ∏ i ∈ A, pSign S i := by
  unfold pSign
  rw [← Finset.prod_filter, ← Finset.prod_filter]
  congr 1
  ext i; simp [and_comm]

/-- **A function of parity pattern `S` is the parity extension of its restriction to the cube**:
`F = parExt S (F ∘ chart)` a.e. on `𝕋⁴`. -/
theorem parExt_restrict {S : Finset (Fin 4)} {F : 𝕋⁴ → ℂ} (hF : HasParity S F) :
    F =ᵐ[volume] parExt S (fun x => F (chart0 x)) := by
  have hall : ∀ᵐ t ∂volume, ∀ A : Finset (Fin 4), F (reflSet A t) = (∏ i ∈ A, pSign S i) * F t :=
    ae_all_iff.2 fun A => hF.comp_reflSet A
  have hgood : ∀ᵐ t ∂(volume : Measure 𝕋⁴), ∀ j, torusRep t j ∉ triKink ∧ torusRep t j ≠ 1 :=
    ae_all_iff.2 ae_torusRep_good
  filter_upwards [hall, hgood] with t hA hg
  set A : Finset (Fin 4) := Finset.univ.filter fun i => 1 / 2 < torusRep t i
  have hchart : chart0 (fold (torusRep t)) = reflSet A t := by
    funext i
    simp only [TorusChart.chart, Pi.zero_apply, sub_zero, div_one, fold, reflSet, A,
      Finset.mem_filter, Finset.mem_univ, true_and]
    have hm := torusRep_mem t i
    have hti : t i = ((torusRep t i : ℝ) : UnitAddCircle) := (congrFun (mk_torusRep t) i).symm
    have hlt : torusRep t i < 1 := lt_of_le_of_ne hm.2 (hg i).2
    have hf : Int.fract (torusRep t i) = torusRep t i := Int.fract_eq_self.2 ⟨hm.1.le, hlt⟩
    by_cases hh : 1 / 2 < torusRep t i
    · rw [if_pos hh, hti, ← AddCircle.coe_neg]
      have htri : tri (torusRep t i) = 1 - torusRep t i := by
        simp only [tri, hf]; exact min_eq_right (by linarith)
      rw [htri, show (1 : ℝ) - torusRep t i = -torusRep t i + ((1 : ℤ) : ℝ) by push_cast; ring,
        coe_add_int_circle]
    · rw [if_neg hh, hti]
      congr 1
      exact tri_of_mem hm.1.le (not_lt.mp hh)
  have hsign : ∏ i ∈ S, ((sgnTri (torusRep t i) : ℝ) : ℂ) = ∏ i ∈ A, pSign S i := by
    rw [← prod_ite_comm]
    refine Finset.prod_congr rfl fun i _ => ?_
    have hm := torusRep_mem t i
    have hlt : torusRep t i < 1 := lt_of_le_of_ne hm.2 (hg i).2
    have hf : Int.fract (torusRep t i) = torusRep t i := Int.fract_eq_self.2 ⟨hm.1.le, hlt⟩
    have hne : torusRep t i ≠ 1 / 2 := fun h => (hg i).1 (Or.inr (by rw [hf, h]))
    simp only [sgnTri, hf, A, Finset.mem_filter, Finset.mem_univ, true_and]
    by_cases hh : 1 / 2 < torusRep t i
    · rw [if_neg (not_lt.mpr hh.le), if_pos hh]; simp
    · rw [if_pos (lt_of_le_of_ne (not_lt.mp hh) hne), if_neg hh]; simp
  simp only [parExt, extR, hchart, hA A, hsign]
  rw [← mul_assoc, ← Finset.prod_mul_distrib]
  rw [Finset.prod_congr rfl fun i _ => pSign_mul_self S i]
  simp

end RenewalGeometry.CubeNeumann
