/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Five-Kraus freedom behind the six-edge normalization

`prop:five-kraus-freedom` of the spacetime–gauge duality paper.

Fix a real Helmert frame (`eq:helmert-frame`): a real `6 × 5` matrix `O` with
`OᵀO = I₅`, `Oᵀ𝟏 = 0` and `OOᵀ = I₆ − 𝟏𝟏ᵀ/6` (`HelmertFrame`).  For operators
`K_1, …, K_6` on a finite-dimensional edge-system space (matrices `Matrix m m ℂ`),
the six-edge normalization `eq:six-edge-normalization`

`∑_e K_e^* K_e = I`, `∑_e K_e = √2 I`, `K_1, …, K_6` linearly independent

(`SixEdgeNormalization`) holds **iff** there are five matrices `B_1, …, B_5` with
`∑_μ B_μ^* B_μ = I` and `I, B_1, …, B_5` linearly independent (`FiveKrausData`) such that

`K_e = I/√18 + √(2/3) ∑_μ O_{eμ} B_μ`   (`eq:six-edge-normal-form`, `normalForm`).

This is `six_edge_iff_five_kraus`.  The consequences stated in the proposition follow:
the coarse edge channel is `∑_e K_e ρ K_e^* = (1/3) ρ + (2/3) ∑_μ B_μ ρ B_μ^*`
(`coarse_channel_normalForm`), and the unital `*`-algebras generated by the two
families coincide, `C*(K_e : e) = C*(B_μ : μ)` (`starAdjoin_normalForm_eq`; in finite
dimension the `*`-algebra generated is the `C*`-algebra generated).  Everything is
assembled in `five_kraus_freedom`.

The proof follows the manuscript: the orthogonal coefficient change with first column
`𝟏/√6` and remaining columns `O`; the coherent-sum constraint fixes the first
coefficient, the Helmert coordinates `D_μ = ∑_e O_{eμ} K_e` (`helmertCoord`) satisfy
`∑_μ D_μ^* D_μ = (2/3) I`, and `B_μ = √(3/2) D_μ` (`extracted`).

Scoped hypotheses: the edge-system space is a finite-dimensional matrix space
`Matrix m m ℂ`; the Helmert frame `O` is a parameter (the proposition is stated for a
chosen `O`).
-/

open Matrix

namespace RenewalGeometry
namespace FiveKraus

noncomputable section

/-- A real Helmert frame (`eq:helmert-frame`): `OᵀO = I₅`, `Oᵀ𝟏 = 0`,
`OOᵀ = I₆ − 𝟏𝟏ᵀ/6`. -/
structure HelmertFrame where
  /-- The `6 × 5` real matrix. -/
  O : Matrix (Fin 6) (Fin 5) ℝ
  /-- `OᵀO = I₅`. -/
  orth : Oᵀ * O = 1
  /-- `Oᵀ𝟏 = 0`, i.e. every column sums to zero. -/
  colSum : ∀ μ, ∑ e, O e μ = 0
  /-- `OOᵀ = I₆ − 𝟏𝟏ᵀ/6`. -/
  proj : O * Oᵀ = 1 - (1 / 6 : ℝ) • Matrix.of (fun _ _ => (1 : ℝ))

namespace HelmertFrame

theorem orth_apply (F : HelmertFrame) (μ ν : Fin 5) :
    ∑ e, F.O e μ * F.O e ν = if μ = ν then 1 else 0 := by
  have h := congrFun (congrFun F.orth μ) ν
  simpa [Matrix.mul_apply, Matrix.one_apply] using h

theorem proj_apply (F : HelmertFrame) (e f : Fin 6) :
    ∑ μ, F.O e μ * F.O f μ = (if e = f then 1 else 0) - 1 / 6 := by
  have h := congrFun (congrFun F.proj e) f
  simpa [Matrix.mul_apply, Matrix.one_apply] using h

end HelmertFrame

section FrameSums

variable {M : Type*} [AddCommGroup M] [Module ℂ M]

/-- `∑_e ∑_{μ,ν} O_{eμ} O_{eν} X_{μν} = ∑_μ X_{μμ}` (from `OᵀO = I`). -/
theorem sum_orth_smul (F : HelmertFrame) (X : Fin 5 → Fin 5 → M) :
    ∑ e, ∑ μ, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • X μ ν = ∑ μ, X μ μ := by
  have h : ∀ μ ν, ∑ e, ((F.O e μ * F.O e ν : ℝ) : ℂ) • X μ ν =
      if μ = ν then X μ μ else 0 := by
    intro μ ν
    rw [← Finset.sum_smul, ← Complex.ofReal_sum, F.orth_apply μ ν]
    split_ifs with hμν
    · subst hμν; simp
    · simp
  calc ∑ e, ∑ μ, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • X μ ν
      = ∑ μ, ∑ ν, ∑ e, ((F.O e μ * F.O e ν : ℝ) : ℂ) • X μ ν := by
        rw [Finset.sum_comm]
        exact Finset.sum_congr rfl fun μ _ => Finset.sum_comm
    _ = ∑ μ, ∑ ν, (if μ = ν then X μ μ else 0) := by simp_rw [h]
    _ = ∑ μ, X μ μ := by simp

/-- `∑_e ∑_ν O_{eμ} O_{eν} Z_ν = Z_μ` (from `OᵀO = I`), one index fixed. -/
theorem sum_orth_smul' (F : HelmertFrame) (μ : Fin 5) (Z : Fin 5 → M) :
    ∑ e, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • Z ν = Z μ := by
  rw [Finset.sum_comm]
  have h : ∀ ν, ∑ e, ((F.O e μ * F.O e ν : ℝ) : ℂ) • Z ν = if μ = ν then Z μ else 0 := by
    intro ν
    rw [← Finset.sum_smul, ← Complex.ofReal_sum, F.orth_apply μ ν]
    split_ifs with hμν
    · subst hμν; simp
    · simp
  simp_rw [h]
  simp

/-- `∑_μ O_{eμ} O_{fμ}`-weighted sums (from `OOᵀ = I − 𝟏𝟏ᵀ/6`), one index fixed. -/
theorem sum_proj_smul (F : HelmertFrame) (e : Fin 6) (Z : Fin 6 → M) :
    ∑ μ, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • Z f = Z e - (1 / 6 : ℂ) • ∑ f, Z f := by
  have h : ∀ f, ∑ μ, ((F.O e μ * F.O f μ : ℝ) : ℂ) • Z f =
      (if e = f then Z e else 0) - (1 / 6 : ℂ) • Z f := by
    intro f
    rw [← Finset.sum_smul, ← Complex.ofReal_sum, F.proj_apply e f]
    push_cast
    split_ifs with hef
    · subst hef; simp [sub_smul]
    · simp
  rw [Finset.sum_comm]
  simp_rw [h]
  simp [Finset.sum_sub_distrib, Finset.smul_sum]

/-- `∑_μ ∑_{e,f} O_{eμ} O_{fμ} Y_{ef} = ∑_e Y_{ee} − (1/6) ∑_{e,f} Y_{ef}`. -/
theorem sum_proj_smul₂ (F : HelmertFrame) (Y : Fin 6 → Fin 6 → M) :
    ∑ μ, ∑ e, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • Y e f =
      ∑ e, Y e e - (1 / 6 : ℂ) • ∑ e, ∑ f, Y e f := by
  calc ∑ μ, ∑ e, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • Y e f
      = ∑ e, ∑ μ, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • Y e f := Finset.sum_comm
    _ = ∑ e, (Y e e - (1 / 6 : ℂ) • ∑ f, Y e f) :=
        Finset.sum_congr rfl fun e _ => sum_proj_smul F e (Y e)
    _ = _ := by simp [Finset.sum_sub_distrib, Finset.smul_sum]

/-- `∑_e ∑_μ O_{eμ} Z_μ = 0` (from `Oᵀ𝟏 = 0`). -/
theorem sum_colSum_smul (F : HelmertFrame) (Z : Fin 5 → M) :
    ∑ e, ∑ μ, ((F.O e μ : ℝ) : ℂ) • Z μ = 0 := by
  rw [Finset.sum_comm]
  refine Finset.sum_eq_zero fun μ _ => ?_
  rw [← Finset.sum_smul, ← Complex.ofReal_sum, F.colSum μ]
  simp

end FrameSums

section Constants

theorem sqrt18_eq : Real.sqrt 18 = 3 * Real.sqrt 2 := by
  rw [show (18 : ℝ) = 3 ^ 2 * 2 by norm_num, Real.sqrt_mul (by norm_num),
    Real.sqrt_sq (by norm_num)]

theorem sqrt2_sq : Real.sqrt 2 ^ 2 = 2 := Real.sq_sqrt (by norm_num)

theorem sqrt2_ne_zero : Real.sqrt 2 ≠ 0 := by positivity

/-- `1/√18 = √2/6`. -/
theorem inv_sqrt18 : (1 / Real.sqrt 18 : ℝ) = Real.sqrt 2 / 6 := by
  rw [sqrt18_eq]
  field_simp
  nlinarith [sqrt2_sq]

theorem six_inv_sqrt18 : 6 * (1 / Real.sqrt 18 : ℝ) = Real.sqrt 2 := by
  rw [inv_sqrt18]; ring

theorem six_inv_sqrt18_sq : 6 * (1 / Real.sqrt 18 : ℝ) ^ 2 = 1 / 3 := by
  rw [inv_sqrt18, div_pow, sqrt2_sq]; norm_num

theorem inv_sqrt18_ne_zero : (1 / Real.sqrt 18 : ℝ) ≠ 0 := by
  rw [inv_sqrt18]; positivity

theorem sqrt_two_thirds_sq : Real.sqrt (2 / 3) ^ 2 = 2 / 3 := Real.sq_sqrt (by norm_num)

theorem sqrt_three_halves_sq : Real.sqrt (3 / 2) ^ 2 = 3 / 2 := Real.sq_sqrt (by norm_num)

theorem sqrt_two_thirds_ne_zero : Real.sqrt (2 / 3) ≠ 0 := by positivity

theorem sqrt_three_halves_ne_zero : Real.sqrt (3 / 2) ≠ 0 := by positivity

theorem sqrt_two_thirds_mul_sqrt_three_halves :
    Real.sqrt (2 / 3) * Real.sqrt (3 / 2) = 1 := by
  rw [← Real.sqrt_mul (by norm_num)]
  norm_num

end Constants

variable {m : Type*} [Fintype m] [DecidableEq m]

/-- **`eq:six-edge-normalization`**: `∑_e K_e^* K_e = I`, `∑_e K_e = √2 I`, and
`K_1, …, K_6` linearly independent. -/
def SixEdgeNormalization (K : Fin 6 → Matrix m m ℂ) : Prop :=
  ∑ e, (K e)ᴴ * K e = 1 ∧ ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) ∧
    LinearIndependent ℂ K

/-- Five Kraus matrices with `∑_μ B_μ^* B_μ = I` and `I, B_1, …, B_5` linearly
independent. -/
def FiveKrausData (B : Fin 5 → Matrix m m ℂ) : Prop :=
  ∑ μ, (B μ)ᴴ * B μ = 1 ∧ LinearIndependent ℂ (Fin.cons (1 : Matrix m m ℂ) B)

/-- The contrast combination `∑_μ O_{eμ} B_μ`. -/
def contrast (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (e : Fin 6) : Matrix m m ℂ :=
  ∑ μ, ((F.O e μ : ℝ) : ℂ) • B μ

/-- **`eq:six-edge-normal-form`**: `K_e = I/√18 + √(2/3) ∑_μ O_{eμ} B_μ`. -/
def normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (e : Fin 6) : Matrix m m ℂ :=
  ((1 / Real.sqrt 18 : ℝ) : ℂ) • (1 : Matrix m m ℂ) +
    ((Real.sqrt (2 / 3) : ℝ) : ℂ) • contrast F B e

/-- The Helmert coordinates `D_μ = ∑_e O_{eμ} K_e` of a six-edge family. -/
def helmertCoord (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ) (μ : Fin 5) : Matrix m m ℂ :=
  ∑ e, ((F.O e μ : ℝ) : ℂ) • K e

/-- The five Kraus matrices `B_μ = √(3/2) D_μ` extracted from a six-edge family. -/
def extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ) (μ : Fin 5) : Matrix m m ℂ :=
  ((Real.sqrt (3 / 2) : ℝ) : ℂ) • helmertCoord F K μ

/-! ### Elementary identities -/

theorem conjTranspose_real_smul (r : ℝ) (X : Matrix m m ℂ) :
    ((r : ℂ) • X)ᴴ = (r : ℂ) • Xᴴ := by
  rw [Matrix.conjTranspose_smul]
  simp only [Complex.star_def, Complex.conj_ofReal]

theorem conjTranspose_contrast (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (e : Fin 6) :
    (contrast F B e)ᴴ = ∑ μ, ((F.O e μ : ℝ) : ℂ) • (B μ)ᴴ := by
  unfold contrast
  rw [Matrix.conjTranspose_sum]
  exact Finset.sum_congr rfl fun μ _ => conjTranspose_real_smul _ _

theorem conjTranspose_helmertCoord (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ) (μ : Fin 5) :
    (helmertCoord F K μ)ᴴ = ∑ e, ((F.O e μ : ℝ) : ℂ) • (K e)ᴴ := by
  unfold helmertCoord
  rw [Matrix.conjTranspose_sum]
  exact Finset.sum_congr rfl fun e _ => conjTranspose_real_smul _ _

theorem sum_contrast (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) :
    ∑ e, contrast F B e = 0 :=
  sum_colSum_smul F B

/-- `∑_e D_e^* D_e = ∑_μ B_μ^* B_μ` for the contrasts `D_e = ∑_μ O_{eμ} B_μ`. -/
theorem sum_conjTranspose_mul_contrast (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) :
    ∑ e, (contrast F B e)ᴴ * contrast F B e = ∑ μ, (B μ)ᴴ * B μ := by
  have h : ∀ e, (contrast F B e)ᴴ * contrast F B e =
      ∑ μ, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • ((B μ)ᴴ * B ν) := by
    intro e
    rw [conjTranspose_contrast, contrast, Finset.sum_mul]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun ν _ => ?_
    rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
    simp only [Complex.ofReal_mul]
  simp_rw [h]
  exact sum_orth_smul F fun μ ν => (B μ)ᴴ * B ν

/-- `∑_e D_e ρ D_e^* = ∑_μ B_μ ρ B_μ^*` for the contrasts. -/
theorem sum_contrast_mul_mul_conjTranspose (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ)
    (ρ : Matrix m m ℂ) :
    ∑ e, contrast F B e * ρ * (contrast F B e)ᴴ = ∑ μ, B μ * ρ * (B μ)ᴴ := by
  have h : ∀ e, contrast F B e * ρ * (contrast F B e)ᴴ =
      ∑ μ, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • (B μ * ρ * (B ν)ᴴ) := by
    intro e
    rw [conjTranspose_contrast, contrast, Finset.sum_mul, Finset.sum_mul]
    refine Finset.sum_congr rfl fun μ _ => ?_
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun ν _ => ?_
    rw [Matrix.smul_mul, Matrix.smul_mul, Matrix.mul_smul, smul_smul]
    simp only [Complex.ofReal_mul]
  simp_rw [h]
  exact sum_orth_smul F fun μ ν => B μ * ρ * (B ν)ᴴ

/-- `D_μ^* D_μ = ∑_{e,f} O_{eμ} O_{fμ} K_e^* K_f` for the Helmert coordinates. -/
theorem conjTranspose_mul_helmertCoord (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (μ : Fin 5) :
    (helmertCoord F K μ)ᴴ * helmertCoord F K μ =
      ∑ e, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • ((K e)ᴴ * K f) := by
  rw [conjTranspose_helmertCoord, helmertCoord, Finset.sum_mul]
  refine Finset.sum_congr rfl fun e _ => ?_
  rw [Finset.mul_sum]
  refine Finset.sum_congr rfl fun f _ => ?_
  rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
  simp only [Complex.ofReal_mul]

/-- Adjoint of an affine family `a I + b D` with real `a`, `b`. -/
theorem conjTranspose_affine (a b : ℝ) (D : Matrix m m ℂ) :
    ((a : ℂ) • (1 : Matrix m m ℂ) + (b : ℂ) • D)ᴴ = (a : ℂ) • 1 + (b : ℂ) • Dᴴ := by
  rw [Matrix.conjTranspose_add, conjTranspose_real_smul, conjTranspose_real_smul,
    Matrix.conjTranspose_one]

/-- `∑_e (a I + b D_e)^* (a I + b D_e)` for real `a`, `b`. -/
theorem sum_conjTranspose_mul_affine (a b : ℝ) (D : Fin 6 → Matrix m m ℂ) :
    ∑ e, ((a : ℂ) • (1 : Matrix m m ℂ) + (b : ℂ) • D e)ᴴ * ((a : ℂ) • 1 + (b : ℂ) • D e) =
      ((6 * a ^ 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) + ((a * b : ℝ) : ℂ) • (∑ e, D e)ᴴ +
        ((a * b : ℝ) : ℂ) • ∑ e, D e + ((b ^ 2 : ℝ) : ℂ) • ∑ e, (D e)ᴴ * D e := by
  have h : ∀ e, ((a : ℂ) • (1 : Matrix m m ℂ) + (b : ℂ) • D e)ᴴ * ((a : ℂ) • 1 + (b : ℂ) • D e) =
      ((a ^ 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) + ((a * b : ℝ) : ℂ) • (D e)ᴴ +
        ((a * b : ℝ) : ℂ) • D e + ((b ^ 2 : ℝ) : ℂ) • ((D e)ᴴ * D e) := by
    intro e
    rw [conjTranspose_affine]
    simp only [Matrix.add_mul, Matrix.mul_add, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
      Matrix.mul_one, smul_add, smul_smul]
    push_cast
    simp only [sq, mul_comm (b : ℂ) (a : ℂ)]
    abel
  simp_rw [h]
  rw [Finset.sum_add_distrib, Finset.sum_add_distrib, Finset.sum_add_distrib,
    Finset.sum_const, Finset.card_univ, Fintype.card_fin, ← Nat.cast_smul_eq_nsmul ℂ 6,
    smul_smul, ← Finset.smul_sum, ← Finset.smul_sum, ← Finset.smul_sum,
    Matrix.conjTranspose_sum]
  push_cast
  try ring_nf

/-- `∑_e (a I + b D_e) ρ (a I + b D_e)^*` for real `a`, `b`. -/
theorem sum_affine_mul_mul_conjTranspose (a b : ℝ) (D : Fin 6 → Matrix m m ℂ)
    (ρ : Matrix m m ℂ) :
    ∑ e, ((a : ℂ) • (1 : Matrix m m ℂ) + (b : ℂ) • D e) * ρ *
        ((a : ℂ) • 1 + (b : ℂ) • D e)ᴴ =
      ((6 * a ^ 2 : ℝ) : ℂ) • ρ + ((a * b : ℝ) : ℂ) • (ρ * (∑ e, D e)ᴴ) +
        ((a * b : ℝ) : ℂ) • ((∑ e, D e) * ρ) + ((b ^ 2 : ℝ) : ℂ) • ∑ e, D e * ρ * (D e)ᴴ := by
  have h : ∀ e, ((a : ℂ) • (1 : Matrix m m ℂ) + (b : ℂ) • D e) * ρ *
      ((a : ℂ) • 1 + (b : ℂ) • D e)ᴴ =
      ((a ^ 2 : ℝ) : ℂ) • ρ + ((a * b : ℝ) : ℂ) • (ρ * (D e)ᴴ) +
        ((a * b : ℝ) : ℂ) • (D e * ρ) + ((b ^ 2 : ℝ) : ℂ) • (D e * ρ * (D e)ᴴ) := by
    intro e
    rw [conjTranspose_affine]
    simp only [Matrix.add_mul, Matrix.mul_add, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
      Matrix.mul_one, smul_add, smul_smul]
    push_cast
    simp only [sq, mul_comm (b : ℂ) (a : ℂ)]
    abel
  simp_rw [h]
  rw [Finset.sum_add_distrib, Finset.sum_add_distrib, Finset.sum_add_distrib,
    Finset.sum_const, Finset.card_univ, Fintype.card_fin, ← Nat.cast_smul_eq_nsmul ℂ 6,
    smul_smul, ← Finset.smul_sum, ← Finset.smul_sum, ← Finset.smul_sum, ← Finset.mul_sum,
    ← Finset.sum_mul, Matrix.conjTranspose_sum]
  push_cast
  try ring_nf

/-! ### From five Kraus matrices to the six-edge normalization -/

/-- `∑_e K_e = √2 I` for the normal form. -/
theorem sum_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) :
    ∑ e, normalForm F B e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) := by
  unfold normalForm
  rw [Finset.sum_add_distrib, ← Finset.smul_sum, ← Finset.smul_sum, sum_contrast, smul_zero,
    add_zero, Finset.sum_const, Finset.card_univ, Fintype.card_fin,
    ← Nat.cast_smul_eq_nsmul ℂ 6, smul_smul, ← six_inv_sqrt18]
  push_cast
  congr 1
  ring

/-- `∑_e K_e^* K_e = I` for the normal form, given `∑_μ B_μ^* B_μ = I`. -/
theorem sum_conjTranspose_mul_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ)
    (hB : ∑ μ, (B μ)ᴴ * B μ = 1) :
    ∑ e, (normalForm F B e)ᴴ * normalForm F B e = 1 := by
  unfold normalForm
  rw [sum_conjTranspose_mul_affine, sum_contrast, sum_conjTranspose_mul_contrast, hB,
    six_inv_sqrt18_sq, sqrt_two_thirds_sq, Matrix.conjTranspose_zero]
  simp only [smul_zero, add_zero]
  rw [← add_smul]
  push_cast
  norm_num

/-- The Helmert coordinates of the normal form recover `√(2/3) B_μ`. -/
theorem helmertCoord_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (μ : Fin 5) :
    helmertCoord F (normalForm F B) μ = ((Real.sqrt (2 / 3) : ℝ) : ℂ) • B μ := by
  have h1 : ∑ e, ((F.O e μ : ℝ) : ℂ) • (((1 / Real.sqrt 18 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) =
      0 := by
    rw [← Finset.sum_smul, ← Complex.ofReal_sum, F.colSum μ]
    simp
  have h2 : ∑ e, ((F.O e μ : ℝ) : ℂ) • (((Real.sqrt (2 / 3) : ℝ) : ℂ) • contrast F B e) =
      ((Real.sqrt (2 / 3) : ℝ) : ℂ) • ∑ e, ∑ ν, ((F.O e μ * F.O e ν : ℝ) : ℂ) • B ν := by
    rw [Finset.smul_sum]
    refine Finset.sum_congr rfl fun e _ => ?_
    unfold contrast
    simp only [Finset.smul_sum, smul_smul]
    refine Finset.sum_congr rfl fun ν _ => ?_
    congr 1
    push_cast; ring
  unfold helmertCoord normalForm
  simp_rw [smul_add]
  rw [Finset.sum_add_distrib, h1, zero_add, h2, sum_orth_smul' F μ B]

/-- A linear combination of the normal-form family as a combination of `I, B_1, …, B_5`. -/
theorem sum_smul_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (g : Fin 6 → ℂ) :
    ∑ e, g e • normalForm F B e =
      (((1 / Real.sqrt 18 : ℝ) : ℂ) * ∑ e, g e) • (1 : Matrix m m ℂ) +
        ∑ μ, (((Real.sqrt (2 / 3) : ℝ) : ℂ) * ∑ e, g e * ((F.O e μ : ℝ) : ℂ)) • B μ := by
  have h1 : ∑ e, g e • (((1 / Real.sqrt 18 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) =
      (((1 / Real.sqrt 18 : ℝ) : ℂ) * ∑ e, g e) • (1 : Matrix m m ℂ) := by
    rw [Finset.mul_sum, Finset.sum_smul]
    exact Finset.sum_congr rfl fun e _ => by rw [smul_smul, mul_comm]
  have h2 : ∑ e, g e • (((Real.sqrt (2 / 3) : ℝ) : ℂ) • contrast F B e) =
      ∑ μ, (((Real.sqrt (2 / 3) : ℝ) : ℂ) * ∑ e, g e * ((F.O e μ : ℝ) : ℂ)) • B μ := by
    unfold contrast
    simp_rw [Finset.smul_sum, smul_smul]
    rw [Finset.sum_comm]
    refine Finset.sum_congr rfl fun ν _ => ?_
    rw [Finset.mul_sum, Finset.sum_smul]
    refine Finset.sum_congr rfl fun e _ => ?_
    congr 1; ring
  unfold normalForm
  simp_rw [smul_add]
  rw [Finset.sum_add_distrib, h1, h2]

/-- The normal-form family is linearly independent when `I, B_1, …, B_5` are. -/
theorem linearIndependent_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ)
    (hB : LinearIndependent ℂ (Fin.cons (1 : Matrix m m ℂ) B)) :
    LinearIndependent ℂ (normalForm F B) := by
  rw [Fintype.linearIndependent_iff] at hB ⊢
  intro g hg
  let g' : Fin 6 → ℂ := Fin.cons (((1 / Real.sqrt 18 : ℝ) : ℂ) * ∑ e, g e)
    (fun μ => ((Real.sqrt (2 / 3) : ℝ) : ℂ) * ∑ e, g e * ((F.O e μ : ℝ) : ℂ))
  have hrel : ∑ i, g' i • (Fin.cons (1 : Matrix m m ℂ) B : Fin 6 → Matrix m m ℂ) i = 0 := by
    rw [Fin.sum_univ_succ]
    simp only [g', Fin.cons_zero, Fin.cons_succ]
    rw [← sum_smul_normalForm]
    exact hg
  have hg' := hB g' hrel
  have h0 : ∑ e, g e = 0 := by
    have := hg' 0
    simp only [g', Fin.cons_zero, mul_eq_zero, Complex.ofReal_eq_zero] at this
    exact this.resolve_left inv_sqrt18_ne_zero
  have hμ : ∀ μ, ∑ e, g e * ((F.O e μ : ℝ) : ℂ) = 0 := by
    intro μ
    have := hg' μ.succ
    simp only [g', Fin.cons_succ, mul_eq_zero, Complex.ofReal_eq_zero] at this
    exact this.resolve_left sqrt_two_thirds_ne_zero
  intro e
  have hkey := sum_proj_smul F e g
  simp only [smul_eq_mul] at hkey
  rw [h0, mul_zero, sub_zero] at hkey
  rw [← hkey]
  refine Finset.sum_eq_zero fun μ _ => ?_
  have : ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) * g f =
      ((F.O e μ : ℝ) : ℂ) * ∑ f, g f * ((F.O f μ : ℝ) : ℂ) := by
    rw [Finset.mul_sum]
    refine Finset.sum_congr rfl fun f _ => ?_
    push_cast; ring
  rw [this, hμ μ, mul_zero]

/-! ### From the six-edge normalization to five Kraus matrices -/

/-- The contrasts of the extracted family: `∑_μ O_{eμ} B_μ = √(3/2)(K_e − (1/6) ∑_f K_f)`. -/
theorem contrast_extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ) (e : Fin 6) :
    contrast F (extracted F K) e =
      ((Real.sqrt (3 / 2) : ℝ) : ℂ) • (K e - (1 / 6 : ℂ) • ∑ f, K f) := by
  unfold contrast extracted helmertCoord
  simp_rw [Finset.smul_sum, smul_smul]
  have h : ∀ μ f, (((F.O e μ : ℝ) : ℂ) * (((Real.sqrt (3 / 2) : ℝ) : ℂ) * ((F.O f μ : ℝ) : ℂ))) •
      K f = ((Real.sqrt (3 / 2) : ℝ) : ℂ) • (((F.O e μ * F.O f μ : ℝ) : ℂ) • K f) := by
    intro μ f
    rw [smul_smul]
    congr 1
    push_cast; ring
  simp_rw [h, ← Finset.smul_sum]
  rw [sum_proj_smul F e K]

/-- The normal form of the extracted family recovers `K`, given `∑_e K_e = √2 I`. -/
theorem normalForm_extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (hsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) (e : Fin 6) :
    normalForm F (extracted F K) e = K e := by
  unfold normalForm
  rw [contrast_extracted, smul_smul, hsum, ← Complex.ofReal_mul,
    sqrt_two_thirds_mul_sqrt_three_halves, Complex.ofReal_one, one_smul, smul_smul,
    inv_sqrt18]
  push_cast
  rw [show ((Real.sqrt 2 : ℝ) : ℂ) / 6 = 1 / 6 * ((Real.sqrt 2 : ℝ) : ℂ) by ring, add_sub_cancel]

/-- `∑_μ B_μ^* B_μ = I` for the extracted family, given the six-edge normalization. -/
theorem sum_conjTranspose_mul_extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (hK : ∑ e, (K e)ᴴ * K e = 1)
    (hsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) :
    ∑ μ, (extracted F K μ)ᴴ * extracted F K μ = 1 := by
  have h : ∀ μ, (extracted F K μ)ᴴ * extracted F K μ =
      ((Real.sqrt (3 / 2) ^ 2 : ℝ) : ℂ) •
        ∑ e, ∑ f, ((F.O e μ * F.O f μ : ℝ) : ℂ) • ((K e)ᴴ * K f) := by
    intro μ
    unfold extracted
    rw [conjTranspose_real_smul, Matrix.smul_mul, Matrix.mul_smul, smul_smul,
      conjTranspose_mul_helmertCoord]
    simp only [sq, Complex.ofReal_mul]
  simp_rw [h]
  rw [← Finset.smul_sum, sum_proj_smul₂ F fun e f => (K e)ᴴ * K f, hK]
  have h2 : ∑ e, ∑ f, (K e)ᴴ * K f = (∑ e, K e)ᴴ * ∑ f, K f := by
    rw [Matrix.conjTranspose_sum, Finset.sum_mul]
    refine Finset.sum_congr rfl fun e _ => ?_
    rw [Finset.mul_sum]
  have h3 : (1 : Matrix m m ℂ) - (1 / 6 : ℂ) •
      ((((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ))ᴴ * (((Real.sqrt 2 : ℝ) : ℂ) • 1)) =
      (2 / 3 : ℂ) • (1 : Matrix m m ℂ) := by
    rw [conjTranspose_real_smul, Matrix.conjTranspose_one, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.one_mul, smul_smul, smul_smul, mul_assoc, ← Complex.ofReal_mul, ← sq, sqrt2_sq]
    ext i j
    simp only [Matrix.sub_apply, Matrix.smul_apply, Matrix.one_apply, smul_eq_mul]
    push_cast
    split_ifs <;> norm_num
  rw [h2, hsum, h3, smul_smul, sqrt_three_halves_sq]
  push_cast
  norm_num

/-- A linear combination of `I, B_1, …, B_5` (extracted family) as a combination of the
`K_f`, given `∑_e K_e = √2 I`. -/
theorem sum_smul_cons_extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (hsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) (c : Fin 6 → ℂ) :
    ∑ i, c i • Fin.cons (1 : Matrix m m ℂ) (extracted F K) i =
      ∑ f, (c 0 * ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ +
        ((Real.sqrt (3 / 2) : ℝ) : ℂ) * ∑ μ, c μ.succ * ((F.O f μ : ℝ) : ℂ)) • K f := by
  have hone : (1 : Matrix m m ℂ) = ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ • ∑ f, K f := by
    rw [hsum, smul_smul, inv_mul_cancel₀ (by exact_mod_cast sqrt2_ne_zero), one_smul]
  rw [Fin.sum_univ_succ, Fin.cons_zero, hone]
  simp only [Fin.cons_succ]
  unfold extracted helmertCoord
  simp_rw [add_smul, Finset.sum_add_distrib, Finset.smul_sum, smul_smul]
  congr 1
  rw [Finset.sum_comm]
  refine Finset.sum_congr rfl fun f _ => ?_
  rw [Finset.mul_sum, Finset.sum_smul]
  refine Finset.sum_congr rfl fun μ _ => ?_
  congr 1; ring

/-- `I, B_1, …, B_5` are linearly independent for the extracted family, given the
six-edge normalization. -/
theorem linearIndependent_cons_extracted (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (hsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ))
    (hK : LinearIndependent ℂ K) :
    LinearIndependent ℂ (Fin.cons (1 : Matrix m m ℂ) (extracted F K)) := by
  rw [Fintype.linearIndependent_iff] at hK ⊢
  intro c hc
  rw [sum_smul_cons_extracted F K hsum] at hc
  have hd := hK _ hc
  have h2 : ∑ f, ((Real.sqrt (3 / 2) : ℝ) : ℂ) * ∑ μ, c μ.succ * ((F.O f μ : ℝ) : ℂ) = 0 := by
    rw [← Finset.mul_sum, Finset.sum_comm]
    simp_rw [← Finset.mul_sum, ← Complex.ofReal_sum, F.colSum]
    simp
  have hc0 : c 0 = 0 := by
    have hsum0 : ∑ f, (c 0 * ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ +
        ((Real.sqrt (3 / 2) : ℝ) : ℂ) * ∑ μ, c μ.succ * ((F.O f μ : ℝ) : ℂ)) = 0 :=
      Finset.sum_eq_zero fun f _ => hd f
    rw [Finset.sum_add_distrib, h2, add_zero, Finset.sum_const, Finset.card_univ,
      Fintype.card_fin, nsmul_eq_mul, mul_eq_zero, mul_eq_zero] at hsum0
    have hs2 : ((Real.sqrt 2 : ℝ) : ℂ)⁻¹ ≠ 0 := by
      exact inv_ne_zero (by exact_mod_cast sqrt2_ne_zero)
    rcases hsum0 with h6 | h | h
    · exact absurd h6 (by norm_num)
    · exact h
    · exact absurd h hs2
  have hcontr : ∀ f, ∑ μ, c μ.succ * ((F.O f μ : ℝ) : ℂ) = 0 := by
    intro f
    have := hd f
    simp only [hc0, zero_mul, zero_add, mul_eq_zero, Complex.ofReal_eq_zero] at this
    exact this.resolve_left sqrt_three_halves_ne_zero
  intro i
  induction i using Fin.cases with
  | zero => exact hc0
  | succ ν =>
    rw [← sum_orth_smul' F ν (fun μ' => c μ'.succ)]
    refine Finset.sum_eq_zero fun e _ => ?_
    have : ∑ μ', ((F.O e ν * F.O e μ' : ℝ) : ℂ) • c μ'.succ =
        ((F.O e ν : ℝ) : ℂ) * ∑ μ', c μ'.succ * ((F.O e μ' : ℝ) : ℂ) := by
      rw [Finset.mul_sum]
      refine Finset.sum_congr rfl fun μ' _ => ?_
      rw [smul_eq_mul]
      push_cast; ring
    rw [this, hcontr e, mul_zero]

/-! ### The proposition -/

/-- **`prop:five-kraus-freedom`, the equivalence.**  The six-edge normalization
`eq:six-edge-normalization` holds iff there are five matrices `B_μ` with
`∑_μ B_μ^* B_μ = I` and `I, B_1, …, B_5` linearly independent such that
`K_e = I/√18 + √(2/3) ∑_μ O_{eμ} B_μ` (`eq:six-edge-normal-form`). -/
theorem six_edge_iff_five_kraus (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ) :
    SixEdgeNormalization K ↔
      ∃ B : Fin 5 → Matrix m m ℂ, FiveKrausData B ∧ ∀ e, K e = normalForm F B e := by
  constructor
  · rintro ⟨hK, hsum, hind⟩
    exact ⟨extracted F K,
      ⟨sum_conjTranspose_mul_extracted F K hK hsum,
        linearIndependent_cons_extracted F K hsum hind⟩,
      fun e => (normalForm_extracted F K hsum e).symm⟩
  · rintro ⟨B, ⟨hB, hind⟩, hK⟩
    have hKe : K = normalForm F B := funext hK
    subst hKe
    exact ⟨sum_conjTranspose_mul_normalForm F B hB, sum_normalForm F B,
      linearIndependent_normalForm F B hind⟩

/-- **`prop:five-kraus-freedom`, the coarse edge channel.**  In the normal form,
`∑_e K_e ρ K_e^* = (1/3) ρ + (2/3) ∑_μ B_μ ρ B_μ^*`, i.e. `ℰ_* = (1/3) id + (2/3) Ψ_*`. -/
theorem coarse_channel_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ)
    (ρ : Matrix m m ℂ) :
    ∑ e, normalForm F B e * ρ * (normalForm F B e)ᴴ =
      (1 / 3 : ℂ) • ρ + (2 / 3 : ℂ) • ∑ μ, B μ * ρ * (B μ)ᴴ := by
  unfold normalForm
  rw [sum_affine_mul_mul_conjTranspose, sum_contrast, sum_contrast_mul_mul_conjTranspose,
    six_inv_sqrt18_sq, sqrt_two_thirds_sq, Matrix.conjTranspose_zero, Matrix.mul_zero,
    Matrix.zero_mul]
  simp only [smul_zero, add_zero]
  push_cast
  try rfl

/-- The generated unital `*`-algebra of a family (its `C*`-algebra in finite dimension). -/
def starAdjoin {ι : Type*} (K : ι → Matrix m m ℂ) : StarSubalgebra ℂ (Matrix m m ℂ) :=
  StarAlgebra.adjoin ℂ (Set.range K)

theorem normalForm_mem_starAdjoin (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (e : Fin 6) :
    normalForm F B e ∈ starAdjoin B := by
  unfold normalForm contrast
  refine add_mem (Subalgebra.smul_mem _ (one_mem _) _)
    (Subalgebra.smul_mem _ (Subalgebra.sum_mem _ fun μ _ => Subalgebra.smul_mem _ ?_ _) _)
  exact StarAlgebra.subset_adjoin ℂ _ ⟨μ, rfl⟩

theorem mem_starAdjoin_normalForm (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) (μ : Fin 5) :
    B μ ∈ starAdjoin (normalForm F B) := by
  have h : B μ = ((Real.sqrt (2 / 3) : ℝ) : ℂ)⁻¹ • helmertCoord F (normalForm F B) μ := by
    rw [helmertCoord_normalForm, smul_smul,
      inv_mul_cancel₀ (by exact_mod_cast sqrt_two_thirds_ne_zero), one_smul]
  rw [h]
  unfold helmertCoord
  refine Subalgebra.smul_mem _ (Subalgebra.sum_mem _ fun e _ => Subalgebra.smul_mem _ ?_ _) _
  exact StarAlgebra.subset_adjoin ℂ _ ⟨e, rfl⟩

/-- **`prop:five-kraus-freedom`, `C*(K_e : e) = C*(B_μ : μ)`.**  The unital `*`-algebras
generated by the normal-form family and by the five Kraus matrices coincide. -/
theorem starAdjoin_normalForm_eq (F : HelmertFrame) (B : Fin 5 → Matrix m m ℂ) :
    starAdjoin (normalForm F B) = starAdjoin B := by
  apply le_antisymm
  · exact StarAlgebra.adjoin_le (Set.range_subset_iff.mpr (normalForm_mem_starAdjoin F B))
  · exact StarAlgebra.adjoin_le (Set.range_subset_iff.mpr (mem_starAdjoin_normalForm F B))

/-- **`prop:five-kraus-freedom`, assembled.**  For a six-edge family `K` satisfying
`eq:six-edge-normalization`, the extracted five Kraus matrices `B_μ = √(3/2) ∑_e O_{eμ} K_e`
satisfy `∑ B_μ^* B_μ = I`, `I, B_1, …, B_5` are linearly independent, `K` has the normal
form `eq:six-edge-normal-form`, the coarse edge channel is `(1/3) id + (2/3) Ψ`, and
`C*(K_e) = C*(B_μ)`. -/
theorem five_kraus_freedom (F : HelmertFrame) (K : Fin 6 → Matrix m m ℂ)
    (hK : SixEdgeNormalization K) :
    FiveKrausData (extracted F K) ∧
      (∀ e, K e = normalForm F (extracted F K) e) ∧
      (∀ ρ : Matrix m m ℂ, ∑ e, K e * ρ * (K e)ᴴ =
        (1 / 3 : ℂ) • ρ + (2 / 3 : ℂ) • ∑ μ, extracted F K μ * ρ * (extracted F K μ)ᴴ) ∧
      starAdjoin K = starAdjoin (extracted F K) := by
  obtain ⟨hKK, hsum, hind⟩ := hK
  have hnf : ∀ e, K e = normalForm F (extracted F K) e :=
    fun e => (normalForm_extracted F K hsum e).symm
  have hKe : K = normalForm F (extracted F K) := funext hnf
  refine ⟨⟨sum_conjTranspose_mul_extracted F K hKK hsum,
    linearIndependent_cons_extracted F K hsum hind⟩, hnf, fun ρ => ?_, ?_⟩
  · conv_lhs => rw [hKe]
    exact coarse_channel_normalForm F _ ρ
  · conv_lhs => rw [hKe]
    exact starAdjoin_normalForm_eq F _

end

end FiveKraus
end RenewalGeometry
