/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.StandardModel.InternalSeedSaturationExact
import RenewalGeometry.StandardModel.FiniteInternalLandingExact
import RenewalGeometry.Commutant.JointTypedActionAlgebra

/-!
# Relative-commutant saturation for actual represented words
  (`thm:internal-seed-saturation`)

`InternalSeedSaturationExact.lean` builds the fixed algebra isomorphism
`Φ₀ = censusCommutantEquiv : M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ ≃ₐ 𝒜'_tet,r` at census `(3, 2, 1, 1)` (sign
sector absent).  This file proves the theorem for **actual represented words**
`x : β → 𝒜'_tet,r` with intrinsic hypotheses:

* the coordinates `y_j = Φ₀⁻¹(x_j)` of the words in the census carrier `ℂ⁷` are computed by
  the fixed `Φ₀`, which is a `*`-isomorphism (`censusCommutantEquiv_star`), so the
  `C^*`-algebra generated by the words is carried onto the `C^*`-algebra generated by the
  `y_j` (`starAdjoin_range_eq_of_coords`);
* the hypotheses are invariant under block unitaries `diag(U₃, U₂, 1, 1)`: the coherent
  realisation `T ⊕ H_priv` of the colour three-space is an **arbitrary** unit vector `τ`
  of the colour block (`T = ℂτ`, `p_T = |τ⟩⟨τ|`, `p_H = P₀ − p_T`), the colour residual
  `ω_col(u) = ‖p_H u p_T‖²_HS + ‖p_T u p_H‖²_HS` is computed relative to it (`omegaCol`),
  and the weak router is any pair of distinct, non-orthogonal rank-one projections
  `|t⟩⟨t|, |h⟩⟨h|` with `t, h` arbitrary unit vectors of the standard multiplicity plane;
* (I1) the generated algebra contains `M₂(H_priv) = {p_H X p_H}` and either a represented
  word with `ω_col > 0` or a represented bridge supplied by a reciprocal mediator bank with
  `m_ret > 0` (`ReciprocalWordBridge`, via `ReciprocalReturnMass.mass_pos_iff`);
  (I2) two distinct non-orthogonal represented rank-one projections on the weak plane;
  (I3) is the census; (I4) independent scalar central supports, or `η_cen > 0`.

The block-coordinate core is `blockAlgebra_le_of_landing`: any star-closed unital
subalgebra of `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ` with these properties is everything.  Note that `p_T`
itself need not be a represented word: it is generated (`rk1_mem_of_bridge`).

Main results: `internal_seed_saturation_words` (`eq:active-internal-algebra` for the actual
words, with dimension `15`, a four-dimensional centre, and nonabelian sectors of `9` and `4`
entries) and `internal_seed_saturation_words_of_unitary` (with the isotypic data produced by
`thm:active-isotypic`).
-/

open Matrix Kronecker Module
open scoped ComplexOrder
open RenewalGeometry.InternalAssembly (blockOf blockAlgebra)
open RenewalGeometry.CentralSeparation (centralProj centralProj_mul_apply mul_centralProj_apply
  centralProj_mul_self centralProj_mem_blockAlgebra centralProj_comm scalar_decomp
  single_add_single_eq etaCen etaCen_pos_iff)

namespace RenewalGeometry
namespace InternalSeedWords

/-! ### Rank-one projections on the census carrier -/

/-- A vector of the census carrier `ℂ⁷` supported on block `k`. -/
def BlockSupported (k : Fin 4) (v : Fin 7 → ℂ) : Prop := ∀ i, blockOf i ≠ k → v i = 0

/-- A unit vector: `⟨v, v⟩ = 1`. -/
def IsUnitVec (v : Fin 7 → ℂ) : Prop := star v ⬝ᵥ v = 1

/-- The rank-one projection `|v⟩⟨v|`. -/
def rk1 (v : Fin 7 → ℂ) : Matrix (Fin 7) (Fin 7) ℂ := vecMulVec v (star v)

/-- The private-plane projection `p_H = P₀ − |τ⟩⟨τ|` of the coherent realisation
`T ⊕ H_priv` of the colour block, `T = ℂτ`. -/
def pHpriv (τ : Fin 7 → ℂ) : Matrix (Fin 7) (Fin 7) ℂ := centralProj 0 - rk1 τ

/-- The colour residual `ω_col(u) = ‖p_H u p_T‖²_HS + ‖p_T u p_H‖²_HS` relative to the
realisation `T = ℂτ` (`eq:colour-bridge`). -/
noncomputable def omegaCol (τ : Fin 7 → ℂ) (u : Matrix (Fin 7) (Fin 7) ℂ) : ℝ :=
  BridgeRouter.frobSq (pHpriv τ * u * rk1 τ) + BridgeRouter.frobSq (rk1 τ * u * pHpriv τ)

theorem rk1_conjTranspose (v : Fin 7 → ℂ) : (rk1 v)ᴴ = rk1 v := by
  rw [rk1, conjTranspose_vecMulVec, star_star]

theorem rk1_mul_rk1 {v : Fin 7 → ℂ} (hv : IsUnitVec v) : rk1 v * rk1 v = rk1 v := by
  rw [rk1, vecMulVec_mul_vecMulVec, hv, one_smul]

theorem vecMulVec_star_mul (a b c d : Fin 7 → ℂ) :
    vecMulVec a (star b) * vecMulVec c (star d) = (star b ⬝ᵥ c) • vecMulVec a (star d) := by
  rw [vecMulVec_mul_vecMulVec, vecMulVec_smul]

/-- `p_T M p_T = ⟨τ, M τ⟩ p_T`. -/
theorem rk1_mul_mul_rk1 (v : Fin 7 → ℂ) (M : Matrix (Fin 7) (Fin 7) ℂ) :
    rk1 v * M * rk1 v = (star v ⬝ᵥ (M *ᵥ v)) • rk1 v := by
  rw [rk1, vecMulVec_mul, vecMulVec_mul_vecMulVec, vecMulVec_smul, dotProduct_mulVec]

theorem centralProj_mulVec_of_supported {k : Fin 4} {v : Fin 7 → ℂ} (hv : BlockSupported k v) :
    centralProj k *ᵥ v = v := by
  ext i
  rw [centralProj, mulVec_diagonal]
  by_cases h : blockOf i = k
  · rw [if_pos h, one_mul]
  · rw [if_neg h, zero_mul, hv i h]

theorem star_vecMul_centralProj_of_supported {k : Fin 4} {v : Fin 7 → ℂ}
    (hv : BlockSupported k v) : star v ᵥ* centralProj k = star v := by
  ext i
  rw [centralProj, vecMul_diagonal, Pi.star_apply]
  by_cases h : blockOf i = k
  · rw [if_pos h, mul_one]
  · rw [if_neg h, mul_zero, hv i h, star_zero]

theorem centralProj_mul_rk1 {k : Fin 4} {v : Fin 7 → ℂ} (hv : BlockSupported k v) :
    centralProj k * rk1 v = rk1 v := by
  rw [rk1, mul_vecMulVec, centralProj_mulVec_of_supported hv]

theorem rk1_mul_centralProj {k : Fin 4} {v : Fin 7 → ℂ} (hv : BlockSupported k v) :
    rk1 v * centralProj k = rk1 v := by
  rw [rk1, vecMulVec_mul, star_vecMul_centralProj_of_supported hv]

theorem centralProj_conjTranspose (k : Fin 4) : (centralProj k)ᴴ = centralProj k := by
  ext i j
  simp only [conjTranspose_apply, centralProj, diagonal_apply]
  split_ifs <;> simp_all

section Colour

variable {τ : Fin 7 → ℂ} (hτ : BlockSupported 0 τ) (hτu : IsUnitVec τ)
include hτ hτu

theorem pHpriv_mul_self : pHpriv τ * pHpriv τ = pHpriv τ := by
  rw [pHpriv, sub_mul, mul_sub, mul_sub, centralProj_mul_self, centralProj_mul_rk1 hτ,
    rk1_mul_centralProj hτ, rk1_mul_rk1 hτu]
  abel

theorem pHpriv_mul_rk1 : pHpriv τ * rk1 τ = 0 := by
  rw [pHpriv, sub_mul, centralProj_mul_rk1 hτ, rk1_mul_rk1 hτu, sub_self]

theorem rk1_mul_pHpriv : rk1 τ * pHpriv τ = 0 := by
  rw [pHpriv, mul_sub, rk1_mul_centralProj hτ, rk1_mul_rk1 hτu, sub_self]

omit hτ hτu in
theorem pHpriv_conjTranspose : (pHpriv τ)ᴴ = pHpriv τ := by
  rw [pHpriv, conjTranspose_sub, centralProj_conjTranspose, rk1_conjTranspose]

omit hτu in
theorem pHpriv_mul_centralProj : pHpriv τ * centralProj 0 = pHpriv τ := by
  rw [pHpriv, sub_mul, centralProj_mul_self, rk1_mul_centralProj hτ]

omit hτu in
theorem centralProj_mul_pHpriv : centralProj 0 * pHpriv τ = pHpriv τ := by
  rw [pHpriv, mul_sub, centralProj_mul_self, centralProj_mul_rk1 hτ]

end Colour

/-! ### The colour block is generated -/

section ColourGen

variable {B : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ)} (hBle : B ≤ blockAlgebra)
  (hBstar : ∀ a ∈ B, aᴴ ∈ B)
  {τ : Fin 7 → ℂ} (hτ : BlockSupported 0 τ) (hτu : IsUnitVec τ)
  (hpriv : ∀ X : Matrix (Fin 7) (Fin 7) ℂ, pHpriv τ * X * pHpriv τ ∈ B)

include hτ hτu hpriv in
theorem pHpriv_mem : pHpriv τ ∈ B := by
  have h := hpriv 1
  rwa [Matrix.mul_one, pHpriv_mul_self hτ hτu] at h

include hτ in
/-- For a block-diagonal `u`: `p_H u (1 − p_H) = p_H u p_T`. -/
theorem pHpriv_mul_mul_compl {u : Matrix (Fin 7) (Fin 7) ℂ} (hu : u ∈ blockAlgebra) :
    pHpriv τ * u * (1 - pHpriv τ) = pHpriv τ * u * rk1 τ := by
  have h1 : (1 : Matrix (Fin 7) (Fin 7) ℂ) - pHpriv τ = (1 - centralProj 0) + rk1 τ := by
    rw [pHpriv]; abel
  have h2 : pHpriv τ * u * (1 - centralProj 0) = 0 := by
    rw [Matrix.mul_sub, Matrix.mul_one, Matrix.mul_assoc, ← centralProj_comm hu,
      ← Matrix.mul_assoc, pHpriv_mul_centralProj hτ, sub_self]
  rw [h1, Matrix.mul_add, h2, zero_add]

include hτ in
/-- For a block-diagonal `u`: `(1 − p_H) u p_H = p_T u p_H`. -/
theorem compl_mul_mul_pHpriv {u : Matrix (Fin 7) (Fin 7) ℂ} (hu : u ∈ blockAlgebra) :
    (1 - pHpriv τ) * u * pHpriv τ = rk1 τ * u * pHpriv τ := by
  have h1 : (1 : Matrix (Fin 7) (Fin 7) ℂ) - pHpriv τ = (1 - centralProj 0) + rk1 τ := by
    rw [pHpriv]; abel
  have h2 : (1 - centralProj 0) * u * pHpriv τ = 0 := by
    rw [Matrix.sub_mul, Matrix.sub_mul, Matrix.one_mul, centralProj_comm hu, Matrix.mul_assoc,
      centralProj_mul_pHpriv hτ, sub_self]
  rw [h1, Matrix.add_mul, Matrix.add_mul, h2, zero_add]

include hτ hτu in
theorem pHpriv_corner_idem (X : Matrix (Fin 7) (Fin 7) ℂ) :
    pHpriv τ * (pHpriv τ * X * rk1 τ) * rk1 τ = pHpriv τ * X * rk1 τ := by
  calc pHpriv τ * (pHpriv τ * X * rk1 τ) * rk1 τ
      = pHpriv τ * pHpriv τ * X * (rk1 τ * rk1 τ) := by simp only [Matrix.mul_assoc]
    _ = _ := by rw [pHpriv_mul_self hτ hτu, rk1_mul_rk1 hτu]

include hτu in
/-- A nonzero `H_priv ← T` corner `v` has `v^* v = c p_T` with `c ≠ 0`. -/
theorem exists_conjTranspose_mul_corner {v : Matrix (Fin 7) (Fin 7) ℂ} (hv0 : v ≠ 0)
    (hvp : v * rk1 τ = v) : ∃ c : ℂ, c ≠ 0 ∧ vᴴ * v = c • rk1 τ := by
  have hkey : vᴴ * v = (star τ ⬝ᵥ ((vᴴ * v) *ᵥ τ)) • rk1 τ := by
    calc vᴴ * v = (v * rk1 τ)ᴴ * (v * rk1 τ) := by rw [hvp]
      _ = rk1 τ * (vᴴ * v) * rk1 τ := by
          rw [conjTranspose_mul, rk1_conjTranspose]; simp only [Matrix.mul_assoc]
      _ = _ := rk1_mul_mul_rk1 _ _
  refine ⟨_, ?_, hkey⟩
  intro hc
  rw [hc, zero_smul] at hkey
  exact hv0 (conjTranspose_mul_self_eq_zero.mp hkey)

include hBstar hτu in
/-- **The type line is generated**: a represented nonzero `H_priv ← T` corner `v` gives
`p_T ∈ B` (`p_T = c⁻¹ v^* v`). -/
theorem rk1_mem_of_corner {v : Matrix (Fin 7) (Fin 7) ℂ} (hvB : v ∈ B) (hv0 : v ≠ 0)
    (hvf : pHpriv τ * v * rk1 τ = v) : rk1 τ ∈ B := by
  have hvp : v * rk1 τ = v := by
    rw [← hvf, Matrix.mul_assoc, rk1_mul_rk1 hτu]
  obtain ⟨c, hc, hkey⟩ := exists_conjTranspose_mul_corner hτu hv0 hvp
  have h := B.smul_mem (mul_mem (hBstar v hvB) hvB) c⁻¹
  rwa [hkey, smul_smul, inv_mul_cancel₀ hc, one_smul] at h

theorem frobSq_zero : BridgeRouter.frobSq (0 : Matrix (Fin 7) (Fin 7) ℂ) = 0 := by
  simp [BridgeRouter.frobSq]

include hBle hBstar hτ hτu hpriv in
/-- A represented word with `ω_col > 0` yields a represented nonzero `H_priv ← T` corner. -/
theorem exists_corner_of_omegaCol_pos {u : Matrix (Fin 7) (Fin 7) ℂ} (huB : u ∈ B)
    (hω : 0 < omegaCol τ u) :
    ∃ v ∈ B, v ≠ 0 ∧ pHpriv τ * v * rk1 τ = v := by
  have hu := hBle huB
  have hpH := pHpriv_mem hτ hτu hpriv
  have hw : pHpriv τ * u * rk1 τ ∈ B := by
    rw [← pHpriv_mul_mul_compl hτ hu]
    exact mul_mem (mul_mem hpH huB) (B.sub_mem B.one_mem hpH)
  have hw' : rk1 τ * u * pHpriv τ ∈ B := by
    rw [← compl_mul_mul_pHpriv hτ hu]
    exact mul_mem (mul_mem (B.sub_mem B.one_mem hpH) huB) hpH
  by_cases h0 : pHpriv τ * u * rk1 τ = 0
  · have h1 : rk1 τ * u * pHpriv τ ≠ 0 := by
      intro h1
      rw [omegaCol, h0, h1, frobSq_zero, add_zero] at hω
      exact lt_irrefl _ hω
    refine ⟨(rk1 τ * u * pHpriv τ)ᴴ, hBstar _ hw', ?_, ?_⟩
    · intro h; exact h1 (by simpa using congrArg conjTranspose h)
    · have he : (rk1 τ * u * pHpriv τ)ᴴ = pHpriv τ * uᴴ * rk1 τ := by
        simp only [conjTranspose_mul, rk1_conjTranspose, pHpriv_conjTranspose, Matrix.mul_assoc]
      rw [he, pHpriv_corner_idem hτ hτu]
  · exact ⟨_, hw, h0, pHpriv_corner_idem hτ hτu u⟩

include hBle hBstar hτ hτu hpriv in
/-- **Colour block (`eq:colour-M3`, intrinsic form).**  If `B` contains `M₂(H_priv)` and a
word with `ω_col > 0`, every colour-block matrix `P₀ Z P₀` lies in `B`. -/
theorem colour_block_mem {u : Matrix (Fin 7) (Fin 7) ℂ} (huB : u ∈ B)
    (hω : 0 < omegaCol τ u) (Z : Matrix (Fin 7) (Fin 7) ℂ) :
    centralProj 0 * Z * centralProj 0 ∈ B := by
  obtain ⟨v, hvB, hv0, hvf⟩ := exists_corner_of_omegaCol_pos hBle hBstar hτ hτu hpriv huB hω
  have hp : rk1 τ ∈ B := rk1_mem_of_corner hBstar hτu hvB hv0 hvf
  have hvp : v * rk1 τ = v := by rw [← hvf, Matrix.mul_assoc, rk1_mul_rk1 hτu]
  have hpv : pHpriv τ * v = v := by
    rw [← hvf, ← Matrix.mul_assoc, ← Matrix.mul_assoc, pHpriv_mul_self hτ hτu]
  obtain ⟨c, hc, hkey⟩ := exists_conjTranspose_mul_corner hτu hv0 hvp
  -- `H_priv ← T` corners
  have hcorner : ∀ Y : Matrix (Fin 7) (Fin 7) ℂ, pHpriv τ * Y * rk1 τ ∈ B := by
    intro Y
    have h1 : pHpriv τ * (Y * rk1 τ * vᴴ) * pHpriv τ * v =
        c • (pHpriv τ * Y * rk1 τ) := by
      calc pHpriv τ * (Y * rk1 τ * vᴴ) * pHpriv τ * v
          = pHpriv τ * Y * rk1 τ * (vᴴ * (pHpriv τ * v)) := by simp only [Matrix.mul_assoc]
        _ = c • (pHpriv τ * Y * rk1 τ) := by
          rw [hpv, hkey, Matrix.mul_smul, Matrix.mul_assoc (pHpriv τ * Y), rk1_mul_rk1 hτu]
    have h2 := B.smul_mem (mul_mem (hpriv (Y * rk1 τ * vᴴ)) hvB) c⁻¹
    rwa [h1, smul_smul, inv_mul_cancel₀ hc, one_smul] at h2
  have hcorner' : ∀ Y : Matrix (Fin 7) (Fin 7) ℂ, rk1 τ * Y * pHpriv τ ∈ B := by
    intro Y
    have h := hBstar _ (hcorner Yᴴ)
    simpa only [conjTranspose_mul, rk1_conjTranspose, pHpriv_conjTranspose,
      conjTranspose_conjTranspose, Matrix.mul_assoc] using h
  have hdiag : rk1 τ * Z * rk1 τ ∈ B := by
    rw [rk1_mul_mul_rk1]; exact B.smul_mem hp _
  have hP0 : centralProj 0 = rk1 τ + pHpriv τ := by rw [pHpriv]; abel
  rw [hP0]
  simp only [Matrix.add_mul, Matrix.mul_add]
  exact add_mem (add_mem hdiag (hcorner Z)) (add_mem (hcorner' Z) (hpriv Z))

end ColourGen

/-! ### The weak block is generated -/

section WeakGen

theorem normSqVec_weakPart {v : Fin 7 → ℂ} (hv : BlockSupported 1 v) (hvu : IsUnitVec v) :
    BridgeRouter.normSqVec (FiniteLanding.weakPart v) = 1 := by
  apply Complex.ofReal_injective
  have h0 : v 0 = 0 := hv 0 (by decide)
  have h1 : v 1 = 0 := hv 1 (by decide)
  have h2 : v 2 = 0 := hv 2 (by decide)
  have h5 : v 5 = 0 := hv 5 (by decide)
  have h6 : v 6 = 0 := hv 6 (by decide)
  unfold IsUnitVec at hvu
  rw [dotProduct, Fin.sum_univ_seven] at hvu
  simp only [Pi.star_apply, h0, h1, h2, h5, h6, star_zero, zero_mul, zero_add, add_zero] at hvu
  simp only [BridgeRouter.normSqVec, FiniteLanding.weakPart, Fin.sum_univ_two,
    Complex.ofReal_add, BridgeRouter.ofReal_normSq_eq, Complex.ofReal_one]
  simp only [Fin.isValue, cons_val_zero, cons_val_one]
  linear_combination hvu

/-- **Distinct rank-one projections on the weak plane have independent vectors**:
`|t⟩⟨t| ≠ |h⟩⟨h|` forces `t₃h₄ − t₄h₃ ≠ 0` (two-dimensional Lagrange identity). -/
theorem weakDet_ne_zero {t h : Fin 7 → ℂ} (ht : BlockSupported 1 t) (hh : BlockSupported 1 h)
    (htu : IsUnitVec t) (hhu : IsUnitVec h) (hne : rk1 t ≠ rk1 h) :
    t 3 * h 4 - t 4 * h 3 ≠ 0 := by
  intro hD
  apply hne
  have hl := BridgeRouter.lagrange_identity (FiniteLanding.weakPart t) (FiniteLanding.weakPart h)
  have hD' : FiniteLanding.weakPart t 0 * FiniteLanding.weakPart h 1 -
      FiniteLanding.weakPart t 1 * FiniteLanding.weakPart h 0 = 0 := by
    simpa [FiniteLanding.weakPart] using hD
  rw [hD', Complex.normSq_zero, zero_add, normSqVec_weakPart ht htu, normSqVec_weakPart hh hhu,
    mul_one] at hl
  have hp := (BridgeRouter.proj_eq_iff _ _ (normSqVec_weakPart ht htu)
    (normSqVec_weakPart hh hhu)).mpr hl
  have hidx : ∀ i : Fin 7, blockOf i = 1 → ∃ a : Fin 2, ![(3 : Fin 7), 4] a = i := by decide
  have hwp : ∀ (v : Fin 7 → ℂ) (a : Fin 2),
      FiniteLanding.weakPart v a = v (![(3 : Fin 7), 4] a) := by
    intro v a; fin_cases a <;> rfl
  ext i j
  simp only [rk1, vecMulVec_apply, Pi.star_apply]
  by_cases hi : blockOf i = 1
  · by_cases hj : blockOf j = 1
    · obtain ⟨a, rfl⟩ := hidx i hi
      obtain ⟨b, rfl⟩ := hidx j hj
      have := congrFun (congrFun hp a) b
      simpa only [BridgeRouter.proj, vecMulVec_apply, Pi.star_apply, hwp] using this
    · rw [ht j hj, hh j hj]; simp
  · rw [ht i hi, hh i hi]; simp

theorem star_piSingle_one (j : Fin 7) :
    star (Pi.single j (1 : ℂ) : Fin 7 → ℂ) = (Pi.single j (1 : ℂ) : Fin 7 → ℂ) := by
  ext k
  by_cases h : k = j
  · subst h; simp
  · simp [Pi.single_apply, h]

/-- `P₁ Z P₁` expanded in the weak matrix units. -/
theorem centralProj_one_sandwich (Z : Matrix (Fin 7) (Fin 7) ℂ) :
    centralProj 1 * Z * centralProj 1 =
      Z 3 3 • Matrix.single 3 3 1 + Z 3 4 • Matrix.single 3 4 1 +
        Z 4 3 • Matrix.single 4 3 1 + Z 4 4 • Matrix.single 4 4 1 := by
  ext i j
  rw [mul_centralProj_apply, centralProj_mul_apply]
  simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.single_apply, smul_eq_mul]
  fin_cases i <;> fin_cases j <;> simp [blockOf]

variable {B : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ)}

/-- **Weak block (`eq:weak-M2`, intrinsic form).**  Two distinct, non-orthogonal represented
rank-one projections `|t⟩⟨t|, |h⟩⟨h|` on the weak multiplicity plane put every weak-block
matrix `P₁ Z P₁` in `B`. -/
theorem weak_block_mem {t h : Fin 7 → ℂ} (ht : BlockSupported 1 t) (hh : BlockSupported 1 h)
    (htu : IsUnitVec t) (hhu : IsUnitVec h) (hPt : rk1 t ∈ B) (hPh : rk1 h ∈ B)
    (hne : rk1 t ≠ rk1 h) (hov : star t ⬝ᵥ h ≠ 0) (Z : Matrix (Fin 7) (Fin 7) ℂ) :
    centralProj 1 * Z * centralProj 1 ∈ B := by
  have hov' : star h ⬝ᵥ t ≠ 0 := by
    rw [star_dotProduct]; exact star_ne_zero.mpr hov
  have hth : vecMulVec t (star h) ∈ B := by
    have h1 := B.smul_mem (mul_mem hPt hPh) (star t ⬝ᵥ h)⁻¹
    rwa [rk1, rk1, vecMulVec_star_mul, smul_smul, inv_mul_cancel₀ hov, one_smul] at h1
  have hht : vecMulVec h (star t) ∈ B := by
    have h1 := B.smul_mem (mul_mem hPh hPt) (star h ⬝ᵥ t)⁻¹
    rwa [rk1, rk1, vecMulVec_star_mul, smul_smul, inv_mul_cancel₀ hov', one_smul] at h1
  have hcomb : ∀ a b c d : ℂ, vecMulVec (a • t + b • h) (star (c • t + d • h)) ∈ B := by
    intro a b c d
    rw [star_add, star_smul, star_smul, add_vecMulVec, vecMulVec_add, vecMulVec_add,
      smul_vecMulVec, smul_vecMulVec, smul_vecMulVec, smul_vecMulVec, vecMulVec_smul,
      vecMulVec_smul, vecMulVec_smul, vecMulVec_smul]
    exact add_mem (add_mem (B.smul_mem (B.smul_mem hPt _) _) (B.smul_mem (B.smul_mem hth _) _))
      (add_mem (B.smul_mem (B.smul_mem hht _) _) (B.smul_mem (B.smul_mem hPh _) _))
  set D := t 3 * h 4 - t 4 * h 3 with hDdef
  have hD : D ≠ 0 := weakDet_ne_zero ht hh htu hhu hne
  have ht0 : t 0 = 0 := ht 0 (by decide)
  have ht1 : t 1 = 0 := ht 1 (by decide)
  have ht2 : t 2 = 0 := ht 2 (by decide)
  have ht5 : t 5 = 0 := ht 5 (by decide)
  have ht6 : t 6 = 0 := ht 6 (by decide)
  have hh0 : h 0 = 0 := hh 0 (by decide)
  have hh1 : h 1 = 0 := hh 1 (by decide)
  have hh2 : h 2 = 0 := hh 2 (by decide)
  have hh5 : h 5 = 0 := hh 5 (by decide)
  have hh6 : h 6 = 0 := hh 6 (by decide)
  have he3 : Pi.single (3 : Fin 7) (1 : ℂ) = (h 4 / D) • t + (-t 4 / D) • h := by
    ext i
    fin_cases i <;> simp [ht0, ht1, ht2, ht5, ht6, hh0, hh1, hh2, hh5, hh6]
    · field_simp; rw [hDdef]; ring
    · field_simp; ring
  have he4 : Pi.single (4 : Fin 7) (1 : ℂ) = (-h 3 / D) • t + (t 3 / D) • h := by
    ext i
    fin_cases i <;> simp [ht0, ht1, ht2, ht5, ht6, hh0, hh1, hh2, hh5, hh6]
    · field_simp; ring
    · field_simp; rw [hDdef]; ring
  have hsp : ∀ i : Fin 7, (i = 3 ∨ i = 4) →
      ∃ a b : ℂ, (Pi.single i (1 : ℂ) : Fin 7 → ℂ) = a • t + b • h := by
    rintro i (rfl | rfl)
    · exact ⟨_, _, he3⟩
    · exact ⟨_, _, he4⟩
  have hunit : ∀ i j : Fin 7, (i = 3 ∨ i = 4) → (j = 3 ∨ j = 4) →
      Matrix.single i j (1 : ℂ) ∈ B := by
    intro i j hi hj
    obtain ⟨a, b, hab⟩ := hsp i hi
    obtain ⟨c, d, hcd⟩ := hsp j hj
    rw [single_eq_single_vecMulVec_single, ← star_piSingle_one j, hab, hcd]
    exact hcomb a b c d
  rw [centralProj_one_sandwich]
  exact add_mem (add_mem (add_mem
    (B.smul_mem (hunit 3 3 (Or.inl rfl) (Or.inl rfl)) _)
    (B.smul_mem (hunit 3 4 (Or.inl rfl) (Or.inr rfl)) _))
    (B.smul_mem (hunit 4 3 (Or.inr rfl) (Or.inl rfl)) _))
    (B.smul_mem (hunit 4 4 (Or.inr rfl) (Or.inr rfl)) _)

end WeakGen

/-! ### Scalar sectors and the block-coordinate core -/

section Core

variable {B : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ)}

/-- **Assembly**: a unital subalgebra of `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ` containing the full colour and
weak blocks and a word separating the two scalar characters is everything. -/
theorem eq_blockAlgebra_of_blocks (hBle : B ≤ blockAlgebra)
    (h0 : ∀ Z, centralProj 0 * Z * centralProj 0 ∈ B)
    (h1 : ∀ Z, centralProj 1 * Z * centralProj 1 ∈ B)
    (hsep : ∃ y ∈ B, y 5 5 ≠ y 6 6) : B = blockAlgebra := by
  have hcorner : ∀ k : Fin 4, (∀ Z, centralProj k * Z * centralProj k ∈ B) →
      ∀ X ∈ blockAlgebra, centralProj k * X ∈ B := by
    intro k hk X hX
    have he : centralProj k * X = centralProj k * X * centralProj k := by
      rw [Matrix.mul_assoc, ← centralProj_comm hX, ← Matrix.mul_assoc, centralProj_mul_self]
    rw [he]; exact hk X
  have hP0X := hcorner 0 h0
  have hP1X := hcorner 1 h1
  have hP0 : centralProj 0 ∈ B := by
    have h := hP0X 1 blockAlgebra.one_mem; rwa [Matrix.mul_one] at h
  have hP1 : centralProj 1 ∈ B := by
    have h := hP1X 1 blockAlgebra.one_mem; rwa [Matrix.mul_one] at h
  have hE : Matrix.single (5 : Fin 7) 5 (1 : ℂ) + Matrix.single 6 6 1 ∈ B := by
    rw [single_add_single_eq]
    exact B.sub_mem (B.sub_mem B.one_mem hP0) hP1
  obtain ⟨b, hb, hb56⟩ := hsep
  have hbb := hBle hb
  have hE55 : Matrix.single (5 : Fin 7) 5 (1 : ℂ) ∈ B := by
    have h1 : b - centralProj 0 * b - centralProj 1 * b -
        b 6 6 • (Matrix.single 5 5 1 + Matrix.single 6 6 1) ∈ B :=
      B.sub_mem (B.sub_mem (B.sub_mem hb (hP0X b hbb)) (hP1X b hbb)) (B.smul_mem hE _)
    have h2 : b - centralProj 0 * b - centralProj 1 * b -
        b 6 6 • (Matrix.single 5 5 1 + Matrix.single 6 6 1) =
        (b 5 5 - b 6 6) • Matrix.single 5 5 1 := by
      have hdec := scalar_decomp hbb
      nth_rewrite 1 [hdec]
      simp only [smul_add, sub_smul]
      abel
    rw [h2] at h1
    have := B.smul_mem h1 (b 5 5 - b 6 6)⁻¹
    rwa [smul_smul, inv_mul_cancel₀ (sub_ne_zero.mpr hb56), one_smul] at this
  have hE66 : Matrix.single (6 : Fin 7) 6 (1 : ℂ) ∈ B := by
    have := B.sub_mem hE hE55
    rwa [add_sub_cancel_left] at this
  refine le_antisymm hBle fun X hX => ?_
  rw [scalar_decomp hX]
  exact B.add_mem (B.add_mem (B.add_mem (hP0X X hX) (hP1X X hX)) (B.smul_mem hE55 _))
    (B.smul_mem hE66 _)

/-- **Block-coordinate saturation core of `thm:internal-seed-saturation`.**  Let `B` be a
star-closed unital subalgebra of `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ` (the census carrier) such that, for a
coherent realisation `T ⊕ H_priv` of the colour block (`T = ℂτ`, `τ` any unit vector of the
colour block):
(I1) `B ⊇ M₂(H_priv)` and some `u ∈ B` has `ω_col(u) > 0`;
(I2) `B` contains two distinct, non-orthogonal rank-one projections of the weak plane;
(I4) some `y ∈ B` separates the two scalar characters.
Then `B = M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ`. -/
theorem eq_blockAlgebra_of_landing (hBle : B ≤ blockAlgebra) (hBstar : ∀ a ∈ B, aᴴ ∈ B)
    {τ : Fin 7 → ℂ} (hτ : BlockSupported 0 τ) (hτu : IsUnitVec τ)
    (hpriv : ∀ X : Matrix (Fin 7) (Fin 7) ℂ, pHpriv τ * X * pHpriv τ ∈ B)
    {u : Matrix (Fin 7) (Fin 7) ℂ} (huB : u ∈ B) (hω : 0 < omegaCol τ u)
    {t h : Fin 7 → ℂ} (ht : BlockSupported 1 t) (hh : BlockSupported 1 h)
    (htu : IsUnitVec t) (hhu : IsUnitVec h) (hPt : rk1 t ∈ B) (hPh : rk1 h ∈ B)
    (hne : rk1 t ≠ rk1 h) (hov : star t ⬝ᵥ h ≠ 0)
    (hsep : ∃ y ∈ B, y 5 5 ≠ y 6 6) : B = blockAlgebra :=
  eq_blockAlgebra_of_blocks hBle (colour_block_mem hBle hBstar hτ hτu hpriv huB hω)
    (weak_block_mem ht hh htu hhu hPt hPh hne hov) hsep

end Core

/-! ### The reciprocal alternative of (I1) for actual words -/

section Reciprocal

theorem frobSq_pos_of_ne_zero {A : Matrix (Fin 7) (Fin 7) ℂ} (hA : A ≠ 0) :
    0 < BridgeRouter.frobSq A := by
  rcases lt_or_eq_of_le (BridgeRouter.frobSq_nonneg A) with h | h
  · exact h
  · exfalso
    apply hA
    have hrow := (Finset.sum_eq_zero_iff_of_nonneg fun i _ =>
      Finset.sum_nonneg fun j _ => Complex.normSq_nonneg _).mp h.symm
    ext i j
    have hij := (Finset.sum_eq_zero_iff_of_nonneg fun j _ => Complex.normSq_nonneg _).mp
      (hrow i (Finset.mem_univ i)) j (Finset.mem_univ j)
    exact Complex.normSq_eq_zero.mp hij

/-- A word with a nonzero `H_priv ← T` corner has `ω_col > 0`. -/
theorem omegaCol_pos_of_corner_ne_zero {τ : Fin 7 → ℂ} {u : Matrix (Fin 7) (Fin 7) ℂ}
    (hu : pHpriv τ * u * rk1 τ ≠ 0) : 0 < omegaCol τ u := by
  have h1 := frobSq_pos_of_ne_zero hu
  have h2 := BridgeRouter.frobSq_nonneg (rk1 τ * u * pHpriv τ)
  rw [omegaCol]; linarith

/-- An `H_priv ← T` corner `r` of a mediator bank embedded through a frame `η` of `H_priv`
and the type vector `τ`: `r ↦ ∑_a r_a |η_a⟩⟨τ|`. -/
def embedCorner {H T : Type} [Fintype H] [Unique T] (η : H → Fin 7 → ℂ) (τ : Fin 7 → ℂ)
    (r : Matrix H T ℂ) : Matrix (Fin 7) (Fin 7) ℂ :=
  ∑ a, r a default • vecMulVec (η a) (star τ)

/-- Orthonormality of a frame of vectors of the census carrier. -/
def Orthonormal7 {H : Type} [DecidableEq H] (η : H → Fin 7 → ℂ) : Prop :=
  ∀ a b, star (η a) ⬝ᵥ η b = if a = b then 1 else 0

theorem rk1_ne_zero {τ : Fin 7 → ℂ} (hτu : IsUnitVec τ) : rk1 τ ≠ 0 := by
  intro h
  have ht := congrArg Matrix.trace h
  rw [rk1, trace_vecMulVec, dotProduct_comm, hτu, trace_zero] at ht
  exact one_ne_zero ht

/-- The embedding of a nonzero corner through an orthonormal frame is nonzero. -/
theorem embedCorner_ne_zero {H T : Type} [Fintype H] [DecidableEq H] [Unique T]
    {η : H → Fin 7 → ℂ} (hη : Orthonormal7 η) {τ : Fin 7 → ℂ} (hτu : IsUnitVec τ)
    {r : Matrix H T ℂ} (hr : r ≠ 0) : embedCorner η τ r ≠ 0 := by
  intro h0
  apply hr
  ext b c
  rw [Unique.eq_default c, Matrix.zero_apply]
  have hprod : vecMulVec τ (star (η b)) * embedCorner η τ r = r b default • rk1 τ := by
    rw [embedCorner, Finset.mul_sum]
    simp only [Matrix.mul_smul, vecMulVec_star_mul]
    rw [Finset.sum_eq_single b]
    · rw [hη b b, if_pos rfl, one_smul]; rfl
    · intro a _ hab; rw [hη b a, if_neg (Ne.symm hab), zero_smul, smul_zero]
    · intro h; exact absurd (Finset.mem_univ b) h
  rw [h0, Matrix.mul_zero] at hprod
  exact (smul_eq_zero.mp hprod.symm).resolve_right (rk1_ne_zero hτu)

/-- **The reciprocal alternative of (I1) for represented words.**  An admitted reciprocal
mediator bank `(v, h, A, Bm)` (`thm:reciprocal-return`) with positive return mass at some
horizon `n`, whose returned words `r_{g,k} = Bm^*(v_g ⊗ h^k)A : T → H_priv` are the
`H_priv ← T` corners of represented words of `BB`, read through an orthonormal frame `η` of
`H_priv`. -/
def ReciprocalWordBridge (BB : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ)) (τ : Fin 7 → ℂ) :
    Prop :=
  ∃ (V N T H G : Type) (_ : Fintype V) (_ : DecidableEq V) (_ : Fintype N) (_ : DecidableEq N)
    (_ : Fintype T) (_ : Unique T) (_ : Fintype H) (_ : DecidableEq H) (_ : Fintype G)
    (_ : Group G) (η : H → Fin 7 → ℂ) (v : G → Matrix V V ℂ) (h : Matrix N N ℂ)
    (A : Matrix (V × N) T ℂ) (Bm : Matrix (V × N) H ℂ) (n : ℕ),
    Orthonormal7 η ∧ (∀ a, pHpriv τ *ᵥ η a = η a) ∧
    0 < ReciprocalReturnMass.mass v h A Bm n ∧
    ∀ (g : G) (k : ℕ), ∃ u ∈ BB,
      pHpriv τ * u * rk1 τ = embedCorner η τ (ReciprocalReturnMass.word v h A Bm g k)

/-- `m_ret > 0` supplies a represented word with `ω_col > 0` (`mass_pos_iff`). -/
theorem exists_omegaCol_pos_of_reciprocal {BB : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ)}
    {τ : Fin 7 → ℂ} (hτu : IsUnitVec τ) (hrec : ReciprocalWordBridge BB τ) :
    ∃ u ∈ BB, 0 < omegaCol τ u := by
  obtain ⟨V, N, T, H, G, _, _, _, _, _, _, _, _, _, _, η, v, h, A, Bm, n, hη, -, hmass, hrep⟩ :=
    hrec
  obtain ⟨g, k, hk⟩ := (ReciprocalReturnMass.mass_pos_iff v h A Bm n).mp hmass
  obtain ⟨u, hu, hcorner⟩ := hrep g k
  refine ⟨u, hu, omegaCol_pos_of_corner_ne_zero ?_⟩
  rw [hcorner]
  exact embedCorner_ne_zero hη hτu hk

end Reciprocal

/-! ### The fixed isomorphism `Φ₀ = censusCommutantEquiv` is a `*`-isomorphism -/

section Star

open InternalSeedSaturation

variable {n : Type} [Fintype n] [DecidableEq n] {G : Type} [Group G]
  {ι : Type} [Fintype ι] [DecidableEq ι] {I J : ι → Type}
  [∀ b, Fintype (I b)] [∀ b, DecidableEq (I b)] [∀ b, Fintype (J b)] [∀ b, DecidableEq (J b)]

theorem blockHom7_star (e : ι ≃ Fin 4) (hcard : ∀ k, Fintype.card (J (e.symm k)) = ![3, 2, 1, 1] k)
    (Y : ∀ b, Matrix (J b) (J b) ℂ) :
    blockHom7 e hcard (star Y) = (blockHom7 e hcard Y)ᴴ := by
  ext i j
  rw [blockHom7_apply, conjTranspose_apply, blockHom7_apply]
  have h := congrFun (congrFun (blockDiagonal'_conjTranspose Y) (censusEquiv e hcard i))
    (censusEquiv e hcard j)
  rw [conjTranspose_apply] at h
  exact h.symm

theorem multBlockHom_star (Y : ∀ b, Matrix (J b) (J b) ℂ) :
    multBlockHom I J (star Y) = (multBlockHom I J Y)ᴴ := by
  rw [multBlockHom_apply, multBlockHom_apply, blockDiagonal'_conjTranspose]
  congr 1
  funext b
  rw [conjTranspose_kronecker, conjTranspose_one]
  rfl

theorem extEmbed_star (W : Matrix n (Σ b, I b × J b) ℂ) (hW1 : Wᴴ * W = 1) (hW2 : W * Wᴴ = 1)
    (Y : ∀ b, Matrix (J b) (J b) ℂ) :
    extEmbed I J W hW1 hW2 (star Y) = (extEmbed I J W hW1 hW2 Y)ᴴ := by
  rw [extEmbed_apply, extEmbed_apply, multBlockHom_star, conjTranspose_mul, conjTranspose_mul,
    conjTranspose_conjTranspose, Matrix.mul_assoc]

variable (ρ : G →* Matrix n n ℂ) (W : Matrix n (Σ b, I b × J b) ℂ) (hW1 : Wᴴ * W = 1)
  (hW2 : W * Wᴴ = 1) (hNI : ∀ b, Nonempty (I b))
  (hM : (fun x => Wᴴ * x * W) ''
      matCommutant (Algebra.adjoin ℂ (Set.range ρ) : Set (Matrix n n ℂ)) = multBlockSet I J)
  (e : ι ≃ Fin 4) (hcard : ∀ k, Fintype.card (J (e.symm k)) = ![3, 2, 1, 1] k)

/-- `Φ₀` on block coordinates: `Φ₀(blockHom7 Y) = W (⊕_b 1 ⊗ Y_b) Wᴴ`. -/
theorem censusCommutantEquiv_blockHom7 (Y : ∀ b, Matrix (J b) (J b) ℂ)
    (hY : blockHom7 e hcard Y ∈ blockAlgebra) :
    ((censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard ⟨_, hY⟩ : extCommutant ρ) :
        Matrix n n ℂ) = extEmbed I J W hW1 hW2 Y := by
  have h2 : (AlgEquiv.ofInjective _ (blockHom7_injective e hcard)).symm
      (Subalgebra.equivOfEq _ _ (range_blockHom7 e hcard).symm ⟨_, hY⟩) = Y := by
    rw [AlgEquiv.symm_apply_eq]; rfl
  simp only [censusCommutantEquiv, AlgEquiv.trans_apply]
  rw [h2]
  rfl

/-- **`Φ₀` is a `*`-isomorphism**: `Φ₀(yᴴ) = Φ₀(y)ᴴ`. -/
theorem censusCommutantEquiv_star (y : Matrix (Fin 7) (Fin 7) ℂ) (hy : y ∈ blockAlgebra)
    (hy' : yᴴ ∈ blockAlgebra) :
    ((censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard ⟨yᴴ, hy'⟩ : extCommutant ρ) :
        Matrix n n ℂ) =
      ((censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard ⟨y, hy⟩ : extCommutant ρ) :
        Matrix n n ℂ)ᴴ := by
  have hr : y ∈ (blockHom7 e hcard).range := by rw [range_blockHom7]; exact hy
  obtain ⟨Y, hYeq⟩ := hr
  have hyY : y = blockHom7 e hcard Y := hYeq.symm
  subst hyY
  have hs : (blockHom7 e hcard Y)ᴴ = blockHom7 e hcard (star Y) := (blockHom7_star e hcard Y).symm
  have hy'' : blockHom7 e hcard (star Y) ∈ blockAlgebra := hs ▸ hy'
  have hsub : (⟨(blockHom7 e hcard Y)ᴴ, hy'⟩ : blockAlgebra) =
      ⟨blockHom7 e hcard (star Y), hy''⟩ := Subtype.ext hs
  rw [hsub, censusCommutantEquiv_blockHom7, censusCommutantEquiv_blockHom7, extEmbed_star]

theorem blockAlgebra_conjTranspose_mem {y : Matrix (Fin 7) (Fin 7) ℂ} (hy : y ∈ blockAlgebra) :
    yᴴ ∈ blockAlgebra :=
  CentralSeparation.blockStarAlgebra.star_mem' hy

include W hW1 hW2 hNI hM e hcard in
/-- The relative commutant is star-closed (transported through `Φ₀`). -/
theorem extCommutant_conjTranspose_mem {z : Matrix n n ℂ} (hz : z ∈ extCommutant ρ) :
    zᴴ ∈ extCommutant ρ := by
  set Φ := censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard
  set m := Φ.symm ⟨z, hz⟩
  have hm := censusCommutantEquiv_star ρ W hW1 hW2 hNI hM e hcard m.1 m.2
    (blockAlgebra_conjTranspose_mem m.2)
  have hz' : ((Φ ⟨m.1, m.2⟩ : extCommutant ρ) : Matrix n n ℂ) = z := by
    show ((Φ m : extCommutant ρ) : Matrix n n ℂ) = z
    rw [AlgEquiv.apply_symm_apply]
  rw [hz'] at hm
  rw [← hm]
  exact (Φ _).2

/-- The census-carrier coordinates `Φ₀⁻¹(x_j)` of represented words. -/
noncomputable def wordCoords {β : Type*} (x : β → Matrix n n ℂ)
    (hx : ∀ j, x j ∈ extCommutant ρ) (j : β) : Matrix (Fin 7) (Fin 7) ℂ :=
  ((censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard).symm ⟨x j, hx j⟩ : blockAlgebra)

theorem wordCoords_mem {β : Type*} (x : β → Matrix n n ℂ) (hx : ∀ j, x j ∈ extCommutant ρ)
    (j : β) : wordCoords ρ W hW1 hW2 hNI hM e hcard x hx j ∈ blockAlgebra :=
  ((censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard).symm ⟨x j, hx j⟩).2

/-- **Transport of the generated `C^*`-algebra through `Φ₀`.**  If the coordinates of the
represented words generate `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ` as a `C^*`-algebra, the words themselves generate
the relative commutant. -/
theorem starAdjoin_range_eq_of_coords {β : Type*} (x : β → Matrix n n ℂ)
    (hx : ∀ j, x j ∈ extCommutant ρ)
    (hgen : starAdjoin (Set.range (wordCoords ρ W hW1 hW2 hNI hM e hcard x hx)) =
      blockAlgebra) :
    starAdjoin (Set.range x) = extCommutant ρ := by
  set Φ := censusCommutantEquiv ρ W hW1 hW2 hNI hM e hcard
  set y := wordCoords ρ W hW1 hW2 hNI hM e hcard x hx
  apply le_antisymm
  · refine starAdjoin_le (fun a ha => extCommutant_conjTranspose_mem ρ W hW1 hW2 hNI hM e hcard ha)
      ?_
    rintro _ ⟨j, rfl⟩
    exact hx j
  · intro z hz
    -- the comap of `C^*(x)` along `ψ = val ∘ Φ₀` contains the preimage of the generators
    let ψ : blockAlgebra →ₐ[ℂ] Matrix n n ℂ := (extCommutant ρ).val.comp Φ.toAlgHom
    have hψy : ∀ j, ψ ⟨y j, wordCoords_mem ρ W hW1 hW2 hNI hM e hcard x hx j⟩ = x j := by
      intro j
      show ((Φ (Φ.symm ⟨x j, hx j⟩) : extCommutant ρ) : Matrix n n ℂ) = x j
      rw [AlgEquiv.apply_symm_apply]
    have hS : Set.range y ∪ star (Set.range y) ⊆ (blockAlgebra : Set (Matrix (Fin 7) (Fin 7) ℂ)) := by
      rintro w (⟨j, rfl⟩ | hs)
      · exact wordCoords_mem ρ W hW1 hW2 hNI hM e hcard x hx j
      · obtain ⟨j, hj⟩ := Set.mem_star.mp hs
        have hw : w = (y j)ᴴ := by rw [← Matrix.star_eq_conjTranspose, hj, star_star]
        rw [hw]
        exact blockAlgebra_conjTranspose_mem (wordCoords_mem ρ W hW1 hW2 hNI hM e hcard x hx j)
    have htop := InternalSeedSaturation.adjoin_preimage_val_eq_top blockAlgebra _ hS
      (by rw [← starAdjoin_eq_adjoin]; exact hgen)
    have hle : Algebra.adjoin ℂ (Subtype.val ⁻¹' (Set.range y ∪ star (Set.range y)) :
        Set blockAlgebra) ≤ (starAdjoin (Set.range x)).comap ψ := by
      rw [Algebra.adjoin_le_iff]
      rintro ⟨m, hm⟩ (⟨j, hj⟩ | hs)
      · have hmeq : (⟨m, hm⟩ : blockAlgebra) =
            ⟨y j, wordCoords_mem ρ W hW1 hW2 hNI hM e hcard x hx j⟩ := Subtype.ext hj.symm
        show ψ ⟨m, hm⟩ ∈ starAdjoin (Set.range x)
        rw [hmeq, hψy]
        exact subset_starAdjoin _ ⟨j, rfl⟩
      · obtain ⟨j, hj⟩ := Set.mem_star.mp hs
        have hm' : m = (y j)ᴴ := by rw [← Matrix.star_eq_conjTranspose, hj, star_star]
        have hmeq : (⟨m, hm⟩ : blockAlgebra) = ⟨(y j)ᴴ, hm' ▸ hm⟩ := Subtype.ext hm'
        show ψ ⟨m, hm⟩ ∈ starAdjoin (Set.range x)
        rw [hmeq]
        show ((Φ ⟨(y j)ᴴ, _⟩ : extCommutant ρ) : Matrix n n ℂ) ∈ _
        rw [censusCommutantEquiv_star ρ W hW1 hW2 hNI hM e hcard (y j)
          (wordCoords_mem ρ W hW1 hW2 hNI hM e hcard x hx j)]
        have := hψy j
        change ((Φ ⟨y j, _⟩ : extCommutant ρ) : Matrix n n ℂ) = x j at this
        rw [this]
        exact conjTranspose_mem_starAdjoin ⟨j, rfl⟩
    rw [htop] at hle
    have hmem := hle (Algebra.mem_top : Φ.symm ⟨z, hz⟩ ∈ ⊤)
    rw [Subalgebra.mem_comap] at hmem
    have hψz : ψ (Φ.symm ⟨z, hz⟩) = z := by
      show ((Φ (Φ.symm ⟨z, hz⟩) : extCommutant ρ) : Matrix n n ℂ) = z
      rw [AlgEquiv.apply_symm_apply]
    rwa [hψz] at hmem

end Star

end InternalSeedWords
end RenewalGeometry
