/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.StandardModel.RecordWitnessInstrument
import NCG.Algebra.CliffordGenerates

/-!
# The record-complete nonidentifiability witness, assembled (`prop:record-witness`)

Final layer of `prop:record-witness` of the spacetime–gauge duality paper.  The earlier layers
(`RecordWitnessNormalization`, `RecordWitnessCommutingFamily`, `RecordWitnessCliffordFamily`,
`RecordWitnessConcrete`, `RecordWitnessInstrument`) provide the two six-edge families, their
shared record data, the word effects and the Gram invariance of the Choi spectrum.  This file
adds the two remaining clauses and assembles the proposition.

* `kronOneAlgHom`: the unital embedding `A ↦ A ⊗ I₅` of `M_d(ℂ)` into `M_{d × 5}(ℂ)`; its range
  is the subalgebra `M_d(ℂ) ⊗ I₅`;
* `adjoin_cliffordHq_eq_kronOne`: **`eq:inequivalent-system-algebras`, Clifford half**: the
  unital algebra generated by the Clifford family `H^q_e` (any Helmert frame, the concrete
  Clifford family `cliffordSMST4`) is exactly `M₄(ℂ) ⊗ I₅`, via `NCG.CommonOrigin.gamma_generates`;
  `adjoin_completion_cliffordHq` is the same for the completions `K^q_e`;
* `choi_charpoly_kraus`: **`eq:matching-Choi-spectrum`**: for any six-edge family with the
  record data `eq:six-edge-normalization` / `eq:matching-record-data` and any four rank-one
  orthogonal record projectors summing to `I`, the characteristic polynomial of the Choi matrix
  of the resolved instrument is
  `X^{N−24} (X − (20/3)(12 − 11ϑ)) (X − 20ϑ/3)³ (X − 8ϑ/3)²⁰`, `N = (dim H_E ⊗ H_R)²`,
  i.e. the nonzero Choi spectrum is `{(20/3)(12−11ϑ)^{(1)}, (20ϑ/3)^{(3)}, (8ϑ/3)^{(20)}}`;
* `record_witness`: **`prop:record-witness`** assembled for the two concrete families.

Rendering notes.  The Choi vectors of the resolved instrument are `B C` with `B` the Choi
vectors of the `24` accepted operators `K_e ⊗ Q_a` and `C = [√((1−ϑ)/2) 𝟏 | √ϑ I]`, so the Choi
matrix is `B M_ϑ B^*` with `M_ϑ = C C^* = ϑ I + (1−ϑ) c c^*`, `c = 𝟏/√2`; its nonzero spectrum is
that of `M_ϑ G₂₄` with `G₂₄ = G₆ ⊗ I₄`, `G₆ = (8/3) I + (2/3) 𝟏𝟏ᵀ` (`Matrix.charpoly_mul_comm'`),
and `M_ϑ G₂₄ = (8ϑ/3) I + 𝟏₆𝟏₆ᵀ ⊗ ((2ϑ/3) I₄ + (10/3)(1−ϑ) 𝟏₄𝟏₄ᵀ)` is computed by two further
rank reductions.  The paper's `Q_a` are nonzero orthogonal projections on `H_R = ℂ⁴` summing to
`I`, hence of trace `1`; the Choi-spectrum clause takes `Tr Q_a = 1` as the hypothesis.
-/

open Matrix Kronecker Polynomial

namespace RenewalGeometry
namespace RecordWitness

open FiveKraus NCG.CommonOrigin

/-! ### The subalgebra `M_d(ℂ) ⊗ I₅` -/

section KronOne

variable (d : Type*) [Fintype d] [DecidableEq d]

/-- The unital algebra embedding `A ↦ A ⊗ I₅`. -/
def kronOneAlgHom : Matrix d d ℂ →ₐ[ℂ] Matrix (d × Fin 5) (d × Fin 5) ℂ where
  toFun A := A ⊗ₖ (1 : Matrix (Fin 5) (Fin 5) ℂ)
  map_one' := Matrix.one_kronecker_one
  map_mul' A B := by rw [← Matrix.mul_kronecker_mul, Matrix.one_mul]
  map_zero' := Matrix.zero_kronecker _
  map_add' A B := Matrix.add_kronecker _ _ _
  commutes' c := by
    simp only [Algebra.algebraMap_eq_smul_one, Matrix.smul_kronecker, Matrix.one_kronecker_one]

@[simp] theorem kronOneAlgHom_apply (A : Matrix d d ℂ) :
    kronOneAlgHom d A = A ⊗ₖ (1 : Matrix (Fin 5) (Fin 5) ℂ) := rfl

theorem mem_kronOne_range {X : Matrix (d × Fin 5) (d × Fin 5) ℂ} :
    X ∈ (kronOneAlgHom d).range ↔ ∃ A : Matrix d d ℂ, X = A ⊗ₖ (1 : Matrix (Fin 5) (Fin 5) ℂ) := by
  simp only [AlgHom.mem_range, kronOneAlgHom_apply]
  exact ⟨fun ⟨A, h⟩ => ⟨A, h.symm⟩, fun ⟨A, h⟩ => ⟨A, h.symm⟩⟩

end KronOne

/-! ### `C*(K^q) = M₄(ℂ) ⊗ I₅` -/

/-- **`eq:inequivalent-system-algebras`, Clifford half.**  For any Helmert frame, the unital
algebra generated by the Clifford edge operators `H^q_e` built from the concrete Clifford
family on `ℂ⁴` is exactly `M₄(ℂ) ⊗ I₅`. -/
theorem adjoin_cliffordHq_eq_kronOne (F : HelmertFrame) :
    Algebra.adjoin ℂ (Set.range (cliffordHq F cliffordSMST4)) = (kronOneAlgHom SMST4).range := by
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨e, rfl⟩
    exact (mem_kronOne_range SMST4).mpr ⟨cliffordH F cliffordSMST4 e, rfl⟩
  · rw [← Algebra.map_top, ← gamma_generates, ← Algebra.adjoin_image, Algebra.adjoin_le_iff]
    rintro _ ⟨_, ⟨μ, rfl⟩, rfl⟩
    have h := gammaTensor_mem_adjoin F cliffordSMST4 μ.castSucc
    have hΓ : cliffordSMST4.Γ μ.castSucc = gamma μ := cliffordSMST4Gen_castSucc μ
    rw [hΓ] at h
    exact h

/-- `C*(K^q_e) = M₄(ℂ) ⊗ I₅` for the completions `K^q_e = I/√18 + (i/3) H^q_e`. -/
theorem adjoin_completion_cliffordHq (F : HelmertFrame) :
    Algebra.adjoin ℂ (Set.range fun e => completion (cliffordHq F cliffordSMST4 e)) =
      (kronOneAlgHom SMST4).range := by
  rw [adjoin_range_completion, adjoin_cliffordHq_eq_kronOne]

/-! ### The Choi spectrum of the resolved instrument (`eq:matching-Choi-spectrum`) -/

section ChoiSpectrum

variable {m r ρ : Type*} [Fintype m] [DecidableEq m] [Fintype r] [DecidableEq r]
  [Fintype ρ] [DecidableEq ρ]

/-- The accepted operators `A_{e,a} = K_e ⊗ Q_a`. -/
def accepted (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (p : Fin 6 × ρ) :
    Matrix (m × r) (m × r) ℂ := K p.1 ⊗ₖ Q p.2

/-- The coefficient matrix `C = [√((1−ϑ)/2) 𝟏 | √ϑ I]` expressing the Choi vectors of the
resolved instrument through those of the accepted operators. -/
noncomputable def coeffMat (ρ : Type*) [DecidableEq ρ] (θ : ℝ) :
    Matrix (Fin 6 × ρ) (Letter ρ) ℂ :=
  Matrix.of fun p ℓ => ℓ.elim ((Real.sqrt (1 - θ) / Real.sqrt 2 : ℝ) : ℂ)
    (fun q => if p = q then ((Real.sqrt θ : ℝ) : ℂ) else 0)

/-- `M_ϑ = C C^* = ϑ I + ((1−ϑ)/2) 𝟏𝟏ᵀ`. -/
noncomputable def coeffGram (ρ : Type*) [DecidableEq ρ] (θ : ℝ) :
    Matrix (Fin 6 × ρ) (Fin 6 × ρ) ℂ :=
  Matrix.of fun p q => (if p = q then (θ : ℂ) else 0) + ((1 - θ : ℝ) : ℂ) / 2

/-- The Gram `G₂₄ = G₆ ⊗ I₄` of the accepted operators. -/
noncomputable def gram24 (ρ : Type*) [DecidableEq ρ] : Matrix (Fin 6 × ρ) (Fin 6 × ρ) ℂ :=
  Matrix.of fun p q => (if p.1 = q.1 then (10 / 3 : ℂ) else 2 / 3) * (if p.2 = q.2 then 1 else 0)

/-- The core `M_ϑ G₂₄ = (8ϑ/3) I + (2ϑ/3) 𝟏₆𝟏₆ᵀ ⊗ I₄ + (10/3)(1−ϑ) 𝟏𝟏ᵀ`. -/
noncomputable def choiCore (ρ : Type*) [DecidableEq ρ] (θ : ℝ) :
    Matrix (Fin 6 × ρ) (Fin 6 × ρ) ℂ :=
  Matrix.of fun p q => (if p = q then (8 * θ / 3 : ℂ) else 0) +
    (if p.2 = q.2 then (2 * θ / 3 : ℂ) else 0) + 10 / 3 * (1 - θ)

/-- The Choi vectors of the resolved instrument are `B C`. -/
theorem choiVec_kraus (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (hKsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) (hQsum : ∑ a, Q a = 1) :
    choiVec (kraus K Q θ) = choiVec (accepted K Q) * coeffMat ρ θ := by
  ext ⟨x, y⟩ ℓ
  rcases ℓ with _ | ⟨e, a⟩
  · simp only [choiVec, Matrix.mul_apply, Matrix.of_apply, coeffMat, Option.elim, kraus,
      accepted]
    rw [← Finset.sum_mul, ← Matrix.sum_apply]
    have hsum : ∑ p : Fin 6 × ρ, K p.1 ⊗ₖ Q p.2 =
        ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix (m × r) (m × r) ℂ) := by
      rw [Fintype.sum_prod_type, ← sum_kronecker_sum, hKsum, hQsum, Matrix.smul_kronecker,
        Matrix.one_kronecker_one]
    rw [hsum]
    have h2 : ((Real.sqrt 2 : ℝ) : ℂ) ≠ 0 := by
      exact_mod_cast (Real.sqrt_pos.mpr two_pos).ne'
    simp only [Matrix.smul_apply, smul_eq_mul]
    push_cast
    field_simp
  · simp only [choiVec, Matrix.mul_apply, Matrix.of_apply, coeffMat, Option.elim, kraus,
      accepted, mul_ite, mul_zero, Fintype.sum_ite_eq', Matrix.smul_apply, smul_eq_mul]
    ring

/-- `C C^* = M_ϑ`. -/
theorem coeffMat_mul_conjTranspose (θ : ℝ) (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1) :
    coeffMat ρ θ * (coeffMat ρ θ)ᴴ = coeffGram ρ θ := by
  ext p q
  have hA : ((Real.sqrt (1 - θ) / Real.sqrt 2 : ℝ) : ℂ) *
      ((Real.sqrt (1 - θ) / Real.sqrt 2 : ℝ) : ℂ) = ((1 - θ : ℝ) : ℂ) / 2 := by
    rw [← Complex.ofReal_mul, div_mul_div_comm, Real.mul_self_sqrt (sub_nonneg.mpr hθ1),
      Real.mul_self_sqrt zero_le_two]
    push_cast
    ring
  have hB : ((Real.sqrt θ : ℝ) : ℂ) * ((Real.sqrt θ : ℝ) : ℂ) = (θ : ℂ) := by
    rw [← Complex.ofReal_mul, Real.mul_self_sqrt hθ0]
  simp only [Matrix.mul_apply, Matrix.conjTranspose_apply, coeffMat, coeffGram, Matrix.of_apply,
    Fintype.sum_option, Option.elim, Complex.star_def, Complex.conj_ofReal, apply_ite
    (starRingEnd ℂ), map_zero, mul_ite, mul_zero, ite_mul, zero_mul, Fintype.sum_ite_eq, hA, hB]
  split_ifs <;> ring

/-- The Gram of the accepted operators is `G₆ ⊗ I₄` when `Tr Q_a = 1`. -/
theorem hsGram_accepted (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ)
    (hgram : ∀ e f, ((K e)ᴴ * K f).trace = if e = f then 10 / 3 else 2 / 3)
    (hQ : ∀ a, (Q a)ᴴ = Q a) (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0)
    (hQtr : ∀ a, (Q a).trace = 1) :
    hsGram (accepted K Q) = gram24 ρ := by
  ext p q
  simp only [hsGram, gram24, Matrix.of_apply, accepted, Matrix.conjTranspose_kronecker,
    ← Matrix.mul_kronecker_mul, Matrix.trace_kronecker, hgram, hQ, hQQ]
  by_cases h : p.2 = q.2
  · rw [if_pos h, if_pos h, hQtr]
  · rw [if_neg h, if_neg h, Matrix.trace_zero]

theorem sum_six_gram (f : Fin 6) :
    ∑ e : Fin 6, (if e = f then (10 / 3 : ℂ) else 2 / 3) = 20 / 3 := by
  fin_cases f <;> simp [Fin.sum_univ_succ] <;> norm_num

/-- `M_ϑ G₂₄` is the core matrix. -/
theorem coeffGram_mul_gram24 (θ : ℝ) : coeffGram ρ θ * gram24 ρ = choiCore ρ θ := by
  have hsumG : ∀ q : Fin 6 × ρ, ∑ s : Fin 6 × ρ, gram24 ρ s q = 20 / 3 := by
    intro q
    simp only [gram24, Matrix.of_apply]
    simp only [Fintype.sum_prod_type]
    have hinner : ∀ x : Fin 6, ∑ c : ρ, (if x = q.1 then (10 / 3 : ℂ) else 2 / 3) *
        (if c = q.2 then 1 else 0) = if x = q.1 then 10 / 3 else 2 / 3 := by
      intro x
      rw [← Finset.mul_sum, Fintype.sum_ite_eq', mul_one]
    simp only [hinner]
    exact sum_six_gram q.1
  ext p q
  simp only [Matrix.mul_apply, coeffGram, Matrix.of_apply, add_mul, ite_mul, zero_mul,
    Finset.sum_add_distrib, Fintype.sum_ite_eq, ← Finset.mul_sum, hsumG]
  simp only [gram24, choiCore, Matrix.of_apply]
  by_cases h1 : p.1 = q.1 <;> by_cases h2 : p.2 = q.2
  · have h : p = q := Prod.ext h1 h2
    simp only [h, ite_true]
    push_cast
    ring
  · have h : p ≠ q := fun h => h2 (congrArg Prod.snd h)
    simp only [h1, h2, h, ite_true, ite_false]
    push_cast
    ring
  · have h : p ≠ q := fun h => h1 (congrArg Prod.fst h)
    simp only [h1, h2, h, ite_true, ite_false]
    push_cast
    ring
  · have h : p ≠ q := fun h => h1 (congrArg Prod.fst h)
    simp only [h1, h2, h, ite_true, ite_false]
    push_cast
    ring

/-- The `4 × 4` block `Q = (2ϑ/3) I₄ + (10/3)(1−ϑ) 𝟏𝟏ᵀ`. -/
noncomputable def coreBlock (ρ : Type*) [DecidableEq ρ] (θ : ℝ) : Matrix ρ ρ ℂ :=
  Matrix.of fun a b => (if a = b then (2 * θ / 3 : ℂ) else 0) + 10 / 3 * (1 - θ)

/-- The left factor `P` of `𝟏₆𝟏₆ᵀ ⊗ Q = P R`. -/
noncomputable def coreLeft (ρ : Type*) [DecidableEq ρ] (θ : ℝ) : Matrix (Fin 6 × ρ) ρ ℂ :=
  Matrix.of fun p b => coreBlock ρ θ p.2 b

/-- The right factor `R` of `𝟏₆𝟏₆ᵀ ⊗ Q = P R`. -/
def coreRight (ρ : Type*) [DecidableEq ρ] : Matrix ρ (Fin 6 × ρ) ℂ :=
  Matrix.of fun b q => if b = q.2 then 1 else 0

theorem choiCore_eq_sub_scalar (θ : ℝ) :
    choiCore ρ θ = coreLeft ρ θ * coreRight ρ - Matrix.scalar (Fin 6 × ρ) (-(8 * θ / 3 : ℂ)) := by
  ext p q
  simp only [choiCore, coreLeft, coreRight, coreBlock, Matrix.sub_apply, Matrix.mul_apply,
    Matrix.of_apply, mul_ite, mul_one, mul_zero, Fintype.sum_ite_eq', Matrix.scalar_apply,
    Matrix.diagonal_apply]
  split_ifs <;> ring

theorem coreRight_mul_coreLeft (θ : ℝ) :
    coreRight ρ * coreLeft ρ θ =
      Matrix.vecMulVec (fun _ : ρ => (20 * (1 - θ) : ℂ)) (fun _ => 1) -
        Matrix.scalar ρ (-(4 * θ : ℂ)) := by
  ext a b
  simp only [coreRight, coreLeft, coreBlock, Matrix.mul_apply, Matrix.of_apply, ite_mul, one_mul,
    zero_mul, Fintype.sum_prod_type, Fintype.sum_ite_eq, Matrix.sub_apply,
    Matrix.vecMulVec_apply, Matrix.scalar_apply, Matrix.diagonal_apply]
  split_ifs <;> simp only [Finset.sum_const, Finset.card_univ, Fintype.card_fin, nsmul_eq_mul] <;>
    push_cast <;> ring

/-- The characteristic polynomial of the `4 × 4` block, scaled by `6`. -/
theorem charpoly_coreRight_mul_coreLeft (hρ : Fintype.card ρ = 4) (θ : ℝ) :
    (coreRight ρ * coreLeft ρ θ).charpoly =
      (X - C (4 * θ : ℂ)) ^ 3 * (X - C (4 * θ + 80 * (1 - θ) : ℂ)) := by
  rw [coreRight_mul_coreLeft, Matrix.charpoly_sub_scalar, Matrix.charpoly_vecMulVec, hρ]
  have hdot : (fun _ : ρ => (20 * (1 - θ) : ℂ)) ⬝ᵥ (fun _ => 1) = 80 * (1 - θ) := by
    simp only [dotProduct, mul_one, Finset.sum_const, Finset.card_univ, hρ, nsmul_eq_mul]
    push_cast
    ring
  rw [hdot]
  apply Polynomial.funext
  intro z
  simp only [eval_comp, eval_mul, eval_pow, eval_sub, eval_add, eval_X, eval_C, eval_smul,
    smul_eq_mul]
  ring

/-- `charpoly (𝟏₆𝟏₆ᵀ ⊗ Q) = X²⁰ · charpoly (6 Q)`. -/
theorem charpoly_coreLeft_mul_coreRight (hρ : Fintype.card ρ = 4) (θ : ℝ) :
    (coreLeft ρ θ * coreRight ρ).charpoly =
      X ^ 20 * ((X - C (4 * θ : ℂ)) ^ 3 * (X - C (4 * θ + 80 * (1 - θ) : ℂ))) := by
  have h := Matrix.charpoly_mul_comm' (coreLeft ρ θ) (coreRight ρ)
  rw [charpoly_coreRight_mul_coreLeft hρ, hρ, Fintype.card_prod, Fintype.card_fin, hρ] at h
  have h24 : (X : ℂ[X]) ^ (6 * 4) = X ^ 4 * X ^ 20 := by ring
  rw [h24, mul_assoc] at h
  exact mul_left_cancel₀ (pow_ne_zero 4 Polynomial.X_ne_zero) h

/-- The characteristic polynomial of the core matrix `M_ϑ G₂₄`. -/
theorem charpoly_choiCore (hρ : Fintype.card ρ = 4) (θ : ℝ) :
    (choiCore ρ θ).charpoly =
      (X - C ((20 / 3) * (12 - 11 * θ) : ℂ)) * (X - C (20 * θ / 3 : ℂ)) ^ 3 *
        (X - C (8 * θ / 3 : ℂ)) ^ 20 := by
  rw [choiCore_eq_sub_scalar, Matrix.charpoly_sub_scalar, charpoly_coreLeft_mul_coreRight hρ]
  apply Polynomial.funext
  intro z
  simp only [eval_comp, eval_mul, eval_pow, eval_sub, eval_add, eval_X, eval_C]
  ring

/-- **`eq:matching-Choi-spectrum`.**  For any six-edge family with `∑ K_e = √2 I` and Gram
`Tr K_e^* K_f = 10/3` (`e = f`) / `2/3` (`e ≠ f`), and four orthogonal rank-one record projectors
`Q_a` summing to `I`, the characteristic polynomial of the Choi matrix of the resolved
instrument on `H_E ⊗ H_R` is
`X^{N − 24} (X − (20/3)(12 − 11ϑ)) (X − 20ϑ/3)³ (X − 8ϑ/3)²⁰` with `N = dim (H_E ⊗ H_R)²`:
the nonzero Choi spectrum is `{(20/3)(12−11ϑ)^{(1)}, (20ϑ/3)^{(3)}, (8ϑ/3)^{(20)}}`. -/
theorem choi_charpoly_kraus (hm : Fintype.card m = 20) (hρ : Fintype.card ρ = 4)
    (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ) (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1)
    (hKsum : ∑ e, K e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ))
    (hgram : ∀ e f, ((K e)ᴴ * K f).trace = if e = f then 10 / 3 else 2 / 3)
    (hQ : ∀ a, (Q a)ᴴ = Q a) (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0)
    (hQsum : ∑ a, Q a = 1) (hQtr : ∀ a, (Q a).trace = 1) :
    (choiMat (kraus K Q θ)).charpoly =
      X ^ (Fintype.card ((m × r) × (m × r)) - 24) *
        ((X - C ((20 / 3) * (12 - 11 * θ) : ℂ)) * (X - C (20 * θ / 3 : ℂ)) ^ 3 *
          (X - C (8 * θ / 3 : ℂ)) ^ 20) := by
  -- the record factor is nonempty
  have hρne : Nonempty ρ := Fintype.card_pos_iff.mp (by rw [hρ]; norm_num)
  have hrne : Nonempty r := by
    by_contra hr
    rw [not_nonempty_iff] at hr
    have := hQtr (Classical.arbitrary ρ)
    rw [Matrix.trace, Finset.univ_eq_empty, Finset.sum_empty] at this
    exact zero_ne_one this
  have hN : 24 ≤ Fintype.card ((m × r) × (m × r)) := by
    rw [Fintype.card_prod, Fintype.card_prod, hm]
    have : 1 ≤ Fintype.card r := Fintype.card_pos
    nlinarith
  -- Choi matrix `= B (C C^*) B^*`
  have hchoi : choiMat (kraus K Q θ) =
      choiVec (accepted K Q) *
        (coeffGram ρ θ * (choiVec (accepted K Q))ᴴ) := by
    rw [choiMat, choiVec_kraus K Q θ hKsum hQsum, Matrix.conjTranspose_mul,
      ← coeffMat_mul_conjTranspose θ hθ0 hθ1]
    simp only [Matrix.mul_assoc]
  have h := Matrix.charpoly_mul_comm' (choiVec (accepted K Q))
    (coeffGram ρ θ * (choiVec (accepted K Q))ᴴ)
  rw [← hchoi, Matrix.mul_assoc, conjTranspose_choiVec_mul,
    hsGram_accepted K Q hgram hQ hQQ hQtr, coeffGram_mul_gram24, charpoly_choiCore hρ,
    Fintype.card_prod, Fintype.card_fin, hρ] at h
  have hsplit : (X : ℂ[X]) ^ Fintype.card ((m × r) × (m × r)) =
      X ^ (6 * 4) * X ^ (Fintype.card ((m × r) × (m × r)) - 24) := by
    rw [← pow_add]
    congr 1
    omega
  rw [hsplit, mul_assoc] at h
  exact mul_left_cancel₀ (pow_ne_zero _ Polynomial.X_ne_zero) h

end ChoiSpectrum

/-! ### `prop:record-witness`, assembled -/

section Assembly

variable {r ρ : Type*} [Fintype r] [DecidableEq r] [Fintype ρ] [DecidableEq ρ]

/-- The commuting completions `K^c_e = I/√18 + (i/3) H^c_e` on `ℂ^{𝒮}`
(`eq:two-system-completions`). -/
noncomputable def Kc (e : Fin 6) : Matrix Three Three ℂ := completion (Hc e)

/-- The Clifford completions `K^q_e = I/√18 + (i/3) H^q_e` on `ℂ⁴ ⊗ ℂ⁵`
(`eq:two-system-completions`, concrete Helmert frame and Clifford family). -/
noncomputable def Kq (e : Fin 6) : Matrix (SMST4 × Fin 5) (SMST4 × Fin 5) ℂ :=
  completion (cliffordHq helmert cliffordSMST4 e)

theorem card_SMST4_prod : Fintype.card (SMST4 × Fin 5) = 20 := by
  rw [Fintype.card_prod, card_SMST4, Fintype.card_fin]

/-- The nonzero Choi spectrum of `eq:matching-Choi-spectrum`, as a polynomial:
`(X − (20/3)(12 − 11ϑ)) (X − 20ϑ/3)³ (X − 8ϑ/3)²⁰`. -/
noncomputable def choiSpectrumPoly (θ : ℝ) : ℂ[X] :=
  (X - C ((20 / 3) * (12 - 11 * θ) : ℂ)) * (X - C (20 * θ / 3 : ℂ)) ^ 3 *
    (X - C (8 * θ / 3 : ℂ)) ^ 20

/-- **`prop:record-witness`** (record-complete nonidentifiability witness).  For the two
concrete lists `K^c` (on `ℂ^{𝒮}`, `|𝒮| = 20`) and `K^q` (on `ℂ⁴ ⊗ ℂ⁵`) of
`eq:two-system-completions`, any four orthogonal rank-one record projectors `Q_a` on a record
factor `ℂ^r` summing to `I`, and any `0 ≤ ϑ ≤ 1`:

* both lists satisfy `eq:six-edge-normalization` (`∑ K_e^* K_e = I`, `∑ K_e = √2 I`, linear
  independence) and `eq:matching-record-data` (`K_e^* K_e = I/6`, `Tr K_e^* K_f = 10/3` or
  `2/3`);
* `C*(K^c) = ℂ^{20}` (the diagonal algebra) and `C*(K^q) = M₄(ℂ) ⊗ I₅`
  (`eq:inequivalent-system-algebras`);
* in both realizations a word with `n₀` no-response letters, `m` accepted letters and one common
  accepted record type `a` has effect `(1−ϑ)^{n₀} (ϑ/6)^m I₂₀ ⊗ Q_a`, and the effect is zero
  when the accepted record types disagree (`eq:record-word-effect`);
* both one-step Choi matrices have characteristic polynomial
  `X^{(20·dim H_R)² − 24} (X − (20/3)(12−11ϑ)) (X − 20ϑ/3)³ (X − 8ϑ/3)²⁰`, i.e. the same nonzero
  Choi spectrum `eq:matching-Choi-spectrum`. -/
theorem record_witness (hρ : Fintype.card ρ = 4) (Q : ρ → Matrix r r ℂ)
    (hQ : ∀ a, (Q a)ᴴ = Q a) (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0)
    (hQsum : ∑ a, Q a = 1) (hQtr : ∀ a, (Q a).trace = 1) (θ : ℝ) (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1) :
    -- `eq:six-edge-normalization`
    (∑ e, (Kc e)ᴴ * Kc e = 1 ∧ ∑ e, Kc e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix Three Three ℂ) ∧
      LinearIndependent ℂ Kc) ∧
    (∑ e, (Kq e)ᴴ * Kq e = 1 ∧
      ∑ e, Kq e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix (SMST4 × Fin 5) (SMST4 × Fin 5) ℂ) ∧
      LinearIndependent ℂ Kq) ∧
    -- `eq:matching-record-data`
    ((∀ e, (Kc e)ᴴ * Kc e = (1 / 6 : ℂ) • (1 : Matrix Three Three ℂ)) ∧
      ∀ e f, ((Kc e)ᴴ * Kc f).trace = if e = f then 10 / 3 else 2 / 3) ∧
    ((∀ e, (Kq e)ᴴ * Kq e = (1 / 6 : ℂ) • (1 : Matrix (SMST4 × Fin 5) (SMST4 × Fin 5) ℂ)) ∧
      ∀ e f, ((Kq e)ᴴ * Kq f).trace = if e = f then 10 / 3 else 2 / 3) ∧
    -- `eq:inequivalent-system-algebras`
    Algebra.adjoin ℂ (Set.range Kc) = diagonalSubalgebra ∧
    Algebra.adjoin ℂ (Set.range Kq) = (kronOneAlgHom SMST4).range ∧
    -- `eq:record-word-effect`
    (∀ w : List (Letter ρ),
      (∀ a ∈ recordTypes w, AllEq (recordTypes w) →
        effect (kraus Kc Q θ) w =
          (((1 - θ : ℝ) : ℂ) ^ noCount w * ((θ / 6 : ℝ) : ℂ) ^ accCount w) •
            ((1 : Matrix Three Three ℂ) ⊗ₖ Q a)) ∧
      (¬ AllEq (recordTypes w) → effect (kraus Kc Q θ) w = 0)) ∧
    (∀ w : List (Letter ρ),
      (∀ a ∈ recordTypes w, AllEq (recordTypes w) →
        effect (kraus Kq Q θ) w =
          (((1 - θ : ℝ) : ℂ) ^ noCount w * ((θ / 6 : ℝ) : ℂ) ^ accCount w) •
            ((1 : Matrix (SMST4 × Fin 5) (SMST4 × Fin 5) ℂ) ⊗ₖ Q a)) ∧
      (¬ AllEq (recordTypes w) → effect (kraus Kq Q θ) w = 0)) ∧
    -- `eq:matching-Choi-spectrum`
    (choiMat (kraus Kc Q θ)).charpoly =
      X ^ ((20 * Fintype.card r) ^ 2 - 24) * choiSpectrumPoly θ ∧
    (choiMat (kraus Kq Q θ)).charpoly =
      X ^ ((20 * Fintype.card r) ^ 2 - 24) * choiSpectrumPoly θ := by
  obtain ⟨hc1, hc2, hc3, hc4⟩ := commuting_record_data
  obtain ⟨hq1, hq2, hq3, hq4⟩ := clifford_record_data helmert cliffordSMST4 card_SMST4
  have hcN : Fintype.card ((Three × r) × (Three × r)) = (20 * Fintype.card r) ^ 2 := by
    rw [Fintype.card_prod, Fintype.card_prod, card_Three, sq]
  have hqN : Fintype.card (((SMST4 × Fin 5) × r) × ((SMST4 × Fin 5) × r)) =
      (20 * Fintype.card r) ^ 2 := by
    rw [Fintype.card_prod, Fintype.card_prod, card_SMST4_prod, sq]
  refine ⟨⟨hc1, hc2, linearIndependent_of_gram _ hc4⟩, ⟨hq1, hq2, linearIndependent_of_gram _ hq4⟩,
    ⟨hc3, hc4⟩, ⟨hq3, hq4⟩, ?_, ?_, ?_, ?_, ?_, ?_⟩
  · show Algebra.adjoin ℂ (Set.range fun e => completion (Hc e)) = diagonalSubalgebra
    rw [adjoin_range_completion, adjoin_Hc_eq_diagonal]
  · exact adjoin_completion_cliffordHq helmert
  · intro w
    exact ⟨(record_word_effect Kc Q θ hθ0 hθ1 hc3 hQ hQQ w).1,
      (record_word_effect Kc Q θ hθ0 hθ1 hc3 hQ hQQ w).2.1⟩
  · intro w
    exact ⟨(record_word_effect Kq Q θ hθ0 hθ1 hq3 hQ hQQ w).1,
      (record_word_effect Kq Q θ hθ0 hθ1 hq3 hQ hQQ w).2.1⟩
  · rw [← hcN]
    exact choi_charpoly_kraus card_Three hρ Kc Q θ hθ0 hθ1 hc2 hc4 hQ hQQ hQsum hQtr
  · rw [← hqN]
    exact choi_charpoly_kraus card_SMST4_prod hρ Kq Q θ hθ0 hθ1 hq2 hq4 hQ hQQ hQsum hQtr

end Assembly

end RecordWitness
end RenewalGeometry
