/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.StandardModel.RecordWitnessNormalization

/-!
# Record-complete nonidentifiability witness: the commuting family

Second layer of `prop:record-witness` / `thm:record-nonidentifiability` of the
spacetime–gauge duality paper: the **commuting** realization
`H^c_e |S⟩ = (2·1_{e∈S} − 1) |S⟩` on `ℂ^{𝒮}`, `𝒮` the twenty three-subsets of `{1,…,6}`.

* `Hc`: the six diagonal sign involutions; `Hc_conjTranspose`, `Hc_mul_self`,
  `Hc_sum`, `Hc_trace`, `Hc_gram`: Hermitian involutions with zero sum, zero trace and
  Gram `Tr(H_e H_f) = 20` (`e = f`) / `−4` (`e ≠ f`) — pair correlation `−1/5`;
* `commuting_record_data`: the commuting completions `K^c_e = I/√18 + (i/3) H^c_e`
  satisfy `eq:six-edge-normalization` (`∑ K^*K = I`, `∑ K = √2 I`) and
  `eq:matching-record-data` (`K^*K = I/6`, `Tr K_e^* K_f = 10/3 | 2/3`);
* `adjoin_Hc_eq_diagonal`: **`eq:inequivalent-system-algebras`, commuting half** — the
  unital algebra generated by the `H^c_e` is exactly the diagonal algebra `ℂ^{20}` (the
  twenty sign patterns separate the basis vectors: Lagrange interpolation
  `∏_e (1 + s_e(S) H_e)/2 = |S⟩⟨S|`), and this algebra is commutative.

Not formalised here: the Clifford realization `H^q_e` (generating `M₄(ℂ) ⊗ I₅`), the
word effects `eq:record-word-effect`, and the Choi spectrum `eq:matching-Choi-spectrum`.
-/

open Matrix

namespace RenewalGeometry
namespace RecordWitness

/-- The twenty three-subsets of `{1, …, 6}`. -/
abbrev Three := {S : Finset (Fin 6) // S.card = 3}

theorem card_Three : Fintype.card Three = 20 := by decide

/-- The sign `s_e(S) = 2·1_{e∈S} − 1`. -/
def sgnZ (e : Fin 6) (S : Three) : ℤ := if e ∈ S.1 then 1 else -1

set_option maxHeartbeats 4000000 in
theorem sgnZ_sum_e : ∀ S : Three, ∑ e, sgnZ e S = 0 := by decide

set_option maxHeartbeats 4000000 in
theorem sgnZ_sum_S : ∀ e : Fin 6, ∑ S : Three, sgnZ e S = 0 := by decide

set_option maxHeartbeats 4000000 in
theorem sgnZ_gram : ∀ e f : Fin 6,
    ∑ S : Three, sgnZ e S * sgnZ f S = if e = f then 20 else -4 := by decide

set_option maxHeartbeats 4000000 in
theorem sgnZ_lagrange : ∀ S S' : Three,
    ∏ e, (1 + sgnZ e S * sgnZ e S') = if S' = S then 64 else 0 := by decide

theorem sgnZ_mul_self (e : Fin 6) (S : Three) : sgnZ e S * sgnZ e S = 1 := by
  unfold sgnZ; split_ifs <;> norm_num

/-- The complex sign `s_e(S)`. -/
noncomputable def sgn (e : Fin 6) (S : Three) : ℂ := (sgnZ e S : ℂ)

/-- **The commuting family** `H^c_e = diag(s_e(S))`. -/
noncomputable def Hc (e : Fin 6) : Matrix Three Three ℂ := Matrix.diagonal (sgn e)

theorem Hc_conjTranspose (e : Fin 6) : (Hc e)ᴴ = Hc e := by
  rw [Hc, Matrix.diagonal_conjTranspose]
  congr 1
  funext S
  simp [sgn, Complex.star_def]

theorem Hc_mul_self (e : Fin 6) : Hc e * Hc e = 1 := by
  rw [Hc, Matrix.diagonal_mul_diagonal, ← Matrix.diagonal_one]
  congr 1
  funext S
  simp only [sgn, Pi.one_apply]
  exact_mod_cast sgnZ_mul_self e S

theorem Hc_sum : ∑ e, Hc e = 0 := by
  simp only [Hc]
  rw [← Matrix.diagonal_zero]
  have h := (map_sum (Matrix.diagonalAddMonoidHom Three ℂ) sgn Finset.univ).symm
  simp only [Matrix.diagonalAddMonoidHom_apply] at h
  rw [h]
  congr 1
  funext S
  simp only [Finset.sum_apply, sgn, Pi.zero_apply]
  exact_mod_cast sgnZ_sum_e S

theorem Hc_trace (e : Fin 6) : (Hc e).trace = 0 := by
  rw [Hc, Matrix.trace_diagonal]
  simp only [sgn]
  exact_mod_cast sgnZ_sum_S e

theorem Hc_gram (e f : Fin 6) : (Hc e * Hc f).trace = if e = f then 20 else -4 := by
  rw [Hc, Hc, Matrix.diagonal_mul_diagonal, Matrix.trace_diagonal]
  simp only [sgn]
  have := sgnZ_gram e f
  split_ifs with h
  · rw [if_pos h] at this; exact_mod_cast this
  · rw [if_neg h] at this; exact_mod_cast this

/-- **The commuting record data**: `eq:six-edge-normalization` (completeness and
coherent sum) and `eq:matching-record-data` for the commuting completions
`K^c_e = completion (Hc e)`. -/
theorem commuting_record_data :
    (∑ e, (completion (Hc e))ᴴ * completion (Hc e) = 1) ∧
    (∑ e, completion (Hc e) = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix Three Three ℂ)) ∧
    (∀ e, (completion (Hc e))ᴴ * completion (Hc e) = (1 / 6 : ℂ) • (1 : Matrix Three Three ℂ)) ∧
    (∀ e f, ((completion (Hc e))ᴴ * completion (Hc f)).trace =
      if e = f then 10 / 3 else 2 / 3) :=
  ⟨sum_conjTranspose_mul_completion Hc Hc_conjTranspose Hc_mul_self,
    sum_completion Hc Hc_sum,
    fun e => completion_conjTranspose_mul_self (Hc e) (Hc_conjTranspose e) (Hc_mul_self e),
    trace_conjTranspose_mul_completion_gram card_Three Hc Hc_conjTranspose Hc_trace Hc_gram⟩

/-! ### The generated algebra is the diagonal algebra `ℂ^{20}` -/

/-- The diagonal subalgebra of `M_{𝒮}(ℂ)`. -/
noncomputable def diagonalSubalgebra : Subalgebra ℂ (Matrix Three Three ℂ) :=
  (Matrix.diagonalAlgHom ℂ (n := Three) (α := ℂ)).range

theorem mem_diagonalSubalgebra {D : Matrix Three Three ℂ} :
    D ∈ diagonalSubalgebra ↔ ∃ d : Three → ℂ, D = Matrix.diagonal d := by
  simp only [diagonalSubalgebra, AlgHom.mem_range, Matrix.diagonalAlgHom_apply]
  exact ⟨fun ⟨d, h⟩ => ⟨d, h.symm⟩, fun ⟨d, h⟩ => ⟨d, h.symm⟩⟩

/-- The Lagrange factor `(1 + s_e(S) H_e)/2`, as a diagonal matrix. -/
noncomputable def lagrangeFactor (S : Three) (e : Fin 6) : Matrix Three Three ℂ :=
  Matrix.diagonal (fun S' => (2 : ℂ)⁻¹ * (1 + sgn e S * sgn e S'))

theorem lagrangeFactor_eq (S : Three) (e : Fin 6) :
    lagrangeFactor S e = (2 : ℂ)⁻¹ • ((1 : Matrix Three Three ℂ) + sgn e S • Hc e) := by
  ext i j
  by_cases hij : i = j
  · subst hij
    simp [lagrangeFactor, Hc, Matrix.diagonal_apply]
  · simp [lagrangeFactor, Hc, Matrix.diagonal_apply, hij]

theorem lagrangeFactor_mem (S : Three) (e : Fin 6) :
    lagrangeFactor S e ∈ Algebra.adjoin ℂ (Set.range Hc) := by
  rw [lagrangeFactor_eq]
  refine Subalgebra.smul_mem _ (Subalgebra.add_mem _ (Subalgebra.one_mem _)
    (Subalgebra.smul_mem _ ?_ _)) _
  exact Algebra.subset_adjoin ⟨e, rfl⟩

/-- The Lagrange projector `∏_e (1 + s_e(S) H_e)/2 = |S⟩⟨S|`. -/
theorem lagrange_projector (S : Three) :
    lagrangeFactor S 0 * lagrangeFactor S 1 * lagrangeFactor S 2 * lagrangeFactor S 3 *
      lagrangeFactor S 4 * lagrangeFactor S 5 = Matrix.diagonal (Pi.single S 1) := by
  simp only [lagrangeFactor, Matrix.diagonal_mul_diagonal]
  congr 1
  funext S'
  simp only [Pi.single_apply, sgn]
  have h := sgnZ_lagrange S S'
  rw [Fin.prod_univ_six] at h
  have h' : (((1 + sgnZ 0 S * sgnZ 0 S') * (1 + sgnZ 1 S * sgnZ 1 S') *
      (1 + sgnZ 2 S * sgnZ 2 S') * (1 + sgnZ 3 S * sgnZ 3 S') * (1 + sgnZ 4 S * sgnZ 4 S') *
      (1 + sgnZ 5 S * sgnZ 5 S') : ℤ) : ℂ) = if S' = S then 64 else 0 := by
    rw [h]; split_ifs <;> norm_num
  push_cast at h'
  split_ifs at h' ⊢ with hS
  · linear_combination (1 / 64 : ℂ) * h'
  · linear_combination (1 / 64 : ℂ) * h'

theorem single_mem_adjoin (S : Three) :
    Matrix.diagonal (Pi.single S 1) ∈ Algebra.adjoin ℂ (Set.range Hc) := by
  rw [← lagrange_projector S]
  have h := lagrangeFactor_mem S
  exact Subalgebra.mul_mem _ (Subalgebra.mul_mem _ (Subalgebra.mul_mem _ (Subalgebra.mul_mem _
    (Subalgebra.mul_mem _ (h 0) (h 1)) (h 2)) (h 3)) (h 4)) (h 5)

/-- **`eq:inequivalent-system-algebras`, commuting half**: the unital algebra generated
by the commuting family is exactly the diagonal algebra `ℂ^{20}`. -/
theorem adjoin_Hc_eq_diagonal : Algebra.adjoin ℂ (Set.range Hc) = diagonalSubalgebra := by
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨e, rfl⟩
    exact mem_diagonalSubalgebra.mpr ⟨sgn e, rfl⟩
  · intro D hD
    obtain ⟨d, rfl⟩ := mem_diagonalSubalgebra.mp hD
    have hd : Matrix.diagonal d = ∑ S, d S • Matrix.diagonal (Pi.single S 1) := by
      ext i j
      simp only [Matrix.sum_apply, Matrix.smul_apply, Matrix.diagonal_apply, Pi.single_apply,
        smul_eq_mul]
      by_cases hij : i = j
      · subst hij; simp
      · simp [hij]
    rw [hd]
    exact Subalgebra.sum_mem _ fun S _ => Subalgebra.smul_mem _ (single_mem_adjoin S) _

/-- The commuting system algebra is commutative. -/
theorem adjoin_Hc_commutative (x y : Matrix Three Three ℂ)
    (hx : x ∈ Algebra.adjoin ℂ (Set.range Hc)) (hy : y ∈ Algebra.adjoin ℂ (Set.range Hc)) :
    x * y = y * x := by
  rw [adjoin_Hc_eq_diagonal] at hx hy
  obtain ⟨a, rfl⟩ := mem_diagonalSubalgebra.mp hx
  obtain ⟨b, rfl⟩ := mem_diagonalSubalgebra.mp hy
  rw [Matrix.diagonal_mul_diagonal, Matrix.diagonal_mul_diagonal]
  congr 1
  funext S
  ring

/-- The commuting system algebra has dimension `20`. -/
theorem finrank_adjoin_Hc : Module.finrank ℂ (Algebra.adjoin ℂ (Set.range Hc)) = 20 := by
  rw [adjoin_Hc_eq_diagonal]
  have hinj : Function.Injective (Matrix.diagonalAlgHom ℂ (n := Three) (α := ℂ)) :=
    fun a b h => Matrix.diagonal_injective h
  have := LinearEquiv.finrank_eq
    (AlgEquiv.ofInjective (Matrix.diagonalAlgHom ℂ (n := Three) (α := ℂ))
      hinj).toLinearEquiv
  rw [diagonalSubalgebra, ← this, Module.finrank_fintype_fun_eq_card, card_Three]

end RecordWitness
end RenewalGeometry
