/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.StandardModel.RecordWitnessConcrete

/-!
# Classical record data do not determine the system algebra (`thm:record-nonidentifiability`)

Final layer of `thm:record-nonidentifiability` / `prop:record-witness` of the spacetime–gauge
duality paper.

* `kraus`: the resolved instrument `L_0 = √(1−θ) I`, `L_{e,a} = √θ K_e ⊗ Q_a` on `H_E ⊗ H_R`
  (`app:source-identifiability`); `wordOp`, `effect`: the word operator `L_w = L_{ℓ_k} ⋯ L_{ℓ_1}`
  and the effect `L_w^* L_w` of a classical word;
* `effect_kraus`: for any family with `K_e^* K_e = I/6` and orthogonal record projectors, the
  effect of a word is `(1−θ)^{n₀} (θ/6)^m · I ⊗ R(w)` with `R(w)` the record projector of the
  word; `record_word_effect` is **`eq:record-word-effect`** (`I ⊗ Q_a` for one common accepted
  record type `a`, zero if the accepted types disagree), and `effect_kraus_eq` says the
  complete classical record channel at every word length is the same for any two families
  with `K^*K = I/6`;
* `sum_kraus_conjTranspose_mul`: the instrument is normalized;
* `choiMat`, `hsGram`, `choiMat_charpoly_eq_of_hsGram_eq`: the Choi matrix of an instrument is
  `B B^*` for the matrix `B` of Choi vectors, so its characteristic polynomial — hence its
  spectrum with multiplicities — is determined by the Hilbert–Schmidt Gram `B^*B` of the Kraus
  operators (`Matrix.charpoly_mul_comm'`); `hsGram_kraus_eq`: the Gram of the resolved
  instrument depends only on `Tr K_e` and `Tr K_e^* K_f`;
* `record_nonidentifiability`: **`thm:record-nonidentifiability`**.  On any `20`-dimensional
  carrier and for any record factor with orthogonal projectors `Q_a` summing to `I`, there are
  two six-edge families `K^c`, `K^q` satisfying `eq:six-edge-normalization` (completeness,
  coherent sum, linear independence) whose resolved instruments are normalized, have the same
  one-step effects, the same effect for every classical word, the same one-letter
  Hilbert–Schmidt Gram `Tr K_e^* K_f`, and Choi matrices with the same characteristic
  polynomial (the same spectrum with multiplicities), while the generated unital algebras are
  not isomorphic (one commutative, the other not) and neither are their commutants.

Rendering notes.  The paper's `C*(K_e)` is the unital `*`-algebra generated by the `K_e`; since
`K_e = I/√18 + (i/3) H_e` with `H_e` Hermitian, the generating set `{K_e, K_e^*}` spans the same
algebra as `{H_e}`, so `C*(K_e) = Algebra.adjoin ℂ (range K)`; the commutant is
`Subalgebra.centralizer`.  Nonisomorphism is proved through the commutative / noncommutative
contrast (`ℂ^{20}` versus an algebra containing `Γ_0 ⊗ I₅, Γ_1 ⊗ I₅`; diagonal commutant versus one
containing `I ⊗ M₅(ℂ)`); the exact identifications `C*(K^c) = ℂ^{20}` (proved in
`RecordWitnessCommutingFamily`) and `C*(K^q) = M₄(ℂ) ⊗ I₅` (not formalised) are not needed for
the countertheorem.  The explicit eigenvalue list `eq:matching-Choi-spectrum` is not computed;
the countertheorem's "same nonzero Choi spectrum" is covered by the equality of the two
characteristic polynomials.
-/

open Matrix Kronecker Polynomial

namespace RenewalGeometry
namespace RecordWitness

open FiveKraus

/-! ### Words, word operators and effects -/

section Words

variable {ι n : Type*} [Fintype n] [DecidableEq n]

/-- The word operator `L_w = L_{ℓ_k} ⋯ L_{ℓ_1}` of the word `w = [ℓ_1, …, ℓ_k]`
(the first letter acts first). -/
def wordOp (L : ι → Matrix n n ℂ) : List ι → Matrix n n ℂ
  | [] => 1
  | ℓ :: w => wordOp L w * L ℓ

/-- The effect `L_w^* L_w` of a classical word. -/
def effect (L : ι → Matrix n n ℂ) (w : List ι) : Matrix n n ℂ :=
  (wordOp L w)ᴴ * wordOp L w

theorem effect_nil (L : ι → Matrix n n ℂ) : effect L [] = 1 := by
  simp [effect, wordOp]

theorem effect_cons (L : ι → Matrix n n ℂ) (ℓ : ι) (w : List ι) :
    effect L (ℓ :: w) = (L ℓ)ᴴ * effect L w * L ℓ := by
  simp only [effect, wordOp, Matrix.conjTranspose_mul, Matrix.mul_assoc]

/-- The one-step effect is the effect of the one-letter word. -/
theorem effect_singleton (L : ι → Matrix n n ℂ) (ℓ : ι) : effect L [ℓ] = (L ℓ)ᴴ * L ℓ := by
  simp [effect, wordOp]

end Words

/-! ### The resolved instrument -/

section Instrument

variable {m r ρ : Type*} [Fintype m] [DecidableEq m] [Fintype r] [DecidableEq r]
  [Fintype ρ] [DecidableEq ρ]

/-- A letter of the resolved classical alphabet: `none` is the no-response letter,
`some (e, a)` is edge `e` accepted with record type `a`. -/
abbrev Letter (ρ : Type*) := Option (Fin 6 × ρ)

/-- The resolved instrument `L_0 = √(1−θ) I`, `L_{e,a} = √θ K_e ⊗ Q_a`. -/
noncomputable def kraus (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ) :
    Letter ρ → Matrix (m × r) (m × r) ℂ
  | none => ((Real.sqrt (1 - θ) : ℝ) : ℂ) • (1 : Matrix (m × r) (m × r) ℂ)
  | some (e, a) => ((Real.sqrt θ : ℝ) : ℂ) • (K e ⊗ₖ Q a)

/-- Number of no-response letters. -/
def noCount : List (Letter ρ) → ℕ
  | [] => 0
  | none :: w => noCount w + 1
  | some _ :: w => noCount w

/-- Number of accepted letters. -/
def accCount : List (Letter ρ) → ℕ
  | [] => 0
  | none :: w => accCount w
  | some _ :: w => accCount w + 1

/-- The list of accepted record types of a word. -/
def recordTypes : List (Letter ρ) → List ρ
  | [] => []
  | none :: w => recordTypes w
  | some (_, a) :: w => a :: recordTypes w

/-- The record projector `Q_{a_1} ⋯ Q_{a_k} ⋯ Q_{a_1}` of a list of record types. -/
def recProj (Q : ρ → Matrix r r ℂ) : List ρ → Matrix r r ℂ
  | [] => 1
  | a :: l => Q a * recProj Q l * Q a

theorem sum_kronecker_sum {ι κ : Type*} [Fintype ι] [Fintype κ] (A : ι → Matrix m m ℂ)
    (B : κ → Matrix r r ℂ) :
    (∑ i, A i) ⊗ₖ (∑ k, B k) = ∑ i, ∑ k, A i ⊗ₖ B k := by
  ext ⟨x, y⟩ ⟨x', y'⟩
  simp [Matrix.sum_apply, Matrix.kroneckerMap_apply, Finset.sum_mul_sum]

theorem real_smul_mul_real_smul (a b : ℝ) (X Y : Matrix (m × r) (m × r) ℂ) :
    ((a : ℂ) • X) * ((b : ℂ) • Y) = ((a * b : ℝ) : ℂ) • (X * Y) := by
  rw [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
  push_cast
  rfl

/-- **The effect of a classical word** for any family with `K_e^* K_e = I/6`:
`L_w^* L_w = (1−θ)^{n₀} (θ/6)^m · I ⊗ R(w)`. -/
theorem effect_kraus (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1)
    (hK : ∀ e, (K e)ᴴ * K e = (1 / 6 : ℂ) • (1 : Matrix m m ℂ))
    (hQ : ∀ a, (Q a)ᴴ = Q a) (w : List (Letter ρ)) :
    effect (kraus K Q θ) w =
      (((1 - θ : ℝ) : ℂ) ^ noCount w * ((θ / 6 : ℝ) : ℂ) ^ accCount w) •
        ((1 : Matrix m m ℂ) ⊗ₖ recProj Q (recordTypes w)) := by
  induction w with
  | nil => simp [effect_nil, noCount, accCount, recordTypes, recProj, Matrix.one_kronecker_one]
  | cons ℓ w ih =>
    rw [effect_cons, ih]
    rcases ℓ with _ | ⟨e, a⟩
    · simp only [kraus, noCount, accCount, recordTypes]
      rw [conjTranspose_real_smul, Matrix.conjTranspose_one, Matrix.smul_mul, Matrix.one_mul,
        Matrix.mul_smul, Matrix.mul_one, smul_smul, smul_smul]
      congr 1
      have h : ((Real.sqrt (1 - θ) : ℝ) : ℂ) * ((Real.sqrt (1 - θ) : ℝ) : ℂ) = ((1 - θ : ℝ) : ℂ) := by
        rw [← Complex.ofReal_mul, Real.mul_self_sqrt (sub_nonneg.mpr hθ1)]
      rw [pow_succ]
      linear_combination (((1 - θ : ℝ) : ℂ) ^ noCount w * ((θ / 6 : ℝ) : ℂ) ^ accCount w) * h
    · simp only [kraus, noCount, accCount, recordTypes, recProj]
      rw [conjTranspose_real_smul, Matrix.conjTranspose_kronecker, hQ]
      simp only [Matrix.smul_mul, Matrix.mul_smul, smul_smul]
      rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul, Matrix.mul_one, hK,
        Matrix.smul_kronecker, smul_smul]
      congr 1
      have h : ((Real.sqrt θ : ℝ) : ℂ) * ((Real.sqrt θ : ℝ) : ℂ) = (θ : ℂ) := by
        rw [← Complex.ofReal_mul, Real.mul_self_sqrt hθ0]
      rw [pow_succ]
      push_cast
      linear_combination ((1 - (θ : ℂ)) ^ noCount w * ((θ : ℂ) / 6) ^ accCount w / 6) * h

/-- The complete classical record channel at every word length is the same for any two
families with `K_e^* K_e = I/6` (the word effects do not see the `K_e` beyond this). -/
theorem effect_kraus_eq (K K' : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1)
    (hK : ∀ e, (K e)ᴴ * K e = (1 / 6 : ℂ) • (1 : Matrix m m ℂ))
    (hK' : ∀ e, (K' e)ᴴ * K' e = (1 / 6 : ℂ) • (1 : Matrix m m ℂ))
    (hQ : ∀ a, (Q a)ᴴ = Q a) (w : List (Letter ρ)) :
    effect (kraus K Q θ) w = effect (kraus K' Q θ) w := by
  rw [effect_kraus K Q θ hθ0 hθ1 hK hQ w, effect_kraus K' Q θ hθ0 hθ1 hK' hQ w]

/-! #### The record projector of a word -/

/-- All entries of a list are equal. -/
def AllEq (l : List ρ) : Prop := ∀ a ∈ l, ∀ b ∈ l, a = b

theorem allEq_of_cons {c : ρ} {l : List ρ} (h : AllEq (c :: l)) : AllEq l :=
  fun a ha b hb => h a (List.mem_cons_of_mem _ ha) b (List.mem_cons_of_mem _ hb)

theorem recProj_of_allEq (Q : ρ → Matrix r r ℂ)
    (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0) :
    ∀ (l : List ρ), AllEq l → ∀ a ∈ l, recProj Q l = Q a := by
  intro l
  induction l with
  | nil => intro _ a ha; simp at ha
  | cons c l ih =>
    intro h a ha
    have hac : a = c := h a ha c (List.mem_cons_self ..)
    subst hac
    simp only [recProj]
    rcases l with _ | ⟨c', l'⟩
    · simp only [recProj, Matrix.mul_one, hQQ, if_true]
    · rw [ih (allEq_of_cons h) c' (List.mem_cons_self ..),
        h c' (List.mem_cons_of_mem _ (List.mem_cons_self ..)) a (List.mem_cons_self ..),
        hQQ, if_pos rfl, hQQ, if_pos rfl]

theorem recProj_of_not_allEq (Q : ρ → Matrix r r ℂ)
    (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0) :
    ∀ (l : List ρ), ¬ AllEq l → recProj Q l = 0 := by
  intro l
  induction l with
  | nil => intro h; exact absurd (fun a ha => by simp at ha) h
  | cons c l ih =>
    intro h
    simp only [recProj]
    by_cases hl : AllEq l
    · rcases l with _ | ⟨c', l'⟩
      · exact absurd (fun a ha b hb => by
          simp only [List.mem_cons, List.not_mem_nil, or_false] at ha hb
          rw [ha, hb]) h
      · rw [recProj_of_allEq Q hQQ _ hl c' (List.mem_cons_self ..)]
        have hcc : c ≠ c' := by
          intro hcc
          apply h
          intro a ha b hb
          have key : ∀ x ∈ c :: c' :: l', x = c := by
            intro x hx
            rcases List.mem_cons.mp hx with hx | hx
            · exact hx
            · rw [hl x hx c' (List.mem_cons_self ..), hcc]
          rw [key a ha, key b hb]
        rw [hQQ, if_neg hcc, Matrix.zero_mul]
    · rw [ih hl, Matrix.mul_zero, Matrix.zero_mul]

/-- **`eq:record-word-effect`.**  A word with `n₀` no-response letters, `m ≥ 1` accepted
letters and one common accepted record type `a` has effect `(1−θ)^{n₀} (θ/6)^m · I ⊗ Q_a`; if
the accepted record types disagree the effect is zero; with no accepted letter the effect is
`(1−θ)^{n₀} I`. -/
theorem record_word_effect (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1)
    (hK : ∀ e, (K e)ᴴ * K e = (1 / 6 : ℂ) • (1 : Matrix m m ℂ))
    (hQ : ∀ a, (Q a)ᴴ = Q a) (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0)
    (w : List (Letter ρ)) :
    (∀ a ∈ recordTypes w, AllEq (recordTypes w) →
      effect (kraus K Q θ) w =
        (((1 - θ : ℝ) : ℂ) ^ noCount w * ((θ / 6 : ℝ) : ℂ) ^ accCount w) •
          ((1 : Matrix m m ℂ) ⊗ₖ Q a)) ∧
    (¬ AllEq (recordTypes w) → effect (kraus K Q θ) w = 0) ∧
    (recordTypes w = [] →
      effect (kraus K Q θ) w = (((1 - θ : ℝ) : ℂ) ^ noCount w) • (1 : Matrix (m × r) (m × r) ℂ)) := by
  refine ⟨fun a ha hall => ?_, fun hne => ?_, fun hnil => ?_⟩
  · rw [effect_kraus K Q θ hθ0 hθ1 hK hQ w, recProj_of_allEq Q hQQ _ hall a ha]
  · rw [effect_kraus K Q θ hθ0 hθ1 hK hQ w, recProj_of_not_allEq Q hQQ _ hne,
      Matrix.kronecker_zero, smul_zero]
  · have hm : accCount w = 0 := by
      clear hK hQ hQQ
      induction w with
      | nil => rfl
      | cons ℓ w ih =>
        rcases ℓ with _ | ⟨e, a⟩
        · exact ih hnil
        · simp [recordTypes] at hnil
    rw [effect_kraus K Q θ hθ0 hθ1 hK hQ w, hnil, hm, recProj, pow_zero, mul_one,
      Matrix.one_kronecker_one]

/-! #### Normalization -/

/-- The resolved instrument is normalized: `∑_ℓ L_ℓ^* L_ℓ = I`. -/
theorem sum_kraus_conjTranspose_mul (K : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1) (hKsum : ∑ e, (K e)ᴴ * K e = 1)
    (hQ : ∀ a, (Q a)ᴴ = Q a) (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0)
    (hQsum : ∑ a, Q a = 1) :
    ∑ ℓ, (kraus K Q θ ℓ)ᴴ * kraus K Q θ ℓ = 1 := by
  rw [Fintype.sum_option, Fintype.sum_prod_type]
  have h0 : (kraus K Q θ none)ᴴ * kraus K Q θ none = ((1 - θ : ℝ) : ℂ) • 1 := by
    simp only [kraus]
    rw [conjTranspose_real_smul, Matrix.conjTranspose_one, real_smul_mul_real_smul,
      Matrix.one_mul, Real.mul_self_sqrt (sub_nonneg.mpr hθ1)]
  have h1 : ∀ e a, (kraus K Q θ (some (e, a)))ᴴ * kraus K Q θ (some (e, a)) =
      (θ : ℂ) • (((K e)ᴴ * K e) ⊗ₖ Q a) := by
    intro e a
    simp only [kraus]
    rw [conjTranspose_real_smul, Matrix.conjTranspose_kronecker, hQ, real_smul_mul_real_smul,
      ← Matrix.mul_kronecker_mul, hQQ, if_pos rfl, Real.mul_self_sqrt hθ0]
  simp_rw [h1]
  rw [h0]
  simp_rw [← Finset.smul_sum]
  rw [← sum_kronecker_sum, hKsum, hQsum, Matrix.one_kronecker_one, ← add_smul]
  push_cast
  rw [sub_add_cancel, one_smul]

end Instrument

/-! ### The Choi matrix and its characteristic polynomial -/

section Choi

variable {ι n : Type*} [Fintype ι] [DecidableEq ι] [Fintype n] [DecidableEq n]

/-- The matrix whose columns are the Choi vectors `|L_ℓ⟩⟩` of the Kraus operators. -/
def choiVec (L : ι → Matrix n n ℂ) : Matrix (n × n) ι ℂ :=
  Matrix.of fun p ℓ => L ℓ p.1 p.2

/-- The Choi matrix `J = ∑_ℓ |L_ℓ⟩⟩⟨⟨L_ℓ| = B B^*` of the channel with Kraus operators `L_ℓ`. -/
def choiMat (L : ι → Matrix n n ℂ) : Matrix (n × n) (n × n) ℂ :=
  choiVec L * (choiVec L)ᴴ

/-- The Hilbert–Schmidt Gram matrix `Tr(L_j^* L_k)` of the Kraus operators. -/
def hsGram (L : ι → Matrix n n ℂ) : Matrix ι ι ℂ :=
  Matrix.of fun j k => ((L j)ᴴ * L k).trace

theorem conjTranspose_choiVec_mul (L : ι → Matrix n n ℂ) :
    (choiVec L)ᴴ * choiVec L = hsGram L := by
  ext j k
  simp only [choiVec, hsGram, Matrix.mul_apply, Matrix.conjTranspose_apply, Matrix.of_apply,
    Matrix.trace, Matrix.diag, Fintype.sum_prod_type]
  exact Finset.sum_comm

/-- **The nonzero Choi spectrum is a Gram invariant**: the characteristic polynomial of the Choi
matrix is determined by the Hilbert–Schmidt Gram of the Kraus operators. -/
theorem choiMat_charpoly_eq_of_hsGram_eq (L L' : ι → Matrix n n ℂ) (h : hsGram L = hsGram L') :
    (choiMat L).charpoly = (choiMat L').charpoly := by
  have h1 := Matrix.charpoly_mul_comm' (choiVec L) (choiVec L)ᴴ
  have h2 := Matrix.charpoly_mul_comm' (choiVec L') (choiVec L')ᴴ
  rw [conjTranspose_choiVec_mul] at h1 h2
  unfold choiMat
  apply mul_left_cancel₀ (pow_ne_zero (Fintype.card ι) (Polynomial.X_ne_zero (R := ℂ)))
  rw [h1, h2, h]

end Choi

section InstrumentGram

variable {m r ρ : Type*} [Fintype m] [DecidableEq m] [Fintype r] [DecidableEq r]
  [Fintype ρ] [DecidableEq ρ]

/-- The Hilbert–Schmidt Gram of the resolved instrument depends only on `Tr K_e` and
`Tr K_e^* K_f`. -/
theorem hsGram_kraus_eq (K K' : Fin 6 → Matrix m m ℂ) (Q : ρ → Matrix r r ℂ) (θ : ℝ)
    (htr : ∀ e, (K e).trace = (K' e).trace)
    (hgram : ∀ e f, ((K e)ᴴ * K f).trace = ((K' e)ᴴ * K' f).trace) :
    hsGram (kraus K Q θ) = hsGram (kraus K' Q θ) := by
  ext j k
  simp only [hsGram, Matrix.of_apply]
  rcases j with _ | ⟨e, a⟩ <;> rcases k with _ | ⟨f, b⟩ <;>
    simp only [kraus, Matrix.conjTranspose_smul, Matrix.smul_mul, Matrix.mul_smul,
      Matrix.trace_smul, Matrix.one_mul, Matrix.mul_one, Matrix.conjTranspose_one,
      Matrix.conjTranspose_kronecker, ← Matrix.mul_kronecker_mul, Matrix.trace_kronecker,
      Matrix.trace_conjTranspose, htr, hgram]

end InstrumentGram

/-! ### Transport along a reindexing -/

section Transport

variable {m n : Type*} [Fintype m] [DecidableEq m] [Fintype n] [DecidableEq n]

theorem reindexAlgEquiv_conjTranspose (σ : m ≃ n) (X : Matrix m m ℂ) :
    (Matrix.reindexAlgEquiv ℂ ℂ σ X)ᴴ = Matrix.reindexAlgEquiv ℂ ℂ σ Xᴴ := by
  simp [Matrix.coe_reindexAlgEquiv]

theorem trace_reindexAlgEquiv (σ : m ≃ n) (X : Matrix m m ℂ) :
    (Matrix.reindexAlgEquiv ℂ ℂ σ X).trace = X.trace := by
  simp only [Matrix.coe_reindexAlgEquiv, Matrix.reindex_apply, Matrix.trace, Matrix.diag,
    Matrix.submatrix_apply]
  exact Fintype.sum_equiv σ.symm _ _ (fun _ => rfl)

theorem mem_adjoin_range_map {ι : Type*} (σ : m ≃ n) (H : ι → Matrix m m ℂ) {x : Matrix m m ℂ}
    (hx : x ∈ Algebra.adjoin ℂ (Set.range H)) :
    Matrix.reindexAlgEquiv ℂ ℂ σ x ∈
      Algebra.adjoin ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)) := by
  have h := AlgHom.map_adjoin (Matrix.reindexAlgEquiv ℂ ℂ σ).toAlgHom (Set.range H)
  have hx' : Matrix.reindexAlgEquiv ℂ ℂ σ x ∈
      (Algebra.adjoin ℂ (Set.range H)).map (Matrix.reindexAlgEquiv ℂ ℂ σ).toAlgHom :=
    Subalgebra.mem_map.mpr ⟨x, hx, rfl⟩
  rw [h] at hx'
  convert hx' using 3
  rw [Set.range_comp']
  rfl

theorem mem_centralizer_range_map {ι : Type*} (σ : m ≃ n) (H : ι → Matrix m m ℂ)
    {x : Matrix m m ℂ} (hx : x ∈ Subalgebra.centralizer ℂ (Set.range H)) :
    Matrix.reindexAlgEquiv ℂ ℂ σ x ∈
      Subalgebra.centralizer ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)) := by
  rw [Subalgebra.mem_centralizer_iff] at hx ⊢
  rintro _ ⟨e, rfl⟩
  rw [← map_mul, ← map_mul, hx (H e) ⟨e, rfl⟩]

/-- Commutativity of the generated algebra pulls back along a reindexing. -/
theorem adjoin_comm_of_map {ι : Type*} (σ : m ≃ n) (H : ι → Matrix m m ℂ)
    (h : ∀ x ∈ Algebra.adjoin ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)),
      ∀ y ∈ Algebra.adjoin ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)),
        x * y = y * x) :
    ∀ x ∈ Algebra.adjoin ℂ (Set.range H), ∀ y ∈ Algebra.adjoin ℂ (Set.range H), x * y = y * x := by
  intro x hx y hy
  have := h _ (mem_adjoin_range_map σ H hx) _ (mem_adjoin_range_map σ H hy)
  rw [← map_mul, ← map_mul] at this
  exact (Matrix.reindexAlgEquiv ℂ ℂ σ).injective this

/-- Commutativity of the commutant pulls back along a reindexing. -/
theorem centralizer_comm_of_map {ι : Type*} (σ : m ≃ n) (H : ι → Matrix m m ℂ)
    (h : ∀ x ∈ Subalgebra.centralizer ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)),
      ∀ y ∈ Subalgebra.centralizer ℂ (Set.range fun e => Matrix.reindexAlgEquiv ℂ ℂ σ (H e)),
        x * y = y * x) :
    ∀ x ∈ Subalgebra.centralizer ℂ (Set.range H),
      ∀ y ∈ Subalgebra.centralizer ℂ (Set.range H), x * y = y * x := by
  intro x hx y hy
  have := h _ (mem_centralizer_range_map σ H hx) _ (mem_centralizer_range_map σ H hy)
  rw [← map_mul, ← map_mul] at this
  exact (Matrix.reindexAlgEquiv ℂ ℂ σ).injective this

end Transport

/-! ### Completions generate the same algebra as the involutions -/

section Completion

variable {m : Type*} [Fintype m] [DecidableEq m]

theorem completion_trace (Hm : Matrix m m ℂ) (htr : Hm.trace = 0) :
    (completion Hm).trace = (Fintype.card m : ℂ) * ((1 / Real.sqrt 18 : ℝ) : ℂ) := by
  simp [completion, Matrix.trace_add, Matrix.trace_smul, Matrix.trace_one, htr, mul_comm]

theorem I_div_three_ne_zero : (Complex.I / 3 : ℂ) ≠ 0 := by
  exact div_ne_zero Complex.I_ne_zero (by norm_num)

theorem adjoin_range_completion (Hm : Fin 6 → Matrix m m ℂ) :
    Algebra.adjoin ℂ (Set.range fun e => completion (Hm e)) = Algebra.adjoin ℂ (Set.range Hm) := by
  apply le_antisymm
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨e, rfl⟩
    unfold completion
    exact Subalgebra.add_mem _ (Subalgebra.smul_mem _ (Subalgebra.one_mem _) _)
      (Subalgebra.smul_mem _ (Algebra.subset_adjoin (Set.mem_range_self e)) _)
  · rw [Algebra.adjoin_le_iff]
    rintro _ ⟨e, rfl⟩
    have h : Hm e = (Complex.I / 3)⁻¹ • (completion (Hm e) -
        ((1 / Real.sqrt 18 : ℝ) : ℂ) • (1 : Matrix m m ℂ)) := by
      unfold completion
      rw [add_sub_cancel_left, smul_smul, inv_mul_cancel₀ I_div_three_ne_zero, one_smul]
    rw [h]
    exact Subalgebra.smul_mem _ (Subalgebra.sub_mem _
      (Algebra.subset_adjoin (Set.mem_range_self e))
      (Subalgebra.smul_mem _ (Subalgebra.one_mem _) _)) _

theorem centralizer_range_completion (Hm : Fin 6 → Matrix m m ℂ) :
    Subalgebra.centralizer ℂ (Set.range fun e => completion (Hm e)) =
      Subalgebra.centralizer ℂ (Set.range Hm) := by
  ext x
  simp only [Subalgebra.mem_centralizer_iff, Set.forall_mem_range]
  refine forall_congr' fun e => ?_
  unfold completion
  constructor
  · intro h
    have h' : (Complex.I / 3) • (Hm e * x) = (Complex.I / 3) • (x * Hm e) := by
      have := h
      simp only [Matrix.add_mul, Matrix.mul_add, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
        Matrix.mul_one] at this
      exact add_left_cancel this
    exact smul_right_injective _ I_div_three_ne_zero h'
  · intro h
    simp only [Matrix.add_mul, Matrix.mul_add, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
      Matrix.mul_one, h]

/-- Six matrices with Gram `Tr K_e^* K_f = 10/3` (`e = f`) / `2/3` (`e ≠ f`) are linearly
independent (the Gram matrix `(8/3) I + (2/3) 𝟏𝟏ᵀ` is nonsingular). -/
theorem linearIndependent_of_gram (K : Fin 6 → Matrix m m ℂ)
    (hgram : ∀ e f, ((K e)ᴴ * K f).trace = if e = f then 10 / 3 else 2 / 3) :
    LinearIndependent ℂ K := by
  rw [Fintype.linearIndependent_iff]
  intro g hg
  have hrow : ∀ f, (8 / 3 : ℂ) * g f + (2 / 3) * ∑ e, g e = 0 := by
    intro f
    have h := congrArg (fun X => ((K f)ᴴ * X).trace) hg
    simp only [Matrix.mul_sum, Matrix.mul_smul, Matrix.trace_sum, Matrix.trace_smul, Matrix.mul_zero,
      Matrix.trace_zero, smul_eq_mul, hgram] at h
    have h2 : ∑ x, g x * (if f = x then (10 / 3 : ℂ) else 2 / 3) =
        (8 / 3 : ℂ) * g f + (2 / 3) * ∑ e, g e := by
      have : ∀ x, g x * (if f = x then (10 / 3 : ℂ) else 2 / 3) =
          (2 / 3) * g x + (if f = x then (8 / 3 : ℂ) * g x else 0) := by
        intro x; split_ifs <;> ring
      simp_rw [this]
      rw [Finset.sum_add_distrib, Finset.sum_ite_eq, if_pos (Finset.mem_univ f), ← Finset.mul_sum]
      ring
    rw [h2] at h
    exact h
  have hsum : ∑ e, g e = 0 := by
    have h := Finset.sum_congr rfl fun f (_ : f ∈ Finset.univ) => hrow f
    rw [Finset.sum_add_distrib, ← Finset.mul_sum, Finset.sum_const, Finset.card_univ,
      Fintype.card_fin, Finset.sum_const_zero] at h
    simp only [nsmul_eq_mul, Nat.cast_ofNat] at h
    linear_combination (3 / 20 : ℂ) * h
  intro e
  have := hrow e
  rw [hsum, mul_zero, add_zero] at this
  exact (mul_eq_zero.mp this).resolve_left (by norm_num)

end Completion

/-! ### The countertheorem -/

section Main

variable {m : Type*} [Fintype m] [DecidableEq m]

/-- The commuting family transported to a carrier of cardinality `20`. -/
noncomputable def HcOn (hm : Fintype.card m = 20) (e : Fin 6) : Matrix m m ℂ :=
  Matrix.reindexAlgEquiv ℂ ℂ (Fintype.equivOfCardEq (card_Three.trans hm.symm)) (Hc e)

/-- The Clifford family transported to a carrier of cardinality `20`. -/
noncomputable def HqOn (hm : Fintype.card m = 20) (e : Fin 6) : Matrix m m ℂ :=
  Matrix.reindexAlgEquiv ℂ ℂ
    (Fintype.equivOfCardEq (by rw [Fintype.card_prod, card_SMST4, Fintype.card_fin, hm]) :
      SMST4 × Fin 5 ≃ m) (cliffordHq helmert cliffordSMST4 e)

theorem HcOn_conjTranspose (hm : Fintype.card m = 20) (e : Fin 6) : (HcOn hm e)ᴴ = HcOn hm e := by
  rw [HcOn, reindexAlgEquiv_conjTranspose, Hc_conjTranspose]

theorem HcOn_mul_self (hm : Fintype.card m = 20) (e : Fin 6) : HcOn hm e * HcOn hm e = 1 := by
  rw [HcOn, ← map_mul, Hc_mul_self, map_one]

theorem HcOn_sum (hm : Fintype.card m = 20) : ∑ e, HcOn hm e = 0 := by
  simp only [HcOn]
  rw [← map_sum, Hc_sum, map_zero]

theorem HcOn_trace (hm : Fintype.card m = 20) (e : Fin 6) : (HcOn hm e).trace = 0 := by
  rw [HcOn, trace_reindexAlgEquiv, Hc_trace]

theorem HcOn_gram (hm : Fintype.card m = 20) (e f : Fin 6) :
    (HcOn hm e * HcOn hm f).trace = if e = f then 20 else -4 := by
  rw [HcOn, HcOn, ← map_mul, trace_reindexAlgEquiv, Hc_gram]

theorem HqOn_conjTranspose (hm : Fintype.card m = 20) (e : Fin 6) : (HqOn hm e)ᴴ = HqOn hm e := by
  rw [HqOn, reindexAlgEquiv_conjTranspose, cliffordHq_conjTranspose]

theorem HqOn_mul_self (hm : Fintype.card m = 20) (e : Fin 6) : HqOn hm e * HqOn hm e = 1 := by
  rw [HqOn, ← map_mul, cliffordHq_mul_self, map_one]

theorem HqOn_sum (hm : Fintype.card m = 20) : ∑ e, HqOn hm e = 0 := by
  simp only [HqOn]
  rw [← map_sum, cliffordHq_sum, map_zero]

theorem HqOn_trace (hm : Fintype.card m = 20) (e : Fin 6) : (HqOn hm e).trace = 0 := by
  rw [HqOn, trace_reindexAlgEquiv, cliffordHq_trace]

theorem HqOn_gram (hm : Fintype.card m = 20) (e f : Fin 6) :
    (HqOn hm e * HqOn hm f).trace = if e = f then 20 else -4 := by
  rw [HqOn, HqOn, ← map_mul, trace_reindexAlgEquiv, cliffordHq_gram_four _ _ card_SMST4]

theorem adjoin_HcOn_commutative (hm : Fintype.card m = 20) :
    ∀ x ∈ Algebra.adjoin ℂ (Set.range (HcOn hm)), ∀ y ∈ Algebra.adjoin ℂ (Set.range (HcOn hm)),
      x * y = y * x := by
  intro x hx y hy
  set φ := Matrix.reindexAlgEquiv ℂ ℂ (Fintype.equivOfCardEq (card_Three.trans hm.symm)) with hφ
  have hle : Algebra.adjoin ℂ (Set.range (HcOn hm)) ≤ diagonalSubalgebra.map φ.toAlgHom := by
    rw [Algebra.adjoin_le_iff]
    rintro _ ⟨e, rfl⟩
    exact Subalgebra.mem_map.mpr ⟨Hc e, mem_diagonalSubalgebra.mpr ⟨sgn e, rfl⟩, rfl⟩
  obtain ⟨a, ha, rfl⟩ := Subalgebra.mem_map.mp (hle hx)
  obtain ⟨b, hb, rfl⟩ := Subalgebra.mem_map.mp (hle hy)
  obtain ⟨da, rfl⟩ := mem_diagonalSubalgebra.mp ha
  obtain ⟨db, rfl⟩ := mem_diagonalSubalgebra.mp hb
  have hcomm : Matrix.diagonal da * Matrix.diagonal db = Matrix.diagonal db * Matrix.diagonal da := by
    rw [Matrix.diagonal_mul_diagonal, Matrix.diagonal_mul_diagonal]
    congr 1
    funext S
    ring
  show φ (Matrix.diagonal da) * φ (Matrix.diagonal db) = φ (Matrix.diagonal db) * φ (Matrix.diagonal da)
  rw [← map_mul, ← map_mul, hcomm]

theorem centralizer_HcOn_commutative (hm : Fintype.card m = 20) :
    ∀ x ∈ Subalgebra.centralizer ℂ (Set.range (HcOn hm)),
      ∀ y ∈ Subalgebra.centralizer ℂ (Set.range (HcOn hm)), x * y = y * x := by
  intro x hx y hy
  set σ := (Fintype.equivOfCardEq (card_Three.trans hm.symm) : Three ≃ m)
  have hx' : (Matrix.reindexAlgEquiv ℂ ℂ σ).symm x ∈ Subalgebra.centralizer ℂ (Set.range Hc) := by
    rw [Subalgebra.mem_centralizer_iff] at hx ⊢
    rintro _ ⟨e, rfl⟩
    apply (Matrix.reindexAlgEquiv ℂ ℂ σ).injective
    rw [map_mul, map_mul, AlgEquiv.apply_symm_apply]
    exact hx (HcOn hm e) ⟨e, rfl⟩
  have hy' : (Matrix.reindexAlgEquiv ℂ ℂ σ).symm y ∈ Subalgebra.centralizer ℂ (Set.range Hc) := by
    rw [Subalgebra.mem_centralizer_iff] at hy ⊢
    rintro _ ⟨e, rfl⟩
    apply (Matrix.reindexAlgEquiv ℂ ℂ σ).injective
    rw [map_mul, map_mul, AlgEquiv.apply_symm_apply]
    exact hy (HcOn hm e) ⟨e, rfl⟩
  have := centralizer_Hc_commutative _ _ hx' hy'
  apply (Matrix.reindexAlgEquiv ℂ ℂ σ).symm.injective
  rw [map_mul, map_mul, this]

theorem adjoin_HqOn_not_commutative (hm : Fintype.card m = 20) :
    ¬ ∀ x ∈ Algebra.adjoin ℂ (Set.range (HqOn hm)), ∀ y ∈ Algebra.adjoin ℂ (Set.range (HqOn hm)),
      x * y = y * x := fun h =>
  adjoin_cliffordHq_not_commutative helmert cliffordSMST4 (adjoin_comm_of_map _ _ h)

theorem centralizer_HqOn_not_commutative (hm : Fintype.card m = 20) :
    ¬ ∀ x ∈ Subalgebra.centralizer ℂ (Set.range (HqOn hm)),
      ∀ y ∈ Subalgebra.centralizer ℂ (Set.range (HqOn hm)), x * y = y * x := fun h =>
  centralizer_cliffordHq_not_commutative helmert cliffordSMST4 (centralizer_comm_of_map _ _ h)

/-- A unital algebra isomorphism between subalgebras transports commutativity. -/
theorem not_nonempty_algEquiv_of_comm {A : Type*} [Ring A] [Algebra ℂ A]
    (S T : Subalgebra ℂ A) (hS : ∀ x ∈ S, ∀ y ∈ S, x * y = y * x)
    (hT : ¬ ∀ x ∈ T, ∀ y ∈ T, x * y = y * x) : ¬ Nonempty (S ≃ₐ[ℂ] T) := by
  rintro ⟨f⟩
  apply hT
  intro x hx y hy
  have h := hS (f.symm ⟨x, hx⟩) (f.symm ⟨x, hx⟩).2 (f.symm ⟨y, hy⟩) (f.symm ⟨y, hy⟩).2
  have h' : f.symm ⟨x, hx⟩ * f.symm ⟨y, hy⟩ = f.symm ⟨y, hy⟩ * f.symm ⟨x, hx⟩ := Subtype.ext h
  have h'' := congrArg f h'
  rw [map_mul, map_mul, AlgEquiv.apply_symm_apply, AlgEquiv.apply_symm_apply] at h''
  exact congrArg Subtype.val h''

/-- **`thm:record-nonidentifiability`** (classical record data do not determine the system
algebra).  On any `20`-dimensional carrier `ℂ^m`, for any record factor `ℂ^r` with orthogonal
projectors `Q_a` summing to `I` and any `0 ≤ θ ≤ 1`, there are two six-edge coefficient families
`K^c`, `K^q` such that

* both satisfy `eq:six-edge-normalization` (`∑ K^*K = I`, `∑ K = √2 I`, linear independence);
* both resolved instruments `L_0 = √(1−θ) I`, `L_{e,a} = √θ K_e ⊗ Q_a` are normalized;
* they have the same one-step effects, the same effect for every classical word (the same
  resolved record channel at every word length), the same one-letter Hilbert–Schmidt Gram
  `Tr K_e^* K_f`, and Choi matrices with the same characteristic polynomial (the same Choi
  spectrum with multiplicities);
* yet the generated unital algebras are not isomorphic, and neither are their commutants. -/
theorem record_nonidentifiability (hm : Fintype.card m = 20)
    {r ρ : Type*} [Fintype r] [DecidableEq r] [Fintype ρ] [DecidableEq ρ]
    (Q : ρ → Matrix r r ℂ) (hQ : ∀ a, (Q a)ᴴ = Q a)
    (hQQ : ∀ a b, Q a * Q b = if a = b then Q a else 0) (hQsum : ∑ a, Q a = 1)
    (θ : ℝ) (hθ0 : 0 ≤ θ) (hθ1 : θ ≤ 1) :
    ∃ Kc Kq : Fin 6 → Matrix m m ℂ,
      (∑ e, (Kc e)ᴴ * Kc e = 1 ∧ ∑ e, Kc e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) ∧
        LinearIndependent ℂ Kc) ∧
      (∑ e, (Kq e)ᴴ * Kq e = 1 ∧ ∑ e, Kq e = ((Real.sqrt 2 : ℝ) : ℂ) • (1 : Matrix m m ℂ) ∧
        LinearIndependent ℂ Kq) ∧
      (∑ ℓ, (kraus Kc Q θ ℓ)ᴴ * kraus Kc Q θ ℓ = 1) ∧
      (∑ ℓ, (kraus Kq Q θ ℓ)ᴴ * kraus Kq Q θ ℓ = 1) ∧
      (∀ ℓ, (kraus Kc Q θ ℓ)ᴴ * kraus Kc Q θ ℓ = (kraus Kq Q θ ℓ)ᴴ * kraus Kq Q θ ℓ) ∧
      (∀ w : List (Letter ρ), effect (kraus Kc Q θ) w = effect (kraus Kq Q θ) w) ∧
      (∀ e f, ((Kc e)ᴴ * Kc f).trace = ((Kq e)ᴴ * Kq f).trace) ∧
      (choiMat (kraus Kc Q θ)).charpoly = (choiMat (kraus Kq Q θ)).charpoly ∧
      ¬ Nonempty (Algebra.adjoin ℂ (Set.range Kc) ≃ₐ[ℂ] Algebra.adjoin ℂ (Set.range Kq)) ∧
      ¬ Nonempty (Subalgebra.centralizer ℂ (Set.range Kc) ≃ₐ[ℂ]
        Subalgebra.centralizer ℂ (Set.range Kq)) := by
  refine ⟨fun e => completion (HcOn hm e), fun e => completion (HqOn hm e), ?_, ?_, ?_, ?_, ?_,
    ?_, ?_, ?_, ?_, ?_⟩
  -- shared record data
  · exact ⟨sum_conjTranspose_mul_completion _ (HcOn_conjTranspose hm) (HcOn_mul_self hm),
      sum_completion _ (HcOn_sum hm),
      linearIndependent_of_gram _ (trace_conjTranspose_mul_completion_gram hm _
        (HcOn_conjTranspose hm) (HcOn_trace hm) (HcOn_gram hm))⟩
  · exact ⟨sum_conjTranspose_mul_completion _ (HqOn_conjTranspose hm) (HqOn_mul_self hm),
      sum_completion _ (HqOn_sum hm),
      linearIndependent_of_gram _ (trace_conjTranspose_mul_completion_gram hm _
        (HqOn_conjTranspose hm) (HqOn_trace hm) (HqOn_gram hm))⟩
  · exact sum_kraus_conjTranspose_mul _ Q θ hθ0 hθ1
      (sum_conjTranspose_mul_completion _ (HcOn_conjTranspose hm) (HcOn_mul_self hm)) hQ hQQ hQsum
  · exact sum_kraus_conjTranspose_mul _ Q θ hθ0 hθ1
      (sum_conjTranspose_mul_completion _ (HqOn_conjTranspose hm) (HqOn_mul_self hm)) hQ hQQ hQsum
  · intro ℓ
    rw [← effect_singleton, ← effect_singleton]
    exact effect_kraus_eq _ _ Q θ hθ0 hθ1
      (fun e => completion_conjTranspose_mul_self _ (HcOn_conjTranspose hm e) (HcOn_mul_self hm e))
      (fun e => completion_conjTranspose_mul_self _ (HqOn_conjTranspose hm e) (HqOn_mul_self hm e))
      hQ _
  · exact effect_kraus_eq _ _ Q θ hθ0 hθ1
      (fun e => completion_conjTranspose_mul_self _ (HcOn_conjTranspose hm e) (HcOn_mul_self hm e))
      (fun e => completion_conjTranspose_mul_self _ (HqOn_conjTranspose hm e) (HqOn_mul_self hm e))
      hQ
  · intro e f
    rw [trace_conjTranspose_mul_completion_gram hm _ (HcOn_conjTranspose hm) (HcOn_trace hm)
      (HcOn_gram hm), trace_conjTranspose_mul_completion_gram hm _ (HqOn_conjTranspose hm)
      (HqOn_trace hm) (HqOn_gram hm)]
  · apply choiMat_charpoly_eq_of_hsGram_eq
    apply hsGram_kraus_eq
    · intro e
      rw [completion_trace _ (HcOn_trace hm e), completion_trace _ (HqOn_trace hm e)]
    · intro e f
      rw [trace_conjTranspose_mul_completion_gram hm _ (HcOn_conjTranspose hm) (HcOn_trace hm)
        (HcOn_gram hm), trace_conjTranspose_mul_completion_gram hm _ (HqOn_conjTranspose hm)
        (HqOn_trace hm) (HqOn_gram hm)]
  · rw [adjoin_range_completion, adjoin_range_completion]
    exact not_nonempty_algEquiv_of_comm _ _ (adjoin_HcOn_commutative hm)
      (adjoin_HqOn_not_commutative hm)
  · rw [centralizer_range_completion, centralizer_range_completion]
    exact not_nonempty_algEquiv_of_comm _ _ (centralizer_HcOn_commutative hm)
      (centralizer_HqOn_not_commutative hm)

end Main

end RecordWitness
end RenewalGeometry
