/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.StandardModel.ConnectedRouterExact

/-!
# Algebraic structure of the router failure set

`prop:router-failure-locus` of the spacetime–gauge duality paper.  For the diagonal
algebra `𝒟_n` of `thm:connected-router` (`ConnectedRouterExact.lean`) the **router
failure set** is

  `𝔉_n = {u ∈ M_n(ℂ) : C*(𝒟_n, u) ≠ M_n(ℂ)}`  (`failureSet`),

and for every nonempty proper vertex set `S` the **cut subspace**

  `L_S = {u : p_i u p_j = p_j u p_i = 0 for all i ∈ S, j ∉ S}`  (`cutSubspace S`),

which is the block-diagonal subalgebra `blockAlgebra S` viewed as a linear subspace.

* `failureSet_eq_biUnion_cutSubspace`: the boxed identity
  `𝔉_n = ⋃_{∅ ≠ S ⊊ {1,…,n}} L_S` (`eq:router-failure-locus`);
* `cutSubspace_ne_top`: each `L_S` is a proper linear subspace (the all-ones matrix,
  whose support graph is complete, lies outside);
* `isClosed_failureSet`, `interior_failureSet`, `dense_compl_failureSet`,
  `isOpen_compl_failureSet`: `𝔉_n` is Euclidean closed with empty interior, so its
  complement is Euclidean open and dense;
* `exists_ideal_failureSet_eq_zeroLocus`: `𝔉_n` is the zero locus of an ideal of
  `ℂ[X_{ab}]` (the product over `S` of the ideals generated by the cross entries
  `X_{ab}`, `a ∈ S ↔ b ∉ S`), i.e. Zariski closed, and it is proper.

The vertex type `n` is an arbitrary finite type with decidable equality; the union
identity assumes `n` nonempty (for `n = ∅` both sides are empty anyway, but
`SimpleGraph.Connected` requires a nonempty vertex set).
-/

open Finset Matrix Topology

namespace RenewalGeometry
namespace ConnectedRouter

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The router failure set `𝔉_n = {u : C*(𝒟_n, u) ≠ M_n(ℂ)}`. -/
def failureSet : Set (Matrix n n ℂ) :=
  {u | Algebra.adjoin ℂ (routerGens u) ≠ ⊤}

/-- The cut subspace `L_S = {u : p_i u p_j = p_j u p_i = 0, i ∈ S, j ∉ S}`: the block
algebra of `S` as a complex linear subspace. -/
def cutSubspace (S : Set n) : Submodule ℂ (Matrix n n ℂ) :=
  Subalgebra.toSubmodule (blockAlgebra S)

theorem mem_cutSubspace {S : Set n} {u : Matrix n n ℂ} :
    u ∈ cutSubspace S ↔ ∀ a b : n, ¬ (a ∈ S ↔ b ∈ S) → u a b = 0 :=
  Iff.rfl

/-- The paper's form of the cut conditions: all corners `p_i u p_j` and `p_j u p_i`
vanish for `i ∈ S`, `j ∉ S`. -/
theorem mem_cutSubspace_iff_corners {S : Set n} {u : Matrix n n ℂ} :
    u ∈ cutSubspace S ↔
      ∀ i ∈ S, ∀ j ∉ S, diagProj i * u * diagProj j = 0 ∧ diagProj j * u * diagProj i = 0 := by
  rw [mem_cutSubspace]
  constructor
  · intro h i hi j hj
    have h1 := h i j (fun hij => hj (hij.mp hi))
    have h2 := h j i (fun hji => hj (hji.mpr hi))
    rw [diagProj_mul_mul_diagProj, diagProj_mul_mul_diagProj, h1, h2, zero_smul, zero_smul]
    exact ⟨rfl, rfl⟩
  · intro h a b hab
    by_cases ha : a ∈ S
    · have hb : b ∉ S := fun hb => hab ⟨fun _ => hb, fun _ => ha⟩
      have := (h a ha b hb).1
      rw [diagProj_mul_mul_diagProj] at this
      by_contra hne
      have := congrFun (congrFun this a) b
      rw [Matrix.smul_apply, Matrix.single_apply_same, smul_eq_mul, mul_one,
        Matrix.zero_apply] at this
      exact hne this
    · have hb : b ∈ S := by
        by_contra hb
        exact hab ⟨fun h => absurd h ha, fun h => absurd h hb⟩
      have := (h b hb a ha).2
      rw [diagProj_mul_mul_diagProj] at this
      by_contra hne
      have := congrFun (congrFun this a) b
      rw [Matrix.smul_apply, Matrix.single_apply_same, smul_eq_mul, mul_one,
        Matrix.zero_apply] at this
      exact hne this

/-- The nonempty proper vertex sets. -/
noncomputable def properCuts : Finset (Set n) := by
  classical exact Finset.univ.filter fun S : Set n => S.Nonempty ∧ S ≠ Set.univ

theorem mem_properCuts {S : Set n} : S ∈ properCuts ↔ S.Nonempty ∧ S ≠ Set.univ := by
  classical
  simp [properCuts]

/-- Membership in a cut subspace makes the vertex set adjacency-closed. -/
theorem adjClosed_of_mem_cutSubspace {S : Set n} {u : Matrix n n ℂ} (hu : u ∈ cutSubspace S) :
    AdjClosed u S := by
  intro a b hab
  by_contra hne
  rcases (supportGraph_adj u a b).mp hab with ⟨_, h | h⟩
  · exact h (hu a b hne)
  · exact h (hu b a (fun hba => hne hba.symm))

/-- **`eq:router-failure-locus`**: `𝔉_n = ⋃_{∅ ≠ S ⊊ {1,…,n}} L_S`. -/
theorem failureSet_eq_biUnion_cutSubspace [Nonempty n] :
    (failureSet : Set (Matrix n n ℂ)) =
      ⋃ S ∈ (properCuts : Finset (Set n)), (cutSubspace S : Set (Matrix n n ℂ)) := by
  ext u
  simp only [Set.mem_iUnion, SetLike.mem_coe, exists_prop, mem_properCuts]
  constructor
  · intro hu
    have hnc : ¬ (supportGraph u).Connected := fun hc =>
      hu (adjoin_eq_top_of_connected u hc)
    obtain ⟨S, hne, hproper, -, hle, -, -⟩ := disconnected_block_reduction u hnc
    exact ⟨S, ⟨hne, hproper⟩, hle (router_mem Algebra.subset_adjoin)⟩
  · rintro ⟨S, ⟨⟨i, hi⟩, hproper⟩, hu⟩
    obtain ⟨j, hj⟩ := (Set.ne_univ_iff_exists_notMem S).mp hproper
    intro htop
    have hle := adjoin_le_blockAlgebra (adjClosed_of_mem_cutSubspace hu)
    rw [htop, top_le_iff] at hle
    exact blockAlgebra_ne_top hi hj hle

/-- The all-ones matrix lies outside every cut subspace of a nonempty proper vertex
set. -/
theorem allOnes_notMem_cutSubspace {S : Set n} (hne : S.Nonempty) (hproper : S ≠ Set.univ) :
    (Matrix.of fun _ _ => (1 : ℂ)) ∉ cutSubspace S := by
  obtain ⟨i, hi⟩ := hne
  obtain ⟨j, hj⟩ := (Set.ne_univ_iff_exists_notMem S).mp hproper
  intro h
  have := h i j (fun hij => hj (hij.mp hi))
  rw [Matrix.of_apply] at this
  exact one_ne_zero this

/-- Each `L_S` (`S` nonempty and proper) is a proper linear subspace of `M_n(ℂ)`. -/
theorem cutSubspace_ne_top {S : Set n} (hne : S.Nonempty) (hproper : S ≠ Set.univ) :
    cutSubspace S ≠ ⊤ := by
  intro h
  exact allOnes_notMem_cutSubspace hne hproper (h ▸ Submodule.mem_top)

/-- The all-ones matrix (complete support graph) is a router. -/
theorem allOnes_notMem_failureSet [Nonempty n] :
    (Matrix.of fun _ _ => (1 : ℂ)) ∉ (failureSet : Set (Matrix n n ℂ)) := by
  rw [failureSet_eq_biUnion_cutSubspace]
  simp only [Set.mem_iUnion, SetLike.mem_coe, exists_prop, mem_properCuts, not_exists, not_and]
  intro S hS
  exact allOnes_notMem_cutSubspace hS.1 hS.2

theorem failureSet_ne_univ [Nonempty n] :
    (failureSet : Set (Matrix n n ℂ)) ≠ Set.univ := fun h =>
  allOnes_notMem_failureSet (h ▸ Set.mem_univ _)

/-! ### Euclidean topology -/

theorem isClosed_cutSubspace (S : Set n) :
    IsClosed ((cutSubspace S : Submodule ℂ (Matrix n n ℂ)) : Set (Matrix n n ℂ)) :=
  Submodule.closed_of_finiteDimensional _

theorem interior_cutSubspace {S : Set n} (hne : S.Nonempty) (hproper : S ≠ Set.univ) :
    interior ((cutSubspace S : Submodule ℂ (Matrix n n ℂ)) : Set (Matrix n n ℂ)) = ∅ := by
  by_contra h
  exact cutSubspace_ne_top hne hproper
    (Submodule.eq_top_of_nonempty_interior' _ (Set.nonempty_iff_ne_empty.mpr h))

/-- A finite union of closed sets with empty interior has empty interior. -/
theorem interior_finset_biUnion_eq_empty {ι : Type*} {X : Type*} [TopologicalSpace X]
    (T : Finset ι) (s : ι → Set X) (hclosed : ∀ i ∈ T, IsClosed (s i))
    (hint : ∀ i ∈ T, interior (s i) = ∅) :
    interior (⋃ i ∈ T, s i) = ∅ := by
  classical
  induction T using Finset.induction_on with
  | empty => simp
  | insert a T haT ih =>
    rw [Finset.set_biUnion_insert,
      interior_union_isClosed_of_interior_empty (hclosed a (Finset.mem_insert_self a T))
        (ih (fun i hi => hclosed i (Finset.mem_insert_of_mem hi))
          (fun i hi => hint i (Finset.mem_insert_of_mem hi)))]
    exact hint a (Finset.mem_insert_self a T)

/-- `𝔉_n` is Euclidean closed. -/
theorem isClosed_failureSet [Nonempty n] :
    IsClosed (failureSet : Set (Matrix n n ℂ)) := by
  rw [failureSet_eq_biUnion_cutSubspace]
  exact properCuts.finite_toSet.isClosed_biUnion fun S _ => isClosed_cutSubspace S

/-- `𝔉_n` has empty Euclidean interior. -/
theorem interior_failureSet [Nonempty n] :
    interior (failureSet : Set (Matrix n n ℂ)) = ∅ := by
  rw [failureSet_eq_biUnion_cutSubspace]
  refine interior_finset_biUnion_eq_empty properCuts _ (fun S _ => isClosed_cutSubspace S)
    fun S hS => ?_
  rw [mem_properCuts] at hS
  exact interior_cutSubspace hS.1 hS.2

/-- The complement of `𝔉_n` (the routers) is Euclidean open. -/
theorem isOpen_compl_failureSet [Nonempty n] :
    IsOpen (failureSet : Set (Matrix n n ℂ))ᶜ :=
  isClosed_failureSet.isOpen_compl

/-- The complement of `𝔉_n` (the routers) is Euclidean dense. -/
theorem dense_compl_failureSet [Nonempty n] :
    Dense (failureSet : Set (Matrix n n ℂ))ᶜ :=
  interior_eq_empty_iff_dense_compl.mp interior_failureSet

/-! ### Zariski closedness -/

/-- The coordinate point of a matrix, as a point of the affine space `ℂ^{n × n}`. -/
def toPoint (u : Matrix n n ℂ) : n × n → ℂ := fun ab => u ab.1 ab.2

/-- The ideal of the cut subspace `L_S`: generated by the cross coordinates
`X_{ab}` with `a ∈ S ↔ b ∉ S`. -/
noncomputable def cutIdeal (S : Set n) : Ideal (MvPolynomial (n × n) ℂ) :=
  Ideal.span {p | ∃ ab : n × n, ¬ (ab.1 ∈ S ↔ ab.2 ∈ S) ∧ p = MvPolynomial.X ab}

theorem mem_cutSubspace_iff_toPoint_mem_zeroLocus {S : Set n} {u : Matrix n n ℂ} :
    u ∈ cutSubspace S ↔ toPoint u ∈ MvPolynomial.zeroLocus ℂ (cutIdeal S) := by
  rw [cutIdeal, MvPolynomial.zeroLocus_span, Set.mem_ofPred_eq, mem_cutSubspace]
  constructor
  · rintro h p ⟨ab, hab, rfl⟩
    rw [MvPolynomial.aeval_X]
    exact h ab.1 ab.2 hab
  · intro h a b hab
    have := h (MvPolynomial.X (a, b)) ⟨(a, b), hab, rfl⟩
    rwa [MvPolynomial.aeval_X] at this

/-- The zero locus of a product of two ideals is the union of the zero loci. -/
theorem zeroLocus_mul {σ : Type*} (I J : Ideal (MvPolynomial σ ℂ)) :
    MvPolynomial.zeroLocus ℂ (I * J) =
      MvPolynomial.zeroLocus ℂ I ∪ MvPolynomial.zeroLocus ℂ J := by
  ext x
  constructor
  · intro hx
    by_contra hnot
    rw [Set.mem_union, not_or] at hnot
    obtain ⟨hI, hJ⟩ := hnot
    rw [MvPolynomial.mem_zeroLocus_iff, not_forall] at hI hJ
    obtain ⟨p, hp⟩ := hI
    obtain ⟨q, hq⟩ := hJ
    rw [_root_.not_imp] at hp hq
    have := hx (p * q) (Ideal.mul_mem_mul hp.1 hq.1)
    rw [map_mul] at this
    exact mul_ne_zero hp.2 hq.2 this
  · rintro (hx | hx)
    · exact MvPolynomial.zeroLocus_anti_mono Ideal.mul_le_left hx
    · exact MvPolynomial.zeroLocus_anti_mono Ideal.mul_le_right hx

/-- The zero locus of a finite product of ideals is the finite union of the zero loci. -/
theorem zeroLocus_finset_prod {σ ι : Type*} (T : Finset ι) (I : ι → Ideal (MvPolynomial σ ℂ)) :
    MvPolynomial.zeroLocus ℂ (∏ i ∈ T, I i) = ⋃ i ∈ T, MvPolynomial.zeroLocus ℂ (I i) := by
  classical
  induction T using Finset.induction_on with
  | empty =>
    rw [Finset.prod_empty, Ideal.one_eq_top, MvPolynomial.zeroLocus_top]
    simp
  | insert a T haT ih =>
    rw [Finset.prod_insert haT, zeroLocus_mul, ih, Finset.set_biUnion_insert]

/-- The failure ideal: the product over all nonempty proper vertex sets of the cut
ideals. -/
noncomputable def failureIdeal (n : Type*) [Fintype n] [DecidableEq n] :
    Ideal (MvPolynomial (n × n) ℂ) :=
  ∏ S ∈ (properCuts : Finset (Set n)), cutIdeal S

/-- **Zariski closedness of `𝔉_n`**: the failure set is the preimage under the
coordinate map of the zero locus of the failure ideal. -/
theorem failureSet_eq_preimage_zeroLocus [Nonempty n] :
    (failureSet : Set (Matrix n n ℂ)) =
      toPoint ⁻¹' MvPolynomial.zeroLocus ℂ (failureIdeal n) := by
  rw [failureSet_eq_biUnion_cutSubspace, failureIdeal, zeroLocus_finset_prod]
  ext u
  simp only [Set.mem_iUnion, SetLike.mem_coe, exists_prop, Set.mem_preimage]
  constructor
  · rintro ⟨S, hS, hu⟩
    exact ⟨S, hS, mem_cutSubspace_iff_toPoint_mem_zeroLocus.mp hu⟩
  · rintro ⟨S, hS, hu⟩
    exact ⟨S, hS, mem_cutSubspace_iff_toPoint_mem_zeroLocus.mpr hu⟩

/-- **`prop:router-failure-locus`, Zariski clause**: `𝔉_n` is the zero locus of an
ideal of the coordinate ring `ℂ[X_{ab}]` (so it is Zariski closed, and its complement
is Zariski open), and the zero locus is a proper subset of the affine space. -/
theorem exists_ideal_failureSet_eq_zeroLocus [Nonempty n] :
    ∃ I : Ideal (MvPolynomial (n × n) ℂ),
      (failureSet : Set (Matrix n n ℂ)) = toPoint ⁻¹' MvPolynomial.zeroLocus ℂ I ∧
      MvPolynomial.zeroLocus ℂ I ≠ Set.univ := by
  refine ⟨failureIdeal n, failureSet_eq_preimage_zeroLocus, fun h => ?_⟩
  apply allOnes_notMem_failureSet (n := n)
  rw [failureSet_eq_preimage_zeroLocus, h]
  exact Set.mem_univ _

/-- **`prop:router-failure-locus`** (spacetime–gauge duality paper), assembled:
`𝔉_n = ⋃_{∅ ≠ S ⊊ [n]} L_S`; every `L_S` is a proper linear subspace; `𝔉_n` is the
zero locus of an ideal (Zariski closed) and proper; its complement is Euclidean open
and dense. -/
theorem router_failure_locus [Nonempty n] :
    ((failureSet : Set (Matrix n n ℂ)) =
        ⋃ S ∈ (properCuts : Finset (Set n)), (cutSubspace S : Set (Matrix n n ℂ))) ∧
    (∀ S : Set n, S.Nonempty → S ≠ Set.univ → cutSubspace S ≠ ⊤) ∧
    (∃ I : Ideal (MvPolynomial (n × n) ℂ),
      (failureSet : Set (Matrix n n ℂ)) = toPoint ⁻¹' MvPolynomial.zeroLocus ℂ I) ∧
    (failureSet : Set (Matrix n n ℂ)) ≠ Set.univ ∧
    IsClosed (failureSet : Set (Matrix n n ℂ)) ∧
    IsOpen (failureSet : Set (Matrix n n ℂ))ᶜ ∧
    Dense (failureSet : Set (Matrix n n ℂ))ᶜ :=
  ⟨failureSet_eq_biUnion_cutSubspace, fun _ hne hproper => cutSubspace_ne_top hne hproper,
    ⟨failureIdeal n, failureSet_eq_preimage_zeroLocus⟩, failureSet_ne_univ,
    isClosed_failureSet, isOpen_compl_failureSet, dense_compl_failureSet⟩

end ConnectedRouter
end RenewalGeometry
