/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import RenewalGeometry.Commutant.ReciprocalWedderburnKronecker

/-!
# Same-carrier tensor-factor alignment

Covers `thm:tensor-factor-alignment` of the spacetime–gauge duality manuscript.

The represented factor algebras on the carrier `𝒦_det = ℂ^K` are the images of unital
`*`-homomorphisms `φ_C : M₃(ℂ) → B(𝒦)`, `φ₁, φ₂ : M₂(ℂ) → B(𝒦)`; `(C_α)`, `(W¹_β)`, `(W²_γ)`
are Hermitian families in these images spanning them.

* `alignDefect` is `Δ_⊗` (`eq:tensor-alignment-defect`), a sum of squared Hilbert–Schmidt
  norms of commutators; `alignDefect_eq_zero_iff`: `Δ_⊗ = 0` iff the three represented factor
  algebras commute pairwise (`eq:tensor-alignment-zero`).
* `MatUnits` / `MatUnits.toStarAlgHom`: a system of `*`-matrix units in `M_K(ℂ)` induces a
  unital `*`-homomorphism `M_ι(ℂ) → M_K(ℂ)`; `MatUnits.spatial`: it is unitarily equivalent
  to `M ↦ M ⊗ I_J` for a finite multiplicity type `J` (finite-dimensional representation
  theorem for full matrix algebras, built from `projection_factor`).
* `tensor_factor_alignment`: on the commuting branch, multiplication
  `X ⊗ Y ⊗ Z ↦ φ_C(X) φ₁(Y) φ₂(Z)` is an injective unital `*`-homomorphism
  `M₃ ⊗ M₂ ⊗ M₂ = M_{Fin 3 × Fin 2 × Fin 2}(ℂ) ≅ M₁₂(ℂ) ↪ B(𝒦)` (`eq:tensor-factor-product`),
  its range is the algebra generated by the three factors, and a unitary `W` carries that
  generated algebra onto `M₁₂(ℂ) ⊗ I_M`.
-/

open Matrix
open scoped Kronecker

namespace RenewalGeometry
namespace TensorFactorAlignment

/-! ## Hilbert–Schmidt defect -/

section Defect

variable {K : Type} [Fintype K] [DecidableEq K]

/-- Squared Hilbert–Schmidt norm. -/
noncomputable def hsNormSq (M : Matrix K K ℂ) : ℝ := ∑ i, ∑ j, Complex.normSq (M i j)

theorem hsNormSq_nonneg (M : Matrix K K ℂ) : 0 ≤ hsNormSq M :=
  Finset.sum_nonneg fun i _ => Finset.sum_nonneg fun j _ => Complex.normSq_nonneg _

theorem hsNormSq_eq_zero_iff (M : Matrix K K ℂ) : hsNormSq M = 0 ↔ M = 0 := by
  constructor
  · intro h
    have h1 := (Finset.sum_eq_zero_iff_of_nonneg fun i _ =>
      Finset.sum_nonneg fun j _ => Complex.normSq_nonneg (M i j)).mp h
    ext i j
    have h2 := (Finset.sum_eq_zero_iff_of_nonneg fun j _ => Complex.normSq_nonneg (M i j)).mp
      (h1 i (Finset.mem_univ _)) j (Finset.mem_univ _)
    simpa using h2
  · rintro rfl
    simp [hsNormSq]

/-- A sum over a finite family of squared HS norms vanishes iff every term vanishes. -/
theorem sum_hsNormSq_eq_zero_iff {ι κ : Type} [Fintype ι] [Fintype κ]
    (F : ι → κ → Matrix K K ℂ) :
    ∑ a, ∑ b, hsNormSq (F a b) = 0 ↔ ∀ a b, F a b = 0 := by
  rw [Finset.sum_eq_zero_iff_of_nonneg fun a _ =>
    Finset.sum_nonneg fun b _ => hsNormSq_nonneg _]
  simp only [Finset.mem_univ, true_implies]
  refine forall_congr' fun a => ?_
  rw [Finset.sum_eq_zero_iff_of_nonneg fun b _ => hsNormSq_nonneg _]
  simp [hsNormSq_eq_zero_iff]

/-- The tensor-alignment defect `Δ_⊗` (`eq:tensor-alignment-defect`). -/
noncomputable def alignDefect {ια ιβ ιγ : Type} [Fintype ια] [Fintype ιβ] [Fintype ιγ]
    (C : ια → Matrix K K ℂ) (W₁ : ιβ → Matrix K K ℂ) (W₂ : ιγ → Matrix K K ℂ) : ℝ :=
  ∑ a, ∑ b, hsNormSq (C a * W₁ b - W₁ b * C a) +
    ∑ a, ∑ c, hsNormSq (C a * W₂ c - W₂ c * C a) +
    ∑ b, ∑ c, hsNormSq (W₁ b * W₂ c - W₂ c * W₁ b)

/-- Commutation of spanning families transfers to their spans. -/
theorem commute_of_span {ι κ : Type} (F : ι → Matrix K K ℂ) (G : κ → Matrix K K ℂ)
    (h : ∀ a b, Commute (F a) (G b)) {x y : Matrix K K ℂ}
    (hx : x ∈ Submodule.span ℂ (Set.range F)) (hy : y ∈ Submodule.span ℂ (Set.range G)) :
    Commute x y := by
  induction hx using Submodule.span_induction with
  | mem x hx =>
    obtain ⟨a, rfl⟩ := hx
    induction hy using Submodule.span_induction with
    | mem y hy => obtain ⟨b, rfl⟩ := hy; exact h a b
    | zero => exact Commute.zero_right _
    | add y z _ _ hy hz => exact hy.add_right hz
    | smul r y _ hy => exact hy.smul_right r
  | zero => exact Commute.zero_left _
  | add x z _ _ hx hz => exact hx.add_left hz
  | smul r x _ hx => exact hx.smul_left r

end Defect

/-! ## Matrix units and their spatial form -/

section Units

variable {ι K : Type} [Fintype ι] [DecidableEq ι] [Fintype K] [DecidableEq K]

/-- A system of `*`-matrix units `u a b` in `M_K(ℂ)` summing to the identity. -/
structure MatUnits (u : ι → ι → Matrix K K ℂ) : Prop where
  mul : ∀ a b c d, u a b * u c d = if b = c then u a d else 0
  star : ∀ a b, (u a b)ᴴ = u b a
  sum : ∑ a, u a a = 1

/-- The linear extension `M ↦ ∑ M_{ab} u_{ab}`. -/
noncomputable def unitsLift (u : ι → ι → Matrix K K ℂ) (M : Matrix ι ι ℂ) : Matrix K K ℂ :=
  ∑ a, ∑ b, M a b • u a b

namespace MatUnits

variable {u : ι → ι → Matrix K K ℂ} (hu : MatUnits u)
include hu

theorem lift_mul (M N : Matrix ι ι ℂ) :
    unitsLift u (M * N) = unitsLift u M * unitsLift u N := by
  have hrow : ∀ a b, (M a b • u a b) * unitsLift u N = ∑ d, (M a b * N b d) • u a d := by
    intro a b
    simp only [unitsLift, Finset.mul_sum, smul_mul_smul_comm, hu.mul, smul_ite, smul_zero]
    rw [Finset.sum_comm]
    simp only [Finset.sum_ite_eq, Finset.mem_univ, if_true]
  show _ = (∑ a, ∑ b, M a b • u a b) * unitsLift u N
  simp only [Finset.sum_mul, hrow]
  simp only [unitsLift, mul_apply, Finset.sum_smul]
  refine Finset.sum_congr rfl fun a _ => ?_
  rw [Finset.sum_comm]

theorem lift_one : unitsLift u (1 : Matrix ι ι ℂ) = 1 := by
  simp only [unitsLift, one_apply, ite_smul, one_smul, zero_smul, Finset.sum_ite_eq,
    Finset.mem_univ, if_true]
  exact hu.sum

theorem lift_add (M N : Matrix ι ι ℂ) : unitsLift u (M + N) = unitsLift u M + unitsLift u N := by
  simp only [unitsLift, Matrix.add_apply, add_smul, Finset.sum_add_distrib]

theorem lift_smul (r : ℂ) (M : Matrix ι ι ℂ) : unitsLift u (r • M) = r • unitsLift u M := by
  simp only [unitsLift, Matrix.smul_apply, smul_eq_mul, Finset.smul_sum, smul_smul]

theorem lift_star (M : Matrix ι ι ℂ) : unitsLift u Mᴴ = (unitsLift u M)ᴴ := by
  simp only [unitsLift, conjTranspose_sum, conjTranspose_smul, hu.star, conjTranspose_apply]
  rw [Finset.sum_comm]

/-- The unital `*`-homomorphism induced by a system of matrix units. -/
noncomputable def toStarAlgHom : Matrix ι ι ℂ →⋆ₐ[ℂ] Matrix K K ℂ where
  toFun := unitsLift u
  map_one' := hu.lift_one
  map_mul' := hu.lift_mul
  map_zero' := by simp [unitsLift]
  map_add' := hu.lift_add
  commutes' r := by
    rw [Algebra.algebraMap_eq_smul_one, Algebra.algebraMap_eq_smul_one, hu.lift_smul, hu.lift_one]
  map_star' M := by
    rw [star_eq_conjTranspose, star_eq_conjTranspose]
    exact hu.lift_star M

theorem toStarAlgHom_apply (M : Matrix ι ι ℂ) : hu.toStarAlgHom M = unitsLift u M := rfl

theorem corner (i₀ a b : ι) (M : Matrix ι ι ℂ) :
    u i₀ a * unitsLift u M * u b i₀ = M a b • u i₀ i₀ := by
  have key : ∀ c d, u i₀ a * u c d * u b i₀ = if c = a ∧ d = b then u i₀ i₀ else 0 := by
    intro c d
    rw [hu.mul]
    by_cases h1 : a = c
    · subst h1
      rw [if_pos rfl, hu.mul]
      by_cases h2 : d = b
      · subst h2; simp
      · simp [h2]
    · rw [if_neg h1, Matrix.zero_mul, if_neg (fun h => h1 h.1.symm)]
  simp only [unitsLift, Finset.mul_sum, Finset.sum_mul, mul_smul_comm, smul_mul_assoc, key,
    smul_ite, smul_zero]
  rw [Finset.sum_eq_single a (fun c _ hc => Finset.sum_eq_zero fun d _ => by simp [hc])
    (by simp)]
  rw [Finset.sum_eq_single b (fun d _ hd => by simp [hd]) (by simp)]
  simp

/-- **Spatial form.**  A system of matrix units is unitarily equivalent to the amplified
standard representation: there are a finite multiplicity type `J` and a unitary
`W : ℂ^{ι × J} → ℂ^K` with `W* (∑ M_{ab} u_{ab}) W = M ⊗ I_J`. -/
theorem spatial [Nonempty ι] :
    ∃ (J : Type) (_ : Fintype J) (_ : DecidableEq J) (W : Matrix K (ι × J) ℂ),
      Wᴴ * W = 1 ∧ W * Wᴴ = 1 ∧
      ∀ M : Matrix ι ι ℂ, Wᴴ * unitsLift u M * W = M ⊗ₖ (1 : Matrix J J ℂ) := by
  classical
  obtain ⟨i₀⟩ := (inferInstance : Nonempty ι)
  have hqh : (u i₀ i₀)ᴴ = u i₀ i₀ := hu.star i₀ i₀
  have hqq : u i₀ i₀ * u i₀ i₀ = u i₀ i₀ := by rw [hu.mul]; simp
  obtain ⟨J, hJf, hJd, E, hE1, hE2⟩ := projection_factor (u i₀ i₀) hqh hqq
  let _ := hJf
  let _ := hJd
  let W : Matrix K (ι × J) ℂ := of fun r p => (u p.1 i₀ * E) r p.2
  have hconj : ∀ (X : Matrix K K ℂ) (a b : ι) (k l : J),
      (Wᴴ * X * W) (a, k) (b, l) = ((u a i₀ * E)ᴴ * X * (u b i₀ * E)) k l := by
    intro X a b k l
    simp only [W, mul_apply, conjTranspose_apply, of_apply]
  have hEqE : Eᴴ * u i₀ i₀ * E = 1 := by
    rw [← hE2, ← Matrix.mul_assoc, hE1, Matrix.one_mul, hE1]
  have hcore : ∀ (X : Matrix K K ℂ) (a b : ι),
      (u a i₀ * E)ᴴ * X * (u b i₀ * E) = Eᴴ * (u i₀ a * X * u b i₀) * E := by
    intro X a b
    rw [conjTranspose_mul, hu.star]
    simp only [Matrix.mul_assoc]
  have hlift : ∀ M : Matrix ι ι ℂ, Wᴴ * unitsLift u M * W = M ⊗ₖ (1 : Matrix J J ℂ) := by
    intro M
    ext ⟨a, k⟩ ⟨b, l⟩
    rw [hconj, hcore, hu.corner, Matrix.mul_smul, Matrix.smul_mul, hEqE]
    simp [kroneckerMap_apply]
  refine ⟨J, hJf, hJd, W, ?_, ?_, hlift⟩
  · have h := hlift 1
    rw [hu.lift_one, Matrix.mul_one, one_kronecker_one] at h
    exact h
  · ext r s
    have hWW : (W * Wᴴ) r s = ∑ a, ((u a i₀ * E) * (u a i₀ * E)ᴴ) r s := by
      simp only [W, mul_apply, conjTranspose_apply, of_apply, Fintype.sum_prod_type]
    rw [hWW]
    have hterm : ∀ a, (u a i₀ * E) * (u a i₀ * E)ᴴ = u a a := by
      intro a
      rw [conjTranspose_mul, hu.star, Matrix.mul_assoc, ← Matrix.mul_assoc E, hE2, hu.mul,
        if_pos rfl, hu.mul, if_pos rfl]
    simp only [hterm]
    rw [← Matrix.sum_apply, hu.sum]

end MatUnits

end Units

/-! ## The aligned tensor product of the three factors -/

section Alignment

variable {K : Type} [Fintype K] [DecidableEq K]

theorem sum_single_diag {n : Type} [Fintype n] [DecidableEq n] :
    ∑ i : n, (single i i (1 : ℂ) : Matrix n n ℂ) = 1 := by
  ext a b
  simp only [Matrix.sum_apply, single_apply, one_apply]
  by_cases h : a = b
  · subst h; simp
  · simp [h]

theorem single_mul_single' {n : Type} [Fintype n] [DecidableEq n] (i j k l : n) :
    (single i j (1 : ℂ) : Matrix n n ℂ) * single k l 1 = if j = k then single i l 1 else 0 := by
  by_cases h : j = k
  · subst h; simp
  · rw [if_neg h]; exact Matrix.single_mul_single_of_ne (c := (1 : ℂ)) i j k h 1

theorem rearrange {a b c a' b' c' : Matrix K K ℂ} (hba : Commute b a') (hca : Commute c a')
    (hcb : Commute c b') : a * b * c * (a' * b' * c') = a * a' * (b * b') * (c * c') := by
  simp only [Matrix.mul_assoc]
  rw [hca.left_comm, hba.left_comm, hcb.left_comm]

variable (φC : Matrix (Fin 3) (Fin 3) ℂ →⋆ₐ[ℂ] Matrix K K ℂ)
  (φ₁ φ₂ : Matrix (Fin 2) (Fin 2) ℂ →⋆ₐ[ℂ] Matrix K K ℂ)

/-- The index type of `M₃ ⊗ M₂ ⊗ M₂ ≅ M₁₂`. -/
abbrev TensorIdx := Fin 3 × Fin 2 × Fin 2

/-- Products of the factor matrix units. -/
noncomputable def tensorUnits (p q : TensorIdx) : Matrix K K ℂ :=
  φC (single p.1 q.1 1) * φ₁ (single p.2.1 q.2.1 1) * φ₂ (single p.2.2 q.2.2 1)

theorem phi_single_mul {n : Type} [Fintype n] [DecidableEq n]
    (φ : Matrix n n ℂ →⋆ₐ[ℂ] Matrix K K ℂ) (i j k l : n) :
    φ (single i j 1) * φ (single k l 1) = if j = k then φ (single i l 1) else 0 := by
  rw [← map_mul, single_mul_single']
  split_ifs <;> simp

theorem phi_single_star {n : Type} [Fintype n] [DecidableEq n]
    (φ : Matrix n n ℂ →⋆ₐ[ℂ] Matrix K K ℂ) (i j : n) :
    (φ (single i j 1))ᴴ = φ (single j i 1) := by
  rw [← star_eq_conjTranspose, ← map_star, star_eq_conjTranspose, conjTranspose_single]
  simp

theorem phi_sum_single {n : Type} [Fintype n] [DecidableEq n]
    (φ : Matrix n n ℂ →⋆ₐ[ℂ] Matrix K K ℂ) : ∑ i, φ (single i i 1) = 1 := by
  rw [← map_sum, sum_single_diag, map_one]

/-- The factor matrix units commute pairwise on the aligned branch, and their products form
a `12 × 12` system of `*`-matrix units. -/
theorem tensorUnits_matUnits (hC1 : ∀ X Y, Commute (φC X) (φ₁ Y))
    (hC2 : ∀ X Z, Commute (φC X) (φ₂ Z)) (h12 : ∀ Y Z, Commute (φ₁ Y) (φ₂ Z)) :
    MatUnits (tensorUnits φC φ₁ φ₂) := by
  refine ⟨?_, ?_, ?_⟩
  · rintro ⟨i, k, m⟩ ⟨j, l, n⟩ ⟨i', k', m'⟩ ⟨j', l', n'⟩
    simp only [tensorUnits]
    rw [rearrange (hC1 _ _).symm (hC2 _ _).symm (h12 _ _).symm, phi_single_mul, phi_single_mul,
      phi_single_mul]
    by_cases h1 : j = i' <;> by_cases h2 : l = k' <;> by_cases h3 : n = m' <;>
      simp [h1, h2, h3]
  · rintro ⟨i, k, m⟩ ⟨j, l, n⟩
    simp only [tensorUnits, conjTranspose_mul, phi_single_star]
    rw [← (hC1 _ _).eq, ← Matrix.mul_assoc, ← (hC2 _ _).eq, Matrix.mul_assoc, ← (h12 _ _).eq,
      ← Matrix.mul_assoc]
  · simp only [tensorUnits, Fintype.sum_prod_type]
    simp only [← Finset.mul_sum, ← Finset.sum_mul]
    rw [phi_sum_single, phi_sum_single, phi_sum_single, Matrix.one_mul, Matrix.one_mul]

theorem phi_eq_sum {n : Type} [Fintype n] [DecidableEq n]
    (φ : Matrix n n ℂ →⋆ₐ[ℂ] Matrix K K ℂ) (X : Matrix n n ℂ) :
    φ X = ∑ i, ∑ j, X i j • φ (single i j 1) := by
  conv_lhs => rw [matrix_eq_sum_single X]
  simp only [map_sum]
  refine Finset.sum_congr rfl fun i _ => Finset.sum_congr rfl fun j _ => ?_
  rw [← map_smul, smul_single, smul_eq_mul, mul_one]

/-- The coordinate permutation `(i,k,m,j,l,n) ↦ (m,n,k,l,i,j)`. -/
def reorderEquiv : (Fin 3 × Fin 2 × Fin 2 × Fin 3 × Fin 2 × Fin 2) ≃
    (Fin 2 × Fin 2 × Fin 2 × Fin 2 × Fin 3 × Fin 3) where
  toFun q := (q.2.2.1, q.2.2.2.2.2, q.2.1, q.2.2.2.2.1, q.1, q.2.2.2.1)
  invFun q := (q.2.2.2.2.1, q.2.2.1, q.1, q.2.2.2.2.2, q.2.2.2.1, q.2.1)
  left_inv _ := rfl
  right_inv _ := rfl

theorem reorder6 {α : Type*} [AddCommMonoid α]
    (F : Fin 3 → Fin 2 → Fin 2 → Fin 3 → Fin 2 → Fin 2 → α) :
    ∑ i, ∑ k, ∑ m, ∑ j, ∑ l, ∑ n, F i k m j l n =
      ∑ m, ∑ n, ∑ k, ∑ l, ∑ i, ∑ j, F i k m j l n := by
  have h1 : ∑ i, ∑ k, ∑ m, ∑ j, ∑ l, ∑ n, F i k m j l n =
      ∑ q : Fin 3 × Fin 2 × Fin 2 × Fin 3 × Fin 2 × Fin 2,
        F q.1 q.2.1 q.2.2.1 q.2.2.2.1 q.2.2.2.2.1 q.2.2.2.2.2 := by
    simp only [Fintype.sum_prod_type]
  have h2 : ∑ m, ∑ n, ∑ k, ∑ l, ∑ i, ∑ j, F i k m j l n =
      ∑ q : Fin 2 × Fin 2 × Fin 2 × Fin 2 × Fin 3 × Fin 3,
        F q.2.2.2.2.1 q.2.2.1 q.1 q.2.2.2.2.2 q.2.2.2.1 q.2.1 := by
    simp only [Fintype.sum_prod_type]
  rw [h1, h2]
  exact Fintype.sum_equiv reorderEquiv _ _ (fun q => rfl)

/-- Multiplication on elementary tensors. -/
theorem unitsLift_kronecker (X : Matrix (Fin 3) (Fin 3) ℂ) (Y Z : Matrix (Fin 2) (Fin 2) ℂ) :
    unitsLift (tensorUnits φC φ₁ φ₂) (X ⊗ₖ (Y ⊗ₖ Z)) = φC X * φ₁ Y * φ₂ Z := by
  rw [phi_eq_sum φC X, phi_eq_sum φ₁ Y, phi_eq_sum φ₂ Z]
  simp only [Finset.sum_mul, Finset.mul_sum, smul_mul_smul_comm]
  simp only [unitsLift, tensorUnits, Fintype.sum_prod_type, kroneckerMap_apply, ← mul_assoc]
  exact reorder6 (fun i k m j l n => (X i j * Y k l * Z m n) •
    (φC (single i j 1) * φ₁ (single k l 1) * φ₂ (single m n 1)))

/-- **Same-carrier tensor-factor alignment (`thm:tensor-factor-alignment`).**
Let `φ_C : M₃(ℂ) → B(𝒦)`, `φ₁, φ₂ : M₂(ℂ) → B(𝒦)` be unital `*`-homomorphisms on a nonzero
finite-dimensional carrier, and let `C`, `W₁`, `W₂` be Hermitian families lying in, and
spanning, the three represented factor algebras.  Then:
1. `Δ_⊗ = 0` iff the three represented factor algebras commute pairwise;
2. on this branch there is an injective unital `*`-homomorphism
   `Ψ : M₃ ⊗ M₂ ⊗ M₂ (= M_{Fin 3 × Fin 2 × Fin 2}(ℂ) ≅ M₁₂(ℂ)) → B(𝒦)` with
   `Ψ(X ⊗ Y ⊗ Z) = φ_C(X) φ₁(Y) φ₂(Z)`, whose range is the algebra generated by the three
   factors;
3. there are a finite multiplicity type `M` and a unitary `W` with
   `W* Ψ(A) W = A ⊗ I_M` for all `A`, so the generated algebra is unitarily equivalent to
   `M₁₂(ℂ) ⊗ I_M`. -/
theorem tensor_factor_alignment [Nonempty K] {ια ιβ ιγ : Type} [Fintype ια] [Fintype ιβ]
    [Fintype ιγ] (C : ια → Matrix K K ℂ) (W₁ : ιβ → Matrix K K ℂ) (W₂ : ιγ → Matrix K K ℂ)
    (_hCh : ∀ a, (C a)ᴴ = C a) (_hW₁h : ∀ b, (W₁ b)ᴴ = W₁ b) (_hW₂h : ∀ c, (W₂ c)ᴴ = W₂ c)
    (hC : ∀ a, C a ∈ Set.range φC) (hW₁ : ∀ b, W₁ b ∈ Set.range φ₁)
    (hW₂ : ∀ c, W₂ c ∈ Set.range φ₂)
    (hCs : ∀ X, φC X ∈ Submodule.span ℂ (Set.range C))
    (hW₁s : ∀ Y, φ₁ Y ∈ Submodule.span ℂ (Set.range W₁))
    (hW₂s : ∀ Z, φ₂ Z ∈ Submodule.span ℂ (Set.range W₂)) :
    (alignDefect C W₁ W₂ = 0 ↔
      (∀ X Y, Commute (φC X) (φ₁ Y)) ∧ (∀ X Z, Commute (φC X) (φ₂ Z)) ∧
        (∀ Y Z, Commute (φ₁ Y) (φ₂ Z))) ∧
    (alignDefect C W₁ W₂ = 0 →
      ∃ Ψ : Matrix TensorIdx TensorIdx ℂ →⋆ₐ[ℂ] Matrix K K ℂ,
        Function.Injective Ψ ∧
        (∀ X Y Z, Ψ (X ⊗ₖ (Y ⊗ₖ Z)) = φC X * φ₁ Y * φ₂ Z) ∧
        Set.range Ψ = (Algebra.adjoin ℂ
          (Set.range φC ∪ Set.range φ₁ ∪ Set.range φ₂) : Set (Matrix K K ℂ)) ∧
        ∃ (M : Type) (_ : Fintype M) (_ : DecidableEq M) (W : Matrix K (TensorIdx × M) ℂ),
          Wᴴ * W = 1 ∧ W * Wᴴ = 1 ∧
          ∀ A : Matrix TensorIdx TensorIdx ℂ, Wᴴ * Ψ A * W = A ⊗ₖ (1 : Matrix M M ℂ)) := by
  -- Part 1
  have hiff : alignDefect C W₁ W₂ = 0 ↔
      (∀ X Y, Commute (φC X) (φ₁ Y)) ∧ (∀ X Z, Commute (φC X) (φ₂ Z)) ∧
        (∀ Y Z, Commute (φ₁ Y) (φ₂ Z)) := by
    have e1 := sum_hsNormSq_eq_zero_iff (fun a b => C a * W₁ b - W₁ b * C a)
    have e2 := sum_hsNormSq_eq_zero_iff (fun a c => C a * W₂ c - W₂ c * C a)
    have e3 := sum_hsNormSq_eq_zero_iff (fun b c => W₁ b * W₂ c - W₂ c * W₁ b)
    have n1 : 0 ≤ ∑ a, ∑ b, hsNormSq (C a * W₁ b - W₁ b * C a) :=
      Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => hsNormSq_nonneg _
    have n2 : 0 ≤ ∑ a, ∑ c, hsNormSq (C a * W₂ c - W₂ c * C a) :=
      Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => hsNormSq_nonneg _
    have n3 : 0 ≤ ∑ b, ∑ c, hsNormSq (W₁ b * W₂ c - W₂ c * W₁ b) :=
      Finset.sum_nonneg fun _ _ => Finset.sum_nonneg fun _ _ => hsNormSq_nonneg _
    have hsplit : alignDefect C W₁ W₂ = 0 ↔
        (∑ a, ∑ b, hsNormSq (C a * W₁ b - W₁ b * C a) = 0 ∧
          ∑ a, ∑ c, hsNormSq (C a * W₂ c - W₂ c * C a) = 0 ∧
          ∑ b, ∑ c, hsNormSq (W₁ b * W₂ c - W₂ c * W₁ b) = 0) := by
      unfold alignDefect
      constructor
      · intro h
        refine ⟨by linarith, by linarith, by linarith⟩
      · rintro ⟨h1, h2, h3⟩
        rw [h1, h2, h3]; norm_num
    rw [hsplit, e1, e2, e3]
    simp only [sub_eq_zero]
    constructor
    · rintro ⟨h1, h2, h3⟩
      exact ⟨fun X Y => commute_of_span C W₁ h1 (hCs X) (hW₁s Y),
        fun X Z => commute_of_span C W₂ h2 (hCs X) (hW₂s Z),
        fun Y Z => commute_of_span W₁ W₂ h3 (hW₁s Y) (hW₂s Z)⟩
    · rintro ⟨h1, h2, h3⟩
      refine ⟨fun a b => ?_, fun a c => ?_, fun b c => ?_⟩
      · obtain ⟨X, hX⟩ := hC a; obtain ⟨Y, hY⟩ := hW₁ b
        rw [← hX, ← hY]; exact (h1 X Y).eq
      · obtain ⟨X, hX⟩ := hC a; obtain ⟨Z, hZ⟩ := hW₂ c
        rw [← hX, ← hZ]; exact (h2 X Z).eq
      · obtain ⟨Y, hY⟩ := hW₁ b; obtain ⟨Z, hZ⟩ := hW₂ c
        rw [← hY, ← hZ]; exact (h3 Y Z).eq
  refine ⟨hiff, fun h0 => ?_⟩
  obtain ⟨h1, h2, h3⟩ := hiff.mp h0
  have hu := tensorUnits_matUnits φC φ₁ φ₂ h1 h2 h3
  let Ψ := hu.toStarAlgHom
  have hΨ : ∀ X Y Z, Ψ (X ⊗ₖ (Y ⊗ₖ Z)) = φC X * φ₁ Y * φ₂ Z := fun X Y Z =>
    unitsLift_kronecker φC φ₁ φ₂ X Y Z
  have hinj : Function.Injective Ψ := by
    haveI : Nontrivial (Matrix K K ℂ) := inferInstance
    exact RingHom.injective (Ψ : Matrix TensorIdx TensorIdx ℂ →+* Matrix K K ℂ)
  refine ⟨Ψ, hinj, hΨ, ?_, ?_⟩
  · -- range = generated algebra
    apply Set.Subset.antisymm
    · rintro _ ⟨A, rfl⟩
      show unitsLift (tensorUnits φC φ₁ φ₂) A ∈ Algebra.adjoin ℂ _
      refine Subalgebra.sum_mem _ fun p _ => Subalgebra.sum_mem _ fun q _ =>
        Subalgebra.smul_mem _ ?_ _
      refine Subalgebra.mul_mem _ (Subalgebra.mul_mem _ ?_ ?_) ?_ <;>
        apply Algebra.subset_adjoin
      · exact Or.inl (Or.inl ⟨_, rfl⟩)
      · exact Or.inl (Or.inr ⟨_, rfl⟩)
      · exact Or.inr ⟨_, rfl⟩
    · have hle : Algebra.adjoin ℂ (Set.range φC ∪ Set.range φ₁ ∪ Set.range φ₂) ≤
          (Ψ : Matrix TensorIdx TensorIdx ℂ →ₐ[ℂ] Matrix K K ℂ).range := by
        rw [Algebra.adjoin_le_iff]
        rintro _ ((⟨X, rfl⟩ | ⟨Y, rfl⟩) | ⟨Z, rfl⟩)
        · refine ⟨X ⊗ₖ ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)), ?_⟩
          show Ψ _ = _
          rw [hΨ, map_one, map_one, Matrix.mul_one, Matrix.mul_one]
        · refine ⟨(1 : Matrix (Fin 3) (Fin 3) ℂ) ⊗ₖ (Y ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)), ?_⟩
          show Ψ _ = _
          rw [hΨ, map_one, map_one, Matrix.mul_one, Matrix.one_mul]
        · refine ⟨(1 : Matrix (Fin 3) (Fin 3) ℂ) ⊗ₖ ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ Z), ?_⟩
          show Ψ _ = _
          rw [hΨ, map_one, map_one, Matrix.one_mul, Matrix.one_mul]
      intro x hx
      obtain ⟨A, hA⟩ := hle hx
      exact ⟨A, hA⟩
  · obtain ⟨M, hMf, hMd, W, hW1, hW2, hW3⟩ := hu.spatial
    exact ⟨M, hMf, hMd, W, hW1, hW2, fun A => hW3 A⟩

end Alignment

end TensorFactorAlignment
end RenewalGeometry
