/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Algebra.CliffordConcrete

/-!
# The Clifford system generates the full matrix factor

The identification clause of `thm:common-origin-clifford`
(`manuscripts/renewal_emergence/renewal_emergence.tex`): the algebra generated by the four
Hermitian Clifford generators is **all** of `M₄(ℂ)` —

`Algebra.adjoin ℂ (range Γ) = ⊤`  (`gamma_generates`).

Together with the Clifford relations (`gamma_clifford`) and
irreducibility (`gamma_commutant`) this is the concrete rendering of
`ℂ_σ[F₂⁴] ≅ Cl₄(ℂ) ≅ M₄(ℂ)`: the sixteen Pauli–Kronecker monomials
are a **trace-orthogonal basis** of `M₄(ℂ)`
(`pauliKron_linearIndependent`, `pauliKron_span`), and every basis
element is an explicit scalar multiple of a product of the `Γ_μ`
(`pauliKron_mem_adjoin`).
-/

namespace NCG.CommonOrigin

open Matrix Kronecker

/-- The Pauli family including the identity. -/
def pauli4 : Fin 4 → Matrix (Fin 2) (Fin 2) ℂ :=
  ![1, pauli1, pauli2, pauli3]

/-- The trace-orthogonality table of the Pauli family:
`Tr(σ_p σ_q) = 2δ_{pq}`. -/
theorem pauli4_trace_mul (p q : Fin 4) :
    (pauli4 p * pauli4 q).trace = if p = q then 2 else 0 := by
  fin_cases p <;> fin_cases q <;>
    simp [pauli4, pauli1, pauli2, pauli3, Matrix.trace,
      Matrix.diag, Matrix.mul_apply, Fin.sum_univ_two,
      Matrix.one_apply, Complex.I_mul_I] <;>
    norm_num

/-- The sixteen Pauli–Kronecker monomials. -/
def pauliKron : Fin 4 × Fin 4 →
    Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ :=
  fun pq => pauli4 pq.1 ⊗ₖ pauli4 pq.2

/-- Trace orthogonality of the monomials: `Tr(K_x K_y) = 4δ_{xy}`. -/
theorem pauliKron_trace_mul (x y : Fin 4 × Fin 4) :
    (pauliKron x * pauliKron y).trace
      = if x = y then 4 else 0 := by
  rcases x with ⟨p, q⟩
  rcases y with ⟨p', q'⟩
  rw [pauliKron, pauliKron, ← Matrix.mul_kronecker_mul,
    Matrix.trace_kronecker, pauli4_trace_mul, pauli4_trace_mul]
  by_cases h1 : p = p'
  · by_cases h2 : q = q'
    · rw [if_pos h1, if_pos h2,
        if_pos (Prod.ext_iff.mpr ⟨h1, h2⟩)]
      norm_num
    · rw [if_pos h1, if_neg h2,
        if_neg (fun h => h2 (Prod.ext_iff.mp h).2), mul_zero]
  · rw [if_neg h1, if_neg (fun h => h1 (Prod.ext_iff.mp h).1),
      zero_mul]

/-- **Linear independence** of the sixteen monomials, by pairing
against the trace form. -/
theorem pauliKron_linearIndependent :
    LinearIndependent ℂ pauliKron := by
  rw [Fintype.linearIndependent_iff]
  intro g hg x
  have h1 : ((∑ y, g y • pauliKron y) * pauliKron x).trace = 0 := by
    rw [hg, Matrix.zero_mul, Matrix.trace_zero]
  rw [Finset.sum_mul, Matrix.trace_sum] at h1
  have h2 : ∀ y : Fin 4 × Fin 4,
      ((g y • pauliKron y) * pauliKron x).trace
        = (if y = x then g y * 4 else 0) := by
    intro y
    rw [Matrix.smul_mul, Matrix.trace_smul, smul_eq_mul,
      pauliKron_trace_mul]
    by_cases h : y = x
    · rw [if_pos h, if_pos h]
    · rw [if_neg h, if_neg h, mul_zero]
  rw [Finset.sum_congr rfl fun y _ => h2 y,
    Finset.sum_ite_eq' Finset.univ x (fun y => g y * 4),
    if_pos (Finset.mem_univ x)] at h1
  have h3 := mul_eq_zero.mp h1
  rcases h3 with h3 | h3
  · exact h3
  · exact absurd h3 (by norm_num)

/-- **The monomials span `M₄(ℂ)`** (sixteen independent vectors in a
sixteen-dimensional space). -/
theorem pauliKron_span :
    Submodule.span ℂ (Set.range pauliKron) = ⊤ := by
  refine pauliKron_linearIndependent.span_eq_top_of_card_eq_finrank
    ?_
  rw [Module.finrank_matrix]
  simp

/-- Every Pauli–Kronecker monomial lies in the algebra generated by
the Clifford system (explicit products and scalars). -/
theorem pauliKron_mem_adjoin (x : Fin 4 × Fin 4) :
    pauliKron x ∈ Algebra.adjoin ℂ (Set.range gamma) := by
  set S := Algebra.adjoin ℂ (Set.range gamma) with hS
  have hg : ∀ μ : Fin 4, gamma μ ∈ S :=
    fun μ => Algebra.subset_adjoin ⟨μ, rfl⟩
  -- first-factor Paulis
  have h10 : pauli1 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ S := hg 0
  have h20 : pauli2 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ S := hg 1
  have hprod01 : gamma 0 * gamma 1
      = Complex.I • (pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ))
      := by
    show pauli1 ⊗ₖ 1 * (pauli2 ⊗ₖ 1)
      = Complex.I • (pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ))
    rw [← Matrix.mul_kronecker_mul, Matrix.one_mul,
      pauli12_eq_I_pauli3, Matrix.smul_kronecker]
  have h30 : pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ S := by
    have h4 : pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)
        = (-Complex.I) • (gamma 0 * gamma 1) := by
      rw [hprod01, smul_smul]
      rw [show -Complex.I * Complex.I = 1 from by
        rw [neg_mul, Complex.I_mul_I, neg_neg], one_smul]
    rw [h4]
    exact Subalgebra.smul_mem S (mul_mem (hg 0) (hg 1)) _
  -- second-factor Paulis
  have h01 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli1 ∈ S := by
    have h4 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli1
        = (pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)) * gamma 2
        := by
      show (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli1
        = pauli3 ⊗ₖ 1 * (pauli3 ⊗ₖ pauli1)
      rw [← Matrix.mul_kronecker_mul, pauli3_sq, Matrix.one_mul]
    rw [h4]
    exact mul_mem h30 (hg 2)
  have h02 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli2 ∈ S := by
    have h4 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli2
        = (pauli3 ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)) * gamma 3
        := by
      show (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli2
        = pauli3 ⊗ₖ 1 * (pauli3 ⊗ₖ pauli2)
      rw [← Matrix.mul_kronecker_mul, pauli3_sq, Matrix.one_mul]
    rw [h4]
    exact mul_mem h30 (hg 3)
  have h03 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli3 ∈ S := by
    have h4 : ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli1)
        * ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli2)
        = Complex.I
          • ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli3) := by
      rw [← Matrix.mul_kronecker_mul, Matrix.one_mul,
        pauli12_eq_I_pauli3, Matrix.kronecker_smul]
    have h5 : (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli3
        = (-Complex.I)
          • (((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli1)
            * ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli2)) := by
      rw [h4, smul_smul]
      rw [show -Complex.I * Complex.I = 1 from by
        rw [neg_mul, Complex.I_mul_I, neg_neg], one_smul]
    rw [h5]
    exact Subalgebra.smul_mem S (mul_mem h01 h02) _
  -- identity factors
  have hA : ∀ p : Fin 4,
      pauli4 p ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ S := by
    intro p
    fin_cases p
    · show (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ 1 ∈ S
      rw [Matrix.one_kronecker_one]
      exact one_mem S
    · exact h10
    · exact h20
    · exact h30
  have hB : ∀ q : Fin 4,
      (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli4 q ∈ S := by
    intro q
    fin_cases q
    · show (1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ 1 ∈ S
      rw [Matrix.one_kronecker_one]
      exact one_mem S
    · exact h01
    · exact h02
    · exact h03
  rcases x with ⟨p, q⟩
  have hsplit : pauliKron (p, q)
      = (pauli4 p ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ))
        * ((1 : Matrix (Fin 2) (Fin 2) ℂ) ⊗ₖ pauli4 q) := by
    rw [pauliKron, ← Matrix.mul_kronecker_mul, Matrix.mul_one,
      Matrix.one_mul]
  rw [hsplit]
  exact mul_mem (hA p) (hB q)

/-- **Theorem `thm:common-origin-clifford` (identification)**: the
Clifford system generates the full matrix factor,
`⟨Γ₀,Γ₁,Γ₂,Γ₃⟩ = M₄(ℂ)`. -/
theorem gamma_generates :
    Algebra.adjoin ℂ (Set.range gamma) = ⊤ := by
  rw [eq_top_iff]
  intro X _
  have h1 : Submodule.span ℂ (Set.range pauliKron)
      ≤ Subalgebra.toSubmodule (Algebra.adjoin ℂ
          (Set.range gamma)) := by
    rw [Submodule.span_le]
    rintro Z ⟨x, rfl⟩
    exact pauliKron_mem_adjoin x
  have h2 : X ∈ Submodule.span ℂ (Set.range pauliKron) := by
    rw [pauliKron_span]
    exact Submodule.mem_top
  exact h1 h2

end NCG.CommonOrigin
