/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Algebra.CliffordGenerates

/-!
# The marked factor is the left Kronecker factor

The finite Stone–von Neumann identification used by
`thm:external-core` (flagship), realized concretely: inside the total
algebra `M_I(ℂ) ⊗ M_J(ℂ) = Matrix (I × J)` (Kronecker model),

* `left_factor_commutant` — anything commuting with the whole left
  factor `{g ⊗ 1}` is of the form `1 ⊗ B` (the commutant of the
  external factor is exactly the internal complement);
* `commutes_of_commutes_gamma` — commuting with the four **marked
  generators** `Γ_μ ⊗ 1` already forces commuting with the whole left
  factor, by `gamma_generates` and adjoin induction;
* `marked_commutant` — hence the commutant of the marked generators
  is exactly `1 ⊗ M_J`;
* `leftKron` / `marked_adjoin_eq_leftKron_range` — the algebra
  generated by the marked generators is exactly the left tensor
  factor `M_I ⊗ 1` (the range of `g ↦ g ⊗ 1`).

Together with the abstract tensor split `NCG.externalFactorSplit`
this discharges the "identification of the marked generators with
the left tensor factor" step of `thm:external-core`: the marked
external algebra **is** the `M₄` factor and its commutant **is** the
internal complement.  (The fully abstract Skolem–Noether/Stone–von
Neumann uniqueness — any two irreducible realizations are unitarily
conjugate — remains outside current Mathlib; the realized model
proved here is what the flagship theorem chain consumes.)
-/

namespace NCG.CommonOrigin

open Matrix Kronecker

variable {I : Type*} [Fintype I] [DecidableEq I]
variable {J : Type*} [Fintype J] [DecidableEq J]

/-- Entry identity extracted from commutation with a matrix unit of
the left factor: for every `a c b j l`,
`X (c,j) (b,l) = if b = c then X (a,j) (a,l) else 0`. -/
theorem entry_of_single_comm (X : Matrix (I × J) (I × J) ℂ)
    (hX : ∀ g : Matrix I I ℂ,
      (g ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (g ⊗ₖ 1))
    (a c b : I) (j l : J) :
    X (c, j) (b, l) = if b = c then X (a, j) (a, l) else 0 := by
  have h := congrFun (congrFun (hX (single a c 1)) (a, j)) (b, l)
  have hL : ((single a c (1:ℂ) ⊗ₖ (1 : Matrix J J ℂ)) * X)
      (a, j) (b, l) = X (c, j) (b, l) := by
    rw [Matrix.mul_apply, Fintype.sum_prod_type]
    simp only [kroneckerMap_apply, Matrix.single_apply,
      Matrix.one_apply]
    simp [Finset.sum_ite_eq]
  have hR : (X * (single a c (1:ℂ) ⊗ₖ (1 : Matrix J J ℂ)))
      (a, j) (b, l) = if b = c then X (a, j) (a, l) else 0 := by
    rw [Matrix.mul_apply, Fintype.sum_prod_type]
    simp only [kroneckerMap_apply, Matrix.single_apply,
      Matrix.one_apply]
    simp [Finset.sum_ite_eq, ite_and, eq_comm]
  rw [hL, hR] at h
  exact h

/-- **Left-factor commutant**: an element commuting with the whole
left Kronecker factor `{g ⊗ 1}` lies in the right factor `1 ⊗ M_J`. -/
theorem left_factor_commutant [Nonempty I]
    (X : Matrix (I × J) (I × J) ℂ)
    (hX : ∀ g : Matrix I I ℂ,
      (g ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (g ⊗ₖ 1)) :
    ∃ B : Matrix J J ℂ, X = (1 : Matrix I I ℂ) ⊗ₖ B := by
  obtain ⟨a₀⟩ := (inferInstance : Nonempty I)
  refine ⟨Matrix.of fun j l => X (a₀, j) (a₀, l), ?_⟩
  ext ⟨c, j⟩ ⟨b, l⟩
  rw [kroneckerMap_apply, Matrix.one_apply,
    entry_of_single_comm X hX a₀ c b j l]
  by_cases hcb : b = c
  · subst hcb
    simp
  · simp [hcb, Ne.symm hcb]

/-- The converse inclusion: right-factor elements commute with the
left factor. -/
theorem kron_right_commutes (g : Matrix I I ℂ) (B : Matrix J J ℂ) :
    (g ⊗ₖ (1 : Matrix J J ℂ)) * ((1 : Matrix I I ℂ) ⊗ₖ B)
      = ((1 : Matrix I I ℂ) ⊗ₖ B) * (g ⊗ₖ 1) := by
  have h1 := Matrix.mul_kronecker_mul g (1 : Matrix I I ℂ)
    (1 : Matrix J J ℂ) B
  have h2 := Matrix.mul_kronecker_mul (1 : Matrix I I ℂ) g B
    (1 : Matrix J J ℂ)
  rw [Matrix.mul_one, Matrix.one_mul] at h1
  rw [Matrix.one_mul, Matrix.mul_one] at h2
  rw [← h1, ← h2]

/-- Commuting with the four **marked generators** `Γ_μ ⊗ 1` forces
commuting with the whole left factor, since the `Γ_μ` generate
`M₄(ℂ)` (`gamma_generates`). -/
theorem commutes_of_commutes_gamma
    (X : Matrix ((Fin 2 × Fin 2) × J) ((Fin 2 × Fin 2) × J) ℂ)
    (hX : ∀ μ : Fin 4,
      (gamma μ ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (gamma μ ⊗ₖ 1)) :
    ∀ g : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ,
      (g ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (g ⊗ₖ 1) := by
  have hmem : ∀ g ∈ Algebra.adjoin ℂ (Set.range gamma),
      (g ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (g ⊗ₖ 1) := by
    intro g hg
    induction hg using Algebra.adjoin_induction with
    | mem g hg =>
      obtain ⟨μ, rfl⟩ := hg
      exact hX μ
    | algebraMap c =>
      have h1 : (algebraMap ℂ
            (Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ) c)
          ⊗ₖ (1 : Matrix J J ℂ)
          = c • (1 : Matrix ((Fin 2 × Fin 2) × J)
              ((Fin 2 × Fin 2) × J) ℂ) := by
        rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_kronecker,
          Matrix.one_kronecker_one]
      rw [h1, Matrix.smul_mul, Matrix.mul_smul, Matrix.one_mul,
        Matrix.mul_one]
    | add x y hx hy ihx ihy =>
      rw [Matrix.add_kronecker, Matrix.add_mul, Matrix.mul_add,
        ihx, ihy]
    | mul x y hx hy ihx ihy =>
      have h1 : (x * y) ⊗ₖ (1 : Matrix J J ℂ)
          = (x ⊗ₖ (1 : Matrix J J ℂ)) * (y ⊗ₖ 1) := by
        have := Matrix.mul_kronecker_mul x y (1 : Matrix J J ℂ)
          (1 : Matrix J J ℂ)
        rw [Matrix.one_mul] at this
        exact this
      rw [h1, Matrix.mul_assoc, ihy, ← Matrix.mul_assoc, ihx,
        Matrix.mul_assoc]
  intro g
  exact hmem g (by rw [gamma_generates]; exact Algebra.mem_top)

/-- **Marked commutant** (finite Stone–von Neumann, realized model):
the commutant of the marked external generators `Γ_μ ⊗ 1` is exactly
the internal complement `1 ⊗ M_J`. -/
theorem marked_commutant
    (X : Matrix ((Fin 2 × Fin 2) × J) ((Fin 2 × Fin 2) × J) ℂ) :
    (∀ μ : Fin 4,
        (gamma μ ⊗ₖ (1 : Matrix J J ℂ)) * X = X * (gamma μ ⊗ₖ 1))
      ↔ ∃ B : Matrix J J ℂ,
          X = (1 : Matrix (Fin 2 × Fin 2) (Fin 2 × Fin 2) ℂ) ⊗ₖ B := by
  constructor
  · intro hX
    exact left_factor_commutant X (commutes_of_commutes_gamma X hX)
  · rintro ⟨B, rfl⟩ μ
    exact kron_right_commutes (gamma μ) B

/-- The left Kronecker embedding `g ↦ g ⊗ 1` as an algebra
homomorphism. -/
def leftKron : Matrix I I ℂ →ₐ[ℂ] Matrix (I × J) (I × J) ℂ where
  toFun g := g ⊗ₖ (1 : Matrix J J ℂ)
  map_one' := Matrix.one_kronecker_one
  map_mul' x y := by
    have := Matrix.mul_kronecker_mul x y (1 : Matrix J J ℂ)
      (1 : Matrix J J ℂ)
    rw [Matrix.one_mul] at this
    exact this
  map_zero' := Matrix.zero_kronecker _
  map_add' x y := Matrix.add_kronecker x y 1
  commutes' c := by
    rw [Algebra.algebraMap_eq_smul_one, Matrix.smul_kronecker,
      Matrix.one_kronecker_one, Algebra.algebraMap_eq_smul_one]

@[simp] theorem leftKron_apply (g : Matrix I I ℂ) :
    (leftKron (J := J) g) = g ⊗ₖ (1 : Matrix J J ℂ) := rfl

/-- **Marked generation** (`thm:external-core`, identification step):
the algebra generated by the marked generators `Γ_μ ⊗ 1` is exactly
the left tensor factor `M₄ ⊗ 1`. -/
theorem marked_adjoin_eq_leftKron_range :
    Algebra.adjoin ℂ
        (Set.range fun μ : Fin 4 => gamma μ ⊗ₖ (1 : Matrix J J ℂ))
      = (leftKron (I := Fin 2 × Fin 2) (J := J)).range := by
  have h1 : (Set.range fun μ : Fin 4 =>
        gamma μ ⊗ₖ (1 : Matrix J J ℂ))
      = leftKron (J := J) '' Set.range gamma := by
    ext X
    constructor
    · rintro ⟨μ, rfl⟩
      exact ⟨gamma μ, ⟨μ, rfl⟩, rfl⟩
    · rintro ⟨g, ⟨μ, rfl⟩, rfl⟩
      exact ⟨μ, rfl⟩
  rw [h1, ← AlgHom.map_adjoin, gamma_generates, Algebra.map_top]

end NCG.CommonOrigin
