import NCG.Grand.MinimalReadAlgebra
import NCG.Grand.CompletionConservative

/-!
# Canonical co-retained master tuple

This module proves the finite content of `thm:accepted-master-tuple`:
the algebra generated by the protected coordinates is precisely the
pullback of the full function algebra on the tuple image; its atoms are
the tuple-fibre indicators; every other sharp co-retention quotient
surjects onto the tuple image and therefore has at least its cardinality;
passive append-only copies are conservative under partial trace; and
every selected panel is an exact compression of the complete master
panel.
-/

open Matrix
open scoped Kronecker

namespace NCG
namespace AcceptedMasterTuple

variable {Ω m : Type*} [Fintype Ω] [Fintype m]
  [DecidableEq Ω] [DecidableEq m]
variable (Ωj : m → Type*) [∀ j, Fintype (Ωj j)]
  [∀ j, DecidableEq (Ωj j)]
variable (r : ∀ j, Ω → Ωj j)

abbrev TupleSpace := ∀ j, Ωj j

def tupleMap (ω : Ω) : TupleSpace Ωj := fun j => r j ω

abbrev TupleImage := Set.range (tupleMap Ωj r)

/-- Pullback of the complete function algebra on the tuple image. -/
def tuplePullbackAlgebra : Subalgebra ℂ (Ω → ℂ) where
  carrier := {f | ∃ g : TupleImage Ωj r → ℂ,
    f = g ∘ fun ω => ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩}
  mul_mem' := by
    rintro f g ⟨F, rfl⟩ ⟨G, rfl⟩
    exact ⟨F * G, rfl⟩
  add_mem' := by
    rintro f g ⟨F, rfl⟩ ⟨G, rfl⟩
    exact ⟨F + G, rfl⟩
  algebraMap_mem' c := ⟨fun _ => c, rfl⟩

/-- Coordinate point indicators, the sharp classical Reads. -/
def coordinateIndicator (j : m) (a : Ωj j) : Ω → ℂ :=
  fun ω => if r j ω = a then 1 else 0

/-- The unital algebra generated by every sharp coordinate Read. -/
def coordinateReadAlgebra : Subalgebra ℂ (Ω → ℂ) :=
  Algebra.adjoin ℂ
    (Set.range fun ja : Σ j, Ωj j =>
      coordinateIndicator Ωj r ja.1 ja.2)

omit [Fintype Ω] [Fintype m] [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
theorem coordinateIndicator_mem_pullback (j : m) (a : Ωj j) :
    coordinateIndicator Ωj r j a ∈ tuplePullbackAlgebra Ωj r := by
  refine ⟨fun t => if t.1 j = a then 1 else 0, ?_⟩
  rfl

omit [Fintype Ω] [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- The indicator of one tuple value is the product of its coordinate
point indicators. -/
theorem tupleIndicator_eq_product (t : TupleImage Ωj r) :
    (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) =
      ∏ j, coordinateIndicator Ωj r j (t.1 j) := by
  funext ω
  by_cases h : tupleMap Ωj r ω = t.1
  · rw [if_pos h]
    symm
    rw [Finset.prod_apply]
    apply Finset.prod_eq_one
    intro j _
    change (if r j ω = t.1 j then (1 : ℂ) else 0) = 1
    have hj : r j ω = t.1 j := by
      simpa [tupleMap] using congrFun h j
    rw [if_pos hj]
  · rw [if_neg h]
    have hex : ∃ j, r j ω ≠ t.1 j := by
      by_contra hall
      push Not at hall
      apply h
      funext j
      exact hall j
    obtain ⟨j, hj⟩ := hex
    symm
    rw [Finset.prod_apply]
    apply Finset.prod_eq_zero (Finset.mem_univ j)
    change (if r j ω = t.1 j then (1 : ℂ) else 0) = 0
    rw [if_neg hj]

omit [Fintype Ω] [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
theorem tupleIndicator_mem_coordinateRead (t : TupleImage Ωj r) :
    (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) ∈
      coordinateReadAlgebra Ωj r := by
  rw [tupleIndicator_eq_product Ωj r t]
  apply Subalgebra.prod_mem
  intro j _
  apply Algebra.subset_adjoin
  exact ⟨⟨j, t.1 j⟩, rfl⟩

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- Exact Read-algebra identity
`R_τ = τ* C(Ω_τ)`. -/
theorem coordinateReadAlgebra_eq_tuplePullback :
    coordinateReadAlgebra Ωj r = tuplePullbackAlgebra Ωj r := by
  apply le_antisymm
  · apply Algebra.adjoin_le
    rintro f ⟨⟨j, a⟩, rfl⟩
    exact coordinateIndicator_mem_pullback Ωj r j a
  · rintro f ⟨g, rfl⟩
    have hdecomp :
        g ∘ (fun ω : Ω => ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩) =
          ∑ t : TupleImage Ωj r, g t •
            (fun ω : Ω =>
              if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) := by
      funext ω
      rw [Finset.sum_apply, Finset.sum_eq_single
        (⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ : TupleImage Ωj r)]
      · simp
      · intro t _ hne
        simp only [Pi.smul_apply, smul_eq_mul]
        have hval : tupleMap Ωj r ω ≠ t.1 := by
          intro hval
          exact hne (Subtype.ext hval.symm)
        rw [if_neg hval, mul_zero]
      · simp
    rw [hdecomp]
    exact Subalgebra.sum_mem _ fun t _ =>
      Subalgebra.smul_mem _ (tupleIndicator_mem_coordinateRead Ωj r t) _

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- The joint-tuple indicators are nonzero pairwise-orthogonal atoms
partitioning the unit. -/
theorem tupleIndicators_are_atoms :
    (∀ t : TupleImage Ωj r,
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) ≠ 0)
    ∧ (∀ t u : TupleImage Ωj r, t ≠ u →
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) *
      (fun ω : Ω => if tupleMap Ωj r ω = u.1 then (1 : ℂ) else 0) = 0)
    ∧ (∑ t : TupleImage Ωj r,
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0)) = 1 := by
  constructor
  · intro t hzero
    obtain ⟨ω, hω⟩ := t.2
    have := congrFun hzero ω
    simp [hω] at this
  constructor
  · intro t u htu
    funext ω
    simp only [Pi.mul_apply, Pi.zero_apply]
    by_cases ht : tupleMap Ωj r ω = t.1
    · rw [if_pos ht, one_mul, if_neg]
      intro hu
      exact htu (Subtype.ext (ht.symm.trans hu))
    · simp [ht]
  · funext ω
    rw [Finset.sum_apply, Finset.sum_eq_single
      (⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ : TupleImage Ωj r)]
    · simp
    · intro t _ hne
      rw [if_neg]
      exact fun hval => hne (Subtype.ext hval.symm)
    · simp

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- Every sharp record through which every coordinate factors maps
surjectively onto the tuple image. -/
theorem universal_tuple_surjection
    {Q : Type*} [Fintype Q]
    (q : Ω → Q) (hq : Function.Surjective q)
    (f : ∀ j, Q → Ωj j) (hfactor : ∀ j, r j = f j ∘ q) :
    ∃ p : Q → TupleImage Ωj r,
      Function.Surjective p ∧
      (∀ ω, p (q ω) =
        ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩) ∧
      Fintype.card (TupleImage Ωj r) ≤ Fintype.card Q := by
  let p : Q → TupleImage Ωj r := fun y =>
    ⟨fun j => f j y, by
      obtain ⟨ω, rfl⟩ := hq y
      refine ⟨ω, ?_⟩
      funext j
      exact congrFun (hfactor j) ω⟩
  have hpq : ∀ ω, p (q ω) =
      ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ := by
    intro ω
    apply Subtype.ext
    funext j
    exact (congrFun (hfactor j) ω).symm
  have hp : Function.Surjective p := by
    rintro ⟨_, ω, rfl⟩
    exact ⟨q ω, hpq ω⟩
  exact ⟨p, hp, hpq, Fintype.card_le_of_surjective p hp⟩

/-- Passive append-only copying is conservative after the ledger is
traced out; the same tensor embedding is a unital injective
star-homomorphism, so no new feedback relation is created. -/
theorem append_only_copy_conservative
    {d ledger : Type*} [Fintype d] [Fintype ledger]
    [DecidableEq d] [DecidableEq ledger] [Nonempty ledger] :
    (∀ (A : Matrix d d ℂ) (W : Matrix ledger ledger ℂ),
      W.trace = 1 →
      partialTraceRight (A ⊗ₖ W) = A)
    ∧ (∀ a b : Matrix d d ℂ,
      (a * b) ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        (a ⊗ₖ 1) * (b ⊗ₖ 1))
    ∧ ((1 : Matrix d d ℂ) ⊗ₖ (1 : Matrix ledger ledger ℂ) = 1)
    ∧ (∀ a : Matrix d d ℂ,
      aᴴ ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        (a ⊗ₖ (1 : Matrix ledger ledger ℂ))ᴴ)
    ∧ (∀ a b : Matrix d d ℂ,
      a ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        b ⊗ₖ (1 : Matrix ledger ledger ℂ) → a = b) :=
  sm_completion_conservative

/-- Every finite selected subpanel is the exact row/column
compression of the complete master panel. -/
theorem master_panel_contains_subpanel
    {I J I' J' : Type*}
    (M : Matrix I J ℂ) (row : I' → I) (col : J' → J) :
    M.submatrix row col =
      fun i j => M (row i) (col j) := rfl

/-! ### Minimality: the tuple-fibre indicators are exactly the
nonzero minimal projections of the Read algebra -/

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- Every idempotent of the coordinate Read algebra is a sum of
tuple-fibre indicators. -/
theorem idempotent_form (p : Ω → ℂ)
    (hp : p ∈ coordinateReadAlgebra Ωj r)
    (hidem : p * p = p) :
    ∃ S : Finset (TupleImage Ωj r),
      p = ∑ t ∈ S, (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) := by
  rw [coordinateReadAlgebra_eq_tuplePullback] at hp
  obtain ⟨g, rfl⟩ := hp
  have hg : ∀ x : TupleImage Ωj r, g x = 0 ∨ g x = 1 := by
    intro x
    obtain ⟨ω, hω⟩ := x.2
    have h := congrFun hidem ω
    simp only [Pi.mul_apply, Function.comp_apply] at h
    have hex : (⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ :
        TupleImage Ωj r) = x := Subtype.ext hω
    rw [hex] at h
    have h2 : g x * (g x - 1) = 0 := by linear_combination h
    rcases mul_eq_zero.mp h2 with h3 | h3
    · exact Or.inl h3
    · exact Or.inr (sub_eq_zero.mp h3)
  refine ⟨Finset.univ.filter (fun t => g t = 1), ?_⟩
  funext ω
  rw [Finset.sum_apply]
  set e : TupleImage Ωj r := ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩
    with he
  by_cases hgω : g e = 1
  · rw [Finset.sum_eq_single_of_mem e
      (Finset.mem_filter.mpr ⟨Finset.mem_univ e, hgω⟩)
      (fun t _ ht => by
        rw [if_neg fun hc => ht (Subtype.ext hc.symm)])]
    rw [if_pos rfl]
    exact hgω
  · rw [Finset.sum_eq_zero (fun t ht => by
      rw [if_neg fun hc => hgω (by
        rw [show e = t from Subtype.ext hc]
        exact (Finset.mem_filter.mp ht).2)])]
    rcases hg e with h0 | h1
    · exact h0
    · exact absurd h1 hgω

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- Each tuple-fibre indicator is a minimal projection: any
idempotent of the algebra below it is `0` or the indicator
itself. -/
theorem tupleIndicator_minimal (t : TupleImage Ωj r)
    (q : Ω → ℂ) (hq : q ∈ coordinateReadAlgebra Ωj r)
    (hqidem : q * q = q)
    (hle : q * (fun ω : Ω =>
      if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) = q) :
    q = 0 ∨ q = (fun ω : Ω =>
      if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) := by
  obtain ⟨S, rfl⟩ := idempotent_form Ωj r _ hq hqidem
  by_cases hS : ∀ s ∈ S, s = t
  · rcases Finset.eq_empty_or_nonempty S with rfl | ⟨s, hs⟩
    · exact Or.inl (by simp)
    · have hst := hS s hs
      subst hst
      have hSe : S = {s} := by
        apply Finset.eq_singleton_iff_unique_mem.mpr
        exact ⟨hs, fun u hu => hS u hu⟩
      rw [hSe, Finset.sum_singleton]
      exact Or.inr rfl
  · exfalso
    push Not at hS
    obtain ⟨s, hsS, hst⟩ := hS
    obtain ⟨ω, hω⟩ := s.2
    have h := congrFun hle ω
    simp only [Pi.mul_apply, Finset.sum_apply] at h
    have hleft : ∑ u ∈ S, (if tupleMap Ωj r ω = u.1
        then (1:ℂ) else 0) = 1 := by
      rw [Finset.sum_eq_single_of_mem s hsS
        (fun u _ hu => by
          rw [if_neg fun hc => hu (Subtype.ext
            (hc.symm.trans hω))])]
      rw [if_pos hω]
    have hright : (if tupleMap Ωj r ω = t.1
        then (1:ℂ) else 0) = 0 := by
      rw [if_neg fun hc => hst (Subtype.ext
        (hω.symm.trans hc))]
    rw [hleft, hright, one_mul] at h
    exact one_ne_zero h.symm

omit [DecidableEq Ω] [DecidableEq m]
  [(j : m) → Fintype (Ωj j)] in
/-- Conversely, every nonzero minimal projection of the Read
algebra is a tuple-fibre indicator. -/
theorem minimal_projection_classification (p : Ω → ℂ)
    (hp : p ∈ coordinateReadAlgebra Ωj r)
    (hidem : p * p = p) (hne : p ≠ 0)
    (hmin : ∀ q ∈ coordinateReadAlgebra Ωj r,
      q * q = q → q * p = q →
      q = 0 ∨ q = p) :
    ∃ t : TupleImage Ωj r, p = (fun ω : Ω =>
      if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) := by
  obtain ⟨S, rfl⟩ := idempotent_form Ωj r _ hp hidem
  rcases Finset.eq_empty_or_nonempty S with rfl | ⟨t, htS⟩
  · exact absurd (by simp) hne
  refine ⟨t, ?_⟩
  have hqmem : (fun ω : Ω =>
      if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0)
      ∈ coordinateReadAlgebra Ωj r :=
    tupleIndicator_mem_coordinateRead Ωj r t
  have hqidem : (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0)
      * (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0)
      = (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) := by
    funext ω
    by_cases h : tupleMap Ωj r ω = t.1 <;>
      simp [h]
  have hqle : (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0)
      * (∑ u ∈ S, fun ω : Ω =>
        if tupleMap Ωj r ω = u.1 then (1:ℂ) else 0)
      = (fun ω : Ω =>
        if tupleMap Ωj r ω = t.1 then (1:ℂ) else 0) := by
    funext ω
    simp only [Pi.mul_apply, Finset.sum_apply]
    by_cases h : tupleMap Ωj r ω = t.1
    · rw [if_pos h, one_mul,
        Finset.sum_eq_single_of_mem t htS
          (fun u _ hu => by
            rw [if_neg fun hc => hu (Subtype.ext
              (hc.symm.trans h))]),
        if_pos h]
    · rw [if_neg h, zero_mul]
  rcases hmin _ hqmem hqidem hqle with h0 | hEq
  · exfalso
    obtain ⟨ω, hω⟩ := t.2
    have := congrFun h0 ω
    rw [if_pos hω] at this
    exact one_ne_zero this
  · exact hEq.symm

/-! ### Append-only ledger copy and its conservativity -/

/-- The passive append-only ledger copy of a
classical–quantum family: each classical block is tensored
with the sharp ledger registration of its coordinate value. -/
noncomputable def ledgerCopy {d L : Type*} [Fintype L]
    [DecidableEq L] (ρ : Ω → Matrix d d ℂ) (v : Ω → L) :
    Ω → Matrix (d × L) (d × L) ℂ :=
  fun ω => ρ ω ⊗ₖ Matrix.single (v ω) (v ω) 1

omit [Fintype Ω] [DecidableEq Ω] in
/-- Tracing out the ledger recovers the original process on
every classical block. -/
theorem ledgerCopy_conservative {d L : Type*} [Fintype d]
    [Fintype L] [DecidableEq d] [DecidableEq L] [Nonempty L]
    (ρ : Ω → Matrix d d ℂ) (v : Ω → L) (ω : Ω) :
    partialTraceRight (ledgerCopy ρ v ω) = ρ ω :=
  sm_completion_conservative.1 (ρ ω) _
    (Matrix.trace_single_eq_same (v ω) 1)

omit [Fintype Ω] [DecidableEq Ω] in
/-- Sequential copies to two append-only ledgers are jointly
conservative: two partial traces recover the original
process. -/
theorem ledgerCopy_sequential {d L1 L2 : Type*} [Fintype d]
    [Fintype L1] [Fintype L2] [DecidableEq d]
    [DecidableEq L1] [DecidableEq L2] [Nonempty L1]
    [Nonempty L2]
    (ρ : Ω → Matrix d d ℂ) (v : Ω → L1) (w : Ω → L2)
    (ω : Ω) :
    partialTraceRight (partialTraceRight
      (ledgerCopy (ledgerCopy ρ v) w ω)) = ρ ω := by
  rw [ledgerCopy_conservative, ledgerCopy_conservative]

omit [Fintype Ω] [DecidableEq Ω] in
/-- The copy is trace preserving on every classical block. -/
theorem ledgerCopy_trace {d L : Type*} [Fintype d]
    [Fintype L] [DecidableEq d] [DecidableEq L]
    (ρ : Ω → Matrix d d ℂ) (v : Ω → L) (ω : Ω) :
    (ledgerCopy ρ v ω).trace = (ρ ω).trace := by
  rw [ledgerCopy, Matrix.trace_kronecker,
    Matrix.trace_single_eq_same, mul_one]

/-! ### The master panel and exact subpanel compression -/

section MasterPanel

variable {n T W' Λ I : Type*} [Fintype n] [Fintype T]
  [Fintype W']

/-- The complete master panel: the Gram of every projected
word against every inserted projected word. -/
noncomputable def masterPanel (p : T → Matrix n n ℂ)
    (W : W' → Matrix n n ℂ) (X : Λ → Matrix n n ℂ)
    (lam : Λ) (ta ub : T × W') : ℂ :=
  ((p ta.1 * W ta.2)ᴴ * (X lam * (p ub.1 * W ub.2))).trace

/-- A synthesized panel element: a finite coefficient
combination of projected words. -/
noncomputable def synthVec (p : T → Matrix n n ℂ)
    (W : W' → Matrix n n ℂ) (c : I → T × W' → ℂ) (i : I) :
    Matrix n n ℂ :=
  ∑ ta : T × W', c i ta • (p ta.1 * W ta.2)

/-- **Exact subpanel compression**: the Gram panel of any
finite coefficient synthesis is the corresponding
coefficient compression of the complete master panel — every
derived provenance/pulse/chronological/determining-field/
action subpanel is contained in the master panel. -/
theorem subpanel_compression (p : T → Matrix n n ℂ)
    (W : W' → Matrix n n ℂ) (X : Λ → Matrix n n ℂ)
    (c : I → T × W' → ℂ) (lam : Λ) (i k : I) :
    ((synthVec p W c i)ᴴ * (X lam * synthVec p W c k)).trace
      = ∑ ta : T × W', ∑ ub : T × W',
        star (c i ta) * c k ub
          * masterPanel p W X lam ta ub := by
  simp only [synthVec, masterPanel]
  rw [Matrix.conjTranspose_sum, Finset.mul_sum,
    Finset.sum_mul_sum]
  rw [Matrix.trace_sum]
  refine Finset.sum_congr rfl fun ta _ => ?_
  rw [Matrix.trace_sum]
  refine Finset.sum_congr rfl fun ub _ => ?_
  simp only [Matrix.conjTranspose_smul, smul_mul_assoc,
    mul_smul_comm, smul_smul, Matrix.trace_smul,
    smul_eq_mul, mul_assoc]
  ring

end MasterPanel

end AcceptedMasterTuple
end NCG
