import NCG.Grand.MinimalReadAlgebra
import NCG.Grand.CompletionConservative

/-!
# Canonical co-retained master tuple

This module proves the finite content of `thm:accepted-master-tuple`:
the algebra generated by the protected coordinates is precisely the
pullback of the full function algebra on the tuple image; its atoms are
the tuple-fibre indicators; every other sharp co-retention quotient
surjects onto the tuple image and therefore has at least its cardinality;
passive append-only copies are conservative under partial trace; and
every selected panel is an exact compression of the complete master
panel.
-/

open Matrix
open scoped Kronecker

namespace NCG
namespace AcceptedMasterTuple

variable {Ω m : Type*} [Fintype Ω] [Fintype m]
  [DecidableEq Ω] [DecidableEq m]
variable (Ωj : m → Type*) [∀ j, Fintype (Ωj j)]
  [∀ j, DecidableEq (Ωj j)]
variable (r : ∀ j, Ω → Ωj j)

abbrev TupleSpace := ∀ j, Ωj j

def tupleMap (ω : Ω) : TupleSpace Ωj := fun j => r j ω

abbrev TupleImage := Set.range (tupleMap Ωj r)

/-- Pullback of the complete function algebra on the tuple image. -/
def tuplePullbackAlgebra : Subalgebra ℂ (Ω → ℂ) where
  carrier := {f | ∃ g : TupleImage Ωj r → ℂ,
    f = g ∘ fun ω => ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩}
  mul_mem' := by
    rintro f g ⟨F, rfl⟩ ⟨G, rfl⟩
    exact ⟨F * G, rfl⟩
  add_mem' := by
    rintro f g ⟨F, rfl⟩ ⟨G, rfl⟩
    exact ⟨F + G, rfl⟩
  algebraMap_mem' c := ⟨fun _ => c, rfl⟩

/-- Coordinate point indicators, the sharp classical Reads. -/
def coordinateIndicator (j : m) (a : Ωj j) : Ω → ℂ :=
  fun ω => if r j ω = a then 1 else 0

/-- The unital algebra generated by every sharp coordinate Read. -/
def coordinateReadAlgebra : Subalgebra ℂ (Ω → ℂ) :=
  Algebra.adjoin ℂ
    (Set.range fun ja : Σ j, Ωj j =>
      coordinateIndicator Ωj r ja.1 ja.2)

theorem coordinateIndicator_mem_pullback (j : m) (a : Ωj j) :
    coordinateIndicator Ωj r j a ∈ tuplePullbackAlgebra Ωj r := by
  refine ⟨fun t => if t.1 j = a then 1 else 0, ?_⟩
  rfl

/-- The indicator of one tuple value is the product of its coordinate
point indicators. -/
theorem tupleIndicator_eq_product (t : TupleImage Ωj r) :
    (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) =
      ∏ j, coordinateIndicator Ωj r j (t.1 j) := by
  funext ω
  by_cases h : tupleMap Ωj r ω = t.1
  · rw [if_pos h]
    symm
    rw [Finset.prod_apply]
    apply Finset.prod_eq_one
    intro j _
    change (if r j ω = t.1 j then (1 : ℂ) else 0) = 1
    have hj : r j ω = t.1 j := by
      simpa [tupleMap] using congrFun h j
    rw [if_pos hj]
  · rw [if_neg h]
    have hex : ∃ j, r j ω ≠ t.1 j := by
      by_contra hall
      push_neg at hall
      apply h
      funext j
      exact hall j
    obtain ⟨j, hj⟩ := hex
    symm
    rw [Finset.prod_apply]
    apply Finset.prod_eq_zero (Finset.mem_univ j)
    change (if r j ω = t.1 j then (1 : ℂ) else 0) = 0
    rw [if_neg hj]

theorem tupleIndicator_mem_coordinateRead (t : TupleImage Ωj r) :
    (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) ∈
      coordinateReadAlgebra Ωj r := by
  rw [tupleIndicator_eq_product Ωj r t]
  apply Subalgebra.prod_mem
  intro j _
  apply Algebra.subset_adjoin
  exact ⟨⟨j, t.1 j⟩, rfl⟩

/-- Exact Read-algebra identity
`R_τ = τ* C(Ω_τ)`. -/
theorem coordinateReadAlgebra_eq_tuplePullback :
    coordinateReadAlgebra Ωj r = tuplePullbackAlgebra Ωj r := by
  apply le_antisymm
  · apply Algebra.adjoin_le
    rintro f ⟨⟨j, a⟩, rfl⟩
    exact coordinateIndicator_mem_pullback Ωj r j a
  · rintro f ⟨g, rfl⟩
    have hdecomp :
        g ∘ (fun ω : Ω => ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩) =
          ∑ t : TupleImage Ωj r, g t •
            (fun ω : Ω =>
              if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) := by
      funext ω
      rw [Finset.sum_apply, Finset.sum_eq_single
        (⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ : TupleImage Ωj r)]
      · simp
      · intro t _ hne
        simp only [Pi.smul_apply, smul_eq_mul]
        have hval : tupleMap Ωj r ω ≠ t.1 := by
          intro hval
          exact hne (Subtype.ext hval.symm)
        rw [if_neg hval, mul_zero]
      · simp
    rw [hdecomp]
    exact Subalgebra.sum_mem _ fun t _ =>
      Subalgebra.smul_mem _ (tupleIndicator_mem_coordinateRead Ωj r t) _

/-- The joint-tuple indicators are nonzero pairwise-orthogonal atoms
partitioning the unit. -/
theorem tupleIndicators_are_atoms :
    (∀ t : TupleImage Ωj r,
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) ≠ 0)
    ∧ (∀ t u : TupleImage Ωj r, t ≠ u →
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0) *
      (fun ω : Ω => if tupleMap Ωj r ω = u.1 then (1 : ℂ) else 0) = 0)
    ∧ (∑ t : TupleImage Ωj r,
      (fun ω : Ω => if tupleMap Ωj r ω = t.1 then (1 : ℂ) else 0)) = 1 := by
  constructor
  · intro t hzero
    obtain ⟨ω, hω⟩ := t.2
    have := congrFun hzero ω
    simp [hω] at this
  constructor
  · intro t u htu
    funext ω
    simp only [Pi.mul_apply, Pi.zero_apply]
    by_cases ht : tupleMap Ωj r ω = t.1
    · rw [if_pos ht, one_mul, if_neg]
      intro hu
      exact htu (Subtype.ext (ht.symm.trans hu))
    · simp [ht]
  · funext ω
    rw [Finset.sum_apply, Finset.sum_eq_single
      (⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ : TupleImage Ωj r)]
    · simp
    · intro t _ hne
      rw [if_neg]
      exact fun hval => hne (Subtype.ext hval.symm)
    · simp

/-- Every sharp record through which every coordinate factors maps
surjectively onto the tuple image. -/
theorem universal_tuple_surjection
    {Q : Type*} [Fintype Q]
    (q : Ω → Q) (hq : Function.Surjective q)
    (f : ∀ j, Q → Ωj j) (hfactor : ∀ j, r j = f j ∘ q) :
    ∃ p : Q → TupleImage Ωj r,
      Function.Surjective p ∧
      (∀ ω, p (q ω) =
        ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩) ∧
      Fintype.card (TupleImage Ωj r) ≤ Fintype.card Q := by
  let p : Q → TupleImage Ωj r := fun y =>
    ⟨fun j => f j y, by
      obtain ⟨ω, rfl⟩ := hq y
      refine ⟨ω, ?_⟩
      funext j
      exact congrFun (hfactor j) ω⟩
  have hpq : ∀ ω, p (q ω) =
      ⟨tupleMap Ωj r ω, ⟨ω, rfl⟩⟩ := by
    intro ω
    apply Subtype.ext
    funext j
    exact (congrFun (hfactor j) ω).symm
  have hp : Function.Surjective p := by
    rintro ⟨_, ω, rfl⟩
    exact ⟨q ω, hpq ω⟩
  exact ⟨p, hp, hpq, Fintype.card_le_of_surjective p hp⟩

/-- Passive append-only copying is conservative after the ledger is
traced out; the same tensor embedding is a unital injective
star-homomorphism, so no new feedback relation is created. -/
theorem append_only_copy_conservative
    {d ledger : Type*} [Fintype d] [Fintype ledger]
    [DecidableEq d] [DecidableEq ledger] [Nonempty ledger] :
    (∀ (A : Matrix d d ℂ) (W : Matrix ledger ledger ℂ),
      W.trace = 1 →
      partialTraceRight (A ⊗ₖ W) = A)
    ∧ (∀ a b : Matrix d d ℂ,
      (a * b) ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        (a ⊗ₖ 1) * (b ⊗ₖ 1))
    ∧ ((1 : Matrix d d ℂ) ⊗ₖ (1 : Matrix ledger ledger ℂ) = 1)
    ∧ (∀ a : Matrix d d ℂ,
      aᴴ ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        (a ⊗ₖ (1 : Matrix ledger ledger ℂ))ᴴ)
    ∧ (∀ a b : Matrix d d ℂ,
      a ⊗ₖ (1 : Matrix ledger ledger ℂ) =
        b ⊗ₖ (1 : Matrix ledger ledger ℂ) → a = b) :=
  sm_completion_conservative

/-- Every finite selected subpanel is the exact row/column
compression of the complete master panel. -/
theorem master_panel_contains_subpanel
    {I J I' J' : Type*}
    (M : Matrix I J ℂ) (row : I' → I) (col : J' → J) :
    M.submatrix row col =
      fun i j => M (row i) (col j) := rfl

end AcceptedMasterTuple
end NCG
