/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import NCG.Grand.Bicommutant
import NCG.Grand.FiniteStarSubalgebraMutualCommutant
import NCG.Grand.StarMatrixUnits

/-!
# Two-control reconstruction of the internal matrix factors
  (`thm:SM-active-residual-algebra`, Gran-Tensor manuscript)

The source-minimal residual carrier of the active Standard-Model
chapter is the 12-dimensional directed-edge carrier of `K₄`
(ordered pairs of distinct vertices): its `S₄ × C₂` decomposition
is `ℂ ⊕ W₊ ⊕ (V₂)₊ ⊕ W₋ ⊕ (W ⊗ sgn)₋` with dimensions
`1, 3, 2, 3, 3` — reversal-even blocks are the unoriented-edge
functions (trivial ⊕ standard ⊕ two-dimensional), reversal-odd
blocks are the cut space (endpoint quotient) and the cycle space
(orthogonal loop kernel).

* `commutant_eq`: the commutant of the algebra `AR` generated by
  the two tetrahedral relabelings `U_s = P (12)`,
  `U_r = P (1234)` and the reversal `R_ι` is exactly the
  five-dimensional span of the pattern matrices
  `1, R, N, M, Dis` (same-endpoint, crossed-endpoint, disjoint).
* `bicommutant_eq`: by the mutual-commutant theorem for
  star-closed subalgebras, `AR` is the commutant of that span —
  the full block algebra of the five isotypic components.
* `Qtype, QC, QW2, QG, QP`: the five explicit orthogonal
  self-adjoint central projections of `AR` summing to `1` with
  traces `1, 3, 2, 3, 3`; `AR` contains every corner
  `Q X Q` (block fullness) and every element of `AR` is the sum
  of its five corners — this is the boxed
  `C*(U_s,U_r,R_ι) ≅ ℂ ⊕ M₃ ⊕ M₂ ⊕ M₃ ⊕ M₃` (SM.0h), with the
  reversal-even internal corner `M₃(C) ⊕ M₂(W₂)` (SM.0i) given
  by `QC + QW2 = (1 + R)/2 − Qtype`.
* `single_control_commutative`, `no_single_control`: a
  `C^*`-algebra generated by one unitary is commutative, and `AR`
  is not — two noncommuting tetrahedral controls are minimal.
* `detC_eq_sign`, `detW2_eq_sign`, `det_product_trivial`:
  the determinant characters of the two reversal-even
  noncommutative blocks both equal the sign character (SM.0j),
  so their product is the trivial `S₄` line.
* `edge_projector_sum`: the six edge projectors of `K₄` sum to
  twice the identity of the cut carrier (SM.0k).
-/

open Matrix

namespace NCG
namespace ActiveResidual

/-- Vertices of `K₄`. -/
abbrev V := Fin 4

/-- The 12 directed edges of `K₄`: ordered pairs of distinct
vertices. -/
abbrev E := {p : V × V // p.1 ≠ p.2}

/-- Relabeling action of a tetrahedral permutation on directed
edges. -/
def act (σ : Equiv.Perm V) (e : E) : E :=
  ⟨(σ e.val.1, σ e.val.2), fun h => e.prop (σ.injective h)⟩

/-- Root reversal on directed edges. -/
def rv (e : E) : E := ⟨(e.val.2, e.val.1), Ne.symm e.prop⟩

@[simp] theorem act_one (e : E) : act 1 e = e := rfl

theorem act_mul (σ τ : Equiv.Perm V) (e : E) :
    act (σ * τ) e = act σ (act τ e) := rfl

@[simp] theorem rv_rv (e : E) : rv (rv e) = e := rfl

theorem act_rv (σ : Equiv.Perm V) (e : E) :
    act σ (rv e) = rv (act σ e) := rfl

/-- The permutation matrix of a relabeling. -/
def Pm (σ : Equiv.Perm V) : Matrix E E ℂ :=
  fun e f => if e = act σ f then 1 else 0

@[simp] theorem Pm_apply (σ : Equiv.Perm V) (e f : E) :
    Pm σ e f = if e = act σ f then 1 else 0 := rfl

/-- The reversal matrix. -/
def Rm : Matrix E E ℂ := fun e f => if e = rv f then 1 else 0

@[simp] theorem Rm_apply (e f : E) :
    Rm e f = if e = rv f then 1 else 0 := rfl

theorem Pm_mul (σ τ : Equiv.Perm V) :
    Pm σ * Pm τ = Pm (σ * τ) := by
  ext e f
  rw [Matrix.mul_apply,
    Finset.sum_eq_single (act τ f)
      (fun h _ hne => by
        rw [Pm_apply τ h f, if_neg hne, mul_zero])
      (fun h => absurd (Finset.mem_univ _) h)]
  rw [Pm_apply τ (act τ f) f, if_pos rfl, mul_one,
    Pm_apply, Pm_apply, act_mul]

theorem Pm_one : Pm 1 = 1 := by
  ext e f
  rw [Pm_apply, act_one, Matrix.one_apply]

theorem Pm_conjTranspose (σ : Equiv.Perm V) :
    (Pm σ)ᴴ = Pm σ⁻¹ := by
  ext e f
  rw [Matrix.conjTranspose_apply, Pm_apply, Pm_apply]
  by_cases h : f = act σ e
  · rw [if_pos h, if_pos (by rw [h, ← act_mul,
      inv_mul_cancel, act_one]), star_one]
  · rw [if_neg h, if_neg (fun hc => h (by
      rw [hc, ← act_mul, mul_inv_cancel, act_one])), star_zero]

theorem Rm_mul_Rm : Rm * Rm = 1 := by
  ext e f
  rw [Matrix.mul_apply,
    Finset.sum_eq_single (rv f)
      (fun h _ hne => by
        rw [Rm_apply h f, if_neg hne, mul_zero])
      (fun h => absurd (Finset.mem_univ _) h)]
  rw [Rm_apply (rv f) f, if_pos rfl, mul_one, Rm_apply,
    rv_rv, Matrix.one_apply]

theorem Rm_conjTranspose : Rmᴴ = Rm := by
  ext e f
  rw [Matrix.conjTranspose_apply, Rm_apply, Rm_apply]
  by_cases h : f = rv e
  · rw [if_pos h, if_pos (by rw [h, rv_rv]), star_one]
  · rw [if_neg h, if_neg (fun hc => h (by rw [hc, rv_rv])),
      star_zero]

theorem Pm_mul_Rm (σ : Equiv.Perm V) :
    Pm σ * Rm = Rm * Pm σ := by
  ext e f
  rw [Matrix.mul_apply,
    Finset.sum_eq_single (rv f)
      (fun h _ hne => by
        rw [Rm_apply h f, if_neg hne, mul_zero])
      (fun h => absurd (Finset.mem_univ _) h),
    Matrix.mul_apply,
    Finset.sum_eq_single (act σ f)
      (fun h _ hne => by
        rw [Pm_apply σ h f, if_neg hne, mul_zero])
      (fun h => absurd (Finset.mem_univ _) h)]
  rw [Rm_apply (rv f) f, if_pos rfl, mul_one,
    Pm_apply σ (act σ f) f, if_pos rfl, mul_one,
    Pm_apply, Rm_apply, act_rv]

/-- The two tetrahedral controls: `s = (12)` and `r = (1234)`
(zero-indexed: the swap `(0 1)` and the 4-cycle). -/
def sPerm : Equiv.Perm V := Equiv.swap 0 1

def rPerm : Equiv.Perm V := finRotate 4

/-- The two-control algebra `C^*(U_s, U_r, R_ι)`. -/
def AR : Subalgebra ℂ (Matrix E E ℂ) :=
  Algebra.adjoin ℂ {Pm sPerm, Pm rPerm, Rm}

theorem closure_sr :
    Subgroup.closure ({rPerm, sPerm} : Set (Equiv.Perm V)) = ⊤ := by
  have h := Equiv.Perm.closure_cycle_adjacent_swap
    (isCycle_finRotate (n := 2)) (by decide) 0
  have h2 : Equiv.swap (0 : V) (finRotate 4 0)
      = Equiv.swap 0 1 := by decide
  rw [h2] at h
  exact h

theorem Pm_mem (σ : Equiv.Perm V) : Pm σ ∈ AR := by
  have hσ : σ ∈ Subgroup.closure ({rPerm, sPerm} :
      Set (Equiv.Perm V)) := by
    rw [closure_sr]; exact Subgroup.mem_top σ
  induction hσ using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · exact Algebra.subset_adjoin (by simp)
    · exact Algebra.subset_adjoin (by simp)
  | one =>
    rw [Pm_one]
    exact AR.one_mem
  | mul x y _ _ ihx ihy =>
    rw [← Pm_mul]
    exact AR.mul_mem ihx ihy
  | inv x _ ih =>
    have hunit : IsUnit (Pm x) :=
      ⟨⟨Pm x, Pm x⁻¹,
        by rw [Pm_mul, mul_inv_cancel, Pm_one],
        by rw [Pm_mul, inv_mul_cancel, Pm_one]⟩, rfl⟩
    obtain ⟨y, hyS, hzy, _⟩ :=
      StarUnits.inv_mem_of_isUnit AR ih hunit
    have hxy : Pm x⁻¹ = y := by
      calc Pm x⁻¹ = Pm x⁻¹ * (Pm x * y) := by
            rw [hzy, Matrix.mul_one]
        _ = (Pm x⁻¹ * Pm x) * y := by rw [Matrix.mul_assoc]
        _ = y := by
            rw [Pm_mul, inv_mul_cancel, Pm_one, Matrix.one_mul]
    rw [hxy]
    exact hyS

theorem Rm_mem : Rm ∈ AR :=
  Algebra.subset_adjoin (by simp)

theorem AR_star : ∀ a ∈ AR, aᴴ ∈ AR := by
  intro a ha
  induction ha using Algebra.adjoin_induction with
  | mem x hx =>
    rcases hx with rfl | rfl | rfl
    · rw [Pm_conjTranspose]; exact Pm_mem _
    · rw [Pm_conjTranspose]; exact Pm_mem _
    · rw [Rm_conjTranspose]; exact Rm_mem
  | algebraMap c =>
    rw [Algebra.algebraMap_eq_smul_one,
      Matrix.conjTranspose_smul, Matrix.conjTranspose_one]
    exact AR.smul_mem AR.one_mem _
  | add x y _ _ ihx ihy =>
    rw [Matrix.conjTranspose_add]
    exact AR.add_mem ihx ihy
  | mul x y _ _ ihx ihy =>
    rw [Matrix.conjTranspose_mul]
    exact AR.mul_mem ihy ihx

/-! ## The pattern matrices and their structure constants

All identities among the five pattern matrices (and their
commutation with the generators) are verified by kernel
computation over `ℤ` and transported to `ℂ` along the cast
ring homomorphism. -/

/-- Reversal pattern matrix over `ℤ`. -/
def RmZ : Matrix E E ℤ := fun e f => if e = rv f then 1 else 0

/-- Same-endpoint (head–head or tail–tail) pattern matrix. -/
def NmZ : Matrix E E ℤ := fun e f =>
  if (e.val.1 = f.val.1 ∧ e.val.2 ≠ f.val.2)
    ∨ (e.val.2 = f.val.2 ∧ e.val.1 ≠ f.val.1) then 1 else 0

/-- Crossed-endpoint (head–tail or tail–head) pattern matrix. -/
def MmZ : Matrix E E ℤ := fun e f =>
  if (e.val.1 = f.val.2 ∧ e.val.2 ≠ f.val.1)
    ∨ (e.val.2 = f.val.1 ∧ e.val.1 ≠ f.val.2) then 1 else 0

/-- Disjoint-edge pattern matrix. -/
def DisZ : Matrix E E ℤ := fun e f =>
  if e.val.1 ≠ f.val.1 ∧ e.val.1 ≠ f.val.2
    ∧ e.val.2 ≠ f.val.1 ∧ e.val.2 ≠ f.val.2 then 1 else 0

/-- Integer permutation matrices of the two controls. -/
def PsZ : Matrix E E ℤ := fun e f =>
  if e = act sPerm f then 1 else 0

def PrZ : Matrix E E ℤ := fun e f =>
  if e = act rPerm f then 1 else 0

/-- Cast an integer pattern matrix to `ℂ`. -/
def cz (A : Matrix E E ℤ) : Matrix E E ℂ :=
  A.map (Int.cast : ℤ → ℂ)

theorem cz_mul (A B : Matrix E E ℤ) :
    cz (A * B) = cz A * cz B :=
  A.map_mul (f := Int.castRingHom ℂ) (M := B)

theorem cz_add (A B : Matrix E E ℤ) :
    cz (A + B) = cz A + cz B :=
  Matrix.map_add _ (by simp) A B

theorem cz_one : cz 1 = 1 :=
  Matrix.map_one _ (by simp) (by simp)

theorem cz_smul (k : ℤ) (A : Matrix E E ℤ) :
    cz (k • A) = (k : ℂ) • cz A := by
  ext e f
  simp only [cz, Matrix.map_apply, Matrix.smul_apply,
    smul_eq_mul, Int.cast_mul]

theorem cz_nsmul (k : ℕ) (A : Matrix E E ℤ) :
    cz (k • A) = (k : ℂ) • cz A := by
  ext e f
  have h : (k • A) e f = (k : ℤ) * A e f := by
    rw [Matrix.smul_apply, nsmul_eq_mul]
  rw [cz, Matrix.map_apply, h, Int.cast_mul,
    Int.cast_natCast, cz, Matrix.smul_apply,
    Matrix.map_apply, smul_eq_mul]

theorem cz_transpose (A : Matrix E E ℤ) :
    (cz A)ᴴ = cz Aᵀ := by
  ext e f
  simp [cz, Matrix.conjTranspose_apply, Matrix.map_apply,
    Matrix.transpose_apply]

theorem cz_inj {A B : Matrix E E ℤ} (h : cz A = cz B) :
    A = B := by
  ext e f
  have h2 := congrArg (fun M => M e f) h
  simpa [cz, Matrix.map_apply] using h2

/-- The complex pattern matrices. -/
def Nm : Matrix E E ℂ := cz NmZ

def Mm : Matrix E E ℂ := cz MmZ

def Dis : Matrix E E ℂ := cz DisZ

theorem Rm_eq_cz : Rm = cz RmZ := by
  ext e f
  simp [Rm, RmZ, cz, Matrix.map_apply, apply_ite
    (Int.cast : ℤ → ℂ)]

theorem Pm_s_eq_cz : Pm sPerm = cz PsZ := by
  ext e f
  simp [Pm, PsZ, cz, Matrix.map_apply, apply_ite
    (Int.cast : ℤ → ℂ)]

theorem Pm_r_eq_cz : Pm rPerm = cz PrZ := by
  ext e f
  simp [Pm, PrZ, cz, Matrix.map_apply, apply_ite
    (Int.cast : ℤ → ℂ)]

/-! ### Structure constants, kernel-verified over `ℤ` -/

theorem hR2 : RmZ * RmZ = 1 := by decide
theorem hRN : RmZ * NmZ = MmZ := by decide
theorem hNR : NmZ * RmZ = MmZ := by decide
theorem hRM : RmZ * MmZ = NmZ := by decide
theorem hMR : MmZ * RmZ = NmZ := by decide
theorem hRD : RmZ * DisZ = DisZ := by decide
theorem hDR : DisZ * RmZ = DisZ := by decide
theorem hN2 : NmZ * NmZ = 4 • 1 + NmZ + MmZ + 2 • DisZ := by
  decide
theorem hM2 : MmZ * MmZ = 4 • 1 + NmZ + MmZ + 2 • DisZ := by
  decide
theorem hNM : NmZ * MmZ = 4 • RmZ + NmZ + MmZ + 2 • DisZ := by
  decide
theorem hMN : MmZ * NmZ = 4 • RmZ + NmZ + MmZ + 2 • DisZ := by
  decide
theorem hND : NmZ * DisZ = NmZ + MmZ := by decide
theorem hDN : DisZ * NmZ = NmZ + MmZ := by decide
theorem hMD : MmZ * DisZ = NmZ + MmZ := by decide
theorem hDM : DisZ * MmZ = NmZ + MmZ := by decide
theorem hD2 : DisZ * DisZ = 2 • 1 + 2 • RmZ := by decide

theorem hsR : PsZ * RmZ = RmZ * PsZ := by decide
theorem hsN : PsZ * NmZ = NmZ * PsZ := by decide
theorem hsM : PsZ * MmZ = MmZ * PsZ := by decide
theorem hsD : PsZ * DisZ = DisZ * PsZ := by decide
theorem hrR : PrZ * RmZ = RmZ * PrZ := by decide
theorem hrN : PrZ * NmZ = NmZ * PrZ := by decide
theorem hrM : PrZ * MmZ = MmZ * PrZ := by decide
theorem hrD : PrZ * DisZ = DisZ * PrZ := by decide

/-! ### The five isotypic projections (24-scaled over `ℤ`)

`Z₁, …, Z₅` are `24 Q` for the five isotypic projections of the
carrier: trivial (dim 1), two-dimensional `(V₂)₊` (dim 2),
even standard `W₊ = C` (dim 3), odd standard `W₋ = G` — the cut
space (dim 3) — and the sign-twisted `(W ⊗ sgn)₋ = P_loop` — the
cycle space (dim 3). -/

def Z1 : Matrix E E ℤ :=
  2 • 1 + 2 • RmZ + 2 • NmZ + 2 • MmZ + 2 • DisZ
def Z2 : Matrix E E ℤ :=
  4 • 1 + 4 • RmZ - 2 • NmZ - 2 • MmZ + 4 • DisZ
def Z3 : Matrix E E ℤ := 6 • 1 + 6 • RmZ - 6 • DisZ
def Z4 : Matrix E E ℤ := 6 • 1 - 6 • RmZ + 3 • NmZ - 3 • MmZ
def Z5 : Matrix E E ℤ := 6 • 1 - 6 • RmZ - 3 • NmZ + 3 • MmZ

theorem hZ11 : Z1 * Z1 = 24 • Z1 := by decide
theorem hZ22 : Z2 * Z2 = 24 • Z2 := by decide
theorem hZ33 : Z3 * Z3 = 24 • Z3 := by decide
theorem hZ44 : Z4 * Z4 = 24 • Z4 := by decide
theorem hZ55 : Z5 * Z5 = 24 • Z5 := by decide
theorem hZ12 : Z1 * Z2 = 0 := by decide
theorem hZ13 : Z1 * Z3 = 0 := by decide
theorem hZ14 : Z1 * Z4 = 0 := by decide
theorem hZ15 : Z1 * Z5 = 0 := by decide
theorem hZ23 : Z2 * Z3 = 0 := by decide
theorem hZ24 : Z2 * Z4 = 0 := by decide
theorem hZ25 : Z2 * Z5 = 0 := by decide
theorem hZ34 : Z3 * Z4 = 0 := by decide
theorem hZ35 : Z3 * Z5 = 0 := by decide
theorem hZ45 : Z4 * Z5 = 0 := by decide

theorem hZsum : Z1 + Z2 + Z3 + Z4 + Z5 = 24 • 1 := by decide

theorem hZ1t : Z1ᵀ = Z1 := by decide
theorem hZ2t : Z2ᵀ = Z2 := by decide
theorem hZ3t : Z3ᵀ = Z3 := by decide
theorem hZ4t : Z4ᵀ = Z4 := by decide
theorem hZ5t : Z5ᵀ = Z5 := by decide

theorem hZ1tr : Z1.trace = 24 := by decide
theorem hZ2tr : Z2.trace = 48 := by decide
theorem hZ3tr : Z3.trace = 72 := by decide
theorem hZ4tr : Z4.trace = 72 := by decide
theorem hZ5tr : Z5.trace = 72 := by decide

theorem hRZ1 : RmZ * Z1 = Z1 := by decide
theorem hNZ1 : NmZ * Z1 = (4:ℤ) • Z1 := by decide
theorem hMZ1 : MmZ * Z1 = (4:ℤ) • Z1 := by decide
theorem hDZ1 : DisZ * Z1 = (2:ℤ) • Z1 := by decide
theorem hRZ2 : RmZ * Z2 = Z2 := by decide
theorem hNZ2 : NmZ * Z2 = (-2) • Z2 := by decide
theorem hMZ2 : MmZ * Z2 = (-2) • Z2 := by decide
theorem hDZ2 : DisZ * Z2 = (2:ℤ) • Z2 := by decide
theorem hRZ3 : RmZ * Z3 = Z3 := by decide
theorem hNZ3 : NmZ * Z3 = 0 := by decide
theorem hMZ3 : MmZ * Z3 = 0 := by decide
theorem hDZ3 : DisZ * Z3 = (-2) • Z3 := by decide
theorem hRZ4 : RmZ * Z4 = -Z4 := by decide
theorem hNZ4 : NmZ * Z4 = (2:ℤ) • Z4 := by decide
theorem hMZ4 : MmZ * Z4 = (-2) • Z4 := by decide
theorem hDZ4 : DisZ * Z4 = 0 := by decide
theorem hRZ5 : RmZ * Z5 = -Z5 := by decide
theorem hNZ5 : NmZ * Z5 = (-2) • Z5 := by decide
theorem hMZ5 : MmZ * Z5 = (2:ℤ) • Z5 := by decide
theorem hDZ5 : DisZ * Z5 = 0 := by decide

theorem hZ1R : Z1 * RmZ = Z1 := by decide
theorem hZ1N : Z1 * NmZ = (4:ℤ) • Z1 := by decide
theorem hZ1M : Z1 * MmZ = (4:ℤ) • Z1 := by decide
theorem hZ1D : Z1 * DisZ = (2:ℤ) • Z1 := by decide
theorem hZ2R : Z2 * RmZ = Z2 := by decide
theorem hZ2N : Z2 * NmZ = (-2) • Z2 := by decide
theorem hZ2M : Z2 * MmZ = (-2) • Z2 := by decide
theorem hZ2D : Z2 * DisZ = (2:ℤ) • Z2 := by decide
theorem hZ3R : Z3 * RmZ = Z3 := by decide
theorem hZ3N : Z3 * NmZ = 0 := by decide
theorem hZ3M : Z3 * MmZ = 0 := by decide
theorem hZ3D : Z3 * DisZ = (-2) • Z3 := by decide
theorem hZ4R : Z4 * RmZ = -Z4 := by decide
theorem hZ4N : Z4 * NmZ = (2:ℤ) • Z4 := by decide
theorem hZ4M : Z4 * MmZ = (-2) • Z4 := by decide
theorem hZ4D : Z4 * DisZ = 0 := by decide
theorem hZ5R : Z5 * RmZ = -Z5 := by decide
theorem hZ5N : Z5 * NmZ = (-2) • Z5 := by decide
theorem hZ5M : Z5 * MmZ = (2:ℤ) • Z5 := by decide
theorem hZ5D : Z5 * DisZ = 0 := by decide

/-- The reversal-even identity `Z₁ + Z₂ + Z₃ = 12(1 + R)`:
the even corner is trivial ⊕ two-dimensional ⊕ even-standard. -/
theorem hZeven : Z1 + Z2 + Z3 = 12 • 1 + 12 • RmZ := by decide

/-! ### Entry formulas for the complex pattern matrices -/

theorem Nm_apply (e f : E) : Nm e f =
    if (e.val.1 = f.val.1 ∧ e.val.2 ≠ f.val.2)
      ∨ (e.val.2 = f.val.2 ∧ e.val.1 ≠ f.val.1)
    then 1 else 0 := by
  simp [Nm, NmZ, cz, Matrix.map_apply,
    apply_ite (Int.cast : ℤ → ℂ)]

theorem Mm_apply (e f : E) : Mm e f =
    if (e.val.1 = f.val.2 ∧ e.val.2 ≠ f.val.1)
      ∨ (e.val.2 = f.val.1 ∧ e.val.1 ≠ f.val.2)
    then 1 else 0 := by
  simp [Mm, MmZ, cz, Matrix.map_apply,
    apply_ite (Int.cast : ℤ → ℂ)]

theorem Dis_apply (e f : E) : Dis e f =
    if e.val.1 ≠ f.val.1 ∧ e.val.1 ≠ f.val.2
      ∧ e.val.2 ≠ f.val.1 ∧ e.val.2 ≠ f.val.2
    then 1 else 0 := by
  simp [Dis, DisZ, cz, Matrix.map_apply,
    apply_ite (Int.cast : ℤ → ℂ)]

/-! ### The commutation relations over `ℂ` -/

theorem s_comm_Nm : Pm sPerm * Nm = Nm * Pm sPerm := by
  rw [Pm_s_eq_cz, Nm, ← cz_mul, ← cz_mul, hsN]

theorem r_comm_Nm : Pm rPerm * Nm = Nm * Pm rPerm := by
  rw [Pm_r_eq_cz, Nm, ← cz_mul, ← cz_mul, hrN]

theorem R_comm_Nm : Rm * Nm = Nm * Rm := by
  rw [Rm_eq_cz, Nm, ← cz_mul, ← cz_mul, hRN, hNR]

theorem s_comm_Mm : Pm sPerm * Mm = Mm * Pm sPerm := by
  rw [Pm_s_eq_cz, Mm, ← cz_mul, ← cz_mul, hsM]

theorem r_comm_Mm : Pm rPerm * Mm = Mm * Pm rPerm := by
  rw [Pm_r_eq_cz, Mm, ← cz_mul, ← cz_mul, hrM]

theorem R_comm_Mm : Rm * Mm = Mm * Rm := by
  rw [Rm_eq_cz, Mm, ← cz_mul, ← cz_mul, hRM, hMR]

theorem s_comm_Dis : Pm sPerm * Dis = Dis * Pm sPerm := by
  rw [Pm_s_eq_cz, Dis, ← cz_mul, ← cz_mul, hsD]

theorem r_comm_Dis : Pm rPerm * Dis = Dis * Pm rPerm := by
  rw [Pm_r_eq_cz, Dis, ← cz_mul, ← cz_mul, hrD]

theorem R_comm_Dis : Rm * Dis = Dis * Rm := by
  rw [Rm_eq_cz, Dis, ← cz_mul, ← cz_mul, hRD, hDR]

/-! ### The commutant of the two-control algebra -/

theorem mem_matCommutant_AR {X : Matrix E E ℂ}
    (hs : Pm sPerm * X = X * Pm sPerm)
    (hr : Pm rPerm * X = X * Pm rPerm)
    (hR : Rm * X = X * Rm) :
    X ∈ matCommutant (AR : Set (Matrix E E ℂ)) := by
  intro a ha
  induction ha using Algebra.adjoin_induction with
  | mem x hx =>
    rcases hx with rfl | rfl | rfl
    · exact hs.symm
    · exact hr.symm
    · exact hR.symm
  | algebraMap c =>
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm,
      smul_mul_assoc, Matrix.mul_one, Matrix.one_mul]
  | add x y _ _ ihx ihy =>
    rw [Matrix.mul_add, Matrix.add_mul, ihx, ihy]
  | mul x y _ _ ihx ihy =>
    rw [← Matrix.mul_assoc, ihx, Matrix.mul_assoc, ihy,
      ← Matrix.mul_assoc]

theorem span_subset_commutant :
    (Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
        Set (Matrix E E ℂ)) : Set (Matrix E E ℂ))
      ⊆ matCommutant (AR : Set (Matrix E E ℂ)) := by
  intro X hX
  induction hX using Submodule.span_induction with
  | mem y hy =>
    simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
      at hy
    rcases hy with rfl | rfl | rfl | rfl | rfl
    · exact mem_matCommutant_AR
        (by rw [Matrix.mul_one, Matrix.one_mul])
        (by rw [Matrix.mul_one, Matrix.one_mul])
        (by rw [Matrix.mul_one, Matrix.one_mul])
    · exact mem_matCommutant_AR (Pm_mul_Rm sPerm)
        (Pm_mul_Rm rPerm) rfl
    · exact mem_matCommutant_AR s_comm_Nm r_comm_Nm R_comm_Nm
    · exact mem_matCommutant_AR s_comm_Mm r_comm_Mm R_comm_Mm
    · exact mem_matCommutant_AR s_comm_Dis r_comm_Dis
        R_comm_Dis
  | zero =>
    intro a _
    rw [Matrix.zero_mul, Matrix.mul_zero]
  | add x y _ _ ihx ihy =>
    intro a ha
    rw [Matrix.add_mul, Matrix.mul_add, ihx a ha, ihy a ha]
  | smul c x _ ih =>
    intro a ha
    rw [smul_mul_assoc, mul_smul_comm, ih a ha]

/-! ### Transport permutations for the pattern chase -/

/-- The permutation sending `0,1,2,3` to a given enumeration. -/
noncomputable def tupPerm (i j k l : V) (hij : i ≠ j) (hik : i ≠ k)
    (hil : i ≠ l) (hjk : j ≠ k) (hjl : j ≠ l)
    (hkl : k ≠ l) : Equiv.Perm V :=
  Equiv.ofBijective ![i, j, k, l]
    (Finite.injective_iff_bijective.mp (by
      intro a b hab
      fin_cases a <;> fin_cases b <;> simp_all))

theorem exists_fourth (i j k : V) :
    ∃ m : V, m ≠ i ∧ m ≠ j ∧ m ≠ k := by
  have hne : ((({i, j, k} : Finset V))ᶜ).Nonempty := by
    rw [← Finset.card_pos, Finset.card_compl,
      Fintype.card_fin]
    have hcard : ({i, j, k} : Finset V).card ≤ 3 :=
      (Finset.card_insert_le _ _).trans
        (Nat.add_le_add_right (Finset.card_insert_le _ _) 1)
    omega
  obtain ⟨m, hm⟩ := hne
  rw [Finset.mem_compl, Finset.mem_insert,
    Finset.mem_insert, Finset.mem_singleton] at hm
  exact ⟨m, fun h => hm (Or.inl h),
    fun h => hm (Or.inr (Or.inl h)),
    fun h => hm (Or.inr (Or.inr h))⟩

/-- Reference directed edges. -/
def e01 : E := ⟨(0, 1), by decide⟩
def e10 : E := ⟨(1, 0), by decide⟩
def e02 : E := ⟨(0, 2), by decide⟩
def e12 : E := ⟨(1, 2), by decide⟩
def e23 : E := ⟨(2, 3), by decide⟩

theorem commutant_subset_span :
    matCommutant (AR : Set (Matrix E E ℂ))
      ⊆ (Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
          Set (Matrix E E ℂ)) : Set (Matrix E E ℂ)) := by
  intro X hX
  have hall : ∀ σ : Equiv.Perm V, X * Pm σ = Pm σ * X :=
    fun σ => hX (Pm σ) (Pm_mem σ)
  have hRc : X * Rm = Rm * X := hX Rm Rm_mem
  have hXP : ∀ (σ : Equiv.Perm V) (e f : E),
      (X * Pm σ) e f = X e (act σ f) := by
    intro σ e f
    rw [Matrix.mul_apply,
      Finset.sum_eq_single (act σ f)
        (fun h _ hne => by
          rw [Pm_apply σ h f, if_neg hne, mul_zero])
        (fun h => absurd (Finset.mem_univ _) h),
      Pm_apply σ (act σ f) f, if_pos rfl, mul_one]
  have hPX : ∀ (σ : Equiv.Perm V) (e f : E),
      (Pm σ * X) e f = X (act σ⁻¹ e) f := by
    intro σ e f
    rw [Matrix.mul_apply,
      Finset.sum_eq_single (act σ⁻¹ e)
        (fun h _ hne => by
          rw [Pm_apply σ e h, if_neg (fun hc => hne (by
            rw [hc, ← act_mul, inv_mul_cancel, act_one])),
            zero_mul])
        (fun h => absurd (Finset.mem_univ _) h),
      Pm_apply σ e (act σ⁻¹ e), ← act_mul, mul_inv_cancel,
      act_one, if_pos rfl, one_mul]
  have hinv : ∀ (σ : Equiv.Perm V) (e f : E),
      X (act σ e) (act σ f) = X e f := by
    intro σ e f
    have h1 : X (act σ e) (act σ f)
        = (X * Pm σ) (act σ e) f := (hXP σ (act σ e) f).symm
    rw [hall σ, hPX, ← act_mul, inv_mul_cancel, act_one]
      at h1
    exact h1
  have hXR : ∀ e f : E, (X * Rm) e f = X e (rv f) := by
    intro e f
    rw [Matrix.mul_apply,
      Finset.sum_eq_single (rv f)
        (fun h _ hne => by
          rw [Rm_apply h f, if_neg hne, mul_zero])
        (fun h => absurd (Finset.mem_univ _) h),
      Rm_apply (rv f) f, if_pos rfl, mul_one]
  have hRX : ∀ e f : E, (Rm * X) e f = X (rv e) f := by
    intro e f
    rw [Matrix.mul_apply,
      Finset.sum_eq_single (rv e)
        (fun h _ hne => by
          rw [Rm_apply e h, if_neg (fun hc => hne (by
            rw [hc, rv_rv])), zero_mul])
        (fun h => absurd (Finset.mem_univ _) h),
      Rm_apply e (rv e), rv_rv, if_pos rfl, one_mul]
  have hrev : ∀ e f : E, X (rv e) (rv f) = X e f := by
    intro e f
    have h1 : X (rv e) (rv f) = (X * Rm) (rv e) f :=
      (hXR (rv e) f).symm
    rw [hRc, hRX, rv_rv] at h1
    exact h1
  -- the five pattern-transport lemmas
  have L5 : ∀ (i j k l : V) (hij : i ≠ j) (hkl : k ≠ l)
      (hik : i ≠ k) (hil : i ≠ l) (hjk : j ≠ k)
      (hjl : j ≠ l),
      X ⟨(i, j), hij⟩ ⟨(k, l), hkl⟩ = X e01 e23 := by
    intro i j k l hij hkl hik hil hjk hjl
    have h := hinv
      (tupPerm i j k l hij hik hil hjk hjl hkl) e01 e23
    exact h
  have L1 : ∀ (i j : V) (hij : i ≠ j),
      X ⟨(i, j), hij⟩ ⟨(i, j), hij⟩ = X e01 e01 := by
    intro i j hij
    obtain ⟨k, hki, hkj, -⟩ := exists_fourth i j i
    obtain ⟨l, hli, hlj, hlk⟩ := exists_fourth i j k
    have h := hinv (tupPerm i j k l hij (Ne.symm hki)
      (Ne.symm hli) (Ne.symm hkj) (Ne.symm hlj)
      (Ne.symm hlk)) e01 e01
    exact h
  have L2 : ∀ (i j : V) (hij : i ≠ j),
      X ⟨(i, j), hij⟩ ⟨(j, i), Ne.symm hij⟩
        = X e01 e10 := by
    intro i j hij
    obtain ⟨k, hki, hkj, -⟩ := exists_fourth i j i
    obtain ⟨l, hli, hlj, hlk⟩ := exists_fourth i j k
    have h := hinv (tupPerm i j k l hij (Ne.symm hki)
      (Ne.symm hli) (Ne.symm hkj) (Ne.symm hlj)
      (Ne.symm hlk)) e01 e10
    exact h
  have L3 : ∀ (i j l : V) (hij : i ≠ j) (hil : i ≠ l)
      (hjl : j ≠ l),
      X ⟨(i, j), hij⟩ ⟨(i, l), hil⟩ = X e01 e02 := by
    intro i j l hij hil hjl
    obtain ⟨m, hmi, hmj, hml⟩ := exists_fourth i j l
    have h := hinv (tupPerm i j l m hij hil (Ne.symm hmi)
      hjl (Ne.symm hmj) (Ne.symm hml)) e01 e02
    exact h
  have L4 : ∀ (i j l : V) (hij : i ≠ j) (hjl : j ≠ l)
      (hil : i ≠ l),
      X ⟨(i, j), hij⟩ ⟨(j, l), hjl⟩ = X e01 e12 := by
    intro i j l hij hjl hil
    obtain ⟨m, hmi, hmj, hml⟩ := exists_fourth i j l
    have h := hinv (tupPerm i j l m hij hil (Ne.symm hmi)
      hjl (Ne.symm hmj) (Ne.symm hml)) e01 e12
    exact h
  -- the explicit five-parameter form
  have hXeq : X = X e01 e01 • (1 : Matrix E E ℂ)
      + X e01 e10 • Rm + X e01 e02 • Nm
      + X e01 e12 • Mm + X e01 e23 • Dis := by
    ext e f
    obtain ⟨⟨i, j⟩, hij⟩ := e
    obtain ⟨⟨k, l⟩, hkl⟩ := f
    simp only [Matrix.add_apply, Matrix.smul_apply,
      Matrix.one_apply, Rm_apply, Nm_apply, Mm_apply,
      Dis_apply, smul_eq_mul, rv, Subtype.mk.injEq,
      Prod.mk.injEq]
    by_cases hik : i = k
    · subst hik
      by_cases hjl : j = l
      · subst hjl
        rw [L1 i j hij]
        simp [hij, Ne.symm hij]
      · rw [L3 i j l hij hkl hjl]
        simp [hjl, hkl, Ne.symm hij]
    · by_cases hjl : j = l
      · subst hjl
        have hjk : j ≠ k := Ne.symm hkl
        have h1 : X ⟨(i, j), hij⟩ ⟨(k, j), hkl⟩
            = X ⟨(j, i), Ne.symm hij⟩ ⟨(j, k), hjk⟩ :=
          hrev ⟨(j, i), Ne.symm hij⟩ ⟨(j, k), hjk⟩
        rw [h1, L3 j i k (Ne.symm hij) hjk hik]
        simp [hij, hik, hjk]
      · by_cases hjk : j = k
        · subst hjk
          by_cases hil : i = l
          · subst hil
            rw [L2 i j hij]
            simp [hij, Ne.symm hij]
          · rw [L4 i j l hij hkl hil]
            simp [hij, hil, hkl]
        · by_cases hil : i = l
          · subst hil
            have h1 : X ⟨(i, j), hij⟩ ⟨(k, i), hkl⟩
                = X ⟨(j, i), Ne.symm hij⟩
                  ⟨(i, k), Ne.symm hkl⟩ :=
              hrev ⟨(j, i), Ne.symm hij⟩
                ⟨(i, k), Ne.symm hkl⟩
            rw [h1, L4 j i k (Ne.symm hij) (Ne.symm hkl)
              hjk]
            simp [hik, hjk, Ne.symm hij]
          · rw [L5 i j k l hij hkl hik hil hjk hjl]
            simp [hik, hil, hjk, hjl]
  rw [hXeq]
  refine Submodule.add_mem _ (Submodule.add_mem _
    (Submodule.add_mem _ (Submodule.add_mem _ ?_ ?_) ?_)
      ?_) ?_ <;>
    exact Submodule.smul_mem _ _
      (Submodule.subset_span (by simp))

/-- **The commutant identification**: the commutant of
`C^*(U_s, U_r, R_ι)` is exactly the five-dimensional span of
the pattern matrices — scalar on each of the five irreducible
summands of the residual carrier. -/
theorem commutant_eq :
    matCommutant (AR : Set (Matrix E E ℂ))
      = (Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
          Set (Matrix E E ℂ)) : Set (Matrix E E ℂ)) :=
  Set.Subset.antisymm commutant_subset_span
    span_subset_commutant

/-- **The bicommutant identification (SM.0h)**: the
two-control algebra is the full commutant of the
five-dimensional pattern span — the complete block algebra
`ℂ ⊕ M₃(ℂ)_C ⊕ M₂(ℂ)_{W₂} ⊕ M₃(ℂ)_G ⊕ M₃(ℂ)_{P_loop}` of the
five isotypic components. -/
theorem bicommutant_eq :
    (AR : Set (Matrix E E ℂ))
      = matCommutant ((Submodule.span ℂ
          ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :
            Submodule ℂ (Matrix E E ℂ)) :
          Set (Matrix E E ℂ)) := by
  rw [← commutant_eq]
  exact (FiniteStarSubalgebraMutualCommutant.mutualCommutants
    AR AR_star).symm

/-! ### The five central block projections over `ℂ` -/

theorem cz_zero : cz (0 : Matrix E E ℤ) = 0 := by
  ext e f
  simp [cz]

noncomputable def Qtype : Matrix E E ℂ := (24:ℂ)⁻¹ • cz Z1
noncomputable def QW2 : Matrix E E ℂ := (24:ℂ)⁻¹ • cz Z2
noncomputable def QC : Matrix E E ℂ := (24:ℂ)⁻¹ • cz Z3
noncomputable def QG : Matrix E E ℂ := (24:ℂ)⁻¹ • cz Z4
noncomputable def QP : Matrix E E ℂ := (24:ℂ)⁻¹ • cz Z5

theorem czQ_mul_self {Z : Matrix E E ℤ}
    (h : Z * Z = 24 • Z) :
    ((24:ℂ)⁻¹ • cz Z) * ((24:ℂ)⁻¹ • cz Z)
      = (24:ℂ)⁻¹ • cz Z := by
  rw [smul_mul_assoc, mul_smul_comm, ← cz_mul, h, cz_nsmul,
    smul_smul, smul_smul,
    show (24:ℂ)⁻¹ * (24:ℂ)⁻¹ * ((24:ℕ):ℂ) = (24:ℂ)⁻¹ by
      norm_num]

theorem czQ_mul_zero {Z W : Matrix E E ℤ} (h : Z * W = 0) :
    ((24:ℂ)⁻¹ • cz Z) * ((24:ℂ)⁻¹ • cz W) = 0 := by
  rw [smul_mul_assoc, mul_smul_comm, ← cz_mul, h, cz_zero,
    smul_zero, smul_zero]

theorem czQ_herm {Z : Matrix E E ℤ} (h : Zᵀ = Z) :
    ((24:ℂ)⁻¹ • cz Z)ᴴ = (24:ℂ)⁻¹ • cz Z := by
  rw [Matrix.conjTranspose_smul, cz_transpose, h,
    star_inv₀, star_ofNat]

theorem cz_trace (A : Matrix E E ℤ) :
    (cz A).trace = ((A.trace : ℤ) : ℂ) := by
  simp [Matrix.trace, Matrix.diag, cz, Matrix.map_apply]

theorem Qtype_idem : Qtype * Qtype = Qtype := czQ_mul_self hZ11
theorem QW2_idem : QW2 * QW2 = QW2 := czQ_mul_self hZ22
theorem QC_idem : QC * QC = QC := czQ_mul_self hZ33
theorem QG_idem : QG * QG = QG := czQ_mul_self hZ44
theorem QP_idem : QP * QP = QP := czQ_mul_self hZ55

theorem Qtype_herm : Qtypeᴴ = Qtype := czQ_herm hZ1t
theorem QW2_herm : QW2ᴴ = QW2 := czQ_herm hZ2t
theorem QC_herm : QCᴴ = QC := czQ_herm hZ3t
theorem QG_herm : QGᴴ = QG := czQ_herm hZ4t
theorem QP_herm : QPᴴ = QP := czQ_herm hZ5t

theorem orth_symm {P Q : Matrix E E ℂ} (hP : Pᴴ = P)
    (hQ : Qᴴ = Q) (h : P * Q = 0) : Q * P = 0 := by
  have h2 := congrArg Matrix.conjTranspose h
  rwa [Matrix.conjTranspose_mul, hP, hQ,
    Matrix.conjTranspose_zero] at h2

theorem Qtype_QW2 : Qtype * QW2 = 0 := czQ_mul_zero hZ12
theorem Qtype_QC : Qtype * QC = 0 := czQ_mul_zero hZ13
theorem Qtype_QG : Qtype * QG = 0 := czQ_mul_zero hZ14
theorem Qtype_QP : Qtype * QP = 0 := czQ_mul_zero hZ15
theorem QW2_QC : QW2 * QC = 0 := czQ_mul_zero hZ23
theorem QW2_QG : QW2 * QG = 0 := czQ_mul_zero hZ24
theorem QW2_QP : QW2 * QP = 0 := czQ_mul_zero hZ25
theorem QC_QG : QC * QG = 0 := czQ_mul_zero hZ34
theorem QC_QP : QC * QP = 0 := czQ_mul_zero hZ35
theorem QG_QP : QG * QP = 0 := czQ_mul_zero hZ45

theorem Qsum : Qtype + QW2 + QC + QG + QP = 1 := by
  rw [Qtype, QW2, QC, QG, QP, ← smul_add, ← smul_add,
    ← smul_add, ← smul_add, ← cz_add, ← cz_add, ← cz_add,
    ← cz_add, hZsum, cz_nsmul, cz_one, smul_smul,
    show (24:ℂ)⁻¹ * ((24:ℕ):ℂ) = 1 by norm_num, one_smul]

/-- The block dimensions `1, 2, 3, 3, 3`. -/
theorem Qtype_trace : Qtype.trace = 1 := by
  rw [Qtype, Matrix.trace_smul, cz_trace, hZ1tr,
    smul_eq_mul]
  norm_num

theorem QW2_trace : QW2.trace = 2 := by
  rw [QW2, Matrix.trace_smul, cz_trace, hZ2tr, smul_eq_mul]
  norm_num

theorem QC_trace : QC.trace = 3 := by
  rw [QC, Matrix.trace_smul, cz_trace, hZ3tr, smul_eq_mul]
  norm_num

theorem QG_trace : QG.trace = 3 := by
  rw [QG, Matrix.trace_smul, cz_trace, hZ4tr, smul_eq_mul]
  norm_num

theorem QP_trace : QP.trace = 3 := by
  rw [QP, Matrix.trace_smul, cz_trace, hZ5tr, smul_eq_mul]
  norm_num

/-- **(SM.0i)** The reversal-even corner deletes the trivial
type line and is carried by `M₃(ℂ)_C ⊕ M₂(ℂ)_{W₂}`:
`Qtype + QW2 + QC` is the even projector `(1 + R_ι)/2`. -/
theorem even_corner :
    Qtype + QW2 + QC = (2:ℂ)⁻¹ • (1 + Rm) := by
  rw [Qtype, QW2, QC, ← smul_add, ← smul_add, ← cz_add,
    ← cz_add, hZeven, cz_add, cz_nsmul, cz_nsmul, cz_one,
    ← Rm_eq_cz, smul_add, smul_smul, smul_smul,
    show (24:ℂ)⁻¹ * ((12:ℕ):ℂ) = (2:ℂ)⁻¹ by norm_num,
    smul_add]

/-! ### Membership and centrality of the block projections -/

theorem basis_pair_comm :
    ∀ x ∈ ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)),
    ∀ y ∈ ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)),
      x * y = y * x := by
  have hNMc : Nm * Mm = Mm * Nm := by
    rw [Nm, Mm, ← cz_mul, ← cz_mul, hNM, hMN]
  have hNDc : Nm * Dis = Dis * Nm := by
    rw [Nm, Dis, ← cz_mul, ← cz_mul, hND, hDN]
  have hMDc : Mm * Dis = Dis * Mm := by
    rw [Mm, Dis, ← cz_mul, ← cz_mul, hMD, hDM]
  intro x hx y hy
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff]
    at hx hy
  rcases hx with rfl | rfl | rfl | rfl | rfl <;>
    rcases hy with rfl | rfl | rfl | rfl | rfl <;>
    first
      | rfl
      | rw [Matrix.one_mul, Matrix.mul_one]
      | exact R_comm_Nm
      | exact R_comm_Nm.symm
      | exact R_comm_Mm
      | exact R_comm_Mm.symm
      | exact R_comm_Dis
      | exact R_comm_Dis.symm
      | exact hNMc
      | exact hNMc.symm
      | exact hNDc
      | exact hNDc.symm
      | exact hMDc
      | exact hMDc.symm

theorem span_comm :
    ∀ x ∈ Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
      Set (Matrix E E ℂ)),
    ∀ y ∈ Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
      Set (Matrix E E ℂ)), x * y = y * x := by
  intro x hx
  induction hx using Submodule.span_induction with
  | mem x hxm =>
    intro y hy
    induction hy using Submodule.span_induction with
    | mem y hym => exact basis_pair_comm x hxm y hym
    | zero => rw [Matrix.mul_zero, Matrix.zero_mul]
    | add y z _ _ ihy ihz =>
      rw [Matrix.mul_add, Matrix.add_mul, ihy, ihz]
    | smul c y _ ihy =>
      rw [mul_smul_comm, smul_mul_assoc, ihy]
  | zero =>
    intro y _
    rw [Matrix.zero_mul, Matrix.mul_zero]
  | add x z _ _ ihx ihz =>
    intro y hy
    rw [Matrix.add_mul, Matrix.mul_add, ihx y hy, ihz y hy]
  | smul c x _ ihx =>
    intro y hy
    rw [smul_mul_assoc, mul_smul_comm, ihx y hy]

theorem czQ_mem_span {Z : Matrix E E ℤ} (a b c d e : ℤ)
    (h : Z = a • 1 + b • RmZ + c • NmZ + d • MmZ + e • DisZ) :
    ((24:ℂ)⁻¹ • cz Z) ∈ Submodule.span ℂ
      ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) := by
  refine Submodule.smul_mem _ _ ?_
  rw [h, cz_add, cz_add, cz_add, cz_add, cz_smul, cz_smul,
    cz_smul, cz_smul, cz_smul, cz_one, ← Rm_eq_cz, ← Nm,
    ← Mm, ← Dis]
  refine Submodule.add_mem _ (Submodule.add_mem _
    (Submodule.add_mem _ (Submodule.add_mem _ ?_ ?_) ?_)
      ?_) ?_ <;>
    exact Submodule.smul_mem _ _
      (Submodule.subset_span (by simp))

theorem Qtype_mem_span : Qtype ∈ Submodule.span ℂ
    ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :=
  czQ_mem_span 2 2 2 2 2 (by decide)

theorem QW2_mem_span : QW2 ∈ Submodule.span ℂ
    ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :=
  czQ_mem_span 4 4 (-2) (-2) 4 (by decide)

theorem QC_mem_span : QC ∈ Submodule.span ℂ
    ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :=
  czQ_mem_span 6 6 0 0 (-6) (by decide)

theorem QG_mem_span : QG ∈ Submodule.span ℂ
    ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :=
  czQ_mem_span 6 (-6) 3 (-3) 0 (by decide)

theorem QP_mem_span : QP ∈ Submodule.span ℂ
    ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)) :=
  czQ_mem_span 6 (-6) (-3) 3 0 (by decide)

/-- The block projections are central for the two-control
algebra: they commute with every element of `AR`. -/
theorem Q_central {Q : Matrix E E ℂ}
    (hQ : Q ∈ Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
      Set (Matrix E E ℂ))) :
    ∀ a ∈ AR, Q * a = a * Q :=
  fun a ha => span_subset_commutant hQ a ha

/-- The block projections belong to the two-control algebra
itself. -/
theorem Q_mem_AR {Q : Matrix E E ℂ}
    (hQ : Q ∈ Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
      Set (Matrix E E ℂ))) :
    Q ∈ AR := by
  rw [← SetLike.mem_coe (p := AR), bicommutant_eq]
  intro a ha
  exact span_comm Q hQ a ha

/-! ### Block fullness: every corner lies in the algebra -/

theorem cz_eigen {B Z : Matrix E E ℤ} {β : ℤ}
    (hL : B * Z = β • Z) (hR : Z * B = β • Z)
    {Bc : Matrix E E ℂ} (hBc : Bc = cz B) :
    Bc * ((24:ℂ)⁻¹ • cz Z) = (β:ℂ) • ((24:ℂ)⁻¹ • cz Z)
      ∧ ((24:ℂ)⁻¹ • cz Z) * Bc
        = (β:ℂ) • ((24:ℂ)⁻¹ • cz Z) := by
  constructor
  · rw [hBc, mul_smul_comm, ← cz_mul, hL, cz_smul,
      smul_smul, smul_smul, mul_comm]
  · rw [hBc, smul_mul_assoc, ← cz_mul, hR, cz_smul,
      smul_smul, smul_smul, mul_comm]

/-- Corner absorption: if every basis element acts on `Q` as a
scalar on both sides, every compression `Q X Q` lies in `AR`. -/
theorem corner_mem {Q : Matrix E E ℂ}
    (hcomm : ∀ B ∈ ({1, Rm, Nm, Mm, Dis} :
        Set (Matrix E E ℂ)),
      ∃ β : ℂ, B * Q = β • Q ∧ Q * B = β • Q)
    (X : Matrix E E ℂ) : Q * X * Q ∈ AR := by
  rw [← SetLike.mem_coe (p := AR), bicommutant_eq]
  intro a ha
  induction ha using Submodule.span_induction with
  | mem y hy =>
    obtain ⟨β, h1, h2⟩ := hcomm y hy
    rw [Matrix.mul_assoc (Q * X) Q y, h2, mul_smul_comm,
      ← Matrix.mul_assoc y (Q * X) Q,
      ← Matrix.mul_assoc y Q X, h1, smul_mul_assoc,
      smul_mul_assoc]
  | zero => rw [Matrix.mul_zero, Matrix.zero_mul]
  | add y z _ _ ihy ihz =>
    rw [Matrix.mul_add, Matrix.add_mul, ihy, ihz]
  | smul c y _ ihy =>
    rw [mul_smul_comm, smul_mul_assoc, ihy]

theorem corner_hyp {Z : Matrix E E ℤ} (rβ nβ mβ dβ : ℤ)
    (hr : RmZ * Z = rβ • Z) (hr' : Z * RmZ = rβ • Z)
    (hn : NmZ * Z = nβ • Z) (hn' : Z * NmZ = nβ • Z)
    (hm : MmZ * Z = mβ • Z) (hm' : Z * MmZ = mβ • Z)
    (hd : DisZ * Z = dβ • Z) (hd' : Z * DisZ = dβ • Z) :
    ∀ B ∈ ({1, Rm, Nm, Mm, Dis} : Set (Matrix E E ℂ)),
      ∃ β : ℂ,
        B * ((24:ℂ)⁻¹ • cz Z) = β • ((24:ℂ)⁻¹ • cz Z)
        ∧ ((24:ℂ)⁻¹ • cz Z) * B
          = β • ((24:ℂ)⁻¹ • cz Z) := by
  intro B hB
  simp only [Set.mem_insert_iff, Set.mem_singleton_iff] at hB
  rcases hB with rfl | rfl | rfl | rfl | rfl
  · exact ⟨1, by rw [Matrix.one_mul, one_smul],
      by rw [Matrix.mul_one, one_smul]⟩
  · exact ⟨(rβ : ℂ), cz_eigen hr hr' Rm_eq_cz⟩
  · exact ⟨(nβ : ℂ), cz_eigen hn hn' rfl⟩
  · exact ⟨(mβ : ℂ), cz_eigen hm hm' rfl⟩
  · exact ⟨(dβ : ℂ), cz_eigen hd hd' rfl⟩

theorem Qtype_corner_mem (X : Matrix E E ℂ) :
    Qtype * X * Qtype ∈ AR :=
  corner_mem (corner_hyp 1 4 4 2
    (by rw [hRZ1, one_smul]) (by rw [hZ1R, one_smul])
    hNZ1 hZ1N hMZ1 hZ1M hDZ1 hZ1D) X

theorem QW2_corner_mem (X : Matrix E E ℂ) :
    QW2 * X * QW2 ∈ AR :=
  corner_mem (corner_hyp 1 (-2) (-2) 2
    (by rw [hRZ2, one_smul]) (by rw [hZ2R, one_smul])
    hNZ2 hZ2N hMZ2 hZ2M hDZ2 hZ2D) X

theorem QC_corner_mem (X : Matrix E E ℂ) :
    QC * X * QC ∈ AR :=
  corner_mem (corner_hyp 1 0 0 (-2)
    (by rw [hRZ3, one_smul]) (by rw [hZ3R, one_smul])
    (by rw [hNZ3, zero_smul]) (by rw [hZ3N, zero_smul])
    (by rw [hMZ3, zero_smul]) (by rw [hZ3M, zero_smul])
    hDZ3 hZ3D) X

theorem QG_corner_mem (X : Matrix E E ℂ) :
    QG * X * QG ∈ AR :=
  corner_mem (corner_hyp (-1) 2 (-2) 0
    (by rw [hRZ4, neg_smul, one_smul])
    (by rw [hZ4R, neg_smul, one_smul])
    hNZ4 hZ4N hMZ4 hZ4M
    (by rw [hDZ4, zero_smul]) (by rw [hZ4D, zero_smul])) X

theorem QP_corner_mem (X : Matrix E E ℂ) :
    QP * X * QP ∈ AR :=
  corner_mem (corner_hyp (-1) (-2) 2 0
    (by rw [hRZ5, neg_smul, one_smul])
    (by rw [hZ5R, neg_smul, one_smul])
    hNZ5 hZ5N hMZ5 hZ5M
    (by rw [hDZ5, zero_smul]) (by rw [hZ5D, zero_smul])) X

/-- **Peirce decomposition**: every element of the
two-control algebra is the sum of its five block corners. -/
theorem peirce_decomposition (X : Matrix E E ℂ)
    (hX : X ∈ AR) :
    X = Qtype * X * Qtype + QW2 * X * QW2 + QC * X * QC
      + QG * X * QG + QP * X * QP := by
  have habs : ∀ Q : Matrix E E ℂ,
      Q ∈ Submodule.span ℂ ({1, Rm, Nm, Mm, Dis} :
        Set (Matrix E E ℂ)) → Q * Q = Q →
      Q * X * Q = Q * X := by
    intro Q hQ hidem
    rw [Matrix.mul_assoc, ← Q_central hQ X hX,
      ← Matrix.mul_assoc, hidem]
  rw [habs Qtype Qtype_mem_span Qtype_idem,
    habs QW2 QW2_mem_span QW2_idem,
    habs QC QC_mem_span QC_idem,
    habs QG QG_mem_span QG_idem,
    habs QP QP_mem_span QP_idem,
    ← Matrix.add_mul, ← Matrix.add_mul, ← Matrix.add_mul,
    ← Matrix.add_mul, Qsum, Matrix.one_mul]

/-! ### Minimality: one unitary control is not enough -/

theorem single_control_commutative (U : Matrix E E ℂ)
    (h1 : U * Uᴴ = 1) (h2 : Uᴴ * U = 1) :
    ∀ x ∈ Algebra.adjoin ℂ ({U, Uᴴ} :
      Set (Matrix E E ℂ)),
    ∀ y ∈ Algebra.adjoin ℂ ({U, Uᴴ} :
      Set (Matrix E E ℂ)), x * y = y * x := by
  have hUU : U * Uᴴ = Uᴴ * U := by rw [h1, h2]
  intro x hx
  induction hx using Algebra.adjoin_induction with
  | mem u hu =>
    intro y hy
    induction hy using Algebra.adjoin_induction with
    | mem v hv =>
      rcases hu with rfl | rfl <;> rcases hv with rfl | rfl
      · rfl
      · exact hUU
      · exact hUU.symm
      · rfl
    | algebraMap c =>
      rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm,
        smul_mul_assoc, Matrix.mul_one, Matrix.one_mul]
    | add v w _ _ ihv ihw =>
      rw [Matrix.mul_add, Matrix.add_mul, ihv, ihw]
    | mul v w _ _ ihv ihw =>
      rw [← Matrix.mul_assoc, ihv, Matrix.mul_assoc, ihw,
        ← Matrix.mul_assoc]
  | algebraMap c =>
    intro y _
    rw [Algebra.algebraMap_eq_smul_one, mul_smul_comm,
      smul_mul_assoc, Matrix.mul_one, Matrix.one_mul]
  | add v w _ _ ihv ihw =>
    intro y hy
    rw [Matrix.add_mul, Matrix.mul_add, ihv y hy, ihw y hy]
  | mul v w _ _ ihv ihw =>
    intro y hy
    rw [Matrix.mul_assoc, ihw y hy, ← Matrix.mul_assoc,
      ihv y hy, Matrix.mul_assoc]

theorem AR_noncommutative :
    Pm sPerm * Pm rPerm ≠ Pm rPerm * Pm sPerm := by
  rw [Pm_mul, Pm_mul]
  intro h
  have h2 := congrArg (fun M => M e02 e01) h
  simp only [Pm_apply] at h2
  rw [if_pos (by decide), if_neg (by decide)] at h2
  exact one_ne_zero h2

/-- **Minimality**: no single unitary control generates the
two-control algebra — a `C^*`-algebra generated by one
unitary is commutative, and `AR` carries noncommutative
matrix blocks. -/
theorem no_single_control (U : Matrix E E ℂ)
    (h1 : U * Uᴴ = 1) (h2 : Uᴴ * U = 1) :
    Algebra.adjoin ℂ ({U, Uᴴ} : Set (Matrix E E ℂ))
      ≠ AR := by
  intro heq
  have hcomm := single_control_commutative U h1 h2
  rw [heq] at hcomm
  exact AR_noncommutative
    (hcomm (Pm sPerm) (Algebra.subset_adjoin (by simp))
      (Pm rPerm) (Algebra.subset_adjoin (by simp)))

/-! ### Determinant characters of the two even
noncommutative blocks (SM.0j)

The `C`- and `W₂`-blocks are compressed to `3×3` and `2×2`
matrix representations by explicit rational quasi-inverse
pairs `(T, S)` with `T S = 1` and `S T = Q`; the determinant
characters of both compressions equal the sign character. -/

/-- Cast an integer matrix of any shape to `ℂ`. -/
def ci {m n : Type} (A : Matrix m n ℤ) : Matrix m n ℂ :=
  A.map (Int.cast : ℤ → ℂ)

theorem ci_mul {l m n : Type} [Fintype m]
    (A : Matrix l m ℤ) (B : Matrix m n ℤ) :
    ci (A * B) = ci A * ci B :=
  A.map_mul (f := Int.castRingHom ℂ) (M := B)

theorem ci_nsmul {m n : Type} (k : ℕ) (A : Matrix m n ℤ) :
    ci (k • A) = (k : ℂ) • ci A := by
  ext e f
  have h : (k • A) e f = (k : ℤ) * A e f := by
    rw [Matrix.smul_apply, nsmul_eq_mul]
  rw [ci, Matrix.map_apply, h, Int.cast_mul,
    Int.cast_natCast, ci, Matrix.smul_apply,
    Matrix.map_apply, smul_eq_mul]

theorem ci_add {m n : Type} (A B : Matrix m n ℤ) :
    ci (A + B) = ci A + ci B :=
  Matrix.map_add _ (by simp) A B

theorem ci_sub {m n : Type} (A B : Matrix m n ℤ) :
    ci (A - B) = ci A - ci B := by
  ext e f
  simp [ci, Matrix.map_apply]

theorem ci_one {m : Type} [Fintype m] [DecidableEq m] :
    ci (1 : Matrix m m ℤ) = 1 :=
  Matrix.map_one _ (by simp) (by simp)

theorem cz_eq_ci (A : Matrix E E ℤ) : cz A = ci A := rfl

/-- Vertex-difference profile of the even-standard basis. -/
def phivZ (c : Fin 3) (x : V) : ℤ :=
  if x.val = c.val then 1 else if x.val = 3 then -1 else 0

/-- The even-standard (`C`-block) basis columns
`y_c(i,j) = φ_c(i) + φ_c(j)`, `φ_c = e_c − e_3`. -/
def S3z : Matrix E (Fin 3) ℤ := fun e c =>
  phivZ c e.val.1 + phivZ c e.val.2

/-- The adjugate-scaled left inverse (`16` times the true
pseudo-inverse). -/
def T3z : Matrix (Fin 3) E ℤ :=
  (!![3,-1,-1;-1,3,-1;-1,-1,3] :
    Matrix (Fin 3) (Fin 3) ℤ) * S3zᵀ

/-- Matching indicators via endpoint sums: the three perfect
matchings of `K₄` have endpoint-sum sets `{1,5}, {2,4}, {3}`. -/
def chiSum (e : E) : ℕ := e.val.1.val + e.val.2.val

/-- The two-dimensional (`W₂`-block) basis columns:
differences of matching indicators. -/
def S2z : Matrix E (Fin 2) ℤ := fun e c =>
  if c = 0 then
    (if chiSum e = 1 ∨ chiSum e = 5 then 1 else 0)
      - (if chiSum e = 2 ∨ chiSum e = 4 then 1 else 0)
  else
    (if chiSum e = 2 ∨ chiSum e = 4 then 1 else 0)
      - (if chiSum e = 3 then 1 else 0)

/-- The adjugate-scaled left inverse (`48` times the true
pseudo-inverse). -/
def T2z : Matrix (Fin 2) E ℤ :=
  (!![8,4;4,8] : Matrix (Fin 2) (Fin 2) ℤ) * S2zᵀ

theorem hTS3z : T3z * S3z = 16 • 1 := by decide
theorem hST3z : S3z * T3z
    = 4 • 1 + 4 • RmZ - 4 • DisZ := by decide
theorem hQS3z : Z3 * S3z = 24 • S3z := by decide
theorem hTS2z : T2z * S2z = 48 • 1 := by decide
theorem hST2z : S2z * T2z = 2 • Z2 := by decide
theorem hQS2z : Z2 * S2z = 24 • S2z := by decide

theorem hs3z : T3z * (PsZ * S3z)
    = 16 • !![0,1,0;1,0,0;0,0,1] := by decide
theorem hr3z : T3z * (PrZ * S3z)
    = 16 • !![-1,-1,-1;1,0,0;0,1,0] := by decide
theorem hs2z : T2z * (PsZ * S2z)
    = 48 • !![1,0;1,-1] := by decide
theorem hr2z : T2z * (PrZ * S2z)
    = 48 • !![0,-1;-1,0] := by decide

/-- The compressed `C`-block representation. -/
noncomputable def rho3 (σ : Equiv.Perm V) :
    Matrix (Fin 3) (Fin 3) ℂ :=
  ((16:ℂ)⁻¹ • ci T3z) * (Pm σ * ci S3z)

/-- The compressed `W₂`-block representation. -/
noncomputable def rho2 (σ : Equiv.Perm V) :
    Matrix (Fin 2) (Fin 2) ℂ :=
  ((48:ℂ)⁻¹ • ci T2z) * (Pm σ * ci S2z)

theorem rho3_one : rho3 1 = 1 := by
  rw [rho3, Pm_one, Matrix.one_mul, Matrix.smul_mul,
    ← ci_mul, hTS3z, ci_nsmul, ci_one, smul_smul,
    show (16:ℂ)⁻¹ * ((16:ℕ):ℂ) = 1 by norm_num, one_smul]

theorem rho2_one : rho2 1 = 1 := by
  rw [rho2, Pm_one, Matrix.one_mul, Matrix.smul_mul,
    ← ci_mul, hTS2z, ci_nsmul, ci_one, smul_smul,
    show (48:ℂ)⁻¹ * ((48:ℕ):ℂ) = 1 by norm_num, one_smul]

theorem hST3 : ci S3z * ((16:ℂ)⁻¹ • ci T3z) = QC := by
  rw [Matrix.mul_smul, ← ci_mul, hST3z, ci_sub, ci_add,
    ci_nsmul, ci_nsmul, ci_nsmul, ci_one, QC, cz_eq_ci,
    show Z3 = 6 • (1 : Matrix E E ℤ) + 6 • RmZ - 6 • DisZ
      from rfl,
    ci_sub, ci_add, ci_nsmul, ci_nsmul, ci_nsmul, ci_one,
    show ((4:ℕ):ℂ) = (4:ℂ) from by norm_num,
    show ((6:ℕ):ℂ) = (6:ℂ) from by norm_num]
  module

theorem hST2 : ci S2z * ((48:ℂ)⁻¹ • ci T2z) = QW2 := by
  rw [Matrix.mul_smul, ← ci_mul, hST2z, ci_nsmul, QW2,
    cz_eq_ci, smul_smul,
    show (48:ℂ)⁻¹ * ((2:ℕ):ℂ) = (24:ℂ)⁻¹ by norm_num]

theorem rho3_mul (σ τ : Equiv.Perm V) :
    rho3 σ * rho3 τ = rho3 (σ * τ) := by
  have hST : ci S3z * ((16:ℂ)⁻¹ • ci T3z) = QC := hST3
  have hQS : QC * ci S3z = ci S3z := by
    rw [QC, cz_eq_ci, Matrix.smul_mul, ← ci_mul, hQS3z,
      ci_nsmul, smul_smul,
      show (24:ℂ)⁻¹ * ((24:ℕ):ℂ) = 1 by norm_num, one_smul]
  have hcen : Pm τ * QC = QC * Pm τ :=
    (Q_central QC_mem_span (Pm τ) (Pm_mem τ)).symm
  calc rho3 σ * rho3 τ
      = ((16:ℂ)⁻¹ • ci T3z) * (Pm σ
          * ((ci S3z * ((16:ℂ)⁻¹ • ci T3z))
            * (Pm τ * ci S3z))) := by
        rw [rho3, rho3, Matrix.mul_assoc, Matrix.mul_assoc,
          Matrix.mul_assoc]
    _ = ((16:ℂ)⁻¹ • ci T3z) * (Pm σ
          * (QC * (Pm τ * ci S3z))) := by rw [hST]
    _ = ((16:ℂ)⁻¹ • ci T3z) * (Pm σ
          * (Pm τ * (QC * ci S3z))) := by
        rw [← Matrix.mul_assoc QC (Pm τ) (ci S3z), ← hcen,
          Matrix.mul_assoc]
    _ = ((16:ℂ)⁻¹ • ci T3z) * (Pm σ
          * (Pm τ * ci S3z)) := by rw [hQS]
    _ = rho3 (σ * τ) := by
        rw [rho3, ← Matrix.mul_assoc (Pm σ) (Pm τ), Pm_mul]

theorem rho2_mul (σ τ : Equiv.Perm V) :
    rho2 σ * rho2 τ = rho2 (σ * τ) := by
  have hST : ci S2z * ((48:ℂ)⁻¹ • ci T2z) = QW2 := hST2
  have hQS : QW2 * ci S2z = ci S2z := by
    rw [QW2, cz_eq_ci, Matrix.smul_mul, ← ci_mul, hQS2z,
      ci_nsmul, smul_smul,
      show (24:ℂ)⁻¹ * ((24:ℕ):ℂ) = 1 by norm_num, one_smul]
  have hcen : Pm τ * QW2 = QW2 * Pm τ :=
    (Q_central QW2_mem_span (Pm τ) (Pm_mem τ)).symm
  calc rho2 σ * rho2 τ
      = ((48:ℂ)⁻¹ • ci T2z) * (Pm σ
          * ((ci S2z * ((48:ℂ)⁻¹ • ci T2z))
            * (Pm τ * ci S2z))) := by
        rw [rho2, rho2, Matrix.mul_assoc, Matrix.mul_assoc,
          Matrix.mul_assoc]
    _ = ((48:ℂ)⁻¹ • ci T2z) * (Pm σ
          * (QW2 * (Pm τ * ci S2z))) := by rw [hST]
    _ = ((48:ℂ)⁻¹ • ci T2z) * (Pm σ
          * (Pm τ * (QW2 * ci S2z))) := by
        rw [← Matrix.mul_assoc QW2 (Pm τ) (ci S2z), ← hcen,
          Matrix.mul_assoc]
    _ = ((48:ℂ)⁻¹ • ci T2z) * (Pm σ
          * (Pm τ * ci S2z)) := by rw [hQS]
    _ = rho2 (σ * τ) := by
        rw [rho2, ← Matrix.mul_assoc (Pm σ) (Pm τ), Pm_mul]

theorem rho3_s_det : (rho3 sPerm).det = -1 := by
  set M3 : Matrix (Fin 3) (Fin 3) ℤ := !![0,1,0;1,0,0;0,0,1]
    with hM3
  have h : rho3 sPerm = ci M3 := by
    rw [hM3]
    rw [rho3, Pm_s_eq_cz, cz_eq_ci, Matrix.smul_mul,
      ← ci_mul, ← ci_mul, hs3z, ci_nsmul, smul_smul,
      show (16:ℂ)⁻¹ * ((16:ℕ):ℂ) = 1 by norm_num, one_smul]
  rw [h, show (ci M3).det = ((M3.det : ℤ) : ℂ) from
    (RingHom.map_det (Int.castRingHom ℂ) M3).symm,
    show M3.det = -1 from by rw [hM3]; decide]
  norm_num

theorem rho3_r_det : (rho3 rPerm).det = -1 := by
  set M3 : Matrix (Fin 3) (Fin 3) ℤ := !![-1,-1,-1;1,0,0;0,1,0]
    with hM3
  have h : rho3 rPerm = ci M3 := by
    rw [hM3]
    rw [rho3, Pm_r_eq_cz, cz_eq_ci, Matrix.smul_mul,
      ← ci_mul, ← ci_mul, hr3z, ci_nsmul, smul_smul,
      show (16:ℂ)⁻¹ * ((16:ℕ):ℂ) = 1 by norm_num, one_smul]
  rw [h, show (ci M3).det = ((M3.det : ℤ) : ℂ) from
    (RingHom.map_det (Int.castRingHom ℂ) M3).symm,
    show M3.det = -1 from by rw [hM3]; decide]
  norm_num

theorem rho2_s_det : (rho2 sPerm).det = -1 := by
  set M2 : Matrix (Fin 2) (Fin 2) ℤ := !![1,0;1,-1]
    with hM2
  have h : rho2 sPerm = ci M2 := by
    rw [hM2]
    rw [rho2, Pm_s_eq_cz, cz_eq_ci, Matrix.smul_mul,
      ← ci_mul, ← ci_mul, hs2z, ci_nsmul, smul_smul,
      show (48:ℂ)⁻¹ * ((48:ℕ):ℂ) = 1 by norm_num, one_smul]
  rw [h, show (ci M2).det = ((M2.det : ℤ) : ℂ) from
    (RingHom.map_det (Int.castRingHom ℂ) M2).symm,
    show M2.det = -1 from by rw [hM2]; decide]
  norm_num

theorem rho2_r_det : (rho2 rPerm).det = -1 := by
  set M2 : Matrix (Fin 2) (Fin 2) ℤ := !![0,-1;-1,0]
    with hM2
  have h : rho2 rPerm = ci M2 := by
    rw [hM2]
    rw [rho2, Pm_r_eq_cz, cz_eq_ci, Matrix.smul_mul,
      ← ci_mul, ← ci_mul, hr2z, ci_nsmul, smul_smul,
      show (48:ℂ)⁻¹ * ((48:ℕ):ℂ) = 1 by norm_num, one_smul]
  rw [h, show (ci M2).det = ((M2.det : ℤ) : ℂ) from
    (RingHom.map_det (Int.castRingHom ℂ) M2).symm,
    show M2.det = -1 from by rw [hM2]; decide]
  norm_num

theorem sign_sPerm : (Equiv.Perm.sign sPerm : ℤ) = -1 := by
  decide

theorem sign_rPerm : (Equiv.Perm.sign rPerm : ℤ) = -1 := by
  decide

theorem det_hom_eq_sign
    (ρ : Equiv.Perm V → ℂ)
    (hone : ρ 1 = 1)
    (hmul : ∀ σ τ, ρ σ * ρ τ = ρ (σ * τ))
    (hs : ρ sPerm = -1) (hr : ρ rPerm = -1) :
    ∀ σ, ρ σ = ((Equiv.Perm.sign σ : ℤ) : ℂ) := by
  intro σ
  have hσ : σ ∈ Subgroup.closure ({rPerm, sPerm} :
      Set (Equiv.Perm V)) := by
    rw [closure_sr]; exact Subgroup.mem_top σ
  induction hσ using Subgroup.closure_induction with
  | mem x hx =>
    rcases hx with rfl | rfl
    · rw [hr, sign_rPerm]
      norm_num
    · rw [hs, sign_sPerm]
      norm_num
  | one =>
    rw [hone, map_one]
    norm_num
  | mul x y _ _ ihx ihy =>
    rw [← hmul, ihx, ihy, map_mul, ← Int.cast_mul]
    norm_num
  | inv x _ ih =>
    have hsq : ((Equiv.Perm.sign x : ℤ) : ℂ)
        * ((Equiv.Perm.sign x : ℤ) : ℂ) = 1 := by
      rw [← Int.cast_mul, ← Units.val_mul, ← sq,
        Int.units_sq, Units.val_one, Int.cast_one]
    have hinvmul : ρ x⁻¹ * ρ x = 1 := by
      rw [hmul, inv_mul_cancel, hone]
    have hval : ρ x⁻¹ = ((Equiv.Perm.sign x : ℤ) : ℂ) := by
      calc ρ x⁻¹
          = ρ x⁻¹ * (((Equiv.Perm.sign x : ℤ) : ℂ)
            * ((Equiv.Perm.sign x : ℤ) : ℂ)) := by
            rw [hsq, mul_one]
        _ = (ρ x⁻¹ * ((Equiv.Perm.sign x : ℤ) : ℂ))
            * ((Equiv.Perm.sign x : ℤ) : ℂ) := by ring
        _ = (ρ x⁻¹ * ρ x)
            * ((Equiv.Perm.sign x : ℤ) : ℂ) := by rw [ih]
        _ = ((Equiv.Perm.sign x : ℤ) : ℂ) := by
            rw [hinvmul, one_mul]
    rw [hval, map_inv]
    have : (Equiv.Perm.sign x)⁻¹ = Equiv.Perm.sign x :=
      inv_eq_of_mul_eq_one_right
        (by rw [← sq, Int.units_sq])
    rw [this]

/-- **(SM.0j), C block**: the determinant character of the
even-standard block is the sign character. -/
theorem detC_eq_sign (σ : Equiv.Perm V) :
    (rho3 σ).det = ((Equiv.Perm.sign σ : ℤ) : ℂ) :=
  det_hom_eq_sign (fun σ => (rho3 σ).det)
    (by rw [rho3_one, Matrix.det_one])
    (fun σ τ => by rw [← Matrix.det_mul, rho3_mul])
    rho3_s_det rho3_r_det σ

/-- **(SM.0j), W₂ block**: the determinant character of the
two-dimensional block is also the sign character. -/
theorem detW2_eq_sign (σ : Equiv.Perm V) :
    (rho2 σ).det = ((Equiv.Perm.sign σ : ℤ) : ℂ) :=
  det_hom_eq_sign (fun σ => (rho2 σ).det)
    (by rw [rho2_one, Matrix.det_one])
    (fun σ τ => by rw [← Matrix.det_mul, rho2_mul])
    rho2_s_det rho2_r_det σ

/-- **(SM.0j), product**: `det C ⊗ det W₂` is the trivial
`S₄` line. -/
theorem det_product_trivial (σ : Equiv.Perm V) :
    (rho3 σ).det * (rho2 σ).det = 1 := by
  rw [detC_eq_sign, detW2_eq_sign, ← Int.cast_mul,
    ← Units.val_mul, ← sq, Int.units_sq, Units.val_one,
    Int.cast_one]

/-! ### The edge projectors of the cut carrier (SM.0k) -/

/-- The normalized cut vector of an edge. -/
def cutVec (i j : V) : V → ℂ := fun x =>
  (if x = j then 1 else 0) - (if x = i then 1 else 0)

/-- The edge projector `P_e = u_e u_e^* ` with
`u_e = (e_j - e_i)/√2`. -/
noncomputable def Pedge (i j : V) : Matrix V V ℂ :=
  (2:ℂ)⁻¹ • Matrix.vecMulVec (cutVec i j) (cutVec i j)

/-- **(SM.0k)**: the six edge projectors of `K₄` sum to twice
the orthogonal projection onto the cut carrier `G` — twice
the identity of `G`. -/
theorem edge_projector_sum :
    Pedge 0 1 + Pedge 0 2 + Pedge 0 3 + Pedge 1 2
      + Pedge 1 3 + Pedge 2 3
    = (2:ℂ) • ((1 : Matrix V V ℂ)
        - (4:ℂ)⁻¹ • Matrix.of (fun _ _ => (1:ℂ))) := by
  ext x y
  fin_cases x <;> fin_cases y <;>
    norm_num [Pedge, cutVec, Matrix.vecMulVec_apply,
      Matrix.one_apply, Fin.ext_iff]

/-- The sum acts as `2` on every mean-zero vector: it is
`2 I_G` on the cut carrier. -/
theorem edge_projector_sum_apply (x : V → ℂ)
    (hx : ∑ v, x v = 0) :
    (Pedge 0 1 + Pedge 0 2 + Pedge 0 3 + Pedge 1 2
      + Pedge 1 3 + Pedge 2 3) *ᵥ x = (2:ℂ) • x := by
  rw [edge_projector_sum]
  funext v
  simp only [Matrix.mulVec, Matrix.smul_apply,
    Matrix.sub_apply, Matrix.one_apply, Matrix.of_apply,
    dotProduct, Pi.smul_apply, smul_eq_mul]
  have h1 : ∀ w : V,
      (2:ℂ) * ((if v = w then (1:ℂ) else 0) - 4⁻¹ * 1)
        * x w
      = (if v = w then (2:ℂ) * x w else 0)
        - 2⁻¹ * x w := by
    intro w
    by_cases hw : v = w
    · rw [if_pos hw, if_pos hw]
      ring
    · rw [if_neg hw, if_neg hw]
      ring
  rw [Finset.sum_congr rfl fun w _ => h1 w,
    Finset.sum_sub_distrib, Finset.sum_ite_eq,
    if_pos (Finset.mem_univ v), ← Finset.mul_sum, hx,
    mul_zero, sub_zero]

end ActiveResidual
end NCG
