/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.RecordGeneration

/-!
# Intrinsic generation of the oriented chronology algebra
  (`prop:ar-forward-generation`, Gran-Tensor manuscript)

* `ar_forward_generation`: the boxed generation identities
  `𝒯_X⁺ = alg(S, P₁, …, P_X) = alg(S, N)` — the oriented
  (non-`*`) chronology algebra generated by the successor and
  the endpoint projections, equivalently by the successor and
  the count operator (via terminating Lagrange interpolation) —
  is exactly the forward-triangular subalgebra; it is proper for
  `X ≥ 2`, while its `*`-closure is all of `M_X(ℂ)`
  (`record_generation`).

Rendering disclosed: `𝒯_X⁺` is rendered as the forward
(lower-triangular in the out/in indices) subalgebra; unitality
is the subalgebra structure; the `*`-closure clause is the
cited `C*(S) = M_X` record.
-/

open Matrix

namespace NCG

/-- The oriented chronology algebra: forward-triangular
matrices (`M j i = 0` when the out-index precedes the
in-index). -/
def forwardAlg (X : ℕ) :
    Subalgebra ℂ (Matrix (Fin X) (Fin X) ℂ) where
  carrier := {M | ∀ j i : Fin X, (j : ℕ) < (i : ℕ) → M j i = 0}
  add_mem' := by
    intro M N hM hN j i hji
    rw [Matrix.add_apply, hM j i hji, hN j i hji, add_zero]
  mul_mem' := by
    intro M N hM hN j i hji
    rw [Matrix.mul_apply]
    apply Finset.sum_eq_zero
    intro k _
    rcases lt_or_ge (j : ℕ) (k : ℕ) with h | h
    · rw [hM j k h, zero_mul]
    · rw [hN k i (lt_of_le_of_lt h hji), mul_zero]
  algebraMap_mem' := by
    intro c j i hji
    rw [Matrix.algebraMap_matrix_apply,
      if_neg (fun hc : j = i => by
        rw [hc] at hji
        omega)]

/-- The endpoint count operator `N e_n = n e_n`. -/
def countN (X : ℕ) : Matrix (Fin X) (Fin X) ℂ :=
  Matrix.diagonal (fun i => (((i : ℕ) + 1 : ℕ) : ℂ))

/-- A list product of diagonal matrices is the diagonal of the
pointwise list product. -/
lemma list_prod_diagonal {X : ℕ} :
    ∀ l : List (Fin X → ℂ),
      (l.map Matrix.diagonal).prod
        = Matrix.diagonal (fun j => (l.map (fun g => g j)).prod)
  | [] => Matrix.diagonal_one.symm
  | a :: t => by
      rw [List.map_cons, List.prod_cons, list_prod_diagonal t,
        Matrix.diagonal_mul_diagonal]
      congr 1

/-- `prop:ar-forward-generation`: both generation identities,
properness, and the `*`-closure. -/
theorem ar_forward_generation {X : ℕ} (hX : 1 ≤ X) :
    (Algebra.adjoin ℂ ({recS X} ∪ Set.range (fun i : Fin X =>
        Matrix.diagonal (Pi.single i (1 : ℂ)))) = forwardAlg X)
    ∧ (Algebra.adjoin ℂ {recS X, countN X} = forwardAlg X)
    ∧ (2 ≤ X → forwardAlg X ≠ ⊤)
    ∧ StarAlgebra.adjoin ℂ
        ({recS X} : Set (Matrix (Fin X) (Fin X) ℂ)) = ⊤ := by
  have hSmem : recS X ∈ forwardAlg X := by
    intro j i hji
    rw [recS, Matrix.of_apply, if_neg (by omega)]
  have hPmem : ∀ i : Fin X,
      Matrix.diagonal (Pi.single i (1 : ℂ)) ∈ forwardAlg X := by
    intro i j i' hji
    exact Matrix.diagonal_apply_ne _ (fun hc => by
      rw [hc] at hji
      omega)
  have hNmem : countN X ∈ forwardAlg X := by
    intro j i hji
    exact Matrix.diagonal_apply_ne _ (fun hc => by
      rw [hc] at hji
      omega)
  have hunit : ∀ j i : Fin X, (i : ℕ) ≤ (j : ℕ) →
      recS X ^ ((j : ℕ) - (i : ℕ))
          * Matrix.diagonal (Pi.single i (1 : ℂ))
        = Matrix.single j i 1 := by
    intro j i hij
    ext r c
    rw [Matrix.mul_diagonal, recS_pow, Matrix.of_apply]
    by_cases hrc : j = r ∧ i = c
    · obtain ⟨hjr, hic⟩ := hrc
      subst hjr
      subst hic
      rw [Matrix.single_apply_same j i (1 : ℂ),
        if_pos (by omega), Pi.single_eq_same, one_mul]
    · rw [Matrix.single_apply_of_ne j i 1 r c hrc]
      by_cases hic : i = c
      · subst hic
        have hjr : j ≠ r := fun h => hrc ⟨h, rfl⟩
        rw [if_neg (fun h : (r : ℕ) = (i : ℕ)
            + ((j : ℕ) - (i : ℕ)) =>
          hjr (Fin.ext (by omega))), zero_mul]
      · rw [Pi.single_eq_of_ne (fun h : c = i => hic h.symm),
          mul_zero]
  have hdecomp : ∀ M ∈ forwardAlg X,
      ∀ (S : Subalgebra ℂ (Matrix (Fin X) (Fin X) ℂ)),
      recS X ∈ S →
      (∀ i : Fin X,
        Matrix.diagonal (Pi.single i (1 : ℂ)) ∈ S) →
      M ∈ S := by
    intro M hM S hS hP
    rw [Matrix.matrix_eq_sum_single M]
    apply sum_mem
    intro j _
    apply sum_mem
    intro i _
    rcases lt_or_ge (j : ℕ) (i : ℕ) with h | h
    · rw [hM j i h]
      rw [show Matrix.single j i (0 : ℂ) = 0 from by
        ext r c
        rw [Matrix.zero_apply]
        by_cases hrc : j = r ∧ i = c
        · obtain ⟨h1, h2⟩ := hrc
          subst h1
          subst h2
          exact Matrix.single_apply_same j i 0
        · exact Matrix.single_apply_of_ne j i 0 r c hrc]
      exact zero_mem S
    · rw [show Matrix.single j i (M j i)
          = M j i • Matrix.single j i (1 : ℂ) from by
        ext r c
        rw [Matrix.smul_apply]
        by_cases hrc : j = r ∧ i = c
        · obtain ⟨h1, h2⟩ := hrc
          subst h1
          subst h2
          rw [Matrix.single_apply_same j i (M j i),
            Matrix.single_apply_same j i (1 : ℂ),
            smul_eq_mul, mul_one]
        · rw [Matrix.single_apply_of_ne j i (M j i) r c hrc,
            Matrix.single_apply_of_ne j i 1 r c hrc,
            smul_zero]]
      exact S.smul_mem (by
        rw [← hunit j i h]
        exact mul_mem (pow_mem hS _) (hP i)) _
  have hfac : ∀ i k : Fin X,
      (((i : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
          • (countN X - ((((k : ℕ) + 1 : ℕ) : ℂ)
            • (1 : Matrix (Fin X) (Fin X) ℂ)))
        = Matrix.diagonal (fun j : Fin X =>
            (((i : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
              * ((((j : ℕ) : ℂ) + 1)
                - (((k : ℕ) : ℂ) + 1))) := by
    intro i k
    ext r c
    by_cases hrc : r = c
    · subst hrc
      simp only [Matrix.smul_apply, Matrix.sub_apply, countN,
        Matrix.diagonal_apply_eq, Matrix.one_apply_eq,
        smul_eq_mul]
      push_cast
      ring
    · simp only [Matrix.smul_apply, Matrix.sub_apply, countN,
        Matrix.diagonal_apply_ne _ hrc,
        Matrix.one_apply_ne hrc, smul_eq_mul]
      ring
  have hlag : ∀ i : Fin X,
      Matrix.diagonal (Pi.single i (1 : ℂ))
        = ((Finset.univ.erase i).toList.map (fun k : Fin X =>
            (((i : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
              • (countN X - ((((k : ℕ) + 1 : ℕ) : ℂ)
                • (1 : Matrix (Fin X) (Fin X) ℂ))))).prod := by
    intro i
    rw [List.map_congr_left (fun k _ => hfac i k)]
    rw [show (Finset.univ.erase i).toList.map
        (fun k : Fin X => Matrix.diagonal (fun j : Fin X =>
          (((i : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
            * ((((j : ℕ) : ℂ) + 1) - (((k : ℕ) : ℂ) + 1))))
        = ((Finset.univ.erase i).toList.map
            (fun k : Fin X => fun j : Fin X =>
              (((i : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
                * ((((j : ℕ) : ℂ) + 1)
                  - (((k : ℕ) : ℂ) + 1)))).map
            Matrix.diagonal from by
      rw [List.map_map]
      rfl]
    rw [list_prod_diagonal]
    congr 1
    funext j
    rw [List.map_map]
    by_cases hj : j = i
    · subst hj
      rw [Pi.single_eq_same]
      symm
      apply List.prod_eq_one
      intro x hx
      obtain ⟨k, hk, rfl⟩ := List.mem_map.mp hx
      have hkj : k ≠ j :=
        (Finset.mem_erase.mp (Finset.mem_toList.mp hk)).1
      have hne : ((j : ℕ) : ℂ) - ((k : ℕ) : ℂ) ≠ 0 := by
        rw [sub_ne_zero]
        intro hc
        apply hkj
        apply Fin.ext
        exact_mod_cast hc.symm
      change (((j : ℕ) : ℂ) - ((k : ℕ) : ℂ))⁻¹
          * ((((j : ℕ) : ℂ) + 1) - (((k : ℕ) : ℂ) + 1)) = 1
      rw [show ((((j : ℕ) : ℂ) + 1) - (((k : ℕ) : ℂ) + 1))
          = (((j : ℕ) : ℂ) - ((k : ℕ) : ℂ)) from by ring]
      exact inv_mul_cancel₀ hne
    · rw [Pi.single_eq_of_ne hj]
      symm
      apply List.prod_eq_zero
      refine List.mem_map.mpr ⟨j, ?_, ?_⟩
      · exact Finset.mem_toList.mpr
          (Finset.mem_erase.mpr ⟨hj, Finset.mem_univ j⟩)
      · change (((i : ℕ) : ℂ) - ((j : ℕ) : ℂ))⁻¹
            * ((((j : ℕ) : ℂ) + 1) - (((j : ℕ) : ℂ) + 1)) = 0
        rw [show ((((j : ℕ) : ℂ) + 1) - (((j : ℕ) : ℂ) + 1))
            = 0 from by ring, mul_zero]
  refine ⟨?_, ?_, ?_, record_generation hX⟩
  · apply le_antisymm
    · apply Algebra.adjoin_le
      rintro x (hx | ⟨i, rfl⟩)
      · rw [Set.mem_singleton_iff.mp hx]
        exact hSmem
      · exact hPmem i
    · intro M hM
      exact hdecomp M hM _
        (Algebra.subset_adjoin (Set.mem_union_left _ rfl))
        (fun i => Algebra.subset_adjoin
          (Set.mem_union_right _ ⟨i, rfl⟩))
  · apply le_antisymm
    · apply Algebra.adjoin_le
      rintro x (rfl | hx)
      · exact hSmem
      · rw [Set.mem_singleton_iff.mp hx]
        exact hNmem
    · intro M hM
      refine hdecomp M hM _
        (Algebra.subset_adjoin (Set.mem_insert _ _)) ?_
      intro i
      rw [hlag i]
      apply list_prod_mem
      intro x hx
      obtain ⟨k, hk, rfl⟩ := List.mem_map.mp hx
      refine (Algebra.adjoin ℂ {recS X, countN X}).smul_mem
        (sub_mem ?_
          ((Algebra.adjoin ℂ {recS X, countN X}).smul_mem
            (one_mem _) _)) _
      exact Algebra.subset_adjoin
        (Set.mem_insert_iff.mpr (Or.inr rfl))
  · intro hX2 htop
    have hmem : Matrix.single (⟨0, by omega⟩ : Fin X)
        (⟨1, by omega⟩ : Fin X) (1 : ℂ) ∈ forwardAlg X := by
      rw [htop]
      exact Algebra.mem_top
    have h01 := hmem ⟨0, by omega⟩ ⟨1, by omega⟩ (by simp)
    rw [Matrix.single_apply_same] at h01
    exact one_ne_zero h01

end NCG
