/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.RecordGeneration
import NCG.Grand.RecordSurvival
import NCG.Grand.RecordCompletionOp

/-!
# Arithmetic chronology-corner conservativity

This file gives the concrete specialization required by
`thm:ar-record-completion`.  The chronology corner is generated by the
protocol-defined truncated successor `recS X`; no arithmetic coefficient or
predicate occurs in its definition.  The successor and every diagonal point
Read survive the contextual future quotient, normalized record discard
recovers every core coefficient, and star-algebra maps carry the corner to the
corner generated by the transported successor.
-/

open Matrix
open scoped Kronecker ComplexOrder

namespace NCG

/-- The chronology corner selected before any arithmetic semantics. -/
def arithmeticChronologyCorner (X : ℕ) :
    StarSubalgebra ℂ (Matrix (Fin X) (Fin X) ℂ) :=
  StarAlgebra.adjoin ℂ ({recS X} : Set (Matrix (Fin X) (Fin X) ℂ))

/-- The diagonal Read of a single chronological position. -/
def chronologyPointRead (X : ℕ) (i : Fin X) :
    Matrix (Fin X) (Fin X) ℂ :=
  Matrix.single i i 1

/-- Against the faithful full-matrix future metric, every nonzero coefficient
survives the contextual quotient. -/
theorem fullMatrixFutureQuotient_survival_iff_nonzero
    {n : Type*} [Fintype n] [DecidableEq n]
    (A : Matrix n n ℂ) :
    (Submodule.Quotient.mk A :
        Matrix n n ℂ ⧸ nullSubmodule (1 : Matrix n n ℂ)) ≠ 0 ↔
      A ≠ 0 := by
  constructor
  · intro hsurv hA
    apply hsurv
    rw [Submodule.Quotient.mk_eq_zero]
    simpa [hA]
  · intro hA
    apply (record_survival (1 : Matrix n n ℂ)).1 A |>.2
    refine ⟨Aᴴ, 1, ?_⟩
    have htrace : (Aᴴ * A).trace ≠ 0 := by
      intro hz
      exact hA (Matrix.trace_conjTranspose_mul_self_eq_zero_iff.mp hz)
    simpa using htrace

/-- Every chronological point Read is a protected nonzero future class. -/
theorem chronologyPointRead_survives
    {X : ℕ} (i : Fin X) :
    (Submodule.Quotient.mk (chronologyPointRead X i) :
        Matrix (Fin X) (Fin X) ℂ ⧸
          nullSubmodule (1 : Matrix (Fin X) (Fin X) ℂ)) ≠ 0 := by
  apply (fullMatrixFutureQuotient_survival_iff_nonzero
    (chronologyPointRead X i)).2
  intro hzero
  have hii := congrFun (congrFun hzero i) i
  simpa [chronologyPointRead] using hii

/-- For a nontrivial chronology, its deterministic successor is a protected
nonzero future class. -/
theorem chronologySuccessor_survives {X : ℕ} (hX : 2 ≤ X) :
    (Submodule.Quotient.mk (recS X) :
        Matrix (Fin X) (Fin X) ℂ ⧸
          nullSubmodule (1 : Matrix (Fin X) (Fin X) ℂ)) ≠ 0 := by
  apply (fullMatrixFutureQuotient_survival_iff_nonzero (recS X)).2
  let i0 : Fin X := ⟨0, by omega⟩
  let i1 : Fin X := ⟨1, by omega⟩
  intro hzero
  have hentry := congrFun (congrFun hzero i1) i0
  simpa [recS, i0, i1] using hentry

/-- Discarding a normalized universal chronology record recovers the old core
coefficient exactly. -/
theorem arithmeticChronologyRecord_discard
    {X c : Type*} [Fintype X] [Fintype c]
    [DecidableEq X] [DecidableEq c]
    (A : Matrix c c ℂ) (recordState : Matrix X X ℂ)
    (hnorm : recordState.trace = 1) :
    partialTraceRight (dA := c) (dK := X) (A ⊗ₖ recordState) = A := by
  rw [(operational_record_completion (r := X) (c := c)).2.2.1 A recordState,
    hnorm, one_smul]

/-- Star-morphisms carry the concrete chronology corner to the corner generated
by the transported deterministic successor. -/
theorem arithmeticChronologyCorner_map
    {X : ℕ} {B : Type*} [Semiring B] [StarRing B]
    [Algebra ℂ B] [StarModule ℂ B]
    (φ : Matrix (Fin X) (Fin X) ℂ →⋆ₐ[ℂ] B) :
    (arithmeticChronologyCorner X).map φ =
      StarAlgebra.adjoin ℂ ({φ (recS X)} : Set B) := by
  rw [arithmeticChronologyCorner, StarAlgHom.map_adjoin]
  congr 1
  ext b
  simp

/-- `thm:ar-record-completion`, exact concrete specialization.  The generated
chronology corner is the full record matrix algebra, its protocol-defined
source Read, all point Reads, and its deterministic successor survive the
future quotient, record discard is conservative, and every star-morphism is
functorial on the selected corner. -/
theorem arithmeticChronologySelection_conservative
    {X : ℕ} (hX : 2 ≤ X) :
    arithmeticChronologyCorner X = ⊤
    ∧ ((Submodule.Quotient.mk (recS X) :
          Matrix (Fin X) (Fin X) ℂ ⧸
            nullSubmodule (1 : Matrix (Fin X) (Fin X) ℂ)) ≠ 0)
    ∧ (∀ i : Fin X, chronologyPointRead X i ∈ arithmeticChronologyCorner X)
    ∧ (∀ i : Fin X,
        (Submodule.Quotient.mk (chronologyPointRead X i) :
            Matrix (Fin X) (Fin X) ℂ ⧸
              nullSubmodule (1 : Matrix (Fin X) (Fin X) ℂ)) ≠ 0)
    ∧ (∀ {c : Type*} [Fintype c] [DecidableEq c]
        (A : Matrix c c ℂ) (recordState : Matrix (Fin X) (Fin X) ℂ),
        recordState.trace = 1 →
          partialTraceRight (dA := c) (dK := Fin X)
            (A ⊗ₖ recordState) = A) := by
  have htop : arithmeticChronologyCorner X = ⊤ :=
    record_generation (by omega)
  refine ⟨htop, chronologySuccessor_survives hX, ?_,
    chronologyPointRead_survives, ?_⟩
  · intro i
    rw [htop]
    trivial
  · intro c _ _ A recordState hnorm
    exact arithmeticChronologyRecord_discard A recordState hnorm

end NCG
