import Mathlib.Tactic

/-!
# Arithmetic response birth versus physical source birth

A newly visible response coordinate is compared with every already assembled
contribution.  Its constitutive residual—not visibility alone—decides whether
an additional physical source is required.  The concrete pair at the end fixes
the same nonzero response trace while giving residual zero in one assembled
model and residual one in another.
-/

namespace NCG.ArithmeticResponseSourceBirthResidual

/-- The residual left after transported old dynamics, deterministic fine
generation, comparison/score writers, and boundary terms are assembled. -/
def constitutiveResidual
    (response transported deterministic comparison boundary : ℝ) : ℝ :=
  response - (transported + deterministic + comparison + boundary)

/-- A physical source birth is exactly a nonzero constitutive residual. -/
def IsPhysicalSourceBirth
    (response transported deterministic comparison boundary : ℝ) : Prop :=
  constitutiveResidual response transported deterministic comparison boundary ≠ 0

theorem source_birth_iff_residual_ne_zero
    (response transported deterministic comparison boundary : ℝ) :
    IsPhysicalSourceBirth response transported deterministic comparison boundary ↔
      response ≠ transported + deterministic + comparison + boundary := by
  simp [IsPhysicalSourceBirth, constitutiveResidual, sub_ne_zero]

/-- Exact assembly closes the constitutive residual and creates no new source,
even when the response coordinate itself is nonzero. -/
theorem generated_response_no_source
    (response transported deterministic comparison boundary : ℝ)
    (hassembly : response = transported + deterministic + comparison + boundary) :
    ¬ IsPhysicalSourceBirth response transported deterministic comparison boundary := by
  simp [IsPhysicalSourceBirth, constitutiveResidual, hassembly]

/-- Failure of the assembled old rows to generate the response leaves a
genuine source residual. -/
theorem unexplained_response_is_source
    (response transported deterministic comparison boundary : ℝ)
    (hres : response ≠ transported + deterministic + comparison + boundary) :
    IsPhysicalSourceBirth response transported deterministic comparison boundary :=
  (source_birth_iff_residual_ne_zero _ _ _ _ _).mpr hres

/-- Nonvacuous separating pair.  Both adjacent-cutoff models display the same
new response trace `1`; in the first it is deterministically generated by the
transported packet, while in the second it remains a nonzero source residual. -/
theorem same_response_birth_with_and_without_source :
    let response : ℝ := 1
    response ≠ 0 ∧
      constitutiveResidual response 1 0 0 0 = 0 ∧
      ¬ IsPhysicalSourceBirth response 1 0 0 0 ∧
      constitutiveResidual response 0 0 0 0 = 1 ∧
      IsPhysicalSourceBirth response 0 0 0 0 := by
  norm_num [constitutiveResidual, IsPhysicalSourceBirth]

/-- Bundled Gran--Tensor corollary: response birth does not logically imply
source birth, and the exact reopening criterion is residual nonvanishing after
all declared old rows are assembled. -/
theorem arithmetic_response_birth_is_not_source_birth :
    (∃ response : ℝ, response ≠ 0 ∧
      ¬ IsPhysicalSourceBirth response 1 0 0 0) ∧
    (∀ response transported deterministic comparison boundary : ℝ,
      IsPhysicalSourceBirth response transported deterministic comparison boundary ↔
        response ≠ transported + deterministic + comparison + boundary) := by
  refine ⟨⟨1, one_ne_zero, ?_⟩, source_birth_iff_residual_ne_zero⟩
  norm_num [IsPhysicalSourceBirth, constitutiveResidual]

end NCG.ArithmeticResponseSourceBirthResidual
