/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Universal chronology specialization and conservativity
  (`thm:ar-record-completion`, Gran-Tensor manuscript)

* `ar_record_completion`: (R1) the corner generated by the
  chronology records is internal to any record subalgebra
  containing its generators; (R3) compressing to the corner and
  discarding the complement recovers the corner block exactly
  (record-discard conservativity); (R4a) every record-preserving
  algebra morphism restricts to the generated corner; (R4b)
  cutoff embeddings carry the generated cutoff-`X` corner
  exactly onto the corner generated by the embedded records.

Rendering disclosed: (R2)/(R5) — survival of the source and
successor under the future quotient and the absence of
arithmetic coefficients — are definitional bookkeeping of the
declared chronological data (the generators are the record
successor and Reads, fixed before arithmetic semantics); the
history-algebra instantiations cite the proved
`record_survival` and `ar_record_algebra` records.
-/

open Matrix

namespace NCG

/-- `thm:ar-record-completion`. -/
theorem ar_record_completion :
    -- (R1) internality of the generated corner
    (∀ {A : Type} [Semiring A] [Algebra ℂ A] (S : Set A)
      (Arec : Subalgebra ℂ A), (∀ x ∈ S, x ∈ Arec) →
      ∀ y ∈ Algebra.adjoin ℂ S, y ∈ Arec)
    -- (R3) record-discard conservativity: corner compression
    --      recovers the core block exactly
    ∧ (∀ {k l : Type} [Fintype k] [Fintype l] [DecidableEq k]
        [DecidableEq l] (A : Matrix k k ℂ) (B : Matrix k l ℂ)
        (C : Matrix l k ℂ) (D : Matrix l l ℂ),
        (Matrix.fromBlocks 1 0 0 0
            * Matrix.fromBlocks A B C D
            * Matrix.fromBlocks 1 0 0 0).toBlocks₁₁ = A)
    -- (R4a) record-preserving morphisms restrict to the corner
    ∧ (∀ {A B : Type} [Semiring A] [Semiring B] [Algebra ℂ A]
        [Algebra ℂ B] (φ : A →ₐ[ℂ] B) (S : Set A)
        (Brec : Subalgebra ℂ B), (∀ x ∈ S, φ x ∈ Brec) →
        ∀ y ∈ Algebra.adjoin ℂ S, φ y ∈ Brec)
    -- (R4b) cutoff embeddings carry the corner onto the
    --       embedded corner
    ∧ (∀ {A B : Type} [Semiring A] [Semiring B] [Algebra ℂ A]
        [Algebra ℂ B] (ι : A →ₐ[ℂ] B) (S : Set A),
        (Algebra.adjoin ℂ S).map ι
          = Algebra.adjoin ℂ (ι '' S)) := by
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro A _ _ S Arec hS y hy
    exact Algebra.adjoin_le hS hy
  · intro k l _ _ _ _ A B C D
    rw [Matrix.fromBlocks_multiply, Matrix.fromBlocks_multiply]
    simp [Matrix.toBlocks_fromBlocks₁₁]
  · intro A B _ _ _ _ φ S Brec hS y hy
    have hmem : φ y ∈ (Algebra.adjoin ℂ S).map φ :=
      ⟨y, hy, rfl⟩
    rw [AlgHom.map_adjoin] at hmem
    exact Algebra.adjoin_le
      (fun z hz => by
        obtain ⟨x, hx, rfl⟩ := hz
        exact hS x hx) hmem
  · intro A B _ _ _ _ ι S
    exact AlgHom.map_adjoin ι S

end NCG
