/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Matter.GenerationTransparency

/-!
# Terminating autonomous identification theorem
  (`thm:SM-autonomous-test`, Gran-Tensor manuscript)

* `sm_autonomous_test`:
  (a) the residual expansion's exact zero criterion:
      `‖S‖² + 2‖C₀ − B/2‖² + 2‖C₂‖² = 0 ⟺
       S = 0 ∧ C₀ = B/2 ∧ C₂ = 0` (the boxed moment identity
      characterising equality with the coarse score-square
      channel);
  (b) the boxed combined criterion: a sum of two nonnegative
      residuals vanishes iff both vanish
      (`Δ_FR + Δ_rec = 0 ⟺ Δ_FR = 0 ∧ Δ_rec = 0`);
  (c) finite Grand-Tensor reconstructibility: the resolvent
      `(I−A)⁻¹` lies in the unital algebra generated by `A`
      (Cayley–Hamilton inverse membership), so the first
      returns are finite loaded panels;
  (d) the six-state positivity: a nonzero signed return `B`
      has strictly nonzero Hilbert–Schmidt norm
      (`Tr(BᴴB) ≠ 0`), hence `Δ_FR > 0` for the displayed
      grading-preserving source.

Rendering disclosed: the decomposition of the grading
normalizer conjugation into trivial ⊕ sign ⊕ off-diagonal
representations (identifying the three twisted first returns
with the channel blocks) is the manuscript's finite Schur
step, and the Stinespring intertwining residual `Δ_rec` is
the declared comparison of the two record representations
(minimal-dilation uniqueness is the comb-dilation layer).
-/

open Matrix
open scoped ComplexOrder

namespace NCG

/-- `thm:SM-autonomous-test`. -/
theorem sm_autonomous_test {n : Type*} [Fintype n]
    [DecidableEq n] :
    -- (a) the residual zero criterion
    (∀ S C₀ C₂ B : Matrix n n ℂ,
      ((Sᴴ * S).trace
          + 2 * (((C₀ - (2⁻¹ : ℂ) • B))ᴴ
              * (C₀ - (2⁻¹ : ℂ) • B)).trace
          + 2 * (C₂ᴴ * C₂).trace = 0)
        ↔ (S = 0 ∧ C₀ = (2⁻¹ : ℂ) • B ∧ C₂ = 0))
    -- (b) combined residual criterion
    ∧ (∀ a b : ℂ, 0 ≤ a → 0 ≤ b →
        (a + b = 0 ↔ a = 0 ∧ b = 0))
    -- (c) polynomial resolvent membership
    ∧ (∀ A : Matrix n n ℂ,
        IsUnit ((1 : Matrix n n ℂ) - A) →
        ((1 : Matrix n n ℂ) - A)⁻¹ ∈ Algebra.adjoin ℂ {A})
    -- (d) nonzero signed return has positive residual
    ∧ (∀ B : Matrix n n ℂ, B ≠ 0 → (Bᴴ * B).trace ≠ 0) := by
  have htr0 : ∀ M : Matrix n n ℂ, (0 : ℂ) ≤ (Mᴴ * M).trace :=
    fun M => (Matrix.posSemidef_conjTranspose_mul_self M).trace_nonneg
  have h2pos : (0 : ℂ) ≤ 2 := by
    rw [show (2 : ℂ) = ((2 : ℝ) : ℂ) from by norm_cast]
    exact Complex.zero_le_real.mpr (by norm_num)
  have hzero : ∀ M : Matrix n n ℂ,
      (Mᴴ * M).trace = 0 ↔ M = 0 := fun M =>
    Matrix.trace_conjTranspose_mul_self_eq_zero_iff
  refine ⟨?_, ?_, ?_, ?_⟩
  · intro S C₀ C₂ B
    constructor
    · intro h0
      have hsplit1 := (add_eq_zero_iff_of_nonneg
        (add_nonneg (htr0 S) (mul_nonneg h2pos (htr0 _)))
        (mul_nonneg h2pos (htr0 C₂))).mp h0
      have hsplit2 := (add_eq_zero_iff_of_nonneg (htr0 S)
        (mul_nonneg h2pos (htr0 _))).mp hsplit1.1
      have hS := (hzero S).mp hsplit2.1
      have hC0 : C₀ - (2⁻¹ : ℂ) • B = 0 := by
        rcases mul_eq_zero.mp hsplit2.2 with h | h
        · exact absurd h two_ne_zero
        · exact (hzero _).mp h
      have hC2 : C₂ = 0 := by
        rcases mul_eq_zero.mp hsplit1.2 with h | h
        · exact absurd h two_ne_zero
        · exact (hzero _).mp h
      exact ⟨hS, sub_eq_zero.mp hC0, hC2⟩
    · rintro ⟨rfl, hC0, rfl⟩
      rw [hC0]
      simp
  · intro a b ha hb
    exact add_eq_zero_iff_of_nonneg ha hb
  · intro A hA
    refine inv_mem_of_isUnit ?_ hA
    exact sub_mem (Subalgebra.one_mem _)
      (Algebra.subset_adjoin rfl)
  · intro B hB h0
    exact hB ((hzero B).mp h0)

end NCG
