/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.KrylovLocalizerFlatnessExact

/-!
# Automatic finite operational-history saturation

For the finite cyclic history carrier, this module chooses the least stable
word depth and proves the reconstruction clauses of
`thm:automatic-history-saturation`: rank equality, full word span, generator
invariance, and uniqueness of every represented operation from its one-step
table on that span.
-/

open Submodule

namespace NCG
namespace AutomaticHistorySaturation

open KrylovLocalizerFlatness

variable {E : Type*} [NormedAddCommGroup E] [InnerProductSpace ℂ E]
  [FiniteDimensional ℂ E]

/-- The least depth at which two consecutive finite word/Krylov spans agree. -/
noncomputable def firstStableDepth
    (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) : ℕ :=
  Nat.find (by
    obtain ⟨n, -, -, hn⟩ := exists_stable_index T V
    exact ⟨n, hn⟩)

theorem firstStableDepth_spec (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) :
    krylov T V (firstStableDepth T V + 1) =
      krylov T V (firstStableDepth T V) := by
  unfold firstStableDepth
  exact Nat.find_spec (p := fun n =>
    krylov T V (n + 1) = krylov T V n) _

theorem firstStableDepth_least (T : E →ₗ[ℂ] E) (V : Submodule ℂ E)
    {n : ℕ} (hn : krylov T V (n + 1) = krylov T V n) :
    firstStableDepth T V ≤ n :=
  Nat.find_min' _ hn

theorem firstStableDepth_positive (T : E →ₗ[ℂ] E) (V : Submodule ℂ E)
    (hV : V ≠ ⊥) : 1 ≤ firstStableDepth T V := by
  by_contra h
  have hzero : firstStableDepth T V = 0 := by omega
  have hs := firstStableDepth_spec T V
  rw [hzero, krylov_one, krylov_zero] at hs
  exact hV hs

theorem firstStableDepth_bound (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) :
    firstStableDepth T V ≤ Module.finrank ℂ E + 1 := by
  obtain ⟨n, -, hn, hstable⟩ := exists_stable_index T V
  exact (firstStableDepth_least T V hstable).trans hn

/-- If `E` is the cyclic history carrier generated by the units/source `V`
and transition `T`, the first stable span is the whole carrier. -/
theorem firstStableDepth_eq_top
    (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) (hV : V ≠ ⊥)
    (hgenerated : ∀ M : Submodule ℂ E,
      V ≤ M → M.map T ≤ M → M = ⊤) :
    krylov T V (firstStableDepth T V) = ⊤ := by
  let r := firstStableDepth T V
  have hr : 1 ≤ r := firstStableDepth_positive T V hV
  have hstable : krylov T V (r + 1) = krylov T V r :=
    firstStableDepth_spec T V
  exact hgenerated _ (source_le_krylov T V hr)
    (krylov_stable_of_eq T V hr hstable)

/-- Once the word span is all of `E`, an operation is reconstructed uniquely
from its values on the depth-`r+1` panel. -/
theorem represented_operation_unique
    (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) (hV : V ≠ ⊥)
    (hgenerated : ∀ M : Submodule ℂ E,
      V ≤ M → M.map T ≤ M → M = ⊤)
    {F : Type*} [AddCommGroup F] [Module ℂ F]
    (A B : E →ₗ[ℂ] F)
    (hpanel : ∀ x, x ∈ krylov T V (firstStableDepth T V + 1) →
      A x = B x) : A = B := by
  apply LinearMap.ext
  intro x
  apply hpanel x
  rw [firstStableDepth_spec T V,
    firstStableDepth_eq_top T V hV hgenerated]
  trivial

/-- Full exact package for `thm:automatic-history-saturation`. -/
theorem automatic_history_saturation_exact
    (T : E →ₗ[ℂ] E) (V : Submodule ℂ E) (hV : V ≠ ⊥)
    (hgenerated : ∀ M : Submodule ℂ E,
      V ≤ M → M.map T ≤ M → M = ⊤) :
    let r := firstStableDepth T V
    (∀ n, krylov T V (n + 1) = krylov T V n → r ≤ n)
    ∧ Module.finrank ℂ (krylov T V r) =
        Module.finrank ℂ (krylov T V (r + 1))
    ∧ krylov T V r = ⊤
    ∧ (krylov T V r).map T ≤ krylov T V r
    ∧ ∀ {F : Type*} [AddCommGroup F] [Module ℂ F]
        (A B : E →ₗ[ℂ] F),
        (∀ x, x ∈ krylov T V (r + 1) → A x = B x) → A = B := by
  dsimp only
  let r := firstStableDepth T V
  have hr : 1 ≤ r := firstStableDepth_positive T V hV
  have hs : krylov T V (r + 1) = krylov T V r :=
    firstStableDepth_spec T V
  have htop : krylov T V r = ⊤ :=
    firstStableDepth_eq_top T V hV hgenerated
  refine ⟨fun _ hn => firstStableDepth_least T V hn,
    by rw [hs], htop, krylov_stable_of_eq T V hr hs, ?_⟩
  intro F _ _ A B hpanel
  exact represented_operation_unique T V hV hgenerated A B hpanel

end AutomaticHistorySaturation
end NCG
