/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.SMCentralDescentSelector
import NCG.Grand.SMGaugeQuotientExact

/-!
# Central-character descent through a cyclic quotient

This supplies the representation-theoretic layer of `thm:SM-selector`.
For a representation of a group whose quotient kernel is generated by one
element of order six, factorization through the quotient is equivalent to
triviality of that generator.  If its scalar central character has exponent
`2t+3s+y`, this is precisely the Standard-Model congruence.  The last theorem
normalizes the already proved finite Fourier sum to the indicator printed in
the manuscript.
-/

namespace NCG
namespace SMCentralDescentSelector

/-- A representation factors through a cyclic order-six quotient exactly
when its central-character exponent is divisible by six.  This is stated for
an arbitrary target group, so it applies in particular to finite-dimensional
linear and unitary representations. -/
theorem representation_descends_iff_centralExponent
    {G H : Type*} [Group G] [Group H]
    (N : Subgroup G) [N.Normal]
    (rho : G →* H) (generator : G) (zeta : H)
    (hN : N = Subgroup.zpowers generator)
    (hzeta : orderOf zeta = 6)
    (triality parity charge : ℤ)
    (hcharacter : rho generator =
      zeta ^ centralExponent triality parity charge) :
    (∃ descended : G ⧸ N →* H,
        descended.comp (QuotientGroup.mk' N) = rho) ↔
      (6 : ℤ) ∣ centralExponent triality parity charge := by
  constructor
  · rintro ⟨descended, hdescended⟩
    have hgenN : generator ∈ N := by
      rw [hN]
      exact Subgroup.mem_zpowers generator
    have hquot : QuotientGroup.mk' N generator = 1 :=
      (QuotientGroup.eq_one_iff generator).2 hgenN
    have heval := congrArg (fun f : G →* H => f generator) hdescended
    have hrho : rho generator = 1 := by
      calc
        rho generator =
            (descended.comp (QuotientGroup.mk' N)) generator := heval.symm
        _ = descended (QuotientGroup.mk' N generator) := rfl
        _ = descended 1 := by rw [hquot]
        _ = 1 := map_one descended
    have hzpow : zeta ^ centralExponent triality parity charge = 1 := by
      rw [← hcharacter, hrho]
    have horder := orderOf_dvd_iff_zpow_eq_one
      (x := zeta) (i := centralExponent triality parity charge)
    rw [hzeta] at horder
    exact horder.mpr hzpow
  · intro hdiv
    have horder := orderOf_dvd_iff_zpow_eq_one
      (x := zeta) (i := centralExponent triality parity charge)
    rw [hzeta] at horder
    have hzpow : zeta ^ centralExponent triality parity charge = 1 :=
      horder.mp hdiv
    have hrho : rho generator = 1 := hcharacter.trans hzpow
    have hker : N ≤ rho.ker := by
      intro x hx
      rw [hN] at hx
      obtain ⟨k, rfl⟩ := Subgroup.mem_zpowers_iff.mp hx
      simp [hrho]
    exact ⟨QuotientGroup.lift N rho hker,
      QuotientGroup.lift_comp_mk' N rho hker⟩

/-- The same quotient-factorization theorem in the label variables printed in
the Standard-Model statement. -/
theorem representation_descends_iff_sm_congruence
    {G H : Type*} [Group G] [Group H]
    (N : Subgroup G) [N.Normal]
    (rho : G →* H) (generator : G) (zeta : H)
    (hN : N = Subgroup.zpowers generator)
    (hzeta : orderOf zeta = 6)
    (triality parity charge : ℤ)
    (hcharacter : rho generator =
      zeta ^ centralExponent triality parity charge) :
    (∃ descended : G ⧸ N →* H,
        descended.comp (QuotientGroup.mk' N) = rho) ↔
      (6 : ℤ) ∣ 2 * triality + 3 * parity + charge := by
  simpa only [centralExponent] using
    representation_descends_iff_centralExponent N rho generator zeta hN
      hzeta triality parity charge hcharacter

/-- The normalized finite Fourier sum is exactly the descent indicator. -/
theorem normalized_descent_fourier_indicator
    (zeta : ℂ) (hzeta : orderOf zeta = 6) (m : ℕ) :
    (6 : ℂ)⁻¹ * (∑ k ∈ Finset.range 6, (zeta ^ m) ^ k) =
      if 6 ∣ m then 1 else 0 := by
  rw [descent_fourier_projector zeta hzeta m]
  split_ifs <;> norm_num

end SMCentralDescentSelector
end NCG
