/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.SmithCoordinatePontryaginExactSequence

/-!
# Pontryagin duality for chain homology

The circle group is divisible, hence injective in abelian groups.  Therefore
the contravariant additive-character functor `Hom(-, 𝕋)` preserves homology.
This is the universal-coefficient mechanism behind
`thm:chain-Pontryagin` in the Gran-Tensor manuscript.
-/

open CategoryTheory CategoryTheory.Limits Opposite

namespace NCG
namespace ChainPontryaginDuality

abbrev Circle := AddCircle (1 : ℝ)
abbrev CircleObject := AddCommGrpCat.of Circle

/-- The additive-character functor with values in the circle. -/
abbrev characterFunctor :
    AddCommGrpCatᵒᵖ ⥤ ModuleCat (End CircleObject) :=
  preadditiveYonedaObj CircleObject

/-- The circle-valued cochain complex dual to a chain complex. -/
abbrev characterCochainComplex {ι : Type*} {c : ComplexShape ι}
    (K : HomologicalComplex AddCommGrpCat c) :
    HomologicalComplex (ModuleCat (End CircleObject)) c.symm :=
  (characterFunctor.mapHomologicalComplex c.symm).obj K.op

/-- `thm:chain-Pontryagin`: cohomology of the circle-valued dual complex is
canonically the character group of integral homology. -/
noncomputable def cohomologyIsoCharacterHomology
    {ι : Type*} {c : ComplexShape ι}
    (K : HomologicalComplex AddCommGrpCat c) (i : ι)
    [K.HasHomology i] :
    (characterCochainComplex K).homology i ≅
      characterFunctor.obj (Opposite.op (K.homology i)) :=
  (K.op.sc i).mapHomologyIso characterFunctor ≪≫
    characterFunctor.mapIso (K.homologyOp i)

/-- The finite root subgroup `μ_d ⊂ 𝕋`. -/
abbrev RootGroupNat (d : ℕ) :=
  NCG.SmithCoordinatePontryagin.RootGroup (d : ℤ)

/-- Additive characters of a finite product are exactly tuples of additive
characters of its factors. -/
noncomputable def characterPiEquiv
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    {G : ι → Type*} [∀ i, AddCommGroup (G i)]
    {A : Type*} [AddCommGroup A] :
    ((∀ i, G i) →+ A) ≃+ (∀ i, G i →+ A) where
  toFun χ i := χ.comp (AddMonoidHom.single G i)
  invFun χ :=
    { toFun := fun x => ∑ i, χ i (x i)
      map_zero' := by simp
      map_add' := by
        intro x y
        simp only [Pi.add_apply, map_add, Finset.sum_add_distrib] }
  left_inv χ := by
    apply AddMonoidHom.ext
    intro x
    change (∑ i, χ (Pi.single i (x i))) = χ x
    rw [← map_sum]
    congr 1
    funext j
    simp
  right_inv χ := by
    funext i
    apply AddMonoidHom.ext
    intro x
    change (∑ j, χ j (Pi.single i x j)) = χ i x
    rw [Fintype.sum_eq_single i]
    · simp
    · intro j hji
      simp [Pi.single_eq_of_ne hji]
  map_add' _ _ := rfl

/-- The value at one of a cyclic character, regarded as a root point. -/
def characterRootValue (d : ℕ) (χ : ZMod d →+ Circle) :
    RootGroupNat d := ⟨χ 1, by
    change (d : ℤ) • χ 1 = 0
    rw [← map_zsmul]
    simp⟩

/-- The cyclic character generated by a root point. -/
noncomputable def rootValueCharacter (d : ℕ) (x : RootGroupNat d) :
    ZMod d →+ Circle := ZMod.lift d
    ⟨{ toFun := fun z => z • (x : Circle)
       map_zero' := by simp
       map_add' := by intro a b; simp [add_smul] }, by
      change (d : ℤ) • (x : Circle) = 0
      have hx : (x : Circle) ∈ AddMonoidHom.ker
          ((d : ℤ) • AddMonoidHom.id Circle) := x.property
      rw [AddMonoidHom.mem_ker] at hx
      simpa using hx⟩

@[simp] theorem rootValueCharacter_intCast (d : ℕ)
    (x : RootGroupNat d) (k : ℤ) :
    rootValueCharacter d x (k : ZMod d) = k • (x : Circle) := by
  exact ZMod.lift_coe d _ k

/-- A character of `ℤ/dℤ` is uniquely its value at one, and that value is a
`d`-torsion point of the circle. -/
noncomputable def cyclicCharacterEquivRootGroup (d : ℕ) :
    (ZMod d →+ Circle) ≃+ RootGroupNat d where
  toFun := characterRootValue d
  invFun := rootValueCharacter d
  left_inv χ := by
    apply AddMonoidHom.ext
    intro z
    obtain ⟨k, rfl⟩ := ZMod.intCast_surjective z
    rw [rootValueCharacter_intCast]
    change k • χ 1 = χ (k : ZMod d)
    rw [← map_zsmul]
    congr 1
    simp
  right_inv x := by
    apply Subtype.ext
    change rootValueCharacter d x 1 = (x : Circle)
    simpa using rootValueCharacter_intCast d x (1 : ℤ)
  map_add' _ _ := by
    apply Subtype.ext
    rfl

/-- The displayed decomposition
`Hom(ℤ^b ⊕ ⨁ⱼ ℤ/dⱼℤ, 𝕋) ≃ 𝕋^b × ∏ⱼ μ_{dⱼ}`. -/
noncomputable def finitelyGeneratedCharacterDecomposition
    (b s : ℕ) (d : Fin s → ℕ) :
    (((Fin b → ℤ) × (∀ j : Fin s, ZMod (d j))) →+ Circle) ≃+
      ((Fin b → Circle) × (∀ j : Fin s, RootGroupNat (d j))) :=
  NCG.SmithCoordinatePontryagin.characterProdEquiv.trans
    ((NCG.SmithCoordinatePontryagin.characterCoordinates
        (Pi.basisFun ℤ (Fin b))).prodCongr
      ((characterPiEquiv (G := fun j : Fin s => ZMod (d j))).trans
        (AddEquiv.piCongrRight fun j =>
          cyclicCharacterEquivRootGroup (d j))))

/-- Complete cycle--flat-connection Pontryagin package: the canonical UCT
isomorphism for every chain complex, together with the explicit free/cyclic
decomposition of the resulting character group. -/
theorem chainPontryaginDuality
    {ι : Type*} {c : ComplexShape ι}
    (K : HomologicalComplex AddCommGrpCat c) (i : ι)
    [K.HasHomology i] (b s : ℕ) (d : Fin s → ℕ) :
    Nonempty
      ((characterCochainComplex K).homology i ≅
        characterFunctor.obj (Opposite.op (K.homology i)))
    ∧ Nonempty
      ((((Fin b → ℤ) × (∀ j : Fin s, ZMod (d j))) →+ Circle) ≃+
        ((Fin b → Circle) × (∀ j : Fin s, RootGroupNat (d j)))) := by
  exact ⟨⟨cohomologyIsoCharacterHomology K i⟩,
    ⟨finitelyGeneratedCharacterDecomposition b s d⟩⟩

end ChainPontryaginDuality
end NCG
