/-
Copyright (c) 2026 Aurelien Pelissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurelien Pelissier
-/
import NCG.Grand.FiniteStarDerivations

/-!
# Channel-native reversible mixer tangents

This file proves `thm:SMST-channel-native-tangent` from the finite residuals
appearing in the manuscript.  An encoder `iota` and decoder `decode` model the
source-fixing matrix-algebra embedding; the sole structural hypothesis is the
exact retraction identity `decode (iota X) = X`.

The tangent defect is the sum of

* the two finite core-preservation residuals;
* the Leibniz and star residuals of the two compressed tangents; and
* the squared Hilbert--Schmidt norm of their sum on every matrix unit.

Its zero branch is equivalent to one unique traceless Hermitian matrix `H`
whose forward tangent is `-i[H,-]` and whose reverse tangent is `+i[H,-]` on
the encoded algebra.  No finite-time unitary hypothesis is used.
-/

open Matrix Finset

namespace NCG

variable {d f : Type*} [Fintype d] [DecidableEq d]
  [Fintype f] [DecidableEq f]

/-- The Hamiltonian derivation generated by `H`, with the manuscript's
`-i[H,-]` convention. -/
def hamiltonianDerivation (H : Matrix d d ℂ) :
    Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ where
  toFun X := (-Complex.I) • (H * X - X * H)
  map_add' X Y := by
    simp only [Matrix.mul_add, Matrix.add_mul]
    module
  map_smul' c X := by
    ext i j
    simp [Matrix.mul_apply, smul_eq_mul]
    ring

@[simp]
theorem hamiltonianDerivation_apply (H X : Matrix d d ℂ) :
    hamiltonianDerivation H X = (-Complex.I) • (H * X - X * H) := rfl

@[simp]
theorem hamiltonianDerivation_neg (H : Matrix d d ℂ) :
    hamiltonianDerivation (-H) = -hamiltonianDerivation H := by
  apply LinearMap.ext
  intro X
  simp only [hamiltonianDerivation_apply, LinearMap.neg_apply,
    Matrix.neg_mul, Matrix.mul_neg, neg_sub_neg]
  module

/-- Compression of a full-cell tangent to the logical matrix carrier. -/
def compressedTangent
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (L : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) :
    Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ :=
  decode.comp (L.comp iota)

@[simp]
theorem compressedTangent_apply
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (L : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ)
    (X : Matrix d d ℂ) :
    compressedTangent decode iota L X = decode (L (iota X)) := rfl

/-- Failure of a full tangent to preserve the encoded logical algebra, tested
on the complete matrix-unit basis. -/
def channelTangentCoreResidual
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (L : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) : ℝ :=
  ∑ p : d × d, hsFrobSq
    (L (iota (Matrix.single p.1 p.2 1))
      - iota (compressedTangent decode iota L
          (Matrix.single p.1 p.2 1)))

/-- Finite Hamiltonian defect of a logical tangent. -/
def hamiltonianResidual
    (L : Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ) : ℝ :=
  leibnizResidual L + starResidual L

/-- Squared superoperator Hilbert--Schmidt norm on the matrix-unit basis. -/
def tangentSuperHSSq
    (L : Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ) : ℝ :=
  ∑ p : d × d, hsFrobSq (L (Matrix.single p.1 p.2 1))

/-- The five-term reversible channel-tangent defect. -/
def channelTangentResidual
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (Lplus Lminus : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) : ℝ :=
  channelTangentCoreResidual decode iota Lplus
    + channelTangentCoreResidual decode iota Lminus
    + hamiltonianResidual (compressedTangent decode iota Lplus)
    + hamiltonianResidual (compressedTangent decode iota Lminus)
    + tangentSuperHSSq
        (compressedTangent decode iota Lplus
          + compressedTangent decode iota Lminus)

theorem channelTangentCoreResidual_nonneg
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (L : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) :
    0 ≤ channelTangentCoreResidual decode iota L := by
  exact Finset.sum_nonneg fun p _ => hsFrobSq_nonneg _

theorem hamiltonianResidual_nonneg
    (L : Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ) :
    0 ≤ hamiltonianResidual L := by
  apply add_nonneg
  · exact Finset.sum_nonneg fun p _ => hsFrobSq_nonneg _
  · exact Finset.sum_nonneg fun p _ => hsFrobSq_nonneg _

theorem tangentSuperHSSq_nonneg
    (L : Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ) :
    0 ≤ tangentSuperHSSq L := by
  exact Finset.sum_nonneg fun p _ => hsFrobSq_nonneg _

/-- The manuscript's tangent defect is manifestly nonnegative. -/
theorem channelTangentResidual_nonneg
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (Lplus Lminus : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) :
    0 ≤ channelTangentResidual decode iota Lplus Lminus := by
  unfold channelTangentResidual
  exact add_nonneg
    (add_nonneg
      (add_nonneg
        (add_nonneg
          (channelTangentCoreResidual_nonneg decode iota Lplus)
          (channelTangentCoreResidual_nonneg decode iota Lminus))
        (hamiltonianResidual_nonneg _))
      (hamiltonianResidual_nonneg _))
    (tangentSuperHSSq_nonneg _)

private theorem channelTangentCoreResidual_eq_zero_iff
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (L : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) :
    channelTangentCoreResidual decode iota L = 0 ↔
      ∀ X, L (iota X) = iota (compressedTangent decode iota L X) := by
  constructor
  · intro hzero
    have hunit : ∀ a b : d,
        L (iota (Matrix.single a b 1)) =
          iota (compressedTangent decode iota L (Matrix.single a b 1)) := by
      intro a b
      have hterm := (Finset.sum_eq_zero_iff_of_nonneg
        (fun p _ => hsFrobSq_nonneg
          (L (iota (Matrix.single p.1 p.2 1))
            - iota (compressedTangent decode iota L
                (Matrix.single p.1 p.2 1))))).mp hzero
          (a, b) (mem_univ _)
      exact sub_eq_zero.mp ((hsFrobSq_eq_zero_iff _).mp hterm)
    intro X
    induction X using Matrix.induction_on' with
    | h_zero => simp
    | h_add A B hA hB => simp only [map_add, hA, hB]
    | h_std_basis a b c =>
        have hsingle : Matrix.single a b c =
            c • Matrix.single a b (1 : ℂ) := by
          rw [Matrix.smul_single, smul_eq_mul, mul_one]
        rw [hsingle]
        simp only [map_smul, hunit]
  · intro h
    unfold channelTangentCoreResidual
    refine Finset.sum_eq_zero fun p _ => ?_
    rw [h, sub_self]
    exact (hsFrobSq_eq_zero_iff _).2 rfl

private theorem tangentSuperHSSq_eq_zero_iff
    (L : Matrix d d ℂ →ₗ[ℂ] Matrix d d ℂ) :
    tangentSuperHSSq L = 0 ↔ L = 0 := by
  constructor
  · intro hzero
    apply LinearMap.ext
    intro X
    induction X using Matrix.induction_on' with
    | h_zero => simp
    | h_add A B hA hB => simp only [map_add, hA, hB, add_zero]
    | h_std_basis a b c =>
        have hterm := (Finset.sum_eq_zero_iff_of_nonneg
          (fun p _ => hsFrobSq_nonneg (L (Matrix.single p.1 p.2 1)))).mp hzero
            (a, b) (mem_univ _)
        have hunit : L (Matrix.single a b 1) = 0 :=
          (hsFrobSq_eq_zero_iff _).mp hterm
        have hsingle : Matrix.single a b c =
            c • Matrix.single a b (1 : ℂ) := by
          rw [Matrix.smul_single, smul_eq_mul, mul_one]
        change L (Matrix.single a b c) = 0
        rw [hsingle, map_smul, hunit, smul_zero]
  · rintro rfl
    unfold tangentSuperHSSq
    simp [hsFrobSq]

private theorem hamiltonianResidual_hamiltonian
    (H : Matrix d d ℂ) (hH : Hᴴ = H) :
    hamiltonianResidual (hamiltonianDerivation H) = 0 := by
  have hLeib : leibnizResidual (hamiltonianDerivation H) = 0 := by
    unfold leibnizResidual
    refine Finset.sum_eq_zero fun p _ => ?_
    apply (hsFrobSq_eq_zero_iff _).2
    unfold leibnizUnitDefect
    simp only [hamiltonianDerivation_apply, Matrix.smul_mul,
      Matrix.mul_smul, Matrix.mul_assoc]
    rw [← smul_sub, ← smul_sub]
    congr 1
    noncomm_ring
    simp
  have hstar : starResidual (hamiltonianDerivation H) = 0 := by
    unfold starResidual
    refine Finset.sum_eq_zero fun p _ => ?_
    apply (hsFrobSq_eq_zero_iff _).2
    unfold starUnitDefect
    simp only [hamiltonianDerivation_apply, Matrix.conjTranspose_smul,
      Matrix.conjTranspose_sub, Matrix.conjTranspose_mul,
      Matrix.conjTranspose_single, hH]
    simp only [star_one]
    change (-Complex.I) •
        (H * Matrix.single p.2 p.1 1 - Matrix.single p.2 p.1 1 * H)
      - (star (-Complex.I)) •
        (Matrix.single p.2 p.1 1 * H - H * Matrix.single p.2 p.1 1) = 0
    rw [show star (-Complex.I) = Complex.I by
      simpa only [Complex.star_def] using Complex.conj_neg_I]
    module
  unfold hamiltonianResidual
  rw [hLeib, hstar, add_zero]

/-- `thm:SMST-channel-native-tangent`: exact characterization of the zero
five-term tangent defect. -/
theorem channel_native_reversible_tangent [Nonempty d]
    (decode : Matrix f f ℂ →ₗ[ℂ] Matrix d d ℂ)
    (iota : Matrix d d ℂ →ₗ[ℂ] Matrix f f ℂ)
    (hretract : ∀ X, decode (iota X) = X)
    (Lplus Lminus : Matrix f f ℂ →ₗ[ℂ] Matrix f f ℂ) :
    channelTangentResidual decode iota Lplus Lminus = 0 ↔
      ∃! H : Matrix d d ℂ,
        Hᴴ = H ∧ Matrix.trace H = 0 ∧
        ∀ X,
          Lplus (iota X) = iota (hamiltonianDerivation H X) ∧
          Lminus (iota X) = iota (hamiltonianDerivation (-H) X) := by
  let Lp := compressedTangent decode iota Lplus
  let Lm := compressedTangent decode iota Lminus
  have hiota : Function.Injective iota := by
    intro X Y hXY
    have := congrArg decode hXY
    simpa only [hretract] using this
  constructor
  · intro hzero
    have hpieces :
        channelTangentCoreResidual decode iota Lplus = 0 ∧
        channelTangentCoreResidual decode iota Lminus = 0 ∧
        hamiltonianResidual Lp = 0 ∧
        hamiltonianResidual Lm = 0 ∧
        tangentSuperHSSq (Lp + Lm) = 0 := by
      have hcP := channelTangentCoreResidual_nonneg decode iota Lplus
      have hcM := channelTangentCoreResidual_nonneg decode iota Lminus
      have hhP := hamiltonianResidual_nonneg Lp
      have hhM := hamiltonianResidual_nonneg Lm
      have hs := tangentSuperHSSq_nonneg (Lp + Lm)
      unfold channelTangentResidual at hzero
      change channelTangentCoreResidual decode iota Lplus
          + channelTangentCoreResidual decode iota Lminus
          + hamiltonianResidual Lp + hamiltonianResidual Lm
          + tangentSuperHSSq (Lp + Lm) = 0 at hzero
      constructor
      · nlinarith
      constructor
      · nlinarith
      constructor
      · nlinarith
      constructor <;> nlinarith
    obtain ⟨hcP, hcM, hhP, hhM, hsum⟩ := hpieces
    have hLpParts : leibnizResidual Lp = 0 ∧ starResidual Lp = 0 := by
      unfold hamiltonianResidual at hhP
      have hl : 0 ≤ leibnizResidual Lp := by
        exact Finset.sum_nonneg
          (fun (p : d × d × d × d) _ => hsFrobSq_nonneg (leibnizUnitDefect Lp p))
      have hs' : 0 ≤ starResidual Lp := by
        exact Finset.sum_nonneg
          (fun (p : d × d) _ => hsFrobSq_nonneg (starUnitDefect Lp p))
      constructor
      · nlinarith
      · nlinarith
    have hLmParts : leibnizResidual Lm = 0 ∧ starResidual Lm = 0 := by
      unfold hamiltonianResidual at hhM
      have hl : 0 ≤ leibnizResidual Lm := by
        exact Finset.sum_nonneg
          (fun (p : d × d × d × d) _ => hsFrobSq_nonneg (leibnizUnitDefect Lm p))
      have hs' : 0 ≤ starResidual Lm := by
        exact Finset.sum_nonneg
          (fun (p : d × d) _ => hsFrobSq_nonneg (starUnitDefect Lm p))
      constructor
      · nlinarith
      · nlinarith
    obtain ⟨Hp, hHp, hHpUnique⟩ :=
      finite_star_derivation_inner Lp hLpParts.1 hLpParts.2
    obtain ⟨Hm, hHm, hHmUnique⟩ :=
      finite_star_derivation_inner Lm hLmParts.1 hLmParts.2
    have hmapsum : Lp + Lm = 0 :=
      (tangentSuperHSSq_eq_zero_iff (Lp + Lm)).mp hsum
    have hHmNeg : Hm = -Hp := by
      symm
      apply hHmUnique (-Hp)
      refine ⟨?_, ?_, ?_⟩
      · rw [Matrix.conjTranspose_neg, hHp.1]
      · rw [Matrix.trace_neg, hHp.2.1, neg_zero]
      · intro X
        have hsX := LinearMap.congr_fun hmapsum X
        simp only [LinearMap.add_apply, LinearMap.zero_apply] at hsX
        calc
          Lm X = -Lp X := eq_neg_of_add_eq_zero_right hsX
          _ = -((-Complex.I) • (Hp * X - X * Hp)) := by rw [hHp.2.2 X]
          _ = (-Complex.I) • (-Hp * X - X * -Hp) := by
            simp only [Matrix.neg_mul, Matrix.mul_neg, neg_sub_neg]
            module
    have hcoreP := (channelTangentCoreResidual_eq_zero_iff decode iota Lplus).mp hcP
    have hcoreM := (channelTangentCoreResidual_eq_zero_iff decode iota Lminus).mp hcM
    refine ⟨Hp, ⟨hHp.1, hHp.2.1, ?_⟩, ?_⟩
    · intro X
      constructor
      · rw [hcoreP X, hHp.2.2 X]
        rfl
      · rw [hcoreM X, hHm.2.2 X, hHmNeg]
        rfl
    · intro H hH
      apply hHpUnique H
      refine ⟨hH.1, hH.2.1, ?_⟩
      intro X
      change decode (Lplus (iota X)) =
        (-Complex.I) • (H * X - X * H)
      rw [(hH.2.2 X).1, hretract]
      rfl
  · rintro ⟨H, hH, -⟩
    have hLp : Lp = hamiltonianDerivation H := by
      apply LinearMap.ext
      intro X
      change decode (Lplus (iota X)) = _
      rw [hH.2.2 X |>.1, hretract]
    have hLm : Lm = hamiltonianDerivation (-H) := by
      apply LinearMap.ext
      intro X
      change decode (Lminus (iota X)) = _
      rw [hH.2.2 X |>.2, hretract]
    have hcP : channelTangentCoreResidual decode iota Lplus = 0 :=
      (channelTangentCoreResidual_eq_zero_iff decode iota Lplus).2 fun X => by
        rw [hH.2.2 X |>.1]
        change iota (hamiltonianDerivation H X) = iota (Lp X)
        rw [hLp]
    have hcM : channelTangentCoreResidual decode iota Lminus = 0 :=
      (channelTangentCoreResidual_eq_zero_iff decode iota Lminus).2 fun X => by
        rw [hH.2.2 X |>.2]
        change iota (hamiltonianDerivation (-H) X) = iota (Lm X)
        rw [hLm]
    have hhP : hamiltonianResidual Lp = 0 := by
      rw [hLp]
      exact hamiltonianResidual_hamiltonian H hH.1
    have hnegH : (-H)ᴴ = -H := by rw [Matrix.conjTranspose_neg, hH.1]
    have hhM : hamiltonianResidual Lm = 0 := by
      rw [hLm]
      exact hamiltonianResidual_hamiltonian (-H) hnegH
    have hs : tangentSuperHSSq (Lp + Lm) = 0 := by
      apply (tangentSuperHSSq_eq_zero_iff (Lp + Lm)).2
      rw [hLp, hLm, hamiltonianDerivation_neg, add_neg_cancel]
    unfold channelTangentResidual
    change channelTangentCoreResidual decode iota Lplus
        + channelTangentCoreResidual decode iota Lminus
        + hamiltonianResidual Lp + hamiltonianResidual Lm
        + tangentSuperHSSq (Lp + Lm) = 0
    rw [hcP, hcM, hhP, hhM, hs]
    norm_num

end NCG
