/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib
import NCG.Grand.BoundarySpectralShift
import NCG.Grand.CompletionAggregate
import NCG.Grand.ConditionalCoreMinimality
import NCG.Grand.GrandScoreControl
import NCG.Grand.EdgeActionPythagoras
import NCG.Grand.JointSourceCore

/-!
# Completion aggregate inversion and stability

Full-statement formalizations for completion aggregation:

* `thm:completion-aggregate-inversion` —
  `completion_aggregate_inversion_exact`,
  `completion_aggregate_injective`: the geometric dwell series
  is summed by a genuine Neumann series (no hypothesized
  resolvent), all boxed inversion/kernel/rank clauses follow,
  and the transform is injective on contractions.
* `thm:completion-aggregate-stability` —
  `completion_aggregate_stability_exact`: the boxed Lipschitz
  bound with the resolvent bound `K = (1+s)/(1-s)` and
  `‖A_s‖ ≤ 1` *proved* from the Neumann series, and the boxed
  `L_{1/3} = 10/3` evaluation.
* `thm:corrected-Douglas-factor` —
  `corrected_douglas_factor_exact`, `douglas_order_equivalence`:
  the boxed reduced factor with uniqueness, and the finite
  Douglas order-equivalence
  `S₁S₁ᴴ ⪯ S₂S₂ᴴ ↔ ∃ contraction factor`.
* `thm:connected-edge-action-Pythagoras` —
  `edge_action_pythagoras_vector`,
  `edge_action_router_unitary`, `connected_edge_action_exact`:
  the boxed quadratic-form Pythagoras, the equal-dimension
  metric-unitary clause, and the bundled congruence/Schur
  clauses.
* `thm:boundary-spectral-shift` —
  `boundary_spectral_shift_exact`: the three proved clauses
  (Schur determinant ratio, boxed log-derivative, boxed contour
  count) bundled over one common-interior block system.
* `thm:conditional-core-minimality` —
  `conditional_core_direct_sum_exact`: the boxed direct-sum
  predictive core assembled as a block diagonal — sector moment
  preservation, cross-sector separation, and the unique
  assembled record-fixing gauge.
* `thm:collision-parity-Hodge` —
  `collision_parity_hodge_exact`: both boxed orthogonal Hodge
  splits instantiated at the concrete odd/even incidence
  matrices of a finite graph, the boxed `b_G = ½∂₊ᴴ𝟙`
  identity, and the vanishing of `b_G` against every even
  cycle.
* `thm:automatic-history-saturation` —
  `history_saturation_exact`: existence of the least
  saturation depth for the boxed Gram-rank equality, span
  freezing from that depth on, and reconstruction (the
  stabilized span is the whole represented history space and
  is invariant under every generator).
* `thm:canonical-score-control` —
  `canonical_score_control_exact`, `score_su2_block_generation`:
  the bundled pulse-group/kickback/controlled-`Z` clauses and
  the dynamical `su(2)`-block clause — on distinct nonzero
  anticommuting frequencies the Lie algebra generated by `L`
  and `-iZ_c` contains each block `su(2)` (via a Vandermonde
  isolation of the frequency blocks).
* `thm:classical-entry-edge-obstruction` —
  `entry_edge_joint_law`, `entry_edge_gram_entry`/`_edge`/
  `_cross`, `entry_edge_residual_bound`,
  `classical_entry_edge_obstruction_exact`: the `S₄`-orbit
  joint law, the boxed Gram blocks `¼I, ⅓I, (2t-1)/6·I`, the
  normalized transport `ρ_t = (2t-1)/√3` with `|ρ_t| ≤ 1/√3`,
  and the boxed Schur residual bound `I - ρ_t²I ⪰ ⅔I ≠ 0`.
-/

open Matrix
open scoped ComplexOrder
open scoped Matrix.Norms.L2Operator

namespace NCG

/-! ## `thm:completion-aggregate-inversion`: Neumann discharge -/

/-- `thm:completion-aggregate-inversion`, exact form.  For a
genuine contraction `‖D₀‖ ≤ 1` (`ℓ²` operator norm) and
`0 ≤ s < 1`, with `c = 1 - s`: the defining dwell series
`Σ_k c·s^k·D₀^{k+1}` converges (`HasSum`) to the boxed
`A_s = c·D₀(I - sD₀)⁻¹`, where the Neumann resolvent
`Σ (sD₀)^n` is *proved* to be a two-sided inverse of
`I - sD₀`; the boxed resolvent identity `cI + sA_s = c(I-sD₀)⁻¹`,
the boxed two-sided operator inverse
`D₀ = A_s(cI+sA_s)⁻¹ = (cI+sA_s)⁻¹A_s`, and the boxed kernel and
rank identities `Ker A_s = Ker D₀`, `rank A_s = rank D₀` all
follow with no assumed invertibility. -/
theorem completion_aggregate_inversion_exact {n : Type*}
    [Fintype n] [DecidableEq n]
    (D : Matrix n n ℂ) {s : ℝ} (hD : ‖D‖ ≤ 1)
    (hs0 : 0 ≤ s) (hs1 : s < 1) :
    -- the dwell series sums to the boxed `A_s = cD₀(I-sD₀)⁻¹`
    HasSum
      (fun k : ℕ => (((1 - s : ℝ) : ℂ) * (s : ℂ) ^ k) • D ^ (k + 1))
      (((1 - s : ℝ) : ℂ) • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k))
    -- the Neumann resolvent is a two-sided inverse of `I - sD₀`
    ∧ (1 - (s : ℂ) • D) * (∑' k : ℕ, ((s : ℂ) • D) ^ k) = 1
    ∧ (∑' k : ℕ, ((s : ℂ) • D) ^ k) * (1 - (s : ℂ) • D) = 1
    -- commutation with the resolvent factor
    ∧ D * (∑' k : ℕ, ((s : ℂ) • D) ^ k)
        = (∑' k : ℕ, ((s : ℂ) • D) ^ k) * D
    -- the boxed resolvent identity `cI + sA_s = c(I - sD₀)⁻¹`
    ∧ ((1 - s : ℝ) : ℂ) • (1 : Matrix n n ℂ)
        + (s : ℂ) • (((1 - s : ℝ) : ℂ)
            • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k))
        = ((1 - s : ℝ) : ℂ) • (∑' k : ℕ, ((s : ℂ) • D) ^ k)
    -- the boxed two-sided operator inverse
    ∧ (((1 - s : ℝ) : ℂ) • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k))
        * ((((1 - s : ℝ) : ℂ))⁻¹ • (1 - (s : ℂ) • D)) = D
    ∧ ((((1 - s : ℝ) : ℂ))⁻¹ • (1 - (s : ℂ) • D))
        * (((1 - s : ℝ) : ℂ) • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k))
        = D
    -- the boxed kernel identity `Ker A_s = Ker D₀`
    ∧ (∀ {m : Type} [Fintype m] (X : Matrix n m ℂ),
        (((1 - s : ℝ) : ℂ) • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k))
            * X = 0
          ↔ D * X = 0)
    -- the boxed rank identity `rank A_s = rank D₀`
    ∧ (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k).rank = D.rank := by
  haveI : CompleteSpace (Matrix n n ℂ) :=
    FiniteDimensional.complete ℂ _
  have hnorm : ‖(s : ℂ) • D‖ < 1 := by
    rw [norm_smul, Complex.norm_real, Real.norm_eq_abs,
      abs_of_nonneg hs0]
    calc s * ‖D‖ ≤ s * 1 :=
          mul_le_mul_of_nonneg_left hD hs0
      _ = s := mul_one s
      _ < 1 := hs1
  have hsummable : Summable fun k : ℕ => ((s : ℂ) • D) ^ k :=
    summable_geometric_of_norm_lt_one hnorm
  have h1 : (1 - (s : ℂ) • D) * (∑' k : ℕ, ((s : ℂ) • D) ^ k)
      = 1 := mul_neg_geom_series _ hnorm
  have h2 : (∑' k : ℕ, ((s : ℂ) • D) ^ k) * (1 - (s : ℂ) • D)
      = 1 := geom_series_mul_neg _ hnorm
  have hc : ((1 - s : ℝ) : ℂ) ≠ 0 :=
    Complex.ofReal_ne_zero.mpr (by linarith)
  have hsum : HasSum
      (fun k : ℕ => (((1 - s : ℝ) : ℂ) * (s : ℂ) ^ k)
        • D ^ (k + 1))
      (((1 - s : ℝ) : ℂ)
        • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k)) := by
    have h := (hsummable.hasSum.mul_left D).const_smul
      (((1 - s : ℝ) : ℂ))
    have hfun : (fun k : ℕ =>
        ((1 - s : ℝ) : ℂ) • (D * ((s : ℂ) • D) ^ k))
        = fun k : ℕ => (((1 - s : ℝ) : ℂ) * (s : ℂ) ^ k)
            • D ^ (k + 1) := by
      funext k
      rw [smul_pow, mul_smul_comm, smul_smul, ← pow_succ']
    rwa [hfun] at h
  obtain ⟨hcomm, hres, hinvL, hinvR, hker, hrank⟩ :=
    completion_aggregate_inversion D
      (∑' k : ℕ, ((s : ℂ) • D) ^ k) (s : ℂ) ((1 - s : ℝ) : ℂ)
      hc h1 h2
  exact ⟨hsum, h1, h2, hcomm, hres, hinvL, hinvR, hker, hrank⟩

/-- `thm:completion-aggregate-inversion`, injectivity clause:
the linear-fractional dwell transform is injective on
contractions — equal aggregates `A_s` force equal centered
channels `D₀`. -/
theorem completion_aggregate_injective {n : Type*}
    [Fintype n] [DecidableEq n]
    (D D' : Matrix n n ℂ) {s : ℝ}
    (hD : ‖D‖ ≤ 1) (hD' : ‖D'‖ ≤ 1)
    (hs0 : 0 ≤ s) (hs1 : s < 1)
    (heq : ((1 - s : ℝ) : ℂ)
        • (D * ∑' k : ℕ, ((s : ℂ) • D) ^ k)
      = ((1 - s : ℝ) : ℂ)
        • (D' * ∑' k : ℕ, ((s : ℂ) • D') ^ k)) :
    D = D' := by
  obtain ⟨_, h1, h2, _, hres, _, _, _, _⟩ :=
    completion_aggregate_inversion_exact D hD hs0 hs1
  obtain ⟨_, h1', h2', _, hres', _, _, _, _⟩ :=
    completion_aggregate_inversion_exact D' hD' hs0 hs1
  have hc : ((1 - s : ℝ) : ℂ) ≠ 0 :=
    Complex.ofReal_ne_zero.mpr (by linarith)
  -- the resolvents agree because the aggregates do
  have hRi : (∑' k : ℕ, ((s : ℂ) • D) ^ k)
      = ∑' k : ℕ, ((s : ℂ) • D') ^ k := by
    have h := hres
    rw [heq, hres'] at h
    exact smul_right_injective (Matrix n n ℂ) hc h.symm
  rcases eq_or_ne s 0 with hs | hs
  · -- at `s = 0` the resolvent is `1` and `A₀ = D₀`
    subst hs
    have hR1 : (∑' k : ℕ, (((0 : ℝ) : ℂ) • D) ^ k)
        = (1 : Matrix n n ℂ) := by
      have h := h2
      simpa only [Complex.ofReal_zero, zero_smul, sub_zero,
        Matrix.mul_one] using h
    have hR1' : (∑' k : ℕ, (((0 : ℝ) : ℂ) • D') ^ k)
        = (1 : Matrix n n ℂ) := by
      have h := h2'
      simpa only [Complex.ofReal_zero, zero_smul, sub_zero,
        Matrix.mul_one] using h
    have h := heq
    rw [hR1, hR1', Matrix.mul_one, Matrix.mul_one] at h
    simpa using h
  · -- at `s ≠ 0` the two left inverses of one unit coincide
    have hsC : ((s : ℝ) : ℂ) ≠ 0 := Complex.ofReal_ne_zero.mpr hs
    have h1'' : (1 - (s : ℂ) • D')
        * (∑' k : ℕ, ((s : ℂ) • D) ^ k) = 1 := by
      rw [hRi]
      exact h1'
    have hdiff : ((1 - (s : ℂ) • D) - (1 - (s : ℂ) • D'))
        * (∑' k : ℕ, ((s : ℂ) • D) ^ k) = 0 := by
      rw [Matrix.sub_mul, h1, h1'', sub_self]
    have hzero : (1 - (s : ℂ) • D) - (1 - (s : ℂ) • D') = 0 := by
      calc
        (1 - (s : ℂ) • D) - (1 - (s : ℂ) • D')
            = ((1 - (s : ℂ) • D) - (1 - (s : ℂ) • D')) * 1 := by
                rw [Matrix.mul_one]
        _ = ((1 - (s : ℂ) • D) - (1 - (s : ℂ) • D'))
              * ((∑' k : ℕ, ((s : ℂ) • D) ^ k)
                * (1 - (s : ℂ) • D)) := by rw [h2]
        _ = (((1 - (s : ℂ) • D) - (1 - (s : ℂ) • D'))
              * (∑' k : ℕ, ((s : ℂ) • D) ^ k))
                * (1 - (s : ℂ) • D) := by rw [Matrix.mul_assoc]
        _ = 0 := by rw [hdiff, Matrix.zero_mul]
    have hsm : (s : ℂ) • D = (s : ℂ) • D' := by
      have h : (1 : Matrix n n ℂ) - (s : ℂ) • D
          = 1 - (s : ℂ) • D' := sub_eq_zero.mp hzero
      have h' := congrArg
        (fun M => (1 : Matrix n n ℂ) - M) h
      simpa using h'
    exact smul_right_injective (Matrix n n ℂ) hsC hsm

/-! ## `thm:completion-aggregate-stability`: proved bounds -/

/-- `thm:completion-aggregate-stability`, exact form: for two
genuine contractions and `0 ≤ s < 1`, the boxed Lipschitz
reconstruction
`‖D₀ - D̃₀‖ ≤ L_s‖A_s - Ã_s‖` with
`L_s = (1+s)/(1-s) + s((1+s)/(1-s))²`, where the aggregates are
the *Neumann-summed* transfers and the resolvent bound
`‖(cI+sA_s)⁻¹‖ ≤ (1+s)/c` and `‖A_s‖ ≤ 1` are proved, not
assumed; and the boxed evaluation `L_{1/3} = 10/3`. -/
theorem completion_aggregate_stability_exact {A : Type*}
    [NormedRing A] [NormedAlgebra ℝ A] [CompleteSpace A]
    [NormOneClass A]
    (D D' : A) {s : ℝ} (hD : ‖D‖ ≤ 1) (hD' : ‖D'‖ ≤ 1)
    (hs0 : 0 ≤ s) (hs1 : s < 1) :
    ‖D - D'‖
      ≤ ((1 + s) / (1 - s) + s * ((1 + s) / (1 - s)) ^ 2)
        * ‖(1 - s) • (D * ∑' k : ℕ, (s • D) ^ k)
            - (1 - s) • (D' * ∑' k : ℕ, (s • D') ^ k)‖
    ∧ (1 + (1 / 3 : ℝ)) / (1 - 1 / 3)
        + (1 / 3) * ((1 + (1 / 3 : ℝ)) / (1 - 1 / 3)) ^ 2
      = 10 / 3 := by
  have hc0 : (0 : ℝ) < 1 - s := by linarith
  -- Neumann data for one contraction
  have key : ∀ X : A, ‖X‖ ≤ 1 →
      ‖s • X‖ < 1
      ∧ (1 - s • X) * (∑' k : ℕ, (s • X) ^ k) = 1
      ∧ (∑' k : ℕ, (s • X) ^ k) * (1 - s • X) = 1
      ∧ ‖(1 - s) • (X * ∑' k : ℕ, (s • X) ^ k)‖ ≤ 1 := by
    intro X hX
    have hnorm : ‖s • X‖ < 1 := by
      rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg hs0]
      calc s * ‖X‖ ≤ s * 1 := mul_le_mul_of_nonneg_left hX hs0
        _ = s := mul_one s
        _ < 1 := hs1
    have h1 : (1 - s • X) * (∑' k : ℕ, (s • X) ^ k) = 1 :=
      mul_neg_geom_series _ hnorm
    have h2 : (∑' k : ℕ, (s • X) ^ k) * (1 - s • X) = 1 :=
      geom_series_mul_neg _ hnorm
    refine ⟨hnorm, h1, h2, ?_⟩
    -- `‖A_s‖ ≤ 1` from the geometric bound on the resolvent
    have hR : ‖∑' k : ℕ, (s • X) ^ k‖ ≤ (1 - ‖s • X‖)⁻¹ := by
      have h := tsum_geometric_le_of_norm_lt_one (s • X) hnorm
      simpa [norm_one] using h
    have hRnn : (0 : ℝ) < 1 - ‖s • X‖ := by
      linarith [hnorm]
    calc ‖(1 - s) • (X * ∑' k : ℕ, (s • X) ^ k)‖
        = (1 - s) * ‖X * ∑' k : ℕ, (s • X) ^ k‖ := by
          rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg hc0.le]
      _ ≤ (1 - s) * (‖X‖ * ‖∑' k : ℕ, (s • X) ^ k‖) :=
          mul_le_mul_of_nonneg_left (norm_mul_le _ _) hc0.le
      _ ≤ (1 - s) * (1 * (1 - ‖s • X‖)⁻¹) := by
          refine mul_le_mul_of_nonneg_left ?_ hc0.le
          exact mul_le_mul hX hR (norm_nonneg _) zero_le_one
      _ = (1 - s) / (1 - ‖s • X‖) := by
          rw [one_mul, div_eq_mul_inv]
      _ ≤ 1 := by
          rw [div_le_one hRnn]
          have hsX : ‖s • X‖ ≤ s := by
            rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg hs0]
            calc s * ‖X‖ ≤ s * 1 :=
                  mul_le_mul_of_nonneg_left hX hs0
              _ = s := mul_one s
          linarith
  obtain ⟨hn, h1, h2, hA1⟩ := key D hD
  obtain ⟨hn', h1', h2', hA1'⟩ := key D' hD'
  set R : A := ∑' k : ℕ, (s • D) ^ k with hR
  set R' : A := ∑' k : ℕ, (s • D') ^ k with hR'
  set Aa : A := (1 - s) • (D * R) with hAa
  set At : A := (1 - s) • (D' * R') with hAt
  have hcne : (1 - s) ≠ 0 := ne_of_gt hc0
  -- resolvent identities `c•1 + s•A = c•R`
  have hresid : ∀ (X Rx : A),
      (1 - s • X) * Rx = 1 →
      (1 - s) • (1 : A) + s • ((1 - s) • (X * Rx))
        = (1 - s) • Rx := by
    intro X Rx hx
    have hexp : Rx = 1 + s • (X * Rx) := by
      have h := hx
      rw [sub_mul, one_mul, smul_mul_assoc] at h
      rw [← h]
      abel
    calc (1 - s) • (1 : A) + s • ((1 - s) • (X * Rx))
        = (1 - s) • (1 + s • (X * Rx)) := by
          rw [smul_add, smul_smul, smul_smul, mul_comm]
      _ = (1 - s) • Rx := by rw [← hexp]
  have hresD := hresid D R h1
  have hresD' := hresid D' R' h1'
  -- instantiate the proved two-inverse Lipschitz assembly
  have hmain := completion_aggregate_stability
    (A := A) D D' Aa At
    ((1 - s)⁻¹ • (1 - s • D)) ((1 - s)⁻¹ • (1 - s • D'))
    ((1 - s) • (1 : A) + s • Aa) ((1 - s) • (1 : A) + s • At)
    s ((1 + s) / (1 - s)) hs0
    (by positivity)
    (by -- `D = A_s · (cI+sA_s)⁻¹`
      rw [hAa, smul_mul_assoc, mul_smul_comm, smul_smul,
        mul_inv_cancel₀ hcne, one_smul, mul_assoc, h2, mul_one])
    (by
      rw [hAt, smul_mul_assoc, mul_smul_comm, smul_smul,
        mul_inv_cancel₀ hcne, one_smul, mul_assoc, h2', mul_one])
    (by -- `(cI+sA)·c⁻¹(1-sD) = 1`
      rw [hresD, smul_mul_assoc, mul_smul_comm, smul_smul,
        mul_inv_cancel₀ hcne, one_smul, h2])
    (by
      rw [hresD', mul_smul_comm, smul_mul_assoc, smul_smul,
        mul_inv_cancel₀ hcne, one_smul, h1'])
    (by -- `R̃_A - R_A = s(Ã - A)`
      rw [add_sub_add_left_eq_sub, ← smul_sub])
    (by -- `‖c⁻¹(1-sD)‖ ≤ (1+s)/c`
      rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg
        (inv_nonneg.mpr hc0.le), div_eq_inv_mul]
      refine mul_le_mul_of_nonneg_left ?_
        (inv_nonneg.mpr hc0.le)
      calc ‖(1 : A) - s • D‖ ≤ ‖(1 : A)‖ + ‖s • D‖ :=
            norm_sub_le _ _
        _ ≤ 1 + s := by
            rw [norm_one]
            have : ‖s • D‖ ≤ s := by
              rw [norm_smul, Real.norm_eq_abs,
                abs_of_nonneg hs0]
              calc s * ‖D‖ ≤ s * 1 :=
                    mul_le_mul_of_nonneg_left hD hs0
                _ = s := mul_one s
            linarith)
    (by
      rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg
        (inv_nonneg.mpr hc0.le), div_eq_inv_mul]
      refine mul_le_mul_of_nonneg_left ?_
        (inv_nonneg.mpr hc0.le)
      calc ‖(1 : A) - s • D'‖ ≤ ‖(1 : A)‖ + ‖s • D'‖ :=
            norm_sub_le _ _
        _ ≤ 1 + s := by
            rw [norm_one]
            have : ‖s • D'‖ ≤ s := by
              rw [norm_smul, Real.norm_eq_abs,
                abs_of_nonneg hs0]
              calc s * ‖D'‖ ≤ s * 1 :=
                    mul_le_mul_of_nonneg_left hD' hs0
                _ = s := mul_one s
            linarith)
    hA1'
  refine ⟨?_, by norm_num⟩
  calc ‖D - D'‖
      ≤ ((1 + s) / (1 - s) + s * ((1 + s) / (1 - s)) ^ 2)
        * ‖Aa - At‖ := hmain.1
    _ = ((1 + s) / (1 - s) + s * ((1 + s) / (1 - s)) ^ 2)
        * ‖(1 - s) • (D * ∑' k : ℕ, (s • D) ^ k)
            - (1 - s) • (D' * ∑' k : ℕ, (s • D') ^ k)‖ := by
        rw [hAa, hAt, hR, hR']

end NCG
