import NCG.Grand.CompactResolventStrongCofinalMarkedRenewalLimitExact

open NCG.CompactResolventSpectralProjectionContractionExact
open NCG.CompactResolventSpectralProjectionTransferExact
open NCG.CompactResolventStrongCofinalMarkedRenewalLimitExact

#print axioms norm_diracSpectralScreen_apply_le
#print axioms tendsto_diracSpectralScreen_apply_of_tendsto
#print axioms tendsto_finiteSpectralCompression_apply
#print axioms tendsto_finiteSpectralCompression_matrixCoefficient
#print axioms tendsto_product_finiteSpectralCompressions_apply
#print axioms tendsto_finiteSpectralCompression_multiplicativityDefect_apply
#print axioms every_compactResolventSpectralTriple_is_strongCofinalMarkedRenewalLimit
