/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.GrandOneRouting

/-!
# Conservative resolved-grading process extensions

This file supplies the process-level countermodel required by
`cth:SM-bare-universal-no-go`.  An arbitrary finite old letter process is
embedded by `A ↦ A ⊗ I₂`.  Every old word is preserved exactly after normalized
discard of the resolved grading.  The same embedded process admits both an
even extension generated by `Z` and an odd extension generated by `X`; the
latter has a nonzero left-to-right block while the former commutes with the
grading on every letter.
-/

open Matrix Kronecker

namespace NCG

/-- Embed an old process coefficient without changing the resolved grading. -/
def resolvedGradingEmbed {h : Type*} [Fintype h] [DecidableEq h]
    (A : Matrix h h ℂ) : Matrix (h × Fin 2) (h × Fin 2) ℂ :=
  A ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)

/-- Discard the resolved grading against its normalized trace. -/
noncomputable def discardResolvedGrading {h : Type*}
    (M : Matrix (h × Fin 2) (h × Fin 2) ℂ) : Matrix h h ℂ :=
  fun i j => (M (i, 0) (j, 0) + M (i, 1) (j, 1)) / 2

/-- Normalized grading discard is a left inverse to the conservative
embedding. -/
theorem discardResolvedGrading_embed {h : Type*} [Fintype h]
    [DecidableEq h] (A : Matrix h h ℂ) :
    discardResolvedGrading (resolvedGradingEmbed A) = A := by
  ext i j
  simp [discardResolvedGrading, resolvedGradingEmbed,
    Matrix.kroneckerMap_apply]

/-- The represented coefficient of an old word. -/
def representedWord {h ι : Type*} [Fintype h] [DecidableEq h]
    (K : ι → Matrix h h ℂ)
    (w : List ι) : Matrix h h ℂ :=
  (w.map K).prod

/-- Embedding commutes with every finite serial word. -/
theorem resolvedGradingEmbed_word {h ι : Type*} [Fintype h]
    [DecidableEq h] (K : ι → Matrix h h ℂ) (w : List ι) :
    (w.map (fun a => resolvedGradingEmbed (K a))).prod =
      resolvedGradingEmbed (representedWord K w) := by
  induction w with
  | nil =>
      simp [representedWord, resolvedGradingEmbed]
  | cons a w ih =>
      simp only [List.map_cons, List.prod_cons, representedWord]
      rw [ih]
      change
        (K a ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)) *
            ((w.map K).prod ⊗ₖ (1 : Matrix (Fin 2) (Fin 2) ℂ)) =
          (K a * (w.map K).prod) ⊗ₖ
            (1 : Matrix (Fin 2) (Fin 2) ℂ)
      rw [← Matrix.mul_kronecker_mul, Matrix.one_mul]

/-- Every old word is recovered exactly after forgetting the newly resolved
grading record. -/
theorem conservativeResolvedGrading_word {h ι : Type*} [Fintype h]
    [DecidableEq h] (K : ι → Matrix h h ℂ) (w : List ι) :
    discardResolvedGrading
        ((w.map (fun a => resolvedGradingEmbed (K a))).prod) =
      representedWord K w := by
  rw [resolvedGradingEmbed_word, discardResolvedGrading_embed]

/-- Left and right projections of the resolved two-state grading. -/
def resolvedLeftProjection : Matrix (Fin 2) (Fin 2) ℂ :=
  Matrix.single 0 0 1

def resolvedRightProjection : Matrix (Fin 2) (Fin 2) ℂ :=
  Matrix.single 1 1 1

/-- The zero-occurrence extension: old letters are conservative and the only
new protected letter is the diagonal grading read. -/
def gradingEvenProcessExtension {h ι : Type*} [Fintype h]
    [DecidableEq h] (K : ι → Matrix h h ℂ) :
    ι ⊕ Unit → Matrix (h × Fin 2) (h × Fin 2) ℂ
  | Sum.inl a => resolvedGradingEmbed (K a)
  | Sum.inr _ => (1 : Matrix h h ℂ) ⊗ₖ clockZ

/-- The nonzero-occurrence extension of the same old process, obtained by
adjoining the physical grading flip. -/
def gradingOddProcessExtension {h ι : Type*} [Fintype h]
    [DecidableEq h] (K : ι → Matrix h h ℂ) :
    ι ⊕ Unit → Matrix (h × Fin 2) (h × Fin 2) ℂ
  | Sum.inl a => resolvedGradingEmbed (K a)
  | Sum.inr _ => (1 : Matrix h h ℂ) ⊗ₖ clockX

/-- Every coefficient in the even extension commutes with the resolved
grading. -/
theorem gradingEvenProcessExtension_commutes {h ι : Type*} [Fintype h]
    [DecidableEq h] (K : ι → Matrix h h ℂ) (a : ι ⊕ Unit) :
    gradingEvenProcessExtension K a *
        ((1 : Matrix h h ℂ) ⊗ₖ clockZ) =
      ((1 : Matrix h h ℂ) ⊗ₖ clockZ) *
        gradingEvenProcessExtension K a := by
  cases a with
  | inl a =>
      simp only [gradingEvenProcessExtension, resolvedGradingEmbed]
      rw [← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
        Matrix.mul_one, Matrix.one_mul, Matrix.one_mul, Matrix.mul_one]
  | inr u =>
      simp [gradingEvenProcessExtension]

/-- The new odd letter has a genuinely nonzero left-to-right block. -/
theorem gradingOddProcessExtension_crossBlock_ne_zero
    {h ι : Type*} [Fintype h] [DecidableEq h] [Nonempty h]
    (K : ι → Matrix h h ℂ) :
    ((1 : Matrix h h ℂ) ⊗ₖ resolvedLeftProjection) *
          gradingOddProcessExtension K (Sum.inr ()) *
          ((1 : Matrix h h ℂ) ⊗ₖ resolvedRightProjection) ≠ 0 := by
  rw [gradingOddProcessExtension,
    ← Matrix.mul_kronecker_mul, ← Matrix.mul_kronecker_mul,
    Matrix.one_mul, Matrix.one_mul]
  obtain ⟨i⟩ := (inferInstance : Nonempty h)
  intro hzero
  have hij := congrFun (congrFun hzero (i, 0)) (i, 1)
  simp [resolvedLeftProjection, resolvedRightProjection, clockX,
    Matrix.kroneckerMap_apply] at hij

/-- `cth:SM-bare-universal-no-go`, exact process-level wrapper.  The same old
operational word tensor embeds conservatively into a wholly grading-even
extension and into an extension with a nonzero grading-changing route. -/
theorem bareOperationalTensor_has_even_and_odd_conservativeExtensions
    {h ι : Type*} [Fintype h] [DecidableEq h] [Nonempty h]
    (K : ι → Matrix h h ℂ) :
    (∀ w : List ι,
      discardResolvedGrading
          ((w.map (fun a => gradingEvenProcessExtension K (Sum.inl a))).prod) =
        representedWord K w) ∧
    (∀ w : List ι,
      discardResolvedGrading
          ((w.map (fun a => gradingOddProcessExtension K (Sum.inl a))).prod) =
        representedWord K w) ∧
    (∀ a, gradingEvenProcessExtension K a *
          ((1 : Matrix h h ℂ) ⊗ₖ clockZ) =
        ((1 : Matrix h h ℂ) ⊗ₖ clockZ) *
          gradingEvenProcessExtension K a) ∧
    ((1 : Matrix h h ℂ) ⊗ₖ resolvedLeftProjection) *
          gradingOddProcessExtension K (Sum.inr ()) *
          ((1 : Matrix h h ℂ) ⊗ₖ resolvedRightProjection) ≠ 0 := by
  refine ⟨?_, ?_, gradingEvenProcessExtension_commutes K,
    gradingOddProcessExtension_crossBlock_ne_zero K⟩
  · intro w
    simpa [gradingEvenProcessExtension] using
      conservativeResolvedGrading_word K w
  · intro w
    simpa [gradingOddProcessExtension] using
      conservativeResolvedGrading_word K w

end NCG
