import NCG.Grand.FiniteTorusFourierInterpolationProjection
import NCG.Grand.IntegerFourierBox

/-!
# Fixed Fourier screens on continuum torus `L²`

The changing finite-torus interpolation projection is not itself a fixed
screen.  For the common-screen argument we instead project onto the span of
the continuum Fourier basis vectors in one integer box.  This file constructs
that orthogonal projection and records the range, idempotence, contraction,
and basis-fixing facts used by resolvent convergence.
-/

noncomputable section

local instance continuumTorusFourierScreen_measureSpace :
    MeasureTheory.MeasureSpace UnitAddCircle :=
  ⟨AddCircle.haarAddCircle⟩
local instance continuumTorusFourierScreen_isAddHaarMeasure :
    MeasureTheory.Measure.IsAddHaarMeasure
    (MeasureTheory.volume : MeasureTheory.Measure UnitAddCircle) :=
  inferInstanceAs (MeasureTheory.Measure.IsAddHaarMeasure AddCircle.haarAddCircle)
local instance continuumTorusFourierScreen_isProbabilityMeasure :
    MeasureTheory.IsProbabilityMeasure
    (MeasureTheory.volume : MeasureTheory.Measure UnitAddCircle) :=
  inferInstanceAs (MeasureTheory.IsProbabilityMeasure AddCircle.haarAddCircle)

namespace NCG

variable {d : Type*} [Fintype d] [DecidableEq d]

abbrev ContinuumTorusL2 (d : Type*) [Fintype d] :=
  MeasureTheory.Lp ℂ 2
    (MeasureTheory.volume : MeasureTheory.Measure (UnitAddTorus d))

/-- The Fourier-basis embedding into continuum torus `L²`. -/
def continuumTorusFourierBasisEmbedding :
    (d → ℤ) ↪ ContinuumTorusL2 d where
  toFun := fun k ↦ UnitAddTorus.mFourierBasis k
  inj' := by
    intro k l h
    apply UnitAddTorus.orthonormal_mFourier.linearIndependent.injective
    simpa only [UnitAddTorus.coe_mFourierBasis] using h

/-- The finite set of Fourier basis vectors indexed by the integer box. -/
def continuumTorusFourierBoxModes (R : ℕ) :
    Finset (ContinuumTorusL2 d) :=
  (integerFourierBox d R).map
    (continuumTorusFourierBasisEmbedding (d := d))

/-- The finite-dimensional continuum Fourier subspace generated by the modes
in the integer box of radius `R`. -/
def continuumTorusFourierBoxSubspace (R : ℕ) :
    Submodule ℂ (ContinuumTorusL2 d) :=
  Submodule.span ℂ (continuumTorusFourierBoxModes (d := d) R :
    Set (ContinuumTorusL2 d))

local instance continuumTorusFourierBoxSubspace_finiteDimensional (R : ℕ) :
    FiniteDimensional ℂ (continuumTorusFourierBoxSubspace (d := d) R) := by
  rw [continuumTorusFourierBoxSubspace]
  infer_instance

local instance continuumTorusFourierBoxSubspace_complete (R : ℕ) :
    CompleteSpace (continuumTorusFourierBoxSubspace (d := d) R) :=
  FiniteDimensional.complete ℂ _

/-- Orthogonal projection onto the fixed continuum Fourier box. -/
def continuumTorusFourierScreen (R : ℕ) :
    ContinuumTorusL2 d →L[ℂ] ContinuumTorusL2 d :=
  (continuumTorusFourierBoxSubspace (d := d) R).starProjection

theorem continuumTorusFourierScreen_range (R : ℕ) :
    (continuumTorusFourierScreen (d := d) R).range =
      continuumTorusFourierBoxSubspace (d := d) R := by
  exact Submodule.range_starProjection _

theorem continuumTorusFourierScreen_idempotent (R : ℕ) :
    (continuumTorusFourierScreen (d := d) R).comp
        (continuumTorusFourierScreen (d := d) R) =
      continuumTorusFourierScreen (d := d) R := by
  exact (continuumTorusFourierBoxSubspace (d := d) R)
    |>.isIdempotentElem_starProjection.eq

/-- A fixed continuum Fourier screen is self-adjoint. -/
theorem continuumTorusFourierScreen_adjoint (R : ℕ) :
    (continuumTorusFourierScreen (d := d) R).adjoint =
      continuumTorusFourierScreen (d := d) R := by
  symm
  apply (ContinuousLinearMap.eq_adjoint_iff
    (continuumTorusFourierScreen (d := d) R)
    (continuumTorusFourierScreen (d := d) R)).2
  intro x y
  exact (continuumTorusFourierBoxSubspace (d := d) R)
    |>.inner_starProjection_left_eq_right x y

theorem continuumTorusFourierScreen_opNorm_le_one (R : ℕ) :
    ‖continuumTorusFourierScreen (d := d) R‖ ≤ 1 := by
  exact (continuumTorusFourierBoxSubspace (d := d) R).starProjection_norm_le

theorem continuumTorusFourierScreen_norm_apply_le (R : ℕ)
    (f : ContinuumTorusL2 d) :
    ‖continuumTorusFourierScreen (d := d) R f‖ ≤ ‖f‖ := by
  exact (continuumTorusFourierBoxSubspace (d := d) R)
    |>.norm_starProjection_apply_le f

theorem mFourierBasis_mem_continuumTorusFourierBoxSubspace
    (R : ℕ) (k : d → ℤ) (hk : k ∈ integerFourierBox d R) :
    UnitAddTorus.mFourierBasis k ∈
      continuumTorusFourierBoxSubspace (d := d) R := by
  apply Submodule.subset_span
  exact Finset.mem_map.mpr
    ⟨k, hk, by simp only [continuumTorusFourierBasisEmbedding,
      Function.Embedding.coeFn_mk, UnitAddTorus.coe_mFourierBasis]⟩

/-- The fixed screen acts as the identity on every Fourier mode in its box. -/
@[simp]
theorem continuumTorusFourierScreen_apply_mFourierBasis_of_mem
    (R : ℕ) (k : d → ℤ) (hk : k ∈ integerFourierBox d R) :
    continuumTorusFourierScreen (d := d) R
        (UnitAddTorus.mFourierBasis k) =
      UnitAddTorus.mFourierBasis k := by
  exact Submodule.starProjection_eq_self_iff.mpr
    (mFourierBasis_mem_continuumTorusFourierBoxSubspace R k hk)

/-- Fourier-box subspaces increase with the radius. -/
theorem continuumTorusFourierBoxSubspace_mono
    {R S : ℕ} (hRS : R ≤ S) :
    continuumTorusFourierBoxSubspace (d := d) R ≤
      continuumTorusFourierBoxSubspace (d := d) S := by
  apply Submodule.span_mono
  intro f hf
  obtain ⟨k, hk, rfl⟩ := Finset.mem_map.mp hf
  exact Finset.mem_map.mpr
    ⟨k, integerFourierBox_mono hRS hk, rfl⟩

end NCG
