/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.ExponentialDifferenceQuotient
import NCG.Grand.FiniteFamilyUniformConvergence
import NCG.Grand.PulseHoweComparison

/-!
# Convergence of covariant Fourier symbols

For a fixed integer mode `k`, the scaled finite-mesh multiplier

`h⁻¹ (exp(2π i h k) 1 - exp(-h B))`

converges in Banach-algebra norm to the continuum covariant symbol
`2π i k 1 + B`.  The result is then uniformized on arbitrary fixed finite
sets of modes and propagated to the positive symbols `D†D`.
-/

open Filter NormedSpace Set Topology

namespace NCG

variable {A : Type} [NormedRing A] [NormOneClass A]
  [NormedAlgebra ℝ A] [NormedAlgebra ℂ A] [CompleteSpace A]
  [IsScalarTower ℝ ℂ A]

/-- The exponential of a complex scalar multiple of the algebra identity is
the corresponding complex scalar exponential times the identity. -/
theorem exp_complex_smul_one (z : ℂ) :
    NormedSpace.exp (z • (1 : A)) = Complex.exp z • (1 : A) := by
  let _ : NormedAlgebra ℚ A := .restrictScalars ℚ ℂ A
  calc
    NormedSpace.exp (z • (1 : A)) =
        NormedSpace.exp (algebraMap ℂ A z) := by
      rw [Algebra.smul_def, mul_one]
    _ = algebraMap ℂ A (NormedSpace.exp z) :=
      (NormedSpace.map_exp (algebraMap ℂ A)
        (continuous_algebraMap ℂ A) z).symm
    _ = Complex.exp z • (1 : A) := by
      rw [← Complex.exp_eq_exp_ℂ, Algebra.smul_def, mul_one]

/-- The infinitesimal Fourier phase generator at integer mode `k`. -/
noncomputable def covariantFourierPhaseGenerator (k : ℤ) : A :=
  (Complex.I * ((2 * Real.pi * (k : ℝ) : ℝ) : ℂ)) • (1 : A)

/-- Continuum multiplier of the covariant derivative at integer mode `k`. -/
noncomputable def continuumCovariantFourierSymbol (k : ℤ) (B : A) : A :=
  covariantFourierPhaseGenerator k + B

/-- Finite-mesh multiplier written intrinsically as the quotient of the two
Banach-algebra exponential curves generated by the Fourier phase and the
negative connection. -/
noncomputable def meshCovariantFourierSymbol (h : ℝ) (k : ℤ) (B : A) : A :=
  (h⁻¹ : ℝ) •
    (NormedSpace.exp (h • covariantFourierPhaseGenerator k) -
      NormedSpace.exp (h • (-B)))

/-- The finite-mesh covariant symbol converges in norm at every fixed integer
Fourier mode. -/
theorem meshCovariantFourierSymbol_norm_sub_tendsto_right
    (k : ℤ) (B : A) :
    Tendsto
      (fun h : ℝ =>
        ‖meshCovariantFourierSymbol h k B -
          continuumCovariantFourierSymbol k B‖)
      (nhdsWithin 0 (Ioi 0)) (𝓝 0) := by
  simpa only [meshCovariantFourierSymbol,
      continuumCovariantFourierSymbol, sub_neg_eq_add]
    using exponentialDifferenceQuotient_tendsto_right
      (covariantFourierPhaseGenerator k) (-B)

/-- Fixed-mode convergence of the covariant symbol itself. -/
theorem meshCovariantFourierSymbol_tendsto_right
    (k : ℤ) (B : A) :
    Tendsto (fun h : ℝ => meshCovariantFourierSymbol h k B)
      (nhdsWithin 0 (Ioi 0))
      (𝓝 (continuumCovariantFourierSymbol k B)) :=
  tendsto_iff_norm_sub_tendsto_zero.mpr
    (meshCovariantFourierSymbol_norm_sub_tendsto_right k B)

/-- Under the standard compatibility between real and complex scalar
actions, the intrinsic two-generator quotient is exactly the familiar
finite-torus multiplier `h⁻¹(exp(2πihk)1-exp(-hB))`. -/
theorem meshCovariantFourierSymbol_eq_explicit
    (h : ℝ) (k : ℤ) (B : A)
    (hreal : ∀ (r : ℝ) (x : A), r • x = (r : ℂ) • x) :
    meshCovariantFourierSymbol h k B =
      (h⁻¹ : ℂ) •
        ((Complex.exp (Complex.I *
            ((2 * Real.pi * h * (k : ℝ) : ℝ) : ℂ))) • (1 : A) -
          NormedSpace.exp (((-h : ℝ) : ℂ) • B)) := by
  calc
    meshCovariantFourierSymbol h k B =
        (h⁻¹ : ℂ) •
          (NormedSpace.exp
              ((h : ℂ) • covariantFourierPhaseGenerator k) -
            NormedSpace.exp ((h : ℂ) • (-B))) := by
      rw [meshCovariantFourierSymbol,
        hreal (h⁻¹) _, hreal h (covariantFourierPhaseGenerator k),
        hreal h (-B)]
      push_cast
      rfl
    _ = _ := by
      congr 2
      · rw [show (h : ℂ) • covariantFourierPhaseGenerator k =
            (Complex.I *
              ((2 * Real.pi * h * (k : ℝ) : ℝ) : ℂ)) • (1 : A) by
          rw [covariantFourierPhaseGenerator, smul_smul]
          congr 1
          push_cast
          ring]
        exact exp_complex_smul_one _
      · congr 1
        rw [smul_neg, ← neg_smul]
        congr 1
        push_cast
        rfl

/-- Fixed-mode convergence is uniform on every fixed finite Fourier box. -/
theorem meshCovariantFourierSymbol_tendstoUniformlyOn_finset
    (s : Finset ℤ) (B : A) :
    TendstoUniformlyOn
      (fun h k => meshCovariantFourierSymbol h k B)
      (fun k => continuumCovariantFourierSymbol k B)
      (nhdsWithin 0 (Ioi 0)) (s : Set ℤ) :=
  tendstoUniformlyOn_finset_of_tendsto s fun k _ =>
    meshCovariantFourierSymbol_tendsto_right k B

section PositiveSymbol

variable [StarRing A] [NormedStarGroup A]

/-- Positive finite-mesh symbol `D†D` at mode `k`. -/
noncomputable def meshCovariantPositiveSymbol (h : ℝ) (k : ℤ) (B : A) : A :=
  star (meshCovariantFourierSymbol h k B) *
    meshCovariantFourierSymbol h k B

/-- Positive continuum symbol `D†D` at mode `k`. -/
noncomputable def continuumCovariantPositiveSymbol (k : ℤ) (B : A) : A :=
  star (continuumCovariantFourierSymbol k B) *
    continuumCovariantFourierSymbol k B

/-- The positive covariant symbol converges at every fixed mode. -/
theorem meshCovariantPositiveSymbol_tendsto_right
    (k : ℤ) (B : A) :
    Tendsto (fun h : ℝ => meshCovariantPositiveSymbol h k B)
      (nhdsWithin 0 (Ioi 0))
      (𝓝 (continuumCovariantPositiveSymbol k B)) := by
  have hD := meshCovariantFourierSymbol_tendsto_right k B
  simpa only [meshCovariantPositiveSymbol,
    continuumCovariantPositiveSymbol] using hD.star.mul hD

/-- Positive-symbol convergence is uniform on every fixed finite box. -/
theorem meshCovariantPositiveSymbol_tendstoUniformlyOn_finset
    (s : Finset ℤ) (B : A) :
    TendstoUniformlyOn
      (fun h k => meshCovariantPositiveSymbol h k B)
      (fun k => continuumCovariantPositiveSymbol k B)
      (nhdsWithin 0 (Ioi 0)) (s : Set ℤ) :=
  tendstoUniformlyOn_finset_of_tendsto s fun k _ =>
    meshCovariantPositiveSymbol_tendsto_right k B

end PositiveSymbol

end NCG
