/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal
import Mathlib.Analysis.Normed.Operator.Extend

/-!
# C-star completion of a normed pre-C-star algebra

Mathlib equips `UniformSpace.Completion A` with its ring, algebra, and normed-space
structures, but it does not currently transport a star operation or the C-star identity.
This file supplies that missing bridge for a (not necessarily complete) normed complex
star algebra satisfying the C-star identity.

The second half packages a bounded state on the dense pre-C-star algebra and proves that
it extends uniquely and isometrically to a positive unital functional on the completion.
Consequently Mathlib's GNS construction applies directly to the completed algebra.

This machinery is intended for algebraic AF/direct limits: after the algebraic limit is
given its compatible C-star norm, its quasilocal C-star algebra is simply its uniform
completion, and compatible finite-stage states extend without any additional analytic
assumption.
-/

open scoped ComplexOrder

noncomputable section

namespace UniformSpace.Completion

variable {A : Type*}

section Star

variable [NormedRing A] [StarRing A] [CStarRing A]

/-- The star operation on a completion, obtained by extending the isometric star map. -/
def completionStar (x : Completion A) : Completion A :=
  Completion.map (star : A → A) x

noncomputable instance instStar : Star (Completion A) :=
  ⟨completionStar⟩

@[simp, norm_cast]
theorem coe_star (a : A) :
    star (a : Completion A) = (star a : A) := by
  exact Completion.map_coe star_isometry.uniformContinuous a

noncomputable instance instContinuousStar : ContinuousStar (Completion A) where
  continuous_star := Completion.continuous_map

noncomputable instance instStarRing : StarRing (Completion A) where
  star_involutive x := by
    induction x using Completion.induction_on with
    | hp => apply isClosed_eq <;> fun_prop
    | ih a => simp
  star_add x y := by
    induction x, y using Completion.induction_on₂ with
    | hp => apply isClosed_eq <;> fun_prop
    | ih a b => simp only [← Completion.coe_add, coe_star, star_add]
  star_mul x y := by
    induction x, y using Completion.induction_on₂ with
    | hp => apply isClosed_eq <;> fun_prop
    | ih a b => simp only [← Completion.coe_mul, coe_star, star_mul]

noncomputable instance instCStarRing : CStarRing (Completion A) where
  norm_mul_self_le x := by
    induction x using Completion.induction_on with
    | hp => apply isClosed_le <;> fun_prop
    | ih a =>
        simpa only [coe_star, ← Completion.coe_mul, Completion.norm_coe]
          using CStarRing.norm_mul_self_le (x := a)

end Star

section Complex

variable [NormedRing A] [StarRing A] [CStarRing A]
  [NormedAlgebra ℂ A] [StarModule ℂ A]

/- Mathlib's current completion instance for `NormedAlgebra` assumes that the
underlying algebra is commutative.  Scalar multiplication is nevertheless
bounded for arbitrary normed complex algebras, so we install the general
instance needed here. -/
noncomputable instance instNormedAlgebraOfPreCStar :
    NormedAlgebra ℂ (Completion A) where
  norm_smul_le := norm_smul_le

noncomputable instance instStarModule : StarModule ℂ (Completion A) where
  star_smul r x := by
    refine Completion.induction_on x
      (isClosed_eq
        (continuous_star.comp (continuous_const_smul r))
        ((continuous_const_smul (star r)).comp continuous_star)) ?_
    intro a
    simp only [← Completion.coe_smul, coe_star, star_smul]

/-- The uniform completion of a normed complex pre-C-star algebra is a C-star algebra. -/
noncomputable instance instCStarAlgebra : CStarAlgebra (Completion A) where
  toNormedRing := inferInstance
  toStarRing := inferInstance
  toCompleteSpace := inferInstance
  toCStarRing := inferInstance
  toNormedAlgebra := inferInstance
  toStarModule := inferInstance

/-- The canonical spectral order on the completed C-star algebra. -/
noncomputable instance instPartialOrder : PartialOrder (Completion A) :=
  CStarAlgebra.spectralOrder _

/-- The canonical spectral order is the order generated by star squares. -/
noncomputable instance instStarOrderedRing : StarOrderedRing (Completion A) :=
  CStarAlgebra.spectralOrderedRing _

end Complex

end UniformSpace.Completion

namespace NCG

open UniformSpace UniformSpace.Completion

variable {A : Type*} [NormedRing A] [StarRing A] [CStarRing A]
  [NormedAlgebra ℂ A] [StarModule ℂ A]

/-- A state on a possibly incomplete normed pre-C-star algebra.

Continuity is included explicitly: unlike on a complete C-star algebra, automatic
continuity of positive maps is not presently available in Mathlib at this generality. -/
structure PreCStarState (A : Type*) [NormedRing A] [StarRing A]
    [CStarRing A] [NormedAlgebra ℂ A] [StarModule ℂ A] where
  toContinuousLinearMap : A →L[ℂ] ℂ
  map_one : toContinuousLinearMap 1 = 1
  map_star_mul_self_nonneg : ∀ a : A, 0 ≤ toContinuousLinearMap (star a * a)
  norm_eq_one : ‖toContinuousLinearMap‖ = 1

namespace PreCStarState

instance : CoeFun (PreCStarState A) fun _ => A → ℂ :=
  ⟨fun ω => ω.toContinuousLinearMap⟩

@[simp]
theorem apply_one (ω : PreCStarState A) : ω 1 = 1 :=
  ω.map_one

/-- The unique continuous extension of a pre-C-star state to the completion. -/
def completionCLM (ω : PreCStarState A) : Completion A →L[ℂ] ℂ :=
  ω.toContinuousLinearMap.extend (Completion.toComplL : A →L[ℂ] Completion A)

@[simp]
theorem completionCLM_coe (ω : PreCStarState A) (a : A) :
    ω.completionCLM (a : Completion A) = ω a := by
  exact ContinuousLinearMap.extend_eq _ Completion.denseRange_coe
    Completion.coe_isometry.isUniformInducing a

/-- The extension is the only continuous functional with the prescribed dense values. -/
theorem completionCLM_unique (ω : PreCStarState A)
    (φ : Completion A →L[ℂ] ℂ)
    (hφ : ∀ a : A, φ (a : Completion A) = ω a) :
    φ = ω.completionCLM := by
  apply ContinuousLinearMap.coeFn_injective
  apply Completion.ext φ.continuous ω.completionCLM.continuous
  intro a
  rw [completionCLM_coe]
  exact hφ a

/-- Dense extension preserves the exact operator norm. -/
theorem norm_completionCLM (ω : PreCStarState A) :
    ‖ω.completionCLM‖ = ‖ω.toContinuousLinearMap‖ := by
  apply le_antisymm
  · apply ω.completionCLM.opNorm_le_bound (norm_nonneg _)
    intro x
    refine Completion.induction_on x
      (isClosed_le ω.completionCLM.continuous.norm
        (continuous_const.mul continuous_norm)) ?_
    intro a
    rw [completionCLM_coe]
    simpa only [Completion.norm_coe] using
      ω.toContinuousLinearMap.le_opNorm a
  · apply ω.toContinuousLinearMap.opNorm_le_bound (norm_nonneg _)
    intro a
    rw [← completionCLM_coe ω a]
    simpa using ω.completionCLM.le_opNorm (a : Completion A)

@[simp]
theorem norm_completionCLM_eq_one (ω : PreCStarState A) :
    ‖ω.completionCLM‖ = 1 := by
  rw [norm_completionCLM, ω.norm_eq_one]

@[simp]
theorem completionCLM_one (ω : PreCStarState A) :
    ω.completionCLM 1 = 1 := by
  rw [← Completion.coe_one A, completionCLM_coe, ω.map_one]

/-- Positivity on star squares passes from the dense algebra to every element of its
completion. -/
theorem completionCLM_star_mul_self_nonneg (ω : PreCStarState A)
    (x : Completion A) : 0 ≤ ω.completionCLM (star x * x) := by
  induction x using Completion.induction_on with
  | hp => apply isClosed_le <;> fun_prop
  | ih a =>
      simpa only [UniformSpace.Completion.coe_star, ← Completion.coe_mul,
        completionCLM_coe] using ω.map_star_mul_self_nonneg a

/-- The completed functional as a genuine Mathlib positive linear map. -/
def completionPositiveLinearMap (ω : PreCStarState A) :
    Completion A →ₚ[ℂ] ℂ :=
  PositiveLinearMap.mk₀ ω.completionCLM.toLinearMap fun x hx => by
    rw [StarOrderedRing.nonneg_iff] at hx
    induction hx using AddSubmonoid.closure_induction with
    | mem y hy =>
        obtain ⟨a, rfl⟩ := hy
        exact ω.completionCLM_star_mul_self_nonneg a
    | zero => simp
    | add x y _ _ hx hy => simpa only [map_add] using add_nonneg hx hy

@[simp]
theorem completionPositiveLinearMap_apply (ω : PreCStarState A)
    (x : Completion A) : ω.completionPositiveLinearMap x = ω.completionCLM x :=
  rfl

@[simp]
theorem completionPositiveLinearMap_one (ω : PreCStarState A) :
    ω.completionPositiveLinearMap 1 = 1 :=
  ω.completionCLM_one

/-- The Hilbert space obtained by applying Mathlib's GNS construction to the completed state. -/
abbrev CompletionGNS (ω : PreCStarState A) :=
  ω.completionPositiveLinearMap.GNS

/-- The canonical GNS representation of the completed pre-C-star algebra. -/
def completionGNSRepresentation (ω : PreCStarState A) :
    Completion A →⋆ₐ[ℂ]
      (ω.CompletionGNS →L[ℂ] ω.CompletionGNS) :=
  ω.completionPositiveLinearMap.gnsStarAlgHom

end PreCStarState

end NCG
