/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.ExactCutoffCompatibility
import Mathlib.Algebra.Star.NonUnitalSubalgebra

/-!
# Sequential cutoff families and support-completed corner systems

This module closes the family-level clauses of
`thm:cutoff-compatibility` from the Gran-Tensor manuscript.

* `cutoffSupportIsometry_family` constructs the unique support isometry at
  every prefix index, including singular prefix Grams.
* `cutoffSequentialTensorIntertwining_implies_prefixExact_family` is the
  converse in (C2), with the physical input/output and memory isometries
  combined by the manuscript's tensor products.
* `MatrixCornerDirectedFamily.supportCompleted` is the non-unital star
  algebra generated by all predecessor process-algebra corners.
* `MatrixCornerDirectedFamily.supportCompletedMap` supplies the strict,
  injective corner maps in (C4), and the final instance verifies the actual
  `DirectedSystem` laws.
-/

open Matrix
open scoped Kronecker

namespace NCG

universe u v

/-- The singular-support cutoff isometry exists uniquely at every prefix
index.  This is the genuinely indexed form of (C1), rather than a theorem
about one unspecified prefix. -/
theorem cutoffSupportIsometry_family
    {κ : Type u} {hX hY eX eY : κ → Type v}
    [∀ k, Fintype (hX k)] [∀ k, Fintype (hY k)]
    [∀ k, Fintype (eX k)] [∀ k, Fintype (eY k)]
    (SX : ∀ k, Matrix (hX k) (eX k) ℂ)
    (SY : ∀ k, Matrix (hY k) (eY k) ℂ)
    (J : ∀ k, Matrix (eY k) (eX k) ℂ)
    (hGram : ∀ k, (SX k)ᴴ * SX k = (SY k * J k)ᴴ * (SY k * J k)) :
    ∀ k, ∃! W : LinearMap.range (SX k).mulVecLin →ₗ[ℂ]
        LinearMap.range (SY k).mulVecLin,
      (∀ u : eX k → ℂ,
        W ((SX k).mulVecLin.rangeRestrict u) =
          (SY k).mulVecLin.rangeRestrict (J k *ᵥ u)) ∧
      (∀ x y : LinearMap.range (SX k).mulVecLin,
        star (x : hX k → ℂ) ⬝ᵥ (y : hX k → ℂ) =
          star (W x : hY k → ℂ) ⬝ᵥ (W y : hY k → ℂ)) := by
  intro k
  exact existsUnique_jointSourceRangeCutoffIsometry
    (SX k) (SY k) (J k) (hGram k)

/-- Strict transitivity of the support maps simultaneously at every prefix
index. -/
theorem cutoffSupportIsometry_strictTransitivity_family
    {κ : Type u} {hX hY hZ eX eY eZ : κ → Type v}
    [∀ k, Fintype (hX k)] [∀ k, Fintype (hY k)]
    [∀ k, Fintype (hZ k)] [∀ k, Fintype (eX k)]
    [∀ k, Fintype (eY k)] [∀ k, Fintype (eZ k)]
    (SX : ∀ k, Matrix (hX k) (eX k) ℂ)
    (SY : ∀ k, Matrix (hY k) (eY k) ℂ)
    (SZ : ∀ k, Matrix (hZ k) (eZ k) ℂ)
    (JYX : ∀ k, Matrix (eY k) (eX k) ℂ)
    (JZY : ∀ k, Matrix (eZ k) (eY k) ℂ)
    (WYX : ∀ k, LinearMap.range (SX k).mulVecLin →ₗ[ℂ]
      LinearMap.range (SY k).mulVecLin)
    (WZY : ∀ k, LinearMap.range (SY k).mulVecLin →ₗ[ℂ]
      LinearMap.range (SZ k).mulVecLin)
    (WZX : ∀ k, LinearMap.range (SX k).mulVecLin →ₗ[ℂ]
      LinearMap.range (SZ k).mulVecLin)
    (hYX : ∀ k u, WYX k ((SX k).mulVecLin.rangeRestrict u) =
      (SY k).mulVecLin.rangeRestrict (JYX k *ᵥ u))
    (hZY : ∀ k u, WZY k ((SY k).mulVecLin.rangeRestrict u) =
      (SZ k).mulVecLin.rangeRestrict (JZY k *ᵥ u))
    (hZX : ∀ k u, WZX k ((SX k).mulVecLin.rangeRestrict u) =
      (SZ k).mulVecLin.rangeRestrict ((JZY k * JYX k) *ᵥ u)) :
    ∀ k, (WZY k).comp (WYX k) = WZX k := by
  intro k
  exact jointSourceRangeCutoff_strictComposition
    (SX k) (SY k) (SZ k) (JYX k) (JZY k)
    (WYX k) (WZY k) (WZX k) (hYX k) (hZY k) (hZX k)

/-- The tensor product of two isometries is an isometry. -/
theorem kronecker_isometry
    {aX aY bX bY : Type*}
    [Fintype aX] [Fintype aY] [Fintype bX] [Fintype bY]
    [DecidableEq aX] [DecidableEq bX]
    (A : Matrix aY aX ℂ) (B : Matrix bY bX ℂ)
    (hA : Aᴴ * A = 1) (hB : Bᴴ * B = 1) :
    (A ⊗ₖ B)ᴴ * (A ⊗ₖ B) = 1 := by
  have hstar : (A ⊗ₖ B)ᴴ = Aᴴ ⊗ₖ Bᴴ := by
    ext ⟨i, j⟩ ⟨k, l⟩
    simp only [Matrix.conjTranspose_apply, Matrix.kroneckerMap_apply,
      star_mul']
  rw [hstar, ← Matrix.mul_kronecker_mul, hA, hB,
    Matrix.one_kronecker_one]

/-- (C2), indexed and in the manuscript's tensor form: sequential
intertwining by `j_out ⊗ C_k` and `j_in ⊗ C_{k-1}` implies exact compression
of every prefix Gram. -/
theorem cutoffSequentialTensorIntertwining_implies_prefixExact_family
    {κ : Type u}
    {outX outY memX memY inX inY prevX prevY : κ → Type v}
    [∀ k, Fintype (outX k)] [∀ k, Fintype (outY k)]
    [∀ k, Fintype (memX k)] [∀ k, Fintype (memY k)]
    [∀ k, Fintype (inX k)] [∀ k, Fintype (inY k)]
    [∀ k, Fintype (prevX k)] [∀ k, Fintype (prevY k)]
    [∀ k, DecidableEq (outX k)] [∀ k, DecidableEq (memX k)]
    [∀ k, DecidableEq (inX k)] [∀ k, DecidableEq (prevX k)]
    (VX : ∀ k, Matrix (outX k × memX k) (inX k × prevX k) ℂ)
    (VY : ∀ k, Matrix (outY k × memY k) (inY k × prevY k) ℂ)
    (jOut : ∀ k, Matrix (outY k) (outX k) ℂ)
    (C : ∀ k, Matrix (memY k) (memX k) ℂ)
    (jIn : ∀ k, Matrix (inY k) (inX k) ℂ)
    (Cprev : ∀ k, Matrix (prevY k) (prevX k) ℂ)
    (hjOut : ∀ k, (jOut k)ᴴ * jOut k = 1)
    (hC : ∀ k, (C k)ᴴ * C k = 1)
    (hintertwine : ∀ k,
      (jOut k ⊗ₖ C k) * VX k =
        VY k * (jIn k ⊗ₖ Cprev k)) :
    ∀ k, (VX k)ᴴ * VX k =
      (jIn k ⊗ₖ Cprev k)ᴴ *
        ((VY k)ᴴ * VY k) * (jIn k ⊗ₖ Cprev k) := by
  intro k
  exact sequentialIntertwining_implies_prefixCompression
    (VX k) (VY k)
    (jOut k ⊗ₖ C k)
    (jIn k ⊗ₖ Cprev k)
    (kronecker_isometry (jOut k) (C k) (hjOut k) (hC k))
    (hintertwine k)

/-- Conjugation by an isometry, bundled as the non-unital star-algebra
homomorphism appropriate for a C-star corner inclusion. -/
def matrixIsometryCornerHom
    {a b : Type*} [Fintype a] [Fintype b] [DecidableEq a]
    (C : Matrix b a ℂ) (hC : Cᴴ * C = 1) :
    Matrix a a ℂ →⋆ₙₐ[ℂ] Matrix b b ℂ where
  toFun x := C * x * Cᴴ
  map_zero' := by simp
  map_add' x y := by simp [Matrix.mul_add, Matrix.add_mul]
  map_mul' x y := by
    symm
    calc
      (C * x * Cᴴ) * (C * y * Cᴴ) =
          C * x * (Cᴴ * C) * y * Cᴴ := by
            simp only [Matrix.mul_assoc]
      _ = C * (x * y) * Cᴴ := by
        rw [hC]
        simp only [Matrix.mul_one, Matrix.one_mul, Matrix.mul_assoc]
  map_smul' r x := by
    simp [Matrix.mul_smul, Matrix.smul_mul]
  map_star' x := by
    simp only [star_eq_conjTranspose, Matrix.conjTranspose_mul,
      Matrix.conjTranspose_conjTranspose, Matrix.mul_assoc]

/-- A corner homomorphism induced by an isometry is injective. -/
theorem matrixIsometryCornerHom_injective
    {a b : Type*} [Fintype a] [Fintype b] [DecidableEq a]
    (C : Matrix b a ℂ) (hC : Cᴴ * C = 1) :
    Function.Injective (matrixIsometryCornerHom C hC) := by
  intro x y hxy
  change C * x * Cᴴ = C * y * Cᴴ at hxy
  calc
    x = (Cᴴ * C) * x * (Cᴴ * C) := by rw [hC]; simp
    _ = Cᴴ * (C * x * Cᴴ) * C := by simp only [Matrix.mul_assoc]
    _ = Cᴴ * (C * y * Cᴴ) * C := by rw [hxy]
    _ = (Cᴴ * C) * y * (Cᴴ * C) := by simp only [Matrix.mul_assoc]
    _ = y := by rw [hC]; simp

/-- Finite matrix carriers and strictly composable cutoff isometries. -/
structure MatrixCornerDirectedFamily
    (I : Type u) [Preorder I] (H : I → Type v)
    [∀ i, Fintype (H i)] [∀ i, DecidableEq (H i)] where
  /-- Carrier isometry for every comparable pair. -/
  cutoff : ∀ i j, i ≤ j → Matrix (H j) (H i) ℂ
  /-- Every carrier map is an isometry. -/
  cutoff_isometry : ∀ i j (hij : i ≤ j),
    (cutoff i j hij)ᴴ * cutoff i j hij = 1
  /-- The self-cutoff is the identity. -/
  cutoff_self : ∀ i, cutoff i i le_rfl = 1
  /-- Carrier isometries compose strictly. -/
  cutoff_comp : ∀ i j k (hij : i ≤ j) (hjk : j ≤ k),
    cutoff j k hjk * cutoff i j hij = cutoff i k (hij.trans hjk)

namespace MatrixCornerDirectedFamily

variable {I : Type u} [Preorder I] {H : I → Type v}
variable [∀ i, Fintype (H i)] [∀ i, DecidableEq (H i)]

/-- The corner map attached to a comparable pair. -/
def cornerMap (D : MatrixCornerDirectedFamily I H)
    (i j : I) (hij : i ≤ j) :
    Matrix (H i) (H i) ℂ →⋆ₙₐ[ℂ] Matrix (H j) (H j) ℂ :=
  matrixIsometryCornerHom (D.cutoff i j hij) (D.cutoff_isometry i j hij)

/-- Each process algebra is supplied as a non-unital star subalgebra of its
finite matrix carrier.  The generators of the completed stage `j` are all
predecessor process elements transported into the `j`-corner. -/
def supportCompletedGenerators (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (j : I) : Set (Matrix (H j) (H j) ℂ) :=
  {a | ∃ i, ∃ hij : i ≤ j, ∃ x : Process i,
    a = D.cornerMap i j hij x}

/-- The manuscript's support-completed algebra
`C*(Γ_{ij} A_i Γ_{ij}*: i ≤ j)`, encoded as the non-unital star algebra
generated by all transported predecessor process algebras. -/
def supportCompleted (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (j : I) : NonUnitalStarSubalgebra ℂ (Matrix (H j) (H j) ℂ) :=
  NonUnitalStarAlgebra.adjoin ℂ (D.supportCompletedGenerators Process j)

/-- A cutoff corner carries every generator of one support-completed stage
to the corresponding generator at the later stage. -/
theorem cornerMap_supportCompletedGenerator_mem
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    {j k : I} (hjk : j ≤ k) {a : Matrix (H j) (H j) ℂ}
    (ha : a ∈ D.supportCompletedGenerators Process j) :
    D.cornerMap j k hjk a ∈ D.supportCompleted Process k := by
  rcases ha with ⟨i, hij, x, rfl⟩
  apply NonUnitalStarAlgebra.subset_adjoin ℂ
  refine ⟨i, hij.trans hjk, x, ?_⟩
  change D.cutoff j k hjk *
      (D.cutoff i j hij * (x : Matrix (H i) (H i) ℂ) *
        (D.cutoff i j hij)ᴴ) * (D.cutoff j k hjk)ᴴ =
    D.cutoff i k (hij.trans hjk) *
      (x : Matrix (H i) (H i) ℂ) *
      (D.cutoff i k (hij.trans hjk))ᴴ
  calc
    D.cutoff j k hjk *
          (D.cutoff i j hij * (x : Matrix (H i) (H i) ℂ) *
            (D.cutoff i j hij)ᴴ) * (D.cutoff j k hjk)ᴴ =
        (D.cutoff j k hjk * D.cutoff i j hij) *
          (x : Matrix (H i) (H i) ℂ) *
          (D.cutoff j k hjk * D.cutoff i j hij)ᴴ := by
            rw [Matrix.conjTranspose_mul]
            simp only [Matrix.mul_assoc]
    _ = D.cutoff i k (hij.trans hjk) *
          (x : Matrix (H i) (H i) ℂ) *
          (D.cutoff i k (hij.trans hjk))ᴴ := by
            rw [D.cutoff_comp i j k hij hjk]

/-- The corner map carries the entire generated support-completed algebra
into the later generated algebra. -/
theorem cornerMap_supportCompleted_mem
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    {j k : I} (hjk : j ≤ k) (a : D.supportCompleted Process j) :
    D.cornerMap j k hjk a ∈ D.supportCompleted Process k := by
  have hmap :
      NonUnitalStarSubalgebra.map (D.cornerMap j k hjk)
          (D.supportCompleted Process j) ≤ D.supportCompleted Process k := by
    rw [supportCompleted, NonUnitalStarAlgHom.map_adjoin]
    apply NonUnitalStarAlgebra.adjoin_le
    rintro y ⟨x, hx, rfl⟩
    exact D.cornerMap_supportCompletedGenerator_mem Process hjk hx
  apply hmap
  exact NonUnitalStarSubalgebra.mem_map.mpr ⟨a, a.property, rfl⟩

/-- The strict connecting homomorphism between support-completed stages. -/
def supportCompletedMap (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (i j : I) (hij : i ≤ j) :
    D.supportCompleted Process i →⋆ₙₐ[ℂ] D.supportCompleted Process j :=
  NonUnitalStarAlgHom.codRestrict
    ((D.cornerMap i j hij).comp
      (NonUnitalStarSubalgebraClass.subtype (D.supportCompleted Process i)))
    (D.supportCompleted Process j)
    (fun x => D.cornerMap_supportCompleted_mem Process hij x)

/-- The support-completed connecting maps are injective. -/
theorem supportCompletedMap_injective
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (i j : I) (hij : i ≤ j) :
    Function.Injective (D.supportCompletedMap Process i j hij) := by
  intro x y hxy
  apply Subtype.ext
  apply matrixIsometryCornerHom_injective
    (D.cutoff i j hij) (D.cutoff_isometry i j hij)
  exact congrArg Subtype.val hxy

/-- Identity law for support-completed cutoff maps. -/
theorem supportCompletedMap_self
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (i : I) (a : D.supportCompleted Process i) :
    D.supportCompletedMap Process i i le_rfl a = a := by
  apply Subtype.ext
  change D.cutoff i i le_rfl * (a : Matrix (H i) (H i) ℂ) *
      (D.cutoff i i le_rfl)ᴴ = a
  rw [D.cutoff_self i]
  simp

/-- Composition law for support-completed cutoff maps. -/
theorem supportCompletedMap_map
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ))
    (i j k : I) (hij : i ≤ j) (hjk : j ≤ k)
    (a : D.supportCompleted Process i) :
    D.supportCompletedMap Process j k hjk
        (D.supportCompletedMap Process i j hij a) =
      D.supportCompletedMap Process i k (hij.trans hjk) a := by
  apply Subtype.ext
  change D.cutoff j k hjk *
      (D.cutoff i j hij * (a : Matrix (H i) (H i) ℂ) *
        (D.cutoff i j hij)ᴴ) * (D.cutoff j k hjk)ᴴ =
    D.cutoff i k (hij.trans hjk) *
      (a : Matrix (H i) (H i) ℂ) *
      (D.cutoff i k (hij.trans hjk))ᴴ
  calc
    D.cutoff j k hjk *
          (D.cutoff i j hij * (a : Matrix (H i) (H i) ℂ) *
            (D.cutoff i j hij)ᴴ) * (D.cutoff j k hjk)ᴴ =
        (D.cutoff j k hjk * D.cutoff i j hij) *
          (a : Matrix (H i) (H i) ℂ) *
          (D.cutoff j k hjk * D.cutoff i j hij)ᴴ := by
            rw [Matrix.conjTranspose_mul]
            simp only [Matrix.mul_assoc]
    _ = D.cutoff i k (hij.trans hjk) *
          (a : Matrix (H i) (H i) ℂ) *
          (D.cutoff i k (hij.trans hjk))ᴴ := by
            rw [D.cutoff_comp i j k hij hjk]

/-- The support-completed corner algebras and their concrete corner
homomorphisms form an actual strict directed system. -/
instance supportCompletedDirectedSystem
    (D : MatrixCornerDirectedFamily I H)
    (Process : ∀ i, NonUnitalStarSubalgebra ℂ (Matrix (H i) (H i) ℂ)) :
    DirectedSystem (fun i => D.supportCompleted Process i)
      (fun i j hij => D.supportCompletedMap Process i j hij) where
  map_self i a := D.supportCompletedMap_self Process i a
  map_map k j i hij hjk a := D.supportCompletedMap_map Process i j k hij hjk a

end MatrixCornerDirectedFamily

end NCG
