/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.EndpointDefectIsotypicLocalization

/-!
# The intrinsic spectral record of an endpoint defect

This module completes `thm:endpoint-defect-record`.  On the direct sum of
the distinct eigenspaces of an endpoint defect, an operator invariant under
the full block commutant is scalar on every eigenspace and has no cross-block
entries.  Thus the invariant algebra is exactly the algebra generated by the
spectral PVM.  Its sharp elements select whole eigenspaces, and a single
degenerate eigenspace has no nontrivial invariant sharp refinement.
-/

open Matrix
open scoped Kronecker

namespace NCG

variable {τ : Type*} [Fintype τ] [DecidableEq τ]
  {v : τ → Type*} [∀ π, Fintype (v π)] [∀ π, DecidableEq (v π)]

/-- The algebraic content of the finest-record assertion.  Commutation with
the central spectral projections removes cross-eigenspace entries, while
commutation with the full matrix algebra on each eigenspace makes every
surviving block scalar. -/
theorem endpointDefect_intrinsicRecordAlgebra
    (Q : Matrix (Σ ρ, Unit × v ρ) (Σ ρ, Unit × v ρ) ℂ)
    (hv : ∀ π, Nonempty (v π))
    (hcentral : ∀ π, Q * endpointIsotypicProjection π
      = endpointIsotypicProjection π * Q)
    (hinvariant : ∀ π (B : Matrix (v π) (v π) ℂ),
      endpointIsotypicBlock Q π *
          ((1 : Matrix Unit Unit ℂ) ⊗ₖ B)
        = ((1 : Matrix Unit Unit ℂ) ⊗ₖ B) *
          endpointIsotypicBlock Q π) :
    ∃ c : τ → ℂ,
      (∀ π, endpointIsotypicBlock Q π =
        c π • (1 : Matrix (Unit × v π) (Unit × v π) ℂ))
      ∧ (∀ {π ρ : τ}, π ≠ ρ →
          ∀ i : Unit × v π, ∀ j : Unit × v ρ,
            Q ⟨π, i⟩ ⟨ρ, j⟩ = 0) := by
  classical
  obtain ⟨A, hA, hcross⟩ :=
    endpointDefect_isotypic_form Q hv hcentral hinvariant
  refine ⟨fun π => A π () (), ?_, hcross⟩
  intro π
  rw [hA π]
  ext ⟨u, i⟩ ⟨w, j⟩
  cases u
  cases w
  by_cases hij : i = j
  · subst j
    simp [Matrix.kroneckerMap_apply, Matrix.smul_apply,
      Matrix.one_apply]
  · simp [Matrix.kroneckerMap_apply, Matrix.smul_apply,
      Matrix.one_apply, hij]

/-- An idempotent complex scalar is either zero or one. -/
theorem complex_idempotent_eq_zero_or_one (z : ℂ) (hz : z * z = z) :
    z = 0 ∨ z = 1 := by
  have hfactor : z * (z - 1) = 0 := by
    calc
      z * (z - 1) = z * z - z := by ring
      _ = 0 := sub_eq_zero.mpr hz
  rcases mul_eq_zero.mp hfactor with hzero | hone
  · exact Or.inl hzero
  · exact Or.inr (sub_eq_zero.mp hone)

/-- Sharp elements of the spectral algebra select whole spectral blocks.
Equivalently, every invariant sharp record is a sum of spectral PVM atoms. -/
theorem endpointDefect_sharpRecordCoefficients (c : τ → ℂ)
    (hsharp : ∀ π, c π * c π = c π) :
    ∃ selected : Finset τ, ∀ π,
      c π = if π ∈ selected then 1 else 0 := by
  classical
  let selected : Finset τ := Finset.univ.filter fun π => c π = 1
  refine ⟨selected, fun π => ?_⟩
  by_cases hone : c π = 1
  · simp [selected, hone]
  · have hzero : c π = 0 :=
      (complex_idempotent_eq_zero_or_one (c π) (hsharp π)).resolve_right hone
    simp [selected, hone, hzero]

/-- A degenerate eigenspace supports no nontrivial basis-free sharp point
record: an idempotent commuting with its full unitary/matrix symmetry is
either the zero projection or the identity projection. -/
theorem endpointDefect_degenerateSector_noSharpPoint
    {κ : Type*} [Fintype κ] [DecidableEq κ] [Nonempty κ]
    (Q : Matrix κ κ ℂ)
    (hinvariant : ∀ B : Matrix κ κ ℂ, Q * B = B * Q)
    (hsharp : Q * Q = Q) :
    Q = 0 ∨ Q = 1 := by
  obtain ⟨c, hc⟩ := endpointDefect_irreducible_visibility Q hinvariant
  subst Q
  obtain ⟨i⟩ := (inferInstance : Nonempty κ)
  have hidem : c * c = c := by
    have h := congr_fun (congr_fun hsharp i) i
    simpa [Matrix.mul_apply, Matrix.one_apply, Finset.sum_ite_eq]
      using h
  rcases complex_idempotent_eq_zero_or_one c hidem with rfl | rfl
  · exact Or.inl (by simp)
  · exact Or.inr (by simp)

end NCG
