/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.GrandRecordBimodule
import NCG.Grand.GrandInterface2

/-!
# Equivariant multiplicity-one factorization

This file supplies the genuine Schur step shared by
`thm:SM-record-bimodule` and `lem:SMST-multiplicity-factorization`.  If the
carrier intertwiner space is the one-dimensional line generated by `D`, then
an equivariant operator on carriers tensored with arbitrary multiplicity spaces
has a unique factorization `Y = D ⊗ F`.  The proof extracts every multiplicity
block from the lifted equivariance equations and applies the one-dimensional
intertwiner hypothesis to that block.
-/

open Matrix
open scoped Kronecker

namespace NCG

/-- The carrier matrix in one fixed pair of multiplicity coordinates. -/
def multiplicityCarrierBlock
    {n m g g' : Type*}
    (Y : Matrix (n × g') (m × g) ℂ) (a : g') (b : g) :
    Matrix n m ℂ :=
  fun i j => Y (i, a) (j, b)

/-- Equivariance of a tensor-amplified operator restricts to equivariance of
each carrier block. -/
theorem tensorEquivariance_multiplicityCarrierBlock
    {κ n m g g' : Type*}
    [Fintype n] [Fintype m] [Fintype g] [Fintype g']
    [DecidableEq g] [DecidableEq g']
    (L : κ → Matrix n n ℂ) (R : κ → Matrix m m ℂ)
    (Y : Matrix (n × g') (m × g) ℂ)
    (hY : ∀ q,
      (L q ⊗ₖ (1 : Matrix g' g' ℂ)) * Y =
        Y * (R q ⊗ₖ (1 : Matrix g g ℂ)))
    (q : κ) (a : g') (b : g) :
    L q * multiplicityCarrierBlock Y a b =
      multiplicityCarrierBlock Y a b * R q := by
  ext i j
  have hentry := congrFun (congrFun (hY q) (i, a)) (j, b)
  simpa [Matrix.mul_apply, Matrix.kroneckerMap_apply,
    Matrix.one_apply, Fintype.sum_prod_type,
    multiplicityCarrierBlock] using hentry

/-- Genuine multiplicity-one Schur factorization.  The hypothesis says that
every carrier intertwiner is uniquely a scalar multiple of the normalized
line `D`; the conclusion derives, rather than assumes, the unique
multiplicity matrix `F`. -/
theorem equivariantOperator_unique_kroneckerFactorization
    {κ n m g g' : Type*}
    [Fintype n] [Fintype m] [Fintype g] [Fintype g']
    [DecidableEq g] [DecidableEq g']
    (L : κ → Matrix n n ℂ) (R : κ → Matrix m m ℂ)
    (D : Matrix n m ℂ)
    (hSchur : ∀ Z : Matrix n m ℂ,
      (∀ q, L q * Z = Z * R q) →
        ∃! c : ℂ, Z = c • D)
    (Y : Matrix (n × g') (m × g) ℂ)
    (hY : ∀ q,
      (L q ⊗ₖ (1 : Matrix g' g' ℂ)) * Y =
        Y * (R q ⊗ₖ (1 : Matrix g g ℂ))) :
    ∃! F : Matrix g' g ℂ, Y = D ⊗ₖ F := by
  classical
  have hblock : ∀ a b, ∃! c : ℂ,
      multiplicityCarrierBlock Y a b = c • D := by
    intro a b
    apply hSchur
    intro q
    exact tensorEquivariance_multiplicityCarrierBlock L R Y hY q a b
  choose coeff hcoeff using fun a b => (hblock a b).exists
  let F : Matrix g' g ℂ := fun a b => coeff a b
  have hfactor : Y = D ⊗ₖ F := by
    ext ia jb
    rcases ia with ⟨i, a⟩
    rcases jb with ⟨j, b⟩
    have hab := congrFun (congrFun (hcoeff a b) i) j
    change Y (i, a) (j, b) = D i j * F a b
    simpa [multiplicityCarrierBlock, F, mul_comm] using hab
  refine ⟨F, hfactor, ?_⟩
  intro F' hF'
  ext a b
  have hblockF : multiplicityCarrierBlock Y a b = F' a b • D := by
    ext i j
    have hij := congrFun (congrFun hF' (i, a)) (j, b)
    simpa [multiplicityCarrierBlock, Matrix.kroneckerMap_apply,
      mul_comm] using hij
  change F' a b = coeff a b
  exact (hblock a b).unique hblockF (hcoeff a b)

/-- Exact packet used by both manuscript records: lifted carrier equivariance
forces the unique `D ⊗ F` decomposition, while the canonical endpoint record
action remains the faithful left-right bimodule action proved in
`sm_record_bimodule`. -/
theorem multiplicityOneTypedLink_exact
    {κ n m g g' : Type*}
    [Fintype n] [Fintype m] [Fintype g] [Fintype g']
    [DecidableEq g] [DecidableEq g']
    (L : κ → Matrix n n ℂ) (R : κ → Matrix m m ℂ)
    (D : Matrix n m ℂ)
    (hSchur : ∀ Z : Matrix n m ℂ,
      (∀ q, L q * Z = Z * R q) →
        ∃! c : ℂ, Z = c • D)
    (Y : Matrix (n × g') (m × g) ℂ)
    (hY : ∀ q,
      (L q ⊗ₖ (1 : Matrix g' g' ℂ)) * Y =
        Y * (R q ⊗ₖ (1 : Matrix g g ℂ))) :
    ∃! F : Matrix g' g ℂ, Y = D ⊗ₖ F :=
  equivariantOperator_unique_kroneckerFactorization L R D hSchur Y hY

end NCG
