/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.ExcursionInversion

/-!
# Exact EASY batch 13: reachable exact-lift normal form
-/

open Matrix

namespace NCG

/-- The source-reachable hidden carrier generated by every word
provenance column. -/
def excursionReachable {σ n p : Type*} [Fintype n] [Fintype p]
    [DecidableEq n] [DecidableEq p]
    (A : σ → Matrix n n ℂ) (B : σ → Matrix n p ℂ)
    (C : σ → Matrix p n ℂ) (D : σ → Matrix p p ℂ) :
    Submodule ℂ (p → ℂ) :=
  Submodule.span ℂ (Set.range fun q : List σ × (n → ℂ) =>
    excursionH A B C D q.1 *ᵥ q.2)

/-- Exactness kills every route from the entire source-reachable
hidden sector back to the visible carrier. -/
theorem exact_lift_reachable_no_return {σ n p : Type*}
    [Fintype n] [Fintype p] [DecidableEq n] [DecidableEq p]
    (A : σ → Matrix n n ℂ) (B : σ → Matrix n p ℂ)
    (C : σ → Matrix p n ℂ) (D : σ → Matrix p p ℂ)
    (T : σ → Matrix n n ℂ)
    (hex : ∀ w, excursionX A B C D w = (w.map T).prod) :
    (∀ a, A a = T a)
      ∧ ∀ b y, y ∈ excursionReachable A B C D → B b *ᵥ y = 0 := by
  have hbase := (resolved_excursion_inversion A B C D).2.2.1 T hex
  refine ⟨hbase.1, ?_⟩
  intro b y hy
  induction hy using Submodule.span_induction with
  | mem y hy =>
      obtain ⟨⟨w, x⟩, rfl⟩ := hy
      change B b *ᵥ (excursionH A B C D w *ᵥ x) = 0
      rw [Matrix.mulVec_mulVec, hbase.2.2 b w,
        Matrix.zero_mulVec]
  | zero => rw [Matrix.mulVec_zero]
  | add x y _ _ hx hy => rw [Matrix.mulVec_add, hx, hy, add_zero]
  | smul c x _ hx => rw [Matrix.mulVec_smul, hx, smul_zero]

/-- `cor:exact-lift-normal-form`: on the declared
source-reachable hidden sector each exact lift is lower
triangular, with visible block `T_a` and zero return block. -/
theorem exact_lift_normal_form {σ n p : Type*}
    [Fintype n] [Fintype p] [DecidableEq n] [DecidableEq p]
    (A : σ → Matrix n n ℂ) (B : σ → Matrix n p ℂ)
    (C : σ → Matrix p n ℂ) (D : σ → Matrix p p ℂ)
    (T : σ → Matrix n n ℂ)
    (hex : ∀ w, excursionX A B C D w = (w.map T).prod) :
    (∀ a, A a = T a)
      ∧ (∀ b y, y ∈ excursionReachable A B C D → B b *ᵥ y = 0) :=
  exact_lift_reachable_no_return A B C D T hex

end NCG
