/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Exact EASY batch 14: hidden scheduler no-go

This file formalizes the two clauses absent from the original
single-matrix witness: multitime invariance after summing every
hidden outcome and the full geometric-hazard reset family.
-/

open Matrix

namespace NCG

/-- Sum over the hidden instrument outcome at each time, with an
arbitrary visible intervention inserted at that time. -/
def hiddenInstrumentProcess {A d R : Type*} [Fintype A]
    [Fintype d] [CommSemiring R]
    (Φ : A → Matrix d d R) (I₀ : Matrix d d R) :
    List (Matrix d d R) → Matrix d d R
  | [] => I₀
  | I :: Is => ∑ a, I * Φ a * hiddenInstrumentProcess Φ I₀ Is

/-- The unmarked process built only from the coarse channel. -/
def coarseChannelProcess {d R : Type*} [Fintype d] [CommSemiring R]
    (Φ : Matrix d d R) (I₀ : Matrix d d R) :
    List (Matrix d d R) → Matrix d d R
  | [] => I₀
  | I :: Is => I * Φ * coarseChannelProcess Φ I₀ Is

/-- Summing the hidden outcomes at every time gives exactly the
process generated by the coarse channel, for every list of
visible interventions. -/
theorem hiddenInstrumentProcess_eq_coarse {A d R : Type*}
    [Fintype A] [Fintype d] [CommSemiring R]
    (Φ : A → Matrix d d R) (I₀ : Matrix d d R)
    (Is : List (Matrix d d R)) :
    hiddenInstrumentProcess Φ I₀ Is =
      coarseChannelProcess (∑ a, Φ a) I₀ Is := by
  induction Is with
  | nil => rfl
  | cons I Is ih =>
      simp only [hiddenInstrumentProcess, coarseChannelProcess, ih]
      calc
        ∑ a, I * Φ a * coarseChannelProcess (∑ a, Φ a) I₀ Is
            = (∑ a, I * Φ a) *
                coarseChannelProcess (∑ a, Φ a) I₀ Is := by
              rw [Finset.sum_mul]
        _ = I * (∑ a, Φ a) *
              coarseChannelProcess (∑ a, Φ a) I₀ Is := by
              rw [Finset.mul_sum]

/-- Positive scalar splitting does not alter the coarse reset
channel. -/
theorem reset_hazard_coarse {d : Type*} [Fintype d] [DecidableEq d]
    (R : Matrix d d ℝ) (lam : ℝ) :
    lam • R + (1 - lam) • R = R := by
  module

private theorem idem_pow {d : Type*} [Fintype d] [DecidableEq d]
    (R : Matrix d d ℝ) (hR : R * R = R) :
    ∀ k : ℕ, 1 ≤ k → R ^ k = R := by
  intro k hk
  induction k with
  | zero => omega
  | succ k ih =>
      rcases Nat.eq_zero_or_pos k with rfl | hkpos
      · simp
      · rw [pow_succ, ih hkpos, hR]

/-- The hidden first-return word of the split reset instrument
has the geometric hazard `λ(1-λ)^(n-1)`. -/
theorem reset_hazard_first_return {d : Type*} [Fintype d] [DecidableEq d]
    (R : Matrix d d ℝ) (hR : R * R = R) (lam : ℝ) :
    ∀ n : ℕ, 1 ≤ n →
      (lam • R) * ((1 - lam) • R) ^ (n - 1)
        = (lam * (1 - lam) ^ (n - 1)) • R := by
  intro n hn
  rcases n with _ | _ | k
  · omega
  · simp
  · have hk : 1 ≤ k + 1 := by omega
    simp only [Nat.add_sub_cancel, smul_pow]
    rw [idem_pow R hR (k + 1) hk, Matrix.smul_mul,
      Matrix.mul_smul,
      hR, smul_smul]

/-- `cth:store-scheduler-no-go`: every hidden refinement with
the same coarse channel has the same unmarked multitime process,
while one reset channel admits all geometric hazards. -/
theorem store_scheduler_no_go_exact {A d : Type*}
    [Fintype A] [Fintype d] [DecidableEq d]
    (Φ : A → Matrix d d ℝ) (I₀ : Matrix d d ℝ)
    (R : Matrix d d ℝ) (hR : R * R = R)
    (lam : ℝ) (hlam0 : 0 ≤ lam) (hlam1 : lam ≤ 1) :
    (∀ Is : List (Matrix d d ℝ),
      hiddenInstrumentProcess Φ I₀ Is =
        coarseChannelProcess (∑ a, Φ a) I₀ Is)
    ∧ (lam • R + (1 - lam) • R = R)
    ∧ (∀ n : ℕ, 1 ≤ n →
      (lam • R) * ((1 - lam) • R) ^ (n - 1)
        = (lam * (1 - lam) ^ (n - 1)) • R)
    ∧ 0 ≤ lam ∧ 0 ≤ 1 - lam := by
  refine ⟨hiddenInstrumentProcess_eq_coarse Φ I₀,
    reset_hazard_coarse R lam,
    reset_hazard_first_return R hR lam,
    hlam0, by linarith⟩

end NCG
