/-
Copyright (c) 2026 Aurelien Pelissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurelien Pelissier
-/
import NCG.Grand.FiniteRealEvenSpectralizationExact
import Mathlib.Analysis.Calculus.Deriv.Star
import Mathlib.Analysis.SpecialFunctions.Exponential

/-!
# Exact calibrated unitary curve for a finite Dirac operator

This file supplies the controlled-unitary tangent used in the finite marked
spectral-packet construction.  Every self-adjoint element of a complex
C-star algebra is recovered exactly from the derivative at zero of its
exponential unitary curve; in particular this applies to the finite Dirac
matrix constructed by `FiniteRealEvenSpectralizationExact`.
-/

namespace NCG.FiniteDiracCalibratedUnitaryCurveExact

noncomputable section

open Matrix
open scoped Matrix.Norms.L2Operator ComplexConjugate

/-- The calibrated exponential curve generated by `D`. -/
def calibratedUnitaryCurve {A : Type*} [CStarAlgebra A]
    (D : A) (t : ℝ) : A :=
  NormedSpace.exp (t • ((-Complex.I) • D))

@[simp]
theorem calibratedUnitaryCurve_zero {A : Type*} [CStarAlgebra A]
    (D : A) : calibratedUnitaryCurve D 0 = 1 := by
  simp [calibratedUnitaryCurve]

attribute [-instance] NormedSpace.complexToReal in
/-- The derivative at zero is exactly the skew-adjoint generator `-iD`. -/
theorem calibratedUnitaryCurve_hasDerivAt_zero
    {A : Type*} [CStarAlgebra A] (D : A) :
    HasDerivAt (calibratedUnitaryCurve D) ((-Complex.I) • D) 0 := by
  change HasDerivAt
    (fun t : ℝ => NormedSpace.exp (t • ((-Complex.I) • D)))
    ((-Complex.I) • D) 0
  simpa only [zero_smul, NormedSpace.exp_zero, one_mul] using
    (hasDerivAt_exp_smul_const (𝕂 := ℝ) ((-Complex.I) • D) 0)

attribute [-instance] NormedSpace.complexToReal in
/-- Multiplication by the calibration phase `i` recovers `D` exactly. -/
theorem calibratedUnitaryCurve_recovers_generator
    {A : Type*} [CStarAlgebra A] (D : A) :
    Complex.I • deriv (calibratedUnitaryCurve D) 0 = D := by
  rw [(calibratedUnitaryCurve_hasDerivAt_zero D).deriv]
  rw [← mul_smul]
  norm_num

/-- A self-adjoint generator gives the left unitary identity at every time. -/
theorem star_calibratedUnitaryCurve_mul
    {A : Type*} [CStarAlgebra A] (D : A) (hD : star D = D) (t : ℝ) :
    star (calibratedUnitaryCurve D t) * calibratedUnitaryCurve D t = 1 := by
  let X : A := t • ((-Complex.I) • D)
  have hstarX : star X = -X := by
    simp [X, hD]
  change star (NormedSpace.exp X) * NormedSpace.exp X = 1
  rw [NormedSpace.star_exp, hstarX]
  letI : NormedAlgebra ℚ A := NormedAlgebra.restrictScalars ℚ ℂ A
  rw [← NormedSpace.exp_add_of_commute (Commute.neg_left (Commute.refl X))]
  simp

/-- A self-adjoint generator gives the right unitary identity at every time. -/
theorem calibratedUnitaryCurve_mul_star
    {A : Type*} [CStarAlgebra A] (D : A) (hD : star D = D) (t : ℝ) :
    calibratedUnitaryCurve D t * star (calibratedUnitaryCurve D t) = 1 := by
  let X : A := t • ((-Complex.I) • D)
  have hstarX : star X = -X := by
    simp [X, hD]
  change NormedSpace.exp X * star (NormedSpace.exp X) = 1
  rw [NormedSpace.star_exp, hstarX]
  letI : NormedAlgebra ℚ A := NormedAlgebra.restrictScalars ℚ ℂ A
  rw [← NormedSpace.exp_add_of_commute (Commute.neg_right (Commute.refl X))]
  simp

/-- The finite spectralization Dirac matrix is therefore exactly generated
by a two-sided unitary curve, with no approximation or logarithm choice. -/
theorem finiteSpectralization_dirac_controlled_unitary_tangent
    {A I J : Type*} [Ring A] [Algebra ℂ A] [StarRing A]
    [StarModule ℂ A] [Fintype I] [Fintype J]
    [DecidableEq I] [DecidableEq J]
    (P : FiniteRealEvenSpectralizationExact.Packet
      (A := A) (I := I) (J := J)) :
    (∀ t : ℝ,
        star (calibratedUnitaryCurve P.dirac t) *
            calibratedUnitaryCurve P.dirac t = 1 ∧
        calibratedUnitaryCurve P.dirac t *
            star (calibratedUnitaryCurve P.dirac t) = 1) ∧
      Complex.I • deriv (calibratedUnitaryCurve P.dirac) 0 = P.dirac := by
  refine ⟨fun t => ⟨?_, ?_⟩, calibratedUnitaryCurve_recovers_generator P.dirac⟩
  · apply star_calibratedUnitaryCurve_mul P.dirac
    change P.diracᴴ = P.dirac
    exact P.dirac_isHermitian
  · apply calibratedUnitaryCurve_mul_star P.dirac
    change P.diracᴴ = P.dirac
    exact P.dirac_isHermitian

end

end NCG.FiniteDiracCalibratedUnitaryCurveExact
