/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.FiniteLinearSystemPanelSaturation

/-!
# Algebraic Krylov saturation

Reachable and observable finite-window filtrations for finite-dimensional
linear systems on arbitrary modules, including quotient carriers.
-/

namespace NCG

/-- The span generated by the first 
` iterates of a source subspace. -/
def finiteReachableFiltration
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) : ℕ → Submodule ℂ V
  | 0 => ⊥
  | n + 1 => finiteReachableFiltration A S n ⊔ S.map (A ^ n)

@[simp] theorem finiteReachableFiltration_zero
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) :
    finiteReachableFiltration A S 0 = ⊥ := rfl

theorem finiteReachableFiltration_succ
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) (n : ℕ) :
    finiteReachableFiltration A S (n + 1) =
      finiteReachableFiltration A S n ⊔ S.map (A ^ n) := rfl

theorem finiteReachableFiltration_mono
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) :
    Monotone (finiteReachableFiltration A S) := by
  exact monotone_nat_of_le_succ fun n => by
    rw [finiteReachableFiltration_succ]
    exact le_sup_left

theorem source_pow_le_finiteReachableFiltration
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) {j n : ℕ}
    (hj : j < n) :
    S.map (A ^ j) ≤ finiteReachableFiltration A S n := by
  induction n with
  | zero => omega
  | succ n ih =>
      rw [finiteReachableFiltration_succ]
      rcases Nat.lt_succ_iff_lt_or_eq.mp hj with h | h
      · exact le_trans (ih h) le_sup_left
      · subst h
        exact le_sup_right

theorem map_finiteReachableFiltration_le_succ
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) (n : ℕ) :
    (finiteReachableFiltration A S n).map A ≤
      finiteReachableFiltration A S (n + 1) := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [finiteReachableFiltration_succ, Submodule.map_sup,
        ← Submodule.map_comp, ← Module.End.mul_eq_comp, ← pow_succ']
      exact sup_le
        (le_trans ih (finiteReachableFiltration_mono A S (Nat.le_succ _)))
        (source_pow_le_finiteReachableFiltration A S (Nat.lt_succ_self _))

theorem finiteReachableFiltration_succ_eq_sup_map
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) {n : ℕ}
    (hn : 1 ≤ n) :
    finiteReachableFiltration A S (n + 1) =
      finiteReachableFiltration A S n ⊔
        (finiteReachableFiltration A S n).map A := by
  apply le_antisymm
  · rw [finiteReachableFiltration_succ]
    refine sup_le le_sup_left (le_trans ?_ le_sup_right)
    obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
    rw [pow_succ', Module.End.mul_eq_comp, Submodule.map_comp]
    exact Submodule.map_mono
      (source_pow_le_finiteReachableFiltration A S (Nat.lt_succ_self m))
  · exact sup_le
      (finiteReachableFiltration_mono A S (Nat.le_succ n))
      (map_finiteReachableFiltration_le_succ A S n)

theorem finiteReachableFiltration_minimal
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S M : Submodule ℂ V)
    (hsource : S ≤ M) (hinv : M.map A ≤ M) :
    ∀ n, finiteReachableFiltration A S n ≤ M := by
  have hpow : ∀ n, S.map (A ^ n) ≤ M := by
    intro n
    induction n with
    | zero =>
        simpa only [pow_zero, Module.End.one_eq_id,
          Submodule.map_id] using hsource
    | succ n ih =>
        rw [pow_succ', Module.End.mul_eq_comp, Submodule.map_comp]
        exact le_trans (Submodule.map_mono ih) hinv
  intro n
  induction n with
  | zero => simp
  | succ n ih =>
      rw [finiteReachableFiltration_succ]
      exact sup_le ih (hpow n)

theorem finiteReachableFiltration_freezes
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V) (k : ℕ)
    (heq : finiteReachableFiltration A S k =
      finiteReachableFiltration A S (k + 1)) :
    ∀ j, k ≤ j → finiteReachableFiltration A S j =
      finiteReachableFiltration A S k := by
  cases k with
  | zero =>
      have hS : S = ⊥ := by
        have h := heq.symm
        simpa only [finiteReachableFiltration_zero,
          finiteReachableFiltration_succ, pow_zero, Module.End.one_eq_id, bot_sup_eq,
          Submodule.map_id] using h
      intro j hj
      induction j with
      | zero => rfl
      | succ j ih =>
          rw [finiteReachableFiltration_succ, ih (Nat.zero_le _), hS]
          simp
  | succ k =>
      let K := finiteReachableFiltration A S (k + 1)
      have hinv : K.map A ≤ K := by
        dsimp [K]
        calc
          _ ≤ finiteReachableFiltration A S (k + 1) ⊔
              (finiteReachableFiltration A S (k + 1)).map A := le_sup_right
          _ = finiteReachableFiltration A S (k + 1 + 1) :=
            (finiteReachableFiltration_succ_eq_sup_map A S (by omega)).symm
          _ = finiteReachableFiltration A S (k + 1) := heq.symm
      have hsource : S ≤ K := by
        dsimp [K]
        have h := source_pow_le_finiteReachableFiltration A S
          (j := 0) (n := k + 1) (by omega)
        simpa only [pow_zero, Module.End.one_eq_id, Submodule.map_id] using h
      intro j hj
      apply le_antisymm
      · exact finiteReachableFiltration_minimal A S K hsource hinv j
      · exact finiteReachableFiltration_mono A S hj

/-- A reachable filtration whose union is the carrier is full by the carrier
dimension. -/
theorem finiteReachableFiltration_eq_top_of_exhaustive
    {V : Type*} [AddCommGroup V] [Module ℂ V]
    [FiniteDimensional ℂ V]
    (A : V →ₗ[ℂ] V) (S : Submodule ℂ V)
    (hexhaust : (⨆ n, finiteReachableFiltration A S n) = ⊤)
    (q : ℕ) (hq : Module.finrank ℂ V ≤ q) :
    finiteReachableFiltration A S q = ⊤ :=
  increasing_filtration_saturates_by_finrank
    (finiteReachableFiltration A S)
    (fun k => finiteReachableFiltration_mono A S (Nat.le_succ k))
    (finiteReachableFiltration_freezes A S) hexhaust q hq

/-- States invisible during the first 
` output times. -/
def finiteObservableKernel
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) : ℕ → Submodule ℂ V
  | 0 => ⊤
  | n + 1 => finiteObservableKernel A O n ⊓ LinearMap.ker (O.comp (A ^ n))

@[simp] theorem finiteObservableKernel_zero
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) :
    finiteObservableKernel A O 0 = ⊤ := rfl

theorem finiteObservableKernel_succ
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) (n : ℕ) :
    finiteObservableKernel A O (n + 1) =
      finiteObservableKernel A O n ⊓ LinearMap.ker (O.comp (A ^ n)) := rfl

theorem finiteObservableKernel_antitone
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) :
    Antitone (finiteObservableKernel A O) := by
  exact antitone_nat_of_succ_le fun n => by
    rw [finiteObservableKernel_succ]
    exact inf_le_left

theorem map_finiteObservableKernel_succ_le
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) (n : ℕ) :
    (finiteObservableKernel A O (n + 1)).map A ≤
      finiteObservableKernel A O n := by
  induction n with
  | zero => simp
  | succ n ih =>
      rw [finiteObservableKernel_succ]
      apply le_inf
      · exact le_trans (Submodule.map_mono inf_le_left) ih
      · rintro y ⟨x, hx, rfl⟩
        rw [LinearMap.mem_ker]
        have hxker := hx.2
        change (O.comp (A ^ (n + 1))) x = 0 at hxker
        simpa only [LinearMap.comp_apply, ← Module.End.mul_apply,
          ← pow_succ] using hxker

theorem finiteObservableKernel_le_all
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W)
    (M : Submodule ℂ V)
    (hall : ∀ n, M ≤ LinearMap.ker (O.comp (A ^ n))) :
    ∀ j, M ≤ finiteObservableKernel A O j := by
  intro j
  induction j with
  | zero => simp
  | succ j ih =>
      rw [finiteObservableKernel_succ]
      exact le_inf ih (hall j)

theorem finiteObservableKernel_freezes
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W) (k : ℕ)
    (heq : finiteObservableKernel A O k =
      finiteObservableKernel A O (k + 1)) :
    ∀ j, k ≤ j → finiteObservableKernel A O j =
      finiteObservableKernel A O k := by
  let K := finiteObservableKernel A O k
  have hinv : K.map A ≤ K := by
    dsimp [K]
    calc
      (finiteObservableKernel A O k).map A ≤
          (finiteObservableKernel A O (k + 1)).map A := by rw [heq]
      _ ≤ finiteObservableKernel A O k :=
        map_finiteObservableKernel_succ_le A O k
  have hO : K ≤ LinearMap.ker O := by
    have hK1 : K ≤ finiteObservableKernel A O 1 := by
      cases k with
      | zero =>
          dsimp [K]
          exact heq.le
      | succ k =>
          exact finiteObservableKernel_antitone A O (by omega)
    intro x hx
    have hx1 := hK1 hx
    rw [finiteObservableKernel_succ] at hx1
    have hx0 := hx1.2
    change (O.comp (A ^ 0)) x = 0 at hx0
    change O x = 0
    simpa using hx0
  have hall : ∀ n, K ≤ LinearMap.ker (O.comp (A ^ n)) := by
    intro n
    induction n with
    | zero =>
        intro x hx
        rw [LinearMap.mem_ker]
        have hx0 := hO hx
        rw [LinearMap.mem_ker] at hx0
        simpa using hx0
    | succ n ih =>
        intro x hx
        rw [LinearMap.mem_ker]
        have hAx : A x ∈ K := hinv ⟨x, hx, rfl⟩
        have h := ih hAx
        rw [LinearMap.mem_ker] at h
        simpa only [LinearMap.comp_apply, ← Module.End.mul_apply,
          ← pow_succ] using h
  intro j hj
  apply le_antisymm
  · exact finiteObservableKernel_antitone A O hj
  · exact finiteObservableKernel_le_all A O K hall j

/-- An observable-kernel filtration whose intersection is zero vanishes by
the carrier dimension. -/
theorem finiteObservableKernel_eq_bot_of_exhaustive
    {V W : Type*} [AddCommGroup V] [Module ℂ V]
    [FiniteDimensional ℂ V]
    [AddCommGroup W] [Module ℂ W]
    (A : V →ₗ[ℂ] V) (O : V →ₗ[ℂ] W)
    (hexhaust : (⨅ n, finiteObservableKernel A O n) = ⊥)
    (p : ℕ) (hp : Module.finrank ℂ V ≤ p) :
    finiteObservableKernel A O p = ⊥ :=
  decreasing_filtration_saturates_by_finrank
    (finiteObservableKernel A O) rfl
    (fun k => finiteObservableKernel_antitone A O (Nat.le_succ k))
    (finiteObservableKernel_freezes A O) hexhaust p hp

end NCG
