import NCG.Grand.FiniteMetzlerUniformizationExact

#print axioms NCG.FiniteMetzlerUniformization.uniformizedKernel_nonnegative
#print axioms NCG.FiniteMetzlerUniformization.uniformizedKernel_rowStochastic
#print axioms NCG.FiniteMetzlerUniformization.canonicalUniformizedKernel_nonnegative
#print axioms NCG.FiniteMetzlerUniformization.canonicalUniformizedKernel_rowStochastic
#print axioms NCG.FiniteMetzlerUniformization.poissonizedMatrix_apply
#print axioms NCG.FiniteMetzlerUniformization.terminalPathValue_eq_pow_mulVec
#print axioms NCG.FiniteMetzlerUniformization.terminalPathValue_indicator_eq_pow_apply
#print axioms NCG.FiniteMetzlerUniformization.poissonized_uniformizedKernel_eq_exponentialEntry
#print axioms NCG.FiniteMetzlerUniformization.exponentialEntry_eq_poisson_power_sum
#print axioms NCG.FiniteMetzlerUniformization.exponentialEntry_eq_poisson_endpoint_value
#print axioms NCG.FiniteMetzlerUniformization.exponentialEntry_mulVec_eq_poisson_endpoint_sum
#print axioms NCG.FiniteMetzlerUniformization.tiltedGenerator_poissonization
#print axioms NCG.FiniteMetzlerUniformization.canonicalTiltedKernel_nonnegative
#print axioms NCG.FiniteMetzlerUniformization.tiltedGenerator_canonical_poissonization
