/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib.Analysis.CStarAlgebra.ContinuousLinearMap
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Order
import Mathlib.Analysis.InnerProductSpace.Positive
import NCG.Grand.SourceCoreSemigroupUnboundedExact

/-!
# Hilbert-space source Gram transport

This module proves the full Hilbert-space form of
`cor:source-core-Gram-transport`: the symmetric Gram perturbation estimate,
the two mutual source-innovation bounds, the vanishing cutoff order error,
and the unbounded source-core Duhamel estimate that supplies the perturbation.
-/

open Filter Set
open ContinuousLinearMap Submodule
open scoped Topology InnerProduct

noncomputable section

namespace NCG
namespace HilbertSourceGramTransport

universe u v w x y z

variable {K : Type u} [NormedAddCommGroup K] [InnerProductSpace ℂ K]
  [CompleteSpace K]
variable {H : Type v} [NormedAddCommGroup H] [InnerProductSpace ℂ H]
  [CompleteSpace H]

/-- The source Gram of a bounded Hilbert-space synthesis map. -/
def gram (B : K →L[ℂ] H) : K →L[ℂ] K := B† ∘L B

/-- Exact symmetric expansion of a Gram perturbation. -/
theorem gram_sub (BN BA : K →L[ℂ] H) :
    gram BN - gram BA =
      (BN - BA)† ∘L BA + BN† ∘L (BN - BA) := by
  ext x
  simp only [gram, sub_apply, comp_apply, map_sub, add_apply]
  abel

/-- The manuscript's boxed Hilbert-space Gram perturbation estimate. -/
theorem norm_gram_sub_le (BN BA : K →L[ℂ] H) :
    ‖gram BN - gram BA‖ ≤
      (‖BN‖ + ‖BA‖) * ‖BN - BA‖ := by
  rw [gram_sub]
  calc
    ‖(BN - BA)† ∘L BA + BN† ∘L (BN - BA)‖
        ≤ ‖(BN - BA)† ∘L BA‖ + ‖BN† ∘L (BN - BA)‖ :=
      norm_add_le _ _
    _ ≤ ‖(BN - BA)†‖ * ‖BA‖ + ‖BN†‖ * ‖BN - BA‖ :=
      add_le_add (opNorm_comp_le _ _) (opNorm_comp_le _ _)
    _ = (‖BN‖ + ‖BA‖) * ‖BN - BA‖ := by
      simp only [LinearIsometryEquiv.norm_map]
      ring

/-- The closed source range used for the intrinsic orthogonal innovation. -/
def sourceRangeClosure (B : K →L[ℂ] H) : ClosedSubmodule ℂ H :=
  B.range.closure

/-- The component of `C` orthogonal to the closed range generated by `B`. -/
def innovation (B C : K →L[ℂ] H) : K →L[ℂ] H :=
  (1 - (sourceRangeClosure B).starProjection) ∘L C

theorem innovation_eq_comp_sub (B C : K →L[ℂ] H) :
    innovation B C =
      (1 - (sourceRangeClosure B).starProjection) ∘L (C - B) := by
  ext x
  simp only [innovation, comp_apply, sub_apply, one_apply_eq_self, map_sub]
  have hmem : B x ∈ sourceRangeClosure B := by
    have hle : B.range ≤ (B.range.closure : Submodule ℂ H) :=
      Submodule.closure_le.mp le_rfl
    exact hle ⟨x, rfl⟩
  rw [(sourceRangeClosure B).starProjection_eq_self_iff.mpr hmem]
  abel

/-- Orthogonal projection cannot enlarge the source discrepancy. -/
theorem norm_innovation_le (B C : K →L[ℂ] H) :
    ‖innovation B C‖ ≤ ‖C - B‖ := by
  rw [innovation_eq_comp_sub]
  let U : Submodule ℂ H := sourceRangeClosure B
  change ‖(1 - U.starProjection) ∘L (C - B)‖ ≤ ‖C - B‖
  rw [← U.starProjection_orthogonal']
  calc
    ‖Uᗮ.starProjection ∘L (C - B)‖
        ≤ ‖Uᗮ.starProjection‖ * ‖C - B‖ :=
      opNorm_comp_le _ _
    _ ≤ 1 * ‖C - B‖ := by
      gcongr
      exact Uᗮ.starProjection_norm_le
    _ = ‖C - B‖ := one_mul _

/-- Each mutual source Schur residual is positive and bounded in norm by the
square of the source discrepancy. -/
theorem innovation_gram_bound (B C : K →L[ℂ] H) :
    ((innovation B C)† ∘L innovation B C).IsPositive ∧
      ‖(innovation B C)† ∘L innovation B C‖ ≤ ‖C - B‖ ^ 2 := by
  constructor
  · exact isPositive_adjoint_comp_self (innovation B C)
  · rw [norm_adjoint_comp_self]
    nlinarith [norm_innovation_le B C, norm_nonneg (innovation B C),
      norm_nonneg (C - B)]

/-- Both directional source innovations obey the same quadratic defect
bound `η²`. -/
theorem mutual_innovation_gram_bound (BN BA : K →L[ℂ] H) :
    ‖(innovation BA BN)† ∘L innovation BA BN‖ ≤ ‖BN - BA‖ ^ 2 ∧
      ‖(innovation BN BA)† ∘L innovation BN BA‖ ≤ ‖BN - BA‖ ^ 2 := by
  constructor
  · exact (innovation_gram_bound BA BN).2
  · simpa [norm_sub_rev] using (innovation_gram_bound BN BA).2

/-- The quadratic form of an operator is bounded by its operator norm. -/
theorem abs_reApplyInnerSelf_le_norm_mul_sq
    (T : K →L[ℂ] K) (x : K) :
    |T.reApplyInnerSelf x| ≤ ‖T‖ * ‖x‖ ^ 2 := by
  rw [ContinuousLinearMap.reApplyInnerSelf_apply]
  calc
    |(inner ℂ (T x) x).re| ≤ ‖inner ℂ (T x) x‖ := Complex.abs_re_le_norm _
    _ ≤ ‖T x‖ * ‖x‖ := norm_inner_le_norm _ _
    _ ≤ (‖T‖ * ‖x‖) * ‖x‖ := by
      gcongr
      exact T.le_opNorm x
    _ = ‖T‖ * ‖x‖ ^ 2 := by ring

/-- Explicit quadratic-form rendering of
`G_A ≼ G_N + ‖G_A-G_N‖ I`. -/
theorem gram_quadratic_le_add_error (BN BA : K →L[ℂ] H) (x : K) :
    (gram BA).reApplyInnerSelf x ≤
      (gram BN).reApplyInnerSelf x +
        ‖gram BA - gram BN‖ * ‖x‖ ^ 2 := by
  have hsplit :
      (gram BA - gram BN).reApplyInnerSelf x =
        (gram BA).reApplyInnerSelf x - (gram BN).reApplyInnerSelf x := by
    simp [ContinuousLinearMap.reApplyInnerSelf_apply, inner_sub_left]
  have hbound := abs_reApplyInnerSelf_le_norm_mul_sq
    (gram BA - gram BN) x
  have hupper :
      (gram BA - gram BN).reApplyInnerSelf x ≤
        ‖gram BA - gram BN‖ * ‖x‖ ^ 2 :=
    (le_abs_self _).trans hbound
  rw [hsplit] at hupper
  linarith

/-- Uniformly bounded source maps whose difference vanishes have vanishing
Gram error. -/
theorem gram_error_tendsto_zero
    (BN BA : ℕ → K →L[ℂ] H) (C : ℝ)
    (hbound : ∀ n, ‖BN n‖ + ‖BA n‖ ≤ C)
    (hdiff : Tendsto (fun n ↦ ‖BN n - BA n‖) atTop (𝓝 0)) :
    Tendsto (fun n ↦ ‖gram (BN n) - gram (BA n)‖) atTop (𝓝 0) ∧
      ∀ n x, (gram (BA n)).reApplyInnerSelf x ≤
        (gram (BN n)).reApplyInnerSelf x +
          ‖gram (BA n) - gram (BN n)‖ * ‖x‖ ^ 2 := by
  constructor
  · refine squeeze_zero' (Eventually.of_forall fun n ↦ norm_nonneg _) ?_
        (by simpa using hdiff.const_mul C)
    exact Eventually.of_forall fun n ↦
      (norm_gram_sub_le (BN n) (BA n)).trans
        (mul_le_mul_of_nonneg_right (hbound n) (norm_nonneg _))
  · exact fun n x ↦ gram_quadratic_le_add_error (BN n) (BA n) x

/-! ### Unbounded source-core history maps -/

variable {𝕂 : Type w} [RCLike 𝕂]
variable {E : Type x} [NormedAddCommGroup E] [NormedSpace 𝕂 E]
  [NormedSpace ℝ E] [IsScalarTower ℝ 𝕂 E] [CompleteSpace E]
variable {DA : Type y} [NormedAddCommGroup DA] [NormedSpace 𝕂 DA]
  [NormedSpace ℝ DA] [IsScalarTower ℝ 𝕂 DA] [CompleteSpace DA]
variable {DN : Type z} [NormedAddCommGroup DN] [NormedSpace 𝕂 DN]
variable {H𝕂 : Type*} [NormedAddCommGroup H𝕂] [NormedSpace 𝕂 H𝕂]
  [NormedSpace ℝ H𝕂] [IsScalarTower ℝ 𝕂 H𝕂] [CompleteSpace H𝕂]
variable {Q : Type*} [NormedAddCommGroup Q] [NormedSpace 𝕂 Q]

/-- Duhamel's source-core estimate transported through a bounded history
source `S₀`. -/
theorem sourceCore_history_defect_bound
    (S : StronglyContinuousSemigroup 𝕂 E)
    (SD : StronglyContinuousSemigroup 𝕂 DA)
    (T : StronglyContinuousSemigroup 𝕂 H𝕂)
    (iA : DA →L[𝕂] E) (A : DA →L[𝕂] E)
    (iN : DN →L[𝕂] H𝕂) (N : DN →L[𝕂] H𝕂)
    (V : E →L[𝕂] H𝕂) (Vdom : DA →L[𝕂] DN)
    (R : DA →L[𝕂] H𝕂) (S₀ : Q →L[𝕂] DA)
    (hSD : ∀ t : ℝ, 0 ≤ t →
      iA.comp (SD t) = (S t).comp iA)
    (hAgen : ∀ x : DA, S.IsRightGeneratorVector (iA x) (A x))
    (hNgen : ∀ y : DN, T.IsRightGeneratorVector (iN y) (N y))
    (hVdom : iN.comp Vdom = V.comp iA)
    (hRdef : R = N.comp Vdom - V.comp A)
    (MN MA omegaN omegaA deltaLeak deltaComp : ℝ)
    {t : ℝ} (ht : 0 ≤ t) (hMN : 0 ≤ MN) (hMA : 0 ≤ MA)
    (hR : ‖R‖ ≤ Real.sqrt (deltaLeak + deltaComp))
    (hT : ∀ q : ℝ, 0 ≤ q →
      ‖T q‖ ≤ MN * Real.exp (omegaN * q))
    (hSDbound : ∀ q : ℝ, 0 ≤ q →
      ‖SD q‖ ≤ MA * Real.exp (omegaA * q)) :
    ‖((T t).comp (V.comp iA)).comp S₀ -
        ((V.comp iA).comp (SD t)).comp S₀‖ ≤
      (MN * MA * exponentialConvolution t omegaN omegaA *
        Real.sqrt (deltaLeak + deltaComp)) * ‖S₀‖ := by
  rw [← sub_comp]
  exact (opNorm_comp_le
    ((T t).comp (V.comp iA) - (V.comp iA).comp (SD t)) S₀).trans
      (mul_le_mul_of_nonneg_right
        (SourceCoreSemigroup.unbounded_semigroup_defect_bound
          S SD T iA A iN N V Vdom R hSD hAgen hNgen hVdom hRdef
          MN MA omegaN omegaA deltaLeak deltaComp ht hMN hMA hR hT hSDbound)
        (norm_nonneg S₀))

end HilbertSourceGramTransport
end NCG
