/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The source-minimal internal seed dichotomy

Machinery for `thm:SM-active-internal-commutant` (SM.0p): on the internal carrier
`ℂ³ = ℂp_T ⊕ H_priv`, the ∗-algebra generated by the type line, the private matrix
units, and one operation word `u` is **all** of `M₃(ℂ)` exactly when the colour
corner weight `ω_col(u) = ‖p_H u p_T‖² + ‖p_T u p_H‖²` is positive:

* `adjoin_eq_top_of_corner` (positive branch): a nonzero corner entry, its adjoint,
  and the private units generate every rectangular matrix unit;
* `adjoin_le_blockDiag_of_omega_zero` (zero branch): with both corners zero every
  generator is block diagonal, so the generated algebra reduces;
* `internal_seed_dichotomy` (SM.0p): the iff.
-/

open Finset Matrix Complex

namespace NCG
namespace InternalSeed

/-- The type-line projector `p_T = E₀₀` on `ℂ³`. -/
def pT : Matrix (Fin 3) (Fin 3) ℂ := Matrix.single 0 0 1

/-- The generating set: type line, private matrix units, the word and its
adjoint. -/
def gens (u : Matrix (Fin 3) (Fin 3) ℂ) : Set (Matrix (Fin 3) (Fin 3) ℂ) :=
  {pT} ∪ {Matrix.single 1 1 1, Matrix.single 1 2 1, Matrix.single 2 1 1,
    Matrix.single 2 2 1} ∪ {u, uᴴ}

/-- The colour corner weight `ω_col(u)`. -/
noncomputable def omegaCol (u : Matrix (Fin 3) (Fin 3) ℂ) : ℝ :=
  Complex.normSq (u 1 0) + Complex.normSq (u 2 0)
    + Complex.normSq (u 0 1) + Complex.normSq (u 0 2)

/-- Block-diagonal matrices (type line against private plane). -/
def blockDiag : Subalgebra ℂ (Matrix (Fin 3) (Fin 3) ℂ) where
  carrier := {X | X 0 1 = 0 ∧ X 0 2 = 0 ∧ X 1 0 = 0 ∧ X 2 0 = 0}
  zero_mem' := by simp
  one_mem' := by
    refine ⟨?_, ?_, ?_, ?_⟩ <;> rw [Matrix.one_apply] <;> simp
  add_mem' := fun {X Y} hX hY => by
    refine ⟨?_, ?_, ?_, ?_⟩ <;> rw [Matrix.add_apply]
    · rw [hX.1, hY.1, add_zero]
    · rw [hX.2.1, hY.2.1, add_zero]
    · rw [hX.2.2.1, hY.2.2.1, add_zero]
    · rw [hX.2.2.2, hY.2.2.2, add_zero]
  mul_mem' := fun {X Y} hX hY => by
    have hentry : ∀ a b : Fin 3, (X * Y) a b = ∑ m, X a m * Y m b :=
      fun a b => Matrix.mul_apply
    refine ⟨?_, ?_, ?_, ?_⟩ <;> rw [hentry, Fin.sum_univ_three]
    · rw [hX.1, hX.2.1, hY.1]
      ring
    · rw [hX.1, hX.2.1, hY.2.1]
      ring
    · rw [hX.2.2.1, hY.2.2.1, hY.2.2.2]
      ring
    · rw [hX.2.2.2, hY.2.2.1, hY.2.2.2]
      ring
  algebraMap_mem' := fun c => by
    refine ⟨?_, ?_, ?_, ?_⟩ <;>
      rw [Matrix.algebraMap_matrix_apply] <;> simp

/-- With vanishing corner weight the generators are block diagonal, so the
generated algebra reduces and is not all of `M₃`. -/
theorem adjoin_ne_top_of_omega_zero (u : Matrix (Fin 3) (Fin 3) ℂ)
    (h : omegaCol u = 0) :
    Algebra.adjoin ℂ (gens u) ≠ ⊤ := by
  have hnn : ∀ z : ℂ, 0 ≤ Complex.normSq z := fun z => Complex.normSq_nonneg z
  have h10 : u 1 0 = 0 := by
    have := Complex.normSq_eq_zero.mp (by
      have h1 := hnn (u 1 0)
      have h2 := hnn (u 2 0)
      have h3 := hnn (u 0 1)
      have h4 := hnn (u 0 2)
      rw [omegaCol] at h
      linarith : Complex.normSq (u 1 0) = 0)
    exact this
  have h20 : u 2 0 = 0 := by
    have := Complex.normSq_eq_zero.mp (by
      have h1 := hnn (u 1 0)
      have h2 := hnn (u 2 0)
      have h3 := hnn (u 0 1)
      have h4 := hnn (u 0 2)
      rw [omegaCol] at h
      linarith : Complex.normSq (u 2 0) = 0)
    exact this
  have h01 : u 0 1 = 0 := by
    have := Complex.normSq_eq_zero.mp (by
      have h1 := hnn (u 1 0)
      have h2 := hnn (u 2 0)
      have h3 := hnn (u 0 1)
      have h4 := hnn (u 0 2)
      rw [omegaCol] at h
      linarith : Complex.normSq (u 0 1) = 0)
    exact this
  have h02 : u 0 2 = 0 := by
    have := Complex.normSq_eq_zero.mp (by
      have h1 := hnn (u 1 0)
      have h2 := hnn (u 2 0)
      have h3 := hnn (u 0 1)
      have h4 := hnn (u 0 2)
      rw [omegaCol] at h
      linarith : Complex.normSq (u 0 2) = 0)
    exact this
  have hgen : gens u ⊆ (blockDiag : Set (Matrix (Fin 3) (Fin 3) ℂ)) := by
    intro X hX
    rcases hX with (hX | hX) | hX
    · rw [Set.mem_singleton_iff.mp hX]
      refine ⟨?_, ?_, ?_, ?_⟩ <;> rw [pT, Matrix.single_apply] <;> simp
    · rcases hX with hX | hX | hX | hX <;> rw [hX] <;>
        exact ⟨by rw [Matrix.single_apply]; simp,
          by rw [Matrix.single_apply]; simp,
          by rw [Matrix.single_apply]; simp,
          by rw [Matrix.single_apply]; simp⟩
    · rcases hX with hX | hX <;> rw [Set.mem_singleton_iff.mp hX]
      · exact ⟨h01, h02, h10, h20⟩
      · refine ⟨?_, ?_, ?_, ?_⟩ <;> rw [Matrix.conjTranspose_apply]
        · rw [h10, star_zero]
        · rw [h20, star_zero]
        · rw [h01, star_zero]
        · rw [h02, star_zero]
  intro hcon
  have hle : Algebra.adjoin ℂ (gens u) ≤ blockDiag := Algebra.adjoin_le hgen
  rw [hcon] at hle
  have hmem : Matrix.single (0 : Fin 3) 1 (1 : ℂ) ∈ blockDiag :=
    hle (Algebra.mem_top)
  have h01mem := hmem.1
  rw [Matrix.single_apply_same] at h01mem
  exact one_ne_zero h01mem

theorem omega_nonneg (u : Matrix (Fin 3) (Fin 3) ℂ) : 0 ≤ omegaCol u := by
  rw [omegaCol]
  have h1 := Complex.normSq_nonneg (u 1 0)
  have h2 := Complex.normSq_nonneg (u 2 0)
  have h3 := Complex.normSq_nonneg (u 0 1)
  have h4 := Complex.normSq_nonneg (u 0 2)
  linarith

/-- A subalgebra containing all nine matrix units is everything. -/
theorem top_of_units {A : Subalgebra ℂ (Matrix (Fin 3) (Fin 3) ℂ)}
    (h : ∀ i j : Fin 3, Matrix.single i j (1 : ℂ) ∈ A) : A = ⊤ := by
  rw [eq_top_iff]
  intro X _
  rw [Matrix.matrix_eq_sum_single X]
  refine A.sum_mem fun i _ => A.sum_mem fun j _ => ?_
  have hX : Matrix.single i j (X i j) = X i j • Matrix.single i j 1 := by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  rw [hX]
  exact A.smul_mem (h i j) _

/-- **The source-minimal internal seed dichotomy (SM.0p)**: the ∗-algebra generated
by the type line, the private matrix units, and one operation word is all of
`M₃(ℂ)` exactly when the colour corner weight is positive. -/
theorem internal_seed_dichotomy (u : Matrix (Fin 3) (Fin 3) ℂ) :
    Algebra.adjoin ℂ (gens u) = ⊤ ↔ 0 < omegaCol u := by
  constructor
  · intro htop
    rcases lt_or_eq_of_le (omega_nonneg u) with h | h
    · exact h
    · exact absurd htop (adjoin_ne_top_of_omega_zero u h.symm)
  · intro hpos
    have hcase : u 1 0 ≠ 0 ∨ u 2 0 ≠ 0 ∨ u 0 1 ≠ 0 ∨ u 0 2 ≠ 0 := by
      by_contra hall
      rw [not_or, not_or, not_or, not_not, not_not, not_not, not_not] at hall
      obtain ⟨h1, h2, h3, h4⟩ := hall
      rw [omegaCol, h1, h2, h3, h4] at hpos
      simp at hpos
    set A := Algebra.adjoin ℂ (gens u) with hA
    have hu : u ∈ A := Algebra.subset_adjoin (by simp [gens])
    have huH : uᴴ ∈ A := Algebra.subset_adjoin (by simp [gens])
    have h00 : Matrix.single (0 : Fin 3) 0 (1 : ℂ) ∈ A := by
      have hp : pT ∈ A := Algebra.subset_adjoin (by simp [gens])
      rwa [pT] at hp
    have h11 : Matrix.single (1 : Fin 3) 1 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens])
    have h12 : Matrix.single (1 : Fin 3) 2 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens])
    have h21 : Matrix.single (2 : Fin 3) 1 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens])
    have h22 : Matrix.single (2 : Fin 3) 2 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens])
    have hextract : ∀ i j : Fin 3, Matrix.single i i (1 : ℂ) ∈ A →
        Matrix.single j j (1 : ℂ) ∈ A → u i j ≠ 0 →
        Matrix.single i j (1 : ℂ) ∈ A := by
      intro i j hii hjj hne
      have h1 : Matrix.single i i (1 : ℂ) * u * Matrix.single j j 1 ∈ A :=
        mul_mem (mul_mem hii hu) hjj
      rw [Matrix.single_mul_mul_single] at h1
      have h2 := A.smul_mem h1 (u i j)⁻¹
      rwa [Matrix.smul_single, smul_eq_mul, one_mul, mul_one,
        inv_mul_cancel₀ hne] at h2
    have hextractH : ∀ i j : Fin 3, Matrix.single i i (1 : ℂ) ∈ A →
        Matrix.single j j (1 : ℂ) ∈ A → u j i ≠ 0 →
        Matrix.single i j (1 : ℂ) ∈ A := by
      intro i j hii hjj hne
      have h1 : Matrix.single i i (1 : ℂ) * uᴴ * Matrix.single j j 1 ∈ A :=
        mul_mem (mul_mem hii huH) hjj
      rw [Matrix.single_mul_mul_single] at h1
      have hne' : uᴴ i j ≠ 0 := by
        rw [Matrix.conjTranspose_apply]
        intro hc
        exact hne (by simpa using congrArg star hc)
      have h2 := A.smul_mem h1 (uᴴ i j)⁻¹
      rwa [Matrix.smul_single, smul_eq_mul, one_mul, mul_one,
        inv_mul_cancel₀ hne'] at h2
    have hstep : ∀ (a b c : Fin 3), Matrix.single a b (1 : ℂ) ∈ A →
        Matrix.single b c (1 : ℂ) ∈ A → Matrix.single a c (1 : ℂ) ∈ A := by
      intro a b c hab hbc
      have h1 := mul_mem hab hbc
      rwa [Matrix.single_mul_single_same, one_mul] at h1
    rcases hcase with h | h | h | h
    · have h10 := hextract 1 0 h11 h00 h
      have h01 := hextractH 0 1 h00 h11 h
      have h20 := hstep 2 1 0 h21 h10
      have h02 := hstep 0 1 2 h01 h12
      refine top_of_units fun i j => ?_
      fin_cases i <;> fin_cases j <;>
        first
          | exact h00 | exact h01 | exact h02 | exact h10 | exact h11
          | exact h12 | exact h20 | exact h21 | exact h22
    · have h20 := hextract 2 0 h22 h00 h
      have h02 := hextractH 0 2 h00 h22 h
      have h10 := hstep 1 2 0 h12 h20
      have h01 := hstep 0 2 1 h02 h21
      refine top_of_units fun i j => ?_
      fin_cases i <;> fin_cases j <;>
        first
          | exact h00 | exact h01 | exact h02 | exact h10 | exact h11
          | exact h12 | exact h20 | exact h21 | exact h22
    · have h01 := hextract 0 1 h00 h11 h
      have h10 := hextractH 1 0 h11 h00 h
      have h20 := hstep 2 1 0 h21 h10
      have h02 := hstep 0 1 2 h01 h12
      refine top_of_units fun i j => ?_
      fin_cases i <;> fin_cases j <;>
        first
          | exact h00 | exact h01 | exact h02 | exact h10 | exact h11
          | exact h12 | exact h20 | exact h21 | exact h22
    · have h02 := hextract 0 2 h00 h22 h
      have h20 := hextractH 2 0 h22 h00 h
      have h10 := hstep 1 2 0 h12 h20
      have h01 := hstep 0 2 1 h02 h21
      refine top_of_units fun i j => ?_
      fin_cases i <;> fin_cases j <;>
        first
          | exact h00 | exact h01 | exact h02 | exact h10 | exact h11
          | exact h12 | exact h20 | exact h21 | exact h22

end InternalSeed
end NCG
