/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The assembled internal relative commutant

Machinery for `thm:SM-active-internal-commutant` (SM.0q): on the assembled
seven-dimensional internal carrier `ℂ³ ⊕ ℂ² ⊕ ℂ ⊕ ℂ` (colour, weak, and two
multiplicity-one sectors), the ∗-algebra generated by the type line, the private
units, the weak units, the scalar sectors, and one colour-supported operation word
equals the **full block algebra** `M₃(ℂ) ⊕ M₂(ℂ) ⊕ ℂ ⊕ ℂ` exactly when the colour
corner weight is positive (`assembled_dichotomy`) — the boxed SM.0q internal
relative commutant on the positive branch.
-/

open Finset Matrix

namespace NCG
namespace InternalAssembly

/-- Sector labels of the assembled carrier: colour `{0,1,2}`, weak `{3,4}`, and two
scalar sectors `{5}`, `{6}`. -/
def blockOf : Fin 7 → Fin 4 := ![0, 0, 0, 1, 1, 2, 3]

/-- The block algebra `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ`. -/
def blockAlgebra : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ) where
  carrier := {X | ∀ i j, blockOf i ≠ blockOf j → X i j = 0}
  zero_mem' := fun i j _ => rfl
  one_mem' := fun i j hij => by
    rw [Matrix.one_apply, if_neg (fun hc => hij (by rw [hc]))]
  add_mem' := fun {X Y} hX hY i j hij => by
    rw [Matrix.add_apply, hX i j hij, hY i j hij, add_zero]
  mul_mem' := fun {X Y} hX hY i j hij => by
    rw [Matrix.mul_apply]
    refine Finset.sum_eq_zero fun m _ => ?_
    by_cases hm : blockOf i = blockOf m
    · rw [hY m j (fun hc => hij (hm.trans hc)), mul_zero]
    · rw [hX i m hm, zero_mul]
  algebraMap_mem' := fun c i j hij => by
    rw [Matrix.algebraMap_matrix_apply, if_neg (fun hc => hij (by rw [hc]))]

/-- The assembled generating set. -/
def gens7 (u : Matrix (Fin 7) (Fin 7) ℂ) : Set (Matrix (Fin 7) (Fin 7) ℂ) :=
  {Matrix.single 0 0 1, Matrix.single 1 1 1, Matrix.single 1 2 1,
   Matrix.single 2 1 1, Matrix.single 2 2 1, Matrix.single 3 3 1,
   Matrix.single 3 4 1, Matrix.single 4 3 1, Matrix.single 4 4 1,
   Matrix.single 5 5 1, Matrix.single 6 6 1, u, uᴴ}

/-- Colour support of the operation word. -/
def ColourSupported (u : Matrix (Fin 7) (Fin 7) ℂ) : Prop :=
  ∀ i j : Fin 7, ¬(blockOf i = 0 ∧ blockOf j = 0) → u i j = 0

/-- The colour corner weight on the assembled carrier. -/
noncomputable def omega7 (u : Matrix (Fin 7) (Fin 7) ℂ) : ℝ :=
  Complex.normSq (u 1 0) + Complex.normSq (u 2 0)
    + Complex.normSq (u 0 1) + Complex.normSq (u 0 2)

theorem omega7_nonneg (u : Matrix (Fin 7) (Fin 7) ℂ) : 0 ≤ omega7 u := by
  rw [omega7]
  have h1 := Complex.normSq_nonneg (u 1 0)
  have h2 := Complex.normSq_nonneg (u 2 0)
  have h3 := Complex.normSq_nonneg (u 0 1)
  have h4 := Complex.normSq_nonneg (u 0 2)
  linarith

/-- Single-entry matrices with same-sector indices are block members. -/
theorem single_mem_blockAlgebra {i j : Fin 7} (h : blockOf i = blockOf j) (c : ℂ) :
    Matrix.single i j c ∈ blockAlgebra := by
  intro a b hab
  rw [Matrix.single_apply, if_neg]
  rintro ⟨hia, hjb⟩
  exact hab (hia ▸ hjb ▸ h)

/-- The generators are block members. -/
theorem gens7_subset_blockAlgebra {u : Matrix (Fin 7) (Fin 7) ℂ}
    (hsupp : ColourSupported u) :
    gens7 u ⊆ (blockAlgebra : Set (Matrix (Fin 7) (Fin 7) ℂ)) := by
  intro X hX
  rcases hX with hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]; exact single_mem_blockAlgebra (by decide) 1
  · rw [hX]
    intro a b hab
    refine hsupp a b ?_
    rintro ⟨ha, hb⟩
    exact hab (ha.trans hb.symm)
  · rw [Set.mem_singleton_iff.mp hX]
    intro a b hab
    rw [Matrix.conjTranspose_apply, hsupp b a (fun hc =>
      hab (hc.2.trans hc.1.symm)), star_zero]

/-- With vanishing colour corner weight the assembled algebra is strictly smaller
than the block algebra. -/
theorem assembled_ne_of_omega_zero {u : Matrix (Fin 7) (Fin 7) ℂ}
    (hsupp : ColourSupported u) (h : omega7 u = 0) :
    Algebra.adjoin ℂ (gens7 u) ≠ blockAlgebra := by
  have hnn := fun z => Complex.normSq_nonneg z
  have h10 : u 1 0 = 0 := by
    refine Complex.normSq_eq_zero.mp ?_
    have h1 := hnn (u 1 0); have h2 := hnn (u 2 0)
    have h3 := hnn (u 0 1); have h4 := hnn (u 0 2)
    rw [omega7] at h
    linarith
  have h20 : u 2 0 = 0 := by
    refine Complex.normSq_eq_zero.mp ?_
    have h1 := hnn (u 1 0); have h2 := hnn (u 2 0)
    have h3 := hnn (u 0 1); have h4 := hnn (u 0 2)
    rw [omega7] at h
    linarith
  have h01 : u 0 1 = 0 := by
    refine Complex.normSq_eq_zero.mp ?_
    have h1 := hnn (u 1 0); have h2 := hnn (u 2 0)
    have h3 := hnn (u 0 1); have h4 := hnn (u 0 2)
    rw [omega7] at h
    linarith
  have h02 : u 0 2 = 0 := by
    refine Complex.normSq_eq_zero.mp ?_
    have h1 := hnn (u 1 0); have h2 := hnn (u 2 0)
    have h3 := hnn (u 0 1); have h4 := hnn (u 0 2)
    rw [omega7] at h
    linarith
  -- the colour-reduced refinement of the block algebra
  let R : Subalgebra ℂ (Matrix (Fin 7) (Fin 7) ℂ) :=
  { carrier := {X | (∀ i j, blockOf i ≠ blockOf j → X i j = 0)
      ∧ X 0 1 = 0 ∧ X 0 2 = 0 ∧ X 1 0 = 0 ∧ X 2 0 = 0}
    zero_mem' := ⟨fun _ _ _ => rfl, rfl, rfl, rfl, rfl⟩
    one_mem' := by
      refine ⟨fun i j hij => ?_, ?_, ?_, ?_, ?_⟩ <;>
        rw [Matrix.one_apply]
      · rw [if_neg (fun hc => hij (by rw [hc]))]
      all_goals rw [if_neg (by decide)]
    add_mem' := fun {X Y} hX hY => by
      refine ⟨fun i j hij => ?_, ?_, ?_, ?_, ?_⟩
      · rw [Matrix.add_apply, hX.1 i j hij, hY.1 i j hij, add_zero]
      · rw [Matrix.add_apply, hX.2.1, hY.2.1, add_zero]
      · rw [Matrix.add_apply, hX.2.2.1, hY.2.2.1, add_zero]
      · rw [Matrix.add_apply, hX.2.2.2.1, hY.2.2.2.1, add_zero]
      · rw [Matrix.add_apply, hX.2.2.2.2, hY.2.2.2.2, add_zero]
    mul_mem' := fun {X Y} hX hY => by
      have hblk : ∀ i j, blockOf i ≠ blockOf j → (X * Y) i j = 0 := by
        intro i j hij
        rw [Matrix.mul_apply]
        refine Finset.sum_eq_zero fun m _ => ?_
        by_cases hm : blockOf i = blockOf m
        · rw [hY.1 m j (fun hc => hij (hm.trans hc)), mul_zero]
        · rw [hX.1 i m hm, zero_mul]
      refine ⟨hblk, ?_, ?_, ?_, ?_⟩ <;> rw [Matrix.mul_apply, Fin.sum_univ_seven]
      · rw [hX.1 0 3 (by decide), hX.1 0 4 (by decide), hX.1 0 5 (by decide),
          hX.1 0 6 (by decide), hX.2.1, hX.2.2.1, hY.2.1]
        ring
      · rw [hX.1 0 3 (by decide), hX.1 0 4 (by decide), hX.1 0 5 (by decide),
          hX.1 0 6 (by decide), hX.2.1, hX.2.2.1, hY.2.2.1]
        ring
      · rw [hY.1 3 0 (by decide), hY.1 4 0 (by decide), hY.1 5 0 (by decide),
          hY.1 6 0 (by decide), hY.2.2.2.1, hY.2.2.2.2, hX.2.2.2.1]
        ring
      · rw [hY.1 3 0 (by decide), hY.1 4 0 (by decide), hY.1 5 0 (by decide),
          hY.1 6 0 (by decide), hY.2.2.2.1, hY.2.2.2.2, hX.2.2.2.2]
        ring
    algebraMap_mem' := fun c => by
      refine ⟨fun i j hij => ?_, ?_, ?_, ?_, ?_⟩ <;>
        rw [Matrix.algebraMap_matrix_apply]
      · rw [if_neg (fun hc => hij (by rw [hc]))]
      all_goals rw [if_neg (by decide)] }
  have hgen : gens7 u ⊆ (R : Set (Matrix (Fin 7) (Fin 7) ℂ)) := by
    intro X hX
    have hblk := gens7_subset_blockAlgebra hsupp hX
    refine ⟨hblk, ?_, ?_, ?_, ?_⟩
    · rcases hX with hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX]; exact h01
      · rw [Set.mem_singleton_iff.mp hX, Matrix.conjTranspose_apply, h10, star_zero]
    · rcases hX with hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX]; exact h02
      · rw [Set.mem_singleton_iff.mp hX, Matrix.conjTranspose_apply, h20, star_zero]
    · rcases hX with hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX]; exact h10
      · rw [Set.mem_singleton_iff.mp hX, Matrix.conjTranspose_apply, h01, star_zero]
    · rcases hX with hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX | hX
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX, Matrix.single_apply]; rw [if_neg (by decide)]
      · rw [hX]; exact h20
      · rw [Set.mem_singleton_iff.mp hX, Matrix.conjTranspose_apply, h02, star_zero]
  intro hcon
  have hle : Algebra.adjoin ℂ (gens7 u) ≤ R := Algebra.adjoin_le hgen
  rw [hcon] at hle
  have hmem : Matrix.single (0 : Fin 7) 1 (1 : ℂ) ∈ R :=
    hle (single_mem_blockAlgebra (by decide) 1)
  have h01mem := hmem.2.1
  rw [Matrix.single_apply_same] at h01mem
  exact one_ne_zero h01mem

/-- **The assembled internal relative commutant (SM.0q)**: the generated ∗-algebra
equals the full block algebra `M₃ ⊕ M₂ ⊕ ℂ ⊕ ℂ` exactly when the colour corner
weight is positive. -/
theorem assembled_dichotomy (u : Matrix (Fin 7) (Fin 7) ℂ)
    (hsupp : ColourSupported u) :
    Algebra.adjoin ℂ (gens7 u) = blockAlgebra ↔ 0 < omega7 u := by
  constructor
  · intro htop
    rcases lt_or_eq_of_le (omega7_nonneg u) with h | h
    · exact h
    · exact absurd htop (assembled_ne_of_omega_zero hsupp h.symm)
  · intro hpos
    have hcase : u 1 0 ≠ 0 ∨ u 2 0 ≠ 0 ∨ u 0 1 ≠ 0 ∨ u 0 2 ≠ 0 := by
      by_contra hall
      rw [not_or, not_or, not_or, not_not, not_not, not_not, not_not] at hall
      obtain ⟨h1, h2, h3, h4⟩ := hall
      rw [omega7, h1, h2, h3, h4] at hpos
      simp at hpos
    set A := Algebra.adjoin ℂ (gens7 u) with hA
    have hu : u ∈ A := Algebra.subset_adjoin (by simp [gens7])
    have huH : uᴴ ∈ A := Algebra.subset_adjoin (by simp [gens7])
    have h00 : Matrix.single (0 : Fin 7) 0 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h11 : Matrix.single (1 : Fin 7) 1 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h12 : Matrix.single (1 : Fin 7) 2 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h21 : Matrix.single (2 : Fin 7) 1 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h22 : Matrix.single (2 : Fin 7) 2 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h33 : Matrix.single (3 : Fin 7) 3 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h34 : Matrix.single (3 : Fin 7) 4 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h43 : Matrix.single (4 : Fin 7) 3 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h44 : Matrix.single (4 : Fin 7) 4 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h55 : Matrix.single (5 : Fin 7) 5 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have h66 : Matrix.single (6 : Fin 7) 6 (1 : ℂ) ∈ A :=
      Algebra.subset_adjoin (by simp [gens7])
    have hextract : ∀ i j : Fin 7, Matrix.single i i (1 : ℂ) ∈ A →
        Matrix.single j j (1 : ℂ) ∈ A → u i j ≠ 0 →
        Matrix.single i j (1 : ℂ) ∈ A := by
      intro i j hii hjj hne
      have h1 : Matrix.single i i (1 : ℂ) * u * Matrix.single j j 1 ∈ A :=
        mul_mem (mul_mem hii hu) hjj
      rw [Matrix.single_mul_mul_single] at h1
      have h2 := A.smul_mem h1 (u i j)⁻¹
      rwa [Matrix.smul_single, smul_eq_mul, one_mul, mul_one,
        inv_mul_cancel₀ hne] at h2
    have hextractH : ∀ i j : Fin 7, Matrix.single i i (1 : ℂ) ∈ A →
        Matrix.single j j (1 : ℂ) ∈ A → u j i ≠ 0 →
        Matrix.single i j (1 : ℂ) ∈ A := by
      intro i j hii hjj hne
      have h1 : Matrix.single i i (1 : ℂ) * uᴴ * Matrix.single j j 1 ∈ A :=
        mul_mem (mul_mem hii huH) hjj
      rw [Matrix.single_mul_mul_single] at h1
      have hne' : uᴴ i j ≠ 0 := by
        rw [Matrix.conjTranspose_apply]
        intro hc
        exact hne (by simpa using congrArg star hc)
      have h2 := A.smul_mem h1 (uᴴ i j)⁻¹
      rwa [Matrix.smul_single, smul_eq_mul, one_mul, mul_one,
        inv_mul_cancel₀ hne'] at h2
    have hstep : ∀ (a b c : Fin 7), Matrix.single a b (1 : ℂ) ∈ A →
        Matrix.single b c (1 : ℂ) ∈ A → Matrix.single a c (1 : ℂ) ∈ A := by
      intro a b c hab hbc
      have h1 := mul_mem hab hbc
      rwa [Matrix.single_mul_single_same, one_mul] at h1
    have hfinish : Matrix.single (0 : Fin 7) 1 (1 : ℂ) ∈ A →
        Matrix.single (0 : Fin 7) 2 (1 : ℂ) ∈ A →
        Matrix.single (1 : Fin 7) 0 (1 : ℂ) ∈ A →
        Matrix.single (2 : Fin 7) 0 (1 : ℂ) ∈ A → A = blockAlgebra := by
      intro h01 h02 h10 h20
      have hunits : ∀ i j : Fin 7, blockOf i = blockOf j →
          Matrix.single i j (1 : ℂ) ∈ A := by
        intro i j
        fin_cases i <;> fin_cases j <;> intro hb <;>
          first
            | exact h00 | exact h01 | exact h02 | exact h10 | exact h11
            | exact h12 | exact h20 | exact h21 | exact h22 | exact h33
            | exact h34 | exact h43 | exact h44 | exact h55 | exact h66
            | exact absurd hb (by decide)
      refine le_antisymm (Algebra.adjoin_le (gens7_subset_blockAlgebra hsupp)) ?_
      intro X hX
      rw [Matrix.matrix_eq_sum_single X]
      refine A.sum_mem fun i _ => A.sum_mem fun j _ => ?_
      by_cases hb : blockOf i = blockOf j
      · have hs := hunits i j hb
        rw [show Matrix.single i j (X i j) = X i j • Matrix.single i j 1 from by
          rw [Matrix.smul_single, smul_eq_mul, mul_one]]
        exact A.smul_mem hs _
      · rw [hX i j hb, Matrix.single_zero]
        exact A.zero_mem
    rcases hcase with h | h | h | h
    · have h10 := hextract 1 0 h11 h00 h
      have h01 := hextractH 0 1 h00 h11 h
      exact hfinish h01 (hstep 0 1 2 h01 h12) h10 (hstep 2 1 0 h21 h10)
    · have h20 := hextract 2 0 h22 h00 h
      have h02 := hextractH 0 2 h00 h22 h
      exact hfinish (hstep 0 2 1 h02 h21) h02 (hstep 1 2 0 h12 h20) h20
    · have h01 := hextract 0 1 h00 h11 h
      have h10 := hextractH 1 0 h11 h00 h
      exact hfinish h01 (hstep 0 1 2 h01 h12) h10 (hstep 2 1 0 h21 h10)
    · have h02 := hextract 0 2 h00 h22 h
      have h20 := hextractH 2 0 h22 h00 h
      exact hfinish (hstep 0 2 1 h02 h21) h02 (hstep 1 2 0 h12 h20) h20

end InternalAssembly
end NCG
