/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.PeriodicUniformContinuityExact
import Mathlib.Analysis.Calculus.FDeriv.Add
import Mathlib.Analysis.Calculus.FDeriv.Comp
import Mathlib.Algebra.Order.Floor.Ring

/-!
# Bounded lattice tiles and uniform continuity of periodic derivatives

Flooring the coordinates in a finite real basis constructs a bounded
fundamental-domain representative. Periodicity of the actual derivative is
derived by differentiating translations, rather than assumed separately.
-/

open Module
open scoped BigOperators

namespace NCG.LatticePeriodicDifferentiation

noncomputable section

variable {ι E F : Type*} [Fintype ι] [DecidableEq ι]
  [NormedAddCommGroup E] [NormedSpace ℝ E]
  [NormedAddCommGroup F] [NormedSpace ℝ F]

/-- Integer combinations of a real basis. -/
def integerCombination (b : Basis ι ℝ E) : (ι → ℤ) →+ E where
  toFun z := ∑ i, (z i : ℝ) • b i
  map_zero' := by simp
  map_add' z w := by simp [Int.cast_add, add_smul, Finset.sum_add_distrib]

/-- The actual full-rank period lattice generated by the basis. -/
def periodLattice (b : Basis ι ℝ E) : AddSubgroup E := (integerCombination b).range

theorem norm_sub_floor_combination_le (b : Basis ι ℝ E) (x : E) :
    ‖x - integerCombination b (fun i => ⌊b.repr x i⌋)‖ ≤ ∑ i, ‖b i‖ := by
  have hdecomp : x - integerCombination b (fun i => ⌊b.repr x i⌋) =
      ∑ i, Int.fract (b.repr x i) • b i := by
    simp only [Int.fract, sub_smul, Finset.sum_sub_distrib, b.sum_repr]
    rfl
  rw [hdecomp]
  apply (norm_sum_le _ _).trans
  apply Finset.sum_le_sum
  intro i hi
  rw [norm_smul, Real.norm_eq_abs, abs_of_nonneg (Int.fract_nonneg _)]
  exact (mul_le_mul_of_nonneg_right (Int.fract_lt_one _).le (norm_nonneg _)).trans_eq
    (one_mul _)

theorem periodLattice_bounded_cover (b : Basis ι ℝ E) (x : E) :
    ∃ p : periodLattice b, ‖x - p‖ ≤ ∑ i, ‖b i‖ := by
  refine ⟨⟨integerCombination b (fun i => ⌊b.repr x i⌋), ?_⟩,
    norm_sub_floor_combination_le b x⟩
  exact ⟨fun i => ⌊b.repr x i⌋, rfl⟩

/-- A continuous full-rank lattice-periodic field is globally uniformly continuous. -/
theorem uniformContinuous_of_lattice_periodic
    (b : Basis ι ℝ E) (f : E → F) (hf : Continuous f)
    (hperiod : ∀ p : periodLattice b, ∀ x : E, f (x + p) = f x) :
    UniformContinuous f := by
  letI : FiniteDimensional ℝ E := Module.Finite.of_basis b
  exact PeriodicUniformContinuity.uniformContinuous_of_bounded_periodic_cover
    (periodLattice b) f hf hperiod (∑ i, ‖b i‖) (periodLattice_bounded_cover b)

/-- Translation invariance of a differentiable field forces the same invariance of its derivative. -/
theorem derivative_periodic
    (P : AddSubgroup E) (f : E → F) (df : E → E →L[ℝ] F)
    (hf : ∀ x, HasFDerivAt f (df x) x)
    (hperiod : ∀ p : P, ∀ x : E, f (x + p) = f x) :
    ∀ p : P, ∀ x : E, df (x + p) = df x := by
  intro p x
  have htrans := (hasFDerivAt_id (𝕜 := ℝ) x).add_const (p : E)
  have hcomp := (hf (x + p)).comp x htrans
  have heq : (fun y : E => f (y + p)) = f := funext (hperiod p)
  have hder : HasFDerivAt f (df (x + p)) x := by
    simpa only [Function.comp_def, id_eq, ContinuousLinearMap.comp_id, heq] using hcomp
  exact hder.unique (hf x)

/-- The uniform derivative hypothesis required for finite-difference consistency
follows from a genuinely continuously differentiable lattice-periodic field. -/
theorem uniformContinuous_derivative_of_lattice_periodic
    (b : Basis ι ℝ E) (f : E → F) (df : E → E →L[ℝ] F)
    (hf : ∀ x, HasFDerivAt f (df x) x) (hdf : Continuous df)
    (hperiod : ∀ p : periodLattice b, ∀ x : E, f (x + p) = f x) :
    UniformContinuous df :=
  uniformContinuous_of_lattice_periodic b df hdf (derivative_periodic _ f df hf hperiod)

end

end NCG.LatticePeriodicDifferentiation
