/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.LockedOpportunity
import NCG.Grand.ContrastSpectrum

/-!
# Minimal Naimark frame of the locked opportunity instrument

This module supplies the rank, non-projectivity, and explicit excess-vector
clauses of `thm:locked-opportunity-instrument`.  The outcome type is written as
`Unit ⊕ Fin 24`: the left cell is the no-response outcome and the right cells
are the twenty-four locked accepted outcomes.
-/

open Matrix
open scoped ComplexOrder MatrixOrder

namespace NCG

/-- The manuscript's locked opportunity coefficient. -/
noncomputable def lockedOpportunityTheta : ℝ := 576851 / 417942208512

/-- Before whitening by `M_ϑ⁻¹/²`, the twenty-five frame columns consist of
the uniform no-response column and twenty-four coordinate columns. -/
noncomputable def lockedRawFrame (θ : ℝ) : Matrix (Fin 24) (Unit ⊕ Fin 24) ℝ :=
  fun i k => match k with
    | Sum.inl _ => Real.sqrt (1 - θ) / Real.sqrt 2
    | Sum.inr j => if i = j then Real.sqrt θ else 0

/-- The normalized synthesis-null vector displayed in the manuscript. -/
noncomputable def lockedNaimarkNullVector (θ : ℝ) : (Unit ⊕ Fin 24) → ℝ :=
  fun k => match k with
    | Sum.inl _ => Real.sqrt (2 * θ) / Real.sqrt (24 - 22 * θ)
    | Sum.inr _ => -Real.sqrt (1 - θ) / Real.sqrt (24 - 22 * θ)

/-- The unnormalized version of the displayed null vector. -/
noncomputable def lockedNaimarkNullDirection (θ : ℝ) : (Unit ⊕ Fin 24) → ℝ :=
  fun k => match k with
    | Sum.inl _ => Real.sqrt (2 * θ)
    | Sum.inr _ => -Real.sqrt (1 - θ)

theorem lockedRawFrame_mulVec_apply (θ : ℝ)
    (v : (Unit ⊕ Fin 24) → ℝ) (i : Fin 24) :
    (lockedRawFrame θ *ᵥ v) i =
      (Real.sqrt (1 - θ) / Real.sqrt 2) * v (Sum.inl ())
        + Real.sqrt θ * v (Sum.inr i) := by
  simp [lockedRawFrame, Matrix.mulVec, dotProduct]

theorem lockedOpportunityTheta_bounds :
    0 < lockedOpportunityTheta ∧ lockedOpportunityTheta < 1 := by
  norm_num [lockedOpportunityTheta]

private theorem locked_sqrt_balance (θ : ℝ) (hθ : 0 ≤ θ) :
    (Real.sqrt (1 - θ) / Real.sqrt 2) * Real.sqrt (2 * θ)
      = Real.sqrt θ * Real.sqrt (1 - θ) := by
  rw [Real.sqrt_mul (by positivity : (0 : ℝ) ≤ 2)]
  have h2 : Real.sqrt (2 : ℝ) ≠ 0 := Real.sqrt_ne_zero'.mpr (by norm_num)
  field_simp [h2]

/-- Direct substitution of the displayed twenty-five-cell vector annihilates
every synthesis row. -/
theorem lockedRawFrame_nullDirection (θ : ℝ) (hθ : 0 ≤ θ) :
    lockedRawFrame θ *ᵥ lockedNaimarkNullDirection θ = 0 := by
  funext i
  rw [lockedRawFrame_mulVec_apply]
  simp only [lockedNaimarkNullDirection, Pi.zero_apply]
  rw [locked_sqrt_balance θ hθ]
  ring

/-- The raw synthesis kernel is exactly the line generated by the displayed
Naimark excess direction.  Thus the twenty-five outcome cells have precisely
one dimension of excess over the minimal twenty-four-dimensional environment. -/
theorem lockedRawFrame_kernel (θ : ℝ) (hθ : 0 < θ) :
    ∀ v : (Unit ⊕ Fin 24) → ℝ,
      lockedRawFrame θ *ᵥ v = 0 ↔
        ∃ z : ℝ, v = z • lockedNaimarkNullDirection θ := by
  intro v
  constructor
  · intro hv
    have hsθ : Real.sqrt θ ≠ 0 := Real.sqrt_ne_zero'.mpr hθ
    have hs2θ : Real.sqrt (2 * θ) ≠ 0 :=
      Real.sqrt_ne_zero'.mpr (mul_pos (by norm_num) hθ)
    refine ⟨v (Sum.inl ()) / Real.sqrt (2 * θ), ?_⟩
    funext k
    cases k with
    | inl u =>
        cases u
        change v (Sum.inl ()) =
          (v (Sum.inl ()) / Real.sqrt (2 * θ)) * Real.sqrt (2 * θ)
        exact (div_mul_cancel₀ _ hs2θ).symm
    | inr i =>
        have hi := congrFun hv i
        rw [lockedRawFrame_mulVec_apply] at hi
        simp only [Pi.zero_apply] at hi
        have hbal := locked_sqrt_balance θ hθ.le
        have ha : Real.sqrt (1 - θ) / Real.sqrt 2 =
            Real.sqrt θ * Real.sqrt (1 - θ) / Real.sqrt (2 * θ) :=
          (eq_div_iff hs2θ).2 hbal
        rw [ha] at hi
        simp only [Pi.smul_apply, smul_eq_mul,
          lockedNaimarkNullDirection]
        have hi' : Real.sqrt (1 - θ) / Real.sqrt (2 * θ)
              * v (Sum.inl ()) + v (Sum.inr i) = 0 := by
          apply (mul_left_cancel₀ hsθ)
          calc
            Real.sqrt θ *
                (Real.sqrt (1 - θ) / Real.sqrt (2 * θ)
                  * v (Sum.inl ()) + v (Sum.inr i)) =
                (Real.sqrt θ * Real.sqrt (1 - θ)
                    / Real.sqrt (2 * θ)) * v (Sum.inl ())
                  + Real.sqrt θ * v (Sum.inr i) := by ring
            _ = 0 := hi
            _ = Real.sqrt θ * 0 := by ring
        calc
          v (Sum.inr i) =
              -(Real.sqrt (1 - θ) / Real.sqrt (2 * θ)
                * v (Sum.inl ())) := by linarith
          _ = (v (Sum.inl ()) / Real.sqrt (2 * θ))
                * -Real.sqrt (1 - θ) := by ring
  · rintro ⟨z, rfl⟩
    rw [Matrix.mulVec_smul, lockedRawFrame_nullDirection θ hθ.le,
      smul_zero]

theorem lockedNaimarkNullVector_eq_smul (θ : ℝ) :
    lockedNaimarkNullVector θ =
      (Real.sqrt (24 - 22 * θ))⁻¹ • lockedNaimarkNullDirection θ := by
  funext k
  cases k <;> simp [lockedNaimarkNullVector,
    lockedNaimarkNullDirection, div_eq_inv_mul, mul_comm]

/-- The manuscript's normalized vector is in the synthesis kernel. -/
theorem lockedRawFrame_nullVector (θ : ℝ) (hθ : 0 ≤ θ) :
    lockedRawFrame θ *ᵥ lockedNaimarkNullVector θ = 0 := by
  rw [lockedNaimarkNullVector_eq_smul, Matrix.mulVec_smul,
    lockedRawFrame_nullDirection θ hθ, smul_zero]

/-- The displayed excess vector has unit Euclidean squared norm. -/
theorem lockedNaimarkNullVector_normalized (θ : ℝ) (hθ0 : 0 ≤ θ)
    (hθ1 : θ < 1) :
    ∑ k, (lockedNaimarkNullVector θ k) ^ 2 = 1 := by
  have hD : 0 < 24 - 22 * θ := by linarith
  rw [Fintype.sum_sum_type]
  simp only [lockedNaimarkNullVector, Finset.sum_const,
    nsmul_eq_mul]
  rw [div_pow, div_pow, Real.sq_sqrt hD.le,
    Real.sq_sqrt (mul_nonneg (by norm_num) hθ0)]
  rw [show (-Real.sqrt (1 - θ)) ^ 2 = Real.sqrt (1 - θ) ^ 2 by ring]
  rw [Real.sq_sqrt (by linarith : 0 ≤ 1 - θ)]
  norm_num
  have hD' : 24 - θ * 22 ≠ 0 := by nlinarith [hD]
  field_simp [hD']
  ring

/-- A full-column-rank accepted Choi synthesis retains rank twenty-four after
positive invertible coefficient whitening.  This proves both accepted and
total coarse Choi-rank clauses once `M_ϑ = S Sᴴ`. -/
theorem lockedOpportunityChoiRanks {r : Type*} [Fintype r]
    (B : Matrix r (Fin 24) ℂ) (S : Matrix (Fin 24) (Fin 24) ℂ)
    (hB : B.rank = 24) (hS : IsUnit S.det) :
    (B * Bᴴ).rank = 24 ∧
      (B * (S * Sᴴ) * Bᴴ).rank = 24 := by
  constructor
  · rw [Matrix.rank_self_mul_conjTranspose, hB]
  · have hfactor : B * (S * Sᴴ) * Bᴴ = (B * S) * (B * S)ᴴ := by
      simp only [Matrix.conjTranspose_mul, Matrix.mul_assoc]
    rw [hfactor, Matrix.rank_self_mul_conjTranspose,
      Matrix.rank_mul_eq_left_of_isUnit_det S B hS, hB]

/-- On a minimal environment, a left inverse of the full-column-rank
Stinespring synthesis recovers every outcome effect from its branch Choi
operator.  Taking `P = W†` is exactly the pseudoinverse formula in the
manuscript, and the formula proves uniqueness. -/
theorem minimalEnvironmentEffect_unique {r e : Type*} [Fintype r] [Fintype e]
    [DecidableEq e]
    (W : Matrix r e ℂ) (P : Matrix e r ℂ) (J : Matrix r r ℂ)
    (F : Matrix e e ℂ) (hPW : P * W = 1)
    (hJ : J = W * F * Wᴴ) :
    F = P * J * Pᴴ := by
  have hWP : Wᴴ * Pᴴ = 1 := by
    rw [← Matrix.conjTranspose_mul, hPW, Matrix.conjTranspose_one]
  symm
  calc
    P * J * Pᴴ = P * (W * F * Wᴴ) * Pᴴ := by rw [hJ]
    _ = (P * W) * F * (Wᴴ * Pᴴ) := by
      simp only [Matrix.mul_assoc]
    _ = F := by rw [hPW, hWP, Matrix.one_mul, Matrix.mul_one]

/-- Consequently two effects representing the same branch Choi operator on
the minimal synthesis space are equal. -/
theorem minimalEnvironmentEffect_injective {r e : Type*} [Fintype r]
    [Fintype e] [DecidableEq e] (W : Matrix r e ℂ) (P : Matrix e r ℂ)
    (hPW : P * W = 1) (F G : Matrix e e ℂ)
    (hFG : W * F * Wᴴ = W * G * Wᴴ) : F = G := by
  rw [minimalEnvironmentEffect_unique W P (W * F * Wᴴ) F hPW rfl,
    minimalEnvironmentEffect_unique W P (W * G * Wᴴ) G hPW rfl,
    hFG]

/-- Gram matrix of the twenty-four accepted minimal-environment frame vectors
at the locked coefficient. -/
noncomputable def lockedAcceptedFrameGram : Matrix (Fin 24) (Fin 24) ℂ :=
  let θ : ℂ := lockedOpportunityTheta
  θ • (θ⁻¹ • (1 - (24 : ℂ)⁻¹ • allOnes24)
    + ((12 : ℂ) - 11 * θ)⁻¹ • ((24 : ℂ)⁻¹ • allOnes24))

/-- Two distinct accepted frame vectors have nonzero overlap.  Hence the
minimal-environment outcome POVM is not projection valued. -/
theorem lockedAcceptedFrame_not_orthogonal :
    lockedAcceptedFrameGram 0 1 ≠ 0 := by
  let θ : ℂ := lockedOpportunityTheta
  have hθ : θ ≠ 0 := by
    norm_num [θ, lockedOpportunityTheta]
  have h12 : (12 : ℂ) - 11 * θ ≠ 0 := by
    norm_num [θ, lockedOpportunityTheta]
  have h01 : (0 : Fin 24) ≠ 1 := by decide
  have hover :=
    (locked_opportunity_contrast_spectrum θ hθ h12).2.2.2 0 1 h01
  have hrhs : -(1 - θ) / (2 * ((12 : ℂ) - 11 * θ)) ≠ 0 := by
    norm_num [θ, lockedOpportunityTheta]
  change θ * (θ⁻¹ • (1 - (24 : ℂ)⁻¹ • allOnes24)
    + ((12 : ℂ) - 11 * θ)⁻¹ • ((24 : ℂ)⁻¹ • allOnes24)) 0 1 ≠ 0
  rw [hover]
  exact hrhs

/-- The only way to obtain the manuscript's rejected thirty-seven-cell count
is to add twelve extra binary refinements to the locked twenty-five cells; it
is therefore arithmetically distinct from the locked Store record. -/
theorem lockedRecord_excludes_thirtySeven :
    6 * 2 * 2 = 24 ∧ 24 + 1 = 25 ∧ 25 + 12 = 37 ∧ 37 ≠ 25 := by
  norm_num

end NCG
