import NCG.Grand.LorentzInvariantDensityClassificationExact

#print axioms NCG.LorentzInvariantDensityClassification.raised_pairing_lorentzNatural
#print axioms NCG.LorentzInvariantDensityClassification.metric_mul_hodgeStar
#print axioms NCG.LorentzInvariantDensityClassification.invariant_pairing_eq_metric_add_wedge
#print axioms NCG.LorentzInvariantDensityClassification.metric_add_wedge_invariant
#print axioms NCG.LorentzInvariantDensityClassification.metric_wedge_coefficients_unique
#print axioms NCG.LorentzInvariantDensityClassification.invariant_pairing_iff_existsUnique
#print axioms NCG.LorentzInvariantDensityClassification.alternating_coframe_scalar_eq_determinant
#print axioms NCG.LorentzInvariantDensityClassification.alternating_coframe_scalar_unique
#print axioms NCG.LorentzInvariantDensityClassification.alternating_coframe_scalar_lorentz_invariant
