/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.OperationalTriviality
import Mathlib.Analysis.CStarAlgebra.GelfandNaimarkSegal

/-!
# GNS density closure for operational triviality

This file supplies the C-star density and cyclicity step missing from
`thm:operational-triviality`.  In a cyclic representation of a normalized
positive functional, scalar action on a norm-dense algebra generated by the
determining panel extends to the whole C-star algebra.  The cyclic Hilbert
space is then one-dimensional and the functional is a character.
-/

open Set
open scoped InnerProductSpace ComplexOrder

noncomputable section

namespace NCG.OperationalTrivialityGNS

variable {A H : Type*}
  [CStarAlgebra A] [PartialOrder A] [StarOrderedRing A]
  [NormedAddCommGroup H] [InnerProductSpace ℂ H] [CompleteSpace H]

/-- A C-star representation regarded as a bounded linear map into bounded
operators. -/
def representationCLM (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) :
    A →L[ℂ] (H →L[ℂ] H) :=
  pi.toLinearMap.mkContinuous 1 fun a => by
    change ‖pi a‖ ≤ 1 * ‖a‖
    simpa only [one_mul] using NonUnitalStarAlgHom.norm_apply_le pi a

@[simp] theorem representationCLM_apply
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (a : A) :
    representationCLM pi a = pi a := rfl

/-- The represented orbit of a fixed vector varies continuously with the
observable. -/
theorem continuous_orbit (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H) :
    Continuous fun a => pi a Omega := by
  exact (ContinuousLinearMap.apply ℂ H Omega).continuous.comp
    (representationCLM pi).continuous

/-- Scalar action on generators propagates through their algebraic unital
algebra. -/
theorem scalar_on_adjoin
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H)
    (D : Set A)
    (hD : ∀ a ∈ D, ∃ c : ℂ, pi a Omega = c • Omega) :
    ∀ a ∈ Algebra.adjoin ℂ D, ∃ c : ℂ, pi a Omega = c • Omega := by
  intro a ha
  induction ha using Algebra.adjoin_induction with
  | mem a ha => exact hD a ha
  | algebraMap c =>
      exact ⟨c, by simp [Algebra.algebraMap_eq_smul_one]⟩
  | add a b _ _ ha hb =>
      obtain ⟨ca, ha⟩ := ha
      obtain ⟨cb, hb⟩ := hb
      exact ⟨ca + cb, by simp [ha, hb, add_smul]⟩
  | mul a b _ _ ha hb =>
      obtain ⟨ca, ha⟩ := ha
      obtain ⟨cb, hb⟩ := hb
      refine ⟨cb * ca, ?_⟩
      simp only [map_mul, ContinuousLinearMap.mul_apply, hb, map_smul,
        ha, smul_smul]

/-- Norm density upgrades scalar action on the generated algebra to scalar
action on every element of the C-star algebra. -/
theorem scalar_on_all_of_dense_adjoin
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H)
    (D : Set A) (hgenerate : Dense (Algebra.adjoin ℂ D : Set A))
    (hD : ∀ a ∈ D, ∃ c : ℂ, pi a Omega = c • Omega) :
    ∀ a : A, ∃ c : ℂ, pi a Omega = c • Omega := by
  let line : Submodule ℂ H := Submodule.span ℂ {Omega}
  have hlineClosed : IsClosed (line : Set H) :=
    Submodule.closed_of_finiteDimensional line
  have hadjoin : ∀ a ∈ Algebra.adjoin ℂ D, pi a Omega ∈ line := by
    intro a ha
    obtain ⟨c, hc⟩ := scalar_on_adjoin pi Omega D hD a ha
    rw [hc]
    exact line.smul_mem c (Submodule.mem_span_singleton_self Omega)
  have hallMem : ∀ a : A, pi a Omega ∈ line := by
    intro a
    refine hgenerate.denseRange_val.induction_on a
      (hlineClosed.preimage (continuous_orbit pi Omega)) ?_
    exact fun b => hadjoin b b.property
  intro a
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp (hallMem a)
  exact ⟨c, hc.symm⟩

/-- A dense cyclic orbit contained in the scalar line through `Omega` forces
the entire Hilbert carrier to be that line. -/
theorem cyclic_scalar_orbit_one_dimensional
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H)
    (hcyclic : DenseRange fun a : A => pi a Omega)
    (hscalar : ∀ a : A, ∃ c : ℂ, pi a Omega = c • Omega) :
    ∀ x : H, ∃ c : ℂ, x = c • Omega := by
  let line : Submodule ℂ H := Submodule.span ℂ {Omega}
  have hlineClosed : IsClosed (line : Set H) :=
    Submodule.closed_of_finiteDimensional line
  have horbit : Set.range (fun a : A => pi a Omega) ⊆ line := by
    rintro _ ⟨a, rfl⟩
    obtain ⟨c, hc⟩ := hscalar a
    change pi a Omega ∈ line
    rw [hc]
    exact line.smul_mem c (Submodule.mem_span_singleton_self Omega)
  intro x
  have hx : x ∈ line :=
    closure_minimal horbit hlineClosed (hcyclic x)
  obtain ⟨c, hc⟩ := Submodule.mem_span_singleton.mp hx
  exact ⟨c, hc.symm⟩

/-- Once every represented observable acts scalarly on the cyclic vector,
the normalized positive functional is multiplicative and hence is a
character. -/
theorem character_of_scalar_cyclic_action
    (phi : A →ₚ[ℂ] ℂ) (hphi_one : phi 1 = 1)
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H)
    (hstate : ∀ a : A, phi a = ⟪Omega, pi a Omega⟫_ℂ)
    (hscalar : ∀ a : A, pi a Omega = phi a • Omega) :
    ∃ chi : A →ₐ[ℂ] ℂ, ∀ a, chi a = phi a := by
  have hmul : ∀ a b : A, phi (a * b) = phi a * phi b := by
    intro a b
    calc
      phi (a * b) = ⟪Omega, pi (a * b) Omega⟫_ℂ := hstate (a * b)
      _ = ⟪Omega, pi a (pi b Omega)⟫_ℂ := by
        rw [map_mul]
        rfl
      _ = ⟪Omega, pi a (phi b • Omega)⟫_ℂ := by rw [hscalar b]
      _ = ⟪Omega, phi b • pi a Omega⟫_ℂ := by rw [map_smul]
      _ = phi b * ⟪Omega, pi a Omega⟫_ℂ := inner_smul_right _ _ _
      _ = phi a * phi b := by rw [← hstate a, mul_comm]
  let chi : A →ₐ[ℂ] ℂ :=
    { toFun := phi
      map_zero' := map_zero phi
      map_add' := map_add phi
      commutes' := fun c => by
        rw [Algebra.algebraMap_eq_smul_one, map_smul, hphi_one,
          smul_eq_mul, mul_one]
        simp
      map_one' := hphi_one
      map_mul' := hmul }
  exact ⟨chi, fun _ => rfl⟩

/-- The complete density/cyclicity discharge used after the Hilbert-space
variance identity: a determining panel with zero deviations makes the GNS
carrier one-dimensional and the state a character. -/
theorem determining_panel_zero_forces_one_dimensional_character
    (phi : A →ₚ[ℂ] ℂ) (hphi_one : phi 1 = 1)
    (pi : A →⋆ₐ[ℂ] (H →L[ℂ] H)) (Omega : H)
    (hOmega : ⟪Omega, Omega⟫_ℂ = 1)
    (hstate : ∀ a : A, phi a = ⟪Omega, pi a Omega⟫_ℂ)
    (hcyclic : DenseRange fun a : A => pi a Omega)
    (D : Set A) (hgenerate : Dense (Algebra.adjoin ℂ D : Set A))
    (hzero : ∀ a ∈ D, pi a Omega = phi a • Omega) :
    (∀ x : H, ∃ c : ℂ, x = c • Omega) ∧
      ∃ chi : A →ₐ[ℂ] ℂ, ∀ a, chi a = phi a := by
  have hallExists := scalar_on_all_of_dense_adjoin pi Omega D hgenerate
    (fun a ha => ⟨phi a, hzero a ha⟩)
  have hall : ∀ a : A, pi a Omega = phi a • Omega := by
    intro a
    obtain ⟨c, hc⟩ := hallExists a
    have hcoeff : phi a = c := by
      calc
        phi a = ⟪Omega, pi a Omega⟫_ℂ := hstate a
        _ = ⟪Omega, c • Omega⟫_ℂ := by rw [hc]
        _ = c * ⟪Omega, Omega⟫_ℂ := inner_smul_right _ _ _
        _ = c := by rw [hOmega, mul_one]
    rw [hc, hcoeff]
  exact ⟨cyclic_scalar_orbit_one_dimensional pi Omega hcyclic
      hallExists,
    character_of_scalar_cyclic_action phi hphi_one pi Omega hstate hall⟩

/-! ## Instantiation for Mathlib's actual GNS construction -/

/-- The canonical cyclic vector in Mathlib's GNS completion. -/
def gnsCyclicVector (phi : A →ₚ[ℂ] ℂ) : phi.GNS :=
  (phi.toPreGNS 1 : phi.GNS)

/-- Acting on the canonical cyclic vector is the dense GNS embedding of the
observable itself. -/
theorem gnsStarAlgHom_apply_cyclicVector (phi : A →ₚ[ℂ] ℂ) (a : A) :
    phi.gnsStarAlgHom a (gnsCyclicVector phi) =
      (phi.toPreGNS a : phi.GNS) := by
  change phi.gnsNonUnitalStarAlgHom a
      (phi.toPreGNS 1 : phi.GNS) = (phi.toPreGNS a : phi.GNS)
  rw [PositiveLinearMap.gnsNonUnitalStarAlgHom_apply_coe]
  congr 1
  change phi.toPreGNS (a * 1) = phi.toPreGNS a
  rw [mul_one]

/-- The canonical GNS orbit is dense, rather than merely declared cyclic. -/
theorem gnsCyclicVector_denseRange (phi : A →ₚ[ℂ] ℂ) :
    DenseRange fun a : A => phi.gnsStarAlgHom a (gnsCyclicVector phi) := by
  have hdense : DenseRange
      ((↑) : phi.PreGNS → phi.GNS) :=
    UniformSpace.Completion.denseRange_coe
  have hcomp : DenseRange
      (((↑) : phi.PreGNS → phi.GNS) ∘ phi.toPreGNS) :=
    hdense.comp phi.toPreGNS.surjective.denseRange
      (UniformSpace.Completion.continuous_coe phi.PreGNS)
  simp only [gnsStarAlgHom_apply_cyclicVector]
  change DenseRange (UniformSpace.Completion.coe' ∘ phi.toPreGNS)
  exact hcomp

/-- The normalized functional is exactly the vector state of the canonical
GNS cyclic vector. -/
theorem gnsCyclicVector_state (phi : A →ₚ[ℂ] ℂ) (a : A) :
    phi a = ⟪gnsCyclicVector phi,
      phi.gnsStarAlgHom a (gnsCyclicVector phi)⟫_ℂ := by
  rw [gnsStarAlgHom_apply_cyclicVector]
  change phi a = ⟪(phi.toPreGNS 1 : phi.GNS),
    (phi.toPreGNS a : phi.GNS)⟫_ℂ
  rw [UniformSpace.Completion.inner_coe,
    PositiveLinearMap.preGNS_inner_def]
  simp

/-- A normalized positive functional gives a unit canonical GNS vector. -/
theorem gnsCyclicVector_inner_self (phi : A →ₚ[ℂ] ℂ)
    (hphi_one : phi 1 = 1) :
    ⟪gnsCyclicVector phi, gnsCyclicVector phi⟫_ℂ = 1 := by
  have h := gnsCyclicVector_state phi 1
  simpa [hphi_one] using h.symm

/-- Exact GNS specialization of the density theorem. -/
theorem gns_determining_panel_zero_forces_one_dimensional_character
    (phi : A →ₚ[ℂ] ℂ) (hphi_one : phi 1 = 1)
    (D : Set A) (hgenerate : Dense (Algebra.adjoin ℂ D : Set A))
    (hzero : ∀ a ∈ D,
      phi.gnsStarAlgHom a (gnsCyclicVector phi) =
        phi a • gnsCyclicVector phi) :
    (∀ x : phi.GNS, ∃ c : ℂ, x = c • gnsCyclicVector phi) ∧
      ∃ chi : A →ₐ[ℂ] ℂ, ∀ a, chi a = phi a := by
  exact determining_panel_zero_forces_one_dimensional_character
    phi hphi_one phi.gnsStarAlgHom (gnsCyclicVector phi)
    (gnsCyclicVector_inner_self phi hphi_one)
    (gnsCyclicVector_state phi) (gnsCyclicVector_denseRange phi)
    D hgenerate hzero

end NCG.OperationalTrivialityGNS
