/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Algebra.JordanWigner

/-!
# Pauli edge normal-current frame

One qubit is assigned to each edge of a finite one-skeleton.  This file proves
that the two endpoint Pauli axes generate the full parallel-edge matrix
algebra, that their joint commutant is scalar, and that the resulting `Z` edge
currents form an orthonormal family for the product normalized trace.
-/

open Matrix

namespace NCG

open CommonOrigin

variable {m : ℕ}

/-- The two protected endpoint axes on edge `j`. -/
def edgeEndpointAxis (q : Fin m × Bool) :
    Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  slotEmbed q.1 (if q.2 then pauli2 else pauli1)

/-- Multiplication inside one tensor slot is ordinary matrix multiplication. -/
theorem slotEmbed_mul_same (j : Fin m)
    (A B : Matrix (Fin 2) (Fin 2) ℂ) :
    slotEmbed j A * slotEmbed j B = slotEmbed j (A * B) := by
  rw [slotEmbed, slotEmbed, slotEmbed, piKron_mul]
  congr 1
  funext k
  by_cases h : k = j
  · subst k
    simp
  · simp [Function.update_of_ne h]

/-- Every one-slot Pauli matrix belongs to the algebra generated by the two
endpoint axes on all edges. -/
theorem slotPauli_mem_edgeEndpointAxis_adjoin (j : Fin m) (p : Fin 4) :
    slotEmbed j (pauli4 p) ∈
      Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m))) := by
  classical
  let S := Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m)))
  have hX : slotEmbed j pauli1 ∈ S := by
    exact Algebra.subset_adjoin ⟨(j, false), by simp [edgeEndpointAxis]⟩
  have hY : slotEmbed j pauli2 ∈ S := by
    exact Algebra.subset_adjoin ⟨(j, true), by simp [edgeEndpointAxis]⟩
  have hZ : slotEmbed j pauli3 ∈ S := by
    have hXY : slotEmbed j pauli1 * slotEmbed j pauli2
        = Complex.I • slotEmbed j pauli3 := by
      rw [slotEmbed_mul_same, pauli12_eq_I_pauli3,
        slotEmbed_smul]
    have hm : slotEmbed j pauli1 * slotEmbed j pauli2 ∈ S :=
      mul_mem hX hY
    have hscale : slotEmbed j pauli3 =
        (-Complex.I) • (slotEmbed j pauli1 * slotEmbed j pauli2) := by
      rw [hXY, smul_smul]
      norm_num [Complex.I_mul_I]
    rw [hscale]
    exact S.smul_mem hm (-Complex.I)
  fin_cases p
  · change slotEmbed j (1 : Matrix (Fin 2) (Fin 2) ℂ) ∈ S
    rw [slotEmbed, Function.update_eq_self, piKron_one]
    exact one_mem S
  · exact hX
  · exact hY
  · exact hZ

/-- Every Pauli word belongs to the endpoint-axis algebra. -/
theorem pauliWord_mem_edgeEndpointAxis_adjoin (w : Fin m → Fin 4) :
    pauliWord w ∈
      Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m))) := by
  classical
  have hprod := noncommProd_slotEmbed Finset.univ
    (fun j => pauli4 (w j))
    (fun j _ k _ hjk => slotEmbed_commute hjk _ _)
  have hword : pauliWord w = piKron (fun j =>
      if j ∈ (Finset.univ : Finset (Fin m)) then pauli4 (w j) else 1) := by
    rw [pauliWord]
    congr 1
    funext j
    simp
  rw [hword, ← hprod]
  exact Submonoid.noncommProd_mem
    (Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m)))).toSubsemiring.toSubmonoid
    _ _ _ (fun j _ => slotPauli_mem_edgeEndpointAxis_adjoin j (w j))

/-- The endpoint axes generate the complete minimal parallel-edge factor. -/
theorem edgeEndpointAxes_generate_fullMatrix :
    Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m))) = ⊤ := by
  rw [eq_top_iff]
  intro X _
  have hspan : Submodule.span ℂ (Set.range (pauliWord (m := m))) ≤
      Subalgebra.toSubmodule
        (Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m)))) := by
    rw [Submodule.span_le]
    rintro Z ⟨w, rfl⟩
    exact pauliWord_mem_edgeEndpointAxis_adjoin w
  apply hspan
  rw [pauliWord_span]
  exact Submodule.mem_top

/-- Endpoint-resolved normal densities with nonzero incidence coefficients
still generate the complete edge factor. -/
def scaledEdgeEndpointDensity (lambda : Fin m × Bool → ℝ)
    (q : Fin m × Bool) :
    Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  (lambda q : ℂ) • edgeEndpointAxis q

theorem nonzeroEdgeEndpointDensities_generate_fullMatrix
    (lambda : Fin m × Bool → ℝ) (hlambda : ∀ q, lambda q ≠ 0) :
    Algebra.adjoin ℂ
      (Set.range (scaledEdgeEndpointDensity (m := m) lambda)) = ⊤ := by
  classical
  have haxis : ∀ q, edgeEndpointAxis q ∈ Algebra.adjoin ℂ
      (Set.range (scaledEdgeEndpointDensity (m := m) lambda)) := by
    intro q
    have hscaled : scaledEdgeEndpointDensity lambda q ∈ Algebra.adjoin ℂ
        (Set.range (scaledEdgeEndpointDensity (m := m) lambda)) :=
      Algebra.subset_adjoin ⟨q, rfl⟩
    have hcast : (lambda q : ℂ) ≠ 0 := by exact_mod_cast hlambda q
    have heq : edgeEndpointAxis q =
        (lambda q : ℂ)⁻¹ • scaledEdgeEndpointDensity lambda q := by
      rw [scaledEdgeEndpointDensity, smul_smul,
        inv_mul_cancel₀ hcast, one_smul]
    rw [heq]
    exact (Algebra.adjoin ℂ
      (Set.range (scaledEdgeEndpointDensity (m := m) lambda))).smul_mem
        hscaled (lambda q : ℂ)⁻¹
  have hle : Algebra.adjoin ℂ (Set.range (edgeEndpointAxis (m := m))) ≤
      Algebra.adjoin ℂ
        (Set.range (scaledEdgeEndpointDensity (m := m) lambda)) := by
    rw [Algebra.adjoin_le_iff]
    rintro X ⟨q, rfl⟩
    exact haxis q
  rw [edgeEndpointAxes_generate_fullMatrix] at hle
  exact top_unique hle

/-- On the minimal parallel-edge carrier, the endpoint-axis algebra has scalar
commutant. -/
theorem edgeEndpointAxes_commutant_is_scalar
    (X : Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ)
    (hX : ∀ q, Commute (edgeEndpointAxis q) X) :
    ∃ c : ℂ, X = c • 1 := by
  classical
  have hcentral : Algebra.adjoin ℂ
      (Set.range (edgeEndpointAxis (m := m))) ≤
      Subalgebra.centralizer ℂ {X} := by
    rw [Algebra.adjoin_le_iff]
    rintro Z ⟨q, rfl⟩
    rw [SetLike.mem_coe, Subalgebra.mem_centralizer_iff]
    rintro Y hY
    rw [Set.mem_singleton_iff] at hY
    subst Y
    exact (hX q).symm
  rw [edgeEndpointAxes_generate_fullMatrix] at hcentral
  have hsingle : ∀ i j : Fin m → Fin 2,
      Commute (Matrix.single i j (1 : ℂ)) X := by
    intro i j
    have hm := hcentral (show Matrix.single i j (1 : ℂ) ∈
      (⊤ : Subalgebra ℂ (Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ)) by trivial)
    rw [Subalgebra.mem_centralizer_iff] at hm
    exact (hm X (Set.mem_singleton X)).symm
  obtain ⟨c, hc⟩ := Matrix.mem_range_scalar_iff_commute_single'.mpr hsingle
  refine ⟨c, ?_⟩
  rw [← hc]
  ext f g
  rw [Matrix.scalar_apply, Matrix.smul_apply, Matrix.one_apply,
    Matrix.diagonal_apply, smul_eq_mul]
  by_cases hfg : f = g <;> simp [hfg]

/-- The Pauli `Z` current on one edge. -/
def edgePauliZ (j : Fin m) :
    Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  slotEmbed j pauli3

/-- The word label of a single-edge `Z` current. -/
def edgePauliZWord (j : Fin m) : Fin m → Fin 4 :=
  Function.update (fun _ => 0) j 3

theorem pauliWord_edgePauliZWord (j : Fin m) :
    pauliWord (edgePauliZWord j) = edgePauliZ j := by
  rw [pauliWord, edgePauliZ, slotEmbed]
  congr 1
  funext k
  by_cases h : k = j
  · subst k
    simp [edgePauliZWord, pauli4]
  · simp [edgePauliZWord, pauli4, Function.update_of_ne h]

/-- Distinct edge-current labels are distinct. -/
theorem edgePauliZWord_ne {j k : Fin m} (hjk : j ≠ k) :
    edgePauliZWord j ≠ edgePauliZWord k := by
  intro h
  have hj := congrFun h j
  have hjj : edgePauliZWord j j = 3 := by simp [edgePauliZWord]
  have hkj : edgePauliZWord k j = 0 := by simp [edgePauliZWord, hjk]
  rw [hjj, hkj] at hj
  omega

/-- Distinct edge currents are trace orthogonal. -/
theorem edgePauliZ_trace_orthogonal {j k : Fin m} (hjk : j ≠ k) :
    (edgePauliZ j * edgePauliZ k).trace = 0 := by
  rw [← pauliWord_edgePauliZWord j, ← pauliWord_edgePauliZWord k,
    pauliWord_trace_mul, if_neg (edgePauliZWord_ne hjk)]

/-- Each edge current has unnormalized squared Hilbert--Schmidt norm `2^m`. -/
theorem edgePauliZ_trace_square (j : Fin m) :
    (edgePauliZ j * edgePauliZ j).trace = (2 : ℂ) ^ m := by
  rw [← pauliWord_edgePauliZWord j, pauliWord_trace_mul, if_pos rfl]

/-- Product-normalized Hilbert--Schmidt pairing. -/
noncomputable def productNormalizedHilbertSchmidt
    (A B : Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ) : ℂ :=
  ((2 : ℂ) ^ m)⁻¹ * (Aᴴ * B).trace

theorem edgePauliZ_hermitian (j : Fin m) : (edgePauliZ j)ᴴ = edgePauliZ j := by
  rw [edgePauliZ, slotEmbed, piKron_conjTranspose]
  congr 1
  funext k
  by_cases h : k = j
  · subst k
    simp [pauli3_herm]
  · simp [Function.update_of_ne h]

/-- Scaled currents on distinct edges are orthogonal for the normalized
product trace. -/
theorem scaledEdgePauliZ_normalized_orthogonal
    {j k : Fin m} (hjk : j ≠ k) (c d : ℂ) :
    productNormalizedHilbertSchmidt (c • edgePauliZ j)
      (d • edgePauliZ k) = 0 := by
  rw [productNormalizedHilbertSchmidt, Matrix.conjTranspose_smul,
    edgePauliZ_hermitian, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.trace_smul, Matrix.trace_smul,
    edgePauliZ_trace_orthogonal hjk]
  simp

/-- A real-scaled edge current has normalized squared norm equal to the square
of its coefficient. -/
theorem realScaledEdgePauliZ_normalized_square (j : Fin m) (c : ℝ) :
    productNormalizedHilbertSchmidt ((c : ℂ) • edgePauliZ j)
      ((c : ℂ) • edgePauliZ j) = (c ^ 2 : ℝ) := by
  rw [productNormalizedHilbertSchmidt, Matrix.conjTranspose_smul,
    edgePauliZ_hermitian, Matrix.smul_mul, Matrix.mul_smul,
    Matrix.trace_smul, Matrix.trace_smul, edgePauliZ_trace_square]
  push_cast
  have hpow : (2 : ℂ) ^ m ≠ 0 := pow_ne_zero _ (by norm_num)
  field_simp
  norm_num
  ring

/-- The protected `X` and `Y` axes on one edge close onto its `Z` current. -/
theorem edgePauliXY_commutator (j : Fin m) :
    slotEmbed j pauli1 * slotEmbed j pauli2 -
      slotEmbed j pauli2 * slotEmbed j pauli1 =
    (2 * Complex.I) • edgePauliZ j := by
  rw [slotEmbed_mul_same, slotEmbed_mul_same,
    pauli12_eq_I_pauli3, pauli21_anticomm, pauli12_eq_I_pauli3]
  rw [show -(Complex.I • pauli3) = (-Complex.I) • pauli3 by module,
    slotEmbed_smul, slotEmbed_smul, edgePauliZ]
  module

/-- The contribution of one edge to a smeared normal Hamiltonian. -/
def edgeNormalHamiltonianTerm
    (src dst : Fin m → V) (lambdaSrc lambdaDst : Fin m → ℝ)
    (N : V → ℝ) (e : Fin m) :
    Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  ((N (src e) * lambdaSrc e : ℝ) : ℂ) • slotEmbed e pauli1 +
    ((N (dst e) * lambdaDst e : ℝ) : ℂ) • slotEmbed e pauli2

/-- Terms supported on different edge factors commute. -/
theorem edgeNormalHamiltonianTerm_commute_distinct
    {src dst : Fin m → V} {lambdaSrc lambdaDst : Fin m → ℝ}
    (N M : V → ℝ) {e f : Fin m} (hef : e ≠ f) :
    Commute
      (edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e)
      (edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst M f) := by
  have hXX := slotEmbed_commute hef pauli1 pauli1
  have hXY := slotEmbed_commute hef pauli1 pauli2
  have hYX := slotEmbed_commute hef pauli2 pauli1
  have hYY := slotEmbed_commute hef pauli2 pauli2
  change edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e *
      edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst M f =
    edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst M f *
      edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e
  simp only [edgeNormalHamiltonianTerm, Matrix.add_mul, Matrix.mul_add,
    Matrix.smul_mul, Matrix.mul_smul]
  rw [hXX.eq, hXY.eq, hYX.eq, hYY.eq]
  simp only [mul_comm]
  module

/-- A double commutator sum localizes to equal indices when all unequal-index
terms commute. -/
theorem commutator_sum_localizes
    {ι n : Type*} [Fintype ι] [Fintype n]
    (A B : ι → Matrix n n ℂ)
    (hoff : ∀ i j, i ≠ j → Commute (A i) (B j)) :
    (∑ i, A i) * (∑ j, B j) - (∑ j, B j) * (∑ i, A i) =
      ∑ i, (A i * B i - B i * A i) := by
  have hAB : (∑ i, A i) * (∑ j, B j) = ∑ i, ∑ j, A i * B j := by
    rw [Finset.sum_mul]
    apply Finset.sum_congr rfl
    intro i _
    rw [Finset.mul_sum]
  have hBA : (∑ j, B j) * (∑ i, A i) = ∑ j, ∑ i, B j * A i := by
    rw [Finset.sum_mul]
    apply Finset.sum_congr rfl
    intro j _
    rw [Finset.mul_sum]
  rw [hAB, hBA, Finset.sum_comm (f := fun j i => B j * A i),
    ← Finset.sum_sub_distrib]
  apply Finset.sum_congr rfl
  intro i _
  rw [← Finset.sum_sub_distrib]
  apply Finset.sum_eq_single i
  · intro j _ hji
    exact sub_eq_zero.mpr (hoff i j (Ne.symm hji)).eq
  · intro hi
    exact absurd (Finset.mem_univ i) hi

/-- Algebraic commutator of two linear combinations of two operators. -/
theorem twoAxis_linearCombination_commutator
    {n : Type*} [Fintype n] (A B : Matrix n n ℂ) (a b c d : ℂ) :
    (a • A + b • B) * (c • A + d • B) -
        (c • A + d • B) * (a • A + b • B) =
      (a * d - c * b) • (A * B - B * A) := by
  simp only [Matrix.add_mul, Matrix.mul_add, Matrix.smul_mul,
    Matrix.mul_smul, smul_sub]
  module

/-- The same-edge commutator has exactly the antisymmetric lapse coefficient. -/
theorem edgeNormalHamiltonianTerm_same_commutator
    (src dst : Fin m → V) (lambdaSrc lambdaDst : Fin m → ℝ)
    (N M : V → ℝ) (e : Fin m) :
    edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e *
        edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst M e -
      edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst M e *
        edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e =
    (((N (src e) * M (dst e) - M (src e) * N (dst e)) *
        lambdaSrc e * lambdaDst e : ℝ) : ℂ) •
      ((2 * Complex.I) • edgePauliZ e) := by
  rw [edgeNormalHamiltonianTerm, edgeNormalHamiltonianTerm,
    twoAxis_linearCombination_commutator, edgePauliXY_commutator]
  congr 1
  push_cast
  ring

/-- Smeared normal Hamiltonian assembled from the edge-local endpoint axes. -/
def edgeNormalHamiltonian
    (src dst : Fin m → V) (lambdaSrc lambdaDst : Fin m → ℝ)
    (N : V → ℝ) : Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  ∑ e, edgeNormalHamiltonianTerm src dst lambdaSrc lambdaDst N e

/-- The physical `-ih` current on edge `e`. -/
def pauliNormalEdgeCurrent (h : ℝ)
    (lambdaSrc lambdaDst : Fin m → ℝ) (e : Fin m) :
    Matrix (Fin m → Fin 2) (Fin m → Fin 2) ℂ :=
  ((2 * h * lambdaSrc e * lambdaDst e : ℝ) : ℂ) • edgePauliZ e

/-- Exact smeared-bracket formula.  The displayed discrete derivative form
`N_x(M_y-M_x)-M_x(N_y-N_x)` is algebraically the coefficient used here. -/
theorem pauliEdgeNormalHamiltonian_smearedBracket
    (src dst : Fin m → V) (lambdaSrc lambdaDst : Fin m → ℝ)
    (N M : V → ℝ) (h : ℝ) :
    (-(Complex.I * h)) •
      (edgeNormalHamiltonian src dst lambdaSrc lambdaDst N *
          edgeNormalHamiltonian src dst lambdaSrc lambdaDst M -
        edgeNormalHamiltonian src dst lambdaSrc lambdaDst M *
          edgeNormalHamiltonian src dst lambdaSrc lambdaDst N) =
    ∑ e, ((N (src e) * M (dst e) - M (src e) * N (dst e) : ℝ) : ℂ) •
      pauliNormalEdgeCurrent h lambdaSrc lambdaDst e := by
  rw [edgeNormalHamiltonian, edgeNormalHamiltonian,
    commutator_sum_localizes]
  · rw [Finset.smul_sum]
    apply Finset.sum_congr rfl
    intro e _
    rw [edgeNormalHamiltonianTerm_same_commutator]
    simp only [pauliNormalEdgeCurrent, smul_smul]
    congr 1
    push_cast
    ring_nf
    rw [show Complex.I ^ 2 = (-1 : ℂ) by
      rw [pow_two, Complex.I_mul_I]]
    ring
  · intro e f hef
    exact edgeNormalHamiltonianTerm_commute_distinct N M hef

/-- The current norm is the manuscript coefficient square. -/
theorem pauliNormalEdgeCurrent_normalized_square
    (h : ℝ) (lambdaSrc lambdaDst : Fin m → ℝ) (e : Fin m) :
    productNormalizedHilbertSchmidt
        (pauliNormalEdgeCurrent h lambdaSrc lambdaDst e)
        (pauliNormalEdgeCurrent h lambdaSrc lambdaDst e) =
      ((2 * h * lambdaSrc e * lambdaDst e) ^ 2 : ℝ) := by
  exact realScaledEdgePauliZ_normalized_square e _

end NCG
