/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.ScoreBank

/-!
# Conditional exponential geometry of the primitive score bank

This module supplies the probabilistic clauses of
`thm:primitive-score-bank`.  It works directly with the five resolved
outcomes, their two current-phase rows, and their two next phases.
-/

open Filter Matrix Set Topology

namespace NCG

/-- Current phase of each resolved primitive outcome. -/
def primitiveCurrentPhase : Fin 5 → Fin 2 := ![0, 0, 1, 1, 1]

/-- Next phase of each resolved primitive outcome. -/
def primitiveNextPhase : Fin 5 → Fin 2 := ![0, 1, 1, 0, 0]

/-- Baseline conditional probability of a resolved outcome given its row. -/
noncomputable def primitiveConditionalProbability : Fin 5 → ℝ :=
  ![1 / 5, 4 / 5, 1 / 3, 1 / 3, 1 / 3]

/-- The two row-centering equations defining branch-local tangent scores. -/
def PrimitiveRowCentered (f : Fin 5 → ℝ) : Prop :=
  (1 / 5 : ℝ) * f 0 + (4 / 5) * f 1 = 0 ∧
    (1 / 3 : ℝ) * f 2 + (1 / 3) * f 3 + (1 / 3) * f 4 = 0

theorem primitiveRowCentered_scoreBank :
    PrimitiveRowCentered scoreUH ∧ PrimitiveRowCentered scoreUP ∧
      PrimitiveRowCentered scoreUE := by
  rcases primitive_score_bank with ⟨_, hcenter, _⟩
  exact ⟨⟨hcenter.1, by simp [scoreUH]⟩,
    ⟨by simp [scoreUP], hcenter.2.1⟩,
    ⟨by simp [scoreUE], hcenter.2.2⟩⟩

/-- Differentiating conditional normalization forces the score into the
row-centered tangent space. -/
theorem score_rowCentered_of_normalized_curve
    (p : ℝ → Fin 5 → ℝ) (f : Fin 5 → ℝ)
    (hnormH : ∀ t, p t 0 + p t 1 = 1)
    (hnormP : ∀ t, p t 2 + p t 3 + p t 4 = 1)
    (hscore : ∀ a, HasDerivAt (fun t ↦ p t a)
      (primitiveConditionalProbability a * f a) 0) :
    PrimitiveRowCentered f := by
  have hdH : primitiveConditionalProbability 0 * f 0 +
      primitiveConditionalProbability 1 * f 1 = 0 := by
    have hfun : (fun t ↦ p t 0 + p t 1) = (fun _ ↦ (1 : ℝ)) := funext hnormH
    have hd := congrArg (fun q : ℝ → ℝ ↦ deriv q 0) hfun
    change deriv ((fun t ↦ p t 0) + (fun t ↦ p t 1)) 0 =
      deriv (fun _ ↦ (1 : ℝ)) 0 at hd
    rw [deriv_add (hscore 0).differentiableAt (hscore 1).differentiableAt,
      (hscore 0).deriv, (hscore 1).deriv, deriv_const] at hd
    exact hd
  have hdP : (primitiveConditionalProbability 2 * f 2 +
      primitiveConditionalProbability 3 * f 3) +
      primitiveConditionalProbability 4 * f 4 = 0 := by
    have hfun : (fun t ↦ p t 2 + p t 3 + p t 4) =
        (fun _ ↦ (1 : ℝ)) := funext hnormP
    have hd := congrArg (fun q : ℝ → ℝ ↦ deriv q 0) hfun
    change deriv (((fun t ↦ p t 2) + (fun t ↦ p t 3)) +
      (fun t ↦ p t 4)) 0 = deriv (fun _ ↦ (1 : ℝ)) 0 at hd
    rw [deriv_add ((hscore 2).add (hscore 3)).differentiableAt
        (hscore 4).differentiableAt,
      deriv_add (hscore 2).differentiableAt (hscore 3).differentiableAt,
      (hscore 2).deriv, (hscore 3).deriv, (hscore 4).deriv, deriv_const] at hd
    exact hd
  constructor
  · norm_num [primitiveConditionalProbability] at hdH ⊢
    exact hdH
  · norm_num [primitiveConditionalProbability] at hdP ⊢
    exact hdP

/-- Row partition function for a one-parameter conditional exponential tilt. -/
noncomputable def primitiveRowPartition (f : Fin 5 → ℝ) (t : ℝ) : Fin 2 → ℝ :=
  ![(1 / 5) * Real.exp (t * f 0) + (4 / 5) * Real.exp (t * f 1),
    (1 / 3) * Real.exp (t * f 2) + (1 / 3) * Real.exp (t * f 3) +
      (1 / 3) * Real.exp (t * f 4)]

/-- The normalized one-parameter conditional exponential family generated by
a branch score `f`. -/
noncomputable def primitiveExponentialProbability (f : Fin 5 → ℝ)
    (t : ℝ) (a : Fin 5) : ℝ :=
  primitiveConditionalProbability a * Real.exp (t * f a) /
    primitiveRowPartition f t (primitiveCurrentPhase a)

theorem primitiveRowPartition_pos (f : Fin 5 → ℝ) (t : ℝ) (x : Fin 2) :
    0 < primitiveRowPartition f t x := by
  fin_cases x <;> simp [primitiveRowPartition] <;> positivity

/-- Conditional exponential tilts stay normalized on both current-phase
rows, for every parameter value. -/
theorem primitiveExponentialProbability_normalized (f : Fin 5 → ℝ) (t : ℝ) :
    primitiveExponentialProbability f t 0 + primitiveExponentialProbability f t 1 = 1 ∧
      primitiveExponentialProbability f t 2 + primitiveExponentialProbability f t 3 +
        primitiveExponentialProbability f t 4 = 1 := by
  have hH := (primitiveRowPartition_pos f t 0).ne'
  have hP := (primitiveRowPartition_pos f t 1).ne'
  constructor <;>
    simp [primitiveExponentialProbability, primitiveConditionalProbability,
      primitiveCurrentPhase, primitiveRowPartition, hH, hP] <;> field_simp <;> ring

theorem primitiveRowPartition_zero (f : Fin 5 → ℝ) (x : Fin 2) :
    primitiveRowPartition f 0 x = 1 := by
  fin_cases x <;> norm_num [primitiveRowPartition]

private theorem primitiveExp_differentiable_deriv (c : ℝ) :
    DifferentiableAt ℝ (fun t : ℝ ↦ Real.exp (t * c)) 0 ∧
      deriv (fun t : ℝ ↦ Real.exp (t * c)) 0 = c := by
  have h := (Real.hasDerivAt_exp (0 * c)).comp 0
    ((hasDerivAt_id 0).mul_const c)
  have hdiff := h.differentiableAt
  have hd := h.deriv
  change DifferentiableAt ℝ (fun t : ℝ ↦ Real.exp (t * c)) 0 at hdiff
  change deriv (fun t : ℝ ↦ Real.exp (t * c)) 0 =
    Real.exp (0 * c) * (1 * c) at hd
  exact ⟨hdiff, by simpa using hd⟩

theorem primitiveRowPartition_differentiable_deriv_zero {f : Fin 5 → ℝ}
    (hf : PrimitiveRowCentered f) (x : Fin 2) :
    DifferentiableAt ℝ (fun t ↦ primitiveRowPartition f t x) 0 ∧
      deriv (fun t ↦ primitiveRowPartition f t x) 0 = 0 := by
  fin_cases x
  ·
    have h0 := primitiveExp_differentiable_deriv (f 0)
    have h1 := primitiveExp_differentiable_deriv (f 1)
    have hd0 : DifferentiableAt ℝ (fun y : ℝ ↦ Real.exp (y * f 0)) 0 := h0.1
    have hd1 : DifferentiableAt ℝ (fun y : ℝ ↦ Real.exp (y * f 1)) 0 := h1.1
    constructor
    · change DifferentiableAt ℝ
        (fun t ↦ (1 / 5 : ℝ) * Real.exp (t * f 0) +
          (4 / 5 : ℝ) * Real.exp (t * f 1)) 0
      exact (hd0.const_mul _).add (hd1.const_mul _)
    · change deriv ((fun t ↦ (1 / 5 : ℝ) * Real.exp (t * f 0)) +
          (fun t ↦ (4 / 5 : ℝ) * Real.exp (t * f 1))) 0 = 0
      rw [deriv_add (hd0.const_mul _) (hd1.const_mul _),
        deriv_const_mul_field, deriv_const_mul_field, h0.2, h1.2]
      exact hf.1
  ·
    have h2 := primitiveExp_differentiable_deriv (f 2)
    have h3 := primitiveExp_differentiable_deriv (f 3)
    have h4 := primitiveExp_differentiable_deriv (f 4)
    have hd2 : DifferentiableAt ℝ (fun y : ℝ ↦ Real.exp (y * f 2)) 0 := h2.1
    have hd3 : DifferentiableAt ℝ (fun y : ℝ ↦ Real.exp (y * f 3)) 0 := h3.1
    have hd4 : DifferentiableAt ℝ (fun y : ℝ ↦ Real.exp (y * f 4)) 0 := h4.1
    constructor
    · change DifferentiableAt ℝ
        (fun t ↦ ((1 / 3 : ℝ) * Real.exp (t * f 2) +
          (1 / 3 : ℝ) * Real.exp (t * f 3)) +
          (1 / 3 : ℝ) * Real.exp (t * f 4)) 0
      exact ((hd2.const_mul _).add (hd3.const_mul _)).add (hd4.const_mul _)
    · change deriv (((fun t ↦ (1 / 3 : ℝ) * Real.exp (t * f 2)) +
          (fun t ↦ (1 / 3 : ℝ) * Real.exp (t * f 3))) +
          (fun t ↦ (1 / 3 : ℝ) * Real.exp (t * f 4))) 0 = 0
      rw [deriv_add ((hd2.const_mul _).add (hd3.const_mul _))
          (hd4.const_mul _),
        deriv_add (hd2.const_mul _) (hd3.const_mul _),
        deriv_const_mul_field, deriv_const_mul_field, deriv_const_mul_field,
        h2.2, h3.2, h4.2]
      exact hf.2

/-- Every row-centered direction is realized as the score of its normalized
conditional exponential family. -/
theorem primitiveExponentialProbability_hasScore {f : Fin 5 → ℝ}
    (hf : PrimitiveRowCentered f) (a : Fin 5) :
    DifferentiableAt ℝ (fun t ↦ primitiveExponentialProbability f t a) 0 ∧
      deriv (fun t ↦ primitiveExponentialProbability f t a) 0 =
        primitiveConditionalProbability a * f a := by
  have hexp := primitiveExp_differentiable_deriv (f a)
  have hnum : DifferentiableAt ℝ
      (fun t ↦ primitiveConditionalProbability a * Real.exp (t * f a)) 0 :=
    hexp.1.const_mul _
  have hden := primitiveRowPartition_differentiable_deriv_zero hf
    (primitiveCurrentPhase a)
  have hden0 := primitiveRowPartition_zero f (primitiveCurrentPhase a)
  constructor
  · exact hnum.div hden.1 (by simpa [hden0])
  · unfold primitiveExponentialProbability
    change deriv
      ((fun t ↦ primitiveConditionalProbability a * Real.exp (t * f a)) /
        (fun t ↦ primitiveRowPartition f t (primitiveCurrentPhase a))) 0 =
      primitiveConditionalProbability a * f a
    rw [deriv_div hnum hden.1 (by simpa [hden0]), deriv_const_mul_field,
      hexp.2, hden.2, hden0]
    ring

/-- Exact tangent exhaustion: a function is the score of a normalized,
fixed-support conditional curve iff it is row-centered. -/
theorem normalized_fixedSupport_score_iff_rowCentered (f : Fin 5 → ℝ) :
    (∃ p : ℝ → Fin 5 → ℝ,
      (∀ t, p t 0 + p t 1 = 1) ∧
      (∀ t, p t 2 + p t 3 + p t 4 = 1) ∧
      (∀ a, HasDerivAt (fun t ↦ p t a)
        (primitiveConditionalProbability a * f a) 0)) ↔
      PrimitiveRowCentered f := by
  constructor
  · rintro ⟨p, hH, hP, hs⟩
    exact score_rowCentered_of_normalized_curve p f hH hP hs
  · intro hf
    refine ⟨primitiveExponentialProbability f,
      fun t ↦ (primitiveExponentialProbability_normalized f t).1,
      fun t ↦ (primitiveExponentialProbability_normalized f t).2, ?_⟩
    intro a
    exact (primitiveExponentialProbability_hasScore hf a).1.hasDerivAt.congr_deriv
      (primitiveExponentialProbability_hasScore hf a).2

/-- Simultaneous conditional exponential family generated by a finite bank of
row-centered directions. -/
noncomputable def primitiveFiniteExponentialProbability {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) (θ : Fin m → ℝ) (a : Fin 5) : ℝ :=
  primitiveExponentialProbability (fun b ↦ ∑ j, θ j * f j b) 1 a

theorem primitiveFiniteExponentialProbability_normalized {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) (θ : Fin m → ℝ) :
    primitiveFiniteExponentialProbability f θ 0 +
        primitiveFiniteExponentialProbability f θ 1 = 1 ∧
      primitiveFiniteExponentialProbability f θ 2 +
        primitiveFiniteExponentialProbability f θ 3 +
        primitiveFiniteExponentialProbability f θ 4 = 1 :=
  primitiveExponentialProbability_normalized _ 1

/-- Restricting the simultaneous family to its `j`th coordinate recovers the
one-parameter exponential family generated by `f j`. -/
theorem primitiveFiniteExponentialProbability_coordinate {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) (j : Fin m) (t : ℝ) (a : Fin 5) :
    primitiveFiniteExponentialProbability f (fun i ↦ if i = j then t else 0) a =
      primitiveExponentialProbability (f j) t a := by
  unfold primitiveFiniteExponentialProbability primitiveExponentialProbability
  have htilt : (fun b : Fin 5 ↦ ∑ i, (if i = j then t else 0) * f i b) =
      fun b ↦ t * f j b := by
    funext b
    simp
  rw [htilt]
  congr 1 <;>
    simp [primitiveRowPartition, mul_assoc]

/-- Hence every finite row-centered bank is realized simultaneously and its
coordinate scores are exactly the prescribed directions. -/
theorem finite_rowCentered_bank_realized {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) (hf : ∀ j, PrimitiveRowCentered (f j)) :
    (∀ θ,
      primitiveFiniteExponentialProbability f θ 0 +
          primitiveFiniteExponentialProbability f θ 1 = 1 ∧
        primitiveFiniteExponentialProbability f θ 2 +
          primitiveFiniteExponentialProbability f θ 3 +
          primitiveFiniteExponentialProbability f θ 4 = 1) ∧
    (∀ j a, deriv (fun t ↦ primitiveFiniteExponentialProbability f
        (fun i ↦ if i = j then t else 0) a) 0 =
      primitiveConditionalProbability a * f j a) := by
  constructor
  · exact primitiveFiniteExponentialProbability_normalized f
  · intro j a
    rw [show (fun t ↦ primitiveFiniteExponentialProbability f
        (fun i ↦ if i = j then t else 0) a) =
        (fun t ↦ primitiveExponentialProbability (f j) t a) by
      funext t
      exact primitiveFiniteExponentialProbability_coordinate f j t a]
    exact (primitiveExponentialProbability_hasScore (hf j) a).2

/-- The Fisher pairing at the origin of two realized tangent directions. -/
noncomputable def primitiveFisherPairing (f g : Fin 5 → ℝ) : ℝ :=
  ∑ a, scoreMu a * f a * g a

theorem primitiveFisherPairing_eq_scoreIP (f g : Fin 5 → ℝ) :
    primitiveFisherPairing f g = scoreIP f g := rfl

/-- Fisher matrix at the origin of a finite realized tangent bank. -/
noncomputable def primitiveFisherMatrix {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) : Matrix (Fin m) (Fin m) ℝ :=
  fun i j ↦ primitiveFisherPairing (f i) (f j)

theorem primitiveFisherMatrix_eq_gram {m : ℕ}
    (f : Fin m → Fin 5 → ℝ) (i j : Fin m) :
    primitiveFisherMatrix f i j = scoreIP (f i) (f j) := rfl

/-- Normalized active phase eigenfunction. -/
noncomputable def primitivePhaseMode : Fin 2 → ℝ :=
  ![-6 / Real.sqrt 30, 5 / Real.sqrt 30]

/-- Doob centering of a function of the next phase, represented on the five
resolved outcomes. -/
noncomputable def primitiveDoobInnovation (g : Fin 2 → ℝ) : Fin 5 → ℝ :=
  fun a ↦ g (primitiveNextPhase a) -
    if primitiveCurrentPhase a = 0 then
      (1 / 5 : ℝ) * g 0 + (4 / 5) * g 1
    else
      (2 / 3 : ℝ) * g 0 + (1 / 3) * g 1

/-- The active Doob innovation is nonzero and spans the image of Doob
centering on the binary next-phase space. -/
theorem primitiveDoobInnovation_rank_one (g : Fin 2 → ℝ) :
    primitiveDoobInnovation g =
      ((g 1 - g 0) * Real.sqrt 30 / 11) •
        primitiveDoobInnovation primitivePhaseMode := by
  funext a
  fin_cases a <;>
    simp [primitiveDoobInnovation, primitiveCurrentPhase, primitiveNextPhase,
      primitivePhaseMode] <;>
    field_simp [Real.sqrt_ne_zero'.mpr (by norm_num : (0 : ℝ) < 30)] <;>
    nlinarith [Real.sq_sqrt (by norm_num : (0 : ℝ) ≤ 30)]

theorem primitivePhaseMode_innovation_ne_zero :
    primitiveDoobInnovation primitivePhaseMode ≠ 0 := by
  intro h
  have h0 := congrFun h 0
  simp [primitiveDoobInnovation, primitivePhaseMode, primitiveCurrentPhase,
    primitiveNextPhase] at h0
  have hsqrt : Real.sqrt 30 > 0 := Real.sqrt_pos.2 (by norm_num)
  field_simp [ne_of_gt hsqrt] at h0
  norm_num at h0

/-- The normalized inactive rotation direction. -/
noncomputable def primitiveZeta : Fin 5 → ℝ := fun a ↦
  Real.sqrt (5 / 8) * scoreUH a - Real.sqrt (3 / 8) * scoreUP a

/-- Both inactive primitive directions have zero conditional expectation given
the next phase.  Equivalently, they are orthogonal to every function of that
next phase, which includes every later active future after the Markov
factorization through `X_{n+1}`. -/
theorem inactiveScores_orthogonal_to_nextPhase :
    (∀ g : Fin 2 → ℝ,
      scoreIP primitiveZeta (fun a ↦ g (primitiveNextPhase a)) = 0) ∧
    (∀ g : Fin 2 → ℝ,
      scoreIP scoreUE (fun a ↦ g (primitiveNextPhase a)) = 0) := by
  have hsqrt : Real.sqrt (5 / 8) * Real.sqrt (11 / 20) =
      Real.sqrt (3 / 8) * Real.sqrt (11 / 12) := by
    calc
      Real.sqrt (5 / 8) * Real.sqrt (11 / 20) =
          Real.sqrt ((5 / 8) * (11 / 20)) := by
            rw [Real.sqrt_mul (by norm_num : (0 : ℝ) ≤ 5 / 8)]
      _ = Real.sqrt ((3 / 8) * (11 / 12)) := by norm_num
      _ = Real.sqrt (3 / 8) * Real.sqrt (11 / 12) := by
            rw [Real.sqrt_mul (by norm_num : (0 : ℝ) ≤ 3 / 8)]
  have hsqrt' : Real.sqrt 5 / Real.sqrt 8 * (Real.sqrt 11 / Real.sqrt 20) =
      Real.sqrt 3 / Real.sqrt 8 * (Real.sqrt 11 / Real.sqrt 12) := by
    simpa [Real.sqrt_div (by norm_num : (0 : ℝ) ≤ 5),
      Real.sqrt_div (by norm_num : (0 : ℝ) ≤ 3),
      Real.sqrt_div (by norm_num : (0 : ℝ) ≤ 11)] using hsqrt
  constructor <;> intro g
  · simp [scoreIP, primitiveZeta, scoreUH, scoreUP, scoreMu,
      primitiveNextPhase, Fin.sum_univ_five]
    ring_nf at hsqrt' ⊢
    rw [hsqrt']
    ring
  · simp [scoreIP, scoreUE, scoreMu, primitiveNextPhase, Fin.sum_univ_five]

end NCG
