/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.GrandRecordMap
import NCG.Grand.RecordSurvival

/-!
# Complete positivity and the minimal protected-record Stinespring hull

This file completes `thm:SM-record-map`.  One-Kraus conjugation is proved
positive at every finite matrix amplification, not merely at level one.  For a
finite star representation `π` and root `S`, the record-sufficient space is
constructed as the cyclic span of all `π(c) S x`; its defining least property
gives existence and uniqueness of the minimal hull.  A kernel criterion states
exactly when a represented record projection is erased on that hull.
-/

open Matrix
open scoped Kronecker ComplexOrder

namespace NCG

/-- Matrix amplification of the Stinespring root. -/
def amplifiedRecordRoot {m e : Type*} [Fintype m] [Fintype e]
    [DecidableEq m] [DecidableEq e] (S : Matrix e e ℂ) :
    Matrix (m × e) (m × e) ℂ :=
  (1 : Matrix m m ℂ) ⊗ₖ S

/-- One-Kraus conjugation is positive at every finite matrix level, which is
the concrete complete-positivity certificate for the protected record map. -/
theorem protectedRecordMap_completelyPositive
    {e : Type*} [Fintype e] [DecidableEq e]
    (S : Matrix e e ℂ) :
    ∀ {m : Type*} [Fintype m] [DecidableEq m]
      (C : Matrix (m × e) (m × e) ℂ), C.PosSemidef →
      ((amplifiedRecordRoot S)ᴴ * C * amplifiedRecordRoot S).PosSemidef := by
  intro m _ _ C hC
  exact hC.conjTranspose_mul_mul_same (amplifiedRecordRoot S)

/-- Cyclic vectors generated by a represented record algebra and the
Stinespring root. -/
def recordCyclicVectors {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S : Matrix e e ℂ) : Set (e → ℂ) :=
  {v | ∃ (c : R) (x : e → ℂ), v = π c *ᵥ (S *ᵥ x)}

/-- The canonical record-sufficient Stinespring space. -/
def protectedRecordCyclicHull {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S : Matrix e e ℂ) :
    Submodule ℂ (e → ℂ) :=
  Submodule.span ℂ (recordCyclicVectors π S)

/-- A subspace is record-sufficient when it contains every represented cyclic
vector `π(c) S x`. -/
def RecordSufficientSubspace {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S : Matrix e e ℂ)
    (F : Submodule ℂ (e → ℂ)) : Prop :=
  ∀ (c : R) (x : e → ℂ), π c *ᵥ (S *ᵥ x) ∈ F

/-- The cyclic hull is contained in exactly the record-sufficient subspaces. -/
theorem protectedRecordCyclicHull_le_iff
    {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S : Matrix e e ℂ)
    (F : Submodule ℂ (e → ℂ)) :
    protectedRecordCyclicHull π S ≤ F ↔
      RecordSufficientSubspace π S F := by
  rw [protectedRecordCyclicHull, Submodule.span_le]
  constructor
  · intro h c x
    apply h
    exact ⟨c, x, rfl⟩
  · intro h v hv
    rcases hv with ⟨c, x, rfl⟩
    exact h c x

/-- Existence and uniqueness of the minimal record-sufficient Stinespring
space: it is precisely the cyclic hull displayed in the manuscript. -/
theorem protectedRecordCyclicHull_uniqueMinimal
    {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S : Matrix e e ℂ) :
    ∃! F : Submodule ℂ (e → ℂ),
      RecordSufficientSubspace π S F ∧
      ∀ W : Submodule ℂ (e → ℂ),
        RecordSufficientSubspace π S W → F ≤ W := by
  refine ⟨protectedRecordCyclicHull π S, ?_, ?_⟩
  · constructor
    · exact (protectedRecordCyclicHull_le_iff π S _).1 le_rfl
    · intro W hW
      exact (protectedRecordCyclicHull_le_iff π S W).2 hW
  · intro F hF
    apply le_antisymm
    · exact hF.2 (protectedRecordCyclicHull π S)
        ((protectedRecordCyclicHull_le_iff π S _).1 le_rfl)
    · exact (protectedRecordCyclicHull_le_iff π S F).2 hF.1

/-- A represented coefficient vanishes on the entire minimal hull exactly when
it kills every cyclic generator.  Thus any protected record with one detected
cyclic vector is retained rather than erased. -/
theorem protectedRecordCyclicHull_erasure_iff
    {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S P : Matrix e e ℂ) :
    protectedRecordCyclicHull π S ≤ LinearMap.ker P.mulVecLin ↔
      ∀ (c : R) (x : e → ℂ), P *ᵥ (π c *ᵥ (S *ᵥ x)) = 0 := by
  rw [protectedRecordCyclicHull_le_iff]
  constructor
  · intro h c x
    have hmem := h c x
    rwa [LinearMap.mem_ker, Matrix.mulVecLin_apply] at hmem
  · intro h c x
    rw [LinearMap.mem_ker, Matrix.mulVecLin_apply]
    exact h c x

/-- Exact finite record-map packet: complete positivity at every amplification,
normalization, and unique minimal cyclic Stinespring hull. -/
theorem protectedRecordMap_exact
    {R e : Type*} [Semiring R] [StarRing R]
    [Algebra ℂ R] [Fintype e] [DecidableEq e]
    (π : R →⋆ₐ[ℂ] Matrix e e ℂ) (S K : Matrix e e ℂ)
    (hS : Sᴴ * S = K) :
    (∀ {m : Type*} [Fintype m] [DecidableEq m]
      (C : Matrix (m × e) (m × e) ℂ), C.PosSemidef →
        ((amplifiedRecordRoot S)ᴴ * C *
          amplifiedRecordRoot S).PosSemidef)
    ∧ Sᴴ * π 1 * S = K
    ∧ (∃! F : Submodule ℂ (e → ℂ),
        RecordSufficientSubspace π S F ∧
        ∀ W : Submodule ℂ (e → ℂ),
          RecordSufficientSubspace π S W → F ≤ W) := by
  refine ⟨protectedRecordMap_completelyPositive S, ?_,
    protectedRecordCyclicHull_uniqueMinimal π S⟩
  simpa using hS

end NCG
