/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.CrossProductCliffordSystem
import Mathlib.Algebra.QuaternionBasis
import Mathlib.LinearAlgebra.Dimension.Free

/-!
# Quaternionic divisibility from two Clifford generators

Two anticommuting real complex structures make their carrier a left module
over the real quaternions.  Consequently its real dimension is divisible by
four.  This is the divisibility half of the Hurwitz dimension obstruction.
-/

open scoped Quaternion

namespace NCG.QuaternionicDimension

variable {V : Type*} [AddCommGroup V] [Module ℝ V]

/-- Evaluation of a quaternion through two anticommuting complex structures. -/
def action (I J : Module.End ℝ V) (q : ℍ[ℝ]) (v : V) : V :=
  q.re • v + q.imI • I v + q.imJ • J v + q.imK • I (J v)

theorem action_add (I J : Module.End ℝ V) (q r : ℍ[ℝ]) (v : V) :
    action I J (q + r) v = action I J q v + action I J r v := by
  simp only [action, Quaternion.re_add, Quaternion.imI_add,
    Quaternion.imJ_add, Quaternion.imK_add, add_smul]
  module

theorem action_smul (I J : Module.End ℝ V) (a : ℝ) (q : ℍ[ℝ]) (v : V) :
    action I J (a • q) v = a • action I J q v := by
  simp only [action, Quaternion.re_smul, Quaternion.imI_smul,
    Quaternion.imJ_smul, Quaternion.imK_smul, mul_smul, smul_add]
  module

theorem action_mul (I J : Module.End ℝ V)
    (hI : I * I = -(1 : Module.End ℝ V))
    (hJ : J * J = -(1 : Module.End ℝ V))
    (hIJ : I * J = -(J * I))
    (q r : ℍ[ℝ]) (v : V) :
    action I J (q * r) v = action I J q (action I J r v) := by
  have hIv (w : V) : I (I w) = -w := by
    have h := congrArg (fun f : Module.End ℝ V => f w) hI
    simpa [Module.End.mul_apply] using h
  have hJv (w : V) : J (J w) = -w := by
    have h := congrArg (fun f : Module.End ℝ V => f w) hJ
    simpa [Module.End.mul_apply] using h
  have hJIv (w : V) : J (I w) = -I (J w) := by
    have h := congrArg (fun f : Module.End ℝ V => f w) hIJ
    simp only [Module.End.mul_apply, LinearMap.neg_apply] at h
    linear_combination (norm := module) h
  simp only [action, Quaternion.re_mul, Quaternion.imI_mul,
    Quaternion.imJ_mul, Quaternion.imK_mul, map_add, map_sub, map_neg, map_smul,
    hIv, hJv, hJIv]
  module

/-- The algebra representation generated by `I` and `J`. -/
noncomputable def representation (I J : Module.End ℝ V)
    (hI : I * I = -(1 : Module.End ℝ V))
    (hJ : J * J = -(1 : Module.End ℝ V))
    (hIJ : I * J = -(J * I)) :
    ℍ[ℝ] →ₐ[ℝ] Module.End ℝ V where
  toFun q :=
    { toFun := action I J q
      map_add' := by
        intro u v
        simp only [action, smul_add, map_add]
        module
      map_smul' := by
        intro a v
        simp only [action, smul_add, map_smul, RingHom.id_apply]
        module }
  map_one' := by
    ext v
    simp [action]
  map_mul' q r := by
    ext v
    exact action_mul I J hI hJ hIJ q r v
  map_zero' := by
    ext v
    simp [action]
  map_add' q r := by
    ext v
    exact action_add I J q r v
  commutes' a := by
    ext v
    simp [action]

/-- Two anticommuting complex structures force real dimension to be a
multiple of four. -/
theorem four_dvd_finrank [FiniteDimensional ℝ V]
    (I J : Module.End ℝ V)
    (hI : I * I = -(1 : Module.End ℝ V))
    (hJ : J * J = -(1 : Module.End ℝ V))
    (hIJ : I * J = -(J * I)) :
    4 ∣ Module.finrank ℝ V := by
  let ρ := representation I J hI hJ hIJ
  letI : Module ℍ[ℝ] V := Module.compHom V ρ.toRingHom
  letI : IsScalarTower ℝ ℍ[ℝ] V :=
    { smul_assoc := by
        intro a q v
        change ρ (a • q) v = a • ρ q v
        rw [map_smul]
        rfl }
  have htower := Module.finrank_mul_finrank ℝ ℍ[ℝ] V
  rw [Quaternion.finrank_eq_four] at htower
  exact ⟨Module.finrank ℍ[ℝ] V, htower.symm⟩

end NCG.QuaternionicDimension
