/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.MinimalRecordHistorySurvival

/-!
# Record survival with a genuinely nontrivial future-null ideal

The complete-entry model makes the contextual null ideal zero.  Here Reads are declared on
a proper family of simple summands of a finite matrix-block history algebra.  The contextual
future-null ideal is proved to be exactly the unread-block ideal.  Thus readable record
projections and writers survive, while unread fibre contrasts are genuinely killed by a
possibly nonzero quotient ideal.
-/

open Matrix

namespace NCG
namespace RecordSurvivalNontrivialBlockIdeal

variable {ι : Type*} [Fintype ι] [DecidableEq ι]
variable (d : ι → Type*) [∀ b, Fintype (d b)] [∀ b, DecidableEq (d b)]

/-- A contextual test consists of a declared readable block and one matrix entry there. -/
abbrev DeclaredEntry (readable : Set ι) :=
  Σ b : {b : ι // b ∈ readable}, d b.1 × d b.1

/-- Entry Read on one declared matrix block. -/
def declaredBlockEntryRead (readable : Set ι) (k : DeclaredEntry d readable) :
    FiniteMatrixBlockAlgebra d →+ ℂ where
  toFun x := x k.1.1 k.2.1 k.2.2
  map_zero' := rfl
  map_add' _ _ := rfl

/-- The complete contextual future-null ideal generated by the declared block-entry Reads. -/
abbrev declaredFutureNullIdeal (readable : Set ι) :
    Ideal (FiniteMatrixBlockAlgebra d) :=
  contextualFutureNullIdeal (declaredBlockEntryRead d readable)

/-- Exact characterization: contextual future-nullity is precisely vanishing on every
declared readable block. -/
theorem contextualFutureNull_iff_zero_on_readable
    (readable : Set ι) (x : FiniteMatrixBlockAlgebra d) :
    contextualFutureNull (declaredBlockEntryRead d readable) x ↔
      ∀ b, b ∈ readable → x b = 0 := by
  constructor
  · intro hx b hb
    ext i j
    have hentry := hx.1 ⟨⟨b, hb⟩, (i, j)⟩ 1 1
    simp only [one_mul, mul_one] at hentry
    exact hentry
  · intro hx
    constructor
    · rintro ⟨⟨b, hb⟩, i, j⟩ u v
      have hxb := hx b hb
      change (u * x * v) b i j = 0
      simp [hxb]
    · rintro ⟨⟨b, hb⟩, i, j⟩ u v
      have hxb := hx b hb
      change (u * star x * v) b i j = 0
      simp [hxb]

/-- Central projection selecting one record block. -/
def recordBlockProjection (b : ι) : FiniteMatrixBlockAlgebra d :=
  Pi.single b 1

/-- A writer with its nonzero payload in the declared target record block. -/
def recordBlockWriter (target : ι) (payload : Matrix (d target) (d target) ℂ) :
    FiniteMatrixBlockAlgebra d :=
  Pi.single target payload

theorem recordBlockProjection_ne_zero [∀ b, Nonempty (d b)] (b : ι) :
    recordBlockProjection d b ≠ 0 := by
  intro h
  have hb := congrFun h b
  simp [recordBlockProjection] at hb

/-- A readable record projection is not future-null and hence survives the quotient. -/
theorem readable_projection_survives [∀ b, Nonempty (d b)]
    (readable : Set ι) {b : ι} (hb : b ∈ readable) :
    Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
        (recordBlockProjection d b) ≠ 0 := by
  intro hzero
  have hmem := Ideal.Quotient.eq_zero_iff_mem.mp hzero
  change contextualFutureNull (declaredBlockEntryRead d readable)
    (recordBlockProjection d b) at hmem
  have hz := (contextualFutureNull_iff_zero_on_readable d readable _).mp hmem b hb
  exact recordBlockProjection_ne_zero d b (by
    funext c
    by_cases hcb : c = b
    · subst c
      simpa [recordBlockProjection] using hz
    · simp [recordBlockProjection, hcb])

/-- Distinct readable record blocks remain distinct in the contextual history quotient. -/
theorem distinct_readable_projections_remain_distinct [∀ b, Nonempty (d b)]
    (readable : Set ι) {b c : ι} (hb : b ∈ readable) (hbc : b ≠ c) :
    Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
        (recordBlockProjection d b) ≠
      Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
        (recordBlockProjection d c) := by
  intro heq
  have hmem := Ideal.Quotient.eq.mp heq
  change contextualFutureNull (declaredBlockEntryRead d readable)
    (recordBlockProjection d b - recordBlockProjection d c) at hmem
  have hz := (contextualFutureNull_iff_zero_on_readable d readable _).mp hmem b hb
  let i : d b := Classical.choice (inferInstance : Nonempty (d b))
  have hbvalue := congrFun (congrFun hz i) i
  simp [recordBlockProjection, hbc] at hbvalue

/-- Every nonzero writer landing in a readable record block survives. -/
theorem readable_writer_survives [∀ b, Nonempty (d b)]
    (readable : Set ι) {target : ι} (ht : target ∈ readable)
    {payload : Matrix (d target) (d target) ℂ} (hpayload : payload ≠ 0) :
    Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
        (recordBlockWriter d target payload) ≠ 0 := by
  intro hzero
  have hmem := Ideal.Quotient.eq_zero_iff_mem.mp hzero
  change contextualFutureNull (declaredBlockEntryRead d readable)
    (recordBlockWriter d target payload) at hmem
  have hz := (contextualFutureNull_iff_zero_on_readable d readable _).mp hmem target ht
  have hpayload0 : payload = 0 := by
    simpa [recordBlockWriter] using hz
  exact hpayload hpayload0

/-- An element supported in one unread block is genuinely future-null. -/
theorem unread_block_is_killed
    (readable : Set ι) {b : ι} (hb : b ∉ readable)
    (payload : Matrix (d b) (d b) ℂ) :
    recordBlockWriter d b payload ∈ declaredFutureNullIdeal d readable := by
  change contextualFutureNull (declaredBlockEntryRead d readable)
    (recordBlockWriter d b payload)
  rw [contextualFutureNull_iff_zero_on_readable d readable]
  intro c hc
  have hcb : c ≠ b := by
    intro h
    subst c
    exact hb hc
  simp [recordBlockWriter, hcb]

/-- If an unread block exists and has a nonzero matrix unit, the contextual future-null
ideal is genuinely nonzero. -/
theorem declaredFutureNullIdeal_ne_bot [∀ b, Nonempty (d b)]
    (readable : Set ι) {b : ι} (hb : b ∉ readable) :
    declaredFutureNullIdeal d readable ≠ ⊥ := by
  intro hbot
  have hmem := unread_block_is_killed d readable hb
    (1 : Matrix (d b) (d b) ℂ)
  rw [hbot, Ideal.mem_bot] at hmem
  exact recordBlockProjection_ne_zero d b (by
    simpa [recordBlockProjection, recordBlockWriter] using hmem)

/-- Exact nontrivial record-survival packet: readable record classes, declared provenance
projections, and nonzero target writers survive, whereas unread contrasts are removed by a
genuinely nonzero contextual ideal whenever an unread block exists. -/
theorem record_survival_with_nontrivial_future_null_ideal [∀ b, Nonempty (d b)]
    (readable : Set ι) {unread : ι} (hunread : unread ∉ readable) :
    declaredFutureNullIdeal d readable ≠ ⊥ ∧
      (∀ b, b ∈ readable →
        Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
          (recordBlockProjection d b) ≠ 0) ∧
      (∀ b c, b ∈ readable → b ≠ c →
        Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
            (recordBlockProjection d b) ≠
          Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
            (recordBlockProjection d c)) ∧
      (∀ target, target ∈ readable →
        ∀ payload : Matrix (d target) (d target) ℂ, payload ≠ 0 →
          Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
            (recordBlockWriter d target payload) ≠ 0) ∧
      (∀ payload : Matrix (d unread) (d unread) ℂ,
        Ideal.Quotient.mk (declaredFutureNullIdeal d readable)
          (recordBlockWriter d unread payload) = 0) := by
  refine ⟨declaredFutureNullIdeal_ne_bot d readable hunread,
    fun b hb => readable_projection_survives d readable hb,
    fun b c hb hbc => distinct_readable_projections_remain_distinct d readable hb hbc,
    fun target ht payload hpayload =>
      readable_writer_survives d readable ht hpayload, ?_⟩
  intro payload
  exact Ideal.Quotient.eq_zero_iff_mem.mpr
    (unread_block_is_killed d readable hunread payload)

end RecordSurvivalNontrivialBlockIdeal
end NCG
