/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.RecordChain

/-!
# The record shift generates the full matrix algebra
  (`thm:ar-record-algebra`, generation clause,
   Gran-Tensor manuscript)

* `recS_pow` / `recS_unit`: the shift powers are the strict
  subdiagonals, and the words `S^a·P₁·(S^b)ᴴ` (with
  `P₁ = 1 - SSᴴ` the base-record projection from the proved
  shift relations) are exactly the matrix units `E_{ab}`;
* `record_generation`: the boxed `C*(S^rec) = M_X(ℂ)` — the
  star subalgebra generated by the single record shift is all
  of `M_X(ℂ)`, so the count ladder is an internal subalgebra of
  the universal operational history algebra.

Together with the proved `recS_relations` (shift algebra) and
`record_ladder` (pointed count ladder) this completes the
record-algebra theorem; the identification of the abstract
universal C*-algebra with its faithful finite representation is
the disclosed rendering.
-/

open Matrix

namespace NCG

/-- The shift powers are the strict subdiagonals. -/
lemma recS_pow (X a : ℕ) :
    recS X ^ a = Matrix.of fun (j i : Fin X) =>
      if (j : ℕ) = (i : ℕ) + a then 1 else 0 := by
  induction a with
  | zero =>
    ext j i
    rw [pow_zero, Matrix.of_apply, Matrix.one_apply]
    simp [Fin.ext_iff]
  | succ a ih =>
    rw [pow_succ, ih]
    ext j i
    rw [Matrix.mul_apply, Matrix.of_apply]
    have hterm : ∀ k ∈ Finset.univ,
        (Matrix.of fun (j i : Fin X) =>
            if (j : ℕ) = (i : ℕ) + a then (1 : ℂ) else 0) j k
          * recS X k i
        = if (k : ℕ) = (i : ℕ) + 1
          then (if (j : ℕ) = (i : ℕ) + 1 + a then 1 else 0)
          else 0 := by
      intro k _
      rw [Matrix.of_apply, recS, Matrix.of_apply]
      by_cases hk : (k : ℕ) = (i : ℕ) + 1
      · rw [if_pos hk, if_pos hk, mul_one, hk]
      · rw [if_neg hk, if_neg hk, mul_zero]
    rw [Finset.sum_congr rfl hterm]
    by_cases hi : (i : ℕ) + 1 < X
    · rw [Finset.sum_eq_single (⟨(i : ℕ) + 1, hi⟩ : Fin X)
        (fun k _ hk => by
          rw [if_neg]
          intro h
          exact hk (Fin.ext h))
        (fun habs => absurd (Finset.mem_univ _) habs)]
      rw [if_pos rfl,
        show (i : ℕ) + 1 + a = (i : ℕ) + (a + 1) from by omega]
    · rw [Finset.sum_eq_zero (fun k _ => by
        rw [if_neg]
        intro h
        have := k.isLt
        omega)]
      rw [if_neg]
      intro h
      have := j.isLt
      omega

private lemma recS_unit {X : ℕ} (hX : 1 ≤ X) (a b : Fin X) :
    recS X ^ (a : ℕ) * (1 - recS X * (recS X)ᴴ)
        * (recS X ^ (b : ℕ))ᴴ
      = Matrix.single a b 1 := by
  have hP1 : (1 : Matrix (Fin X) (Fin X) ℂ)
      - recS X * (recS X)ᴴ
      = Matrix.of (fun (j i : Fin X) =>
          if (j : ℕ) = 0 ∧ (i : ℕ) = 0 then (1 : ℂ) else 0) := by
    rw [(recS_relations hX).2.1, sub_sub_cancel]
  rw [hP1, recS_pow, recS_pow]
  have hleft : (Matrix.of fun (j i : Fin X) =>
        if (j : ℕ) = (i : ℕ) + (a : ℕ) then (1 : ℂ) else 0)
      * Matrix.of (fun (j i : Fin X) =>
          if (j : ℕ) = 0 ∧ (i : ℕ) = 0 then (1 : ℂ) else 0)
      = Matrix.of fun (j i : Fin X) =>
          if (j : ℕ) = (a : ℕ) ∧ (i : ℕ) = 0
          then (1 : ℂ) else 0 := by
    ext j i
    rw [Matrix.mul_apply, Matrix.of_apply]
    have hterm : ∀ k ∈ Finset.univ,
        (Matrix.of fun (j i : Fin X) =>
            if (j : ℕ) = (i : ℕ) + (a : ℕ) then (1 : ℂ) else 0)
            j k
          * Matrix.of (fun (j i : Fin X) =>
              if (j : ℕ) = 0 ∧ (i : ℕ) = 0 then (1 : ℂ) else 0)
            k i
        = if (k : ℕ) = 0
          then (if (j : ℕ) = (a : ℕ) ∧ (i : ℕ) = 0
            then 1 else 0)
          else 0 := by
      intro k _
      rw [Matrix.of_apply, Matrix.of_apply]
      by_cases hk : (k : ℕ) = 0
      · rw [if_pos hk, hk]
        by_cases hi : (i : ℕ) = 0
        · by_cases hj : (j : ℕ) = (a : ℕ) <;>
            simp [hi, hj]
        · simp [hi]
      · rw [show (if (k : ℕ) = 0 ∧ (i : ℕ) = 0
            then (1 : ℂ) else 0) = 0
            from if_neg (fun hand => hk hand.1),
          mul_zero, if_neg hk]
    rw [Finset.sum_congr rfl hterm]
    have h0 : 0 < X := hX
    rw [Finset.sum_eq_single (⟨0, h0⟩ : Fin X)
      (fun k _ hk => by
        rw [if_neg]
        intro h
        exact hk (Fin.ext h))
      (fun habs => absurd (Finset.mem_univ _) habs)]
    rw [if_pos rfl]
  rw [hleft]
  ext j i
  rw [Matrix.mul_apply, Matrix.single_apply]
  have hterm : ∀ k ∈ Finset.univ,
      (Matrix.of fun (j i : Fin X) =>
          if (j : ℕ) = (a : ℕ) ∧ (i : ℕ) = 0
          then (1 : ℂ) else 0) j k
        * (Matrix.of fun (j i : Fin X) =>
            if (j : ℕ) = (i : ℕ) + (b : ℕ) then (1 : ℂ) else 0)ᴴ
          k i
      = if (k : ℕ) = 0
        then (if (j : ℕ) = (a : ℕ) ∧ (i : ℕ) = (b : ℕ)
          then 1 else 0)
        else 0 := by
    intro k _
    rw [Matrix.conjTranspose_apply, Matrix.of_apply,
      Matrix.of_apply]
    by_cases hk : (k : ℕ) = 0
    · rw [if_pos hk]
      by_cases hj : (j : ℕ) = (a : ℕ)
      · by_cases hi : (i : ℕ) = (b : ℕ) <;>
          simp [hj, hi, hk]
      · simp [hj, hk]
    · rw [if_neg (fun hand => hk hand.2), zero_mul,
        if_neg hk]
  rw [Finset.sum_congr rfl hterm]
  have h0 : 0 < X := hX
  rw [Finset.sum_eq_single (⟨0, h0⟩ : Fin X)
    (fun k _ hk => by
      rw [if_neg]
      intro h
      exact hk (Fin.ext h))
    (fun habs => absurd (Finset.mem_univ _) habs)]
  rw [if_pos rfl]
  simp only [Fin.ext_iff]
  by_cases hja : (j : ℕ) = (a : ℕ)
  · by_cases hib : (i : ℕ) = (b : ℕ)
    · rw [if_pos ⟨hja, hib⟩, if_pos ⟨hja.symm, hib.symm⟩]
    · rw [if_neg (fun hand => hib hand.2),
        if_neg (fun hand => hib hand.2.symm)]
  · rw [if_neg (fun hand => hja hand.1),
      if_neg (fun hand => hja hand.1.symm)]

/-- `thm:ar-record-algebra`, generation clause: the boxed
`C*(S^rec) = M_X(ℂ)` — the star subalgebra generated by the
record shift is the full matrix algebra. -/
theorem record_generation {X : ℕ} (hX : 1 ≤ X) :
    StarAlgebra.adjoin ℂ
        ({recS X} : Set (Matrix (Fin X) (Fin X) ℂ)) = ⊤ := by
  rw [eq_top_iff]
  intro M _
  have hS : recS X ∈ StarAlgebra.adjoin ℂ
      ({recS X} : Set (Matrix (Fin X) (Fin X) ℂ)) :=
    StarAlgebra.subset_adjoin ℂ _ (Set.mem_singleton _)
  have hunit : ∀ a b : Fin X,
      Matrix.single a b (1 : ℂ) ∈ StarAlgebra.adjoin ℂ
        ({recS X} : Set (Matrix (Fin X) (Fin X) ℂ)) := by
    intro a b
    rw [← recS_unit hX a b]
    exact mul_mem
      (mul_mem (pow_mem hS _)
        (sub_mem (one_mem _) (mul_mem hS (star_mem hS))))
      (star_mem (pow_mem hS _))
  have hexp : M = ∑ a : Fin X, ∑ b : Fin X,
      M a b • Matrix.single a b (1 : ℂ) := by
    ext j i
    simp only [Matrix.sum_apply, Matrix.smul_apply,
      Matrix.single_apply, smul_eq_mul]
    rw [Finset.sum_congr rfl (fun a _ =>
      Finset.sum_congr rfl (fun b _ => show
        M a b * (if a = j ∧ b = i then (1 : ℂ) else 0)
          = if b = i then (if a = j then M a b else 0)
            else 0 from by
      by_cases ha : a = j <;> by_cases hb : b = i <;>
        simp [ha, hb]))]
    rw [Finset.sum_congr rfl (fun a _ =>
      Finset.sum_ite_eq' Finset.univ i
        (fun b => if a = j then M a b else 0))]
    simp only [Finset.mem_univ, if_true]
    rw [Finset.sum_ite_eq' Finset.univ j (fun a => M a i)]
    simp
  rw [hexp]
  exact sum_mem fun a _ => sum_mem fun b _ =>
    SMulMemClass.smul_mem _ (hunit a b)

end NCG
