/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Bounded local relation audit
  (`cor:relational-depth-four`, Gran-Tensor manuscript)

* `relational_depth_four`: the boxed RC.12 presentation
  completeness — the group presented on the six `A₃` root
  generators by the three translated relation types
  (inverse pairs are the free-group inverses, lengths
  two; the three triangle relations
  `(e_j-e_i)·e_i·(-e_j)`, lengths three; the three
  commutator squares `e_i·e_j·(-e_i)·(-e_j)`, lengths
  four) is exactly the free abelian accumulator `ℤ³`:
  (i) an explicit isomorphism
      `PresentedGroup rels ≃* Multiplicative (Fin 3 → ℤ)`
      carrying each word class to its endpoint;
  (ii) consequently two root words have the same
      accumulator endpoint **iff** they are equal modulo
      the normal closure of the RC.12 relations — every
      same-endpoint equality is generated by the three
      relation types, so local routers and action
      cochains are decided at relation depth at most
      four.

The deck-period clause (a compact quotient adds exactly
its period subgroup) is the manuscript's regulator layer;
inverse relations enter through the free-group inverse
letters.
-/

namespace NCG

/-- The additive endpoint of each unoriented `A₃` root
generator (`e₁, e₂, e₃, e₂-e₁, e₃-e₁, e₃-e₂`). -/
def a3RootEndpoint : Fin 6 → (Fin 3 → ℤ) :=
  ![![1, 0, 0], ![0, 1, 0], ![0, 0, 1],
    ![-1, 1, 0], ![-1, 0, 1], ![0, -1, 1]]

/-- The boxed RC.12 relation set: three triangle
relations (length three) and three commutator squares
(length four); the length-two inverse relations are the
free-group inverses. -/
def a3DepthFourRels : Set (FreeGroup (Fin 6)) :=
  { FreeGroup.of 3 * FreeGroup.of 0 * (FreeGroup.of 1)⁻¹,
    FreeGroup.of 4 * FreeGroup.of 0 * (FreeGroup.of 2)⁻¹,
    FreeGroup.of 5 * FreeGroup.of 1 * (FreeGroup.of 2)⁻¹,
    FreeGroup.of 0 * FreeGroup.of 1 * (FreeGroup.of 0)⁻¹
      * (FreeGroup.of 1)⁻¹,
    FreeGroup.of 0 * FreeGroup.of 2 * (FreeGroup.of 0)⁻¹
      * (FreeGroup.of 2)⁻¹,
    FreeGroup.of 1 * FreeGroup.of 2 * (FreeGroup.of 1)⁻¹
      * (FreeGroup.of 2)⁻¹ }

/-- The endpoint homomorphism to the free abelian
accumulator. -/
noncomputable def a3EndpointHom :
    FreeGroup (Fin 6) →* Multiplicative (Fin 3 → ℤ) :=
  FreeGroup.lift fun a =>
    Multiplicative.ofAdd (a3RootEndpoint a)

lemma a3EndpointHom_rels :
    ∀ r ∈ a3DepthFourRels, a3EndpointHom r = 1 := by
  intro r hr
  rcases hr with rfl | rfl | rfl | rfl | rfl | rfl <;>
    (simp only [a3EndpointHom, map_mul, map_inv,
      FreeGroup.lift_apply_of]
     rw [show (1 : Multiplicative (Fin 3 → ℤ))
       = Multiplicative.ofAdd 0 from rfl]
     rw [← ofAdd_neg]
     try rw [← ofAdd_neg]
     rw [← ofAdd_add]
     try rw [← ofAdd_add]
     try rw [← ofAdd_add]
     congr 1
     funext i
     rcases (by decide : ∀ x : Fin 3, x = 0 ∨ x = 1
         ∨ x = 2) i with rfl | rfl | rfl <;>
       simp [a3RootEndpoint, Matrix.cons_val,
         Matrix.cons_val_zero, Matrix.cons_val_one])

/-- The induced homomorphism on the presented group. -/
noncomputable def a3PresentedToAccumulator :
    PresentedGroup a3DepthFourRels →*
      Multiplicative (Fin 3 → ℤ) :=
  PresentedGroup.toGroup a3EndpointHom_rels

private lemma mul_shuffle {G : Type*} [Group G]
    (a₀ b₀ a₁ b₁ a₂ b₂ : G)
    (h10 : Commute a₁ b₀) (h20 : Commute a₂ b₀)
    (h21 : Commute a₂ b₁) :
    a₀ * b₀ * (a₁ * b₁) * (a₂ * b₂)
      = a₀ * a₁ * a₂ * (b₀ * b₁ * b₂) := by
  calc a₀ * b₀ * (a₁ * b₁) * (a₂ * b₂)
      = a₀ * (b₀ * a₁) * (b₁ * a₂) * b₂ := by group
    _ = a₀ * (a₁ * b₀) * (a₂ * b₁) * b₂ := by
        rw [← h10.eq, ← h21.eq]
    _ = a₀ * a₁ * (b₀ * a₂) * (b₁ * b₂) := by group
    _ = a₀ * a₁ * (a₂ * b₀) * (b₁ * b₂) := by
        rw [← h20.eq]
    _ = a₀ * a₁ * a₂ * (b₀ * b₁ * b₂) := by group

/-- `cor:relational-depth-four` (the boxed RC.12
presentation completeness): the depth-four presented
group is the free abelian accumulator, and two root words
have equal endpoints iff they agree modulo the RC.12
relations. -/
theorem relational_depth_four :
    -- (i) the presented group is the accumulator `ℤ³`
    (∃ e : PresentedGroup a3DepthFourRels ≃*
        Multiplicative (Fin 3 → ℤ),
      ∀ w : FreeGroup (Fin 6),
        e (PresentedGroup.mk a3DepthFourRels w)
          = a3EndpointHom w)
    -- (ii) same endpoint iff same relation class
    ∧ (∀ w₁ w₂ : FreeGroup (Fin 6),
        PresentedGroup.mk a3DepthFourRels w₁
          = PresentedGroup.mk a3DepthFourRels w₂
        ↔ a3EndpointHom w₁ = a3EndpointHom w₂) := by
  -- relations hold in the quotient
  have hrel : ∀ r ∈ a3DepthFourRels,
      PresentedGroup.mk a3DepthFourRels r = 1 := by
    intro r hr
    exact (QuotientGroup.eq_one_iff r).mpr
      (Subgroup.subset_normalClosure hr)
  -- commutation of the three basis generator classes
  have hc01 : Commute
      (PresentedGroup.of (rels := a3DepthFourRels) 0)
      (PresentedGroup.of 1) := by
    have h := hrel _ (by
      right; right; right; left; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    rw [Commute, SemiconjBy]
    calc PresentedGroup.of (rels := a3DepthFourRels) 0
          * PresentedGroup.of 1
        = (PresentedGroup.of 0 * PresentedGroup.of 1
            * (PresentedGroup.of
              (rels := a3DepthFourRels) 0)⁻¹
            * (PresentedGroup.of 1)⁻¹)
          * (PresentedGroup.of 1
            * PresentedGroup.of 0) := by group
      _ = 1 * (PresentedGroup.of 1
            * PresentedGroup.of 0) := by rw [h]
      _ = PresentedGroup.of 1 * PresentedGroup.of 0 :=
          one_mul _
  have hc02 : Commute
      (PresentedGroup.of (rels := a3DepthFourRels) 0)
      (PresentedGroup.of 2) := by
    have h := hrel _ (by
      right; right; right; right; left; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    rw [Commute, SemiconjBy]
    calc PresentedGroup.of (rels := a3DepthFourRels) 0
          * PresentedGroup.of 2
        = (PresentedGroup.of 0 * PresentedGroup.of 2
            * (PresentedGroup.of
              (rels := a3DepthFourRels) 0)⁻¹
            * (PresentedGroup.of 2)⁻¹)
          * (PresentedGroup.of 2
            * PresentedGroup.of 0) := by group
      _ = 1 * (PresentedGroup.of 2
            * PresentedGroup.of 0) := by rw [h]
      _ = PresentedGroup.of 2 * PresentedGroup.of 0 :=
          one_mul _
  have hc12 : Commute
      (PresentedGroup.of (rels := a3DepthFourRels) 1)
      (PresentedGroup.of 2) := by
    have h := hrel _ (by
      right; right; right; right; right; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    rw [Commute, SemiconjBy]
    calc PresentedGroup.of (rels := a3DepthFourRels) 1
          * PresentedGroup.of 2
        = (PresentedGroup.of 1 * PresentedGroup.of 2
            * (PresentedGroup.of
              (rels := a3DepthFourRels) 1)⁻¹
            * (PresentedGroup.of 2)⁻¹)
          * (PresentedGroup.of 2
            * PresentedGroup.of 1) := by group
      _ = 1 * (PresentedGroup.of 2
            * PresentedGroup.of 1) := by rw [h]
      _ = PresentedGroup.of 2 * PresentedGroup.of 1 :=
          one_mul _
  -- triangle relations express nonbasis generators
  have ht3 : PresentedGroup.of
      (rels := a3DepthFourRels) 3
      = PresentedGroup.of 1
        * (PresentedGroup.of 0)⁻¹ := by
    have h := hrel _ (by left; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    calc PresentedGroup.of (rels := a3DepthFourRels) 3
        = (PresentedGroup.of 3 * PresentedGroup.of 0
            * (PresentedGroup.of 1)⁻¹)
          * (PresentedGroup.of 1
            * (PresentedGroup.of 0)⁻¹) := by group
      _ = 1 * (PresentedGroup.of 1
            * (PresentedGroup.of 0)⁻¹) := by rw [h]
      _ = PresentedGroup.of 1
          * (PresentedGroup.of 0)⁻¹ := one_mul _
  have ht4 : PresentedGroup.of
      (rels := a3DepthFourRels) 4
      = PresentedGroup.of 2
        * (PresentedGroup.of 0)⁻¹ := by
    have h := hrel _ (by right; left; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    calc PresentedGroup.of (rels := a3DepthFourRels) 4
        = (PresentedGroup.of 4 * PresentedGroup.of 0
            * (PresentedGroup.of 2)⁻¹)
          * (PresentedGroup.of 2
            * (PresentedGroup.of 0)⁻¹) := by group
      _ = 1 * (PresentedGroup.of 2
            * (PresentedGroup.of 0)⁻¹) := by rw [h]
      _ = PresentedGroup.of 2
          * (PresentedGroup.of 0)⁻¹ := one_mul _
  have ht5 : PresentedGroup.of
      (rels := a3DepthFourRels) 5
      = PresentedGroup.of 2
        * (PresentedGroup.of 1)⁻¹ := by
    have h := hrel _ (by right; right; left; rfl)
    simp only [map_mul, map_inv] at h
    simp only [show ∀ b : Fin 6,
      PresentedGroup.mk a3DepthFourRels (FreeGroup.of b)
        = PresentedGroup.of b from fun _ => rfl] at h
    calc PresentedGroup.of (rels := a3DepthFourRels) 5
        = (PresentedGroup.of 5 * PresentedGroup.of 1
            * (PresentedGroup.of 2)⁻¹)
          * (PresentedGroup.of 2
            * (PresentedGroup.of 1)⁻¹) := by group
      _ = 1 * (PresentedGroup.of 2
            * (PresentedGroup.of 1)⁻¹) := by rw [h]
      _ = PresentedGroup.of 2
          * (PresentedGroup.of 1)⁻¹ := one_mul _
  -- the reverse homomorphism from the accumulator
  set ψfun : Multiplicative (Fin 3 → ℤ) →
      PresentedGroup a3DepthFourRels := fun x =>
    PresentedGroup.of 0 ^ (Multiplicative.toAdd x 0)
      * PresentedGroup.of 1
        ^ (Multiplicative.toAdd x 1)
      * PresentedGroup.of 2
        ^ (Multiplicative.toAdd x 2)
    with hψfun
  have hψmul : ∀ x y,
      ψfun (x * y) = ψfun x * ψfun y := by
    intro x y
    simp only [hψfun, toAdd_mul, Pi.add_apply, zpow_add]
    exact mul_shuffle _ _ _ _ _ _
      (hc01.symm.zpow_zpow _ _)
      (hc02.symm.zpow_zpow _ _)
      (hc12.symm.zpow_zpow _ _)
  set ψ : Multiplicative (Fin 3 → ℤ) →*
      PresentedGroup a3DepthFourRels :=
    { toFun := ψfun
      map_one' := by
        simp only [hψfun]
        simp
      map_mul' := hψmul } with hψ
  -- generator images of the descended homomorphism
  have hφof : ∀ a : Fin 6,
      a3PresentedToAccumulator (PresentedGroup.of a)
        = Multiplicative.ofAdd (a3RootEndpoint a) :=
    fun a => PresentedGroup.toGroup.of a3EndpointHom_rels
  -- φ ∘ ψ = id on the accumulator
  have hφψ : ∀ x, a3PresentedToAccumulator (ψ x) = x := by
    intro x
    rw [hψ]
    simp only [MonoidHom.coe_mk, OneHom.coe_mk, hψfun]
    rw [map_mul, map_mul, map_zpow, map_zpow, map_zpow]
    rw [hφof 0, hφof 1, hφof 2]
    rw [← ofAdd_zsmul, ← ofAdd_zsmul, ← ofAdd_zsmul,
      ← ofAdd_add, ← ofAdd_add]
    rw [show x = Multiplicative.ofAdd
      (Multiplicative.toAdd x) from rfl]
    congr 1
    funext j
    rcases (by decide : ∀ i : Fin 3, i = 0 ∨ i = 1
        ∨ i = 2) j with rfl | rfl | rfl <;>
      simp [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
  -- ψ ∘ φ = id on the six generators
  have hψφ : ∀ a : Fin 6,
      ψ (a3PresentedToAccumulator (PresentedGroup.of a))
        = PresentedGroup.of a := by
    intro a
    rw [hφof a, hψ]
    simp only [MonoidHom.coe_mk, OneHom.coe_mk, hψfun,
      toAdd_ofAdd]
    rcases (by decide : ∀ x : Fin 6, x = 0 ∨ x = 1
        ∨ x = 2 ∨ x = 3 ∨ x = 4 ∨ x = 5) a
      with rfl | rfl | rfl | rfl | rfl | rfl
    · simp [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
    · simp [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
    · simp [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
    · -- generator 3 : `g₀⁻¹ g₁`
      simp only [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
      norm_num
      rw [ht3]
      exact (hc01.inv_left).eq
    · -- generator 4 : `g₀⁻¹ g₂`
      simp only [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
      norm_num
      rw [ht4]
      exact (hc02.inv_left).eq
    · -- generator 5 : `g₁⁻¹ g₂`
      simp only [a3RootEndpoint, Matrix.cons_val,
        Matrix.cons_val_zero, Matrix.cons_val_one]
      norm_num
      rw [ht5]
      exact (hc12.inv_left).eq
  -- assemble the isomorphism
  set eqv : PresentedGroup a3DepthFourRels ≃*
      Multiplicative (Fin 3 → ℤ) :=
    MonoidHom.toMulEquiv a3PresentedToAccumulator ψ
      (PresentedGroup.ext fun a => hψφ a)
      (MonoidHom.ext hφψ) with heqv
  have hcompat : ∀ w : FreeGroup (Fin 6),
      eqv (PresentedGroup.mk a3DepthFourRels w)
        = a3EndpointHom w := by
    have hcomp : a3PresentedToAccumulator.comp
        (PresentedGroup.mk a3DepthFourRels)
        = a3EndpointHom := by
      apply FreeGroup.ext_hom
      intro a
      simp only [MonoidHom.comp_apply]
      rw [show PresentedGroup.mk a3DepthFourRels
        (FreeGroup.of a) = PresentedGroup.of a from rfl]
      rw [hφof a, a3EndpointHom,
        FreeGroup.lift_apply_of]
    intro w
    have := DFunLike.congr_fun hcomp w
    simpa [heqv] using this
  refine ⟨⟨eqv, hcompat⟩, ?_⟩
  intro w₁ w₂
  constructor
  · intro h
    rw [← hcompat, ← hcompat, h]
  · intro h
    apply eqv.injective
    rw [hcompat, hcompat, h]

end NCG
