/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Generated fine Einstein–matter responses and source attribution

Exact encoding of `cor:SMST-generated-response-source` (SMC.1) on the fine weak-test
carrier `V` (a real inner product space).

For adjacent loaded cutoffs the transported old response `J A_X(U)`, the response
`G` generated by the common fine nonlinear writer, the assembled declared packet `S`
and the fine response `A_Y(J U)` define the unexplained response
`R^src = A_Y(J U) - J A_X(U) - G - S` (SMC.1).

* `sourceBirth v = ⟪v, R^src⟫` is the projection of the residual on a fine response
  direction; `isNewSource_iff`: a direction is a new physical source exactly when this
  projection is nonzero;
* `sourceBirth_eq_zero_of_generated`: a direction whose fine response is fully licensed
  by old transport, the common nonlinear writer and the declared packet (a generated
  higher harmonic or constraint correction) has zero source birth;
* `unexplainedRange_eq`: the source-minimal unexplained range is the polar (orthogonal)
  complement of the zero-birth directions, i.e. the span of the residual.
-/

open scoped RealInnerProductSpace

namespace NCG
namespace SMSTGeneratedResponseSource

set_option linter.unusedSectionVars false

variable {V : Type*} [NormedAddCommGroup V] [InnerProductSpace ℝ V] [FiniteDimensional ℝ V]

/-- **(SMC.1)**: the unexplained response
`R^src = A_Y(J U) - J A_X(U) - G^nl - S^decl`. -/
def residual (fine old generated declared : V) : V := fine - old - generated - declared

/-- The source birth of a fine response direction `v`: its projection on the residual. -/
def sourceBirth (fine old generated declared v : V) : ℝ :=
  ⟪v, residual fine old generated declared⟫

/-- A direction is a new physical source when its projection in `R^src` is nonzero. -/
def IsNewSource (fine old generated declared v : V) : Prop :=
  sourceBirth fine old generated declared v ≠ 0

theorem isNewSource_iff (fine old generated declared v : V) :
    IsNewSource fine old generated declared v ↔
      ⟪v, fine - old - generated - declared⟫ ≠ 0 := Iff.rfl

/-- A fine response direction is *licensed* (generated) when its fine response is
exactly its old-transport, nonlinear-writer and declared-packet response. -/
def IsGenerated (fine old generated declared v : V) : Prop :=
  ⟪v, fine⟫ = ⟪v, old⟫ + ⟪v, generated⟫ + ⟪v, declared⟫

/-- A generated higher harmonic or fine constraint correction has zero source birth. -/
theorem sourceBirth_eq_zero_of_generated {fine old generated declared v : V}
    (h : IsGenerated fine old generated declared v) :
    sourceBirth fine old generated declared v = 0 := by
  unfold sourceBirth residual
  rw [inner_sub_right, inner_sub_right, inner_sub_right]
  unfold IsGenerated at h
  linarith

/-- Conversely, a direction with zero source birth is licensed. -/
theorem isGenerated_of_sourceBirth_eq_zero {fine old generated declared v : V}
    (h : sourceBirth fine old generated declared v = 0) :
    IsGenerated fine old generated declared v := by
  unfold sourceBirth residual at h
  rw [inner_sub_right, inner_sub_right, inner_sub_right] at h
  unfold IsGenerated
  linarith

/-- The zero-birth directions form the orthogonal complement of the residual line. -/
noncomputable def zeroBirthDirections (fine old generated declared : V) : Submodule ℝ V :=
  (Submodule.span ℝ {residual fine old generated declared})ᗮ

theorem mem_zeroBirthDirections_iff (fine old generated declared v : V) :
    v ∈ zeroBirthDirections fine old generated declared ↔
      sourceBirth fine old generated declared v = 0 := by
  unfold zeroBirthDirections sourceBirth
  rw [Submodule.mem_orthogonal_singleton_iff_inner_right, real_inner_comm]

/-- **Source-minimal unexplained range**: the polar range of the residual is exactly
the orthogonal complement of the zero-birth directions, i.e. the residual line. -/
theorem unexplainedRange_eq (fine old generated declared : V) :
    (zeroBirthDirections fine old generated declared)ᗮ
      = Submodule.span ℝ {residual fine old generated declared} := by
  unfold zeroBirthDirections
  exact Submodule.orthogonal_orthogonal _

end SMSTGeneratedResponseSource
end NCG
