/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Source-ideal split, writer saturation, and the uniform gap
  (`thm:central-source-decomposition`,
   `thm:primitive-writer-saturation`, `thm:uniform-gap-limit`,
   `cor:endpoint-defect-symmetry`, Gran-Tensor manuscript)

* `central_source_decomposition`: the boxed Peirce split — a
  central idempotent `z` gives the two-sided ideal `zA`, the
  decomposition `a = za + (1-z)a`, and `z` is unique for its
  ideal;
* `primitive_writer_saturation`: a dense subset has the same
  closed orbit — `closure (f '' B) = closure (f '' A)` for
  continuous `f` and `B` dense in `A`;
* `uniform_gap_limit`: the boxed direct-limit gap — a bound on a
  dense increasing family is a bound on the limit
  (`‖T∞‖ = sup ρ_X` in criterion form), and with `TE = ET = E`,
  `E² = E` the boxed decay `‖Tᵏ - E‖ ≤ ‖QTQ‖ᵏ` holds since
  `T - E = QTQ` and `(T - E)ᵏ = Tᵏ - E`;
* `endpoint_defect_symmetry`: the isotypic localization — a
  matrix commuting with every `1 ⊗ B` is `A ⊗ 1`; coherent
  endpoint defects live entirely in multiplicity space, and on an
  irreducible payload the response is one visibility.

Rendering disclosed: on the manuscript side the ideal is
generated by a source packet (`z` is the packet's central
support, existence via finite-dimensional structure theory —
displayed); Schur's lemma for the general isotypic decomposition
`⊕ V_π ⊗ M_π` reduces to the proved `1 ⊗ M` commutant statement
blockwise.
-/

namespace NCG

section Peirce

variable {R : Type*} [Ring R]

/-- `thm:central-source-decomposition`: the central idempotent
Peirce split, with uniqueness of the central support. -/
theorem central_source_decomposition (z : R)
    (hz : z * z = z) (hcen : ∀ a, z * a = a * z) :
    (∀ a, a = z * a + (1 - z) * a)
    ∧ (∀ a b, (z * a) * b = z * (a * b)
        ∧ b * (z * a) = z * (b * a))
    ∧ ∀ z' : R, z' * z' = z' → (∀ a, z' * a = a * z') →
        (∀ a, ∃ b, z * a = z' * b)
        → (∀ a, ∃ b, z' * a = z * b) → z = z' := by
  refine ⟨fun a => by noncomm_ring, fun a b => ⟨by noncomm_ring,
    by rw [← mul_assoc, ← hcen b, mul_assoc]⟩, ?_⟩
  intro z' hz' hcen' h1 h2
  obtain ⟨b, hb⟩ := h1 1
  obtain ⟨c, hc⟩ := h2 1
  rw [mul_one] at hb hc
  have h3 : z' * z = z := by
    rw [hb, ← mul_assoc, hz']
  have h4 : z * z' = z' := by
    rw [hc, ← mul_assoc, hz]
  calc z = z' * z := h3.symm
    _ = z * z' := hcen' z
    _ = z' := h4

end Peirce

/-- `thm:primitive-writer-saturation`: a dense generating set has
the same closed orbit as the full algebra. -/
theorem primitive_writer_saturation {A H : Type*}
    [TopologicalSpace A] [TopologicalSpace H]
    (f : A → H) (hf : Continuous f) (B S : Set A)
    (hBS : B ⊆ S) (hdense : S ⊆ closure B) :
    closure (f '' B) = closure (f '' S) := by
  refine le_antisymm (closure_mono (Set.image_mono hBS)) ?_
  refine closure_minimal ?_ isClosed_closure
  calc f '' S ⊆ f '' closure B := Set.image_mono hdense
    _ ⊆ closure (f '' B) :=
        image_closure_subset_closure_image hf

section Gap

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]

/-- `thm:uniform-gap-limit`, criterion half: a uniform bound on a
family with dense union is a bound on the limit operator. -/
theorem uniform_gap_limit_bound (T : E →L[ℂ] E) (c : ℝ)
    (hc : 0 ≤ c) (S : ℕ → Set E)
    (hdense : Dense (⋃ n, S n))
    (hbd : ∀ n, ∀ x ∈ S n, ‖T x‖ ≤ c * ‖x‖) :
    ‖T‖ ≤ c := by
  refine T.opNorm_le_bound hc fun x => ?_
  have hx : x ∈ closure (⋃ n, S n) := hdense x
  have hclosed : IsClosed {y : E | ‖T y‖ ≤ c * ‖y‖} :=
    isClosed_le (by fun_prop) (by fun_prop)
  have hsub : (⋃ n, S n) ⊆ {y : E | ‖T y‖ ≤ c * ‖y‖} := by
    intro y hy
    obtain ⟨n, hn⟩ := Set.mem_iUnion.mp hy
    exact hbd n y hn
  exact hclosed.closure_subset_iff.mpr hsub hx

/-- `thm:uniform-gap-limit`, boxed decay: with `TE = ET = E`,
`E² = E`, one has `T - E = (1-E)T(1-E)` and
`‖Tᵏ - E‖ ≤ ‖T - E‖ᵏ` — the geometric convergence to the fixed
projection. -/
theorem uniform_gap_decay {R : Type*} [NormedRing R]
    (T Eproj : R) (hTE : T * Eproj = Eproj)
    (hET : Eproj * T = Eproj) (hE : Eproj * Eproj = Eproj) :
    T - Eproj = (1 - Eproj) * T * (1 - Eproj)
    ∧ ∀ k : ℕ, ‖T ^ (k + 1) - Eproj‖
        ≤ ‖T - Eproj‖ ^ (k + 1) := by
  constructor
  · have hexp : (1 - Eproj) * T * (1 - Eproj)
        = T - Eproj * T - T * Eproj + Eproj * T * Eproj := by
      noncomm_ring
    rw [hexp, hET, hTE, hE]
    abel
  · intro k
    have hTkE : ∀ j : ℕ, T ^ (j + 1) * Eproj = Eproj := by
      intro j
      induction j with
      | zero => simpa using hTE
      | succ i ih => rw [pow_succ, mul_assoc, hTE, ih]
    have hpow : ∀ j : ℕ, T ^ (j + 1) - Eproj
        = (T - Eproj) ^ (j + 1) := by
      intro j
      induction j with
      | zero => simp
      | succ j ih =>
        have hstep : (T - Eproj) ^ (j + 2)
            = (T - Eproj) ^ (j + 1) * (T - Eproj) := by
          rw [pow_succ]
        rw [hstep, ← ih]
        have hexp2 : (T ^ (j + 1) - Eproj) * (T - Eproj)
            = T ^ (j + 2) - T ^ (j + 1) * Eproj
              - Eproj * T + Eproj * Eproj := by
          noncomm_ring
        rw [hexp2, hET, hE, hTkE j]
        abel
    rw [hpow k]
    exact norm_pow_le' _ (Nat.succ_pos k)

end Gap

open Kronecker in
/-- `cor:endpoint-defect-symmetry`, commutant localization: a
matrix commuting with every `1 ⊗ B` is `A ⊗ 1` — coherent
endpoint defects live entirely in multiplicity space. -/
theorem endpoint_defect_symmetry {ι κ : Type*} [Fintype ι]
    [Fintype κ] [DecidableEq ι] [DecidableEq κ] [Nonempty κ]
    (C : Matrix (ι × κ) (ι × κ) ℂ)
    (hcomm : ∀ B : Matrix κ κ ℂ,
      C * ((1 : Matrix ι ι ℂ) ⊗ₖ B)
        = ((1 : Matrix ι ι ℂ) ⊗ₖ B) * C) :
    ∃ A : Matrix ι ι ℂ,
      C = A ⊗ₖ (1 : Matrix κ κ ℂ) := by
  classical
  obtain ⟨a0⟩ := ‹Nonempty κ›
  have key : ∀ (a b : κ) (i j : ι) (x y : κ),
      (if b = y then C (i, x) (j, a) else 0)
        = if a = x then C (i, b) (j, y) else 0 := by
    intro a b i j x y
    have h := congr_fun (congr_fun
      (hcomm (Matrix.single a b 1)) (i, x)) (j, y)
    simp only [Matrix.mul_apply, Matrix.kroneckerMap_apply,
      Matrix.one_apply, Matrix.single_apply,
      Fintype.sum_prod_type, ite_and, mul_ite, mul_zero,
      mul_one, ite_mul, zero_mul, one_mul,
      Finset.sum_ite_eq, Finset.mem_univ, if_true] at h
    by_cases hby : b = y <;> by_cases hax : a = x <;>
      simp_all [Finset.sum_ite_eq, Finset.sum_ite_eq']
  refine ⟨Matrix.of fun i j => C (i, a0) (j, a0), ?_⟩
  ext ⟨i, x⟩ ⟨j, y⟩
  by_cases hxy : x = y
  · subst hxy
    have h := key x a0 i j x a0
    rw [if_pos rfl, if_pos rfl] at h
    simp [Matrix.kroneckerMap_apply, Matrix.of_apply, h]
  · have h := key y y i j x y
    rw [if_pos rfl, if_neg (fun hyx => hxy hyx.symm)] at h
    simp [Matrix.kroneckerMap_apply, Matrix.of_apply, hxy, h]

end NCG
