/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Static channel samples and reflected Markov dynamics do not determine a terminal germ

The first witness is a smooth polynomial perturbation which vanishes at any prescribed finite bank
of nonzero sample times but has derivative one at zero.  The second keeps one symmetric reflected
Markov generator fixed while choosing either the zero or a nonzero inner Hamiltonian derivation on
a two-dimensional operation algebra.
-/

open Matrix

namespace NCG.StaticChannelsDoNotDetermineTerminalGerm

/-- Smooth interpolation factor vanishing at every prescribed nonzero sample time. -/
noncomputable def finiteSampleGerm (samples : Finset ℝ) (t : ℝ) : ℝ :=
  t * ∏ a ∈ samples, (1 - t / a)

theorem finiteSampleGerm_zero (samples : Finset ℝ) : finiteSampleGerm samples 0 = 0 := by
  simp [finiteSampleGerm]

theorem finiteSampleGerm_vanishes {samples : Finset ℝ} (hzero : 0 ∉ samples)
    {a : ℝ} (ha : a ∈ samples) : finiteSampleGerm samples a = 0 := by
  have hane : a ≠ 0 := by
    intro haz
    exact hzero (haz ▸ ha)
  unfold finiteSampleGerm
  rw [Finset.prod_eq_zero ha]
  · simp
  · simp [hane]

theorem finiteSampleGerm_deriv_zero (samples : Finset ℝ) :
    deriv (finiteSampleGerm samples) 0 = 1 := by
  let g : ℝ → ℝ := fun t => ∏ a ∈ samples, (1 - t / a)
  have hg : DifferentiableAt ℝ g 0 := by
    dsimp [g]
    fun_prop
  have hraw := (hasDerivAt_id (0 : ℝ)).mul hg.hasDerivAt
  have heq : finiteSampleGerm samples =ᶠ[nhds 0] (id * g : ℝ → ℝ) :=
    Filter.Eventually.of_forall (by intro t; simp [finiteSampleGerm, g])
  have h := hraw.congr_of_eventuallyEq heq
  have hvalue : g 0 = 1 := by simp [g]
  exact (h.congr_deriv (by simp [hvalue])).deriv

/-- Any finite static sample bank is shared by two smooth coefficient paths with different germs. -/
theorem finite_static_samples_do_not_determine_germ
    (samples : Finset ℝ) (hzero : 0 ∉ samples) :
    (∀ a ∈ samples, finiteSampleGerm samples a = 0) ∧
    finiteSampleGerm samples 0 = 0 ∧
    deriv (fun _t : ℝ => (0 : ℝ)) 0 = 0 ∧
    deriv (finiteSampleGerm samples) 0 = 1 := by
  exact ⟨fun _ ha => finiteSampleGerm_vanishes hzero ha,
    finiteSampleGerm_zero samples, by simp, finiteSampleGerm_deriv_zero samples⟩

/-- A fixed self-adjoint two-state reflected Markov generator. -/
def reflectedMarkovGenerator : Matrix (Fin 2) (Fin 2) ℝ :=
  !![-1, 1; 1, -1]

theorem reflectedMarkovGenerator_selfAdjoint :
    reflectedMarkovGeneratorᴴ = reflectedMarkovGenerator := by
  ext i j
  fin_cases i <;> fin_cases j <;> norm_num [reflectedMarkovGenerator]

def nontrivialHamiltonian : Matrix (Fin 2) (Fin 2) ℂ :=
  !![1, 0; 0, -1]

def transverseObservable : Matrix (Fin 2) (Fin 2) ℂ :=
  !![0, 1; 1, 0]

/-- The antisymmetric inner germ generated by a Hermitian coefficient. -/
def innerGerm (H A : Matrix (Fin 2) (Fin 2) ℂ) : Matrix (Fin 2) (Fin 2) ℂ :=
  -(Complex.I) • (H * A - A * H)

theorem zero_innerGerm :
    innerGerm 0 transverseObservable = 0 := by
  simp [innerGerm]

theorem nontrivial_innerGerm :
    innerGerm nontrivialHamiltonian transverseObservable ≠ 0 := by
  intro h
  have h01 := congrFun (congrFun h 0) 1
  norm_num [innerGerm, nontrivialHamiltonian, transverseObservable,
    Matrix.mul_apply, Fin.sum_univ_two] at h01

/-- The same symmetric reflected Markov generator is compatible with two different operation-algebra
inner germs, so it cannot supply the antisymmetric differential row by itself. -/
theorem reflected_markov_dynamics_do_not_determine_inner_germ :
    reflectedMarkovGeneratorᴴ = reflectedMarkovGenerator ∧
    innerGerm 0 transverseObservable = 0 ∧
    innerGerm nontrivialHamiltonian transverseObservable ≠ 0 :=
  ⟨reflectedMarkovGenerator_selfAdjoint, zero_innerGerm, nontrivial_innerGerm⟩

/-- Exact finite content of `thm:GT-NCG-static-no-germ`. -/
theorem static_coefficient_and_markov_dynamics_do_not_imply_terminal_germ
    (samples : Finset ℝ) (hzero : 0 ∉ samples) :
    ((∀ a ∈ samples, finiteSampleGerm samples a = 0) ∧
      finiteSampleGerm samples 0 = 0 ∧
      deriv (fun _t : ℝ => (0 : ℝ)) 0 = 0 ∧
      deriv (finiteSampleGerm samples) 0 = 1) ∧
    reflectedMarkovGeneratorᴴ = reflectedMarkovGenerator ∧
    innerGerm 0 transverseObservable = 0 ∧
    innerGerm nontrivialHamiltonian transverseObservable ≠ 0 := by
  exact ⟨finite_static_samples_do_not_determine_germ samples hzero,
    reflectedMarkovGenerator_selfAdjoint, zero_innerGerm, nontrivial_innerGerm⟩

end NCG.StaticChannelsDoNotDetermineTerminalGerm
