/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.SharpBanachExponentialTail
import Mathlib.Analysis.CStarAlgebra.ContinuousFunctionalCalculus.Basic

/-!
# Compressed exponential remainder and Store channel limit

This is the analytic (R5) clause of the Store-native route.  It proves the
exact compressed first-order expansion, its sharp exponential tail bound, and
the convergence of the rescaled one-Kraus occurrence forms.
-/

open Filter
open scoped Topology

namespace NCG

/-- The coherently calibrated link generated by `G` at complex time `s`. -/
noncomputable def storeUnitaryLink
    {A : Type*} [CStarAlgebra A] (G : A) (s : ℂ) : A :=
  NormedSpace.exp ((-Complex.I * s) • G)

/-- The compressed link between the protected right and left supports. -/
noncomputable def storeCompressedLink
    {A : Type*} [CStarAlgebra A] (pL pR G : A) (s : ℂ) : A :=
  pL * storeUnitaryLink G s * pR

/-- The compressed nonlinear remainder. -/
noncomputable def storeCompressedRemainder
    {A : Type*} [CStarAlgebra A] (pL pR G : A) (s : ℂ) : A :=
  pL * exponentialLinearRemainder ((-Complex.I * s) • G) * pR

/-- (R5) Exact first-order compressed expansion. -/
theorem storeCompressedLink_firstOrder
    {A : Type*} [CStarAlgebra A] (pL pR G : A)
    (hLR : pL * pR = 0) (s : ℂ) :
    storeCompressedLink pL pR G s =
      (-Complex.I * s) • (pL * G * pR) +
        storeCompressedRemainder pL pR G s := by
  have hexp : NormedSpace.exp ((-Complex.I * s) • G) =
      1 + (-Complex.I * s) • G +
        exponentialLinearRemainder ((-Complex.I * s) • G) := by
    unfold exponentialLinearRemainder
    abel
  rw [storeCompressedLink, storeUnitaryLink,
    storeCompressedRemainder, hexp]
  simp only [mul_add, add_mul, mul_one, hLR, zero_add]
  have hlinear : pL * ((-Complex.I * s) • G) * pR =
      (-Complex.I * s) • (pL * G * pR) := by
    rw [mul_smul_comm, smul_mul_assoc]
  rw [hlinear]

/-- (R5) The exact manuscript bound for the compressed exponential tail. -/
theorem norm_storeCompressedRemainder_le
    {A : Type*} [CStarAlgebra A] [NormOneClass A] (pL pR G : A)
    (hpL : ‖pL‖ ≤ 1) (hpR : ‖pR‖ ≤ 1) (s : ℂ) :
    ‖storeCompressedRemainder pL pR G s‖ ≤
      Real.exp (‖s‖ * ‖G‖) - 1 - ‖s‖ * ‖G‖ := by
  have hcompress : ‖storeCompressedRemainder pL pR G s‖ ≤
      ‖exponentialLinearRemainder ((-Complex.I * s) • G)‖ := by
    unfold storeCompressedRemainder
    calc
      ‖pL * exponentialLinearRemainder ((-Complex.I * s) • G) * pR‖
          ≤ ‖pL‖ * ‖exponentialLinearRemainder ((-Complex.I * s) • G)‖ * ‖pR‖ := by
            exact (norm_mul_le _ _).trans (mul_le_mul_of_nonneg_right
              (norm_mul_le _ _) (norm_nonneg _))
      _ ≤ 1 * ‖exponentialLinearRemainder ((-Complex.I * s) • G)‖ * 1 := by
            gcongr
      _ = ‖exponentialLinearRemainder ((-Complex.I * s) • G)‖ := by ring
  refine hcompress.trans ?_
  have htail := norm_exponentialLinearRemainder_le ((-Complex.I * s) • G)
  simpa [norm_smul, norm_mul] using htail

/-- The centered rescaled compressed Kraus operator. -/
noncomputable def rescaledStoreKraus
    {A : Type*} [CStarAlgebra A] (pL pR G : A) (s : ℂ) : A :=
  s⁻¹ • (pL * (storeUnitaryLink G s - 1) * pR)

/-- The rescaled compressed Kraus operator converges to `-i B`, where
`B = pL G pR`. -/
theorem tendsto_rescaledStoreKraus
    {A : Type*} [CStarAlgebra A] (pL pR G : A) :
    Tendsto (rescaledStoreKraus pL pR G)
      (𝓝[({0} : Set ℂ)ᶜ] 0)
      (𝓝 ((-Complex.I) • (pL * G * pR))) := by
  let X : A := (-Complex.I) • G
  have hslope :=
    (hasDerivAt_exp_smul_const (𝕂 := ℂ) X (0 : ℂ)).tendsto_slope_zero
  have hslope' : Tendsto
      (fun s : ℂ => s⁻¹ • (NormedSpace.exp (s • X) - 1))
      (𝓝[({0} : Set ℂ)ᶜ] 0) (𝓝 X) := by
    simpa [NormedSpace.exp_zero] using hslope
  have hpL : Tendsto (fun _ : ℂ => pL)
      (𝓝[({0} : Set ℂ)ᶜ] 0) (𝓝 pL) := tendsto_const_nhds
  have hpR : Tendsto (fun _ : ℂ => pR)
      (𝓝[({0} : Set ℂ)ᶜ] 0) (𝓝 pR) := tendsto_const_nhds
  have hcompressed := (hpL.mul hslope').mul hpR
  have hfun : (fun s : ℂ =>
      pL * (s⁻¹ • (NormedSpace.exp (s • X) - 1)) * pR) =
      rescaledStoreKraus pL pR G := by
    funext s
    unfold rescaledStoreKraus storeUnitaryLink X
    have hscale (c : ℂ) (Y : A) :
        pL * (c • Y) * pR = c • (pL * Y * pR) := by
      rw [mul_smul_comm, smul_mul_assoc]
    rw [hscale]
    congr 3
    rw [smul_smul]
    rw [mul_comm s (-Complex.I)]
  rw [hfun] at hcompressed
  simpa [X, smul_mul_assoc, mul_smul_comm] using hcompressed

/-- The rescaled one-Kraus occurrence forms converge pointwise to the nonzero
CP occurrence form generated by the odd corner `B`. -/
theorem tendsto_rescaledStoreOccurrence
    {A : Type*} [CStarAlgebra A] (pL pR G ρ : A) :
    Tendsto (fun s : ℂ =>
      rescaledStoreKraus pL pR G s * ρ *
        star (rescaledStoreKraus pL pR G s))
      (𝓝[({0} : Set ℂ)ᶜ] 0)
      (𝓝 ((pL * G * pR) * ρ * star (pL * G * pR))) := by
  have hK := tendsto_rescaledStoreKraus pL pR G
  have h := (hK.mul_const ρ).mul hK.star
  let B := pL * G * pR
  have hphase : ((-Complex.I) • B) * ρ * star ((-Complex.I) • B) =
      B * ρ * star B := by
    have hstar : star ((-Complex.I) • B) =
        Complex.I • star B := by
      rw [star_smul]
      norm_num
    rw [hstar]
    rw [smul_mul_assoc, mul_smul_comm, smul_mul_assoc, smul_smul]
    norm_num
  simpa only [B, hphase] using h

/-- The one-Kraus occurrence channel as a bounded linear superoperator. -/
noncomputable def krausOccurrenceCLM
    {A : Type*} [CStarAlgebra A] (K : A) : A →L[ℂ] A :=
  (ContinuousLinearMap.mulLeftRight ℂ A K) (star K)

/-- (R5) The rescaled occurrence channels converge in superoperator norm.
For finite matrix algebras this is equivalent to convergence in diamond norm,
since all norms on the finite-dimensional superoperator space induce the same
topology. -/
theorem tendsto_rescaledStoreOccurrence_superoperator
    {A : Type*} [CStarAlgebra A] (pL pR G : A) :
    Tendsto (fun s : ℂ =>
      krausOccurrenceCLM (rescaledStoreKraus pL pR G s))
      (𝓝[({0} : Set ℂ)ᶜ] 0)
      (𝓝 (krausOccurrenceCLM ((-Complex.I) • (pL * G * pR)))) := by
  have hK := tendsto_rescaledStoreKraus pL pR G
  have hcontinuous : Continuous (fun K : A => krausOccurrenceCLM K) := by
    unfold krausOccurrenceCLM
    exact (ContinuousLinearMap.mulLeftRight ℂ A).continuous.clm_apply
      continuous_star
  exact (hcontinuous.tendsto _).comp hK

end NCG
