/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.TetrahedralConnection

/-!
# Tetrahedral prototype curvature expansion and real-fibre obstruction

This module completes the analytic and explicit representation-theoretic parts
of `thm:tetrahedral-prototype-connection` that are not present in the elementary
orbit-product core.

* `exp_secondOrder_remainder_isBigO` is the genuine Banach-algebra exponential
  Taylor theorem with cubic remainder.
* `tetrahedral_prototype_connection` (re-exported from the core module)
  identifies the ordered second-order coefficient with the commutator.
* the `standardK`, `standardS`, and `standardR` calculations are the concrete
  untwisted real `S₄` standard-fibre computation: the stabilizer and reversal
  conditions leave only `ℝ(e₃-e₄)`, whose order-three orbit sum is
  `(1,1,1,-3)`, so area cancellation forces the generator to vanish.
-/

open Asymptotics Filter Finset Topology

namespace NCG

section PrototypeOrbit

variable {G M : Type*} [Group G] [Monoid M]

/-- Router obtained by transporting one prototype with a group
representation. -/
def transportedPrototype (ρ : G →* Units M) (U : Units M) (g : G) : Units M :=
  ρ g * U * (ρ g)⁻¹

/-- Choice-independence under an ordered-edge stabilizer element is exactly
commutation of the prototype with that stabilizer.  This is the abstract
one-orbit mechanism used for the `(34)` stabilizer of `(1,2)`. -/
theorem transportedPrototype_stabilizer_iff
    (ρ : G →* Units M) (U : Units M) (k : G) :
    transportedPrototype ρ U k = U ↔ Commute U (ρ k) := by
  constructor
  · intro h
    have hc := congrArg (fun z : Units M => z * ρ k) h
    have hk : ρ k * U = U * ρ k := by
      simpa [transportedPrototype, mul_assoc] using hc
    exact hk.symm
  · intro h
    unfold transportedPrototype
    rw [← h.eq]
    group

/-- Orientation reversal sends the prototype router to its inverse exactly
when the reversing symmetry intertwines `U` with `U⁻¹`.  For unitary routers,
inverse is adjoint, giving the manuscript's reversal equation. -/
theorem transportedPrototype_reversal_iff
    (ρ : G →* Units M) (U : Units M) (s : G) :
    transportedPrototype ρ U s = U⁻¹ ↔
      ρ s * U = U⁻¹ * ρ s := by
  constructor
  · intro h
    have hc := congrArg (fun z : Units M => z * ρ s) h
    simpa [transportedPrototype, mul_assoc] using hc
  · intro h
    unfold transportedPrototype
    rw [h]
    group

/-- Conjugation transports an ordered triangle product as a whole.  Thus all
triangles in one group orbit have conjugate holonomy. -/
theorem transportedPrototype_triangleProduct
    (ρ : G →* Units M) (U₁ U₂ U₃ : Units M) (g : G) :
    transportedPrototype ρ (U₁ * U₂ * U₃) g =
      transportedPrototype ρ U₁ g * transportedPrototype ρ U₂ g *
        transportedPrototype ρ U₃ g := by
  unfold transportedPrototype
  group

/-- Reversing an oriented triangle inverts its holonomy. -/
theorem reverseTriangleHolonomy (U₁ U₂ U₃ : Units M) :
    (U₁ * U₂ * U₃)⁻¹ = U₃⁻¹ * U₂⁻¹ * U₁⁻¹ := by
  group

end PrototypeOrbit

section ExponentialRemainder

variable {E : Type*} [NormedAddCommGroup E] [NormedSpace ℂ E]
  [CompleteSpace E]

/-- The matrix/Banach-algebra exponential has its actual second-order Taylor
polynomial with an `O(‖z‖³)` remainder. -/
theorem exp_secondOrder_remainder_isBigO :
    (fun z : E →L[ℂ] E => NormedSpace.exp z -
      (1 + z + (2 : ℂ)⁻¹ • z ^ 2))
      =O[𝓝 0] fun z : E →L[ℂ] E => ‖z‖ ^ 3 := by
  have h := (NormedSpace.exp_hasFPowerSeriesAt_zero
    (𝕂 := ℂ) (𝔸 := E →L[ℂ] E)).isBigO_sub_partialSum_pow 3
  refine h.congr' ?_ EventuallyEq.rfl
  filter_upwards with z
  simp only [zero_add]
  congr 1
  norm_num [FormalMultilinearSeries.partialSum,
    NormedSpace.expSeries_apply_eq, Finset.sum_range_succ]

/-- The second-order exponential expansion along the complex line generated by
`-A`, in the scalar form used by the tetrahedral holonomy. -/
theorem exp_negLine_secondOrder_remainder_isBigO (A : E →L[ℂ] E) :
    (fun h : ℂ => NormedSpace.exp (-h • A) -
      (1 - h • A + (h ^ 2 / 2) • A ^ 2))
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
  have htend : Tendsto (fun h : ℂ => -h • A) (𝓝 0) (𝓝 0) := by
    have hc : Continuous (fun h : ℂ => -h • A) :=
      continuous_id.neg.smul continuous_const
    simpa only [neg_zero, zero_smul] using hc.tendsto (0 : ℂ)
  have hmain := exp_secondOrder_remainder_isBigO.comp_tendsto htend
  have hnorm : (fun h : ℂ => ‖-h • A‖ ^ 3)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    refine IsBigO.of_bound (‖A‖ ^ 3) ?_
    filter_upwards with h
    simp only [norm_pow, norm_smul, norm_neg, norm_norm]
    ring_nf
    exact le_rfl
  refine (hmain.trans hnorm).congr' ?_ EventuallyEq.rfl
  filter_upwards with h
  simp only [Function.comp_apply]
  rw [neg_smul, neg_pow, smul_pow, smul_smul]
  norm_num
  congr 1
  · module
  · congr 1
    field_simp
    ring

/-- Linear part of `exp (-hA)`. -/
def expLinearTerm (A : E →L[ℂ] E) (h : ℂ) : E →L[ℂ] E := -h • A

/-- Quadratic part of `exp (-hA)`. -/
def expQuadraticTerm (A : E →L[ℂ] E) (h : ℂ) : E →L[ℂ] E :=
  (h ^ 2 / 2) • A ^ 2

/-- The quadratic Taylor polynomial of `exp (-hA)`. -/
def expQuadraticPolynomial (A : E →L[ℂ] E) (h : ℂ) : E →L[ℂ] E :=
  1 + expLinearTerm A h + expQuadraticTerm A h

theorem expLinearTerm_isBigO (A : E →L[ℂ] E) :
    expLinearTerm A =O[𝓝 0] fun h : ℂ => ‖h‖ := by
  refine IsBigO.of_bound ‖A‖ ?_
  filter_upwards with h
  simp [expLinearTerm, mul_comm]

theorem expQuadraticTerm_isBigO (A : E →L[ℂ] E) :
    expQuadraticTerm A =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := by
  refine IsBigO.of_bound (‖A ^ 2‖ / 2) ?_
  filter_upwards with h
  simp only [expQuadraticTerm, norm_smul, norm_div, norm_pow, norm_ofNat,
    norm_norm]
  have htwo : ‖(2 : ℂ)‖ = 2 := by norm_num
  rw [htwo]
  ring_nf
  exact le_rfl

/-- Near zero, every norm power of order at least three is `O(‖h‖³)`. -/
theorem norm_pow_isBigO_norm_pow_three {n : ℕ} (hn : 3 ≤ n) :
    (fun h : ℂ => ‖h‖ ^ n) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
  refine IsBigO.of_bound 1 ?_
  filter_upwards [Metric.ball_mem_nhds (0 : ℂ) one_pos] with h hh
  have hle : ‖h‖ ≤ 1 := by
    simpa [Metric.mem_ball, dist_zero_right] using hh.le
  simp only [norm_pow, norm_norm, one_mul]
  exact pow_le_pow_right_of_le_one' hle hn

theorem expQuadraticPolynomial_tendsto_one (A : E →L[ℂ] E) :
    Tendsto (expQuadraticPolynomial A) (𝓝 0) (𝓝 1) := by
  have hc : Continuous (expQuadraticPolynomial A) := by
    fun_prop
  simpa [expQuadraticPolynomial, expLinearTerm, expQuadraticTerm] using
    hc.tendsto (0 : ℂ)

/-- The literal ordered-product curvature expansion.  When the three orbit
generators sum to zero, the product has no linear term and its quadratic term
is the commutator; all remaining terms are cubic in norm. -/
theorem ordered_exp_product_curvature_remainder_isBigO
    (A₁ A₂ A₃ : E →L[ℂ] E) (hsum : A₁ + A₂ + A₃ = 0) :
    (fun h : ℂ =>
      NormedSpace.exp (-h • A₁) * NormedSpace.exp (-h • A₂) *
          NormedSpace.exp (-h • A₃) -
        (1 + (h ^ 2 / 2) • (A₁ * A₂ - A₂ * A₁)))
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
  let L₁ := expLinearTerm A₁
  let L₂ := expLinearTerm A₂
  let L₃ := expLinearTerm A₃
  let Q₁ := expQuadraticTerm A₁
  let Q₂ := expQuadraticTerm A₂
  let Q₃ := expQuadraticTerm A₃
  let P₁ := expQuadraticPolynomial A₁
  let P₂ := expQuadraticPolynomial A₂
  let P₃ := expQuadraticPolynomial A₃
  let S₁ : ℂ → E →L[ℂ] E := fun h => L₁ h + L₂ h
  let S₂ : ℂ → E →L[ℂ] E := fun h => Q₁ h + Q₂ h + L₁ h * L₂ h
  let R₁₂ : ℂ → E →L[ℂ] E := fun h =>
    L₁ h * Q₂ h + Q₁ h * L₂ h + Q₁ h * Q₂ h

  have hL₁ : L₁ =O[𝓝 0] fun h : ℂ => ‖h‖ := expLinearTerm_isBigO A₁
  have hL₂ : L₂ =O[𝓝 0] fun h : ℂ => ‖h‖ := expLinearTerm_isBigO A₂
  have hL₃ : L₃ =O[𝓝 0] fun h : ℂ => ‖h‖ := expLinearTerm_isBigO A₃
  have hQ₁ : Q₁ =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := expQuadraticTerm_isBigO A₁
  have hQ₂ : Q₂ =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := expQuadraticTerm_isBigO A₂
  have hQ₃ : Q₃ =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := expQuadraticTerm_isBigO A₃

  have hL₁L₂ : (fun h => L₁ h * L₂ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := by
    simpa [pow_two] using hL₁.mul hL₂
  have hS₁ : S₁ =O[𝓝 0] fun h : ℂ => ‖h‖ := by
    simpa [S₁] using hL₁.add hL₂
  have hS₂ : S₂ =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 2 := by
    simpa [S₂] using (hQ₁.add hQ₂).add hL₁L₂

  have hL₁Q₂ : (fun h => L₁ h * Q₂ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [pow_succ, pow_two, mul_assoc] using hL₁.mul hQ₂
  have hQ₁L₂ : (fun h => Q₁ h * L₂ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [pow_succ, pow_two, mul_assoc, mul_comm] using hQ₁.mul hL₂
  have hQ₁Q₂_four : (fun h => Q₁ h * Q₂ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 4 := by
    simpa [pow_succ, pow_two, mul_assoc] using hQ₁.mul hQ₂
  have hQ₁Q₂ : (fun h => Q₁ h * Q₂ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 :=
    hQ₁Q₂_four.trans (norm_pow_isBigO_norm_pow_three (n := 4) (by omega))
  have hR₁₂ : R₁₂ =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [R₁₂] using (hL₁Q₂.add hQ₁L₂).add hQ₁Q₂

  have hP₃ : P₃ =O[𝓝 0] fun _h : ℂ => (1 : ℝ) := by
    exact isBigO_const_of_tendsto (expQuadraticPolynomial_tendsto_one A₃)
      (one_ne_zero : (1 : ℝ) ≠ 0)
  have hR₁₂P₃ : (fun h => R₁₂ h * P₃ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa using hR₁₂.mul hP₃
  have hS₂L₃ : (fun h => S₂ h * L₃ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [pow_succ, pow_two, mul_assoc, mul_comm] using hS₂.mul hL₃
  have hS₁Q₃ : (fun h => S₁ h * Q₃ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [pow_succ, pow_two, mul_assoc] using hS₁.mul hQ₃
  have hS₂Q₃_four : (fun h => S₂ h * Q₃ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 4 := by
    simpa [pow_succ, pow_two, mul_assoc] using hS₂.mul hQ₃
  have hS₂Q₃ : (fun h => S₂ h * Q₃ h) =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 :=
    hS₂Q₃_four.trans (norm_pow_isBigO_norm_pow_three (n := 4) (by omega))
  have hpoly : (fun h => R₁₂ h * P₃ h + S₂ h * L₃ h +
      S₂ h * Q₃ h + S₁ h * Q₃ h)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 :=
    ((hR₁₂P₃.add hS₂L₃).add hS₂Q₃).add hS₁Q₃

  have hrem₁ : (fun h => NormedSpace.exp (-h • A₁) - P₁ h)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [P₁, expQuadraticPolynomial, expLinearTerm, expQuadraticTerm] using
      exp_negLine_secondOrder_remainder_isBigO A₁
  have hrem₂ : (fun h => NormedSpace.exp (-h • A₂) - P₂ h)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [P₂, expQuadraticPolynomial, expLinearTerm, expQuadraticTerm] using
      exp_negLine_secondOrder_remainder_isBigO A₂
  have hrem₃ : (fun h => NormedSpace.exp (-h • A₃) - P₃ h)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    simpa [P₃, expQuadraticPolynomial, expLinearTerm, expQuadraticTerm] using
      exp_negLine_secondOrder_remainder_isBigO A₃
  have hE₁ : (fun h => NormedSpace.exp (-h • A₁)) =O[𝓝 0] fun _h : ℂ => (1 : ℝ) :=
    isBigO_const_of_tendsto
      ((continuous_const.neg.smul continuous_const).cexp.tendsto (0 : ℂ))
      (one_ne_zero : (1 : ℝ) ≠ 0)
  have hE₂ : (fun h => NormedSpace.exp (-h • A₂)) =O[𝓝 0] fun _h : ℂ => (1 : ℝ) :=
    isBigO_const_of_tendsto
      ((continuous_const.neg.smul continuous_const).cexp.tendsto (0 : ℂ))
      (one_ne_zero : (1 : ℝ) ≠ 0)
  have hP₁ : P₁ =O[𝓝 0] fun _h : ℂ => (1 : ℝ) :=
    isBigO_const_of_tendsto (expQuadraticPolynomial_tendsto_one A₁)
      (one_ne_zero : (1 : ℝ) ≠ 0)
  have hP₂ : P₂ =O[𝓝 0] fun _h : ℂ => (1 : ℝ) :=
    isBigO_const_of_tendsto (expQuadraticPolynomial_tendsto_one A₂)
      (one_ne_zero : (1 : ℝ) ≠ 0)
  have hExpPoly : (fun h =>
      NormedSpace.exp (-h • A₁) * NormedSpace.exp (-h • A₂) *
          NormedSpace.exp (-h • A₃) - P₁ h * P₂ h * P₃ h)
      =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
    have hfirst : (fun h =>
        (NormedSpace.exp (-h • A₁) - P₁ h) * P₂ h * P₃ h)
        =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
      simpa using (hrem₁.mul hP₂).mul hP₃
    have hsecond : (fun h =>
        NormedSpace.exp (-h • A₁) *
          (NormedSpace.exp (-h • A₂) - P₂ h) * P₃ h)
        =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
      simpa [mul_comm] using (hE₁.mul hrem₂).mul hP₃
    have hthird : (fun h =>
        NormedSpace.exp (-h • A₁) * NormedSpace.exp (-h • A₂) *
          (NormedSpace.exp (-h • A₃) - P₃ h))
        =O[𝓝 0] fun h : ℂ => ‖h‖ ^ 3 := by
      simpa using (hE₁.mul hE₂).mul hrem₃
    refine (hfirst.add hsecond |>.add hthird).congr' ?_ EventuallyEq.rfl
    filter_upwards with h
    noncomm_ring

  refine (hExpPoly.add hpoly).congr' ?_ EventuallyEq.rfl
  filter_upwards with h
  have hlin : S₁ h + L₃ h = 0 := by
    dsimp [S₁, L₁, L₂, L₃, expLinearTerm]
    rw [← neg_smul, ← neg_smul, ← neg_smul, ← smul_add, ← smul_add, hsum,
      smul_zero]
  have hcoeff :=
    (tetrahedral_prototype_connection
      (M := Unit) (𝒜 := E →L[ℂ] E) (W := ℂ)).2.1 A₁ A₂ A₃ hsum
  have hquad : S₂ h + S₁ h * L₃ h + Q₃ h =
      (h ^ 2 / 2) • (A₁ * A₂ - A₂ * A₁) := by
    calc
      S₂ h + S₁ h * L₃ h + Q₃ h =
          h ^ 2 • ((1 / 2 : ℂ) • (A₁ ^ 2 + A₂ ^ 2 + A₃ ^ 2) +
            (A₁ * A₂ + A₁ * A₃ + A₂ * A₃)) := by
              dsimp [S₂, S₁, L₁, L₂, L₃, Q₁, Q₂, Q₃,
                expLinearTerm, expQuadraticTerm]
              module
      _ = (h ^ 2 / 2) • (A₁ * A₂ - A₂ * A₁) := by
        rw [hcoeff]
        module
  have hproduct : P₁ h * P₂ h * P₃ h =
      1 + (S₁ h + L₃ h) + (S₂ h + S₁ h * L₃ h + Q₃ h) +
        (R₁₂ h * P₃ h + S₂ h * L₃ h + S₂ h * Q₃ h + S₁ h * Q₃ h) := by
    dsimp [P₁, P₂, P₃, S₁, S₂, R₁₂, expQuadraticPolynomial]
    noncomm_ring
  rw [hproduct, hlin, hquad]
  noncomm_ring

end ExponentialRemainder

section StandardTetrahedralFibre

/-- The mean-zero standard tetrahedral fibre. -/
def TetrahedralStandardVector := {a : Fin 4 → ℝ // ∑ i, a i = 0}

/-- Coordinate action of the odd stabilizer `(34)` on the permutation
representation. -/
def standardK (a : Fin 4 → ℝ) : Fin 4 → ℝ :=
  ![a 0, a 1, a 3, a 2]

/-- Coordinate action of the odd edge reversal `(12)`. -/
def standardS (a : Fin 4 → ℝ) : Fin 4 → ℝ :=
  ![a 1, a 0, a 2, a 3]

/-- Coordinate action of the order-three element `(123)`, fixing vertex four. -/
def standardR (a : Fin 4 → ℝ) : Fin 4 → ℝ :=
  ![a 2, a 0, a 1, a 3]

/-- The unique possible generator line after the stabilizer and reversal
relations. -/
def e₃Sube₄ : Fin 4 → ℝ := ![0, 0, 1, -1]

/-- The stabilizer/reversal equations on the untwisted real standard fibre
leave exactly the line `ℝ(e₃-e₄)`. -/
theorem standard_stabilizer_reversal_line (a : Fin 4 → ℝ)
    (hk : standardK a = -a) (hs : standardS a = a) :
    ∃ t : ℝ, a = t • e₃Sube₄ := by
  have hk0 := congrFun hk 0
  have hk1 := congrFun hk 1
  have hk2 := congrFun hk 2
  have hk3 := congrFun hk 3
  have hs01 := congrFun hs 0
  simp [standardK] at hk0 hk1 hk2 hk3
  simp [standardS] at hs01
  refine ⟨a 2, ?_⟩
  funext i
  fin_cases i <;> simp [e₃Sube₄] <;> linarith

/-- The order-three orbit of `e₃-e₄` has the manuscript's explicit nonzero
sum `(1,1,1,-3)`. -/
theorem standard_orderThree_orbitSum :
    e₃Sube₄ + standardR e₃Sube₄ + standardR (standardR e₃Sube₄) =
      ![1, 1, 1, -3] := by
  funext i
  fin_cases i
  · change (0 : ℝ) + 1 + 0 = 1
    norm_num
  · change (0 : ℝ) + 0 + 1 = 1
    norm_num
  · change (1 : ℝ) + 0 + 0 = 1
    norm_num
  · change (-1 : ℝ) + -1 + -1 = -3
    norm_num

/-- The explicit orbit sum is nonzero. -/
theorem standard_orderThree_orbitSum_ne_zero :
    e₃Sube₄ + standardR e₃Sube₄ + standardR (standardR e₃Sube₄) ≠ 0 := by
  rw [standard_orderThree_orbitSum]
  intro h
  have h0 := congrFun h 0
  norm_num at h0

/-- On the bare untwisted real standard tetrahedral fibre, stabilizer,
reversal, and area cancellation force the infinitesimal connection generator
to vanish. -/
theorem standard_tetrahedral_denseConnection_noGo (a : Fin 4 → ℝ)
    (hk : standardK a = -a) (hs : standardS a = a)
    (harea : a + standardR a + standardR (standardR a) = 0) :
    a = 0 := by
  obtain ⟨t, rfl⟩ := standard_stabilizer_reversal_line a hk hs
  have h0 := congrFun harea 0
  simp [standardR, e₃Sube₄] at h0
  have ht : t = 0 := by linarith
  simp [ht]

/-- Scalar/trivial fibres have no nonzero infinitesimal area-scaled
connection: the orbit sum is three copies of the same generator. -/
theorem trivialFibre_areaCancellation_noGo (A : ℂ) (harea : A + A + A = 0) :
    A = 0 := by
  linear_combination (1 / 3 : ℂ) * harea

end StandardTetrahedralFibre

end NCG
