/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Grand.EquivariantMultiplicityFactorization
import NCG.Grand.FinalPanels1

/-!
# Tetrahedral provenance isotypic localization

This file gives a concrete Schur computation for the standard three-dimensional
representation of `S₄`.  The adjacent transpositions `(01)`, `(12)`, and `(23)`
act on the basis `e₀-e₃, e₁-e₃, e₂-e₃` by the three matrices below.  A direct
entry calculation proves that their common commutant consists exactly of the
scalar matrices.  Consequently an equivariant synthesis into a standard
isotypic block factors uniquely through its multiplicity space.
-/

open Matrix
open scoped Kronecker

namespace NCG

/-- Adjacent transpositions generating `S₄` on its standard carrier. -/
inductive StandardS4Generator
  | swap01
  | swap12
  | swap23
  deriving DecidableEq

/-- The standard `S₄` carrier in the basis
`e₀-e₃, e₁-e₃, e₂-e₃`. -/
def standardS4Carrier :
    StandardS4Generator → Matrix (Fin 3) (Fin 3) ℂ
  | .swap01 => !![0, 1, 0; 1, 0, 0; 0, 0, 1]
  | .swap12 => !![1, 0, 0; 0, 0, 1; 0, 1, 0]
  | .swap23 => !![1, 0, 0; 0, 1, 0; -1, -1, -1]

/-- Concrete Schur lemma for the standard tetrahedral carrier: a matrix
commuting with the three adjacent transpositions is uniquely scalar. -/
theorem standardS4Carrier_commutant_is_scalar
    (Z : Matrix (Fin 3) (Fin 3) ℂ)
    (hZ : ∀ q, standardS4Carrier q * Z = Z * standardS4Carrier q) :
    ∃! c : ℂ, Z = c • (1 : Matrix (Fin 3) (Fin 3) ℂ) := by
  have hA00 := congrFun (congrFun (hZ .swap01) (0 : Fin 3)) (0 : Fin 3)
  have hA01 := congrFun (congrFun (hZ .swap01) (0 : Fin 3)) (1 : Fin 3)
  have hA02 := congrFun (congrFun (hZ .swap01) (0 : Fin 3)) (2 : Fin 3)
  have hA20 := congrFun (congrFun (hZ .swap01) (2 : Fin 3)) (0 : Fin 3)
  have hB01 := congrFun (congrFun (hZ .swap12) (0 : Fin 3)) (1 : Fin 3)
  have hB10 := congrFun (congrFun (hZ .swap12) (1 : Fin 3)) (0 : Fin 3)
  have hB11 := congrFun (congrFun (hZ .swap12) (1 : Fin 3)) (1 : Fin 3)
  have hB12 := congrFun (congrFun (hZ .swap12) (1 : Fin 3)) (2 : Fin 3)
  have hC02 := congrFun (congrFun (hZ .swap23) (0 : Fin 3)) (2 : Fin 3)
  simp [standardS4Carrier, Matrix.mul_apply, Fin.sum_univ_succ] at hA00 hA01 hA02 hA20
  simp [standardS4Carrier, Matrix.mul_apply, Fin.sum_univ_succ] at hB01 hB10 hB11 hB12
  simp [standardS4Carrier, Matrix.mul_apply, Fin.sum_univ_succ] at hC02
  have h02 : Z 0 2 = 0 := by linear_combination hC02 / 2
  have h01 : Z 0 1 = 0 := hB01.trans h02
  have h10 : Z 1 0 = 0 := hA00.trans h01
  have h12 : Z 1 2 = 0 := hA02.trans h02
  have h20 : Z 2 0 = 0 := hB10.trans h10
  have h21 : Z 2 1 = 0 := hB11.trans h12
  refine ⟨Z 0 0, ?_, ?_⟩
  · ext i j
    fin_cases i <;> fin_cases j <;>
      simp [Matrix.smul_apply, hA01, hB12,
        h01, h02, h10, h12, h20, h21]
  · intro c hc
    have hc00 := congrFun (congrFun hc (0 : Fin 3)) (0 : Fin 3)
    simpa [Matrix.smul_apply, Matrix.one_apply] using hc00.symm

/-- A multiplicity vector regarded as the single-column matrix from the
multiplicity-one source. -/
def provenanceColumn {m : Type*} (p : m → ℂ) : Matrix m PUnit ℂ :=
  fun a _ => p a

/-- Schur localization for a tetrahedral provenance source.  In carrier-first
coordinates, every equivariant map from one standard carrier to the standard
isotypic block is uniquely `I_[31] ⊗ p`.  This is the coordinate-swapped form
of the manuscript's `p ⊗ I_[31]`. -/
theorem standardS4_equivariantSynthesis_unique_factorization
    {m : Type*} [Fintype m] [DecidableEq m]
    (Y : Matrix (Fin 3 × m) (Fin 3 × PUnit) ℂ)
    (hY : ∀ q,
      (standardS4Carrier q ⊗ₖ (1 : Matrix m m ℂ)) * Y =
        Y * (standardS4Carrier q ⊗ₖ (1 : Matrix PUnit PUnit ℂ))) :
    ∃! p : m → ℂ,
      Y = (1 : Matrix (Fin 3) (Fin 3) ℂ) ⊗ₖ provenanceColumn p := by
  classical
  obtain ⟨F, hF, hF_unique⟩ :=
    equivariantOperator_unique_kroneckerFactorization
      standardS4Carrier standardS4Carrier
      (1 : Matrix (Fin 3) (Fin 3) ℂ)
      standardS4Carrier_commutant_is_scalar Y hY
  let p : m → ℂ := fun a => F a PUnit.unit
  have hFp : F = provenanceColumn p := by
    ext a u
    cases u
    rfl
  refine ⟨p, hF.trans (congrArg
    (fun A : Matrix m PUnit ℂ =>
      (1 : Matrix (Fin 3) (Fin 3) ℂ) ⊗ₖ A) hFp), ?_⟩
  intro q hq
  have hqF : provenanceColumn q = F := hF_unique _ hq
  funext a
  have ha := congrFun (congrFun hqF a) PUnit.unit
  simpa [provenanceColumn, p] using ha

/-- Normalized projector onto the multiplicity line generated by `p`. -/
noncomputable def tetrahedralMultiplicityProjector
    {m : Type*} [Fintype m] (p : m → ℂ) :
    Matrix m m ℂ :=
  (star p ⬝ᵥ p)⁻¹ • Matrix.vecMulVec p (star p)

/-- The provenance projector in the manuscript's multiplicity-first tensor
ordering: `|p⟩⟨p| / ‖p‖² ⊗ I_[31]`. -/
noncomputable def tetrahedralProvenanceProjector
    {m : Type*} [Fintype m] (p : m → ℂ) :
    Matrix (m × Fin 3) (m × Fin 3) ℂ :=
  tetrahedralMultiplicityProjector p ⊗ₖ
    (1 : Matrix (Fin 3) (Fin 3) ℂ)

/-- The displayed tetrahedral provenance projector is an orthogonal algebraic
projector whenever the source vector is nonzero. -/
theorem tetrahedralProvenanceProjector_idempotent
    {m : Type*} [Fintype m] (p : m → ℂ) (hp : star p ⬝ᵥ p ≠ 0) :
    tetrahedralProvenanceProjector p * tetrahedralProvenanceProjector p =
      tetrahedralProvenanceProjector p := by
  rw [tetrahedralProvenanceProjector, ← Matrix.mul_kronecker_mul,
    tetrahedralMultiplicityProjector,
    rank_one_projector_idempotent p hp, Matrix.one_mul]

/-- The multiplicity projector has one-dimensional range: every projected
vector is an explicit scalar multiple of `p`.  Hence the provenance short can
remove at most one multiplicity direction in the standard isotypic block. -/
theorem tetrahedralMultiplicityProjector_range_is_line
    {m : Type*} [Fintype m] (p x : m → ℂ) :
    (tetrahedralMultiplicityProjector p).mulVec x =
      ((star p ⬝ᵥ p)⁻¹ * (star p ⬝ᵥ x)) • p := by
  rw [tetrahedralMultiplicityProjector, Matrix.smul_mulVec,
    Matrix.vecMulVec_mulVec]
  simp [smul_smul, mul_comm]

/-- The four connected `S₄` isotypes inequivalent to the standard `[31]`
carrier. -/
inductive NonstandardConnectedS4Isotype
  | trivial
  | partition22
  | partition211
  | sign
  deriving DecidableEq

/-- An orthogonal isotypic coordinate model: the first summand contains the
four nonstandard isotypes and the second is the standard multiplicity block. -/
abbrev ConnectedS4IsotypicCarrier (m : Type*) :=
  (NonstandardConnectedS4Isotype → ℂ) × ((m × Fin 3) → ℂ)

/-- Provenance short on the complete isotypic carrier.  It is zero on every
inequivalent summand and applies the displayed projector only on `[31]`. -/
noncomputable def tetrahedralProvenanceShort
    {m : Type*} [Fintype m]
    (p : m → ℂ) (x : ConnectedS4IsotypicCarrier m) :
    ConnectedS4IsotypicCarrier m :=
  (0, (tetrahedralProvenanceProjector p).mulVec x.2)

/-- Trivial, `[22]`, `[211]`, and sign witnesses are automatically killed by
the provenance projector, i.e. are provenance independent. -/
theorem tetrahedralProvenanceShort_kills_nonstandard_isotypes
    {m : Type*} [Fintype m] (p : m → ℂ)
    (w : NonstandardConnectedS4Isotype → ℂ) :
    tetrahedralProvenanceShort p
      (w, (0 : (m × Fin 3) → ℂ)) = 0 := by
  simp [tetrahedralProvenanceShort]

/-- The complete provenance short changes only the standard isotypic block. -/
theorem tetrahedralProvenanceShort_preserves_nonstandard_component
    {m : Type*} [Fintype m] (p : m → ℂ)
    (x : ConnectedS4IsotypicCarrier m) :
    (tetrahedralProvenanceShort p x).1 = 0 := rfl

/-- The block-localized provenance short is itself idempotent. -/
theorem tetrahedralProvenanceShort_idempotent
    {m : Type*} [Fintype m] (p : m → ℂ) (hp : star p ⬝ᵥ p ≠ 0)
    (x : ConnectedS4IsotypicCarrier m) :
    tetrahedralProvenanceShort p (tetrahedralProvenanceShort p x) =
      tetrahedralProvenanceShort p x := by
  apply Prod.ext
  · rfl
  · change (tetrahedralProvenanceProjector p).mulVec
        ((tetrahedralProvenanceProjector p).mulVec x.2) =
      (tetrahedralProvenanceProjector p).mulVec x.2
    rw [Matrix.mulVec_mulVec,
      tetrahedralProvenanceProjector_idempotent p hp]

/-- **`cor:S4-provenance-isotypic`.**  The complete tetrahedral provenance
localization certificate in the standard-isotypic coordinate decomposition:
Schur factorization is unique, the displayed projector is idempotent, its
multiplicity range is a line, and every inequivalent connected isotype is
killed while the short remains confined to and idempotent on the standard
block. -/
theorem tetrahedral_provenance_isotypic_localization
    {m : Type*} [Fintype m] [DecidableEq m]
    (Y : Matrix (Fin 3 × m) (Fin 3 × PUnit) ℂ)
    (hY : ∀ q,
      (standardS4Carrier q ⊗ₖ (1 : Matrix m m ℂ)) * Y =
        Y * (standardS4Carrier q ⊗ₖ (1 : Matrix PUnit PUnit ℂ)))
    (p : m → ℂ) (hp : star p ⬝ᵥ p ≠ 0) :
    (∃! q : m → ℂ,
        Y = (1 : Matrix (Fin 3) (Fin 3) ℂ) ⊗ₖ provenanceColumn q) ∧
      tetrahedralProvenanceProjector p * tetrahedralProvenanceProjector p =
        tetrahedralProvenanceProjector p ∧
      (∀ x : m → ℂ,
        (tetrahedralMultiplicityProjector p).mulVec x =
          ((star p ⬝ᵥ p)⁻¹ * (star p ⬝ᵥ x)) • p) ∧
      (∀ w : NonstandardConnectedS4Isotype → ℂ,
        tetrahedralProvenanceShort p
          (w, (0 : (m × Fin 3) → ℂ)) = 0) ∧
      (∀ x : ConnectedS4IsotypicCarrier m,
        (tetrahedralProvenanceShort p x).1 = 0) ∧
      (∀ x : ConnectedS4IsotypicCarrier m,
        tetrahedralProvenanceShort p (tetrahedralProvenanceShort p x) =
          tetrahedralProvenanceShort p x) := by
  exact ⟨standardS4_equivariantSynthesis_unique_factorization Y hY,
    tetrahedralProvenanceProjector_idempotent p hp,
    tetrahedralMultiplicityProjector_range_is_line p,
    tetrahedralProvenanceShort_kills_nonstandard_isotypes p,
    tetrahedralProvenanceShort_preserves_nonstandard_component p,
    tetrahedralProvenanceShort_idempotent p hp⟩

end NCG
