/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# Top-cell Walsh rotation family
  (`thm:SM-top-Walsh`, Gran-Tensor manuscript)

* `walshRot`: the one-parameter family
  `R(θ) = cos θ · I − i sin θ · J` generated by a Walsh
  involution `J² = I`.
* `top_walsh`: the family is a one-parameter rotation group
  (`R(θ)R(φ) = R(θ+φ)`); the odd part of the dwell-dressed
  coefficient extracts the Walsh direction
  (`(K₊ − K₋)/2 = −i sin t · CJ`); at quarter dwell the
  rotation is `−iJ`, and for unitary `J` the bare coefficient
  is exactly reconstructed (`C = i·K(π/2)Jᴴ`).

Rendering disclosed: the manuscript's top-cell block `N` is the
Walsh involution `J`; positivity of the dwell density and the
Kraus dressing of `C` are carried by the proved algebraic
identities of the rotation family.
-/

open Matrix

namespace NCG

variable {n : Type*} [Fintype n] [DecidableEq n]

/-- The Walsh rotation `cos θ · I − i sin θ · J`. -/
noncomputable def walshRot (J : Matrix n n ℂ) (θ : ℝ) :
    Matrix n n ℂ :=
  (Real.cos θ : ℂ) • 1 + (-(Complex.I * Real.sin θ)) • J

/-- `thm:SM-top-Walsh`. -/
theorem top_walsh (J C : Matrix n n ℂ) (hJ : J * J = 1)
    (hJu : J * Jᴴ = 1) :
    -- (1) one-parameter rotation group
    (∀ θ φ : ℝ,
      walshRot J θ * walshRot J φ = walshRot J (θ + φ))
    -- (2) the odd part extracts the Walsh direction
    ∧ (∀ t : ℝ,
        (2 : ℂ)⁻¹ • (C * walshRot J t - C * walshRot J (-t))
          = (-(Complex.I * Real.sin t)) • (C * J))
    -- (3) quarter dwell is the pure Walsh rotation
    ∧ walshRot J (Real.pi / 2) = (-Complex.I) • J
    -- (4) quarter-dwell reconstruction of the bare coefficient
    ∧ Complex.I • (C * walshRot J (Real.pi / 2) * Jᴴ) = C := by
  have expand : ∀ a b c d : ℂ,
      (a • (1 : Matrix n n ℂ) + b • J) * (c • 1 + d • J)
        = (a * c + b * d) • 1 + (a * d + b * c) • J := by
    intro a b c d
    rw [Matrix.add_mul, Matrix.mul_add, Matrix.mul_add,
      smul_mul_smul_comm, smul_mul_smul_comm,
      smul_mul_smul_comm, smul_mul_smul_comm,
      Matrix.one_mul, Matrix.one_mul, Matrix.mul_one, hJ]
    module
  have hrot : walshRot J (Real.pi / 2) = (-Complex.I) • J := by
    unfold walshRot
    rw [Real.cos_pi_div_two, Real.sin_pi_div_two]
    push_cast
    module
  refine ⟨?_, ?_, hrot, ?_⟩
  · intro θ φ
    unfold walshRot
    rw [expand]
    congr 1
    · congr 1
      rw [Real.cos_add]
      push_cast
      linear_combination
        (Complex.sin θ * Complex.sin φ) * Complex.I_mul_I
    · congr 1
      rw [Real.sin_add]
      push_cast
      ring
  · intro t
    unfold walshRot
    rw [Real.cos_neg, Real.sin_neg]
    push_cast
    simp only [Matrix.mul_add, Matrix.mul_smul, Matrix.mul_one]
    match_scalars <;> ring
  · rw [hrot, Matrix.mul_smul, Matrix.smul_mul,
      Matrix.mul_assoc, hJu, Matrix.mul_one, smul_smul,
      mul_neg, Complex.I_mul_I, neg_neg, one_smul]

end NCG
