/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import Mathlib

/-!
# The weak reset generation: two overlapping lines generate `M₂`

Machinery for `thm:SM-active-internal-commutant` (the SM.0n weak-reset packet):
two rank-one projections onto **distinct, non-orthogonal** lines of `ℂ²` generate
the full matrix algebra `M₂(ℂ)`:

* `vecMulVec_mul`: the rank-one product rule
  `|a⟩⟨b| · |c⟩⟨d| = ⟨b, c⟩ · |a⟩⟨d|`;
* products of the two projections give all four line-to-line rank-one maps;
* expanding the standard basis through the (independent) pair of line vectors
  expresses every matrix unit, so the generated algebra is everything
  (`two_lines_generate`).
-/

open Finset Matrix

namespace NCG
namespace WeakReset

/-- A subalgebra of `2×2` matrices containing all four matrix units is
everything. -/
theorem top_of_units {n : Type*} [Fintype n] [DecidableEq n]
    {A : Subalgebra ℂ (Matrix n n ℂ)}
    (h : ∀ i j : n, Matrix.single i j (1 : ℂ) ∈ A) : A = ⊤ := by
  rw [eq_top_iff]
  intro X _
  rw [Matrix.matrix_eq_sum_single X]
  refine A.sum_mem fun i _ => A.sum_mem fun j _ => ?_
  have hX : Matrix.single i j (X i j) = X i j • Matrix.single i j 1 := by
    rw [Matrix.smul_single, smul_eq_mul, mul_one]
  rw [hX]
  exact A.smul_mem (h i j) _

/-- The rank-one product rule `|a⟩⟨b| · |c⟩⟨d| = ⟨b, c⟩ · |a⟩⟨d|`. -/
theorem vecMulVec_mul (a b c d : Fin 2 → ℂ) :
    Matrix.vecMulVec a (star b) * Matrix.vecMulVec c (star d)
      = (∑ m, star (b m) * c m) • Matrix.vecMulVec a (star d) := by
  ext k l
  rw [Matrix.mul_apply, Matrix.smul_apply]
  simp only [Matrix.vecMulVec_apply, Pi.star_apply, smul_eq_mul]
  calc ∑ m, a k * star (b m) * (c m * star (d l))
      = ∑ m, star (b m) * c m * (a k * star (d l)) :=
        Finset.sum_congr rfl fun m _ => by ring
    _ = (∑ m, star (b m) * c m) * (a k * star (d l)) :=
        (Finset.sum_mul _ _ _).symm

/-- **The SM.0n weak-reset generation**: the algebra generated by the rank-one
carriers of two independent, non-orthogonal lines of `ℂ²` is all of `M₂(ℂ)`. -/
theorem two_lines_generate (t h : Fin 2 → ℂ)
    (hd : t 0 * h 1 - t 1 * h 0 ≠ 0)
    (hover : (∑ m, star (t m) * h m) ≠ 0) :
    Algebra.adjoin ℂ
      {Matrix.vecMulVec t (star t), Matrix.vecMulVec h (star h)} = ⊤ := by
  set A := Algebra.adjoin ℂ
    {Matrix.vecMulVec t (star t), Matrix.vecMulVec h (star h)} with hA
  have hP : Matrix.vecMulVec t (star t) ∈ A :=
    Algebra.subset_adjoin (Set.mem_insert _ _)
  have hQ : Matrix.vecMulVec h (star h) ∈ A :=
    Algebra.subset_adjoin (Set.mem_insert_of_mem _ rfl)
  have hoverH : (∑ m, star (h m) * t m) ≠ 0 := by
    intro hc
    apply hover
    have hstar : (∑ m, star (t m) * h m) = star (∑ m, star (h m) * t m) := by
      rw [star_sum]
      exact Finset.sum_congr rfl fun m _ => by
        rw [star_mul, star_star]
    rw [hstar, hc, star_zero]
  -- the four line-to-line rank-one maps
  have hTth : Matrix.vecMulVec t (star h) ∈ A := by
    have h1 := mul_mem hP hQ
    rw [vecMulVec_mul] at h1
    have h2 := A.smul_mem h1 (∑ m, star (t m) * h m)⁻¹
    rwa [smul_smul, inv_mul_cancel₀ hover, one_smul] at h2
  have hTht : Matrix.vecMulVec h (star t) ∈ A := by
    have h1 := mul_mem hQ hP
    rw [vecMulVec_mul] at h1
    have h2 := A.smul_mem h1 (∑ m, star (h m) * t m)⁻¹
    rwa [smul_smul, inv_mul_cancel₀ hoverH, one_smul] at h2
  -- basis-expansion coefficients
  set dd : ℂ := t 0 * h 1 - t 1 * h 0 with hdd
  set cT : Fin 2 → ℂ := ![h 1 / dd, -h 0 / dd] with hcT
  set cH : Fin 2 → ℂ := ![-(t 1) / dd, t 0 / dd] with hcH
  have he00 : h 1 / dd * t 0 + -t 1 / dd * h 0 = 1 := by
    field_simp
    rw [hdd]
    ring
  have he01 : h 1 / dd * t 1 + -t 1 / dd * h 1 = 0 := by
    field_simp
    ring
  have he10 : -h 0 / dd * t 0 + t 0 / dd * h 0 = 0 := by
    field_simp
    ring
  have he11 : -h 0 / dd * t 1 + t 0 / dd * h 1 = 1 := by
    field_simp
    rw [hdd]
    ring
  have hexp : ∀ i k : Fin 2, cT i * t k + cH i * h k
      = if i = k then 1 else 0 := by
    intro i k
    fin_cases i <;> fin_cases k
    · simpa [hcT, hcH] using he00
    · simpa [hcT, hcH] using he01
    · simpa [hcT, hcH] using he10
    · simpa [hcT, hcH] using he11
  -- every matrix unit is a combination of the four rank-one maps
  have hsingle : ∀ i j : Fin 2, Matrix.single i j (1 : ℂ) ∈ A := by
    intro i j
    have hexpand : Matrix.single i j (1 : ℂ)
        = (cT i * star (cT j)) • Matrix.vecMulVec t (star t)
          + (cT i * star (cH j)) • Matrix.vecMulVec t (star h)
          + (cH i * star (cT j)) • Matrix.vecMulVec h (star t)
          + (cH i * star (cH j)) • Matrix.vecMulVec h (star h) := by
      ext k l
      simp only [Matrix.add_apply, Matrix.smul_apply, Matrix.vecMulVec_apply,
        Pi.star_apply, smul_eq_mul, Matrix.single_apply]
      have h1 := hexp i k
      have h2 := hexp j l
      calc (if i = k ∧ j = l then (1 : ℂ) else 0)
          = (if i = k then (1 : ℂ) else 0) * star (if j = l then (1 : ℂ) else 0) := by
            by_cases hik : i = k <;> by_cases hjl : j = l <;>
              simp [hik, hjl]
        _ = (cT i * t k + cH i * h k) * star (cT j * t l + cH j * h l) := by
            rw [h1, h2]
        _ = cT i * star (cT j) * (t k * star (t l))
              + cT i * star (cH j) * (t k * star (h l))
              + cH i * star (cT j) * (h k * star (t l))
              + cH i * star (cH j) * (h k * star (h l)) := by
            rw [star_add, star_mul, star_mul]
            ring
    rw [hexpand]
    exact add_mem (add_mem (add_mem (A.smul_mem hP _) (A.smul_mem hTth _))
      (A.smul_mem hTht _)) (A.smul_mem hQ _)
  exact top_of_units hsingle

end WeakReset
end NCG
