/-
Copyright (c) 2026 Aurélien Pélissier. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Aurélien Pélissier
-/
import NCG.Algebra.ProjectiveDefect

/-!
# Internal holonomy and the spatial commutator block

The spatial–spatial block of the modular form is generated by coherent
internal transport:

* **Definition `def:coherent-internal-holonomy`** — the internally
  dressed revision `R^int_α = S̃_α ⊗ U_α`, modelled as the pair
  `(S̃_α, U_α)` in the product group; commutators compute componentwise
  (`NCG.prod_commutator`);
* **Theorem `thm:nonabelian-holonomy-spatial-entry`** — the dressed
  commutator factorises: with the flat base commutator trivial
  (`prop:flat-spatial-block-zero`), the total scalar commutator is the
  internal one (`NCG.dressed_commutator`); an internal `−1` produces
  `ω(α,β) = 1`;
* **Theorem `thm:nonabelian-holonomy-necessary` (i),(ii)** — abelian
  internal transport gives a vanishing spatial block, so a nonzero
  block forces noncommuting recurrent transport
  (`NCG.abelian_transport_trivial_block`,
  `NCG.noncomm_of_nontrivial_block`);  the `2^m` representation bound
  (iii) is not formalised;
* **Lemma `lem:spatial-omega-gauge-invariant`** — the commutator
  bicharacter is invariant under scalar regauging
  `U_α ↦ μ(α)U_α` by central scalars
  (`NCG.commutator_central_regauge`). -/

namespace NCG

open scoped commutatorElement

variable {G G' : Type*} [Group G] [Group G']

/-- Commutators in a product group compute componentwise
(Definition `def:coherent-internal-holonomy`: the dressed revision is
the pair `(S̃_α, U_α)`). -/
theorem prod_commutator (a c : G) (b d : G') :
    ⁅((a, b) : G × G'), (c, d)⁆ = (⁅a, c⁆, ⁅b, d⁆) := rfl

/-- **Theorem `thm:nonabelian-holonomy-spatial-entry`**
(factorisation): when the flat base commutator is trivial
(`prop:flat-spatial-block-zero`), the commutator of the dressed
revisions is carried entirely by the internal holonomy — an internal
group commutator `−1` therefore realises `ω(α,β) = 1`. -/
theorem dressed_commutator (S S' : G) (hflat : Commute S S')
    (U U' : G') :
    ⁅((S, U) : G × G'), (S', U')⁆ = (1, ⁅U, U'⁆) := by
  rw [prod_commutator,
    commutatorElement_eq_one_iff_commute.mpr hflat]

/-- **Theorem `thm:nonabelian-holonomy-necessary` (i)**: abelian
internal transport gives a trivial dressed commutator — the spatial
block vanishes. -/
theorem abelian_transport_trivial_block (S S' : G)
    (hflat : Commute S S') (U U' : G') (hU : Commute U U') :
    ⁅((S, U) : G × G'), (S', U')⁆ = 1 := by
  rw [dressed_commutator S S' hflat,
    commutatorElement_eq_one_iff_commute.mpr hU]
  rfl

/-- **Theorem `thm:nonabelian-holonomy-necessary` (ii)**: a nontrivial
spatial entry forces noncommuting internal transport in every gauge. -/
theorem noncomm_of_nontrivial_block (S S' : G) (hflat : Commute S S')
    (U U' : G')
    (h : ⁅((S, U) : G × G'), (S', U')⁆ ≠ 1) : ¬Commute U U' :=
  fun hU => h (abelian_transport_trivial_block S S' hflat U U' hU)

/-- Right-slot version of central-multiplication invariance. -/
theorem commutatorElement_mul_central {z a b : G}
    (hz : z ∈ Subgroup.center G) : ⁅a, z * b⁆ = ⁅a, b⁆ := by
  have h1 : ⁅z * b, a⁆ = ⁅b, a⁆ := commutatorElement_central_mul hz
  calc ⁅a, z * b⁆ = ⁅z * b, a⁆⁻¹ := (commutatorElement_inv _ _).symm
    _ = ⁅b, a⁆⁻¹ := by rw [h1]
    _ = ⁅a, b⁆ := commutatorElement_inv _ _

/-- **Lemma `lem:spatial-omega-gauge-invariant`**: the commutator
bicharacter of the internal transports is invariant under scalar
regauging `U_α ↦ μ(α)·U_α` by central scalars — it depends only on the
projective cohomology class of the multiplier. -/
theorem commutator_central_regauge {μα μβ a b : G}
    (hα : μα ∈ Subgroup.center G) (hβ : μβ ∈ Subgroup.center G) :
    ⁅μα * a, μβ * b⁆ = ⁅a, b⁆ := by
  rw [commutatorElement_central_mul hα,
    commutatorElement_mul_central hβ]

end NCG
